agent.c
agent_failed
static size_t atomicio(struct ssh_agent_struct *agent, void *buf, size_t n, int do_read)
References ssh_agent_struct::channel, ssh_pollfd_struct::events, ssh_pollfd_struct::fd, POLLIN, POLLOUT, ssh_agent_struct::sock, SSH_AGAIN, ssh_channel_read, ssh_channel_write, SSH_ERROR, ssh_poll, ssh_socket_get_fd.
Referenced by agent_talk.
ssh_agent ssh_agent_new(struct ssh_session_struct *session)
Create a new ssh agent structure.
An allocated ssh agent structure or NULL on error.
References ssh_agent_struct::channel, ssh_agent_struct::count, SAFE_FREE, session, ssh_agent_struct::sock, ssh_socket_new, ZERO_STRUCTP.
Referenced by ssh_new.
static void agent_set_channel(struct ssh_agent_struct *agent, ssh_channel channel)
References ssh_agent_struct::channel.
Referenced by ssh_set_agent_channel.
int ssh_set_agent_channel(ssh_session session, ssh_channel channel)
sets the SSH agent channel. The SSH agent channel will be used to authenticate this client using an agent through a channel, from another session. The most likely use is to implement SSH Agent forwarding into a SSH proxy.
channel a SSH channel from another session. SSH_OK in case of success SSH_ERROR in case of an error
References ssh_session_struct::agent, agent_set_channel, session, SSH_ERROR, SSH_OK, SSH_REQUEST_DENIED, ssh_set_error.
int ssh_set_agent_socket(ssh_session session, socket_t fd)
sets the SSH agent socket. The SSH agent will be used to authenticate this client using the given socket to communicate with the ssh-agent. The caller is responsible for connecting to the socket prior to calling this function.
SSH_OK in case of success SSH_ERROR in case of an error
References ssh_session_struct::agent, session, ssh_agent_struct::sock, SSH_ERROR, SSH_OK, SSH_REQUEST_DENIED, ssh_set_error, ssh_socket_set_fd.
void ssh_agent_close(struct ssh_agent_struct *agent)
References ssh_agent_struct::sock, ssh_socket_close.
Referenced by ssh_agent_free.
void ssh_agent_free(ssh_agent agent)
References ssh_agent_struct::ident, SAFE_FREE, ssh_agent_struct::sock, ssh_agent_close, SSH_BUFFER_FREE, ssh_socket_free.
static int agent_connect(ssh_session session)
References ssh_session_struct::agent, ssh_agent_struct::channel, session, ssh_agent_struct::sock, ssh_socket_unix.
Referenced by ssh_agent_is_running.
static int agent_talk(struct ssh_session_struct *session, struct ssh_buffer_struct *request, struct ssh_buffer_struct *reply)
References ssh_session_struct::agent, atomicio, PULL_BE_U32, PUSH_BE_U32, session, ssh_buffer_add_data, ssh_buffer_get, ssh_buffer_get_len, SSH_FATAL, SSH_LOG, SSH_LOG_TRACE, SSH_LOG_WARN, ssh_set_error.
Referenced by ssh_agent_get_ident_count, ssh_agent_sign_data.
uint32_t ssh_agent_get_ident_count(struct ssh_session_struct *session)
References ssh_session_struct::agent, agent_failed, agent_talk, bswap_32, ssh_agent_struct::count, ssh_agent_struct::ident, rc, session, SSH2_AGENT_IDENTITIES_ANSWER, SSH2_AGENTC_REQUEST_IDENTITIES, ssh_buffer_add_u8, SSH_BUFFER_FREE, ssh_buffer_get_u32, ssh_buffer_get_u8, ssh_buffer_new, ssh_buffer_reinit, SSH_FATAL, SSH_LOG, SSH_LOG_DEBUG, SSH_LOG_WARN, ssh_set_error, ssh_set_error_oom.
Referenced by ssh_agent_get_first_ident.
ssh_key ssh_agent_get_first_ident(struct ssh_session_struct *session, char **comment)
References session, ssh_agent_get_ident_count, ssh_agent_get_next_ident.
Referenced by ssh_userauth_agent.
ssh_key ssh_agent_get_next_ident(struct ssh_session_struct *session, char **comment)
References ssh_session_struct::agent, ssh_agent_struct::count, ssh_agent_struct::ident, key, rc, session, ssh_buffer_get_ssh_string, SSH_ERROR, ssh_pki_import_cert_blob, ssh_pki_import_pubkey_blob, SSH_STRING_FREE, ssh_string_to_char.
Referenced by ssh_agent_get_first_ident, ssh_userauth_agent.
int ssh_agent_is_running(ssh_session session)
References ssh_session_struct::agent, agent_connect, session, ssh_agent_struct::sock, ssh_socket_is_open.
ssh_string ssh_agent_sign_data(ssh_session session, const ssh_key pubkey, struct ssh_buffer_struct *data)
References agent_failed, agent_talk, bswap_32, ssh_string_struct::data, ssh_session_struct::extensions, pubkey, rc, session, SSH2_AGENT_SIGN_RESPONSE, SSH2_AGENTC_SIGN_REQUEST, SSH_AGENT_RSA_SHA2_256, SSH_AGENT_RSA_SHA2_512, ssh_buffer_add_data, ssh_buffer_add_ssh_string, ssh_buffer_add_u32, ssh_buffer_add_u8, ssh_buffer_allocate_size, SSH_BUFFER_FREE, ssh_buffer_get, ssh_buffer_get_len, ssh_buffer_get_ssh_string, ssh_buffer_get_u8, ssh_buffer_new, SSH_EXT_SIG_RSA_SHA256, SSH_EXT_SIG_RSA_SHA512, SSH_FATAL, ssh_key_type_plain, SSH_KEYTYPE_RSA, SSH_LOG, SSH_LOG_WARN, ssh_pki_export_pubkey_blob, ssh_set_error, SSH_STRING_FREE, ssh_string_len.
Referenced by ssh_pki_do_sign_agent.