agent.h
SSH_AGENTC_REQUEST_RSA_IDENTITIES
SSH_AGENT_RSA_IDENTITIES_ANSWER
SSH_AGENTC_RSA_CHALLENGE
SSH_AGENT_RSA_RESPONSE
SSH_AGENT_FAILURE
SSH_AGENT_SUCCESS
SSH_AGENTC_ADD_RSA_IDENTITY
SSH_AGENTC_REMOVE_RSA_IDENTITY
SSH_AGENTC_REMOVE_ALL_RSA_IDENTITIES
SSH2_AGENTC_REQUEST_IDENTITIES
SSH2_AGENT_IDENTITIES_ANSWER
SSH2_AGENTC_SIGN_REQUEST
SSH2_AGENT_SIGN_RESPONSE
SSH2_AGENTC_ADD_IDENTITY
SSH2_AGENTC_REMOVE_IDENTITY
SSH2_AGENTC_REMOVE_ALL_IDENTITIES
SSH_AGENTC_ADD_SMARTCARD_KEY
SSH_AGENTC_REMOVE_SMARTCARD_KEY
SSH_AGENTC_LOCK
SSH_AGENTC_UNLOCK
SSH_AGENTC_ADD_RSA_ID_CONSTRAINED
SSH2_AGENTC_ADD_ID_CONSTRAINED
SSH_AGENTC_ADD_SMARTCARD_KEY_CONSTRAINED
SSH_AGENT_CONSTRAIN_LIFETIME
SSH_AGENT_CONSTRAIN_CONFIRM
SSH2_AGENT_FAILURE
SSH_COM_AGENT2_FAILURE
SSH_AGENT_OLD_SIGNATURE
SSH_AGENT_RSA_SHA2_256
SSH_AGENT_RSA_SHA2_512
struct ssh_agent_struct* ssh_agent_new(struct ssh_session_struct *session)
Create a new ssh agent structure.
An allocated ssh agent structure or NULL on error.
References ssh_agent_struct::channel, ssh_agent_struct::count, SAFE_FREE, session, ssh_agent_struct::sock, ssh_socket_new, ZERO_STRUCTP.
Referenced by ssh_new.
void ssh_agent_close(struct ssh_agent_struct *agent)
References ssh_agent_struct::sock, ssh_socket_close.
Referenced by ssh_agent_free.
void ssh_agent_free(struct ssh_agent_struct *agent)
Free an allocated ssh agent structure.
agent The ssh agent structure to free.
Referenced by ssh_free.
int ssh_agent_is_running(struct ssh_session_struct *session)
Check if the ssh agent is running.
session The ssh session to check for the agent. 1 if it is running, 0 if not.
Referenced by ssh_userauth_agent, torture_auth_agent, torture_auth_agent_nonblocking.
uint32_t ssh_agent_get_ident_count(struct ssh_session_struct *session)
References ssh_session_struct::agent, agent_failed, agent_talk, bswap_32, ssh_agent_struct::count, ssh_agent_struct::ident, rc, session, SSH2_AGENT_IDENTITIES_ANSWER, SSH2_AGENTC_REQUEST_IDENTITIES, ssh_buffer_add_u8, SSH_BUFFER_FREE, ssh_buffer_get_u32, ssh_buffer_get_u8, ssh_buffer_new, ssh_buffer_reinit, SSH_FATAL, SSH_LOG, SSH_LOG_DEBUG, SSH_LOG_WARN, ssh_set_error, ssh_set_error_oom.
Referenced by ssh_agent_get_first_ident.
ssh_key ssh_agent_get_next_ident(struct ssh_session_struct *session, char **comment)
References ssh_session_struct::agent, ssh_agent_struct::count, ssh_agent_struct::ident, key, rc, session, ssh_buffer_get_ssh_string, SSH_ERROR, ssh_pki_import_cert_blob, ssh_pki_import_pubkey_blob, SSH_STRING_FREE, ssh_string_to_char.
Referenced by ssh_agent_get_first_ident, ssh_userauth_agent.
ssh_key ssh_agent_get_first_ident(struct ssh_session_struct *session, char **comment)
References session, ssh_agent_get_ident_count, ssh_agent_get_next_ident.
Referenced by ssh_userauth_agent.
ssh_string ssh_agent_sign_data(ssh_session session, const ssh_key pubkey, struct ssh_buffer_struct *data)
References agent_failed, agent_talk, bswap_32, ssh_string_struct::data, ssh_session_struct::extensions, pubkey, rc, session, SSH2_AGENT_SIGN_RESPONSE, SSH2_AGENTC_SIGN_REQUEST, SSH_AGENT_RSA_SHA2_256, SSH_AGENT_RSA_SHA2_512, ssh_buffer_add_data, ssh_buffer_add_ssh_string, ssh_buffer_add_u32, ssh_buffer_add_u8, ssh_buffer_allocate_size, SSH_BUFFER_FREE, ssh_buffer_get, ssh_buffer_get_len, ssh_buffer_get_ssh_string, ssh_buffer_get_u8, ssh_buffer_new, SSH_EXT_SIG_RSA_SHA256, SSH_EXT_SIG_RSA_SHA512, SSH_FATAL, ssh_key_type_plain, SSH_KEYTYPE_RSA, SSH_LOG, SSH_LOG_WARN, ssh_pki_export_pubkey_blob, ssh_set_error, SSH_STRING_FREE, ssh_string_len.
Referenced by ssh_pki_do_sign_agent.