auth.h
ssh_auth_state_e
No authentication asked
ssh_auth_service_state_e
initial state
typedef struct ssh_kbdint_struct* ssh_kbdint
SSH_PACKET_CALLBACK(ssh_packet_userauth_banner)
References ssh_session_struct::banner, session, ssh_buffer_get_ssh_string, SSH_LOG, SSH_LOG_DEBUG, SSH_LOG_WARN, SSH_PACKET_USED, SSH_STRING_FREE, user.
SSH_PACKET_CALLBACK(ssh_packet_userauth_failure)
References ssh_session_struct::auth, ssh_session_struct::current_method, rc, SAFE_FREE, session, ssh_auth_get_current_method, SSH_AUTH_METHOD_GSSAPI_MIC, SSH_AUTH_METHOD_HOSTBASED, SSH_AUTH_METHOD_INTERACTIVE, SSH_AUTH_METHOD_PASSWORD, SSH_AUTH_METHOD_PUBLICKEY, SSH_AUTH_METHOD_UNKNOWN, SSH_AUTH_STATE_ERROR, SSH_AUTH_STATE_FAILED, SSH_AUTH_STATE_PARTIAL, ssh_buffer_unpack, SSH_FATAL, ssh_get_error, SSH_LOG, SSH_LOG_INFO, SSH_OK, SSH_PACKET_USED, SSH_REQUEST_DENIED, ssh_set_error, ssh_session_struct::state, ssh_session_struct::supported_methods, user.
SSH_PACKET_CALLBACK(ssh_packet_userauth_success)
References ssh_session_struct::auth, ssh_session_struct::current_method, ssh_crypto_struct::delayed_compress_in, ssh_crypto_struct::delayed_compress_out, ssh_crypto_struct::do_compress_in, ssh_crypto_struct::do_compress_out, ssh_session_struct::flags, session, ssh_session_struct::session_state, SSH_AUTH_METHOD_UNKNOWN, SSH_AUTH_STATE_SUCCESS, SSH_DIRECTION_IN, SSH_DIRECTION_OUT, SSH_LOG, SSH_LOG_DEBUG, SSH_LOG_TRACE, ssh_packet_get_current_crypto, SSH_PACKET_USED, ssh_reset_error, SSH_SESSION_FLAG_AUTHENTICATED, SSH_SESSION_STATE_AUTHENTICATED, ssh_session_struct::state, user.
SSH_PACKET_CALLBACK(ssh_packet_userauth_pk_ok)
References ssh_session_struct::auth, rc, session, SSH_AUTH_STATE_ERROR, SSH_AUTH_STATE_GSSAPI_REQUEST_SENT, SSH_AUTH_STATE_KBDINT_SENT, SSH_AUTH_STATE_PK_OK, SSH_AUTH_STATE_PUBKEY_OFFER_SENT, SSH_LOG, SSH_LOG_TRACE, SSH_PACKET_USED, ssh_session_struct::state, user.
SSH_PACKET_CALLBACK(ssh_packet_userauth_info_request)
References ssh_session_struct::auth, ssh_kbdint_struct::echo, ssh_kbdint_struct::instruction, ssh_session_struct::kbdint, KBDINT_MAX_PROMPT, ssh_kbdint_struct::name, ssh_kbdint_struct::nanswers, ssh_kbdint_struct::nprompts, ssh_kbdint_struct::prompts, rc, session, SSH_AUTH_STATE_INFO, ssh_buffer_unpack, SSH_ERROR, SSH_FATAL, ssh_kbdint_clean, ssh_kbdint_free, ssh_kbdint_new, SSH_LOG, SSH_LOG_DEBUG, SSH_OK, SSH_PACKET_USED, ssh_set_error, ssh_set_error_oom, SSH_STRING_FREE, ssh_session_struct::state, user.
SSH_PACKET_CALLBACK(ssh_packet_userauth_info_response)
References session, SSH_PACKET_USED, user.
ssh_kbdint ssh_kbdint_new(void)
Referenced by ssh_message_auth_interactive_request, SSH_PACKET_CALLBACK.
void ssh_kbdint_clean(ssh_kbdint kbd)
References ssh_kbdint_struct::answers, ssh_kbdint_struct::echo, explicit_bzero, ssh_kbdint_struct::instruction, ssh_kbdint_struct::name, ssh_kbdint_struct::nanswers, ssh_kbdint_struct::nprompts, ssh_kbdint_struct::prompts, SAFE_FREE.
Referenced by ssh_message_auth_interactive_request, SSH_PACKET_CALLBACK.
void ssh_kbdint_free(ssh_kbdint kbd)
References ssh_kbdint_struct::answers, ssh_kbdint_struct::echo, explicit_bzero, ssh_kbdint_struct::instruction, ssh_kbdint_struct::name, ssh_kbdint_struct::nanswers, ssh_kbdint_struct::nprompts, ssh_kbdint_struct::prompts, SAFE_FREE.
Referenced by ssh_free, ssh_message_auth_interactive_request, SSH_PACKET_CALLBACK, ssh_userauth_kbdint_send.