base64.c
SET_A
SET_B
SET_C
SET_D
GET_A
GET_B
GET_C
BLOCK
BITS
const uint8_t alphabet[][]
Referenced by _bin_to_base64.
static int _base64_to_bin(unsigned char dest[3], const char *source, int num)
References GET_A, GET_B, GET_C, to_block4.
Referenced by base64_to_bin.
static int get_equals(char *string)
Referenced by base64_to_bin.
ssh_buffer base64_to_bin(const char *source)
References _base64_to_bin, buffer, error, get_equals, SAFE_FREE, ssh_buffer_add_data, SSH_BUFFER_FREE, ssh_buffer_new, ssh_buffer_set_secure.
Referenced by check_public_key, match_hashed_host, match_hashed_hostname, ssh_pki_import_pubkey_base64, ssh_pki_openssh_import.
static int to_block4(unsigned long *block, const char *source, int num)
References BLOCK.
Referenced by _base64_to_bin.
static void _bin_to_base64(uint8_t *dest, const uint8_t source[3], size_t len)
References alphabet, BITS.
Referenced by bin_to_base64.
uint8_t* bin_to_base64(const uint8_t *source, size_t len)
References _bin_to_base64.
Referenced by ssh_get_b64_unpadded, ssh_pki_export_pubkey_base64, ssh_pki_openssh_privkey_export, ssh_publickey_to_file.