bind_config.c
MAX_LINE_SIZE
PARSING
IN_MATCH
ssh_bind_config_match_e
struct ssh_bind_config_keyword_table_s ssh_bind_config_keyword_table[][]
struct ssh_bind_config_match_keyword_table_s ssh_bind_config_match_keyword_table[][]
static enum ssh_bind_config_opcode_e ssh_bind_config_get_opcode(char *keyword, uint32_t *parser_flags)
Referenced by ssh_bind_config_parse_line.
static int ssh_bind_config_parse_line(ssh_bind bind, const char *line, unsigned int count, uint32_t *parser_flags, uint8_t *seen)
References BIND_CFG_CIPHERS, BIND_CFG_HOSTKEY, BIND_CFG_HOSTKEY_ALGORITHMS, BIND_CFG_INCLUDE, BIND_CFG_KEXALGORITHMS, BIND_CFG_LISTENADDRESS, BIND_CFG_LOGLEVEL, BIND_CFG_MACS, BIND_CFG_MATCH, BIND_CFG_MAX, BIND_CFG_NA, BIND_CFG_NOT_ALLOWED_IN_MATCH, BIND_CFG_PORT, BIND_CFG_PUBKEY_ACCEPTED_KEY_TYPES, BIND_CFG_UNKNOWN, BIND_CFG_UNSUPPORTED, BIND_MATCH_ADDRESS, BIND_MATCH_ALL, BIND_MATCH_GROUP, BIND_MATCH_HOST, BIND_MATCH_LOCALADDRESS, BIND_MATCH_LOCALPORT, BIND_MATCH_RDOMAIN, BIND_MATCH_UNKNOWN, BIND_MATCH_USER, IN_MATCH, local_parse_file, ssh_bind_config_match_keyword_table_s::opcode, PARSING, rc, s, SAFE_FREE, ssh_bind_config_get_match_opcode, ssh_bind_config_get_opcode, SSH_BIND_OPTIONS_BINDADDR, SSH_BIND_OPTIONS_BINDPORT_STR, SSH_BIND_OPTIONS_CIPHERS_C_S, SSH_BIND_OPTIONS_CIPHERS_S_C, SSH_BIND_OPTIONS_HMAC_C_S, SSH_BIND_OPTIONS_HMAC_S_C, SSH_BIND_OPTIONS_HOSTKEY, SSH_BIND_OPTIONS_HOSTKEY_ALGORITHMS, SSH_BIND_OPTIONS_KEY_EXCHANGE, SSH_BIND_OPTIONS_LOG_VERBOSITY, SSH_BIND_OPTIONS_PUBKEY_ACCEPTED_KEY_TYPES, ssh_bind_options_set, ssh_config_get_str_tok, ssh_config_get_token, SSH_FATAL, SSH_LOG, SSH_LOG_DEBUG, SSH_LOG_INFO, SSH_LOG_NONE, SSH_LOG_TRACE, SSH_LOG_WARN, ssh_set_error, ssh_set_error_invalid, ssh_set_error_oom.
Referenced by local_parse_file, ssh_bind_config_parse_file.
static void local_parse_file(ssh_bind bind, const char *filename, uint32_t *parser_flags, uint8_t *seen)
References MAX_LINE_SIZE, ssh_bind_config_parse_line, SSH_LOG, SSH_LOG_PACKET, SSH_LOG_RARE.
Referenced by ssh_bind_config_parse_line.
static enum ssh_bind_config_match_e ssh_bind_config_get_match_opcode(const char *keyword)
Referenced by ssh_bind_config_parse_line.
int ssh_bind_config_parse_file(ssh_bind bind, const char *filename)
References BIND_CFG_MAX, MAX_LINE_SIZE, PARSING, ssh_bind_config_parse_line, SSH_LOG, SSH_LOG_PACKET.
Referenced by torture_bind_config_ciphers, torture_bind_config_corner_cases, torture_bind_config_full, torture_bind_config_hostkey, torture_bind_config_hostkey_algorithms, torture_bind_config_hostkey_separately, torture_bind_config_hostkey_twice_rec, torture_bind_config_include, torture_bind_config_include_recursive, torture_bind_config_kexalgorithms, torture_bind_config_listen_address, torture_bind_config_loglevel, torture_bind_config_macs, torture_bind_config_match_all, torture_bind_config_match_corner_cases, torture_bind_config_match_invalid, torture_bind_config_match_not_allowed, torture_bind_config_match_twice, torture_bind_config_match_unsupported, torture_bind_config_port, torture_bind_config_pubkey_accepted.