bind.c
SOCKOPT_TYPE_ARG4
static socket_t bind_socket(ssh_bind sshbind, const char *hostname, int port)
References CLOSE_SOCKET, port, rc, s, SSH_FATAL, SSH_INVALID_SOCKET, ssh_set_error, ZERO_STRUCT.
Referenced by ssh_bind_listen.
ssh_bind ssh_bind_new(void)
Creates a new SSH server bind.
A newly allocated ssh_bind session pointer.
References ssh_bind_struct::bindfd, ssh_bind_struct::bindport, ssh_bind_struct::common, ssh_common_struct::log_verbosity, SSH_INVALID_SOCKET.
Referenced by LLVMFuzzerTestOneInput, main, pkd_exec_hello, run_server, ssh_server, sshbind_setup.
static int ssh_bind_import_keys(ssh_bind sshbind)
References ssh_bind_struct::dsa, ssh_bind_struct::dsakey, ssh_bind_struct::ecdsa, ssh_bind_struct::ecdsakey, ssh_bind_struct::ed25519, ssh_bind_struct::ed25519key, is_ecdsa_key_type, rc, ssh_bind_struct::rsa, ssh_bind_struct::rsakey, SSH_EOF, SSH_ERROR, SSH_FATAL, ssh_key_free, ssh_key_type, SSH_KEYTYPE_DSS, SSH_KEYTYPE_ED25519, SSH_KEYTYPE_RSA, SSH_OK, ssh_pki_import_privkey_file, ssh_set_error.
Referenced by ssh_bind_accept_fd, ssh_bind_listen.
int ssh_bind_listen(ssh_bind ssh_bind_o)
Start listening to the socket.
ssh_bind_o The ssh server bind to use. 0 on success, < 0 on error.
References bind_socket, ssh_bind_struct::bindaddr, ssh_bind_struct::bindfd, ssh_bind_struct::bindport, CLOSE_SOCKET, ssh_bind_struct::dsa, ssh_bind_struct::ecdsa, ssh_bind_struct::ed25519, host, rc, ssh_bind_struct::rsa, ssh_bind_import_keys, SSH_ERROR, SSH_FATAL, SSH_INVALID_SOCKET, ssh_key_free, SSH_LOG, SSH_LOG_INFO, SSH_OK, ssh_set_error.
Referenced by main, run_server.
int ssh_bind_set_callbacks(ssh_bind sshbind, ssh_bind_callbacks callbacks, void *userdata)
Set the callback for this bind.
sshbind The bind to set the callback on. callbacks An already set up ssh_bind_callbacks instance. userdata A pointer to private data to pass to the callbacks. SSH_OK on success, SSH_ERROR if an error occured. structssh_callbacks_structcb={ .userdata=data, .auth_function=my_auth_function }; ssh_callbacks_init(&cb); ssh_bind_set_callbacks(session,&cb);
References ssh_bind_struct::bind_callbacks, ssh_bind_struct::bind_callbacks_userdata, callbacks, SSH_ERROR, SSH_FATAL, ssh_set_error, ssh_set_error_invalid.
static int ssh_bind_poll_callback(ssh_poll_handle sshpoll, socket_t fd, int revents, void *user)
References ssh_bind_struct::bind_callbacks, ssh_bind_struct::bind_callbacks_userdata, ssh_bind_callbacks_struct::incoming_connection, POLLIN, ssh_callbacks_exists, user.
Referenced by ssh_bind_get_poll.
ssh_poll_handle ssh_bind_get_poll(ssh_bind sshbind)
References ssh_bind_struct::bindfd, ssh_bind_struct::poll, POLLIN, ssh_bind_poll_callback, ssh_poll_new.
void ssh_bind_set_blocking(ssh_bind ssh_bind_o, int blocking)
Set the session to blocking/nonblocking mode.
ssh_bind_o The ssh server bind to use. blocking Zero for nonblocking mode.
References ssh_bind_struct::blocking.
socket_t ssh_bind_get_fd(ssh_bind ssh_bind_o)
Recover the file descriptor from the session.
ssh_bind_o The ssh server bind to get the fd from. The file descriptor.
References ssh_bind_struct::bindfd.
void ssh_bind_set_fd(ssh_bind ssh_bind_o, socket_t fd)
Set the file descriptor for a session.
ssh_bind_o The ssh server bind to set the fd. fd The file descriptssh_bind B
References ssh_bind_struct::bindfd.
void ssh_bind_fd_toaccept(ssh_bind ssh_bind_o)
Allow the file descriptor to accept new sessions.
ssh_bind_o The ssh server bind to use.
References ssh_bind_struct::toaccept.
void ssh_bind_free(ssh_bind ssh_bind_o)
Free a ssh servers bind.
ssh_bind_o The ssh server bind to free.
References ssh_bind_struct::banner, ssh_bind_struct::bindaddr, ssh_bind_struct::bindfd, CLOSE_SOCKET, ssh_bind_struct::config_dir, ssh_bind_struct::dsa, ssh_bind_struct::dsakey, ssh_bind_struct::ecdsa, ssh_bind_struct::ecdsakey, ssh_bind_struct::ed25519, ssh_bind_struct::ed25519key, ssh_bind_struct::pubkey_accepted_key_types, ssh_bind_struct::rsa, ssh_bind_struct::rsakey, SAFE_FREE, SSH_INVALID_SOCKET, SSH_KEX_METHODS, ssh_key_free, ssh_bind_struct::wanted_methods.
Referenced by LLVMFuzzerTestOneInput, main, pkd_exec_hello, run_server, sshbind_teardown, test_ssh_channel_request_x11.
int ssh_bind_accept_fd(ssh_bind ssh_bind_o, ssh_session session, socket_t fd)
Accept an incoming ssh connection on the given file descriptor and initialize the session.
ssh_bind_o The ssh server bind to accept a connection. session A preallocated ssh session fd A file descriptor of an already established TCP inbound connection ssh_new ssh_bind_accept SSH_OK when a connection is established
References ssh_bind_struct::banner, ssh_bind_struct::bindaddr, ssh_session_struct::bindaddr, ssh_bind_struct::common, ssh_session_struct::common, ssh_session_struct::custombanner, ssh_bind_struct::dsa, ssh_session_struct::dsa_key, ssh_bind_struct::ecdsa, ssh_session_struct::ecdsa_key, ssh_bind_struct::ed25519, ssh_session_struct::ed25519_key, ssh_common_struct::log_verbosity, ssh_session_struct::opts, ssh_bind_struct::pubkey_accepted_key_types, ssh_session_struct::pubkey_accepted_types, rc, ssh_bind_struct::rsa, ssh_session_struct::rsa_key, SAFE_FREE, ssh_session_struct::server, session, ssh_session_struct::socket, ssh_session_struct::srv, ssh_bind_import_keys, ssh_bind_options_parse_config, SSH_ERROR, SSH_FATAL, ssh_find_all_matching, SSH_KEX_METHODS, ssh_key_dup, SSH_OK, ssh_reseed, ssh_set_error, ssh_set_error_oom, ssh_socket_free, ssh_socket_get_poll_handle, ssh_socket_new, ssh_socket_set_fd, ssh_bind_struct::wanted_methods, ssh_session_struct::wanted_methods.
Referenced by LLVMFuzzerTestOneInput, pkd_exec_hello, ssh_bind_accept, ssh_server.
int ssh_bind_accept(ssh_bind ssh_bind_o, ssh_session session)
Accept an incoming ssh connection and initialize the session.
ssh_bind_o The ssh server bind to accept a connection. session A preallocated ssh session ssh_new SSH_OK when a connection is established
References ssh_bind_struct::bindfd, CLOSE_SOCKET, rc, session, ssh_session_struct::socket, ssh_bind_accept_fd, SSH_ERROR, SSH_FATAL, SSH_INVALID_SOCKET, ssh_set_error, ssh_socket_free.
Referenced by main, run_server, test_ssh_channel_request_x11.