blf.h
BLF_N
BLF_MAXKEYLEN
BLF_MAXUTILIZED
typedef struct BlowfishContext ssh_blf_ctx
void Blowfish_encipher(ssh_blf_ctx *, uint32_t *, uint32_t *)
References BLFRND, BlowfishContext::P, BlowfishContext::S, s.
Referenced by Blowfish_expand0state, Blowfish_expandstate, ssh_blf_cbc_encrypt, ssh_blf_ecb_encrypt, ssh_blf_enc.
void Blowfish_decipher(ssh_blf_ctx *, uint32_t *, uint32_t *)
References BLFRND, BlowfishContext::P, BlowfishContext::S, s.
Referenced by ssh_blf_cbc_decrypt, ssh_blf_dec, ssh_blf_ecb_decrypt.
void Blowfish_initstate(ssh_blf_ctx *)
Referenced by bcrypt_hash, ssh_blf_key.
void Blowfish_expand0state(ssh_blf_ctx *, const uint8_t *, uint16_t)
References BLF_N, Blowfish_encipher, Blowfish_stream2word, k, key, BlowfishContext::P, BlowfishContext::S.
Referenced by bcrypt_hash, ssh_blf_key.
void Blowfish_expandstate(ssh_blf_ctx *, const uint8_t *, uint16_t, const uint8_t *, uint16_t)
References BLF_N, Blowfish_encipher, Blowfish_stream2word, k, key, BlowfishContext::P, BlowfishContext::S.
Referenced by bcrypt_hash.
void ssh_blf_key(ssh_blf_ctx *, const uint8_t *, uint16_t)
References Blowfish_expand0state, Blowfish_initstate, k.
void ssh_blf_enc(ssh_blf_ctx *, uint32_t *, uint16_t)
References Blowfish_encipher.
Referenced by bcrypt_hash.
void ssh_blf_dec(ssh_blf_ctx *, uint32_t *, uint16_t)
References Blowfish_decipher.
void ssh_blf_ecb_encrypt(ssh_blf_ctx *, uint8_t *, uint32_t)
References Blowfish_encipher.
void ssh_blf_ecb_decrypt(ssh_blf_ctx *, uint8_t *, uint32_t)
References Blowfish_decipher.
void ssh_blf_cbc_encrypt(ssh_blf_ctx *, uint8_t *, uint8_t *, uint32_t)
References Blowfish_encipher, iv.
void ssh_blf_cbc_decrypt(ssh_blf_ctx *, uint8_t *, uint8_t *, uint32_t)
References Blowfish_decipher, iv.
uint32_t Blowfish_stream2word(const uint8_t *, uint16_t, uint16_t *)
Referenced by bcrypt_hash, Blowfish_expand0state, Blowfish_expandstate.