blowfish.c
inline
F
BLFRND
void Blowfish_encipher(ssh_blf_ctx *c, uint32_t *xl, uint32_t *xr)
References BLFRND, BlowfishContext::P, BlowfishContext::S, s.
Referenced by Blowfish_expand0state, Blowfish_expandstate, ssh_blf_cbc_encrypt, ssh_blf_ecb_encrypt, ssh_blf_enc.
void Blowfish_decipher(ssh_blf_ctx *c, uint32_t *xl, uint32_t *xr)
References BLFRND, BlowfishContext::P, BlowfishContext::S, s.
Referenced by ssh_blf_cbc_decrypt, ssh_blf_dec, ssh_blf_ecb_decrypt.
void Blowfish_initstate(ssh_blf_ctx *c)
Referenced by bcrypt_hash, ssh_blf_key.
uint32_t Blowfish_stream2word(const uint8_t *data, uint16_t databytes, uint16_t *current)
Referenced by bcrypt_hash, Blowfish_expand0state, Blowfish_expandstate.
void Blowfish_expand0state(ssh_blf_ctx *c, const uint8_t *key, uint16_t keybytes)
References BLF_N, Blowfish_encipher, Blowfish_stream2word, k, key, BlowfishContext::P, BlowfishContext::S.
Referenced by bcrypt_hash, ssh_blf_key.
void Blowfish_expandstate(ssh_blf_ctx *c, const uint8_t *data, uint16_t databytes, const uint8_t *key, uint16_t keybytes)
References BLF_N, Blowfish_encipher, Blowfish_stream2word, k, key, BlowfishContext::P, BlowfishContext::S.
Referenced by bcrypt_hash.
void ssh_blf_key(ssh_blf_ctx *c, const uint8_t *k, uint16_t len)
References Blowfish_expand0state, Blowfish_initstate, k.
void ssh_blf_enc(ssh_blf_ctx *c, uint32_t *data, uint16_t blocks)
References Blowfish_encipher.
Referenced by bcrypt_hash.
void ssh_blf_dec(ssh_blf_ctx *c, uint32_t *data, uint16_t blocks)
References Blowfish_decipher.
void ssh_blf_ecb_encrypt(ssh_blf_ctx *c, uint8_t *data, uint32_t len)
References Blowfish_encipher.
void ssh_blf_ecb_decrypt(ssh_blf_ctx *c, uint8_t *data, uint32_t len)
References Blowfish_decipher.
void ssh_blf_cbc_encrypt(ssh_blf_ctx *c, uint8_t *iv, uint8_t *data, uint32_t len)
References Blowfish_encipher, iv.
void ssh_blf_cbc_decrypt(ssh_blf_ctx *c, uint8_t *iva, uint8_t *data, uint32_t len)
References Blowfish_decipher, iv.