buffer.h
SSH_BUFFER_PACK_END
ssh_buffer_pack
ssh_buffer_unpack
void ssh_buffer_set_secure(ssh_buffer buffer)
Sets the buffer as secure.
A secure buffer will never leave cleartext data in the heap after being reallocated or freed. buffer buffer to set secure.
References buffer.
Referenced by base64_to_bin, setup, ssh_pki_do_sign, ssh_pki_openssh_import, ssh_userauth_password, thread_buffer_pack_badformat, thread_buffer_prepend, thread_growing_buffer, thread_growing_buffer_shifting, thread_ssh_buffer_add_format, thread_ssh_buffer_get_format, thread_ssh_buffer_get_format_error.
int ssh_buffer_add_ssh_string(ssh_buffer buffer, ssh_string string)
Referenced by pki_ecdsa_signature_to_blob, pki_import_cert_buffer, pki_publickey_to_blob, sftp_reply_handle, sftp_reply_name, sftp_reply_names_add, sftp_reply_status, ssh_agent_sign_data, ssh_gssapi_send_auth_mic, SSH_PACKET_CALLBACK, ssh_pki_do_sign_agent, ssh_pki_export_signature_blob, ssh_send_kex, ssh_userauth_agent_publickey, ssh_userauth_publickey.
int ssh_buffer_add_u8(ssh_buffer buffer, uint8_t data)
Referenced by ssh_agent_get_ident_count, ssh_agent_sign_data, ssh_auth_reply_success, ssh_hashbufin_add_cookie, ssh_hashbufout_add_cookie, ssh_make_sessionid, ssh_message_global_request_reply_default, ssh_message_global_request_reply_success, ssh_message_reply_default, SSH_PACKET_CALLBACK, ssh_pki_openssh_privkey_export.
int ssh_buffer_add_u16(ssh_buffer buffer, uint16_t data)
int ssh_buffer_add_u32(ssh_buffer buffer, uint32_t data)
Referenced by sftp_reply_attr, sftp_reply_data, sftp_reply_handle, sftp_reply_name, sftp_reply_names, sftp_reply_status, ssh_agent_sign_data, ssh_make_sessionid, ssh_message_reply_default, SSH_PACKET_CALLBACK, thread_ssh_buffer_get_ssh_string, torture_ssh_buffer_get_ssh_string.
int ssh_buffer_add_u64(ssh_buffer buffer, uint64_t data)
int ssh_buffer_validate_length(struct ssh_buffer_struct *buffer, size_t len)
Valdiates that the given length can be obtained from the buffer.
buffer The buffer to read from. len The length to be checked. SSH_OK if the length is valid, SSH_ERROR otherwise.
References buffer, ssh_buffer_struct::pos, SSH_ERROR, SSH_OK.
Referenced by ssh_buffer_get_data, ssh_buffer_get_ssh_string, ssh_buffer_unpack_va.
void* ssh_buffer_allocate(struct ssh_buffer_struct *buffer, uint32_t len)
References buffer, buffer_shift, buffer_verify, realloc_buffer.
Referenced by ssh_packet_socket_callback.
int ssh_buffer_allocate_size(struct ssh_buffer_struct *buffer, uint32_t len)
Ensure the buffer has at least a certain preallocated size.
buffer The buffer to enlarge. len The length to ensure as allocated. 0 on success, < 0 on error.
References buffer, buffer_shift, buffer_verify, realloc_buffer.
Referenced by ssh_agent_sign_data, ssh_buffer_new, ssh_buffer_pack_allocate_va, ssh_hashbufin_add_cookie, ssh_hashbufout_add_cookie.
int ssh_buffer_pack_va(struct ssh_buffer_struct *buffer, const char *format, size_t argc, va_list ap)
References buffer, ssh_string_struct::data, htonll, rc, SAFE_FREE, ssh_buffer_add_data, ssh_buffer_add_ssh_string, ssh_buffer_add_u16, ssh_buffer_add_u32, ssh_buffer_add_u64, ssh_buffer_add_u8, SSH_BUFFER_PACK_END, SSH_ERROR, SSH_LOG, SSH_LOG_WARN, ssh_make_bignum_string, SSH_OK.
Referenced by _ssh_buffer_pack.
int _ssh_buffer_pack(struct ssh_buffer_struct *buffer, const char *format, size_t argc,...)
References buffer, rc, ssh_buffer_pack_allocate_va, ssh_buffer_pack_va, SSH_ERROR, SSH_OK.
int ssh_buffer_unpack_va(struct ssh_buffer_struct *buffer, const char *format, size_t argc, va_list ap)
References buffer, explicit_bzero, ntohll, rc, SAFE_FREE, ssh_buffer_get_data, ssh_buffer_get_len, ssh_buffer_get_ssh_string, ssh_buffer_get_u32, ssh_buffer_get_u64, ssh_buffer_get_u8, SSH_BUFFER_PACK_END, ssh_buffer_validate_length, SSH_ERROR, SSH_LOG, SSH_LOG_WARN, ssh_make_string_bn, SSH_OK, ssh_string_burn, SSH_STRING_FREE.
Referenced by _ssh_buffer_unpack.
int _ssh_buffer_unpack(struct ssh_buffer_struct *buffer, const char *format, size_t argc,...)
References buffer, rc, ssh_buffer_unpack_va.
int ssh_buffer_prepend_data(ssh_buffer buffer, const void *data, uint32_t len)
Referenced by packet_send2, thread_buffer_prepend, torture_buffer_prepend.
int ssh_buffer_add_buffer(ssh_buffer buffer, ssh_buffer source)
Referenced by channel_open, pki_import_cert_buffer, pki_publickey_to_blob, ssh_pki_copy_cert_to_privkey, ssh_pki_do_sign_agent.
int ssh_buffer_get_u8(ssh_buffer buffer, uint8_t *data)
Referenced by ssh_agent_get_ident_count, ssh_agent_sign_data, SSH_PACKET_CALLBACK, ssh_packet_parse_type, ssh_packet_socket_callback, ssh_pki_openssh_import, thread_growing_buffer_shifting, torture_growing_buffer_shifting.
int ssh_buffer_get_u32(ssh_buffer buffer, uint32_t *data)
Referenced by sftp_get_client_message, ssh_agent_get_ident_count, SSH_PACKET_CALLBACK, thread_buffer_prepend, torture_buffer_prepend.
int ssh_buffer_get_u64(ssh_buffer buffer, uint64_t *data)
ssh_string ssh_buffer_get_ssh_string(ssh_buffer buffer)
Referenced by pki_import_cert_buffer, pki_import_pubkey_buffer, pki_signature_from_ecdsa_blob, sftp_get_client_message, ssh_agent_get_next_ident, ssh_agent_sign_data, SSH_PACKET_CALLBACK, ssh_pki_import_pubkey_base64, ssh_pki_import_pubkey_blob, ssh_pki_import_signature_blob, ssh_pki_openssh_import, thread_ssh_buffer_get_ssh_string, torture_ssh_buffer_get_ssh_string.
uint32_t ssh_buffer_pass_bytes_end(ssh_buffer buffer, uint32_t len)
Referenced by ssh_packet_socket_callback.
uint32_t ssh_buffer_pass_bytes(ssh_buffer buffer, uint32_t len)
Referenced by ssh_channel_read_timeout, SSH_PACKET_CALLBACK, ssh_packet_socket_callback, ssh_socket_nonblocking_flush, ssh_socket_pollcallback.