callbacks.c
is_callback_valid
static void ssh_legacy_log_callback(int priority, const char *function, const char *buffer, void *userdata)
References buffer, ssh_common_struct::callbacks, ssh_session_struct::common, ssh_callbacks_struct::log_function, session, ssh_callbacks_struct::userdata.
Referenced by ssh_set_callbacks.
int ssh_set_callbacks(ssh_session session, ssh_callbacks cb)
Set the session callback functions.
This functions sets the callback structure to use your own callback functions for auth, logging and status. Note, that the callback structure is not copied into the session so it needs to be valid for the whole session lifetime. structssh_callbacks_structcb={ .userdata=data, .auth_function=my_auth_function }; ssh_callbacks_init(&cb); ssh_set_callbacks(session,&cb); session The session to set the callback structure. cb The callback structure itself. SSH_OK on success, SSH_ERROR on error.
References ssh_common_struct::callbacks, cb, ssh_session_struct::common, is_callback_valid, ssh_callbacks_struct::log_function, session, SSH_ERROR, SSH_FATAL, ssh_get_log_callback, ssh_legacy_log_callback, ssh_set_error, ssh_set_log_callback, ssh_set_log_userdata.
Referenced by LLVMFuzzerTestOneInput, main.
static int ssh_add_set_channel_callbacks(ssh_channel channel, ssh_channel_callbacks cb, int prepend)
References ssh_channel_struct::callbacks, cb, is_callback_valid, rc, ssh_channel_struct::session, session, SSH_ERROR, SSH_FATAL, ssh_list_append, ssh_list_new, ssh_list_prepend, ssh_set_error, ssh_set_error_oom.
Referenced by ssh_add_channel_callbacks, ssh_set_channel_callbacks.
int ssh_set_channel_callbacks(ssh_channel channel, ssh_channel_callbacks cb)
Set the channel callback functions.
This functions sets the callback structure to use your own callback functions for channel data and exceptions. Note, that the structure is not copied to the channel structure so it needs to be valid as for the whole life of the channel or until it is removed with ssh_remove_channel_callbacks(). structssh_channel_callbacks_structcb={ .userdata=data, .channel_data_function=my_channel_data_function }; ssh_callbacks_init(&cb); ssh_set_channel_callbacks(channel,&cb); channel The channel to set the callback structure. cb The callback structure itself. SSH_OK on success, SSH_ERROR on error. this function will not replace existing callbacks but set the new one atop of them.
References cb, ssh_add_set_channel_callbacks.
Referenced by channel_open, default_handle_session_cb, handle_kbdint_session_cb, handle_session, message_callback, new_session_channel, pkd_channel_openreq_cb.
int ssh_add_channel_callbacks(ssh_channel channel, ssh_channel_callbacks cb)
Add channel callback functions.
This function will add channel callback functions to the channel callback list. Callbacks missing from a callback structure will be probed in the next on the list. channel The channel to set the callback structure. cb The callback structure itself. SSH_OK on success, SSH_ERROR on error. ssh_set_channel_callbacks
References cb, ssh_add_set_channel_callbacks.
Referenced by ssh_connector_set_in_channel, ssh_connector_set_out_channel.
int ssh_remove_channel_callbacks(ssh_channel channel, ssh_channel_callbacks cb)
Remove a channel callback.
The channel has been added with ssh_add_channel_callbacks or ssh_set_channel_callbacks in this case. channel The channel to remove the callback structure from. cb The callback structure to remove SSH_OK on success, SSH_ERROR on error.
References ssh_channel_struct::callbacks, cb, SSH_ERROR, ssh_list_find, ssh_list_remove, SSH_OK.
Referenced by do_cleanup, ssh_connector_free.
int ssh_set_server_callbacks(ssh_session session, ssh_server_callbacks cb)
Set the session server callback functions.
This functions sets the callback structure to use your own callback functions for user authentication, new channels and requests. Note, that the structure is not copied to the session structure so it needs to be valid for the whole session lifetime. structssh_server_callbacks_structcb={ .userdata=data, .auth_password_function=my_auth_function }; ssh_callbacks_init(&cb); ssh_set_server_callbacks(session,&cb); session The session to set the callback structure. cb The callback structure itself. SSH_OK on success, SSH_ERROR on error.
References cb, is_callback_valid, ssh_session_struct::server_callbacks, session, SSH_ERROR, SSH_FATAL, ssh_set_error.
Referenced by default_handle_session_cb, handle_kbdint_session_cb, handle_session, main, pkd_exec_hello, test_ssh_channel_request_x11.