chacha.h
CHACHA_MINKEYLEN
CHACHA_NONCELEN
CHACHA_CTRLEN
CHACHA_STATELEN
void chacha_keysetup(struct chacha_ctx *x, const uint8_t *k, uint32_t kbits)
References chacha_ctx::input, k, sigma, tau, U8TO32_LITTLE.
Referenced by chacha20_set_encrypt_key.
void chacha_ivsetup(struct chacha_ctx *x, const uint8_t *iv, const uint8_t *ctr)
References chacha_ctx::input, iv, U8TO32_LITTLE.
Referenced by chacha20_poly1305_aead_decrypt, chacha20_poly1305_aead_decrypt_length, chacha20_poly1305_aead_encrypt.
void chacha_encrypt_bytes(struct chacha_ctx *x, const uint8_t *m, uint8_t *c, uint32_t bytes)
References chacha_ctx::input, m, PLUS, PLUSONE, QUARTERROUND, U32TO8_LITTLE, U8TO32_LITTLE, XOR.
Referenced by chacha20_poly1305_aead_decrypt, chacha20_poly1305_aead_decrypt_length, chacha20_poly1305_aead_encrypt.