channels.h
SSH_CHANNEL_FLAG_CLOSED_REMOTE
SSH_CHANNEL_FLAG_CLOSED_LOCAL
SSH_CHANNEL_FLAG_FREED_LOCAL
SSH_CHANNEL_FLAG_NOT_BOUND
ssh_channel_request_state_e
No request has been made
ssh_channel_state_e
SSH_PACKET_CALLBACK(ssh_packet_channel_open_conf)
References error, ssh_channel_struct::flags, ssh_channel_struct::local_channel, rc, ssh_channel_struct::remote_channel, ssh_channel_struct::remote_maxpacket, ssh_channel_struct::remote_window, session, ssh_buffer_unpack, SSH_CHANNEL_FLAG_NOT_BOUND, ssh_channel_from_local, SSH_CHANNEL_STATE_OPEN, SSH_CHANNEL_STATE_OPENING, SSH_FATAL, SSH_LOG, SSH_LOG_PACKET, SSH_LOG_PROTOCOL, SSH_LOG_RARE, SSH_OK, SSH_PACKET_USED, ssh_set_error, ssh_channel_struct::state, user.
SSH_PACKET_CALLBACK(ssh_packet_channel_open_fail)
References channel_from_msg, error, ssh_channel_struct::local_channel, rc, SAFE_FREE, session, ssh_buffer_unpack, SSH_CHANNEL_STATE_OPEN_DENIED, SSH_CHANNEL_STATE_OPENING, SSH_FATAL, SSH_LOG, SSH_LOG_RARE, SSH_OK, SSH_PACKET_USED, SSH_REQUEST_DENIED, ssh_set_error, ssh_channel_struct::state, user.
SSH_PACKET_CALLBACK(ssh_packet_channel_success)
References channel_from_msg, ssh_channel_struct::local_channel, ssh_channel_struct::remote_channel, ssh_channel_struct::request_state, session, SSH_CHANNEL_REQ_STATE_ACCEPTED, SSH_CHANNEL_REQ_STATE_PENDING, ssh_get_error, SSH_LOG, SSH_LOG_FUNCTIONS, SSH_LOG_PACKET, SSH_LOG_RARE, SSH_PACKET_USED, user.
SSH_PACKET_CALLBACK(ssh_packet_channel_failure)
References channel_from_msg, ssh_channel_struct::local_channel, ssh_channel_struct::remote_channel, ssh_channel_struct::request_state, session, SSH_CHANNEL_REQ_STATE_DENIED, SSH_CHANNEL_REQ_STATE_PENDING, ssh_get_error, SSH_LOG, SSH_LOG_FUNCTIONS, SSH_LOG_PACKET, SSH_LOG_RARE, SSH_PACKET_USED, user.
SSH_PACKET_CALLBACK(ssh_request_success)
References ssh_session_struct::global_req_state, session, SSH_CHANNEL_REQ_STATE_ACCEPTED, SSH_CHANNEL_REQ_STATE_PENDING, SSH_LOG, SSH_LOG_PACKET, SSH_LOG_RARE, SSH_PACKET_USED, user.
SSH_PACKET_CALLBACK(ssh_request_denied)
References ssh_session_struct::global_req_state, session, SSH_CHANNEL_REQ_STATE_DENIED, SSH_CHANNEL_REQ_STATE_PENDING, SSH_LOG, SSH_LOG_PACKET, SSH_LOG_RARE, SSH_PACKET_USED, user.
SSH_PACKET_CALLBACK(channel_rcv_change_window)
References channel_from_msg, ssh_channel_struct::local_channel, rc, ssh_channel_struct::remote_channel, ssh_channel_struct::remote_window, session, ssh_buffer_unpack, ssh_get_error, SSH_LOG, SSH_LOG_FUNCTIONS, SSH_LOG_PACKET, SSH_LOG_PROTOCOL, SSH_OK, SSH_PACKET_USED, user.
SSH_PACKET_CALLBACK(channel_rcv_eof)
References ssh_channel_struct::callbacks, channel_from_msg, ssh_channel_struct::local_channel, ssh_channel_struct::remote_channel, ssh_channel_struct::remote_eof, ssh_channel_struct::session, session, ssh_callbacks_execute_list, ssh_get_error, SSH_LOG, SSH_LOG_FUNCTIONS, SSH_LOG_PACKET, SSH_PACKET_USED, user.
SSH_PACKET_CALLBACK(channel_rcv_close)
References ssh_channel_struct::callbacks, channel_from_msg, ssh_channel_struct::delayed_close, ssh_channel_struct::flags, ssh_channel_struct::local_channel, ssh_channel_struct::remote_channel, ssh_channel_struct::remote_eof, ssh_channel_struct::session, session, ssh_buffer_get_len, ssh_callbacks_execute_list, ssh_channel_do_free, SSH_CHANNEL_FLAG_CLOSED_REMOTE, SSH_CHANNEL_FLAG_FREED_LOCAL, SSH_CHANNEL_STATE_CLOSED, ssh_get_error, SSH_LOG, SSH_LOG_FUNCTIONS, SSH_LOG_PACKET, SSH_PACKET_USED, ssh_channel_struct::state, ssh_channel_struct::stderr_buffer, ssh_channel_struct::stdout_buffer, user.
SSH_PACKET_CALLBACK(channel_rcv_request)
References ssh_channel_struct::callbacks, channel_from_msg, ssh_channel_struct::exit_status, ssh_session_struct::out_buffer, rc, ssh_channel_struct::remote_channel, SAFE_FREE, ssh_channel_struct::session, session, SSH2_MSG_CHANNEL_FAILURE, ssh_buffer_pack, ssh_buffer_unpack, ssh_callbacks_execute_list, ssh_get_error, SSH_LOG, SSH_LOG_FUNCTIONS, SSH_LOG_PACKET, SSH_LOG_PROTOCOL, SSH_LOG_WARNING, ssh_message_handle_channel_request, SSH_OK, ssh_packet_send, SSH_PACKET_USED, user.
SSH_PACKET_CALLBACK(channel_rcv_data)
References ssh_channel_struct::callbacks, channel_default_bufferize, channel_from_msg, ssh_channel_struct::counter, grow_window, ssh_counter_struct::in_bytes, ssh_channel_struct::local_window, PRIdS, ssh_channel_struct::remote_window, ssh_channel_struct::session, session, SSH2_MSG_CHANNEL_DATA, ssh_buffer_get, ssh_buffer_get_len, ssh_buffer_get_ssh_string, ssh_buffer_get_u32, ssh_buffer_pass_bytes, ssh_callbacks_iterate, ssh_callbacks_iterate_end, ssh_callbacks_iterate_exec, ssh_get_error, SSH_LOG, SSH_LOG_FUNCTIONS, SSH_LOG_PACKET, SSH_LOG_RARE, SSH_PACKET_USED, ssh_string_data, SSH_STRING_FREE, ssh_string_len, ssh_channel_struct::stderr_buffer, ssh_channel_struct::stdout_buffer, user, WINDOWLIMIT.
int channel_default_bufferize(ssh_channel channel, void *data, size_t len, bool is_stderr)
References ssh_iterator::data, ssh_channel_struct::session, session, ssh_buffer_add_data, SSH_BUFFER_FREE, ssh_buffer_new, SSH_LOG, SSH_LOG_PACKET, ssh_set_error_invalid, ssh_set_error_oom, ssh_channel_struct::stderr_buffer, ssh_channel_struct::stdout_buffer.
Referenced by SSH_PACKET_CALLBACK.
int ssh_channel_flush(ssh_channel channel)
References ssh_channel_struct::session, ssh_blocking_flush, SSH_TIMEOUT_DEFAULT.
Referenced by channel_write_common, ssh_channel_close, ssh_channel_send_eof.
uint32_t ssh_channel_new_id(ssh_session session)
References ssh_session_struct::maxchannel, session.
Referenced by channel_open, ssh_message_channel_request_open_reply_accept_channel.
ssh_channel ssh_channel_from_local(ssh_session session, uint32_t id)
References ssh_session_struct::channels, ssh_channel_struct::local_channel, ssh_iterator::next, session, ssh_iterator_value, ssh_list_get_iterator.
Referenced by channel_from_msg, SSH_PACKET_CALLBACK.
void ssh_channel_do_free(ssh_channel channel)
References ssh_channel_struct::callbacks, ssh_session_struct::channels, SAFE_FREE, ssh_channel_struct::session, session, SSH_BUFFER_FREE, ssh_list_find, ssh_list_free, ssh_list_remove, ssh_channel_struct::stderr_buffer, ssh_channel_struct::stdout_buffer.
Referenced by ssh_channel_free, ssh_disconnect, ssh_free, SSH_PACKET_CALLBACK.
int ssh_global_request(ssh_session session, const char *request, ssh_buffer buffer, int reply)
References buffer, error, ssh_session_struct::global_req_state, ssh_session_struct::out_buffer, rc, session, ssh_session_struct::session_state, SSH2_MSG_GLOBAL_REQUEST, SSH_AGAIN, ssh_buffer_add_data, ssh_buffer_get, ssh_buffer_get_len, ssh_buffer_pack, ssh_buffer_reinit, SSH_CHANNEL_REQ_STATE_ACCEPTED, SSH_CHANNEL_REQ_STATE_DENIED, SSH_CHANNEL_REQ_STATE_ERROR, SSH_CHANNEL_REQ_STATE_NONE, SSH_CHANNEL_REQ_STATE_PENDING, SSH_ERROR, ssh_global_request_termination, ssh_handle_packets_termination, SSH_LOG, SSH_LOG_PACKET, SSH_LOG_PROTOCOL, SSH_OK, ssh_packet_send, SSH_REQUEST_DENIED, SSH_SESSION_STATE_ERROR, ssh_set_error, ssh_set_error_oom, SSH_TIMEOUT_DEFAULT.
Referenced by ssh_channel_cancel_forward, ssh_channel_listen_forward, ssh_send_keepalive, torture_server_unknown_global_request, torture_unknown_request.