client.c
set_status
static void socket_callback_connected(int code, int errno_code, void *user)
References session, ssh_session_struct::session_state, ssh_session_struct::ssh_connection_callback, SSH_FATAL, SSH_LOG, SSH_LOG_RARE, SSH_SESSION_STATE_CONNECTING, SSH_SESSION_STATE_ERROR, SSH_SESSION_STATE_SOCKET_CONNECTED, ssh_set_error, SSH_SOCKET_CONNECTED_OK, user.
Referenced by ssh_connect.
static int callback_receive_banner(const void *data, size_t len, void *user)
References buffer, ssh_session_struct::serverbanner, session, ssh_session_struct::session_state, ssh_session_struct::ssh_connection_callback, SSH_ERROR, SSH_FATAL, SSH_LOG, SSH_LOG_DEBUG, SSH_LOG_PACKET, SSH_SESSION_STATE_BANNER_RECEIVED, SSH_SESSION_STATE_ERROR, SSH_SESSION_STATE_SOCKET_CONNECTED, ssh_set_error, user.
Referenced by ssh_connect.
int ssh_send_banner(ssh_session session, int server)
References buffer, CLIENT_BANNER_SSH2, ssh_session_struct::clientbanner, ssh_session_struct::custombanner, ssh_session_struct::opts, rc, ssh_session_struct::serverbanner, session, ssh_session_struct::socket, SSH_ERROR, SSH_OK, ssh_socket_write.
Referenced by ssh_client_connection_callback, ssh_handle_key_exchange.
static int dh_handshake(ssh_session session)
References ssh_session_struct::dh_handshake_state, DH_STATE_FINISHED, DH_STATE_INIT, DH_STATE_INIT_SENT, DH_STATE_NEWKEYS_SENT, ssh_crypto_struct::kex_type, ssh_session_struct::next_crypto, rc, session, SSH_AGAIN, ssh_client_curve25519_init, ssh_client_dh_init, ssh_client_dhgex_init, ssh_client_ecdh_init, SSH_ERROR, SSH_FATAL, SSH_KEX_CURVE25519_SHA256, SSH_KEX_CURVE25519_SHA256_LIBSSH_ORG, SSH_KEX_DH_GROUP14_SHA1, SSH_KEX_DH_GROUP16_SHA512, SSH_KEX_DH_GROUP18_SHA512, SSH_KEX_DH_GROUP1_SHA1, SSH_KEX_ECDH_SHA2_NISTP256, SSH_KEX_ECDH_SHA2_NISTP384, SSH_KEX_ECDH_SHA2_NISTP521, SSH_OK, ssh_set_error.
Referenced by ssh_client_connection_callback.
static int ssh_service_request_termination(void *s)
References ssh_session_struct::auth, s, ssh_session_struct::service_state, session, ssh_session_struct::session_state, SSH_AUTH_SERVICE_SENT, SSH_SESSION_STATE_ERROR.
Referenced by ssh_service_request.
int ssh_service_request(ssh_session session, const char *service)
References ssh_session_struct::auth, ssh_session_struct::out_buffer, rc, ssh_session_struct::service_state, session, SSH2_MSG_SERVICE_REQUEST, SSH_AGAIN, SSH_AUTH_SERVICE_ACCEPTED, SSH_AUTH_SERVICE_DENIED, SSH_AUTH_SERVICE_NONE, SSH_AUTH_SERVICE_SENT, ssh_buffer_pack, SSH_ERROR, SSH_FATAL, ssh_handle_packets_termination, SSH_LOG, SSH_LOG_PACKET, SSH_OK, ssh_packet_send, ssh_service_request_termination, ssh_set_error, ssh_set_error_oom, SSH_TIMEOUT_USER.
Referenced by ssh_userauth_request_service.
static void ssh_client_connection_callback(ssh_session session)
References ssh_session_struct::alive, ssh_crypto_struct::client_kex, ssh_session_struct::connected, dh_handshake, ssh_session_struct::dh_handshake_state, DH_STATE_FINISHED, error, ssh_session_struct::flags, ssh_kex_struct::methods, ssh_session_struct::next_crypto, rc, ssh_crypto_struct::server_kex, ssh_session_struct::serverbanner, session, ssh_session_struct::session_state, set_status, ssh_session_struct::socket, ssh_analyze_banner, SSH_ERROR, SSH_FATAL, ssh_kex_select_methods, ssh_list_kex, SSH_LOG, SSH_LOG_PROTOCOL, SSH_OK, ssh_packet_register_socket_callback, ssh_packet_set_default_callbacks, ssh_send_banner, ssh_send_kex, SSH_SESSION_FLAG_AUTHENTICATED, SSH_SESSION_STATE_AUTHENTICATED, SSH_SESSION_STATE_AUTHENTICATING, SSH_SESSION_STATE_BANNER_RECEIVED, SSH_SESSION_STATE_CONNECTING, SSH_SESSION_STATE_DH, SSH_SESSION_STATE_ERROR, SSH_SESSION_STATE_INITIAL_KEX, SSH_SESSION_STATE_KEXINIT_RECEIVED, SSH_SESSION_STATE_NONE, SSH_SESSION_STATE_SOCKET_CONNECTED, ssh_set_client_kex, ssh_set_error, ssh_set_fd_towrite, ssh_socket_close.
Referenced by ssh_connect.
static int ssh_connect_termination(void *user)
References session, ssh_session_struct::session_state, SSH_SESSION_STATE_AUTHENTICATING, SSH_SESSION_STATE_DISCONNECTED, SSH_SESSION_STATE_ERROR, user.
Referenced by ssh_connect.
int ssh_connect(ssh_session session)
Connect to the ssh server.
session The ssh session to connect. SSH_OK on success, SSH_ERROR on error. SSH_AGAIN, if the session is in nonblocking mode, and call must be done again. ssh_new() ssh_disconnect()
References ssh_session_struct::alive, ssh_session_struct::bindaddr, callback_receive_banner, ssh_session_struct::client, ssh_session_struct::config_processed, ssh_socket_callbacks_struct::connected, ssh_socket_callbacks_struct::data, ssh_socket_callbacks_struct::exception, ssh_session_struct::fd, ssh_session_struct::host, ssh_session_struct::opts, ssh_session_struct::pending_call_state, ssh_session_struct::port, ssh_session_struct::ProxyCommand, session, ssh_session_struct::session_state, set_status, ssh_session_struct::socket, socket_callback_connected, ssh_session_struct::socket_callbacks, SSH_AGAIN, ssh_client_connection_callback, ssh_connect_termination, ssh_session_struct::ssh_connection_callback, ssh_copyright, SSH_ERROR, SSH_FATAL, ssh_handle_packets_termination, SSH_INVALID_SOCKET, ssh_is_blocking, SSH_LOG, SSH_LOG_PACKET, SSH_LOG_PROTOCOL, SSH_OK, ssh_options_apply, ssh_options_parse_config, SSH_PENDING_CALL_CONNECT, SSH_PENDING_CALL_NONE, SSH_SESSION_STATE_CONNECTING, SSH_SESSION_STATE_DISCONNECTED, SSH_SESSION_STATE_ERROR, SSH_SESSION_STATE_SOCKET_CONNECTED, ssh_set_error, ssh_socket_connect, ssh_socket_connect_proxycommand, ssh_socket_exception_callback, ssh_socket_set_callbacks, ssh_socket_set_fd, ssh_threads_get_type, SSH_TIMEOUT_NONBLOCKING, ssh_session_struct::timeout, ssh_session_struct::timeout_usec, ssh_socket_callbacks_struct::userdata.
Referenced by authenticate, client, ssh::Session::connect, connect_host, connect_ssh, do_connect, LLVMFuzzerTestOneInput, main, ssh_client, test_algorithm, torture_algorithms_zlib, torture_algorithms_zlib_openssh, torture_auth_agent, torture_auth_agent_nonblocking, torture_auth_autopubkey, torture_auth_autopubkey_nonblocking, torture_auth_cert, torture_auth_kbdint, torture_auth_kbdint_nonblocking, torture_auth_none, torture_auth_none_nonblocking, torture_auth_password, torture_auth_password_nonblocking, torture_auth_pubkey_types, torture_auth_pubkey_types_ecdsa, torture_auth_pubkey_types_ecdsa_nonblocking, torture_auth_pubkey_types_ed25519, torture_auth_pubkey_types_ed25519_nonblocking, torture_auth_pubkey_types_nonblocking, torture_client_config_autoparse, torture_client_config_suppress, torture_connect_double, torture_connect_nonblocking, torture_connect_socket, torture_hostkey_ed25519, torture_hostkey_rsa, torture_hostkey_rsa_sha256, torture_hostkey_rsa_sha512, torture_knownhosts_conflict, torture_knownhosts_export, torture_knownhosts_fail, torture_knownhosts_new_file, torture_knownhosts_no_hostkeychecking, torture_knownhosts_other, torture_knownhosts_other_auto, torture_knownhosts_port, torture_knownhosts_standard_port, torture_knownhosts_unknown, torture_knownhosts_wildcard, torture_knownhosts_write_and_verify, torture_options_set_proxycommand_notexist, torture_options_set_proxycommand_ssh, torture_options_set_proxycommand_ssh_stderr, torture_rekey_default, torture_rekey_send, torture_rekey_server_send, torture_rekey_time, torture_server_auth_kbdint, torture_server_auth_none, torture_server_auth_password, torture_server_auth_pubkey, torture_server_hostkey_mismatch, torture_server_unknown_global_request, torture_ssh_session, try_config_content.
char* ssh_get_issue_banner(ssh_session session)
Get the issue banner from the server.
This is the banner showing a disclaimer to users who log in, typically their right or the fact that they will be monitored. session The SSH session to use. A newly allocated string with the banner, NULL on error.
References ssh_session_struct::banner, session, ssh_string_to_char.
Referenced by authenticate_console, client, ssh::Session::getIssueBanner.
int ssh_get_openssh_version(ssh_session session)
Get the version of the OpenSSH server, if it is not an OpenSSH server then 0 will be returned.
You can use the SSH_VERSION_INT macro to compare version numbers. session The SSH session to use. The version number if available, 0 otherwise. intopenssh=ssh_get_openssh_version(); if(openssh==SSH_INT_VERSION(6,1,0)){ printf("Versionmatch!\m"); }
References ssh_session_struct::openssh, session.
Referenced by ssh::Session::getOpensshVersion, ssh_channel_open_forward_unix, torture_algorithms_zlib, torture_algorithms_zlib_openssh.
void ssh_disconnect(ssh_session session)
Disconnect from a session (client or server). The session can then be reused to open a new session.
session The SSH session to use.
References ssh_session_struct::alive, ssh_session_struct::auth, ssh_session_struct::channels, ssh_session_struct::clientbanner, crypto_free, crypto_new, ssh_session_struct::current_crypto, error, ssh_session_struct::fd, ssh_session_struct::in_buffer, ssh_session_struct::in_hashbuf, ssh_session_struct::next_crypto, ssh_session_struct::opts, ssh_session_struct::out_buffer, ssh_session_struct::out_hashbuf, ssh_session_struct::packet_callbacks, rc, ssh_session_struct::recv_seq, SAFE_FREE, ssh_session_struct::send_seq, ssh_session_struct::serverbanner, session, ssh_session_struct::session_state, ssh_session_struct::socket, SSH2_DISCONNECT_BY_APPLICATION, SSH2_MSG_DISCONNECT, ssh_buffer_pack, ssh_buffer_reinit, ssh_channel_do_free, SSH_INVALID_SOCKET, ssh_iterator_value, ssh_list_free, ssh_list_get_iterator, ssh_list_pop_head, ssh_list_remove, ssh_message_free, ssh_session_struct::ssh_message_list, SSH_OK, ssh_packet_send, SSH_SESSION_STATE_DISCONNECTED, ssh_set_error_oom, ssh_socket_close, ssh_socket_is_open, ssh_socket_reset, ssh_session_struct::supported_methods.
Referenced by auth_password, connect_host, connect_ssh, ssh::Session::disconnect, docycle, LLVMFuzzerTestOneInput, main, pkd_exec_hello, run_server, session_teardown, ssh_silent_disconnect, teardown, test_algorithm, torture_algorithms_zlib, torture_algorithms_zlib_openssh, torture_connect_double, torture_connect_failure, torture_hostkey_ed25519, torture_hostkey_rsa, torture_hostkey_rsa_sha256, torture_hostkey_rsa_sha512, torture_knownhosts_conflict, torture_knownhosts_other_auto, torture_knownhosts_port, torture_knownhosts_unknown, torture_rekey_default, torture_rekey_send, torture_rekey_server_send, torture_rekey_time, torture_ssh_session.
const char* ssh_copyright(void)
References LIBSSH_VERSION, SSH_STRINGIFY.
Referenced by ssh_connect.