CMakeLists.txt
requires an out of source build Please create a separate build directory and run cmake path to
cmake_minimum_required(VERSION 3.3.0) cmake_policy(SET CMP0048 NEW) list(APPEND CMAKE_MODULE_PATH "$
cmake Modules include(DefineCMakeDefaults) include(DefineCompilerFlags) project(libssh VERSION 0.8.90 LANGUAGES C) set(APPLICATION_NAME $
set(LIBRARY_VERSION "4.8.1") set(LIBRARY_SOVERSION "4") include(DefinePlatformDefaults) include(DefineOptions.cmake) include(CPackConfig.cmake) include(GNUInstallDirs) include(CompilerChecks.cmake) include(MacroEnsureOutOfSourceBuild) macro_ensure_out_of_source_build("$
Referenced by ssh_select_cb, ssh_socket_fd_isset, ssh_socket_fd_set.
requires an out of source build Please create a separate build directory and run cmake path GCrypt or mbedTLS endif(NOT MBEDTLS_FOUND) endif(NOT GCRYPT_FOUND) endif(NOT OPENSSL_FOUND) endif(WITH_GCRYPT) if(UNIT_TESTING) find_package(CMocka REQUIRED) endif() set(CMAKE_THREAD_PREFER_PTHREADS ON) set(THREADS_PREFER_PTHREAD_FLAG ON) find_package(Threads) if(WITH_GSSAPI) find_package(GSSAPI) endif(WITH_GSSAPI) if(WITH_PKCS11_URI) find_package(softhsm) if(NOT SOFTHSM_FOUND) message(SEND_ERROR "Could not find softhsm module!") endif(NOT SOFTHSM_FOUND) endif(WITH_PKCS11_URI) if(WITH_NACL) find_package(NaCl) if(NOT NACL_FOUND) set(WITH_NACL OFF) endif(NOT NACL_FOUND) endif(WITH_NACL) if(BSD OR SOLARIS OR OSX) find_package(Argp) endif(BSD OR SOLARIS OR OSX) if(UNIX) find_package(ABIMap 0.3.1) else(UNIX) set(WITH_SYMBOL_VERSIONING OFF) endif(UNIX) include(ConfigureChecks.cmake) configure_file(config.h.cmake $
Referenced by pki_verify_data_signature, torture_pki_ed25519_generate_key, torture_pki_ed25519_verify, torture_setup_create_sshd_config, usage.
config h add_subdirectory(doc) add_subdirectory(include) add_subdirectory(src) if(UNIX) configure_file(libssh.pc.cmake $
libssh pc install(FILES ${CMAKE_CURRENT_BINARY_DIR}/libssh.pc DESTINATION ${CMAKE_INSTALL_LIBDIR}/pkgconfig COMPONENT pkgconfig) endif(UNIX) include(CMakePackageConfigHelpers) set(LIBSSH_LIBRARY_NAME $