config.c
MAX_LINE_SIZE
ssh_config_match_e
struct ssh_config_keyword_table_s ssh_config_keyword_table[][]
struct ssh_config_match_keyword_table_s ssh_config_match_keyword_table[][]
static int ssh_config_parse_line(ssh_session session, const char *line, unsigned int count, int *parsing)
References generate.a, FALL_THROUGH, ssh_session_struct::host, local_parse_file, MATCH_ALL, MATCH_CANONICAL, MATCH_EXEC, MATCH_FINAL, MATCH_HOST, match_hostname, MATCH_LOCALUSER, MATCH_ORIGINALHOST, MATCH_UNKNOWN, MATCH_USER, ssh_config_match_keyword_table_s::opcode, ssh_session_struct::options_seen, ssh_session_struct::opts, s, SAFE_FREE, session, SOC_BINDADDRESS, SOC_CIPHERS, SOC_COMPRESSION, SOC_GLOBALKNOWNHOSTSFILE, SOC_GSSAPIAUTHENTICATION, SOC_GSSAPICLIENTIDENTITY, SOC_GSSAPIDELEGATECREDENTIALS, SOC_GSSAPISERVERIDENTITY, SOC_HOST, SOC_HOSTKEYALGORITHMS, SOC_HOSTNAME, SOC_IDENTITY, SOC_INCLUDE, SOC_KBDINTERACTIVEAUTHENTICATION, SOC_KEXALGORITHMS, SOC_KNOWNHOSTS, SOC_LOGLEVEL, SOC_MACS, SOC_MATCH, SOC_NA, SOC_PASSWORDAUTHENTICATION, SOC_PORT, SOC_PROTOCOL, SOC_PROXYCOMMAND, SOC_PROXYJUMP, SOC_PUBKEYACCEPTEDTYPES, SOC_PUBKEYAUTHENTICATION, SOC_REKEYLIMIT, SOC_STRICTHOSTKEYCHECK, SOC_TIMEOUT, SOC_UNKNOWN, SOC_UNSUPPORTED, SOC_USERNAME, ssh_config_get_cmd, ssh_config_get_long, ssh_config_get_match_opcode, ssh_config_get_opcode, ssh_config_get_str_tok, ssh_config_get_token, ssh_config_get_yesno, ssh_config_match, ssh_config_parse_proxy_jump, SSH_FATAL, ssh_get_local_username, SSH_LOG, SSH_LOG_DEBUG, SSH_LOG_INFO, SSH_LOG_NONE, SSH_LOG_TRACE, SSH_LOG_WARN, ssh_lowercase, ssh_match_exec, SSH_OK, SSH_OPTIONS_ADD_IDENTITY, SSH_OPTIONS_BINDADDR, SSH_OPTIONS_CIPHERS_C_S, SSH_OPTIONS_CIPHERS_S_C, SSH_OPTIONS_COMPRESSION, SSH_OPTIONS_GLOBAL_KNOWNHOSTS, SSH_OPTIONS_GSSAPI_AUTH, SSH_OPTIONS_GSSAPI_CLIENT_IDENTITY, SSH_OPTIONS_GSSAPI_DELEGATE_CREDENTIALS, SSH_OPTIONS_GSSAPI_SERVER_IDENTITY, SSH_OPTIONS_HMAC_C_S, SSH_OPTIONS_HMAC_S_C, SSH_OPTIONS_HOST, SSH_OPTIONS_HOSTKEYS, SSH_OPTIONS_KBDINT_AUTH, SSH_OPTIONS_KEY_EXCHANGE, SSH_OPTIONS_KNOWNHOSTS, SSH_OPTIONS_LOG_VERBOSITY, SSH_OPTIONS_PASSWORD_AUTH, SSH_OPTIONS_PORT_STR, SSH_OPTIONS_PROXYCOMMAND, SSH_OPTIONS_PUBKEY_AUTH, SSH_OPTIONS_PUBLICKEY_ACCEPTED_TYPES, SSH_OPTIONS_REKEY_DATA, SSH_OPTIONS_REKEY_TIME, ssh_options_set, SSH_OPTIONS_SSH2, SSH_OPTIONS_STRICTHOSTKEYCHECK, SSH_OPTIONS_TIMEOUT, SSH_OPTIONS_USER, ssh_path_expand_escape, ssh_set_error, ssh_set_error_oom, ssh_session_struct::username.
Referenced by local_parse_file, ssh_config_parse_file.
static enum ssh_config_opcode_e ssh_config_get_opcode(char *keyword)
Referenced by ssh_config_parse_line.
static void local_parse_file(ssh_session session, const char *filename, int *parsing)
References MAX_LINE_SIZE, session, ssh_config_parse_line, SSH_LOG, SSH_LOG_PACKET, SSH_LOG_RARE.
Referenced by ssh_config_parse_line.
static enum ssh_config_match_e ssh_config_get_match_opcode(const char *keyword)
Referenced by ssh_config_parse_line.
static int ssh_config_match(char *value, const char *pattern, bool negate)
References match_pattern_list, pattern, SSH_LOG, SSH_LOG_TRACE.
Referenced by ssh_config_parse_line.
static int ssh_exec_shell(char *cmd)
References rc, shell, SSH_LOG, SSH_LOG_DEBUG, SSH_LOG_TRACE, SSH_LOG_WARN.
Referenced by ssh_match_exec.
static int ssh_match_exec(ssh_session session, const char *command, bool negate)
References session, ssh_exec_shell, SSH_LOG, SSH_LOG_TRACE, ssh_path_expand_escape.
Referenced by ssh_config_parse_line.
static int ssh_config_parse_proxy_jump(ssh_session session, const char *s, bool do_parsing)
References port, s, SAFE_FREE, session, ssh_config_parse_uri, SSH_ERROR, SSH_LOG, SSH_LOG_WARN, SSH_OK, SSH_OPTIONS_PROXYCOMMAND, ssh_options_set, ssh_set_error_oom, username.
Referenced by ssh_config_parse_line.
int ssh_config_parse_file(ssh_session session, const char *filename)
References MAX_LINE_SIZE, session, ssh_config_parse_line, SSH_LOG, SSH_LOG_PACKET.
Referenced by ssh_options_parse_config, torture_config_auth_methods, torture_config_double_ports, torture_config_from_file, torture_config_glob, torture_config_match, torture_config_new, torture_config_proxyjump, torture_config_pubkeyacceptedkeytypes, torture_config_rekey, torture_config_unknown.