connector.c
CHUNKSIZE
static int ssh_connector_channel_data_cb(ssh_session session, ssh_channel channel, void *data, uint32_t len, int is_stderr, void *userdata)
References ssh_connector_struct::in_available, ssh_connector_struct::in_flags, MIN, ssh_connector_struct::out_channel, ssh_connector_struct::out_fd, ssh_connector_struct::out_flags, ssh_connector_struct::out_wontblock, session, ssh_channel_window_size, ssh_channel_write, ssh_channel_write_stderr, ssh_connector_except, ssh_connector_except_channel, ssh_connector_fd_write, ssh_connector_reset_pollevents, SSH_CONNECTOR_STDERR, SSH_CONNECTOR_STDOUT, SSH_ERROR, SSH_FATAL, SSH_INVALID_SOCKET, SSH_LOG, SSH_LOG_TRACE, ssh_set_error, ssh_channel_callbacks_struct::userdata.
Referenced by ssh_connector_new.
static int ssh_connector_channel_write_wontblock_cb(ssh_session session, ssh_channel channel, size_t bytes, void *userdata)
References buffer, CHUNKSIZE, ssh_connector_struct::in_available, ssh_connector_struct::in_channel, ssh_connector_struct::in_fd, MIN, ssh_connector_struct::out_channel, ssh_connector_struct::out_wontblock, session, ssh_channel_is_eof, ssh_channel_read_nonblocking, ssh_channel_send_eof, ssh_channel_write, ssh_connector_except_channel, ssh_connector_fd_in_cb, ssh_connector_reset_pollevents, SSH_ERROR, SSH_FATAL, SSH_INVALID_SOCKET, SSH_LOG, SSH_LOG_TRACE, ssh_set_error, ssh_channel_callbacks_struct::userdata.
Referenced by ssh_connector_new.
static ssize_t ssh_connector_fd_read(ssh_connector connector, void *buffer, uint32_t len)
References buffer, ssh_connector_struct::fd_is_socket, ssh_connector_struct::in_fd.
Referenced by ssh_connector_fd_in_cb.
static ssize_t ssh_connector_fd_write(ssh_connector connector, const void *buffer, uint32_t len)
References buffer, ssh_connector_struct::fd_is_socket, ssh_connector_struct::out_fd.
Referenced by ssh_connector_channel_data_cb, ssh_connector_fd_in_cb, ssh_connector_fd_out_cb.
static bool ssh_connector_fd_is_socket(socket_t socket)
References rc, s, SSH_LOG, SSH_LOG_TRACE.
Referenced by ssh_connector_set_in_fd, ssh_connector_set_out_fd.
ssh_connector ssh_connector_new(ssh_session session)
References ssh_channel_callbacks_struct::channel_data_function, ssh_channel_callbacks_struct::channel_write_wontblock_function, ssh_connector_struct::fd_is_socket, ssh_connector_struct::in_channel_cb, ssh_connector_struct::in_fd, ssh_connector_struct::out_channel_cb, ssh_connector_struct::out_fd, ssh_connector_struct::session, session, ssh_callbacks_init, ssh_connector_channel_data_cb, ssh_connector_channel_write_wontblock_cb, SSH_INVALID_SOCKET, ssh_set_error_oom, ssh_channel_callbacks_struct::userdata.
Referenced by select_loop.
void ssh_connector_free(ssh_connector connector)
References ssh_connector_struct::event, ssh_connector_struct::in_channel, ssh_connector_struct::in_channel_cb, ssh_connector_struct::in_poll, ssh_connector_struct::out_channel, ssh_connector_struct::out_channel_cb, ssh_connector_struct::out_poll, ssh_connector_remove_event, ssh_poll_free, ssh_remove_channel_callbacks.
Referenced by select_loop.
int ssh_connector_set_in_channel(ssh_connector connector, ssh_channel channel, enum ssh_connector_flags_e flags)
References ssh_connector_struct::in_channel, ssh_connector_struct::in_channel_cb, ssh_connector_struct::in_fd, ssh_connector_struct::in_flags, ssh_add_channel_callbacks, SSH_CONNECTOR_STDERR, SSH_CONNECTOR_STDOUT, SSH_INVALID_SOCKET.
Referenced by select_loop.
int ssh_connector_set_out_channel(ssh_connector connector, ssh_channel channel, enum ssh_connector_flags_e flags)
References ssh_connector_struct::in_flags, ssh_connector_struct::out_channel, ssh_connector_struct::out_channel_cb, ssh_connector_struct::out_fd, ssh_connector_struct::out_flags, ssh_add_channel_callbacks, SSH_CONNECTOR_STDERR, SSH_CONNECTOR_STDOUT, SSH_INVALID_SOCKET.
Referenced by select_loop.
void ssh_connector_set_in_fd(ssh_connector connector, socket_t fd)
References ssh_connector_struct::fd_is_socket, ssh_connector_struct::in_channel, ssh_connector_struct::in_fd, ssh_connector_fd_is_socket.
Referenced by select_loop.
void ssh_connector_set_out_fd(ssh_connector connector, socket_t fd)
References ssh_connector_struct::fd_is_socket, ssh_connector_struct::out_channel, ssh_connector_struct::out_fd, ssh_connector_fd_is_socket.
Referenced by select_loop.
static void ssh_connector_except(ssh_connector connector, socket_t fd)
Referenced by ssh_connector_channel_data_cb, ssh_connector_fd_cb, ssh_connector_fd_in_cb, ssh_connector_fd_out_cb.
static void ssh_connector_except_channel(ssh_connector connector, ssh_channel channel)
Referenced by ssh_connector_channel_data_cb, ssh_connector_channel_write_wontblock_cb, ssh_connector_fd_out_cb.
static void ssh_connector_reset_pollevents(ssh_connector connector)
References ssh_connector_struct::in_available, ssh_connector_struct::in_fd, ssh_connector_struct::in_poll, ssh_connector_struct::out_fd, ssh_connector_struct::out_poll, ssh_connector_struct::out_wontblock, POLLIN, POLLOUT, SSH_INVALID_SOCKET, ssh_poll_add_events, ssh_poll_remove_events.
Referenced by ssh_connector_channel_data_cb, ssh_connector_channel_write_wontblock_cb, ssh_connector_fd_cb.
static void ssh_connector_fd_in_cb(ssh_connector connector)
References buffer, CHUNKSIZE, ssh_connector_struct::in_available, ssh_connector_struct::in_fd, ssh_channel_struct::local_eof, MIN, ssh_connector_struct::out_channel, ssh_connector_struct::out_fd, ssh_connector_struct::out_flags, ssh_connector_struct::out_wontblock, rc, ssh_connector_struct::session, ssh_channel_callbacks_struct::size, ssh_channel_send_eof, ssh_channel_window_size, ssh_channel_write, ssh_channel_write_stderr, ssh_connector_except, ssh_connector_fd_read, ssh_connector_fd_write, SSH_CONNECTOR_STDOUT, SSH_ERROR, SSH_FATAL, SSH_INVALID_SOCKET, SSH_LOG, SSH_LOG_TRACE, ssh_set_error.
Referenced by ssh_connector_channel_write_wontblock_cb, ssh_connector_fd_cb, ssh_connector_fd_out_cb.
static void ssh_connector_fd_out_cb(ssh_connector connector)
References buffer, CHUNKSIZE, ssh_connector_struct::in_available, ssh_connector_struct::in_channel, ssh_connector_struct::in_fd, ssh_connector_struct::out_fd, ssh_connector_struct::out_wontblock, ssh_connector_struct::session, ssh_channel_is_eof, ssh_channel_read_nonblocking, ssh_connector_except, ssh_connector_except_channel, ssh_connector_fd_in_cb, ssh_connector_fd_write, SSH_ERROR, SSH_FATAL, SSH_INVALID_SOCKET, SSH_LOG, SSH_LOG_TRACE, ssh_set_error.
Referenced by ssh_connector_fd_cb.
static int ssh_connector_fd_cb(ssh_poll_handle p, socket_t fd, int revents, void *userdata)
References ssh_connector_struct::in_fd, ssh_connector_struct::out_fd, POLLERR, POLLHUP, POLLIN, POLLOUT, ssh_connector_except, ssh_connector_fd_in_cb, ssh_connector_fd_out_cb, ssh_connector_reset_pollevents, ssh_channel_callbacks_struct::userdata.
Referenced by ssh_connector_set_event.
int ssh_connector_set_event(ssh_connector connector, ssh_event event)
References error, ssh_connector_struct::event, ssh_connector_struct::in_available, ssh_connector_struct::in_channel, ssh_connector_struct::in_fd, ssh_connector_struct::in_poll, ssh_connector_struct::out_channel, ssh_connector_struct::out_fd, ssh_connector_struct::out_poll, ssh_connector_struct::out_wontblock, POLLERR, POLLIN, POLLOUT, rc, ssh_connector_struct::session, session, ssh_channel_get_session, ssh_channel_poll_timeout, ssh_channel_window_size, ssh_connector_fd_cb, SSH_ERROR, ssh_event_add_poll, ssh_event_add_session, SSH_FATAL, SSH_INVALID_SOCKET, SSH_OK, ssh_poll_new, ssh_set_error.
Referenced by ssh_event_add_connector.
int ssh_connector_remove_event(ssh_connector connector)
References ssh_connector_struct::event, ssh_connector_struct::in_channel, ssh_connector_struct::in_poll, ssh_connector_struct::out_channel, ssh_connector_struct::out_poll, session, ssh_channel_get_session, ssh_event_remove_poll, ssh_event_remove_session, SSH_OK, ssh_poll_free.
Referenced by ssh_connector_free, ssh_event_remove_connector.