dh.c
P_GROUP1_LEN
P_GROUP14_LEN
P_GROUP16_LEN
P_GROUP18_LEN
unsigned char p_group1_value[][]
Referenced by ssh_dh_init.
unsigned char p_group14_value[][]
Referenced by ssh_dh_init.
unsigned char p_group16_value[][]
Referenced by ssh_dh_init.
unsigned char p_group18_value[][]
Referenced by ssh_dh_init.
bignum ssh_dh_generator
Referenced by ssh_dh_finalize, ssh_dh_free_generator, ssh_dh_init, ssh_dh_init_common, ssh_dh_is_known_group.
bignum ssh_dh_group1
Referenced by ssh_dh_finalize, ssh_dh_free_modulus, ssh_dh_init, ssh_dh_init_common.
bignum ssh_dh_group14
Referenced by ssh_dh_finalize, ssh_dh_free_modulus, ssh_dh_init, ssh_dh_init_common, ssh_dh_is_known_group.
bignum ssh_dh_group16
Referenced by ssh_dh_finalize, ssh_dh_free_modulus, ssh_dh_init, ssh_dh_init_common, ssh_dh_is_known_group.
bignum ssh_dh_group18
Referenced by ssh_dh_finalize, ssh_dh_free_modulus, ssh_dh_init, ssh_dh_init_common, ssh_dh_is_known_group.
int dh_crypto_initialized
Referenced by ssh_dh_finalize, ssh_dh_init.
ssh_packet_callback dh_client_callbacks[][]
struct ssh_packet_callbacks_struct ssh_dh_client_callbacks
Referenced by ssh_client_dh_init, SSH_PACKET_CALLBACK.
int ssh_dh_init(void)
References dh_crypto_initialized, error, P_GROUP14_LEN, p_group14_value, P_GROUP16_LEN, p_group16_value, P_GROUP18_LEN, p_group18_value, P_GROUP1_LEN, p_group1_value, rc, ssh_dh_finalize, ssh_dh_generator, ssh_dh_group1, ssh_dh_group14, ssh_dh_group16, ssh_dh_group18, SSH_ERROR, SSH_OK.
Referenced by libssh_constructor.
void ssh_dh_finalize(void)
References dh_crypto_initialized, ssh_dh_generator, ssh_dh_group1, ssh_dh_group14, ssh_dh_group16, ssh_dh_group18.
Referenced by _ssh_finalize, ssh_dh_init.
int ssh_dh_import_next_pubkey_blob(ssh_session session, ssh_string pubkey_blob)
References ssh_session_struct::next_crypto, ssh_crypto_struct::server_pubkey, session, ssh_pki_import_pubkey_blob.
Referenced by ssh_get_key_params, SSH_PACKET_CALLBACK.
SSH_PACKET_CALLBACK(ssh_packet_client_dh_reply)
References DH_CLIENT_KEYPAIR, ssh_crypto_struct::dh_ctx, ssh_session_struct::dh_handshake_state, DH_SERVER_KEYPAIR, ssh_crypto_struct::dh_server_signature, DH_STATE_NEWKEYS_SENT, error, ssh_session_struct::next_crypto, ssh_session_struct::out_buffer, rc, ssh_crypto_struct::server_pubkey, session, ssh_session_struct::session_state, ssh_crypto_struct::shared_secret, SSH2_MSG_NEWKEYS, ssh_buffer_add_u8, ssh_buffer_unpack, ssh_dh_cleanup, ssh_dh_client_callbacks, ssh_dh_compute_shared_secret, ssh_dh_debug_crypto, ssh_dh_import_next_pubkey_blob, ssh_dh_keypair_set_keys, SSH_ERROR, SSH_FATAL, SSH_LOG, SSH_LOG_PROTOCOL, SSH_OK, ssh_packet_remove_callbacks, ssh_packet_send, SSH_PACKET_USED, SSH_SESSION_STATE_ERROR, ssh_set_error, SSH_STRING_FREE, user.
int ssh_client_dh_init(ssh_session session)
References DH_CLIENT_KEYPAIR, ssh_crypto_struct::dh_ctx, ssh_session_struct::dh_handshake_state, DH_STATE_INIT_SENT, error, ssh_session_struct::next_crypto, ssh_session_struct::out_buffer, pubkey, rc, session, SSH2_MSG_KEXDH_INIT, ssh_buffer_pack, ssh_dh_cleanup, ssh_dh_client_callbacks, ssh_dh_init_common, ssh_dh_keypair_gen_keys, ssh_dh_keypair_get_keys, SSH_ERROR, SSH_OK, ssh_packet_send, ssh_packet_set_callbacks.
Referenced by dh_handshake.
bool ssh_dh_is_known_group(bignum modulus, bignum generator)
References bits, m, ssh_dh_generator, ssh_dh_group14, ssh_dh_group16, ssh_dh_group18, SSH_LOG, SSH_LOG_TRACE.
Referenced by SSH_PACKET_CALLBACK.
ssh_key ssh_dh_get_current_server_publickey(ssh_session session)
References ssh_session_struct::current_crypto, ssh_crypto_struct::server_pubkey, session.
Referenced by ssh_dh_get_current_server_publickey_blob, ssh_dump_knownhost, ssh_is_server_known, ssh_session_export_known_hosts_entry.
int ssh_dh_get_current_server_publickey_blob(ssh_session session, ssh_string *pubkey_blob)
References pubkey, session, ssh_dh_get_current_server_publickey, ssh_pki_export_pubkey_blob.
Referenced by check_public_key, ssh_get_pubkey.
ssh_key ssh_dh_get_next_server_publickey(ssh_session session)
References ssh_session_struct::next_crypto, ssh_crypto_struct::server_pubkey, session.
Referenced by ssh_dh_get_next_server_publickey_blob, SSH_PACKET_CALLBACK.
int ssh_dh_get_next_server_publickey_blob(ssh_session session, ssh_string *pubkey_blob)
References pubkey, session, ssh_dh_get_next_server_publickey, ssh_pki_export_pubkey_blob.
Referenced by ssh_make_sessionid.
static char* ssh_get_b64_unpadded(const unsigned char *hash, size_t len)
References bin_to_base64, k, SAFE_FREE, strndup.
Referenced by ssh_get_fingerprint_hash, torture_sha1_hash, torture_sha256_hash.
char* ssh_get_fingerprint_hash(enum ssh_publickey_hash_type type, unsigned char *hash, size_t len)
Get a hash as a human-readable hex- or base64-string.
This gets an allocated fingerprint hash. If it is a SHA sum, it will return an unpadded base64 strings. If it is a MD5 sum, it will return hex string. Either way, the output is prepended by the hash-type. Do NOT use MD5 or SHA1! Those hash functions are being deprecated. type Which sort of hash is given, use SSH_PUBLICKEY_HASH_SHA256 or better. hash The hash to be converted to fingerprint. len Length of the buffer to convert. Returns the allocated fingerprint hash or NULL on error. ssh_string_free_char()
References rc, SAFE_FREE, ssh_get_b64_unpadded, ssh_get_hexa, SSH_PUBLICKEY_HASH_MD5, SSH_PUBLICKEY_HASH_SHA1, SSH_PUBLICKEY_HASH_SHA256.
Referenced by ssh_print_hash, torture_sha256_fingerprint.
void ssh_print_hash(enum ssh_publickey_hash_type type, unsigned char *hash, size_t len)
Print a hash as a human-readable hex- or base64-string.
This prints an unpadded base64 strings for SHA sums and hex strings for MD5 sum. Either way, the output is prepended by the hash-type. type Which sort of hash is given. Use SSH_PUBLICKEY_HASH_SHA256 or better. hash The hash to be converted to fingerprint. len Length of the buffer to convert. ssh_get_publickey_hash() ssh_get_fingerprint_hash()
References SAFE_FREE, ssh_get_fingerprint_hash.
Referenced by verify_knownhost.