dh.h
DH_CLIENT_KEYPAIR
DH_SERVER_KEYPAIR
int ssh_dh_init_common(struct ssh_crypto_struct *crypto)
References ctx, ssh_crypto_struct::dh_ctx, ssh_crypto_struct::kex_type, rc, ssh_dh_cleanup, ssh_dh_generator, ssh_dh_group1, ssh_dh_group14, ssh_dh_group16, ssh_dh_group18, ssh_dh_set_parameters, SSH_ERROR, SSH_KEX_DH_GROUP14_SHA1, SSH_KEX_DH_GROUP16_SHA512, SSH_KEX_DH_GROUP18_SHA512, SSH_KEX_DH_GROUP1_SHA1, SSH_OK.
Referenced by ssh_client_dh_init, ssh_client_dhgex_init.
void ssh_dh_cleanup(struct ssh_crypto_struct *crypto)
References ctx, DH_CLIENT_KEYPAIR, ssh_crypto_struct::dh_ctx, DH_SERVER_KEYPAIR, dh_ctx::keypair, ssh_dh_free_dh_keypair, ssh_dh_free_generator, ssh_dh_free_modulus.
Referenced by crypto_free, ssh_client_dh_init, ssh_client_dhgex_init, ssh_dh_init_common, SSH_PACKET_CALLBACK.
int ssh_dh_get_parameters(struct dh_ctx *ctx, const_bignum *modulus, const_bignum *generator)
References ctx, DH_get0_pqg, SSH_ERROR, SSH_OK.
Referenced by ssh_make_sessionid.
int ssh_dh_set_parameters(struct dh_ctx *ctx, const bignum modulus, const bignum generator)
References ctx, DH_CLIENT_KEYPAIR, DH_SERVER_KEYPAIR, DH_set0_pqg, rc, ssh_dh_free_dh_keypair, ssh_dh_free_generator, ssh_dh_free_modulus, ssh_dh_init_dh_keypair, SSH_ERROR, SSH_OK.
Referenced by ssh_dh_init_common, SSH_PACKET_CALLBACK.
int ssh_dh_keypair_gen_keys(struct dh_ctx *ctx, int peer)
References bits, ctx, DH_SECURITY_BITS, error, dh_ctx::generator, dh_ctx::keypair, MIN, dh_ctx::modulus, rc, SSH_ERROR, SSH_OK.
Referenced by ssh_client_dh_init, SSH_PACKET_CALLBACK.
int ssh_dh_keypair_get_keys(struct dh_ctx *ctx, int peer, const_bignum *priv, const_bignum *pub)
References ctx, DH_CLIENT_KEYPAIR, DH_get0_key, DH_SERVER_KEYPAIR, SSH_ERROR, SSH_OK.
Referenced by ssh_client_dh_init, ssh_dh_compute_shared_secret, ssh_dh_debug_crypto, ssh_make_sessionid, SSH_PACKET_CALLBACK.
int ssh_dh_keypair_set_keys(struct dh_ctx *ctx, int peer, const bignum priv, const bignum pub)
References ctx, DH_CLIENT_KEYPAIR, DH_SERVER_KEYPAIR, DH_set0_key, SSH_ERROR, SSH_OK.
Referenced by SSH_PACKET_CALLBACK.
int ssh_dh_compute_shared_secret(struct dh_ctx *ctx, int local, int remote, bignum *dest)
References ctx, dh_ctx::keypair, dh_ctx::modulus, rc, ssh_dh_keypair_get_keys, SSH_ERROR, SSH_OK.
Referenced by SSH_PACKET_CALLBACK.
void ssh_dh_debug_crypto(struct ssh_crypto_struct *c)
References ssh_crypto_struct::client_kex, ssh_kex_struct::cookie, DH_CLIENT_KEYPAIR, ssh_crypto_struct::dh_ctx, DH_SERVER_KEYPAIR, dh_ctx::generator, dh_ctx::modulus, ssh_crypto_struct::server_kex, ssh_crypto_struct::shared_secret, ssh_dh_keypair_get_keys, ssh_log_hexdump, ssh_print_bignum.
Referenced by SSH_PACKET_CALLBACK.
int ssh_dh_init(void)
References dh_crypto_initialized, error, P_GROUP14_LEN, p_group14_value, P_GROUP16_LEN, p_group16_value, P_GROUP18_LEN, p_group18_value, P_GROUP1_LEN, p_group1_value, rc, ssh_dh_finalize, ssh_dh_generator, ssh_dh_group1, ssh_dh_group14, ssh_dh_group16, ssh_dh_group18, SSH_ERROR, SSH_OK.
Referenced by libssh_constructor.
void ssh_dh_finalize(void)
References dh_crypto_initialized, ssh_dh_generator, ssh_dh_group1, ssh_dh_group14, ssh_dh_group16, ssh_dh_group18.
Referenced by _ssh_finalize, ssh_dh_init.
int ssh_dh_import_next_pubkey_blob(ssh_session session, ssh_string pubkey_blob)
References ssh_session_struct::next_crypto, ssh_crypto_struct::server_pubkey, session, ssh_pki_import_pubkey_blob.
Referenced by ssh_get_key_params, SSH_PACKET_CALLBACK.
ssh_key ssh_dh_get_current_server_publickey(ssh_session session)
References ssh_session_struct::current_crypto, ssh_crypto_struct::server_pubkey, session.
Referenced by ssh_dh_get_current_server_publickey_blob, ssh_dump_knownhost, ssh_is_server_known, ssh_session_export_known_hosts_entry.
int ssh_dh_get_current_server_publickey_blob(ssh_session session, ssh_string *pubkey_blob)
References pubkey, session, ssh_dh_get_current_server_publickey, ssh_pki_export_pubkey_blob.
Referenced by check_public_key, ssh_get_pubkey.
ssh_key ssh_dh_get_next_server_publickey(ssh_session session)
References ssh_session_struct::next_crypto, ssh_crypto_struct::server_pubkey, session.
Referenced by ssh_dh_get_next_server_publickey_blob, SSH_PACKET_CALLBACK.
int ssh_dh_get_next_server_publickey_blob(ssh_session session, ssh_string *pubkey_blob)
References pubkey, session, ssh_dh_get_next_server_publickey, ssh_pki_export_pubkey_blob.
Referenced by ssh_make_sessionid.
int ssh_client_dh_init(ssh_session session)
References DH_CLIENT_KEYPAIR, ssh_crypto_struct::dh_ctx, ssh_session_struct::dh_handshake_state, DH_STATE_INIT_SENT, error, ssh_session_struct::next_crypto, ssh_session_struct::out_buffer, pubkey, rc, session, SSH2_MSG_KEXDH_INIT, ssh_buffer_pack, ssh_dh_cleanup, ssh_dh_client_callbacks, ssh_dh_init_common, ssh_dh_keypair_gen_keys, ssh_dh_keypair_get_keys, SSH_ERROR, SSH_OK, ssh_packet_send, ssh_packet_set_callbacks.
Referenced by dh_handshake.
int ssh_server_dh_process_init(ssh_session session, ssh_buffer packet)
int ssh_fallback_group(uint32_t pmax, bignum *p, bignum *g)
bool ssh_dh_is_known_group(bignum modulus, bignum generator)
References bits, m, ssh_dh_generator, ssh_dh_group14, ssh_dh_group16, ssh_dh_group18, SSH_LOG, SSH_LOG_TRACE.
Referenced by SSH_PACKET_CALLBACK.