ed25519.c
F
static int crypto_verify_32(const unsigned char *x, const unsigned char *y)
References F.
Referenced by crypto_sign_ed25519_open.
static void get_hram(unsigned char *hram, const unsigned char *sm, const unsigned char *pk, unsigned char *playground, uint64_t smlen)
References ctx, sha512_final, sha512_init, sha512_update.
Referenced by crypto_sign_ed25519, crypto_sign_ed25519_open.
int crypto_sign_ed25519_keypair(unsigned char *pk, unsigned char *sk)
References ctx, ge25519_pack, ge25519_scalarmult_base, sc25519_from32bytes, sha512_final, sha512_init, sha512_update, ssh_get_random.
int crypto_sign_ed25519(unsigned char *sm, uint64_t *smlen, const unsigned char *m, uint64_t mlen, const unsigned char *sk)
References ctx, ge25519_pack, ge25519_scalarmult_base, get_hram, m, s, sc25519_add, sc25519_from32bytes, sc25519_from64bytes, sc25519_mul, sc25519_to32bytes, sha512_final, sha512_init, sha512_update.
int crypto_sign_ed25519_open(unsigned char *m, uint64_t *mlen, const unsigned char *sm, uint64_t smlen, const unsigned char *pk)
References crypto_verify_32, ge25519_base, ge25519_double_scalarmult_vartime, ge25519_pack, ge25519_unpackneg_vartime, get_hram, m, sc25519_from32bytes, sc25519_from64bytes.