authentication.c
int authenticate_kbdint(ssh_session session, const char *password)
References buffer, echo, instruction, name, session, SSH_AUTH_ERROR, SSH_AUTH_INFO, ssh_getpass, ssh_userauth_kbdint, ssh_userauth_kbdint_getinstruction, ssh_userauth_kbdint_getname, ssh_userauth_kbdint_getnprompts, ssh_userauth_kbdint_getprompt, ssh_userauth_kbdint_setanswer.
Referenced by authenticate_console.
static int auth_keyfile(ssh_session session, char *keyfile)
References key, pubkey, rc, session, SSH_AUTH_DENIED, SSH_AUTH_SUCCESS, ssh_key_free, SSH_OK, ssh_pki_import_privkey_file, ssh_pki_import_pubkey_file, ssh_userauth_publickey, ssh_userauth_try_publickey.
Referenced by authenticate_console.
static void error(ssh_session session)
References session, ssh_get_error.
Referenced by authenticate_console.
int authenticate_console(ssh_session session)
References auth_keyfile, authenticate_kbdint, buffer, error, rc, session, SSH_AUTH_ERROR, SSH_AUTH_METHOD_GSSAPI_MIC, SSH_AUTH_METHOD_INTERACTIVE, SSH_AUTH_METHOD_PASSWORD, SSH_AUTH_METHOD_PUBLICKEY, SSH_AUTH_SUCCESS, ssh_get_issue_banner, ssh_getpass, SSH_STRING_FREE_CHAR, ssh_userauth_gssapi, ssh_userauth_list, ssh_userauth_none, ssh_userauth_password, ssh_userauth_publickey_auto.
Referenced by client, connect_ssh.