fe25519.h
fe25519
fe25519_freeze
fe25519_unpack
fe25519_pack
fe25519_iszero
fe25519_iseq_vartime
fe25519_cmov
fe25519_setone
fe25519_setzero
fe25519_neg
fe25519_getparity
fe25519_add
fe25519_sub
fe25519_mul
fe25519_square
fe25519_invert
fe25519_pow2523
void fe25519_freeze(fe25519 *r)
References equal, ge, m, fe25519::v.
Referenced by fe25519_getparity, fe25519_iseq_vartime, fe25519_iszero, fe25519_pack.
void fe25519_unpack(fe25519 *r, const unsigned char x[32])
References fe25519::v.
void fe25519_pack(unsigned char r[32], const fe25519 *x)
References fe25519_freeze, fe25519::v.
uint32_t fe25519_iszero(const fe25519 *x)
References equal, fe25519_freeze, fe25519::v.
int fe25519_iseq_vartime(const fe25519 *x, const fe25519 *y)
References fe25519_freeze, fe25519::v.
void fe25519_cmov(fe25519 *r, const fe25519 *x, unsigned char b)
References fe25519::v.
void fe25519_setone(fe25519 *r)
References fe25519::v.
void fe25519_setzero(fe25519 *r)
References fe25519::v.
Referenced by fe25519_neg.
void fe25519_neg(fe25519 *r, const fe25519 *x)
References fe25519_setzero, fe25519_sub, fe25519::v.
unsigned char fe25519_getparity(const fe25519 *x)
References fe25519_freeze, fe25519::v.
void fe25519_add(fe25519 *r, const fe25519 *x, const fe25519 *y)
References reduce_add_sub, fe25519::v.
void fe25519_sub(fe25519 *r, const fe25519 *x, const fe25519 *y)
References reduce_add_sub, fe25519::v.
Referenced by fe25519_neg.
void fe25519_mul(fe25519 *r, const fe25519 *x, const fe25519 *y)
References reduce_mul, times38, fe25519::v.
Referenced by fe25519_invert, fe25519_pow2523, fe25519_square.
void fe25519_square(fe25519 *r, const fe25519 *x)
References fe25519_mul.
Referenced by fe25519_invert, fe25519_pow2523.
void fe25519_invert(fe25519 *r, const fe25519 *x)
References fe25519_mul, fe25519_square.
void fe25519_pow2523(fe25519 *r, const fe25519 *x)
References fe25519_mul, fe25519_square.