ge25519.c
ge25519_p3
const fe25519 ge25519_ecd
Referenced by ge25519_unpackneg_vartime.
const fe25519 ge25519_ec2d
Referenced by add_p1p1, ge25519_mixadd2.
const fe25519 ge25519_sqrtm1
Referenced by ge25519_unpackneg_vartime.
const ge25519 ge25519_base
const ge25519_aff ge25519_base_multiples_affine[425][425]
Referenced by choose_t.
static void p1p1_to_p2(ge25519_p2 *r, const ge25519_p1p1 *p)
References fe25519_mul, ge25519_p1p1::t, ge25519_p1p1::x, ge25519_p2::x, ge25519_p1p1::y, ge25519_p2::y, ge25519_p1p1::z, ge25519_p2::z.
Referenced by ge25519_double_scalarmult_vartime, p1p1_to_p3.
static void p1p1_to_p3(ge25519_p3 *r, const ge25519_p1p1 *p)
References fe25519_mul, p1p1_to_p2, ge25519_p1p1::x, ge25519_p1p1::y.
Referenced by ge25519_double_scalarmult_vartime.
static void ge25519_mixadd2(ge25519_p3 *r, const ge25519_aff *q)
References generate.a, fe25519_add, fe25519_mul, fe25519_sub, ge25519_ec2d, ge25519_aff::x, ge25519_aff::y.
Referenced by ge25519_scalarmult_base.
static void add_p1p1(ge25519_p1p1 *r, const ge25519_p3 *p, const ge25519_p3 *q)
References generate.a, fe25519_add, fe25519_mul, fe25519_sub, ge25519_ec2d, ge25519_p1p1::t, ge25519_p1p1::x, ge25519_p1p1::y, ge25519_p1p1::z.
Referenced by ge25519_double_scalarmult_vartime.
static void dbl_p1p1(ge25519_p1p1 *r, const ge25519_p2 *p)
References generate.a, fe25519_add, fe25519_neg, fe25519_square, fe25519_sub, ge25519_p1p1::t, ge25519_p1p1::x, ge25519_p2::x, ge25519_p1p1::y, ge25519_p2::y, ge25519_p1p1::z, ge25519_p2::z.
Referenced by ge25519_double_scalarmult_vartime.
static void cmov_aff(ge25519_aff *r, const ge25519_aff *p, unsigned char b)
References fe25519_cmov, ge25519_aff::x, ge25519_aff::y.
Referenced by choose_t.
static unsigned char equal(signed char b, signed char c)
Referenced by choose_t.
static unsigned char negative(signed char b)
Referenced by choose_t, freeze.
static void choose_t(ge25519_aff *t, unsigned long long pos, signed char b)
References cmov_aff, equal, fe25519_cmov, fe25519_neg, ge25519_base_multiples_affine, negative, ge25519_aff::x.
Referenced by ge25519_scalarmult_base.
static void setneutral(ge25519 *r)
References fe25519_setone, fe25519_setzero, ge25519::t, ge25519::x, ge25519::y, ge25519::z.
Referenced by ge25519_double_scalarmult_vartime.
int ge25519_unpackneg_vartime(ge25519_p3 *r, const unsigned char p[32])
References fe25519_add, fe25519_getparity, fe25519_iseq_vartime, fe25519_mul, fe25519_neg, fe25519_pow2523, fe25519_setone, fe25519_square, fe25519_sub, fe25519_unpack, ge25519_ecd, ge25519_sqrtm1.
void ge25519_pack(unsigned char r[32], const ge25519_p3 *p)
References fe25519_getparity, fe25519_invert, fe25519_mul, fe25519_pack.
int ge25519_isneutral_vartime(const ge25519_p3 *p)
References fe25519_iseq_vartime, fe25519_iszero.
void ge25519_double_scalarmult_vartime(ge25519_p3 *r, const ge25519_p3 *p1, const sc25519 *s1, const ge25519_p3 *p2, const sc25519 *s2)
References add_p1p1, dbl_p1p1, ge25519_p3, p1p1_to_p2, p1p1_to_p3, sc25519_2interleave2, setneutral.
void ge25519_scalarmult_base(ge25519_p3 *r, const sc25519 *s)
References choose_t, fe25519_mul, fe25519_setone, ge25519_mixadd2, s, sc25519_window3.