libssh_error
void _ssh_set_error(void *error, int code, const char *function, const char *descr,...)
References error, ssh_common_struct::error, error_struct::error_buffer, ERROR_BUFFERLEN, error_struct::error_code, ssh_get_log_level, ssh_log_function, SSH_LOG_WARN.
Referenced by _ssh_set_error_invalid.
void _ssh_set_error_oom(void *error, const char *function)
References error, error_struct::error_buffer, error_struct::error_code, SSH_FATAL.
void _ssh_set_error_invalid(void *error, const char *function)
References _ssh_set_error, error, SSH_FATAL.
void ssh_reset_error(void *error)
References error, ssh_common_struct::error, error_struct::error_buffer, error_struct::error_code, ZERO_STRUCT.
Referenced by SSH_PACKET_CALLBACK.
const char* ssh_get_error(void *error)
Retrieve the error text message from the last error.
error An ssh_session or ssh_bind. A static string describing the error.
References error, error_struct::error_buffer.
Referenced by _assert_ssh_return_code, _assert_ssh_return_code_equal, _assert_ssh_return_code_not_equal, authenticate, batch_shell, benchmarks_async_sftp_down, benchmarks_raw_down, benchmarks_raw_up, benchmarks_scp_down, benchmarks_scp_up, benchmarks_ssh_latency, benchmarks_sync_sftp_down, benchmarks_sync_sftp_up, channel_new_session_cb, client, connect_host, connect_ssh, create_files, default_handle_session_cb, do_connect, error, fetch_files, forwarding, ssh::Session::getError, handle_kbdint_session_cb, handle_session, main, pkd_channel_openreq_cb, pkd_exec_hello, run_server, select_loop, set_opts, sftp_test, shell, ssh_client, SSH_PACKET_CALLBACK, ssh_packet_process, ssh_server, ssh_try_publickey_from_file, ssh::SshException::SshException, torture_sftp_mkdir, upload_script, verify_knownhost.
int ssh_get_error_code(void *error)
Retrieve the error code from the last error.
error An ssh_session or ssh_bind. SSH_NO_ERROR No error occurred SSH_REQUEST_DENIED The last request was denied but situation is recoverable SSH_FATAL A fatal error occurred. This could be an unexpected disconnection Other error codes are internal but can be considered same than SSH_FATAL.
References error, error_struct::error_code.
Referenced by benchmarks_ssh_latency, ssh::Session::getErrorCode, ssh::SshException::SshException, test_algorithm, torture_algorithms_zlib, torture_algorithms_zlib_openssh, torture_auth_agent, torture_auth_agent_nonblocking, torture_auth_autopubkey, torture_auth_autopubkey_nonblocking, torture_auth_kbdint, torture_auth_kbdint_nonblocking, torture_auth_none, torture_auth_none_nonblocking, torture_auth_password, torture_auth_password_nonblocking, torture_auth_pubkey_types, torture_auth_pubkey_types_ecdsa, torture_auth_pubkey_types_ecdsa_nonblocking, torture_auth_pubkey_types_ed25519, torture_auth_pubkey_types_ed25519_nonblocking, torture_auth_pubkey_types_nonblocking, torture_rekey_send, torture_rekey_server_send, torture_rekey_time, torture_server_auth_kbdint, torture_server_auth_none, torture_server_auth_password, torture_server_auth_pubkey, try_config_content.