libssh_channel
ssh_channel ssh_channel_read_termination_struct::channel
Referenced by ssh_channel_exit_status_termination, ssh_channel_get_exit_status, ssh_channel_get_session, ssh_channel_poll, ssh_channel_poll_timeout, ssh_channel_read, ssh_channel_read_nonblocking, ssh_channel_read_timeout.
uint32_t ssh_channel_read_termination_struct::count
Referenced by ssh_channel_read, ssh_channel_read_nonblocking, ssh_channel_read_timeout.
ssh_buffer ssh_channel_read_termination_struct::buffer
static ssh_channel channel_from_msg(ssh_session session, ssh_buffer packet)
References chan, rc, session, ssh_buffer_unpack, ssh_channel_from_local, SSH_FATAL, SSH_OK, ssh_set_error.
Referenced by SSH_PACKET_CALLBACK.
ssh_channel ssh_channel_new(ssh_session session)
Allocate a new channel.
session The ssh session to use. A pointer to a newly allocated channel, NULL on error.
References ssh_session_struct::channels, ssh_channel_struct::exit_status, ssh_channel_struct::flags, ssh_session_struct::flags, ssh_channel_struct::request_state, SAFE_FREE, ssh_channel_struct::session, session, SSH_BUFFER_FREE, ssh_buffer_new, SSH_CHANNEL_FLAG_NOT_BOUND, SSH_CHANNEL_REQ_STATE_NONE, SSH_CHANNEL_STATE_NOT_OPEN, ssh_list_new, ssh_list_prepend, SSH_SESSION_FLAG_AUTHENTICATED, ssh_set_error_oom, ssh_channel_struct::state, ssh_channel_struct::stderr_buffer, ssh_channel_struct::stdout_buffer.
Referenced by batch_shell, benchmarks_raw_down, benchmarks_raw_up, benchmarks_ssh_latency, ssh::Channel::Channel, channel_new, channel_new_session_cb, channel_open, client_thread, create_files, do_connect, forwarding, LLVMFuzzerTestOneInput, main, new_session_channel, pkd_channel_openreq_cb, shell, ssh_message_channel_request_open_reply_accept, ssh_scp_init, torture_channel_read_error, torture_request_env, torture_server_unknown_global_request, torture_unknown_request, upload_script.
uint32_t ssh_channel_new_id(ssh_session session)
References ssh_session_struct::maxchannel, session.
Referenced by channel_open, ssh_message_channel_request_open_reply_accept_channel.
SSH_PACKET_CALLBACK(ssh_packet_channel_open_conf)
References error, ssh_channel_struct::flags, ssh_channel_struct::local_channel, rc, ssh_channel_struct::remote_channel, ssh_channel_struct::remote_maxpacket, ssh_channel_struct::remote_window, session, ssh_buffer_unpack, SSH_CHANNEL_FLAG_NOT_BOUND, ssh_channel_from_local, SSH_CHANNEL_STATE_OPEN, SSH_CHANNEL_STATE_OPENING, SSH_FATAL, SSH_LOG, SSH_LOG_PACKET, SSH_LOG_PROTOCOL, SSH_LOG_RARE, SSH_OK, SSH_PACKET_USED, ssh_set_error, ssh_channel_struct::state, user.
SSH_PACKET_CALLBACK(ssh_packet_channel_open_fail)
References channel_from_msg, error, ssh_channel_struct::local_channel, rc, SAFE_FREE, session, ssh_buffer_unpack, SSH_CHANNEL_STATE_OPEN_DENIED, SSH_CHANNEL_STATE_OPENING, SSH_FATAL, SSH_LOG, SSH_LOG_RARE, SSH_OK, SSH_PACKET_USED, SSH_REQUEST_DENIED, ssh_set_error, ssh_channel_struct::state, user.
static int ssh_channel_open_termination(void *c)
References ssh_channel_struct::session, ssh_session_struct::session_state, SSH_CHANNEL_STATE_OPENING, SSH_SESSION_STATE_ERROR, ssh_channel_struct::state.
Referenced by channel_open.
static int channel_open(ssh_channel channel, const char *type, uint32_t window, uint32_t maxpacket, ssh_buffer payload)
References ssh_channel_struct::local_channel, ssh_channel_struct::local_maxpacket, ssh_channel_struct::local_window, ssh_session_struct::out_buffer, rc, ssh_channel_struct::session, session, ssh_session_struct::session_state, SSH2_MSG_CHANNEL_OPEN, SSH_AGAIN, ssh_buffer_add_buffer, ssh_buffer_pack, ssh_channel_new_id, ssh_channel_open_termination, SSH_CHANNEL_STATE_CLOSED, SSH_CHANNEL_STATE_NOT_OPEN, SSH_CHANNEL_STATE_OPEN, SSH_CHANNEL_STATE_OPEN_DENIED, SSH_CHANNEL_STATE_OPENING, SSH_ERROR, SSH_FATAL, ssh_handle_packets_termination, SSH_LOG, SSH_LOG_PACKET, SSH_LOG_PROTOCOL, SSH_OK, ssh_packet_send, SSH_SESSION_STATE_ERROR, ssh_set_error, ssh_set_error_oom, SSH_TIMEOUT_DEFAULT, ssh_channel_struct::state.
Referenced by ssh_channel_open_auth_agent, ssh_channel_open_forward, ssh_channel_open_forward_unix, ssh_channel_open_session.
ssh_channel ssh_channel_from_local(ssh_session session, uint32_t id)
References ssh_session_struct::channels, ssh_channel_struct::local_channel, ssh_iterator::next, session, ssh_iterator_value, ssh_list_get_iterator.
Referenced by channel_from_msg, SSH_PACKET_CALLBACK.
static int grow_window(ssh_session session, ssh_channel channel, uint32_t minimumsize)
References error, ssh_channel_struct::local_channel, ssh_channel_struct::local_window, ssh_session_struct::out_buffer, rc, ssh_channel_struct::remote_channel, session, SSH2_MSG_CHANNEL_WINDOW_ADJUST, ssh_buffer_pack, ssh_buffer_reinit, SSH_ERROR, SSH_LOG, SSH_LOG_PROTOCOL, SSH_OK, ssh_packet_send, ssh_set_error_oom, WINDOWBASE.
Referenced by ssh_channel_read_timeout, SSH_PACKET_CALLBACK.
SSH_PACKET_CALLBACK(channel_rcv_change_window)
References channel_from_msg, ssh_channel_struct::local_channel, rc, ssh_channel_struct::remote_channel, ssh_channel_struct::remote_window, session, ssh_buffer_unpack, ssh_get_error, SSH_LOG, SSH_LOG_FUNCTIONS, SSH_LOG_PACKET, SSH_LOG_PROTOCOL, SSH_OK, SSH_PACKET_USED, user.
SSH_PACKET_CALLBACK(channel_rcv_data)
References ssh_channel_struct::callbacks, channel_default_bufferize, channel_from_msg, ssh_channel_struct::counter, grow_window, ssh_counter_struct::in_bytes, ssh_channel_struct::local_window, PRIdS, ssh_channel_struct::remote_window, ssh_channel_struct::session, session, SSH2_MSG_CHANNEL_DATA, ssh_buffer_get, ssh_buffer_get_len, ssh_buffer_get_ssh_string, ssh_buffer_get_u32, ssh_buffer_pass_bytes, ssh_callbacks_iterate, ssh_callbacks_iterate_end, ssh_callbacks_iterate_exec, ssh_get_error, SSH_LOG, SSH_LOG_FUNCTIONS, SSH_LOG_PACKET, SSH_LOG_RARE, SSH_PACKET_USED, ssh_string_data, SSH_STRING_FREE, ssh_string_len, ssh_channel_struct::stderr_buffer, ssh_channel_struct::stdout_buffer, user, WINDOWLIMIT.
SSH_PACKET_CALLBACK(channel_rcv_eof)
References ssh_channel_struct::callbacks, channel_from_msg, ssh_channel_struct::local_channel, ssh_channel_struct::remote_channel, ssh_channel_struct::remote_eof, ssh_channel_struct::session, session, ssh_callbacks_execute_list, ssh_get_error, SSH_LOG, SSH_LOG_FUNCTIONS, SSH_LOG_PACKET, SSH_PACKET_USED, user.
SSH_PACKET_CALLBACK(channel_rcv_close)
References ssh_channel_struct::callbacks, channel_from_msg, ssh_channel_struct::delayed_close, ssh_channel_struct::flags, ssh_channel_struct::local_channel, ssh_channel_struct::remote_channel, ssh_channel_struct::remote_eof, ssh_channel_struct::session, session, ssh_buffer_get_len, ssh_callbacks_execute_list, ssh_channel_do_free, SSH_CHANNEL_FLAG_CLOSED_REMOTE, SSH_CHANNEL_FLAG_FREED_LOCAL, SSH_CHANNEL_STATE_CLOSED, ssh_get_error, SSH_LOG, SSH_LOG_FUNCTIONS, SSH_LOG_PACKET, SSH_PACKET_USED, ssh_channel_struct::state, ssh_channel_struct::stderr_buffer, ssh_channel_struct::stdout_buffer, user.
SSH_PACKET_CALLBACK(channel_rcv_request)
References ssh_channel_struct::callbacks, channel_from_msg, ssh_channel_struct::exit_status, ssh_session_struct::out_buffer, rc, ssh_channel_struct::remote_channel, SAFE_FREE, ssh_channel_struct::session, session, SSH2_MSG_CHANNEL_FAILURE, ssh_buffer_pack, ssh_buffer_unpack, ssh_callbacks_execute_list, ssh_get_error, SSH_LOG, SSH_LOG_FUNCTIONS, SSH_LOG_PACKET, SSH_LOG_PROTOCOL, SSH_LOG_WARNING, ssh_message_handle_channel_request, SSH_OK, ssh_packet_send, SSH_PACKET_USED, user.
int channel_default_bufferize(ssh_channel channel, void *data, size_t len, bool is_stderr)
References ssh_iterator::data, ssh_channel_struct::session, session, ssh_buffer_add_data, SSH_BUFFER_FREE, ssh_buffer_new, SSH_LOG, SSH_LOG_PACKET, ssh_set_error_invalid, ssh_set_error_oom, ssh_channel_struct::stderr_buffer, ssh_channel_struct::stdout_buffer.
Referenced by SSH_PACKET_CALLBACK.
int ssh_channel_open_session(ssh_channel channel)
Open a session channel (suited for a shell, not TCP forwarding).
channel An allocated channel. SSH_OK on success, SSH_ERROR if an error occurred, SSH_AGAIN if in nonblocking mode and call has to be done again. ssh_channel_open_forward() ssh_channel_request_env() ssh_channel_request_shell() ssh_channel_request_exec()
References CHANNEL_INITIAL_WINDOW, CHANNEL_MAX_PACKET, channel_open, SSH_ERROR.
Referenced by batch_shell, benchmarks_raw_down, benchmarks_raw_up, benchmarks_ssh_latency, channel_open_session, client_thread, create_files, do_connect, LLVMFuzzerTestOneInput, main, ssh::Channel::openSession, shell, ssh_scp_init, torture_channel_read_error, torture_request_env, torture_server_unknown_global_request, torture_unknown_request, upload_script.
int ssh_channel_open_auth_agent(ssh_channel channel)
Open an agent authentication forwarding channel. This type of channel can be opened by a server towards a client in order to provide SSH-Agent services to the server-side process. This channel can only be opened if the client claimed support by sending a channel request beforehand.
channel An allocated channel. SSH_OK on success, SSH_ERROR if an error occurred, SSH_AGAIN if in nonblocking mode and call has to be done again. ssh_channel_open_forward()
References CHANNEL_INITIAL_WINDOW, CHANNEL_MAX_PACKET, channel_open, SSH_ERROR.
int ssh_channel_open_forward(ssh_channel channel, const char *remotehost, int remoteport, const char *sourcehost, int localport)
Open a TCP/IP forwarding channel.
channel An allocated channel. remotehost The remote host to connected (host name or IP). remoteport The remote port. sourcehost The numeric IP address of the machine from where the connection request originates. This is mostly for logging purposes. localport The port on the host from where the connection originated. This is mostly for logging purposes. SSH_OK on success, SSH_ERROR if an error occurred, SSH_AGAIN if in nonblocking mode and call has to be done again. This function does not bind the local port and does not automatically forward the content of a socket to the channel. You still have to use channel_read and channel_write for this.
References CHANNEL_INITIAL_WINDOW, CHANNEL_MAX_PACKET, channel_open, error, rc, ssh_channel_struct::session, session, SSH_BUFFER_FREE, ssh_buffer_new, ssh_buffer_pack, SSH_ERROR, SSH_OK, ssh_set_error_invalid, ssh_set_error_oom, SSH_STRING_FREE.
Referenced by channel_open_forward, do_connect, forwarding, ssh::Channel::openForward.
int ssh_channel_open_forward_unix(ssh_channel channel, const char *remotepath, const char *sourcehost, int localport)
Open a TCP/IP - UNIX domain socket forwarding channel.
channel An allocated channel. remotepath The UNIX socket path on the remote machine sourcehost The numeric IP address of the machine from where the connection request originates. This is mostly for logging purposes. localport The port on the host from where the connection originated. This is mostly for logging purposes. SSH_OK on success, SSH_ERROR if an error occurred, SSH_AGAIN if in nonblocking mode and call has to be done again. This function does not bind the local port and does not automatically forward the content of a socket to the channel. You still have to use channel_read and channel_write for this. Requires support of OpenSSH for UNIX domain socket forwarding.
References CHANNEL_INITIAL_WINDOW, CHANNEL_MAX_PACKET, channel_open, error, rc, ssh_channel_struct::session, session, SSH_BUFFER_FREE, ssh_buffer_new, ssh_buffer_pack, SSH_ERROR, ssh_get_openssh_version, SSH_OK, SSH_REQUEST_DENIED, ssh_set_error, ssh_set_error_invalid, ssh_set_error_oom, SSH_STRING_FREE.
void ssh_channel_free(ssh_channel channel)
Close and free a channel.
channel The channel to free. Any data unread on this channel will be lost.
References ssh_session_struct::alive, ssh_channel_struct::flags, ssh_channel_struct::session, session, ssh_channel_close, ssh_channel_do_free, SSH_CHANNEL_FLAG_CLOSED_LOCAL, SSH_CHANNEL_FLAG_CLOSED_REMOTE, SSH_CHANNEL_FLAG_FREED_LOCAL, SSH_CHANNEL_FLAG_NOT_BOUND, SSH_CHANNEL_STATE_CLOSED, SSH_CHANNEL_STATE_OPEN, ssh_channel_struct::state.
Referenced by batch_shell, benchmarks_raw_down, benchmarks_raw_up, benchmarks_ssh_latency, channel_free, create_files, do_cleanup, do_connect, LLVMFuzzerTestOneInput, main, pkd_channel_openreq_cb, pkd_exec_hello, select_loop, shell, ssh_message_channel_request_open_reply_accept, ssh_scp_close, ssh_scp_free, torture_channel_read_error, upload_script, ssh::Channel::~Channel.
void ssh_channel_do_free(ssh_channel channel)
References ssh_channel_struct::callbacks, ssh_session_struct::channels, SAFE_FREE, ssh_channel_struct::session, session, SSH_BUFFER_FREE, ssh_list_find, ssh_list_free, ssh_list_remove, ssh_channel_struct::stderr_buffer, ssh_channel_struct::stdout_buffer.
Referenced by ssh_channel_free, ssh_disconnect, ssh_free, SSH_PACKET_CALLBACK.
int ssh_channel_send_eof(ssh_channel channel)
Send an end of file on the channel.
This doesn't close the channel. You may still read from it but not write. channel The channel to send the eof to. SSH_OK on success, SSH_ERROR if an error occurred. Example: rc=ssh_channel_send_eof(channel); if(rc==SSH_ERROR){ return-1; } while(!ssh_channel_is_eof(channel)){ rc=ssh_channel_read(channel,buf,sizeof(buf),0); if(rc==SSH_ERROR){ return-1; } } ssh_channel_close(channel); ssh_channel_close() ssh_channel_free() ssh_channel_is_eof()
References error, ssh_channel_struct::local_channel, ssh_channel_struct::local_eof, ssh_session_struct::out_buffer, rc, ssh_channel_struct::remote_channel, ssh_channel_struct::session, session, SSH2_MSG_CHANNEL_EOF, ssh_buffer_pack, ssh_buffer_reinit, ssh_channel_flush, SSH_ERROR, SSH_LOG, SSH_LOG_PACKET, SSH_OK, ssh_packet_send, ssh_set_error_oom.
Referenced by channel_send_eof, default_handle_session_cb, do_connect, handle_kbdint_session_cb, handle_session, main, my_fd_data_function, pkd_exec_hello, select_loop, ssh::Channel::sendEof, ssh_channel_close, ssh_connector_channel_write_wontblock_cb, ssh_connector_fd_in_cb, ssh_scp_close, torture_ssh_forward, upload_script.
int ssh_channel_close(ssh_channel channel)
Close a channel.
This sends an end of file and then closes the channel. You won't be able to recover any data the server was going to send or was in buffers. channel The channel to close. SSH_OK on success, SSH_ERROR if an error occurred. ssh_channel_free() ssh_channel_is_eof()
References error, ssh_channel_struct::flags, ssh_channel_struct::local_channel, ssh_session_struct::out_buffer, rc, ssh_channel_struct::remote_channel, ssh_channel_struct::session, session, SSH2_MSG_CHANNEL_CLOSE, ssh_buffer_pack, ssh_buffer_reinit, SSH_CHANNEL_FLAG_CLOSED_LOCAL, ssh_channel_flush, ssh_channel_send_eof, SSH_CHANNEL_STATE_CLOSED, SSH_ERROR, SSH_LOG, SSH_LOG_PACKET, SSH_OK, ssh_packet_send, ssh_set_error_oom, ssh_channel_struct::state.
Referenced by benchmarks_raw_down, benchmarks_raw_up, benchmarks_ssh_latency, channel_close, ssh::Channel::close, create_files, default_handle_session_cb, do_cleanup, do_connect, handle_kbdint_session_cb, handle_session, main, my_fd_data_function, pkd_exec_hello, ssh_channel_free, ssh_scp_close, torture_request_env, torture_server_unknown_global_request, torture_ssh_forward, torture_unknown_request, upload_script.
static int ssh_channel_waitwindow_termination(void *c)
References ssh_channel_struct::remote_window, ssh_channel_struct::session, ssh_session_struct::session_state, SSH_CHANNEL_STATE_CLOSED, SSH_SESSION_STATE_ERROR, ssh_channel_struct::state.
Referenced by channel_write_common.
static int ssh_waitsession_unblocked(void *s)
References s, session, ssh_session_struct::session_state, SSH_SESSION_STATE_DH, SSH_SESSION_STATE_INITIAL_KEX, SSH_SESSION_STATE_KEXINIT_RECEIVED.
Referenced by channel_write_common.
int ssh_channel_flush(ssh_channel channel)
References ssh_channel_struct::session, ssh_blocking_flush, SSH_TIMEOUT_DEFAULT.
Referenced by channel_write_common, ssh_channel_close, ssh_channel_send_eof.
static int channel_write_common(ssh_channel channel, const void *data, uint32_t len, int is_stderr)
References ssh_channel_struct::counter, ssh_iterator::data, ssh_channel_struct::delayed_close, error, ssh_channel_struct::local_channel, ssh_channel_struct::local_eof, MIN, ssh_session_struct::out_buffer, ssh_counter_struct::out_bytes, rc, ssh_channel_struct::remote_channel, ssh_channel_struct::remote_maxpacket, ssh_channel_struct::remote_window, ssh_channel_struct::session, session, ssh_session_struct::session_state, SSH2_EXTENDED_DATA_STDERR, SSH2_MSG_CHANNEL_DATA, SSH2_MSG_CHANNEL_EXTENDED_DATA, ssh_buffer_pack, ssh_buffer_reinit, ssh_channel_flush, SSH_CHANNEL_STATE_CLOSED, SSH_CHANNEL_STATE_OPEN, ssh_channel_waitwindow_termination, SSH_ERROR, ssh_handle_packets_termination, SSH_LOG, SSH_LOG_PACKET, SSH_LOG_PROTOCOL, SSH_OK, ssh_packet_send, SSH_REQUEST_DENIED, SSH_SESSION_STATE_ERROR, ssh_set_error, ssh_set_error_invalid, ssh_set_error_oom, SSH_TIMEOUT_DEFAULT, ssh_waitsession_unblocked, ssh_channel_struct::state.
Referenced by ssh_channel_write, ssh_channel_write_stderr.
uint32_t ssh_channel_window_size(ssh_channel channel)
Get the remote window size.
This is the maximum amounts of bytes the remote side expects us to send before growing the window again. channel The channel to query. The remote window size A nonzero return value does not guarantee the socket is ready to send that much data. Buffering may happen in the local SSH packet buffer, so beware of really big window sizes. A zero return value means ssh_channel_write (default settings) will block until the window grows back.
References ssh_channel_struct::remote_window.
Referenced by ssh_connector_channel_data_cb, ssh_connector_fd_in_cb, ssh_connector_set_event.
int ssh_channel_write(ssh_channel channel, const void *data, uint32_t len)
Blocking write on a channel.
channel The channel to write to. data A pointer to the data to write. len The length of the buffer to write to. The number of bytes written, SSH_ERROR on error. ssh_channel_read()
References channel_write_common, ssh_iterator::data.
Referenced by atomicio, benchmarks_raw_down, benchmarks_raw_up, channel_write, do_connect, main, my_fd_data_function, pkd_exec_hello, process_stdout, select_loop, ssh_connector_channel_data_cb, ssh_connector_channel_write_wontblock_cb, ssh_connector_fd_in_cb, ssh_scp_accept_request, ssh_scp_deny_request, ssh_scp_init, ssh_scp_leave_directory, ssh_scp_pull_request, ssh_scp_push_directory, ssh_scp_push_file64, ssh_scp_read, ssh_scp_write, upload_script, ssh::Channel::write.
int ssh_channel_is_open(ssh_channel channel)
Check if the channel is open or not.
channel The channel to check. 0 if channel is closed, nonzero otherwise. ssh_channel_is_closed()
References ssh_session_struct::alive, ssh_channel_struct::session, SSH_CHANNEL_STATE_OPEN, ssh_channel_struct::state.
Referenced by channel_is_open, channel_protocol_select, default_handle_session_cb, handle_kbdint_session_cb, handle_session, ssh::Channel::isOpen, my_fd_data_function, select_loop.
int ssh_channel_is_closed(ssh_channel channel)
Check if the channel is closed or not.
channel The channel to check. 0 if channel is opened, nonzero otherwise. ssh_channel_is_open()
References ssh_session_struct::alive, ssh_channel_struct::session, SSH_CHANNEL_STATE_OPEN, SSH_ERROR, ssh_channel_struct::state.
Referenced by channel_is_closed, channel_protocol_select, do_cleanup, ssh::Channel::isClosed, my_fd_data_function, select_loop.
int ssh_channel_is_eof(ssh_channel channel)
Check if remote has sent an EOF.
channel The channel to check. 0 if there is no EOF, nonzero otherwise.
References ssh_channel_struct::remote_eof, ssh_buffer_get_len, SSH_ERROR, ssh_channel_struct::stderr_buffer, ssh_channel_struct::stdout_buffer.
Referenced by channel_is_eof, channel_read_buffer, create_files, ssh::Channel::isEof, ssh_connector_channel_write_wontblock_cb, ssh_connector_fd_out_cb, ssh_scp_close, ssh_scp_pull_request.
void ssh_channel_set_blocking(ssh_channel channel, int blocking)
Put the channel into blocking or nonblocking mode.
channel The channel to use. blocking A boolean for blocking or nonblocking. A side-effect of this is to put the whole session in non-blocking mode. ssh_set_blocking()
References ssh_channel_struct::session, ssh_set_blocking.
Referenced by channel_set_blocking.
SSH_PACKET_CALLBACK(ssh_packet_channel_success)
References channel_from_msg, ssh_channel_struct::local_channel, ssh_channel_struct::remote_channel, ssh_channel_struct::request_state, session, SSH_CHANNEL_REQ_STATE_ACCEPTED, SSH_CHANNEL_REQ_STATE_PENDING, ssh_get_error, SSH_LOG, SSH_LOG_FUNCTIONS, SSH_LOG_PACKET, SSH_LOG_RARE, SSH_PACKET_USED, user.
SSH_PACKET_CALLBACK(ssh_packet_channel_failure)
References channel_from_msg, ssh_channel_struct::local_channel, ssh_channel_struct::remote_channel, ssh_channel_struct::request_state, session, SSH_CHANNEL_REQ_STATE_DENIED, SSH_CHANNEL_REQ_STATE_PENDING, ssh_get_error, SSH_LOG, SSH_LOG_FUNCTIONS, SSH_LOG_PACKET, SSH_LOG_RARE, SSH_PACKET_USED, user.
static int ssh_channel_request_termination(void *c)
References ssh_channel_struct::request_state, ssh_channel_struct::session, ssh_session_struct::session_state, SSH_CHANNEL_REQ_STATE_PENDING, SSH_SESSION_STATE_ERROR.
Referenced by channel_request.
static int channel_request(ssh_channel channel, const char *request, ssh_buffer buffer, int reply)
References buffer, error, ssh_session_struct::out_buffer, rc, ssh_channel_struct::remote_channel, ssh_channel_struct::request_state, ssh_channel_struct::session, session, ssh_session_struct::session_state, SSH2_MSG_CHANNEL_REQUEST, SSH_AGAIN, ssh_buffer_add_data, ssh_buffer_get, ssh_buffer_get_len, ssh_buffer_pack, ssh_buffer_reinit, SSH_CHANNEL_REQ_STATE_ACCEPTED, SSH_CHANNEL_REQ_STATE_DENIED, SSH_CHANNEL_REQ_STATE_ERROR, SSH_CHANNEL_REQ_STATE_NONE, SSH_CHANNEL_REQ_STATE_PENDING, ssh_channel_request_termination, SSH_ERROR, SSH_FATAL, ssh_handle_packets_termination, SSH_LOG, SSH_LOG_PACKET, SSH_LOG_PROTOCOL, SSH_OK, ssh_packet_send, SSH_REQUEST_DENIED, SSH_SESSION_STATE_ERROR, ssh_set_error, ssh_set_error_oom, SSH_TIMEOUT_DEFAULT.
Referenced by ssh_channel_change_pty_size, ssh_channel_request_auth_agent, ssh_channel_request_env, ssh_channel_request_exec, ssh_channel_request_pty_size, ssh_channel_request_send_break, ssh_channel_request_send_signal, ssh_channel_request_shell, ssh_channel_request_subsystem, ssh_channel_request_x11.
int ssh_channel_request_pty_size(ssh_channel channel, const char *terminal, int col, int row)
Request a pty with a specific type and size.
channel The channel to sent the request. terminal The terminal type ("vt100, xterm,..."). col The number of columns. row The number of rows. SSH_OK on success, SSH_ERROR if an error occurred, SSH_AGAIN if in nonblocking mode and call has to be done again.
References buffer, channel_request, error, rc, ssh_channel_struct::request_state, ssh_channel_struct::session, session, SSH_BUFFER_FREE, ssh_buffer_new, ssh_buffer_pack, SSH_CHANNEL_REQ_STATE_NONE, SSH_ERROR, SSH_OK, ssh_set_error_invalid, ssh_set_error_oom, terminal.
Referenced by channel_request_pty_size, ssh::Channel::requestPty, ssh_channel_request_pty.
int ssh_channel_request_pty(ssh_channel channel)
Request a PTY.
channel The channel to send the request. SSH_OK on success, SSH_ERROR if an error occurred, SSH_AGAIN if in nonblocking mode and call has to be done again. ssh_channel_request_pty_size()
References ssh_channel_request_pty_size.
Referenced by channel_request_pty, ssh::Channel::requestPty, shell.
int ssh_channel_change_pty_size(ssh_channel channel, int cols, int rows)
Change the size of the terminal associated to a channel.
channel The channel to change the size. cols The new number of columns. rows The new number of rows. SSH_OK on success, SSH_ERROR if an error occurred. Do not call it from a signal handler if you are not sure any other libssh function using the same channel/session is running at same time (not 100% threadsafe).
References buffer, channel_request, error, rc, ssh_channel_struct::session, session, SSH_BUFFER_FREE, ssh_buffer_new, ssh_buffer_pack, SSH_ERROR, SSH_OK, ssh_set_error_oom.
Referenced by ssh::Channel::changePtySize, channel_change_pty_size, sizechanged.
int ssh_channel_request_shell(ssh_channel channel)
Request a shell.
channel The channel to send the request. SSH_OK on success, SSH_ERROR if an error occurred, SSH_AGAIN if in nonblocking mode and call has to be done again.
References channel_request, SSH_ERROR.
Referenced by channel_request_shell, ssh::Channel::requestShell, shell.
int ssh_channel_request_subsystem(ssh_channel channel, const char *subsys)
Request a subsystem (for example "sftp").
channel The channel to send the request. subsys The subsystem to request (for example "sftp"). SSH_OK on success, SSH_ERROR if an error occurred, SSH_AGAIN if in nonblocking mode and call has to be done again. You normally don't have to call it for sftp, see sftp_new().
References buffer, channel_request, error, rc, ssh_channel_struct::request_state, ssh_channel_struct::session, SSH_BUFFER_FREE, ssh_buffer_new, ssh_buffer_pack, SSH_CHANNEL_REQ_STATE_NONE, SSH_ERROR, SSH_OK, ssh_set_error_invalid, ssh_set_error_oom.
Referenced by channel_request_subsystem, ssh::Channel::requestSubsystem, ssh_channel_request_sftp.
int ssh_channel_request_sftp(ssh_channel channel)
Request sftp subsystem on the channel.
channel The channel to request the sftp subsystem. SSH_OK on success, SSH_ERROR if an error occurred, SSH_AGAIN if in nonblocking mode and call has to be done again. You should use sftp_new() which does this for you.
References ssh_channel_request_subsystem, SSH_ERROR.
Referenced by channel_request_sftp.
static char* generate_cookie(void)
References s, ssh_get_random.
Referenced by ssh_channel_request_x11.
int ssh_channel_request_x11(ssh_channel channel, int single_connection, const char *protocol, const char *cookie, int screen_number)
Sends the "x11-req" channel request over an existing session channel.
This will enable redirecting the display of the remote X11 applications to local X server over an secure tunnel. channel An existing session channel where the remote X11 applications are going to be executed. single_connection A boolean to mark only one X11 app will be redirected. protocol A x11 authentication protocol. Pass NULL to use the default value MIT-MAGIC-COOKIE-1. cookie A x11 authentication cookie. Pass NULL to generate a random cookie. screen_number The screen number. SSH_OK on success, SSH_ERROR if an error occurred, SSH_AGAIN if in nonblocking mode and call has to be done again.
References buffer, channel_request, error, generate_cookie, rc, ssh_channel_struct::request_state, SAFE_FREE, ssh_channel_struct::session, SSH_BUFFER_FREE, ssh_buffer_new, ssh_buffer_pack, SSH_CHANNEL_REQ_STATE_NONE, SSH_ERROR, SSH_OK, ssh_set_error_oom.
Referenced by channel_request_x11, client_thread, ssh::Channel::requestX11.
static ssh_channel ssh_channel_accept(ssh_session session, int channeltype, int timeout_ms, int *destination_port)
References ssh_message_struct::channel_request_open, ssh_iterator::data, ssh_channel_request_open::destination_port, if, ssh_iterator::next, session, ssh_handle_packets, ssh_list_get_iterator, ssh_list_remove, ssh_message_channel_request_open_reply_accept, ssh_message_free, ssh_session_struct::ssh_message_list, ssh_message_subtype, ssh_message_type, SSH_NO_ERROR, SSH_REQUEST_CHANNEL_OPEN, ssh_set_error.
Referenced by ssh_channel_accept_forward, ssh_channel_accept_x11, ssh_forward_accept.
ssh_channel ssh_channel_accept_x11(ssh_channel channel, int timeout_ms)
Accept an X11 forwarding channel.
channel An x11-enabled session channel. timeout_ms Timeout in milliseconds. A newly created channel, or NULL if no X11 request from the server.
References ssh_channel_struct::session, ssh_channel_accept, SSH_CHANNEL_X11.
Referenced by ssh::Channel::acceptX11, channel_accept_x11.
int ssh_channel_request_auth_agent(ssh_channel channel)
Send an "auth-agent-req" channel request over an existing session channel.
This client-side request will enable forwarding the agent over an secure tunnel. When the server is ready to open one authentication agent channel, an ssh_channel_open_request_auth_agent_callback event will be generated. channel The channel to send signal. SSH_OK on success, SSH_ERROR if an error occurred
References channel_request, SSH_ERROR.
SSH_PACKET_CALLBACK(ssh_request_success)
References ssh_session_struct::global_req_state, session, SSH_CHANNEL_REQ_STATE_ACCEPTED, SSH_CHANNEL_REQ_STATE_PENDING, SSH_LOG, SSH_LOG_PACKET, SSH_LOG_RARE, SSH_PACKET_USED, user.
SSH_PACKET_CALLBACK(ssh_request_denied)
References ssh_session_struct::global_req_state, session, SSH_CHANNEL_REQ_STATE_DENIED, SSH_CHANNEL_REQ_STATE_PENDING, SSH_LOG, SSH_LOG_PACKET, SSH_LOG_RARE, SSH_PACKET_USED, user.
static int ssh_global_request_termination(void *s)
References ssh_session_struct::global_req_state, s, session, ssh_session_struct::session_state, SSH_CHANNEL_REQ_STATE_PENDING, SSH_SESSION_STATE_ERROR.
Referenced by ssh_global_request.
int ssh_global_request(ssh_session session, const char *request, ssh_buffer buffer, int reply)
References buffer, error, ssh_session_struct::global_req_state, ssh_session_struct::out_buffer, rc, session, ssh_session_struct::session_state, SSH2_MSG_GLOBAL_REQUEST, SSH_AGAIN, ssh_buffer_add_data, ssh_buffer_get, ssh_buffer_get_len, ssh_buffer_pack, ssh_buffer_reinit, SSH_CHANNEL_REQ_STATE_ACCEPTED, SSH_CHANNEL_REQ_STATE_DENIED, SSH_CHANNEL_REQ_STATE_ERROR, SSH_CHANNEL_REQ_STATE_NONE, SSH_CHANNEL_REQ_STATE_PENDING, SSH_ERROR, ssh_global_request_termination, ssh_handle_packets_termination, SSH_LOG, SSH_LOG_PACKET, SSH_LOG_PROTOCOL, SSH_OK, ssh_packet_send, SSH_REQUEST_DENIED, SSH_SESSION_STATE_ERROR, ssh_set_error, ssh_set_error_oom, SSH_TIMEOUT_DEFAULT.
Referenced by ssh_channel_cancel_forward, ssh_channel_listen_forward, ssh_send_keepalive, torture_server_unknown_global_request, torture_unknown_request.
int ssh_channel_listen_forward(ssh_session session, const char *address, int port, int *bound_port)
Sends the "tcpip-forward" global request to ask the server to begin listening for inbound connections.
session The ssh session to send the request. address The address to bind to on the server. Pass NULL to bind to all available addresses on all protocol families supported by the server. port The port to bind to on the server. Pass 0 to ask the server to allocate the next available unprivileged port number bound_port The pointer to get actual bound port. Pass NULL to ignore. SSH_OK on success, SSH_ERROR if an error occurred, SSH_AGAIN if in nonblocking mode and call has to be done again.
References buffer, error, ssh_session_struct::global_req_state, ssh_session_struct::in_buffer, port, rc, session, SSH_BUFFER_FREE, ssh_buffer_new, ssh_buffer_pack, ssh_buffer_unpack, SSH_CHANNEL_REQ_STATE_NONE, SSH_ERROR, ssh_global_request, SSH_OK, ssh_set_error_oom.
Referenced by channel_forward_listen, ssh::Session::listenForward, ssh_forward_listen, torture_ssh_forward.
int ssh_forward_listen(ssh_session session, const char *address, int port, int *bound_port)
References port, session, ssh_channel_listen_forward.
ssh_channel ssh_forward_accept(ssh_session session, int timeout_ms)
References session, ssh_channel_accept, SSH_CHANNEL_FORWARDED_TCPIP.
ssh_channel ssh_channel_accept_forward(ssh_session session, int timeout_ms, int *destination_port)
Accept an incoming TCP/IP forwarding channel and get information about incomming connection.
session The ssh session to use. timeout_ms A timeout in milliseconds. destination_port A pointer to destination port or NULL. Newly created channel, or NULL if no incoming channel request from the server
References session, ssh_channel_accept, SSH_CHANNEL_FORWARDED_TCPIP.
Referenced by ssh::Session::acceptForward, channel_forward_accept, torture_ssh_forward.
int ssh_channel_cancel_forward(ssh_session session, const char *address, int port)
Sends the "cancel-tcpip-forward" global request to ask the server to cancel the tcpip-forward request.
session The ssh session to send the request. address The bound address on the server. port The bound port on the server. SSH_OK on success, SSH_ERROR if an error occurred, SSH_AGAIN if in nonblocking mode and call has to be done again.
References buffer, error, ssh_session_struct::global_req_state, port, rc, session, SSH_BUFFER_FREE, ssh_buffer_new, ssh_buffer_pack, SSH_CHANNEL_REQ_STATE_NONE, SSH_ERROR, ssh_global_request, SSH_OK, ssh_set_error_oom.
Referenced by ssh::Session::cancelForward, channel_forward_cancel, ssh_forward_cancel.
int ssh_forward_cancel(ssh_session session, const char *address, int port)
References port, session, ssh_channel_cancel_forward.
int ssh_channel_request_env(ssh_channel channel, const char *name, const char *value)
Set environment variables.
channel The channel to set the environment variables. name The name of the variable. value The value to set. SSH_OK on success, SSH_ERROR if an error occurred, SSH_AGAIN if in nonblocking mode and call has to be done again. Some environment variables may be refused by security reasons.
References buffer, channel_request, error, name, rc, ssh_channel_struct::request_state, ssh_channel_struct::session, SSH_BUFFER_FREE, ssh_buffer_new, ssh_buffer_pack, SSH_CHANNEL_REQ_STATE_NONE, SSH_ERROR, SSH_OK, ssh_set_error_invalid, ssh_set_error_oom.
Referenced by benchmarks_ssh_latency, channel_request_env, ssh::Channel::requestEnv, torture_request_env.
int ssh_channel_request_exec(ssh_channel channel, const char *cmd)
Run a shell command without an interactive shell.
This is similar to 'sh -c command'. channel The channel to execute the command. cmd The command to execute (e.g. "ls ~/ -al | grep -i reports"). SSH_OK on success, SSH_ERROR if an error occurred, SSH_AGAIN if in nonblocking mode and call has to be done again. Example: rc=ssh_channel_request_exec(channel,"psaux"); if(rc>0){ return-1; } while((rc=ssh_channel_read(channel,buffer,sizeof(buffer),0))>0){ if(fwrite(buffer,1,rc,stdout)!=(unsignedint)rc){ return-1; } } ssh_channel_request_shell()
References buffer, channel_request, error, rc, ssh_channel_struct::request_state, ssh_channel_struct::session, SSH_BUFFER_FREE, ssh_buffer_new, ssh_buffer_pack, SSH_CHANNEL_REQ_STATE_NONE, SSH_ERROR, SSH_OK, ssh_set_error_invalid, ssh_set_error_oom.
Referenced by batch_shell, benchmarks_raw_down, benchmarks_raw_up, channel_request_exec, create_files, do_connect, LLVMFuzzerTestOneInput, main, ssh::Channel::requestExec, ssh_scp_init, torture_channel_read_error, torture_request_env, upload_script.
int ssh_channel_request_send_signal(ssh_channel channel, const char *sig)
Send a signal to remote process (as described in RFC 4254, section 6.9).
Sends a signal 'sig' to the remote process. Note, that remote system may not support signals concept. In such a case this request will be silently ignored. Only SSH-v2 is supported (I'm not sure about SSH-v1). OpenSSH doesn't support signals yet, see: https://bugzilla.mindrot.org/show_bug.cgi?id=1424 channel The channel to send signal. sig The signal to send (without SIG prefix) SIGABRT -> ABRT SIGALRM -> ALRM SIGFPE -> FPE SIGHUP -> HUP SIGILL -> ILL SIGINT -> INT SIGKILL -> KILL SIGPIPE -> PIPE SIGQUIT -> QUIT SIGSEGV -> SEGV SIGTERM -> TERM SIGUSR1 -> USR1 SIGUSR2 -> USR2 SSH_OK on success, SSH_ERROR if an error occurred (including attempts to send signal via SSH-v1 session).
References buffer, channel_request, error, rc, ssh_channel_struct::session, SSH_BUFFER_FREE, ssh_buffer_new, ssh_buffer_pack, SSH_ERROR, SSH_OK, ssh_set_error_invalid, ssh_set_error_oom.
Referenced by channel_request_send_signal, ssh::Channel::requestSendSignal.
int ssh_channel_request_send_break(ssh_channel channel, uint32_t length)
Send a break signal to the server (as described in RFC 4335).
Sends a break signal to the remote process. Note, that remote system may not support breaks. In such a case this request will be silently ignored. Only SSH-v2 is supported. channel The channel to send the break to. length The break-length in milliseconds to send. SSH_OK on success, SSH_ERROR if an error occurred (including attempts to send signal via SSH-v1 session).
References buffer, channel_request, error, rc, ssh_channel_struct::session, SSH_BUFFER_FREE, ssh_buffer_new, ssh_buffer_pack, SSH_ERROR, SSH_OK, ssh_set_error_oom.
int channel_read_buffer(ssh_channel channel, ssh_buffer buffer, uint32_t count, int is_stderr)
Read data from a channel into a buffer.
channel The channel to read from. buffer The buffer which will get the data. count The count of bytes to be read. If it is bigger than 0, the exact size will be read, else (bytes=0) it will return once anything is available. is_stderr A boolean value to mark reading from the stderr stream. The number of bytes read, 0 on end of file or SSH_ERROR on error. DeprecatedPlease use ssh_channel_read instead This function doesn't work in nonblocking/timeout mode ssh_channel_read
References buffer, ssh_channel_struct::session, session, ssh_buffer_add_data, ssh_buffer_reinit, ssh_channel_is_eof, ssh_channel_poll, ssh_channel_read, SSH_ERROR, ssh_handle_packets, ssh_set_error_invalid, ssh_set_error_oom, SSH_TIMEOUT_INFINITE.
static int ssh_channel_read_termination(void *s)
References ctx, s, ssh_buffer_get_len, SSH_SESSION_STATE_ERROR.
Referenced by ssh_channel_poll_timeout, ssh_channel_read_timeout.
int ssh_channel_read(ssh_channel channel, void *dest, uint32_t count, int is_stderr)
Reads data from a channel.
channel The channel to read from. dest The destination buffer which will get the data. count The count of bytes to be read. is_stderr A boolean value to mark reading from the stderr flow. The number of bytes read, 0 on end of file or SSH_ERROR on error. In nonblocking mode it Can return 0 if no data is available or SSH_AGAIN. This function may return less than count bytes of data, and won't block until count bytes have been read. The read function using a buffer has been renamed to channel_read_buffer().
References ssh_channel_read_termination_struct::channel, ssh_channel_read_termination_struct::count, ssh_channel_read_timeout, SSH_TIMEOUT_DEFAULT.
Referenced by atomicio, benchmarks_raw_down, benchmarks_raw_up, channel_read, channel_read_buffer, create_files, do_connect, main, select_loop, ssh_channel_read_nonblocking, ssh_scp_close, ssh_scp_read, ssh_scp_read_string, ssh_scp_response, torture_channel_read_error, torture_request_env.
int ssh_channel_read_timeout(ssh_channel channel, void *dest, uint32_t count, int is_stderr, int timeout_ms)
Reads data from a channel.
channel The channel to read from. dest The destination buffer which will get the data. count The count of bytes to be read. is_stderr A boolean value to mark reading from the stderr flow. timeout_ms A timeout in milliseconds. A value of -1 means infinite timeout. The number of bytes read, 0 on end of file or SSH_ERROR on error. In nonblocking mode it Can return 0 if no data is available or SSH_AGAIN. This function may return less than count bytes of data, and won't block until count bytes have been read. The read function using a buffer has been renamed to channel_read_buffer().
References ssh_channel_read_termination_struct::channel, ssh_channel_read_termination_struct::count, ssh_channel_struct::counter, ctx, grow_window, ssh_counter_struct::in_bytes, ssh_channel_struct::local_window, rc, ssh_channel_struct::remote_eof, ssh_channel_struct::session, session, ssh_session_struct::session_state, ssh_buffer_get, ssh_buffer_get_len, ssh_buffer_pass_bytes, ssh_channel_read_termination, SSH_CHANNEL_STATE_CLOSED, SSH_ERROR, SSH_FATAL, ssh_handle_packets_termination, SSH_LOG, SSH_LOG_PACKET, SSH_SESSION_STATE_ERROR, ssh_set_error, ssh_set_error_invalid, SSH_TIMEOUT_DEFAULT, SSH_TIMEOUT_INFINITE, ssh_channel_struct::state, ssh_channel_struct::stderr_buffer, ssh_channel_struct::stdout_buffer, WINDOWLIMIT.
Referenced by ssh::Channel::read, ssh_channel_read.
int ssh_channel_read_nonblocking(ssh_channel channel, void *dest, uint32_t count, int is_stderr)
Do a nonblocking read on the channel.
A nonblocking read on the specified channel. it will return <= count bytes of data read atomically. channel The channel to read from. dest A pointer to a destination buffer. count The count of bytes of data to be read. is_stderr A boolean to select the stderr stream. The number of bytes read, 0 if nothing is available or SSH_ERROR on error. Don't forget to check for EOF as it would return 0 here. ssh_channel_is_eof()
References ssh_channel_read_termination_struct::channel, ssh_channel_read_termination_struct::count, rc, ssh_channel_struct::session, session, ssh_session_struct::session_state, ssh_channel_poll, ssh_channel_read, SSH_ERROR, ssh_is_blocking, SSH_SESSION_STATE_ERROR, ssh_set_blocking, ssh_set_error_invalid.
Referenced by channel_read_nonblocking, do_connect, ssh::Channel::readNonblocking, ssh_connector_channel_write_wontblock_cb, ssh_connector_fd_out_cb.
int ssh_channel_poll(ssh_channel channel, int is_stderr)
Polls a channel for data to read.
channel The channel to poll. is_stderr A boolean to select the stderr stream. The number of bytes available for reading, 0 if nothing is available or SSH_ERROR on error. When the channel is in EOF state, the function returns SSH_EOF. ssh_channel_is_eof()
References ssh_channel_read_termination_struct::channel, ssh_channel_struct::remote_eof, ssh_channel_struct::session, ssh_session_struct::session_state, ssh_buffer_get_len, SSH_EOF, SSH_ERROR, ssh_handle_packets, SSH_SESSION_STATE_ERROR, SSH_TIMEOUT_NONBLOCKING, ssh_channel_struct::stderr_buffer, ssh_channel_struct::stdout_buffer.
Referenced by channel_poll, channel_read_buffer, do_connect, ssh::Channel::poll, select_loop, ssh_channel_read_nonblocking, ssh_scp_write, ssh_select.
int ssh_channel_poll_timeout(ssh_channel channel, int timeout, int is_stderr)
Polls a channel for data to read, waiting for a certain timeout.
channel The channel to poll. timeout Set an upper limit on the time for which this function will block, in milliseconds. Specifying a negative value means an infinite timeout. This parameter is passed to the poll() function. is_stderr A boolean to select the stderr stream. The number of bytes available for reading, 0 if nothing is available (timeout elapsed), SSH_EOF on end of file, SSH_ERROR on error. When the channel is in EOF state, the function returns SSH_EOF. ssh_channel_is_eof()
References ssh_channel_read_termination_struct::channel, ctx, rc, ssh_channel_struct::remote_eof, ssh_channel_struct::session, session, ssh_session_struct::session_state, ssh_buffer_get_len, ssh_channel_read_termination, SSH_EOF, SSH_ERROR, ssh_handle_packets_termination, SSH_SESSION_STATE_ERROR, ssh_channel_struct::stderr_buffer, ssh_channel_struct::stdout_buffer.
Referenced by ssh_connector_set_event.
ssh_session ssh_channel_get_session(ssh_channel channel)
Recover the session in which belongs a channel.
channel The channel to recover the session from. The session pointer.
References ssh_channel_read_termination_struct::channel, ssh_channel_struct::session.
Referenced by channel_get_session, my_fd_data_function, ssh_connector_remove_event, ssh_connector_set_event.
static int ssh_channel_exit_status_termination(void *c)
References ssh_channel_read_termination_struct::channel, ssh_channel_struct::exit_status, ssh_channel_struct::flags, ssh_channel_struct::session, ssh_session_struct::session_state, SSH_CHANNEL_FLAG_CLOSED_REMOTE, SSH_SESSION_STATE_ERROR.
Referenced by ssh_channel_get_exit_status.
int ssh_channel_get_exit_status(ssh_channel channel)
Get the exit status of the channel (error code from the executed instruction).
channel The channel to get the status from. The exit status, -1 if no exit status has been returned (yet), or SSH_ERROR on error. This function may block until a timeout (or never) if the other side is not willing to close the channel. If you're looking for an async handling of this register a callback for the exit status. ssh_channel_exit_status_callback
References ssh_channel_read_termination_struct::channel, ssh_channel_struct::exit_status, rc, ssh_channel_struct::session, ssh_session_struct::session_state, ssh_channel_exit_status_termination, SSH_ERROR, ssh_handle_packets_termination, SSH_SESSION_STATE_ERROR, SSH_TIMEOUT_DEFAULT.
Referenced by channel_get_exit_status, do_connect, ssh::Channel::getExitStatus.
static int channel_protocol_select(ssh_channel *rchans, ssh_channel *wchans, ssh_channel *echans, ssh_channel *rout, ssh_channel *wout, ssh_channel *eout)
References chan, ssh_channel_struct::remote_eof, ssh_channel_struct::remote_window, ssh_channel_struct::session, ssh_session_struct::socket, ssh_buffer_get_len, ssh_channel_is_closed, ssh_channel_is_open, ssh_handle_packets, ssh_socket_data_available, ssh_socket_data_writable, ssh_socket_is_open, SSH_TIMEOUT_NONBLOCKING, ssh_channel_struct::stderr_buffer, ssh_channel_struct::stdout_buffer.
Referenced by ssh_channel_select.
static size_t count_ptrs(ssh_channel *ptrs)
Referenced by ssh_channel_select.
int ssh_channel_select(ssh_channel *readchans, ssh_channel *writechans, ssh_channel *exceptchans, struct timeval *timeout)
Act like the standard select(2) on channels.
The list of pointers are then actualized and will only contain pointers to channels that are respectively readable, writable or have an exception to trap. readchans A NULL pointer or an array of channel pointers, terminated by a NULL. writechans A NULL pointer or an array of channel pointers, terminated by a NULL. exceptchans A NULL pointer or an array of channel pointers, terminated by a NULL. timeout Timeout as defined by select(2). SSH_OK on a successful operation, SSH_EINTR if the select(2) syscall was interrupted, then relaunch the function, or SSH_ERROR on error.
References channel_protocol_select, count_ptrs, rc, SAFE_FREE, session, SSH_ERROR, ssh_event_add_session, ssh_event_dopoll, ssh_event_free, ssh_event_new, SSH_OK, ssh_poll_get_default_ctx, ssh_timeout_elapsed, SSH_TIMEOUT_INFINITE, ssh_timeout_update, ssh_timestamp_init.
Referenced by channel_select.
void ssh_channel_set_counter(ssh_channel channel, ssh_counter counter)
Set the channel data counter.
structssh_counter_structcounter={ .in_bytes=0, .out_bytes=0, .in_packets=0, .out_packets=0 }; ssh_channel_set_counter(channel,&counter); channel The SSH channel. counter Counter for bytes handled by the channel.
References ssh_channel_struct::counter.
int ssh_channel_write_stderr(ssh_channel channel, const void *data, uint32_t len)
Blocking write on a channel stderr.
channel The channel to write to. data A pointer to the data to write. len The length of the buffer to write to. The number of bytes written, SSH_ERROR on error. ssh_channel_read()
References channel_write_common.
Referenced by process_stderr, ssh_connector_channel_data_cb, ssh_connector_fd_in_cb, ssh::Channel::write.