libssh_threads
struct ssh_threads_callbacks_struct* user_callbacks
Referenced by ssh_threads_get_type, ssh_threads_init, ssh_threads_set_callbacks.
int ssh_threads_init(void)
References crypto_thread_init, rc, SSH_OK, ssh_threads_get_default, user_callbacks.
Referenced by libssh_constructor.
void ssh_threads_finalize(void)
References crypto_thread_finalize.
Referenced by _ssh_finalize.
int ssh_threads_set_callbacks(struct ssh_threads_callbacks_struct *cb)
Set the thread callbacks structure.
This is necessary if your program is using libssh in a multithreaded fashion. This function must be called first, outside of any threading context (in your main() function for instance), before you call ssh_init(). cb A pointer to a ssh_threads_callbacks_struct structure, which contains the different callbacks to be set. Always returns SSH_OK. ssh_threads_callbacks_struct SSH_THREADS_PTHREAD Buglibgcrypt 1.6 and bigger backend does not support custom callback. Using anything else than pthreads here will fail.
References cb, crypto_thread_finalize, crypto_thread_init, rc, user_callbacks.
Referenced by pkd_init_libssh, setup.
const char* ssh_threads_get_type(void)
References ssh_threads_callbacks_struct::type, user_callbacks.
Referenced by ssh_connect.