libssh_server
ssh_bind_options_e
typedef struct ssh_bind_struct* ssh_bind
typedef void(* ssh_bind_incoming_connection_callback) (ssh_bind sshbind, void *userdata))(ssh_bind sshbind, void *userdata)
Incoming connection callback. This callback is called when a ssh_bind has a new incoming connection.
sshbind Current sshbind session handler userdata Userdata to be passed to the callback function.
typedef struct ssh_bind_callbacks_struct* ssh_bind_callbacks
ssh_bind ssh_bind_new(void)
Creates a new SSH server bind.
A newly allocated ssh_bind session pointer.
References ssh_bind_struct::bindfd, ssh_bind_struct::bindport, ssh_bind_struct::common, ssh_common_struct::log_verbosity, SSH_INVALID_SOCKET.
Referenced by LLVMFuzzerTestOneInput, main, pkd_exec_hello, run_server, ssh_server, sshbind_setup.
LIBSSH_API int ssh_bind_options_set(ssh_bind sshbind, enum ssh_bind_options_e type, const void *value)
Referenced by LLVMFuzzerTestOneInput, main, pkd_exec_hello, run_server, set_default_keys, ssh_bind_config_parse_line, ssh_server.
LIBSSH_API int ssh_bind_options_parse_config(ssh_bind sshbind, const char *filename)
Referenced by run_server, ssh_bind_accept_fd.
int ssh_bind_listen(ssh_bind ssh_bind_o)
Start listening to the socket.
ssh_bind_o The ssh server bind to use. 0 on success, < 0 on error.
References bind_socket, ssh_bind_struct::bindaddr, ssh_bind_struct::bindfd, ssh_bind_struct::bindport, CLOSE_SOCKET, ssh_bind_struct::dsa, ssh_bind_struct::ecdsa, ssh_bind_struct::ed25519, host, rc, ssh_bind_struct::rsa, ssh_bind_import_keys, SSH_ERROR, SSH_FATAL, SSH_INVALID_SOCKET, ssh_key_free, SSH_LOG, SSH_LOG_INFO, SSH_OK, ssh_set_error.
Referenced by main, run_server.
int ssh_bind_set_callbacks(ssh_bind sshbind, ssh_bind_callbacks callbacks, void *userdata)
Set the callback for this bind.
sshbind The bind to set the callback on. callbacks An already set up ssh_bind_callbacks instance. userdata A pointer to private data to pass to the callbacks. SSH_OK on success, SSH_ERROR if an error occured. structssh_callbacks_structcb={ .userdata=data, .auth_function=my_auth_function }; ssh_callbacks_init(&cb); ssh_bind_set_callbacks(session,&cb);
References ssh_bind_struct::bind_callbacks, ssh_bind_struct::bind_callbacks_userdata, callbacks, SSH_ERROR, SSH_FATAL, ssh_set_error, ssh_set_error_invalid.
void ssh_bind_set_blocking(ssh_bind ssh_bind_o, int blocking)
Set the session to blocking/nonblocking mode.
ssh_bind_o The ssh server bind to use. blocking Zero for nonblocking mode.
References ssh_bind_struct::blocking.
socket_t ssh_bind_get_fd(ssh_bind ssh_bind_o)
Recover the file descriptor from the session.
ssh_bind_o The ssh server bind to get the fd from. The file descriptor.
References ssh_bind_struct::bindfd.
void ssh_bind_set_fd(ssh_bind ssh_bind_o, socket_t fd)
Set the file descriptor for a session.
ssh_bind_o The ssh server bind to set the fd. fd The file descriptssh_bind B
References ssh_bind_struct::bindfd.
void ssh_bind_fd_toaccept(ssh_bind ssh_bind_o)
Allow the file descriptor to accept new sessions.
ssh_bind_o The ssh server bind to use.
References ssh_bind_struct::toaccept.
int ssh_bind_accept(ssh_bind ssh_bind_o, ssh_session session)
Accept an incoming ssh connection and initialize the session.
ssh_bind_o The ssh server bind to accept a connection. session A preallocated ssh session ssh_new SSH_OK when a connection is established
References ssh_bind_struct::bindfd, CLOSE_SOCKET, rc, session, ssh_session_struct::socket, ssh_bind_accept_fd, SSH_ERROR, SSH_FATAL, SSH_INVALID_SOCKET, ssh_set_error, ssh_socket_free.
Referenced by main, run_server, test_ssh_channel_request_x11.
int ssh_bind_accept_fd(ssh_bind ssh_bind_o, ssh_session session, socket_t fd)
Accept an incoming ssh connection on the given file descriptor and initialize the session.
ssh_bind_o The ssh server bind to accept a connection. session A preallocated ssh session fd A file descriptor of an already established TCP inbound connection ssh_new ssh_bind_accept SSH_OK when a connection is established
References ssh_bind_struct::banner, ssh_bind_struct::bindaddr, ssh_session_struct::bindaddr, ssh_bind_struct::common, ssh_session_struct::common, ssh_session_struct::custombanner, ssh_bind_struct::dsa, ssh_session_struct::dsa_key, ssh_bind_struct::ecdsa, ssh_session_struct::ecdsa_key, ssh_bind_struct::ed25519, ssh_session_struct::ed25519_key, ssh_common_struct::log_verbosity, ssh_session_struct::opts, ssh_bind_struct::pubkey_accepted_key_types, ssh_session_struct::pubkey_accepted_types, rc, ssh_bind_struct::rsa, ssh_session_struct::rsa_key, SAFE_FREE, ssh_session_struct::server, session, ssh_session_struct::socket, ssh_session_struct::srv, ssh_bind_import_keys, ssh_bind_options_parse_config, SSH_ERROR, SSH_FATAL, ssh_find_all_matching, SSH_KEX_METHODS, ssh_key_dup, SSH_OK, ssh_reseed, ssh_set_error, ssh_set_error_oom, ssh_socket_free, ssh_socket_get_poll_handle, ssh_socket_new, ssh_socket_set_fd, ssh_bind_struct::wanted_methods, ssh_session_struct::wanted_methods.
Referenced by LLVMFuzzerTestOneInput, pkd_exec_hello, ssh_bind_accept, ssh_server.
LIBSSH_API ssh_gssapi_creds ssh_gssapi_get_creds(ssh_session session)
Referenced by auth_gssapi_mic.
int ssh_handle_key_exchange(ssh_session session)
Handles the key exchange and set up encryption.
session A connected ssh session ssh_bind_accept SSH_OK if the key exchange was successful
References ssh_session_struct::alive, callback_receive_banner, ssh_socket_callbacks_struct::data, ssh_socket_callbacks_struct::exception, rc, server_set_kex, session, ssh_session_struct::session_state, ssh_session_struct::socket, ssh_session_struct::socket_callbacks, ssh_session_struct::ssh_connection_callback, SSH_ERROR, ssh_handle_packets_termination, SSH_LOG, SSH_LOG_PACKET, SSH_OK, ssh_send_banner, ssh_server_connection_callback, ssh_server_kex_termination, SSH_SESSION_STATE_DISCONNECTED, SSH_SESSION_STATE_ERROR, SSH_SESSION_STATE_NONE, SSH_SESSION_STATE_SOCKET_CONNECTED, ssh_socket_exception_callback, ssh_socket_set_callbacks, SSH_TIMEOUT_USER, ssh_socket_callbacks_struct::userdata.
Referenced by default_handle_session_cb, handle_kbdint_session_cb, handle_session, LLVMFuzzerTestOneInput, main, pkd_exec_hello, ssh_server, test_ssh_channel_request_x11.
int ssh_server_init_kex(ssh_session session)
Initialize the set of key exchange, hostkey, ciphers, MACs, and compression algorithms for the given ssh_session.
The selection of algorithms and keys used are determined by the options that are currently set in the given ssh_session structure. May only be called before the initial key exchange has begun. session The session structure to initialize. ssh_handle_key_exchange ssh_options_set SSH_OK if initialization succeeds.
References ssh_kex_struct::methods, ssh_session_struct::next_crypto, SAFE_FREE, ssh_crypto_struct::server_kex, server_set_kex, session, ssh_session_struct::session_state, SSH_ERROR, SSH_KEX_METHODS, SSH_SESSION_STATE_BANNER_RECEIVED.
void ssh_bind_free(ssh_bind ssh_bind_o)
Free a ssh servers bind.
ssh_bind_o The ssh server bind to free.
References ssh_bind_struct::banner, ssh_bind_struct::bindaddr, ssh_bind_struct::bindfd, CLOSE_SOCKET, ssh_bind_struct::config_dir, ssh_bind_struct::dsa, ssh_bind_struct::dsakey, ssh_bind_struct::ecdsa, ssh_bind_struct::ecdsakey, ssh_bind_struct::ed25519, ssh_bind_struct::ed25519key, ssh_bind_struct::pubkey_accepted_key_types, ssh_bind_struct::rsa, ssh_bind_struct::rsakey, SAFE_FREE, SSH_INVALID_SOCKET, SSH_KEX_METHODS, ssh_key_free, ssh_bind_struct::wanted_methods.
Referenced by LLVMFuzzerTestOneInput, main, pkd_exec_hello, run_server, sshbind_teardown, test_ssh_channel_request_x11.
void ssh_set_auth_methods(ssh_session session, int auth_methods)
Set the acceptable authentication methods to be sent to the client.
session The server session auth_methods The authentication methods we will support, which can be bitwise-or'd. Supported methods are: SSH_AUTH_METHOD_PASSWORD SSH_AUTH_METHOD_PUBLICKEY SSH_AUTH_METHOD_HOSTBASED SSH_AUTH_METHOD_INTERACTIVE SSH_AUTH_METHOD_GSSAPI_MIC
References ssh_session_struct::auth, session, ssh_session_struct::supported_methods.
Referenced by default_handle_session_cb, handle_kbdint_session_cb, handle_session, LLVMFuzzerTestOneInput, main, pkd_exec_hello.
int ssh_message_reply_default(ssh_message msg)
Reply with a standard reject message.
Use this function if you don't know what to respond or if you want to reject a request. msg The message to use for the reply. 0 on success, -1 on error. ssh_message_get()
References ssh_message_struct::session, ssh_auth_reply_default, SSH_LOG, SSH_LOG_PACKET, ssh_message_channel_request_open_reply_default, ssh_message_channel_request_reply_default, ssh_message_global_request_reply_default, ssh_message_service_request_reply_default, SSH_REQUEST_AUTH, SSH_REQUEST_CHANNEL, SSH_REQUEST_CHANNEL_OPEN, SSH_REQUEST_GLOBAL, SSH_REQUEST_SERVICE, ssh_message_struct::type.
Referenced by authenticate, main, ssh_execute_message_callbacks.
const char * ssh_message_auth_user(ssh_message msg)
Get the name of the authenticated user.
msg The message to get the username from. The username or NULL if an error occured. ssh_message_get() ssh_message_type()
References ssh_message_struct::auth_request, ssh_auth_request::username.
Referenced by authenticate.
const char * ssh_message_auth_password(ssh_message msg)
Get the password of the authenticated user.
msg The message to get the password from. The username or NULL if an error occured. ssh_message_get() ssh_message_type()
References ssh_message_struct::auth_request, ssh_auth_request::password.
Referenced by authenticate.
ssh_key ssh_message_auth_pubkey(ssh_message msg)
Get the publickey of the authenticated user.
If you need the key for later user you should duplicate it. msg The message to get the public key from. The public key or NULL. ssh_key_dup() ssh_key_cmp() ssh_message_get() ssh_message_type()
References ssh_message_struct::auth_request, ssh_auth_request::pubkey.
int ssh_message_auth_kbdint_is_response(ssh_message msg)
References ssh_message_struct::auth_request, ssh_auth_request::kbdint_response.
Referenced by authenticate.
enum ssh_publickey_state_e ssh_message_auth_publickey_state(ssh_message msg)
int ssh_message_auth_reply_success(ssh_message msg, int partial)
References ssh_message_struct::session, ssh_auth_reply_success, SSH_ERROR.
Referenced by authenticate, authenticate_callback.
int ssh_message_auth_reply_pk_ok(ssh_message msg, ssh_string algo, ssh_string pubkey)
References ssh_session_struct::out_buffer, pubkey, rc, ssh_message_struct::session, SSH2_MSG_USERAUTH_PK_OK, ssh_buffer_pack, SSH_ERROR, SSH_OK, ssh_packet_send, ssh_set_error_oom.
Referenced by ssh_message_auth_reply_pk_ok_simple.
int ssh_message_auth_reply_pk_ok_simple(ssh_message msg)
References ssh_message_struct::auth_request, ssh_auth_request::pubkey, SSH_ERROR, ssh_message_auth_reply_pk_ok, ssh_pki_export_pubkey_blob, SSH_STRING_FREE, ssh_string_from_char, ssh_key_struct::type_c.
int ssh_message_auth_set_methods(ssh_message msg, int methods)
References ssh_session_struct::auth, ssh_kex_struct::methods, ssh_message_struct::session, ssh_session_struct::supported_methods.
Referenced by authenticate, authenticate_callback.
int ssh_message_auth_interactive_request(ssh_message msg, const char *name, const char *instruction, unsigned int num_prompts, const char **prompts, char *echo)
References ssh_session_struct::auth, echo, ssh_kbdint_struct::echo, instruction, ssh_kbdint_struct::instruction, ssh_session_struct::kbdint, name, ssh_kbdint_struct::name, ssh_kbdint_struct::nprompts, ssh_session_struct::out_buffer, prompts, ssh_kbdint_struct::prompts, rc, ssh_message_struct::session, SSH2_MSG_USERAUTH_INFO_REQUEST, SSH_AUTH_STATE_INFO, ssh_buffer_pack, SSH_ERROR, ssh_kbdint_clean, ssh_kbdint_free, ssh_kbdint_new, SSH_LOG, SSH_LOG_PROTOCOL, SSH_OK, ssh_packet_send, SSH_PACKET_USED, ssh_set_error_oom, ssh_session_struct::state.
Referenced by authenticate, authenticate_kbdint.
int ssh_message_service_reply_success(ssh_message msg)
References ssh_session_struct::out_buffer, rc, ssh_service_request::service, ssh_message_struct::service_request, ssh_message_struct::session, session, SSH2_MSG_SERVICE_ACCEPT, ssh_buffer_pack, SSH_ERROR, SSH_LOG, SSH_LOG_PACKET, SSH_OK, ssh_packet_send, ssh_set_error_oom.
Referenced by ssh_message_service_request_reply_default.
const char * ssh_message_service_service(ssh_message msg)
References ssh_service_request::service, ssh_message_struct::service_request.
int ssh_message_global_request_reply_success(ssh_message msg, uint16_t bound_port)
References ssh_global_request::bind_port, error, ssh_message_struct::global_request, ssh_session_struct::out_buffer, rc, ssh_message_struct::session, SSH2_MSG_REQUEST_SUCCESS, ssh_buffer_add_u8, ssh_buffer_pack, SSH_ERROR, SSH_GLOBAL_REQUEST_TCPIP_FORWARD, SSH_LOG, SSH_LOG_FUNCTIONS, SSH_LOG_PACKET, SSH_OK, ssh_packet_send, ssh_set_error_oom, ssh_global_request::type, ssh_global_request::want_reply.
void ssh_set_message_callback(ssh_session session, int(*ssh_bind_message_callback)(ssh_session session, ssh_message msg, void *data), void *data)
defines the ssh_message callback
session the current ssh session ssh_bind_message_callback a function pointer to a callback taking the current ssh session and received message as parameters. the function returns 0 if the message has been parsed and treated successfully, 1 otherwise (libssh must take care of the response). data void pointer to be passed to callback functions
References session, ssh_session_struct::ssh_message_callback, ssh_session_struct::ssh_message_callback_data.
Referenced by handle_kbdint_session_cb, main.
int ssh_execute_message_callbacks(ssh_session session)
References session, ssh_handle_packets, ssh_session_struct::ssh_message_callback, ssh_session_struct::ssh_message_callback_data, ssh_message_free, ssh_session_struct::ssh_message_list, ssh_message_pop_head, ssh_message_reply_default, SSH_OK, SSH_TIMEOUT_NONBLOCKING.
const char * ssh_message_channel_request_open_originator(ssh_message msg)
References ssh_message_struct::channel_request_open, ssh_channel_request_open::originator.
int ssh_message_channel_request_open_originator_port(ssh_message msg)
References ssh_message_struct::channel_request_open, ssh_channel_request_open::originator_port.
const char * ssh_message_channel_request_open_destination(ssh_message msg)
References ssh_message_struct::channel_request_open, ssh_channel_request_open::destination.
Referenced by open_tcp_socket.
int ssh_message_channel_request_open_destination_port(ssh_message msg)
References ssh_message_struct::channel_request_open, ssh_channel_request_open::destination_port.
Referenced by open_tcp_socket.
ssh_channel ssh_message_channel_request_channel(ssh_message msg)
References ssh_channel_request::channel, ssh_message_struct::channel_request.
const char * ssh_message_channel_request_pty_term(ssh_message msg)
References ssh_message_struct::channel_request, ssh_channel_request::TERM.
int ssh_message_channel_request_pty_width(ssh_message msg)
References ssh_message_struct::channel_request, ssh_channel_request::width.
int ssh_message_channel_request_pty_height(ssh_message msg)
References ssh_message_struct::channel_request, ssh_channel_request::height.
int ssh_message_channel_request_pty_pxwidth(ssh_message msg)
References ssh_message_struct::channel_request, ssh_channel_request::pxwidth.
int ssh_message_channel_request_pty_pxheight(ssh_message msg)
References ssh_message_struct::channel_request, ssh_channel_request::pxheight.
const char * ssh_message_channel_request_env_name(ssh_message msg)
References ssh_message_struct::channel_request, ssh_channel_request::var_name.
const char * ssh_message_channel_request_env_value(ssh_message msg)
References ssh_message_struct::channel_request, ssh_channel_request::var_value.
const char * ssh_message_channel_request_command(ssh_message msg)
References ssh_message_struct::channel_request, ssh_channel_request::command.
const char * ssh_message_channel_request_subsystem(ssh_message msg)
References ssh_message_struct::channel_request, ssh_channel_request::subsystem.
int ssh_message_channel_request_x11_single_connection(ssh_message msg)
References ssh_message_struct::channel_request, ssh_channel_request::x11_single_connection.
const char * ssh_message_channel_request_x11_auth_protocol(ssh_message msg)
References ssh_message_struct::channel_request, ssh_channel_request::x11_auth_protocol.
const char * ssh_message_channel_request_x11_auth_cookie(ssh_message msg)
References ssh_message_struct::channel_request, ssh_channel_request::x11_auth_cookie.
int ssh_message_channel_request_x11_screen_number(ssh_message msg)
References ssh_message_struct::channel_request, ssh_channel_request::x11_screen_number.
const char * ssh_message_global_request_address(ssh_message msg)
References ssh_global_request::bind_address, ssh_message_struct::global_request.
int ssh_message_global_request_port(ssh_message msg)
References ssh_global_request::bind_port, ssh_message_struct::global_request.
LIBSSH_API int ssh_channel_open_reverse_forward(ssh_channel channel, const char *remotehost, int remoteport, const char *sourcehost, int localport)
LIBSSH_API int ssh_channel_open_x11(ssh_channel channel, const char *orig_addr, int orig_port)
LIBSSH_API int ssh_channel_request_send_exit_status(ssh_channel channel, int exit_status)
Referenced by default_handle_session_cb, handle_kbdint_session_cb, handle_session, pkd_exec_hello.
LIBSSH_API int ssh_channel_request_send_exit_signal(ssh_channel channel, const char *signum, int core, const char *errmsg, const char *lang)
int ssh_send_keepalive(ssh_session session)
References session, ssh_global_request, SSH_OK.
SSH_DEPRECATED LIBSSH_API int ssh_accept(ssh_session session)
SSH_DEPRECATED LIBSSH_API int channel_write_stderr(ssh_channel channel, const void *data, uint32_t len)
static socket_t bind_socket(ssh_bind sshbind, const char *hostname, int port)
References CLOSE_SOCKET, port, rc, s, SSH_FATAL, SSH_INVALID_SOCKET, ssh_set_error, ZERO_STRUCT.
Referenced by ssh_bind_listen.
static int ssh_bind_import_keys(ssh_bind sshbind)
References ssh_bind_struct::dsa, ssh_bind_struct::dsakey, ssh_bind_struct::ecdsa, ssh_bind_struct::ecdsakey, ssh_bind_struct::ed25519, ssh_bind_struct::ed25519key, is_ecdsa_key_type, rc, ssh_bind_struct::rsa, ssh_bind_struct::rsakey, SSH_EOF, SSH_ERROR, SSH_FATAL, ssh_key_free, ssh_key_type, SSH_KEYTYPE_DSS, SSH_KEYTYPE_ED25519, SSH_KEYTYPE_RSA, SSH_OK, ssh_pki_import_privkey_file, ssh_set_error.
Referenced by ssh_bind_accept_fd, ssh_bind_listen.
static int ssh_bind_poll_callback(ssh_poll_handle sshpoll, socket_t fd, int revents, void *user)
References ssh_bind_struct::bind_callbacks, ssh_bind_struct::bind_callbacks_userdata, ssh_bind_callbacks_struct::incoming_connection, POLLIN, ssh_callbacks_exists, user.
Referenced by ssh_bind_get_poll.
ssh_poll_handle ssh_bind_get_poll(ssh_bind sshbind)
References ssh_bind_struct::bindfd, ssh_bind_struct::poll, POLLIN, ssh_bind_poll_callback, ssh_poll_new.
int server_set_kex(ssh_session session)
References ssh_kex_struct::cookie, ssh_session_struct::dsa_key, ssh_session_struct::ecdsa_key, ssh_session_struct::ed25519_key, ssh_kex_struct::methods, ssh_session_struct::next_crypto, ssh_session_struct::opts, rc, ssh_session_struct::rsa_key, SAFE_FREE, ssh_crypto_struct::server_kex, session, ssh_session_struct::srv, SSH_FATAL, ssh_find_all_matching, ssh_get_random, SSH_HOSTKEYS, ssh_kex_get_default_methods, ssh_kex_get_fips_methods, SSH_KEX_METHODS, ssh_key_type, ssh_key_type_to_char, ssh_options_set_algo, ssh_set_error, ssh_key_struct::type_c, ssh_session_struct::wanted_methods, ZERO_STRUCTP.
Referenced by ssh_handle_key_exchange, ssh_send_rekex, ssh_server_connection_callback, ssh_server_init_kex.
static int ssh_server_send_extensions(ssh_session session)
References error, ssh_session_struct::opts, ssh_session_struct::out_buffer, ssh_session_struct::pubkey_accepted_types, rc, session, SSH2_MSG_EXT_INFO, ssh_buffer_pack, ssh_buffer_reinit, SSH_ERROR, SSH_HOSTKEYS, ssh_kex_get_default_methods, ssh_kex_get_fips_methods, SSH_LOG, SSH_LOG_PACKET, SSH_OK, ssh_packet_send.
Referenced by ssh_server_connection_callback.
SSH_PACKET_CALLBACK(ssh_packet_kexdh_init)
References ssh_session_struct::dh_handshake_state, DH_STATE_INIT, ssh_session_struct::first_kex_follows_guess_wrong, session, ssh_session_struct::session_state, SSH_LOG, SSH_LOG_DEBUG, SSH_LOG_PACKET, SSH_LOG_RARE, SSH_PACKET_NOT_USED, SSH_PACKET_USED, SSH_SESSION_STATE_ERROR, user.
int ssh_get_key_params(ssh_session session, ssh_key *privkey, enum ssh_digest_e *digest)
References ssh_session_struct::dsa_key, ssh_session_struct::ecdsa_key, ssh_session_struct::ed25519_key, ssh_session_struct::hostkey, ssh_session_struct::hostkey_digest, privkey, pubkey, rc, ssh_session_struct::rsa_key, session, ssh_session_struct::srv, ssh_dh_import_next_pubkey_blob, SSH_FATAL, ssh_key_free, SSH_KEYTYPE_DSS, SSH_KEYTYPE_ECDSA_P256, SSH_KEYTYPE_ECDSA_P384, SSH_KEYTYPE_ECDSA_P521, SSH_KEYTYPE_ED25519, SSH_KEYTYPE_RSA, SSH_KEYTYPE_RSA1, SSH_KEYTYPE_UNKNOWN, SSH_OK, ssh_pki_export_privkey_to_pubkey, ssh_pki_export_pubkey_blob, ssh_set_error, ssh_set_error_oom, SSH_STRING_FREE.
static void ssh_server_connection_callback(ssh_session session)
References ssh_session_struct::alive, ssh_crypto_struct::client_kex, ssh_session_struct::clientbanner, ssh_session_struct::connected, crypt_set_algorithms_server, ssh_socket_callbacks_struct::data, ssh_session_struct::dh_handshake_state, DH_STATE_FINISHED, error, ssh_session_struct::extensions, ssh_session_struct::flags, ssh_kex_struct::methods, ssh_session_struct::next_crypto, rc, ssh_crypto_struct::server_kex, server_set_kex, session, ssh_session_struct::session_state, set_status, ssh_session_struct::socket, ssh_session_struct::socket_callbacks, ssh_analyze_banner, SSH_DIRECTION_IN, SSH_ERROR, SSH_EXT_NEGOTIATION, SSH_FATAL, ssh_kex_select_methods, ssh_list_kex, SSH_LOG, SSH_LOG_PROTOCOL, SSH_OK, ssh_packet_register_socket_callback, ssh_packet_set_default_callbacks, ssh_packet_set_newkeys, ssh_packet_socket_callback, ssh_send_kex, ssh_server_send_extensions, SSH_SESSION_FLAG_AUTHENTICATED, SSH_SESSION_STATE_AUTHENTICATED, SSH_SESSION_STATE_AUTHENTICATING, SSH_SESSION_STATE_BANNER_RECEIVED, SSH_SESSION_STATE_CONNECTING, SSH_SESSION_STATE_DH, SSH_SESSION_STATE_ERROR, SSH_SESSION_STATE_INITIAL_KEX, SSH_SESSION_STATE_KEXINIT_RECEIVED, SSH_SESSION_STATE_NONE, SSH_SESSION_STATE_SOCKET_CONNECTED, ssh_set_error, ssh_socket_close.
Referenced by ssh_handle_key_exchange.
static int callback_receive_banner(const void *data, size_t len, void *user)
References buffer, ssh_session_struct::clientbanner, session, ssh_session_struct::session_state, ssh_session_struct::ssh_connection_callback, SSH_FATAL, SSH_LOG, SSH_LOG_PACKET, SSH_SESSION_STATE_BANNER_RECEIVED, SSH_SESSION_STATE_ERROR, ssh_set_error, user.
Referenced by ssh_handle_key_exchange.
static int ssh_server_kex_termination(void *s)
References s, session, ssh_session_struct::session_state, SSH_SESSION_STATE_AUTHENTICATING, SSH_SESSION_STATE_DISCONNECTED, SSH_SESSION_STATE_ERROR.
Referenced by ssh_handle_key_exchange.
int ssh_auth_reply_default(ssh_session session, int partial)
References ssh_session_struct::auth, ssh_session_struct::out_buffer, rc, session, SSH2_MSG_USERAUTH_FAILURE, SSH_AUTH_METHOD_GSSAPI_MIC, SSH_AUTH_METHOD_HOSTBASED, SSH_AUTH_METHOD_INTERACTIVE, SSH_AUTH_METHOD_PASSWORD, SSH_AUTH_METHOD_PUBLICKEY, ssh_buffer_pack, SSH_ERROR, SSH_LOG, SSH_LOG_PACKET, SSH_OK, ssh_packet_send, ssh_set_error_oom, ssh_session_struct::supported_methods.
Referenced by ssh_auth_reply_success, ssh_message_reply_default.
static int ssh_message_channel_request_open_reply_default(ssh_message msg)
References ssh_message_struct::channel_request_open, ssh_session_struct::out_buffer, rc, ssh_channel_request_open::sender, ssh_message_struct::session, SSH2_MSG_CHANNEL_OPEN_FAILURE, SSH2_OPEN_ADMINISTRATIVELY_PROHIBITED, ssh_buffer_pack, SSH_ERROR, SSH_LOG, SSH_LOG_FUNCTIONS, SSH_OK, ssh_packet_send, ssh_set_error_oom.
Referenced by ssh_message_reply_default.
static int ssh_message_channel_request_reply_default(ssh_message msg)
References ssh_channel_request::channel, ssh_message_struct::channel_request, ssh_session_struct::out_buffer, rc, ssh_channel_struct::remote_channel, ssh_message_struct::session, SSH2_MSG_CHANNEL_FAILURE, ssh_buffer_pack, SSH_ERROR, SSH_LOG, SSH_LOG_PACKET, SSH_OK, ssh_packet_send, ssh_set_error_oom, ssh_channel_request::want_reply.
Referenced by ssh_message_reply_default.
static int ssh_message_service_request_reply_default(ssh_message msg)
References ssh_message_service_reply_success.
Referenced by ssh_message_reply_default.
static int ssh_message_global_request_reply_default(ssh_message msg)
References error, ssh_message_struct::global_request, ssh_session_struct::out_buffer, ssh_message_struct::session, SSH2_MSG_REQUEST_FAILURE, ssh_buffer_add_u8, SSH_ERROR, SSH_LOG, SSH_LOG_FUNCTIONS, SSH_LOG_PACKET, SSH_OK, ssh_packet_send, ssh_global_request::want_reply.
Referenced by ssh_message_reply_default.
ssh_public_key ssh_message_auth_publickey(ssh_message msg)
References ssh_message_struct::auth_request, ssh_auth_request::pubkey, ssh_pki_convert_key_to_publickey.
int ssh_auth_reply_success(ssh_session session, int partial)
References ssh_crypto_struct::delayed_compress_in, ssh_crypto_struct::delayed_compress_out, ssh_crypto_struct::do_compress_in, ssh_crypto_struct::do_compress_out, ssh_session_struct::flags, ssh_session_struct::out_buffer, session, ssh_session_struct::session_state, SSH2_MSG_USERAUTH_SUCCESS, ssh_auth_reply_default, ssh_buffer_add_u8, SSH_DIRECTION_IN, SSH_DIRECTION_OUT, SSH_ERROR, SSH_LOG, SSH_LOG_PROTOCOL, ssh_packet_get_current_crypto, ssh_packet_send, SSH_SESSION_FLAG_AUTHENTICATED, SSH_SESSION_STATE_AUTHENTICATED.
Referenced by ssh_message_auth_reply_success.
SERVERBANNER
SOCKOPT_TYPE_ARG4