libssh_messages
static ssh_message ssh_message_new(ssh_session session)
References ssh_message_struct::auth_request, ssh_message_struct::session, session, ssh_auth_request::signature_state, SSH_PUBLICKEY_STATE_NONE.
Referenced by ssh_message_handle_channel_request, SSH_PACKET_CALLBACK.
static int ssh_message_reply_default(ssh_message msg)
References error, ssh_session_struct::out_buffer, ssh_session_struct::recv_seq, ssh_message_struct::session, SSH2_MSG_UNIMPLEMENTED, ssh_buffer_add_u32, ssh_buffer_add_u8, SSH_ERROR, SSH_LOG, SSH_LOG_FUNCTIONS, ssh_packet_send.
Referenced by ssh_execute_message_callback, ssh_message_queue.
static int ssh_execute_message_callback(ssh_session session, ssh_message msg)
References session, ssh_session_struct::ssh_message_callback, ssh_session_struct::ssh_message_callback_data, SSH_MESSAGE_FREE, ssh_message_reply_default, SSH_OK.
Referenced by ssh_message_queue.
static void ssh_message_queue(ssh_session session, ssh_message message)
References ssh_session_struct::server_callbacks, session, ssh_execute_message_callback, ssh_list_append, ssh_list_new, ssh_session_struct::ssh_message_callback, SSH_MESSAGE_FREE, ssh_session_struct::ssh_message_list, ssh_message_reply_default, SSH_OK, ssh_set_error_oom.
Referenced by ssh_message_handle_channel_request, SSH_PACKET_CALLBACK.
ssh_message ssh_message_pop_head(ssh_session session)
References session, ssh_iterator_value, ssh_list_get_iterator, ssh_list_remove, ssh_session_struct::ssh_message_list.
Referenced by ssh_execute_message_callbacks, ssh_message_get.
static int ssh_message_termination(void *s)
References s, session, ssh_session_struct::session_state, ssh_list_get_iterator, ssh_session_struct::ssh_message_list, SSH_SESSION_STATE_ERROR.
Referenced by ssh_message_get.
ssh_message ssh_message_get(ssh_session session)
Retrieve a SSH message from a SSH session.
session The SSH session to get the message. The SSH message received, NULL in case of error, or timeout elapsed. This function blocks until a message has been received. Betterset up a callback if this behavior is unwanted.
References rc, session, ssh_session_struct::session_state, ssh_handle_packets_termination, ssh_list_new, ssh_list_pop_head, ssh_session_struct::ssh_message_list, ssh_message_pop_head, ssh_message_termination, SSH_SESSION_STATE_ERROR, SSH_TIMEOUT_USER.
Referenced by authenticate, main.
int ssh_message_type(ssh_message msg)
Get the type of the message.
msg The message to get the type from. The message type or -1 on error.
References ssh_message_struct::type.
Referenced by authenticate, authenticate_callback, global_request, main, message_callback, ssh_channel_accept.
int ssh_message_subtype(ssh_message msg)
Get the subtype of the message.
msg The message to get the subtype from. The message type or -1 on error.
References ssh_message_struct::auth_request, ssh_message_struct::channel_request, ssh_message_struct::channel_request_open, ssh_message_struct::global_request, ssh_auth_request::method, SSH_REQUEST_AUTH, SSH_REQUEST_CHANNEL, SSH_REQUEST_CHANNEL_OPEN, SSH_REQUEST_GLOBAL, ssh_channel_request_open::type, ssh_global_request::type, ssh_channel_request::type, ssh_message_struct::type.
Referenced by authenticate, authenticate_callback, main, message_callback, ssh_channel_accept.
void ssh_message_free(ssh_message msg)
Free a SSH message.
msg The message to release the memory.
References ssh_message_struct::auth_request, ssh_global_request::bind_address, ssh_message_struct::channel_request, ssh_message_struct::channel_request_open, ssh_channel_request::command, ssh_channel_request_open::destination, explicit_bzero, ssh_message_struct::global_request, ssh_channel_request::modes, ssh_channel_request_open::originator, ssh_auth_request::password, ssh_auth_request::pubkey, SAFE_FREE, ssh_service_request::service, ssh_message_struct::service_request, SSH_CHANNEL_REQUEST_ENV, SSH_CHANNEL_REQUEST_EXEC, SSH_CHANNEL_REQUEST_PTY, SSH_CHANNEL_REQUEST_SUBSYSTEM, SSH_CHANNEL_REQUEST_X11, ssh_key_free, SSH_REQUEST_AUTH, SSH_REQUEST_CHANNEL, SSH_REQUEST_CHANNEL_OPEN, SSH_REQUEST_GLOBAL, SSH_REQUEST_SERVICE, ssh_channel_request::subsystem, ssh_channel_request::TERM, ssh_channel_request::type, ssh_message_struct::type, ssh_auth_request::username, ssh_channel_request::var_name, ssh_channel_request::var_value, ssh_channel_request::x11_auth_cookie, ssh_channel_request::x11_auth_protocol, ZERO_STRUCTP.
Referenced by authenticate, authenticate_callback, main, ssh_channel_accept, ssh_disconnect, ssh_execute_message_callbacks, ssh_free.
SSH_PACKET_CALLBACK(ssh_packet_userauth_info_response)
References session, SSH_PACKET_USED, user.
SSH_PACKET_CALLBACK(ssh_packet_channel_open)
References ssh_message_struct::channel_request_open, ssh_channel_request_open::destination, ssh_channel_request_open::destination_port, error, ssh_channel_request_open::originator, ssh_channel_request_open::originator_port, ssh_channel_request_open::packet_size, rc, SAFE_FREE, ssh_channel_request_open::sender, session, ssh_session_struct::session_state, ssh_buffer_unpack, SSH_CHANNEL_AUTH_AGENT, SSH_CHANNEL_DIRECT_TCPIP, SSH_CHANNEL_FORWARDED_TCPIP, SSH_CHANNEL_SESSION, SSH_CHANNEL_UNKNOWN, SSH_CHANNEL_X11, SSH_FATAL, SSH_LOG, SSH_LOG_PACKET, SSH_MESSAGE_FREE, ssh_message_new, ssh_message_queue, SSH_OK, SSH_PACKET_USED, SSH_REQUEST_CHANNEL_OPEN, SSH_SESSION_STATE_AUTHENTICATED, ssh_set_error, ssh_set_error_oom, ssh_channel_request_open::type, ssh_message_struct::type, user, ssh_channel_request_open::window.
int ssh_message_channel_request_open_reply_accept_channel(ssh_message msg, ssh_channel chan)
References chan, ssh_message_struct::channel_request_open, ssh_channel_struct::flags, ssh_channel_struct::local_channel, ssh_channel_struct::local_maxpacket, ssh_channel_struct::local_window, ssh_session_struct::out_buffer, ssh_channel_request_open::packet_size, rc, ssh_channel_struct::remote_channel, ssh_channel_struct::remote_maxpacket, ssh_channel_struct::remote_window, ssh_channel_request_open::sender, ssh_message_struct::session, session, SSH2_MSG_CHANNEL_OPEN_CONFIRMATION, ssh_buffer_pack, SSH_CHANNEL_FLAG_NOT_BOUND, ssh_channel_new_id, SSH_CHANNEL_STATE_OPEN, SSH_ERROR, SSH_LOG, SSH_LOG_PACKET, SSH_OK, ssh_packet_send, ssh_set_error_oom, ssh_channel_struct::state, ssh_channel_request_open::window.
Referenced by ssh_message_channel_request_open_reply_accept.
ssh_channel ssh_message_channel_request_open_reply_accept(ssh_message msg)
References chan, rc, ssh_message_struct::session, ssh_channel_free, ssh_channel_new, ssh_message_channel_request_open_reply_accept_channel.
Referenced by main, message_callback, ssh_channel_accept.
int ssh_message_handle_channel_request(ssh_session session, ssh_channel channel, ssh_buffer packet, const char *request, uint8_t want_reply)
References ssh_channel_request::channel, ssh_message_struct::channel_request, ssh_channel_request::command, error, ssh_channel_request::height, ssh_channel_struct::local_channel, ssh_channel_request::modes, ssh_channel_request::pxheight, ssh_channel_request::pxwidth, rc, ssh_channel_struct::remote_channel, session, ssh_buffer_unpack, SSH_CHANNEL_REQUEST_ENV, SSH_CHANNEL_REQUEST_EXEC, SSH_CHANNEL_REQUEST_PTY, SSH_CHANNEL_REQUEST_SHELL, SSH_CHANNEL_REQUEST_SUBSYSTEM, SSH_CHANNEL_REQUEST_UNKNOWN, SSH_CHANNEL_REQUEST_WINDOW_CHANGE, SSH_CHANNEL_REQUEST_X11, SSH_ERROR, SSH_LOG, SSH_LOG_PACKET, SSH_MESSAGE_FREE, ssh_message_new, ssh_message_queue, SSH_OK, SSH_REQUEST_CHANNEL, ssh_set_error_oom, ssh_channel_request::subsystem, ssh_channel_request::TERM, ssh_channel_request::type, ssh_message_struct::type, ssh_channel_request::var_name, ssh_channel_request::var_value, ssh_channel_request::want_reply, ssh_channel_request::width, ssh_channel_request::x11_auth_cookie, ssh_channel_request::x11_auth_protocol, ssh_channel_request::x11_screen_number, ssh_channel_request::x11_single_connection.
Referenced by SSH_PACKET_CALLBACK.
int ssh_message_channel_request_reply_success(ssh_message msg)
References ssh_channel_request::channel, ssh_message_struct::channel_request, ssh_session_struct::out_buffer, rc, ssh_channel_struct::remote_channel, ssh_message_struct::session, SSH2_MSG_CHANNEL_SUCCESS, ssh_buffer_pack, SSH_ERROR, SSH_LOG, SSH_LOG_PACKET, SSH_OK, ssh_packet_send, ssh_set_error_oom, ssh_channel_request::want_reply.
Referenced by main.