libssh_pki
static int pki_openssh_import_privkey_blob(ssh_buffer key_blob_buffer, ssh_key *pkey)
References key, pki_import_privkey_buffer, rc, SAFE_FREE, ssh_buffer_unpack, SSH_ERROR, ssh_key_free, ssh_key_type_from_name, SSH_KEYTYPE_UNKNOWN, SSH_LOG, SSH_LOG_WARN, SSH_OK.
Referenced by ssh_pki_openssh_import.
static int pki_private_key_decrypt(ssh_string blob, const char *passphrase, const char *ciphername, const char *kdfname, ssh_string kdfoptions, ssh_auth_callback auth_fn, void *auth_data)
decrypts an encrypted private key blob in OpenSSH format.
References bcrypt_pbkdf, ssh_cipher_struct::blocksize, buffer, ssh_cipher_struct::decrypt, explicit_bzero, ssh_cipher_struct::keysize, name, ssh_cipher_struct::name, rc, SAFE_FREE, ssh_cipher_struct::set_decrypt_key, ssh_buffer_add_data, SSH_BUFFER_FREE, ssh_buffer_new, ssh_buffer_unpack, ssh_cipher_clear, SSH_ERROR, ssh_get_ciphertab, SSH_LOG, SSH_LOG_DEBUG, SSH_LOG_WARN, SSH_OK, ssh_string_data, ssh_string_len.
Referenced by ssh_pki_openssh_import.
static ssh_key ssh_pki_openssh_import(const char *text_key, const char *passphrase, ssh_auth_callback auth_fn, void *auth_data, bool private)
References base64_to_bin, buffer, key, OPENSSH_AUTH_MAGIC, OPENSSH_HEADER_BEGIN, OPENSSH_HEADER_END, pki_openssh_import_privkey_blob, pki_private_key_decrypt, rc, SAFE_FREE, ssh_buffer_add_data, SSH_BUFFER_FREE, ssh_buffer_get_len, ssh_buffer_get_ssh_string, ssh_buffer_get_u8, ssh_buffer_new, ssh_buffer_set_secure, ssh_buffer_unpack, SSH_ERROR, ssh_key_free, SSH_LOG, SSH_LOG_INFO, SSH_LOG_WARN, SSH_OK, ssh_pki_import_pubkey_blob, ssh_string_data, ssh_string_len.
Referenced by ssh_pki_openssh_privkey_import, ssh_pki_openssh_pubkey_import.
ssh_key ssh_pki_openssh_privkey_import(const char *text_key, const char *passphrase, ssh_auth_callback auth_fn, void *auth_data)
References ssh_pki_openssh_import.
Referenced by ssh_pki_import_privkey_base64.
ssh_key ssh_pki_openssh_pubkey_import(const char *text_key)
References ssh_pki_openssh_import.
Referenced by ssh_pki_import_pubkey_file.
static int pki_openssh_export_privkey_blob(const ssh_key privkey, ssh_buffer buffer)
References buffer, ED25519_KEY_LEN, privkey, rc, ssh_buffer_pack, SSH_ERROR, SSH_KEYTYPE_ED25519, SSH_LOG, SSH_LOG_WARN.
Referenced by ssh_pki_openssh_privkey_export.
static int pki_private_key_encrypt(ssh_buffer privkey_buffer, const char *passphrase, const char *ciphername, const char *kdfname, ssh_auth_callback auth_fn, void *auth_data, uint32_t rounds, ssh_string salt)
References bcrypt_pbkdf, ssh_cipher_struct::blocksize, ssh_cipher_struct::encrypt, explicit_bzero, ssh_cipher_struct::keysize, name, ssh_cipher_struct::name, rc, ssh_cipher_struct::set_encrypt_key, ssh_buffer_get, ssh_buffer_get_len, ssh_cipher_clear, SSH_ERROR, ssh_get_ciphertab, SSH_LOG, SSH_LOG_WARN, SSH_OK, ssh_string_data, ssh_string_len.
Referenced by ssh_pki_openssh_privkey_export.
ssh_string ssh_pki_openssh_privkey_export(const ssh_key privkey, const char *passphrase, ssh_auth_callback auth_fn, void *auth_data)
References bin_to_base64, buffer, error, explicit_bzero, OPENSSH_AUTH_MAGIC, OPENSSH_HEADER_BEGIN, OPENSSH_HEADER_END, pki_openssh_export_privkey_blob, pki_private_key_encrypt, pki_publickey_to_blob, privkey, rc, SAFE_FREE, ssh_buffer_add_u8, SSH_BUFFER_FREE, ssh_buffer_get, ssh_buffer_get_data, ssh_buffer_get_len, ssh_buffer_new, ssh_buffer_pack, ssh_buffer_reinit, SSH_ERROR, ssh_get_random, SSH_KEYTYPE_ED25519, SSH_LOG, SSH_LOG_INFO, SSH_LOG_WARN, SSH_OK, ssh_string_data, SSH_STRING_FREE, ssh_string_new.
Referenced by ssh_pki_export_privkey_base64, ssh_pki_export_privkey_file.
enum ssh_keytypes_e pki_privatekey_type_from_string(const char *privkey)
const char* ssh_pki_key_ecdsa_name(const ssh_key key)
returns the ECDSA key name ("ecdsa-sha2-nistp256" for example)
key the ssh_key whose ECDSA name to get the ECDSA key name ("ecdsa-sha2-nistp256" for example) "unknown" if the ECDSA key name is not known
References key, pki_key_ecdsa_nid_to_name.
Referenced by pki_import_pubkey_buffer, ssh_pki_generate, torture_ecdsa_sign_verify_uri, torture_pki_ecdsa_name, torture_pki_generate_key_ecdsa.
ssh_key ssh_key_new(void)
creates a new empty SSH key
an empty ssh_key handle, or NULL on error.
References ZERO_STRUCTP.
Referenced by pki_import_cert_buffer, pki_import_privkey_buffer, pki_import_pubkey_buffer, pki_key_dup, pki_private_key_from_base64, pki_uri_import, publickey_from_privatekey, publickey_to_string, ssh_pki_generate, ssh_userauth_agent_pubkey, ssh_userauth_pubkey.
ssh_key ssh_key_dup(const ssh_key key)
References key, pki_key_dup.
Referenced by ssh_bind_accept_fd, ssh_get_server_publickey, ssh_pki_convert_key_to_publickey, thread_pki_rsa_duplicate_key, torture_pki_dsa_duplicate_key, torture_pki_ecdsa_duplicate_key, torture_pki_ecdsa_duplicate_key_uri, torture_pki_ecdsa_duplicate_then_demote, torture_pki_ecdsa_duplicate_then_demote_uri, torture_pki_ed25519_privkey_dup, torture_pki_ed25519_pubkey_dup, torture_pki_rsa_duplicate_key.
void ssh_key_clean(ssh_key key)
clean up the key and deallocate all existing keys
key ssh_key to clean
References ED25519_KEY_LEN, explicit_bzero, key, SAFE_FREE, SSH_BUFFER_FREE, SSH_KEY_FLAG_EMPTY, SSH_KEYTYPE_SK_ECDSA, SSH_KEYTYPE_SK_ECDSA_CERT01, SSH_KEYTYPE_SK_ED25519, SSH_KEYTYPE_SK_ED25519_CERT01, SSH_KEYTYPE_UNKNOWN, ssh_string_burn, ssh_string_free.
Referenced by ssh_key_free.
void ssh_key_free(ssh_key key)
deallocate a SSH key
key ssh_key handle to free
References key, SAFE_FREE, ssh_key_clean.
Referenced by auth_keyfile, auth_publickey, crypto_free, pki_import_cert_buffer, pki_import_privkey_buffer, pki_import_pubkey_buffer, pki_key_dup, pki_openssh_import_privkey_blob, pki_private_key_from_base64, pki_uri_import, privatekey_from_file, publickey_from_file, publickey_from_privatekey, publickey_from_string, publickey_to_string, ssh_agent_state_free, ssh_bind_free, ssh_bind_import_keys, ssh_bind_listen, ssh_free, ssh_get_key_params, ssh_get_pubkey_hash, ssh_knownhosts_entry_free, ssh_message_free, ssh_pki_convert_key_to_privatekey, ssh_pki_convert_key_to_publickey, ssh_pki_generate, ssh_pki_openssh_import, ssh_userauth_agent, ssh_userauth_agent_pubkey, ssh_userauth_offer_pubkey, ssh_userauth_pubkey, ssh_userauth_publickey_auto, verify_knownhost.
enum ssh_keytypes_e ssh_key_type(const ssh_key key)
returns the type of a ssh key
key the ssh_key handle one of SSH_KEYTYPE_RSA, SSH_KEYTYPE_DSS, SSH_KEYTYPE_ECDSA_P256, SSH_KEYTYPE_ECDSA_P384, SSH_KEYTYPE_ECDSA_P521, SSH_KEYTYPE_ED25519, SSH_KEYTYPE_DSS_CERT01, SSH_KEYTYPE_RSA_CERT01, SSH_KEYTYPE_ECDSA_P256_CERT01, SSH_KEYTYPE_ECDSA_P384_CERT01, SSH_KEYTYPE_ECDSA_P521_CERT01, or SSH_KEYTYPE_ED25519_CERT01. SSH_KEYTYPE_UNKNOWN if the type is unknown
Referenced by pkd_auth_pubkey_cb, server_set_kex, ssh_bind_import_keys, ssh_is_server_known, thread_pki_rsa_import_cert_file, thread_pki_rsa_import_privkey_base64, torture_ecdsa_sign_verify_uri, torture_knownhosts_parse_line_default_ed25519, torture_knownhosts_parse_line_ecdsa, torture_knownhosts_parse_line_hashed_ed25519, torture_knownhosts_parse_line_pattern_ed25519, torture_knownhosts_parse_line_port_ed25519, torture_knownhosts_parse_line_port_wildcard, torture_knownhosts_parse_line_rsa, torture_knownhosts_parse_line_standard_port, torture_knownhosts_read_file, torture_pki_dsa_import_cert_file, torture_pki_ecdsa_import_cert_file, torture_pki_ed25519_generate_key, torture_pki_ed25519_import_cert_file, torture_pki_ed25519_import_export_privkey_base64, torture_pki_ed25519_import_privkey_base64, torture_pki_ed25519_import_privkey_base64_comment, torture_pki_ed25519_import_privkey_base64_whitespace, torture_pki_generate_key_ecdsa, torture_pki_keytype, torture_pki_rsa_import_cert_file, torture_pki_rsa_import_privkey_base64, torture_pki_rsa_import_privkey_base64_comment, torture_pki_rsa_import_privkey_base64_whitespace.
const char* ssh_key_signature_to_char(enum ssh_keytypes_e type, enum ssh_digest_e hash_type)
Convert a signature type to a string.
type The algorithm type to convert. A string for the keytype or NULL if unknown.
References SSH_DIGEST_AUTO, SSH_DIGEST_SHA1, SSH_DIGEST_SHA256, SSH_DIGEST_SHA512, ssh_key_type_to_char, SSH_KEYTYPE_RSA, SSH_KEYTYPE_RSA_CERT01.
Referenced by pki_do_sign_hash, pki_sign_data, pki_signature_from_blob, ssh_key_get_signature_algorithm.
const char* ssh_key_type_to_char(enum ssh_keytypes_e type)
Convert a key type to a string.
type The type to convert. A string for the keytype or NULL if unknown.
Referenced by pkd_auth_pubkey_cb, pki_import_cert_buffer, pki_import_privkey_buffer, pki_import_pubkey_buffer, pki_private_key_from_base64, pki_uri_import, publickey_from_privatekey, server_set_kex, ssh_is_server_known, ssh_key_signature_to_char, ssh_known_hosts_parse_line, ssh_pki_generate, ssh_type_to_char, ssh_userauth_agent_pubkey, ssh_userauth_pubkey, torture_ecdsa_sign_verify_uri, torture_pki_ed25519_generate_key, torture_pki_generate_key_ecdsa, torture_pki_keytype.
enum ssh_digest_e ssh_key_hash_from_name(const char *name)
References SSH_KEYTYPE_DSS, SSH_KEYTYPE_DSS_CERT01, SSH_KEYTYPE_ECDSA, SSH_KEYTYPE_ECDSA_P256, SSH_KEYTYPE_ECDSA_P256_CERT01, SSH_KEYTYPE_ECDSA_P384, SSH_KEYTYPE_ECDSA_P384_CERT01, SSH_KEYTYPE_ECDSA_P521, SSH_KEYTYPE_ECDSA_P521_CERT01, SSH_KEYTYPE_ED25519, SSH_KEYTYPE_ED25519_CERT01, SSH_KEYTYPE_RSA, SSH_KEYTYPE_RSA1, SSH_KEYTYPE_RSA_CERT01, SSH_KEYTYPE_SK_ECDSA, SSH_KEYTYPE_SK_ECDSA_CERT01, SSH_KEYTYPE_SK_ED25519, SSH_KEYTYPE_SK_ED25519_CERT01, SSH_KEYTYPE_UNKNOWN.
Referenced by ssh_pki_import_signature_blob.
int ssh_key_algorithm_allowed(ssh_session session, const char *type)
Checks the given key against the configured allowed public key algorithm types.
session The SSH session type The key algorithm to check 1 if the key algorithm is allowed, 0 otherwise
References ssh_session_struct::client, ssh_session_struct::opts, ssh_session_struct::pubkey_accepted_types, ssh_session_struct::server, session, SSH_HOSTKEYS, ssh_kex_get_default_methods, ssh_kex_get_fips_methods, SSH_LOG, SSH_LOG_DEBUG, SSH_LOG_WARN, ssh_match_group, ssh_session_struct::wanted_methods.
Referenced by ssh_userauth_agent_publickey, ssh_userauth_publickey, ssh_userauth_try_publickey.
enum ssh_digest_e ssh_key_type_to_hash(ssh_session session, enum ssh_keytypes_e type)
Convert a key type to a hash type. This is usually unambiguous for all the key types, unless the SHA2 extension (RFC 8332) is negotiated during key exchange.
session SSH Session. type The type to convert. A hash type to be used.
Referenced by ssh_key_get_signature_algorithm, ssh_userauth_publickey, torture_options_set_pubkey_accepted_types, torture_pki_ecdsa_cert_verify.
const char* ssh_key_get_signature_algorithm(ssh_session session, enum ssh_keytypes_e type)
Gets signature algorithm name to be used with the given key type.
session SSH session. type The algorithm type to convert. A string for the keytype or NULL if unknown.
References ssh_session_struct::openssh, session, ssh_key_signature_to_char, ssh_key_type_to_hash, SSH_KEYTYPE_RSA_CERT01, SSH_LOG, SSH_LOG_DEBUG, SSH_VERSION_INT.
Referenced by ssh_userauth_agent_publickey, ssh_userauth_publickey, ssh_userauth_try_publickey.
enum ssh_keytypes_e ssh_key_type_from_signature_name(const char *name)
Convert a ssh key algorithm name to a ssh key algorithm type.
name The name to convert. The enum ssh key algorithm type.
Referenced by ssh_pki_import_signature_blob.
enum ssh_keytypes_e ssh_key_type_from_name(const char *name)
Convert a ssh key name to a ssh key type.
name The name to convert. The enum ssh key type.
Referenced by pki_openssh_import_privkey_blob, setup_rsa_key, ssh_known_hosts_parse_line, ssh_pki_import_pubkey_blob, ssh_pki_import_pubkey_file, ssh_type_from_name, thread_pki_rsa_publickey_base64, torture_pki_dsa_publickey_base64, torture_pki_ecdsa_publickey_base64, torture_pki_ed25519_publickey_base64, torture_pki_keytype, torture_pki_rsa_publickey_base64.
enum ssh_keytypes_e ssh_key_type_plain(enum ssh_keytypes_e type)
Get the pubic key type corresponding to a certificate type.
type The certificate or public key type. The matching public key type.
Referenced by pki_signature_from_blob, ssh_agent_sign_data, ssh_pki_signature_verify, torture_pki_verify_mismatch.
int ssh_key_is_public(const ssh_key k)
Check if the key has/is a public key.
k The key to check. 1 if it is a public key, 0 if not.
References k, SSH_KEY_FLAG_PUBLIC.
Referenced by ssh_userauth_try_publickey, thread_pki_rsa_import_cert_file, thread_pki_rsa_import_privkey_base64, torture_pki_dsa_import_cert_file, torture_pki_ecdsa_import_cert_file, torture_pki_ecdsa_import_pubkey_uri, torture_pki_ed25519_import_cert_file, torture_pki_ed25519_import_privkey_base64, torture_pki_ed25519_import_privkey_base64_comment, torture_pki_ed25519_import_privkey_base64_whitespace, torture_pki_ed25519_pubkey_dup, torture_pki_rsa_import_cert_file, torture_pki_rsa_import_privkey_base64, torture_pki_rsa_import_privkey_base64_comment, torture_pki_rsa_import_privkey_base64_whitespace, torture_pki_rsa_import_pubkey_uri.
int ssh_key_is_private(const ssh_key k)
Check if the key is a private key.
k The key to check. 1 if it is a private key, 0 if not.
References k, SSH_KEY_FLAG_PRIVATE.
Referenced by pki_key_dup, pki_key_to_pkey, pki_sign_data, pki_verify_data_signature, ssh_key_cmp, ssh_pki_do_sign, ssh_pki_export_privkey_base64, ssh_pki_export_privkey_file, ssh_pki_export_privkey_to_pubkey, ssh_userauth_publickey, thread_pki_rsa_import_privkey_base64, thread_pki_rsa_import_privkey_base64_passphrase, thread_pki_rsa_publickey_from_privatekey, torture_pki_dsa_import_openssh_privkey_base64_passphrase, torture_pki_dsa_import_privkey_base64_passphrase, torture_pki_dsa_publickey_from_privatekey, torture_pki_ecdsa_import_privkey_base64, torture_pki_ecdsa_import_privkey_base64_comment, torture_pki_ecdsa_import_privkey_base64_whitespace, torture_pki_ed25519_import_export_privkey_base64, torture_pki_ed25519_import_privkey_base64, torture_pki_ed25519_import_privkey_base64_comment, torture_pki_ed25519_import_privkey_base64_passphrase, torture_pki_ed25519_import_privkey_base64_whitespace, torture_pki_ed25519_privkey_dup, torture_pki_ed25519_publickey_from_privatekey, torture_pki_rsa_import_openssh_privkey_base64_passphrase, torture_pki_rsa_import_privkey_base64, torture_pki_rsa_import_privkey_base64_comment, torture_pki_rsa_import_privkey_base64_passphrase, torture_pki_rsa_import_privkey_base64_whitespace, torture_pki_rsa_import_privkey_uri, torture_pki_rsa_publickey_from_privatekey, torture_pki_rsa_publickey_from_privatekey_uri.
int ssh_key_cmp(const ssh_key k1, const ssh_key k2, enum ssh_keycmp_e what)
Compare keys if they are equal.
k1 The first key to compare. k2 The second key to compare. what What part or type of the key do you want to compare. 0 if equal, 1 if not.
References pki_ed25519_key_cmp, pki_key_compare, ssh_key_struct::sk_application, SSH_KEY_CMP_PRIVATE, ssh_key_is_private, SSH_KEYTYPE_ED25519, SSH_KEYTYPE_SK_ECDSA, SSH_KEYTYPE_SK_ED25519, SSH_LOG, SSH_LOG_WARN, ssh_string_get_char, ssh_string_len, ssh_key_struct::type.
Referenced by auth_publickey, ssh_known_hosts_entries_compare, thread_pki_rsa_duplicate_key, torture_pki_dsa_duplicate_key, torture_pki_ecdsa_duplicate_key, torture_pki_ecdsa_duplicate_key_uri, torture_pki_ed25519_write_privkey, torture_pki_rsa_duplicate_key.
ssh_signature ssh_signature_new(void)
References ZERO_STRUCTP.
Referenced by pki_do_sign_hash, pki_sign_data, pki_signature_from_blob.
void ssh_signature_free(ssh_signature sig)
References ssh_signature_struct::ed25519_sig, ssh_signature_struct::raw_sig, SAFE_FREE, SSH_KEYTYPE_DSS, SSH_KEYTYPE_DSS_CERT01, SSH_KEYTYPE_ECDSA, SSH_KEYTYPE_ECDSA_P256, SSH_KEYTYPE_ECDSA_P256_CERT01, SSH_KEYTYPE_ECDSA_P384, SSH_KEYTYPE_ECDSA_P384_CERT01, SSH_KEYTYPE_ECDSA_P521, SSH_KEYTYPE_ECDSA_P521_CERT01, SSH_KEYTYPE_ED25519, SSH_KEYTYPE_ED25519_CERT01, SSH_KEYTYPE_RSA, SSH_KEYTYPE_RSA1, SSH_KEYTYPE_RSA_CERT01, SSH_KEYTYPE_SK_ECDSA, SSH_KEYTYPE_SK_ECDSA_CERT01, SSH_KEYTYPE_SK_ED25519, SSH_KEYTYPE_SK_ED25519_CERT01, SSH_KEYTYPE_UNKNOWN, ssh_string_burn, SSH_STRING_FREE, ssh_signature_struct::type.
Referenced by pki_do_sign_hash, pki_sign_data, pki_signature_from_blob, SSH_PACKET_CALLBACK, ssh_pki_do_sign, test_sign_verify_data, thread_pki_rsa_generate_key, torture_ecdsa_sign_verify_uri, torture_pki_dsa_cert_verify, torture_pki_dsa_generate_key, torture_pki_ecdsa_cert_verify, torture_pki_ed25519_cert_verify, torture_pki_ed25519_generate_key, torture_pki_ed25519_sign, torture_pki_ed25519_sign_openssh_privkey_passphrase, torture_pki_ed25519_verify, torture_pki_ed25519_verify_bad, torture_pki_fail_sign_with_incompatible_hash, torture_pki_generate_key_ecdsa, torture_pki_rsa_generate_key, torture_pki_rsa_sha2, torture_pki_sign_verify_uri, torture_pki_verify_mismatch.
int ssh_pki_import_privkey_base64(const char *b64_key, const char *passphrase, ssh_auth_callback auth_fn, void *auth_data, ssh_key *pkey)
import a base64 formated key from a memory c-string
b64_key The c-string holding the base64 encoded key passphrase The passphrase to decrypt the key, or NULL auth_fn An auth function you may want to use or NULL. auth_data Private data passed to the auth function. pkey A pointer where the allocated key can be stored. You need to free the memory. SSH_ERROR in case of error, SSH_OK otherwise. ssh_key_free()
References key, OPENSSH_HEADER_BEGIN, pki_private_key_from_base64, SSH_ERROR, SSH_LOG, SSH_LOG_INFO, SSH_OK, ssh_pki_openssh_privkey_import.
Referenced by ssh_pki_import_privkey_file, thread_pki_rsa_copy_cert_to_privkey, thread_pki_rsa_import_privkey_base64, thread_pki_rsa_import_privkey_base64_NULL_key, thread_pki_rsa_import_privkey_base64_NULL_str, thread_pki_rsa_import_privkey_base64_passphrase, thread_pki_rsa_publickey_from_privatekey, torture_pki_dsa_import_openssh_privkey_base64_passphrase, torture_pki_dsa_import_privkey_base64, torture_pki_dsa_import_privkey_base64_comment, torture_pki_dsa_import_privkey_base64_passphrase, torture_pki_dsa_import_privkey_base64_whitespace, torture_pki_dsa_publickey_from_privatekey, torture_pki_ecdsa_import_privkey_base64, torture_pki_ecdsa_import_privkey_base64_comment, torture_pki_ecdsa_import_privkey_base64_whitespace, torture_pki_ecdsa_publickey_from_privatekey, torture_pki_ed25519_import_export_privkey_base64, torture_pki_ed25519_import_privkey_base64, torture_pki_ed25519_import_privkey_base64_comment, torture_pki_ed25519_import_privkey_base64_passphrase, torture_pki_ed25519_import_privkey_base64_whitespace, torture_pki_ed25519_privkey_dup, torture_pki_ed25519_publickey_from_privatekey, torture_pki_ed25519_sign, torture_pki_ed25519_sign_openssh_privkey_passphrase, torture_pki_rsa_copy_cert_to_privkey, torture_pki_rsa_import_openssh_privkey_base64_passphrase, torture_pki_rsa_import_privkey_base64, torture_pki_rsa_import_privkey_base64_comment, torture_pki_rsa_import_privkey_base64_NULL_key, torture_pki_rsa_import_privkey_base64_NULL_str, torture_pki_rsa_import_privkey_base64_passphrase, torture_pki_rsa_import_privkey_base64_whitespace, torture_pki_rsa_publickey_from_privatekey.
int ssh_pki_export_privkey_base64(const ssh_key privkey, const char *passphrase, ssh_auth_callback auth_fn, void *auth_data, char **b64_key)
Convert a private key to a pem base64 encoded key, or OpenSSH format for keytype ssh-ed25519.
privkey The private key to export. passphrase The passphrase to use to encrypt the key with or NULL. An empty string means no passphrase. auth_fn An auth function you may want to use or NULL. auth_data Private data passed to the auth function. b64_key A pointer to store the allocated base64 encoded key. You need to free the buffer. SSH_OK on success, SSH_ERROR on error.
References pki_private_key_to_pem, privkey, SSH_ERROR, ssh_key_is_private, SSH_KEYTYPE_ED25519, SSH_OK, ssh_pki_openssh_privkey_export, ssh_string_data, SSH_STRING_FREE, ssh_string_len, strndup.
Referenced by torture_pki_ed25519_import_export_privkey_base64.
int ssh_pki_import_privkey_file(const char *filename, const char *passphrase, ssh_auth_callback auth_fn, void *auth_data, ssh_key *pkey)
Import a key from a file.
filename The filename of the the private key. passphrase The passphrase to decrypt the private key. Set to NULL if none is needed or it is unknown. auth_fn An auth function you may want to use or NULL. auth_data Private data passed to the auth function. pkey A pointer to store the allocated ssh_key. You need to free the key. SSH_OK on success, SSH_EOF if the file doesn't exist or permission denied, SSH_ERROR otherwise. ssh_key_free()
References MAX_PRIVKEY_SIZE, pki_uri_import, rc, SAFE_FREE, SSH_EOF, SSH_ERROR, SSH_KEY_PRIVATE, SSH_LOG, SSH_LOG_WARN, ssh_pki_import_privkey_base64, ssh_pki_is_uri.
Referenced by auth_keyfile, privatekey_from_file, ssh_bind_import_keys, ssh_userauth_publickey_auto, thread_pki_rsa_duplicate_key, torture_auth_cert, torture_auth_pubkey_types_ed25519, torture_auth_pubkey_types_ed25519_nonblocking, torture_ecdsa_sign_verify_uri, torture_pki_dsa_cert_verify, torture_pki_dsa_duplicate_key, torture_pki_dsa_generate_pubkey_from_privkey, torture_pki_ecdsa_cert_verify, torture_pki_ecdsa_duplicate_key, torture_pki_ecdsa_duplicate_key_uri, torture_pki_ecdsa_duplicate_then_demote, torture_pki_ecdsa_duplicate_then_demote_uri, torture_pki_ecdsa_generate_pubkey_from_privkey, torture_pki_ecdsa_import_pubkey_uri_invalid_configurations, torture_pki_ecdsa_name, torture_pki_ecdsa_publickey_from_privatekey_uri, torture_pki_ed25519_cert_verify, torture_pki_ed25519_generate_pubkey_from_privkey, torture_pki_ed25519_write_privkey, torture_pki_rsa_duplicate_key, torture_pki_rsa_generate_pubkey_from_privkey, torture_pki_rsa_import_privkey_uri, torture_pki_rsa_publickey_from_privatekey_uri, torture_pki_rsa_sha2, torture_pki_rsa_uri_invalid_configurations, torture_pki_sign_verify_uri.
int ssh_pki_export_privkey_file(const ssh_key privkey, const char *passphrase, ssh_auth_callback auth_fn, void *auth_data, const char *filename)
Export a private key to a pem file on disk, or OpenSSH format for keytype ssh-ed25519.
privkey The private key to export. passphrase The passphrase to use to encrypt the key with or NULL. An empty string means no passphrase. auth_fn An auth function you may want to use or NULL. auth_data Private data passed to the auth function. filename The path where to store the pem file. SSH_OK on success, SSH_ERROR on error.
References pki_private_key_to_pem, privkey, rc, SSH_EOF, SSH_ERROR, ssh_key_is_private, SSH_KEYTYPE_ED25519, SSH_LOG, SSH_LOG_FUNCTIONS, SSH_OK, ssh_pki_openssh_privkey_export, ssh_string_data, SSH_STRING_FREE, ssh_string_len.
Referenced by main, torture_pki_ed25519_write_privkey.
ssh_public_key ssh_pki_convert_key_to_publickey(const ssh_key key)
References key, ssh_key_dup, ssh_key_free, ssh_public_key_struct::type, ssh_key_struct::type, ssh_public_key_struct::type_c, ssh_key_struct::type_c, ZERO_STRUCTP.
Referenced by publickey_from_privatekey, ssh_message_auth_publickey.
ssh_private_key ssh_pki_convert_key_to_privatekey(const ssh_key key)
References key, privkey, ssh_key_free.
int pki_import_privkey_buffer(enum ssh_keytypes_e type, ssh_buffer buffer, ssh_key *pkey)
References buffer, key, pki_key_ecdsa_nid_from_name, pki_privkey_build_dss, pki_privkey_build_ecdsa, pki_privkey_build_ed25519, pki_privkey_build_rsa, privkey, pubkey, rc, ssh_buffer_unpack, SSH_ERROR, SSH_KEY_FLAG_PRIVATE, SSH_KEY_FLAG_PUBLIC, ssh_key_free, ssh_key_new, ssh_key_type_to_char, SSH_KEYTYPE_DSS, SSH_KEYTYPE_DSS_CERT01, SSH_KEYTYPE_ECDSA_P256, SSH_KEYTYPE_ECDSA_P256_CERT01, SSH_KEYTYPE_ECDSA_P384, SSH_KEYTYPE_ECDSA_P384_CERT01, SSH_KEYTYPE_ECDSA_P521, SSH_KEYTYPE_ECDSA_P521_CERT01, SSH_KEYTYPE_ED25519, SSH_KEYTYPE_ED25519_CERT01, SSH_KEYTYPE_RSA, SSH_KEYTYPE_RSA1, SSH_KEYTYPE_RSA_CERT01, SSH_KEYTYPE_SK_ECDSA, SSH_KEYTYPE_SK_ECDSA_CERT01, SSH_KEYTYPE_SK_ED25519, SSH_KEYTYPE_SK_ED25519_CERT01, SSH_KEYTYPE_UNKNOWN, SSH_LOG, ssh_log_hexdump, SSH_LOG_WARN, SSH_OK, ssh_string_burn, ssh_string_data, SSH_STRING_FREE, ssh_string_get_char, ssh_string_len.
Referenced by pki_openssh_import_privkey_blob.
static int pki_import_pubkey_buffer(ssh_buffer buffer, enum ssh_keytypes_e type, ssh_key *pkey)
References buffer, ED25519_KEY_LEN, key, pki_key_ecdsa_nid_from_name, pki_pubkey_build_dss, pki_pubkey_build_ecdsa, pki_pubkey_build_rsa, pubkey, rc, ssh_buffer_get_ssh_string, ssh_buffer_unpack, SSH_ERROR, SSH_KEY_FLAG_PUBLIC, ssh_key_free, ssh_key_new, ssh_key_type_to_char, SSH_KEYTYPE_DSS, SSH_KEYTYPE_DSS_CERT01, SSH_KEYTYPE_ECDSA, SSH_KEYTYPE_ECDSA_P256, SSH_KEYTYPE_ECDSA_P256_CERT01, SSH_KEYTYPE_ECDSA_P384, SSH_KEYTYPE_ECDSA_P384_CERT01, SSH_KEYTYPE_ECDSA_P521, SSH_KEYTYPE_ECDSA_P521_CERT01, SSH_KEYTYPE_ED25519, SSH_KEYTYPE_ED25519_CERT01, SSH_KEYTYPE_RSA, SSH_KEYTYPE_RSA1, SSH_KEYTYPE_RSA_CERT01, SSH_KEYTYPE_SK_ECDSA, SSH_KEYTYPE_SK_ECDSA_CERT01, SSH_KEYTYPE_SK_ED25519, SSH_KEYTYPE_SK_ED25519_CERT01, SSH_KEYTYPE_UNKNOWN, SSH_LOG, ssh_log_hexdump, SSH_LOG_WARN, SSH_OK, ssh_pki_key_ecdsa_name, ssh_string_burn, ssh_string_data, SSH_STRING_FREE, ssh_string_get_char, ssh_string_len.
Referenced by pki_import_cert_buffer, ssh_pki_import_pubkey_base64, ssh_pki_import_pubkey_blob.
static int pki_import_cert_buffer(ssh_buffer buffer, enum ssh_keytypes_e type, ssh_key *pkey)
References buffer, key, pki_import_pubkey_buffer, rc, ssh_buffer_add_buffer, ssh_buffer_add_ssh_string, SSH_BUFFER_FREE, ssh_buffer_get_ssh_string, ssh_buffer_new, SSH_ERROR, ssh_key_free, ssh_key_new, ssh_key_type_to_char, SSH_KEYTYPE_DSS, SSH_KEYTYPE_DSS_CERT01, SSH_KEYTYPE_ECDSA_P256, SSH_KEYTYPE_ECDSA_P256_CERT01, SSH_KEYTYPE_ECDSA_P384, SSH_KEYTYPE_ECDSA_P384_CERT01, SSH_KEYTYPE_ECDSA_P521, SSH_KEYTYPE_ECDSA_P521_CERT01, SSH_KEYTYPE_ED25519, SSH_KEYTYPE_ED25519_CERT01, SSH_KEYTYPE_RSA, SSH_KEYTYPE_RSA_CERT01, SSH_KEYTYPE_SK_ECDSA, SSH_KEYTYPE_SK_ECDSA_CERT01, SSH_KEYTYPE_SK_ED25519, SSH_KEYTYPE_SK_ED25519_CERT01, SSH_OK, SSH_STRING_FREE, ssh_string_from_char.
Referenced by ssh_pki_import_pubkey_base64, ssh_pki_import_pubkey_blob.
int ssh_pki_import_pubkey_base64(const char *b64_key, enum ssh_keytypes_e type, ssh_key *pkey)
Import a base64 formated public key from a memory c-string.
b64_key The base64 key to format. type The type of the key to format. pkey A pointer where the allocated key can be stored. You need to free the memory. SSH_OK on success, SSH_ERROR on error. ssh_key_free()
References base64_to_bin, buffer, is_cert_type, pki_import_cert_buffer, pki_import_pubkey_buffer, rc, SSH_BUFFER_FREE, ssh_buffer_get_ssh_string, SSH_ERROR, SSH_STRING_FREE.
Referenced by setup_rsa_key, ssh_known_hosts_parse_line, ssh_pki_import_cert_base64, ssh_pki_import_pubkey_file, thread_pki_rsa_publickey_base64, torture_pki_dsa_publickey_base64, torture_pki_ecdsa_publickey_base64, torture_pki_ed25519_pubkey_dup, torture_pki_ed25519_publickey_base64, torture_pki_ed25519_verify, torture_pki_ed25519_verify_bad, torture_pki_rsa_publickey_base64.
int ssh_pki_import_pubkey_blob(const ssh_string key_blob, ssh_key *pkey)
References buffer, is_cert_type, pki_import_cert_buffer, pki_import_pubkey_buffer, rc, ssh_buffer_add_data, SSH_BUFFER_FREE, ssh_buffer_get_ssh_string, ssh_buffer_new, SSH_ERROR, ssh_key_type_from_name, SSH_KEYTYPE_UNKNOWN, SSH_LOG, SSH_LOG_WARN, ssh_string_data, SSH_STRING_FREE, ssh_string_get_char, ssh_string_len.
Referenced by publickey_from_string, ssh_agent_get_next_ident, ssh_dh_import_next_pubkey_blob, ssh_pki_import_cert_blob, ssh_pki_openssh_import, ssh_userauth_offer_pubkey.
bool ssh_pki_is_uri(const char *cmp)
Detect if the pathname in cmp is a PKCS #11 URI.
cmp The path to the public/private key or a private/public PKCS #11 URI. true if filename is a URI starting with "pkcs11:" false otherwise.
References PKCS11_URI, rc.
Referenced by ssh_pki_import_privkey_file, ssh_pki_import_pubkey_file, ssh_userauth_publickey_auto.
char* ssh_pki_export_pub_uri_from_priv_uri(const char *priv_uri)
export a Public PKCS #11 URI from a Private PKCS #11 URI by replacing "type=private" to "type=public". TODO: Improve the parser
priv_uri Private PKCS #11 URI. pointer to the public PKCS #11 URI
References ssh_strreplace.
Referenced by ssh_userauth_publickey_auto.
int ssh_pki_import_pubkey_file(const char *filename, ssh_key *pkey)
Import a public key from the given filename.
filename The path to the public key. pkey A pointer to store the allocated public key. You need to free the memory. SSH_OK on success, SSH_EOF if the file doesn't exist or permission denied, SSH_ERROR otherwise. ssh_key_free()
References MAX_PUBKEY_SIZE, OPENSSH_HEADER_BEGIN, pki_uri_import, rc, SAFE_FREE, SSH_EOF, SSH_ERROR, SSH_KEY_PUBLIC, ssh_key_type_from_name, SSH_KEYTYPE_UNKNOWN, SSH_LOG, SSH_LOG_WARN, SSH_OK, ssh_pki_import_pubkey_base64, ssh_pki_is_uri, ssh_pki_openssh_pubkey_import.
Referenced by auth_keyfile, auth_publickey, publickey_from_file, ssh_pki_import_cert_file, ssh_userauth_publickey_auto, thread_pki_rsa_copy_cert_to_privkey, thread_pki_rsa_duplicate_key, thread_pki_rsa_import_pubkey_file, torture_pki_dsa_duplicate_key, torture_pki_dsa_import_pubkey_file, torture_pki_dsa_import_pubkey_from_openssh_privkey, torture_pki_ecdsa_duplicate_key, torture_pki_ecdsa_duplicate_key_uri, torture_pki_ecdsa_import_pubkey_file, torture_pki_ecdsa_import_pubkey_from_openssh_privkey, torture_pki_ecdsa_import_pubkey_uri, torture_pki_ecdsa_import_pubkey_uri_invalid_configurations, torture_pki_ed25519_import_pubkey_file, torture_pki_ed25519_import_pubkey_from_openssh_privkey, torture_pki_rsa_copy_cert_to_privkey, torture_pki_rsa_duplicate_key, torture_pki_rsa_import_pubkey_file, torture_pki_rsa_import_pubkey_from_openssh_privkey, torture_pki_rsa_import_pubkey_uri, torture_pki_rsa_uri_invalid_configurations, torture_pki_sign_verify_uri.
int ssh_pki_import_cert_base64(const char *b64_cert, enum ssh_keytypes_e type, ssh_key *pkey)
Import a base64 formated certificate from a memory c-string.
b64_cert The base64 cert to format. type The type of the cert to format. pkey A pointer where the allocated key can be stored. You need to free the memory. SSH_OK on success, SSH_ERROR on error. ssh_key_free()
References ssh_pki_import_pubkey_base64.
int ssh_pki_import_cert_blob(const ssh_string cert_blob, ssh_key *pkey)
References ssh_pki_import_pubkey_blob.
Referenced by ssh_agent_get_next_ident.
int ssh_pki_import_cert_file(const char *filename, ssh_key *pkey)
Import a certificate from the given filename.
filename The path to the certificate. pkey A pointer to store the allocated certificate. You need to free the memory. SSH_OK on success, SSH_EOF if the file doesn't exist or permission denied, SSH_ERROR otherwise. ssh_key_free()
References ssh_pki_import_pubkey_file.
Referenced by thread_pki_rsa_copy_cert_to_privkey, thread_pki_rsa_import_cert_file, torture_auth_cert, torture_pki_dsa_cert_verify, torture_pki_dsa_import_cert_file, torture_pki_ecdsa_cert_verify, torture_pki_ecdsa_import_cert_file, torture_pki_ed25519_cert_verify, torture_pki_ed25519_import_cert_file, torture_pki_rsa_copy_cert_to_privkey, torture_pki_rsa_import_cert_file, torture_pki_rsa_sha2, torture_pki_verify_mismatch.
int ssh_pki_generate(enum ssh_keytypes_e type, int parameter, ssh_key *pkey)
Generates a keypair.
type Type of key to create parameter Parameter to the creation of key: rsa : length of the key in bits (e.g. 1024, 2048, 4096) dsa : length of the key in bits (e.g. 1024, 2048, 3072) pkey A pointer to store the allocated private key. You need to free the memory. SSH_OK on success, SSH_ERROR on error. Generating a key pair may take some time.
References error, key, pki_key_generate_dss, pki_key_generate_ecdsa, pki_key_generate_ed25519, pki_key_generate_rsa, rc, SSH_ERROR, SSH_KEY_FLAG_PRIVATE, SSH_KEY_FLAG_PUBLIC, ssh_key_free, ssh_key_new, ssh_key_type_to_char, SSH_KEYTYPE_DSS, SSH_KEYTYPE_DSS_CERT01, SSH_KEYTYPE_ECDSA, SSH_KEYTYPE_ECDSA_P256, SSH_KEYTYPE_ECDSA_P256_CERT01, SSH_KEYTYPE_ECDSA_P384, SSH_KEYTYPE_ECDSA_P384_CERT01, SSH_KEYTYPE_ECDSA_P521, SSH_KEYTYPE_ECDSA_P521_CERT01, SSH_KEYTYPE_ED25519, SSH_KEYTYPE_ED25519_CERT01, SSH_KEYTYPE_RSA, SSH_KEYTYPE_RSA1, SSH_KEYTYPE_RSA_CERT01, SSH_KEYTYPE_SK_ECDSA, SSH_KEYTYPE_SK_ECDSA_CERT01, SSH_KEYTYPE_SK_ED25519, SSH_KEYTYPE_SK_ED25519_CERT01, SSH_KEYTYPE_UNKNOWN, SSH_OK, ssh_pki_key_ecdsa_name.
Referenced by main, thread_pki_rsa_generate_key, torture_pki_dsa_generate_key, torture_pki_ed25519_generate_key, torture_pki_fail_sign_with_incompatible_hash, torture_pki_generate_key_ecdsa, torture_pki_rsa_generate_key, torture_pki_sign_data_dsa, torture_pki_sign_data_ecdsa, torture_pki_sign_data_rsa, torture_pki_verify_mismatch.
int ssh_pki_export_privkey_to_pubkey(const ssh_key privkey, ssh_key *pkey)
Create a public key from a private key.
privkey The private key to get the public key from. pkey A pointer to store the newly allocated public key. You NEED to free the key. SSH_OK on success, SSH_ERROR on error. ssh_key_free()
References pki_key_dup, privkey, pubkey, SSH_ERROR, ssh_key_is_private, SSH_OK.
Referenced by publickey_from_privatekey, ssh_get_key_params, ssh_userauth_publickey_auto, test_sign_verify_data, thread_pki_rsa_duplicate_key, thread_pki_rsa_generate_key, thread_pki_rsa_publickey_from_privatekey, torture_ecdsa_sign_verify_uri, torture_pki_dsa_duplicate_key, torture_pki_dsa_generate_key, torture_pki_dsa_generate_pubkey_from_privkey, torture_pki_dsa_publickey_from_privatekey, torture_pki_ecdsa_duplicate_key, torture_pki_ecdsa_duplicate_key_uri, torture_pki_ecdsa_duplicate_then_demote, torture_pki_ecdsa_duplicate_then_demote_uri, torture_pki_ecdsa_generate_pubkey_from_privkey, torture_pki_ecdsa_publickey_from_privatekey, torture_pki_ecdsa_publickey_from_privatekey_uri, torture_pki_ed25519_generate_key, torture_pki_ed25519_generate_pubkey_from_privkey, torture_pki_ed25519_publickey_from_privatekey, torture_pki_fail_sign_with_incompatible_hash, torture_pki_generate_key_ecdsa, torture_pki_rsa_duplicate_key, torture_pki_rsa_generate_key, torture_pki_rsa_generate_pubkey_from_privkey, torture_pki_rsa_publickey_from_privatekey, torture_pki_rsa_publickey_from_privatekey_uri, torture_pki_rsa_sha2, torture_pki_verify_mismatch.
int ssh_pki_export_pubkey_blob(const ssh_key key, ssh_string *pblob)
References key, pki_publickey_to_blob, SSH_ERROR, SSH_OK.
Referenced by publickey_from_file, publickey_to_string, ssh_agent_sign_data, ssh_dh_get_current_server_publickey_blob, ssh_dh_get_next_server_publickey_blob, ssh_get_key_params, ssh_get_pubkey_hash, ssh_get_publickey_hash, ssh_message_auth_reply_pk_ok_simple, ssh_userauth_agent_publickey, ssh_userauth_publickey, ssh_userauth_try_publickey.
int ssh_pki_export_pubkey_base64(const ssh_key key, char **b64_key)
Convert a public key to a base64 encoded key.
key The key to hash b64_key A pointer to store the allocated base64 encoded key. You need to free the buffer. SSH_OK on success, SSH_ERROR on error. SSH_STRING_FREE_CHAR()
References bin_to_base64, key, pki_publickey_to_blob, SSH_ERROR, SSH_OK, ssh_string_data, SSH_STRING_FREE, ssh_string_len.
Referenced by ssh_dump_knownhost, ssh_pki_export_pubkey_file, ssh_session_export_known_hosts_entry, thread_pki_rsa_duplicate_key, thread_pki_rsa_publickey_base64, torture_pki_dsa_duplicate_key, torture_pki_dsa_publickey_base64, torture_pki_ecdsa_duplicate_key, torture_pki_ecdsa_duplicate_key_uri, torture_pki_ecdsa_publickey_base64, torture_pki_ed25519_publickey_base64, torture_pki_rsa_duplicate_key, torture_pki_rsa_publickey_base64.
int ssh_pki_export_pubkey_file(const ssh_key key, const char *filename)
References host, key, rc, SSH_ERROR, ssh_get_local_username, SSH_OK, ssh_pki_export_pubkey_base64, user.
Referenced by ssh_userauth_publickey_auto, torture_pki_dsa_generate_pubkey_from_privkey, torture_pki_ecdsa_generate_pubkey_from_privkey, torture_pki_ecdsa_publickey_from_privatekey_uri, torture_pki_ed25519_generate_pubkey_from_privkey, torture_pki_rsa_generate_pubkey_from_privkey.
int ssh_pki_copy_cert_to_privkey(const ssh_key certkey, ssh_key privkey)
Copy the certificate part of a public key into a private key.
certkey The certificate key. privkey The target private key to copy the certificate to. SSH_OK on success, SSH_ERROR otherwise.
References ssh_key_struct::cert, privkey, rc, ssh_buffer_add_buffer, SSH_BUFFER_FREE, ssh_buffer_new, SSH_ERROR, SSH_OK, ssh_key_struct::type.
Referenced by thread_pki_rsa_copy_cert_to_privkey, torture_auth_cert, torture_pki_rsa_copy_cert_to_privkey.
int ssh_pki_export_signature_blob(const ssh_signature sig, ssh_string *sig_blob)
References pki_signature_to_blob, rc, ssh_buffer_add_ssh_string, SSH_BUFFER_FREE, ssh_buffer_get, ssh_buffer_get_len, ssh_buffer_new, SSH_ERROR, SSH_OK, ssh_string_fill, SSH_STRING_FREE, ssh_string_from_char, ssh_string_new, ssh_signature_struct::type_c.
Referenced by ssh_pki_do_sign.
int ssh_pki_import_signature_blob(const ssh_string sig_blob, const ssh_key pubkey, ssh_signature *psig)
References pki_signature_from_blob, pubkey, rc, ssh_signature_struct::sk_counter, ssh_signature_struct::sk_flags, ssh_buffer_add_data, SSH_BUFFER_FREE, ssh_buffer_get_ssh_string, ssh_buffer_new, ssh_buffer_unpack, SSH_ERROR, ssh_key_hash_from_name, ssh_key_type_from_signature_name, SSH_KEYTYPE_SK_ECDSA, SSH_KEYTYPE_SK_ED25519, SSH_OK, ssh_string_data, SSH_STRING_FREE, ssh_string_get_char, ssh_string_len.
Referenced by SSH_PACKET_CALLBACK.
int pki_key_check_hash_compatible(ssh_key key, enum ssh_digest_e hash_type)
References key, SSH_DIGEST_AUTO, SSH_DIGEST_SHA1, SSH_DIGEST_SHA256, SSH_DIGEST_SHA384, SSH_DIGEST_SHA512, SSH_ERROR, SSH_KEYTYPE_DSS, SSH_KEYTYPE_DSS_CERT01, SSH_KEYTYPE_ECDSA, SSH_KEYTYPE_ECDSA_P256, SSH_KEYTYPE_ECDSA_P256_CERT01, SSH_KEYTYPE_ECDSA_P384, SSH_KEYTYPE_ECDSA_P384_CERT01, SSH_KEYTYPE_ECDSA_P521, SSH_KEYTYPE_ECDSA_P521_CERT01, SSH_KEYTYPE_ED25519, SSH_KEYTYPE_ED25519_CERT01, SSH_KEYTYPE_RSA, SSH_KEYTYPE_RSA1, SSH_KEYTYPE_RSA_CERT01, SSH_KEYTYPE_SK_ECDSA, SSH_KEYTYPE_SK_ECDSA_CERT01, SSH_KEYTYPE_SK_ED25519, SSH_KEYTYPE_SK_ED25519_CERT01, SSH_KEYTYPE_UNKNOWN, SSH_LOG, SSH_LOG_TRACE, SSH_LOG_WARN, SSH_OK.
Referenced by pki_do_sign, pki_sign_data, pki_verify_data_signature, ssh_pki_signature_verify.
int ssh_pki_signature_verify(ssh_session session, ssh_signature sig, const ssh_key key, const unsigned char *input, size_t input_len)
References ctx, explicit_bzero, ssh_signature_struct::hash_type, key, pki_key_check_hash_compatible, pki_verify_data_signature, rc, session, sha256_final, sha256_init, sha256_update, ssh_signature_struct::sk_counter, ssh_signature_struct::sk_flags, ssh_buffer_free, ssh_buffer_get, ssh_buffer_get_len, ssh_buffer_new, ssh_buffer_pack, SSH_ERROR, ssh_key_type_plain, SSH_KEYTYPE_SK_ECDSA, SSH_KEYTYPE_SK_ECDSA_CERT01, SSH_KEYTYPE_SK_ED25519, SSH_KEYTYPE_SK_ED25519_CERT01, SSH_LOG, SSH_LOG_FUNCTIONS, SSH_LOG_TRACE, SSH_LOG_WARN, SSH_OK, ssh_string_data, ssh_string_len, ssh_signature_struct::type, ssh_signature_struct::type_c.
Referenced by SSH_PACKET_CALLBACK, thread_pki_rsa_generate_key, torture_ecdsa_sign_verify_uri, torture_pki_dsa_cert_verify, torture_pki_dsa_generate_key, torture_pki_ecdsa_cert_verify, torture_pki_ed25519_cert_verify, torture_pki_ed25519_generate_key, torture_pki_ed25519_verify, torture_pki_ed25519_verify_bad, torture_pki_generate_key_ecdsa, torture_pki_rsa_generate_key, torture_pki_rsa_sha2, torture_pki_sign_verify_uri, torture_pki_verify_mismatch.
ssh_signature pki_do_sign(const ssh_key privkey, const unsigned char *input, size_t input_len, enum ssh_digest_e hash_type)
References pki_key_check_hash_compatible, pki_sign_data, privkey, rc, SSH_LOG, SSH_LOG_TRACE, SSH_OK.
Referenced by ssh_pki_do_sign, thread_pki_rsa_generate_key, torture_ecdsa_sign_verify_uri, torture_pki_dsa_cert_verify, torture_pki_dsa_generate_key, torture_pki_ecdsa_cert_verify, torture_pki_ed25519_cert_verify, torture_pki_ed25519_generate_key, torture_pki_ed25519_sign, torture_pki_ed25519_sign_openssh_privkey_passphrase, torture_pki_generate_key_ecdsa, torture_pki_rsa_generate_key, torture_pki_rsa_sha2, torture_pki_sign_verify_uri, torture_pki_verify_mismatch.
ssh_string ssh_pki_do_sign(ssh_session session, ssh_buffer sigbuf, const ssh_key privkey, enum ssh_digest_e hash_type)
References ssh_crypto_struct::digest_len, pki_do_sign, privkey, rc, session, ssh_crypto_struct::session_id, SSH_BUFFER_FREE, ssh_buffer_get, ssh_buffer_get_len, ssh_buffer_new, ssh_buffer_pack, ssh_buffer_set_secure, SSH_DIRECTION_BOTH, ssh_key_is_private, SSH_LOG, SSH_LOG_TRACE, SSH_OK, ssh_packet_get_current_crypto, ssh_pki_export_signature_blob, ssh_signature_free, ssh_string_fill, SSH_STRING_FREE, ssh_string_new.
Referenced by ssh_userauth_publickey.
ssh_string ssh_pki_do_sign_agent(ssh_session session, struct ssh_buffer_struct *buf, const ssh_key pubkey)
References ssh_crypto_struct::digest_len, pubkey, rc, session, ssh_crypto_struct::session_id, ssh_agent_sign_data, ssh_buffer_add_buffer, ssh_buffer_add_ssh_string, SSH_BUFFER_FREE, ssh_buffer_new, SSH_DIRECTION_BOTH, ssh_packet_get_current_crypto, ssh_string_fill, SSH_STRING_FREE, ssh_string_new.
Referenced by ssh_userauth_agent_publickey.
PKCS11_URI