libssh_session
static void ssh_client_connection_callback(ssh_session session)
References ssh_session_struct::alive, ssh_crypto_struct::client_kex, ssh_session_struct::connected, dh_handshake, ssh_session_struct::dh_handshake_state, DH_STATE_FINISHED, error, ssh_session_struct::flags, ssh_kex_struct::methods, ssh_session_struct::next_crypto, rc, ssh_crypto_struct::server_kex, ssh_session_struct::serverbanner, session, ssh_session_struct::session_state, set_status, ssh_session_struct::socket, ssh_analyze_banner, SSH_ERROR, SSH_FATAL, ssh_kex_select_methods, ssh_list_kex, SSH_LOG, SSH_LOG_PROTOCOL, SSH_OK, ssh_packet_register_socket_callback, ssh_packet_set_default_callbacks, ssh_send_banner, ssh_send_kex, SSH_SESSION_FLAG_AUTHENTICATED, SSH_SESSION_STATE_AUTHENTICATED, SSH_SESSION_STATE_AUTHENTICATING, SSH_SESSION_STATE_BANNER_RECEIVED, SSH_SESSION_STATE_CONNECTING, SSH_SESSION_STATE_DH, SSH_SESSION_STATE_ERROR, SSH_SESSION_STATE_INITIAL_KEX, SSH_SESSION_STATE_KEXINIT_RECEIVED, SSH_SESSION_STATE_NONE, SSH_SESSION_STATE_SOCKET_CONNECTED, ssh_set_client_kex, ssh_set_error, ssh_set_fd_towrite, ssh_socket_close.
Referenced by ssh_connect.
static int ssh_connect_termination(void *user)
References session, ssh_session_struct::session_state, SSH_SESSION_STATE_AUTHENTICATING, SSH_SESSION_STATE_DISCONNECTED, SSH_SESSION_STATE_ERROR, user.
Referenced by ssh_connect.
int ssh_connect(ssh_session session)
Connect to the ssh server.
session The ssh session to connect. SSH_OK on success, SSH_ERROR on error. SSH_AGAIN, if the session is in nonblocking mode, and call must be done again. ssh_new() ssh_disconnect()
References ssh_session_struct::alive, ssh_session_struct::bindaddr, callback_receive_banner, ssh_session_struct::client, ssh_session_struct::config_processed, ssh_socket_callbacks_struct::connected, ssh_socket_callbacks_struct::data, ssh_socket_callbacks_struct::exception, ssh_session_struct::fd, ssh_session_struct::host, ssh_session_struct::opts, ssh_session_struct::pending_call_state, ssh_session_struct::port, ssh_session_struct::ProxyCommand, session, ssh_session_struct::session_state, set_status, ssh_session_struct::socket, socket_callback_connected, ssh_session_struct::socket_callbacks, SSH_AGAIN, ssh_client_connection_callback, ssh_connect_termination, ssh_session_struct::ssh_connection_callback, ssh_copyright, SSH_ERROR, SSH_FATAL, ssh_handle_packets_termination, SSH_INVALID_SOCKET, ssh_is_blocking, SSH_LOG, SSH_LOG_PACKET, SSH_LOG_PROTOCOL, SSH_OK, ssh_options_apply, ssh_options_parse_config, SSH_PENDING_CALL_CONNECT, SSH_PENDING_CALL_NONE, SSH_SESSION_STATE_CONNECTING, SSH_SESSION_STATE_DISCONNECTED, SSH_SESSION_STATE_ERROR, SSH_SESSION_STATE_SOCKET_CONNECTED, ssh_set_error, ssh_socket_connect, ssh_socket_connect_proxycommand, ssh_socket_exception_callback, ssh_socket_set_callbacks, ssh_socket_set_fd, ssh_threads_get_type, SSH_TIMEOUT_NONBLOCKING, ssh_session_struct::timeout, ssh_session_struct::timeout_usec, ssh_socket_callbacks_struct::userdata.
Referenced by authenticate, client, ssh::Session::connect, connect_host, connect_ssh, do_connect, LLVMFuzzerTestOneInput, main, ssh_client, test_algorithm, torture_algorithms_zlib, torture_algorithms_zlib_openssh, torture_auth_agent, torture_auth_agent_nonblocking, torture_auth_autopubkey, torture_auth_autopubkey_nonblocking, torture_auth_cert, torture_auth_kbdint, torture_auth_kbdint_nonblocking, torture_auth_none, torture_auth_none_nonblocking, torture_auth_password, torture_auth_password_nonblocking, torture_auth_pubkey_types, torture_auth_pubkey_types_ecdsa, torture_auth_pubkey_types_ecdsa_nonblocking, torture_auth_pubkey_types_ed25519, torture_auth_pubkey_types_ed25519_nonblocking, torture_auth_pubkey_types_nonblocking, torture_client_config_autoparse, torture_client_config_suppress, torture_connect_double, torture_connect_nonblocking, torture_connect_socket, torture_hostkey_ed25519, torture_hostkey_rsa, torture_hostkey_rsa_sha256, torture_hostkey_rsa_sha512, torture_knownhosts_conflict, torture_knownhosts_export, torture_knownhosts_fail, torture_knownhosts_new_file, torture_knownhosts_no_hostkeychecking, torture_knownhosts_other, torture_knownhosts_other_auto, torture_knownhosts_port, torture_knownhosts_standard_port, torture_knownhosts_unknown, torture_knownhosts_wildcard, torture_knownhosts_write_and_verify, torture_options_set_proxycommand_notexist, torture_options_set_proxycommand_ssh, torture_options_set_proxycommand_ssh_stderr, torture_rekey_default, torture_rekey_send, torture_rekey_server_send, torture_rekey_time, torture_server_auth_kbdint, torture_server_auth_none, torture_server_auth_password, torture_server_auth_pubkey, torture_server_hostkey_mismatch, torture_server_unknown_global_request, torture_ssh_session, try_config_content.
char* ssh_get_issue_banner(ssh_session session)
Get the issue banner from the server.
This is the banner showing a disclaimer to users who log in, typically their right or the fact that they will be monitored. session The SSH session to use. A newly allocated string with the banner, NULL on error.
References ssh_session_struct::banner, session, ssh_string_to_char.
Referenced by authenticate_console, client, ssh::Session::getIssueBanner.
int ssh_get_openssh_version(ssh_session session)
Get the version of the OpenSSH server, if it is not an OpenSSH server then 0 will be returned.
You can use the SSH_VERSION_INT macro to compare version numbers. session The SSH session to use. The version number if available, 0 otherwise. intopenssh=ssh_get_openssh_version(); if(openssh==SSH_INT_VERSION(6,1,0)){ printf("Versionmatch!\m"); }
References ssh_session_struct::openssh, session.
Referenced by ssh::Session::getOpensshVersion, ssh_channel_open_forward_unix, torture_algorithms_zlib, torture_algorithms_zlib_openssh.
void ssh_disconnect(ssh_session session)
Disconnect from a session (client or server). The session can then be reused to open a new session.
session The SSH session to use.
References ssh_session_struct::alive, ssh_session_struct::auth, ssh_session_struct::channels, ssh_session_struct::clientbanner, crypto_free, crypto_new, ssh_session_struct::current_crypto, error, ssh_session_struct::fd, ssh_session_struct::in_buffer, ssh_session_struct::in_hashbuf, ssh_session_struct::next_crypto, ssh_session_struct::opts, ssh_session_struct::out_buffer, ssh_session_struct::out_hashbuf, ssh_session_struct::packet_callbacks, rc, ssh_session_struct::recv_seq, SAFE_FREE, ssh_session_struct::send_seq, ssh_session_struct::serverbanner, session, ssh_session_struct::session_state, ssh_session_struct::socket, SSH2_DISCONNECT_BY_APPLICATION, SSH2_MSG_DISCONNECT, ssh_buffer_pack, ssh_buffer_reinit, ssh_channel_do_free, SSH_INVALID_SOCKET, ssh_iterator_value, ssh_list_free, ssh_list_get_iterator, ssh_list_pop_head, ssh_list_remove, ssh_message_free, ssh_session_struct::ssh_message_list, SSH_OK, ssh_packet_send, SSH_SESSION_STATE_DISCONNECTED, ssh_set_error_oom, ssh_socket_close, ssh_socket_is_open, ssh_socket_reset, ssh_session_struct::supported_methods.
Referenced by auth_password, connect_host, connect_ssh, ssh::Session::disconnect, docycle, LLVMFuzzerTestOneInput, main, pkd_exec_hello, run_server, session_teardown, ssh_silent_disconnect, teardown, test_algorithm, torture_algorithms_zlib, torture_algorithms_zlib_openssh, torture_connect_double, torture_connect_failure, torture_hostkey_ed25519, torture_hostkey_rsa, torture_hostkey_rsa_sha256, torture_hostkey_rsa_sha512, torture_knownhosts_conflict, torture_knownhosts_other_auto, torture_knownhosts_port, torture_knownhosts_unknown, torture_rekey_default, torture_rekey_send, torture_rekey_server_send, torture_rekey_time, torture_ssh_session.
const char* ssh_copyright(void)
References LIBSSH_VERSION, SSH_STRINGIFY.
Referenced by ssh_connect.
static int ssh_select_cb(socket_t fd, int revents, void *userdata)
References POLLIN, set.
Referenced by ssh_select.
int ssh_select(ssh_channel *channels, ssh_channel *outchannels, socket_t maxfd, fd_set *readfds, struct timeval *timeout)
A wrapper for the select syscall.
This functions acts more or less like the select(2) syscall. There is no support for writing or exceptions. channels Arrays of channels pointers terminated by a NULL. It is never rewritten. outchannels Arrays of same size that "channels", there is no need to initialize it. maxfd Maximum +1 file descriptor from readfds. readfds A fd_set of file descriptors to be select'ed for reading. timeout The timeout in milliseconds. SSH_OK on success, SSH_ERROR on error, SSH_EINTR if it was interrupted. In that case, just restart it. libssh is not reentrant here. That means that if a signal is caught during the processing of this function, you cannot call libssh functions on sessions that are busy with ssh_select(). select(2)
References POLLIN, rc, session, ssh_channel_poll, SSH_ERROR, ssh_event_add_fd, ssh_event_add_session, ssh_event_dopoll, ssh_event_free, ssh_event_new, ssh_event_remove_fd, SSH_OK, ssh_select_cb, ssh_timeout_elapsed, ssh_timeout_update, ssh_timestamp_init, ZERO_STRUCT.
Referenced by select_loop, torture_channel_select.
bool ssh_dh_is_known_group(bignum modulus, bignum generator)
References bits, m, ssh_dh_generator, ssh_dh_group14, ssh_dh_group16, ssh_dh_group18, SSH_LOG, SSH_LOG_TRACE.
Referenced by SSH_PACKET_CALLBACK.
ssh_key ssh_dh_get_current_server_publickey(ssh_session session)
References ssh_session_struct::current_crypto, ssh_crypto_struct::server_pubkey, session.
Referenced by ssh_dh_get_current_server_publickey_blob, ssh_dump_knownhost, ssh_is_server_known, ssh_session_export_known_hosts_entry.
int ssh_dh_get_current_server_publickey_blob(ssh_session session, ssh_string *pubkey_blob)
References pubkey, session, ssh_dh_get_current_server_publickey, ssh_pki_export_pubkey_blob.
Referenced by check_public_key, ssh_get_pubkey.
ssh_key ssh_dh_get_next_server_publickey(ssh_session session)
References ssh_session_struct::next_crypto, ssh_crypto_struct::server_pubkey, session.
Referenced by ssh_dh_get_next_server_publickey_blob, SSH_PACKET_CALLBACK.
int ssh_dh_get_next_server_publickey_blob(ssh_session session, ssh_string *pubkey_blob)
References pubkey, session, ssh_dh_get_next_server_publickey, ssh_pki_export_pubkey_blob.
Referenced by ssh_make_sessionid.
static char* ssh_get_b64_unpadded(const unsigned char *hash, size_t len)
References bin_to_base64, k, SAFE_FREE, strndup.
Referenced by ssh_get_fingerprint_hash, torture_sha1_hash, torture_sha256_hash.
char* ssh_get_fingerprint_hash(enum ssh_publickey_hash_type type, unsigned char *hash, size_t len)
Get a hash as a human-readable hex- or base64-string.
This gets an allocated fingerprint hash. If it is a SHA sum, it will return an unpadded base64 strings. If it is a MD5 sum, it will return hex string. Either way, the output is prepended by the hash-type. Do NOT use MD5 or SHA1! Those hash functions are being deprecated. type Which sort of hash is given, use SSH_PUBLICKEY_HASH_SHA256 or better. hash The hash to be converted to fingerprint. len Length of the buffer to convert. Returns the allocated fingerprint hash or NULL on error. ssh_string_free_char()
References rc, SAFE_FREE, ssh_get_b64_unpadded, ssh_get_hexa, SSH_PUBLICKEY_HASH_MD5, SSH_PUBLICKEY_HASH_SHA1, SSH_PUBLICKEY_HASH_SHA256.
Referenced by ssh_print_hash, torture_sha256_fingerprint.
void ssh_print_hash(enum ssh_publickey_hash_type type, unsigned char *hash, size_t len)
Print a hash as a human-readable hex- or base64-string.
This prints an unpadded base64 strings for SHA sums and hex strings for MD5 sum. Either way, the output is prepended by the hash-type. type Which sort of hash is given. Use SSH_PUBLICKEY_HASH_SHA256 or better. hash The hash to be converted to fingerprint. len Length of the buffer to convert. ssh_get_publickey_hash() ssh_get_fingerprint_hash()
References SAFE_FREE, ssh_get_fingerprint_hash.
Referenced by verify_knownhost.
static struct ssh_tokens_st* ssh_get_knownhost_line(FILE **file, const char *filename, const char **found_type)
References buffer, ssh_tokenize, ssh_tokens_free, ssh_tokens_st::tokens.
Referenced by ssh_is_server_known.
static int check_public_key(ssh_session session, char **tokens)
References base64_to_bin, rc, session, ssh_buffer_free, ssh_buffer_get, ssh_buffer_get_len, ssh_dh_get_current_server_publickey_blob, SSH_FATAL, ssh_set_error, ssh_string_data, ssh_string_free, ssh_string_len, ssh_tokens_st::tokens.
Referenced by ssh_is_server_known.
static int match_hashed_host(const char *host, const char *sourcehash)
References base64_to_bin, buffer, hmac_final, hmac_init, hmac_update, host, mac, SAFE_FREE, ssh_buffer_free, ssh_buffer_get, ssh_buffer_get_len, SSH_HMAC_SHA1, SSH_LOG, SSH_LOG_PACKET.
Referenced by ssh_is_server_known.
int ssh_is_server_known(ssh_session session)
This function is deprecated.
DeprecatedPlease use ssh_session_is_known_server() ssh_session_is_known_server()
References check_public_key, ssh_session_struct::current_crypto, ssh_session_struct::global_knownhosts, host, ssh_session_struct::host, ssh_session_struct::knownhosts, match_hashed_host, match_hostname, ssh_session_struct::opts, ssh_session_struct::port, pubkey, SAFE_FREE, session, ssh_dh_get_current_server_publickey, SSH_FATAL, ssh_get_knownhost_line, ssh_hostport, ssh_key_type, ssh_key_type_to_char, SSH_LOG, SSH_LOG_PACKET, ssh_lowercase, SSH_OK, ssh_options_apply, SSH_REQUEST_DENIED, SSH_SERVER_ERROR, SSH_SERVER_FILE_NOT_FOUND, SSH_SERVER_FOUND_OTHER, SSH_SERVER_KNOWN_CHANGED, SSH_SERVER_KNOWN_OK, SSH_SERVER_NOT_KNOWN, ssh_session_update_known_hosts, ssh_set_error, ssh_set_error_oom, ssh_tokens_free, ssh_session_struct::StrictHostKeyChecking, ssh_tokens_st::tokens.
Referenced by torture_knownhosts_conflict, torture_knownhosts_fail, torture_knownhosts_other, torture_knownhosts_other_auto, torture_knownhosts_port, torture_knownhosts_standard_port, torture_knownhosts_wildcard.
char* ssh_dump_knownhost(ssh_session session)
This function is deprecated.
DeprecatedPlease use ssh_session_export_known_hosts_entry()
References buffer, ssh_session_struct::current_crypto, host, ssh_session_struct::host, ssh_session_struct::opts, ssh_session_struct::port, rc, SAFE_FREE, session, ssh_dh_get_current_server_publickey, SSH_FATAL, ssh_hostport, ssh_lowercase, ssh_pki_export_pubkey_base64, ssh_set_error, ssh_key_struct::type_c.
int ssh_write_knownhost(ssh_session session)
This function is deprecated.
DeprecatedPlease use ssh_session_update_known_hosts()
References buffer, ssh_session_struct::knownhosts, ssh_session_struct::opts, rc, SAFE_FREE, session, ssh_dirname, SSH_ERROR, SSH_FATAL, ssh_mkdirs, SSH_OK, ssh_options_apply, ssh_session_export_known_hosts_entry, ssh_set_error.
Referenced by torture_knownhosts_conflict, torture_knownhosts_other_auto, torture_knownhosts_port.
static int hash_hostname(const char *name, unsigned char *salt, unsigned int salt_size, unsigned char **hash, unsigned int *hash_size)
References hmac_final, hmac_init, hmac_update, name, SSH_ERROR, SSH_HMAC_SHA1, SSH_OK.
Referenced by match_hashed_hostname.
static int match_hashed_hostname(const char *host, const char *hashed_host)
References base64_to_bin, error, hash_hostname, host, rc, SSH_BUFFER_FREE, ssh_buffer_get, ssh_buffer_get_len, SSH_OK.
Referenced by ssh_known_hosts_parse_line.
void ssh_knownhosts_entry_free(struct ssh_knownhosts_entry *entry)
Free an allocated ssh_knownhosts_entry.
Use SSH_KNOWNHOSTS_ENTRY_FREE() to set the pointer to NULL. entry The entry to free.
References ssh_knownhosts_entry::comment, ssh_knownhosts_entry::hostname, ssh_knownhosts_entry::publickey, SAFE_FREE, ssh_key_free, ssh_knownhosts_entry::unparsed.
Referenced by ssh_known_hosts_get_algorithms, ssh_known_hosts_get_algorithms_names, ssh_known_hosts_parse_line, ssh_known_hosts_read_entries.
static int known_hosts_read_line(FILE *fp, char *buf, size_t buf_size, size_t *buf_len, size_t *lineno)
Referenced by ssh_known_hosts_read_entries.
static int ssh_known_hosts_entries_compare(struct ssh_knownhosts_entry *k1, struct ssh_knownhosts_entry *k2)
References ssh_knownhosts_entry::hostname, ssh_knownhosts_entry::publickey, ssh_key_cmp, SSH_KEY_CMP_PUBLIC.
Referenced by ssh_known_hosts_read_entries.
static int ssh_known_hosts_read_entries(const char *match, const char *filename, struct ssh_list **entries)
References error, known_hosts_read_line, ssh_iterator::next, rc, SSH_AGAIN, SSH_ERROR, ssh_iterator_value, ssh_known_hosts_entries_compare, ssh_known_hosts_parse_line, ssh_knownhosts_entry_free, ssh_list_append, ssh_list_get_iterator, ssh_list_new, SSH_LOG, SSH_LOG_WARN, SSH_OK.
Referenced by ssh_known_hosts_get_algorithms, ssh_known_hosts_get_algorithms_names, torture_knownhosts_read_file.
static char* ssh_session_get_host_port(ssh_session session)
References host, ssh_session_struct::host, ssh_session_struct::opts, ssh_session_struct::port, SAFE_FREE, session, SSH_FATAL, ssh_hostport, ssh_lowercase, ssh_set_error, ssh_set_error_oom.
Referenced by ssh_known_hosts_get_algorithms, ssh_known_hosts_get_algorithms_names, ssh_session_export_known_hosts_entry.
struct ssh_list* ssh_known_hosts_get_algorithms(ssh_session session)
References error, ssh_session_struct::global_knownhosts, ssh_session_struct::knownhosts, ssh_iterator::next, ssh_session_struct::opts, ssh_knownhosts_entry::publickey, rc, SAFE_FREE, session, ssh_iterator_value, ssh_known_hosts_read_entries, ssh_knownhosts_entry_free, ssh_list_append, ssh_list_count, ssh_list_free, ssh_list_get_iterator, ssh_list_new, ssh_list_remove, SSH_OK, ssh_options_apply, SSH_REQUEST_DENIED, ssh_session_get_host_port, ssh_set_error, ssh_key_struct::type_c.
Referenced by torture_knownhosts_duplicate, torture_knownhosts_precheck.
static const char* ssh_known_host_sigs_from_hostkey_type(enum ssh_keytypes_e type)
References SSH_KEYTYPE_DSS, SSH_KEYTYPE_ECDSA_P256, SSH_KEYTYPE_ECDSA_P384, SSH_KEYTYPE_ECDSA_P521, SSH_KEYTYPE_ED25519, SSH_KEYTYPE_RSA, SSH_KEYTYPE_UNKNOWN, SSH_LOG, SSH_LOG_WARN.
Referenced by ssh_known_hosts_get_algorithms_names.
char* ssh_known_hosts_get_algorithms_names(ssh_session session)
References ssh_session_struct::global_knownhosts, ssh_session_struct::knownhosts, ssh_session_struct::opts, ssh_knownhosts_entry::publickey, rc, SAFE_FREE, session, ssh_iterator_value, ssh_known_host_sigs_from_hostkey_type, ssh_known_hosts_read_entries, ssh_knownhosts_entry_free, ssh_list_count, ssh_list_free, ssh_list_get_iterator, ssh_list_remove, ssh_options_apply, ssh_remove_duplicates, SSH_REQUEST_DENIED, ssh_session_get_host_port, ssh_set_error, ssh_key_struct::type.
Referenced by ssh_client_select_hostkeys, torture_knownhosts_get_algorithms_names.
int ssh_known_hosts_parse_line(const char *hostname, const char *line, struct ssh_knownhosts_entry **entry)
Parse a line from a known_hosts entry into a structure.
This parses an known_hosts entry into a structure with the key in a libssh consumeable form. You can use the PKI key function to further work with it. hostname The hostname to match the line to line The line to compare and parse if we have a hostname match. entry A pointer to store the the allocated known_hosts entry structure. The user needs to free the memory using SSH_KNOWNHOSTS_ENTRY_FREE(). SSH_OK on success, SSH_ERROR otherwise.
References ssh_knownhosts_entry::comment, ssh_knownhosts_entry::hostname, match_hashed_hostname, match_hostname, ssh_knownhosts_entry::publickey, rc, SAFE_FREE, SSH_AGAIN, SSH_ERROR, ssh_hostport, ssh_key_type_from_name, ssh_key_type_to_char, SSH_KEYTYPE_UNKNOWN, ssh_knownhosts_entry_free, SSH_LOG, SSH_LOG_WARN, SSH_OK, ssh_pki_import_pubkey_base64, ssh_knownhosts_entry::unparsed.
Referenced by ssh_known_hosts_read_entries, torture_knownhosts_parse_line_default_ed25519, torture_knownhosts_parse_line_ecdsa, torture_knownhosts_parse_line_hashed_ed25519, torture_knownhosts_parse_line_pattern_ed25519, torture_knownhosts_parse_line_port_ed25519, torture_knownhosts_parse_line_port_wildcard, torture_knownhosts_parse_line_rsa, torture_knownhosts_parse_line_standard_port.
enum ssh_known_hosts_e ssh_session_has_known_hosts_entry(ssh_session session)
Check if the set hostname and port matches an entry in known_hosts.
This check if the set hostname and port has an entry in the known_hosts file. You need to set at least the hostname using ssh_options_set(). session The session with with the values set to check. A ssh_known_hosts_e return value.
Referenced by torture_knownhosts_host_exists, torture_knownhosts_host_exists_global.
int ssh_session_export_known_hosts_entry(ssh_session session, char **pentry_string)
Export the current session information to a known_hosts string.
This exports the current information of a session which is connected so a ssh server into an entry line which can be added to a known_hosts file. session The session with information to export. pentry_string A pointer to a string to store the alloocated line of the entry. The user must free it using ssh_string_free_char(). SSH_OK on succcess, SSH_ERROR otherwise.
References ssh_session_struct::current_crypto, host, ssh_session_struct::host, ssh_session_struct::opts, rc, SAFE_FREE, session, ssh_dh_get_current_server_publickey, SSH_ERROR, SSH_FATAL, SSH_OK, ssh_pki_export_pubkey_base64, ssh_session_get_host_port, ssh_set_error, ssh_set_error_invalid, ssh_key_struct::type_c.
Referenced by ssh_known_hosts_check_server_key, ssh_write_knownhost, torture_knownhosts_export.
int ssh_session_update_known_hosts(ssh_session session)
Add the current connected server to the user known_hosts file.
This adds the currently connected server to the known_hosts file by appending a new line at the end. The global known_hosts file is considered read-only so it is not touched by this function. session The session to use to write the entry. SSH_OK on success, SSH_ERROR otherwise.
Referenced by ssh_is_server_known, torture_knownhosts_conflict, torture_knownhosts_new_file, torture_knownhosts_unknown, torture_knownhosts_write_and_verify, verify_knownhost, ssh::Session::writeKnownhost.
static enum ssh_known_hosts_e ssh_known_hosts_check_server_key(const char *hosts_entry, const char *filename, ssh_key server_key, struct ssh_knownhosts_entry **pentry)
References ssh_session_struct::knownhosts, ssh_session_struct::opts, rc, SAFE_FREE, session, ssh_dirname, SSH_ERROR, SSH_FATAL, ssh_mkdirs, SSH_OK, ssh_options_apply, ssh_session_export_known_hosts_entry, ssh_set_error.
enum ssh_known_hosts_e ssh_session_get_known_hosts_entry(ssh_session session, struct ssh_knownhosts_entry **pentry)
Get the known_hosts entry for the current connected session.
session The session to validate. pentry A pointer to store the allocated known hosts entry. SSH_KNOWN_HOSTS_OK: The server is known and has not changed. SSH_KNOWN_HOSTS_CHANGED: The server key has changed. Either you are under attack or the administrator changed the key. You HAVE to warn the user about a possible attack. SSH_KNOWN_HOSTS_OTHER: The server gave use a key of a type while we had an other type recorded. It is a possible attack. SSH_KNOWN_HOSTS_UNKNOWN: The server is unknown. User should confirm the public key hash is correct. SSH_KNOWN_HOSTS_NOT_FOUND: The known host file does not exist. The host is thus unknown. File will be created if host key is accepted. SSH_KNOWN_HOSTS_ERROR: There had been an eror checking the host. ssh_knownhosts_entry_free()
enum ssh_known_hosts_e ssh_session_get_known_hosts_entry_file(ssh_session session, const char *filename, struct ssh_knownhosts_entry **pentry)
Get the known_hosts entry for the current connected session from the given known_hosts file.
session The session to validate. filename The filename to parse. pentry A pointer to store the allocated known hosts entry. SSH_KNOWN_HOSTS_OK: The server is known and has not changed. SSH_KNOWN_HOSTS_CHANGED: The server key has changed. Either you are under attack or the administrator changed the key. You HAVE to warn the user about a possible attack. SSH_KNOWN_HOSTS_OTHER: The server gave use a key of a type while we had an other type recorded. It is a possible attack. SSH_KNOWN_HOSTS_UNKNOWN: The server is unknown. User should confirm the public key hash is correct. SSH_KNOWN_HOSTS_NOT_FOUND: The known host file does not exist. The host is thus unknown. File will be created if host key is accepted. SSH_KNOWN_HOSTS_ERROR: There had been an eror checking the host. ssh_knownhosts_entry_free()
enum ssh_known_hosts_e ssh_session_is_known_server(ssh_session session)
Check if the servers public key for the connected session is known.
This checks if we already know the public key of the server we want to connect to. This allows to detect if there is a MITM attach going on of if there have been changes on the server we don't know about. session The SSH to validate. SSH_KNOWN_HOSTS_OK: The server is known and has not changed. SSH_KNOWN_HOSTS_CHANGED: The server key has changed. Either you are under attack or the administrator changed the key. You HAVE to warn the user about a possible attack. SSH_KNOWN_HOSTS_OTHER: The server gave use a key of a type while we had an other type recorded. It is a possible attack. SSH_KNOWN_HOSTS_UNKNOWN: The server is unknown. User should confirm the public key hash is correct. SSH_KNOWN_HOSTS_NOT_FOUND: The known host file does not exist. The host is thus unknown. File will be created if host key is accepted. SSH_KNOWN_HOSTS_ERROR: There had been an error checking the host.
Referenced by connect_host, do_connect, ssh::Session::isServerKnown, torture_knownhosts_conflict, torture_knownhosts_new_file, torture_knownhosts_no_hostkeychecking, torture_knownhosts_other, torture_knownhosts_unknown, torture_knownhosts_write_and_verify, torture_server_hostkey_mismatch, verify_knownhost.
int ssh_options_copy(ssh_session src, ssh_session *dest)
Duplicate the options of a session structure.
If you make several sessions with the same options this is useful. You cannot use twice the same option structure in ssh_session_connect. src The session to use to copy the options. dest A pointer to store the allocated session with duplicated options. You have to free the memory. 0 on sucess, -1 on error with errno set. ssh_session_connect()
References ssh_session_struct::bindaddr, ssh_common_struct::callbacks, ssh_session_struct::common, ssh_session_struct::compressionlevel, ssh_session_struct::config_processed, ssh_iterator::data, ssh_session_struct::fd, ssh_session_struct::flags, ssh_session_struct::global_knownhosts, ssh_session_struct::gss_client_identity, ssh_session_struct::gss_delegate_creds, ssh_session_struct::gss_server_identity, ssh_session_struct::host, ssh_session_struct::identity, ssh_session_struct::knownhosts, ssh_common_struct::log_verbosity, ssh_iterator::next, ssh_session_struct::nodelay, ssh_session_struct::options_seen, ssh_session_struct::opts, ssh_session_struct::port, ssh_session_struct::ProxyCommand, ssh_session_struct::pubkey_accepted_types, rc, SAFE_FREE, ssh_free, SSH_KEX_METHODS, ssh_list_append, ssh_list_get_iterator, ssh_list_pop_head, ssh_new, ssh_session_struct::sshdir, ssh_session_struct::StrictHostKeyChecking, ssh_session_struct::timeout, ssh_session_struct::timeout_usec, ssh_session_struct::username, ssh_session_struct::wanted_methods.
Referenced by ssh::Session::optionsCopy, torture_options_copy.
int ssh_options_set_algo(ssh_session session, enum ssh_kex_types_e algo, const char *list)
References ssh_session_struct::opts, SAFE_FREE, session, ssh_keep_fips_algos, ssh_keep_known_algos, ssh_kex_get_description, SSH_REQUEST_DENIED, ssh_set_error, ssh_session_struct::wanted_methods.
Referenced by server_set_kex, ssh_options_set.
int ssh_options_set(ssh_session session, enum ssh_options_e type, const void *value)
This function can set all possible ssh options.
session An allocated SSH session structure. type The option type to set. This could be one of the following: SSH_OPTIONS_HOST: The hostname or ip address to connect to (const char *). SSH_OPTIONS_PORT: The port to connect to (unsigned int *). SSH_OPTIONS_PORT_STR: The port to connect to (const char *). SSH_OPTIONS_FD: The file descriptor to use (socket_t). If you wish to open the socket yourself for a reason or another, set the file descriptor. Don't forget to set the hostname as the hostname is used as a key in the known_host mechanism. SSH_OPTIONS_BINDADDR: The address to bind the client to (const char *). SSH_OPTIONS_USER: The username for authentication (const char *). If the value is NULL, the username is set to the default username. SSH_OPTIONS_SSH_DIR: Set the ssh directory (const char *,format string). If the value is NULL, the directory is set to the default ssh directory. The ssh directory is used for files like known_hosts and identity (private and public key). It may include "%s" which will be replaced by the user home directory. SSH_OPTIONS_KNOWNHOSTS: Set the known hosts file name (const char *,format string). If the value is NULL, the directory is set to the default known hosts file, normally ~/.ssh/known_hosts. The known hosts file is used to certify remote hosts are genuine. It may include "%d" which will be replaced by the user home directory. SSH_OPTIONS_GLOBAL_KNOWNHOSTS: Set the global known hosts file name (const char *,format string). If the value is NULL, the directory is set to the default global known hosts file, normally /etc/ssh/ssh_known_hosts. The known hosts file is used to certify remote hosts are genuine. SSH_OPTIONS_ADD_IDENTITY (or SSH_OPTIONS_IDENTITY): Add a new identity file (const char *, format string) to the identity list. By default identity, id_dsa and id_rsa are checked. The identity used to authenticate with public key will be prepended to the list. It may include "%s" which will be replaced by the user home directory. SSH_OPTIONS_TIMEOUT: Set a timeout for the connection in seconds (long). SSH_OPTIONS_TIMEOUT_USEC: Set a timeout for the connection in micro seconds (long). SSH_OPTIONS_SSH1: Deprecated SSH_OPTIONS_SSH2: Unused SSH_OPTIONS_LOG_VERBOSITY: Set the session logging verbosity (int). The verbosity of the messages. Every log smaller or equal to verbosity will be shown. SSH_LOG_NOLOG: No logging SSH_LOG_WARNING: Only warnings SSH_LOG_PROTOCOL: High level protocol information SSH_LOG_PACKET: Lower level protocol infomations, packet level SSH_LOG_FUNCTIONS: Every function path SSH_OPTIONS_LOG_VERBOSITY_STR: Set the session logging verbosity via a string that will be converted to a numerical value (e.g. "3") and interpreted according to the values of SSH_OPTIONS_LOG_VERBOSITY above (const char *). SSH_OPTIONS_CIPHERS_C_S: Set the symmetric cipher client to server (const char *, comma-separated list). SSH_OPTIONS_CIPHERS_S_C: Set the symmetric cipher server to client (const char *, comma-separated list). SSH_OPTIONS_KEY_EXCHANGE: Set the key exchange method to be used (const char *, comma-separated list). ex: "ecdh-sha2-nistp256,diffie-hellman-group14-sha1,diffie-hellman-group1-sha1" SSH_OPTIONS_HMAC_C_S: Set the Message Authentication Code algorithm client to server (const char *, comma-separated list). SSH_OPTIONS_HMAC_S_C: Set the Message Authentication Code algorithm server to client (const char *, comma-separated list). SSH_OPTIONS_HOSTKEYS: Set the preferred server host key types (const char *, comma-separated list). ex: "ssh-rsa,ssh-dss,ecdh-sha2-nistp256" SSH_OPTIONS_PUBLICKEY_ACCEPTED_TYPES: Set the preferred public key algorithms to be used for authentication (const char *, comma-separated list). ex: "ssh-rsa,rsa-sha2-256,ssh-dss,ecdh-sha2-nistp256" SSH_OPTIONS_COMPRESSION_C_S: Set the compression to use for client to server communication (const char *, "yes", "no" or a specific algorithm name if needed ("zlib","zlib@openssh.com","none"). SSH_OPTIONS_COMPRESSION_S_C: Set the compression to use for server to client communication (const char *, "yes", "no" or a specific algorithm name if needed ("zlib","zlib@openssh.com","none"). SSH_OPTIONS_COMPRESSION: Set the compression to use for both directions communication (const char *, "yes", "no" or a specific algorithm name if needed ("zlib","zlib@openssh.com","none"). SSH_OPTIONS_COMPRESSION_LEVEL: Set the compression level to use for zlib functions. (int, value from 1 to 9, 9 being the most efficient but slower). SSH_OPTIONS_STRICTHOSTKEYCHECK: Set the parameter StrictHostKeyChecking to avoid asking about a fingerprint (int, 0 = false). SSH_OPTIONS_PROXYCOMMAND: Set the command to be executed in order to connect to server (const char *). SSH_OPTIONS_GSSAPI_SERVER_IDENTITY Set it to specify the GSSAPI server identity that libssh should expect when connecting to the server (const char *). SSH_OPTIONS_GSSAPI_CLIENT_IDENTITY Set it to specify the GSSAPI client identity that libssh should expect when connecting to the server (const char *). SSH_OPTIONS_GSSAPI_DELEGATE_CREDENTIALS Set it to specify that GSSAPI should delegate credentials to the server (int, 0 = false). SSH_OPTIONS_PASSWORD_AUTH Set it if password authentication should be used in ssh_userauth_auto_pubkey(). (int, 0=false). Currently without effect (ssh_userauth_auto_pubkey doesn't use password authentication). SSH_OPTIONS_PUBKEY_AUTH Set it if pubkey authentication should be used in ssh_userauth_auto_pubkey(). (int, 0=false). SSH_OPTIONS_KBDINT_AUTH Set it if keyboard-interactive authentication should be used in ssh_userauth_auto_pubkey(). (int, 0=false). Currently without effect (ssh_userauth_auto_pubkey doesn't use keyboard-interactive authentication). SSH_OPTIONS_GSSAPI_AUTH Set it if gssapi authentication should be used in ssh_userauth_auto_pubkey(). (int, 0=false). Currently without effect (ssh_userauth_auto_pubkey doesn't use gssapi authentication). SSH_OPTIONS_NODELAY Set it to disable Nagle's Algorithm (TCP_NODELAY) on the session socket. (int, 0=false) SSH_OPTIONS_PROCESS_CONFIG Set it to false to disable automatic processing of per-user and system-wide OpenSSH configuration files. LibSSH automatically uses these configuration files unless you provide it with this option or with different file (bool). SSH_OPTIONS_REKEY_DATA Set the data limit that can be transferred with a single key in bytes. RFC 4253 Section 9 recommends 1GB of data, while RFC 4344 provides more specific restrictions, that are applied automatically. When specified, the lower value will be used. (uint64_t, 0=default) SSH_OPTIONS_REKEY_TIME Set the time limit for a session before intializing a rekey in seconds. RFC 4253 Section 9 recommends one hour. (uint32_t, 0=off) value The value to set. This is a generic pointer and the datatype which is used should be set according to the type set. 0 on success, < 0 on error.
References ssh_session_struct::bindaddr, ssh_session_struct::common, ssh_session_struct::compressionlevel, ssh_session_struct::config_processed, ssh_session_struct::fd, ssh_session_struct::flags, ssh_session_struct::global_knownhosts, ssh_session_struct::gss_client_identity, ssh_session_struct::gss_delegate_creds, ssh_session_struct::gss_server_identity, ssh_session_struct::host, ssh_session_struct::identity, ssh_session_struct::knownhosts, ssh_common_struct::log_verbosity, ssh_session_struct::nodelay, ssh_session_struct::opts, ssh_session_struct::port, ssh_session_struct::ProxyCommand, ssh_session_struct::pubkey_accepted_types, rc, ssh_session_struct::rekey_data, ssh_session_struct::rekey_time, SAFE_FREE, session, SSH_COMP_C_S, SSH_COMP_S_C, SSH_CRYPT_C_S, SSH_CRYPT_S_C, ssh_get_local_username, SSH_HOSTKEYS, SSH_INVALID_SOCKET, ssh_keep_fips_algos, ssh_keep_known_algos, SSH_KEX, ssh_list_prepend, SSH_MAC_C_S, SSH_MAC_S_C, SSH_OPT_FLAG_GSSAPI_AUTH, SSH_OPT_FLAG_KBDINT_AUTH, SSH_OPT_FLAG_PASSWORD_AUTH, SSH_OPT_FLAG_PUBKEY_AUTH, SSH_OPTIONS_ADD_IDENTITY, SSH_OPTIONS_BINDADDR, SSH_OPTIONS_CIPHERS_C_S, SSH_OPTIONS_CIPHERS_S_C, SSH_OPTIONS_COMPRESSION, SSH_OPTIONS_COMPRESSION_C_S, SSH_OPTIONS_COMPRESSION_LEVEL, SSH_OPTIONS_COMPRESSION_S_C, SSH_OPTIONS_FD, SSH_OPTIONS_GLOBAL_KNOWNHOSTS, SSH_OPTIONS_GSSAPI_AUTH, SSH_OPTIONS_GSSAPI_CLIENT_IDENTITY, SSH_OPTIONS_GSSAPI_DELEGATE_CREDENTIALS, SSH_OPTIONS_GSSAPI_SERVER_IDENTITY, SSH_OPTIONS_HMAC_C_S, SSH_OPTIONS_HMAC_S_C, SSH_OPTIONS_HOST, SSH_OPTIONS_HOSTKEYS, SSH_OPTIONS_IDENTITY, SSH_OPTIONS_KBDINT_AUTH, SSH_OPTIONS_KEY_EXCHANGE, SSH_OPTIONS_KNOWNHOSTS, SSH_OPTIONS_LOG_VERBOSITY, SSH_OPTIONS_LOG_VERBOSITY_STR, SSH_OPTIONS_NODELAY, SSH_OPTIONS_PASSWORD_AUTH, SSH_OPTIONS_PORT, SSH_OPTIONS_PORT_STR, SSH_OPTIONS_PROCESS_CONFIG, SSH_OPTIONS_PROXYCOMMAND, SSH_OPTIONS_PUBKEY_AUTH, SSH_OPTIONS_PUBLICKEY_ACCEPTED_TYPES, SSH_OPTIONS_REKEY_DATA, SSH_OPTIONS_REKEY_TIME, ssh_options_set, ssh_options_set_algo, SSH_OPTIONS_SSH1, SSH_OPTIONS_SSH2, SSH_OPTIONS_SSH_DIR, SSH_OPTIONS_STRICTHOSTKEYCHECK, SSH_OPTIONS_TIMEOUT, SSH_OPTIONS_TIMEOUT_USEC, SSH_OPTIONS_USER, ssh_path_expand_tilde, SSH_REQUEST_DENIED, ssh_set_error, ssh_set_error_invalid, ssh_set_error_oom, ssh_set_log_level, ssh_session_struct::sshdir, ssh_session_struct::StrictHostKeyChecking, ssh_session_struct::timeout, ssh_session_struct::timeout_usec, ssh_session_struct::username.
Referenced by authenticate, client, connect_host, connect_ssh, LLVMFuzzerTestOneInput, main, pkd_exec_hello, session_setup, ssh::Session::setOption, setup, setup_config_files, ssh_client, ssh_config_parse_line, ssh_config_parse_proxy_jump, ssh_options_apply, ssh_options_getopt, ssh_options_parse_config, ssh_options_set, test_algorithm, torture_algorithms_zlib, torture_algorithms_zlib_openssh, torture_auth_agent, torture_auth_agent_cert, torture_auth_agent_cert_nonblocking, torture_auth_agent_nonblocking, torture_auth_autopubkey, torture_auth_autopubkey_nonblocking, torture_auth_cert, torture_auth_kbdint, torture_auth_kbdint_nonblocking, torture_auth_none, torture_auth_none_nonblocking, torture_auth_password, torture_auth_password_nonblocking, torture_auth_pubkey_types, torture_auth_pubkey_types_ecdsa, torture_auth_pubkey_types_ecdsa_nonblocking, torture_auth_pubkey_types_ed25519, torture_auth_pubkey_types_ed25519_nonblocking, torture_auth_pubkey_types_nonblocking, torture_client_config_suppress, torture_config_auth_methods, torture_config_match, torture_config_proxyjump, torture_config_rekey, torture_connect_double, torture_connect_nonblocking, torture_connect_socket, torture_hostkey_ed25519, torture_hostkey_rsa, torture_hostkey_rsa_sha256, torture_hostkey_rsa_sha512, torture_knownhosts_algorithms, torture_knownhosts_algorithms_global, torture_knownhosts_algorithms_negative, torture_knownhosts_algorithms_wanted, torture_knownhosts_conflict, torture_knownhosts_duplicate, torture_knownhosts_fail, torture_knownhosts_get_algorithms_names, torture_knownhosts_host_exists, torture_knownhosts_host_exists_global, torture_knownhosts_new_file, torture_knownhosts_no_hostkeychecking, torture_knownhosts_other, torture_knownhosts_other_auto, torture_knownhosts_port, torture_knownhosts_precheck, torture_knownhosts_standard_port, torture_knownhosts_unknown, torture_knownhosts_wildcard, torture_options_config_host, torture_options_config_match, torture_options_config_match_multi, torture_options_copy, torture_options_get_global_knownhosts, torture_options_get_host, torture_options_get_identity, torture_options_get_knownhosts, torture_options_get_port, torture_options_get_user, torture_options_proxycommand, torture_options_set_ciphers, torture_options_set_fd, torture_options_set_global_knownhosts, torture_options_set_host, torture_options_set_hostkey, torture_options_set_identity, torture_options_set_key_exchange, torture_options_set_knownhosts, torture_options_set_macs, torture_options_set_port, torture_options_set_proxycommand_notexist, torture_options_set_proxycommand_ssh, torture_options_set_proxycommand_ssh_stderr, torture_options_set_pubkey_accepted_types, torture_options_set_user, torture_packet, torture_pki_verify_mismatch, torture_rekey_default, torture_rekey_send, torture_rekey_time, torture_run_tests, torture_server_auth_kbdint, torture_server_auth_none, torture_server_auth_password, torture_server_auth_pubkey, torture_server_hostkey_mismatch, torture_server_unknown_global_request, torture_ssh_forward, torture_ssh_session, try_config_content.
int ssh_options_get_port(ssh_session session, unsigned int *port_target)
This function can get ssh the ssh port. It must only be used on a valid ssh session. This function is useful when the session options have been automatically inferred from the environment or configuration files and one.
session An allocated SSH session structure. port_target An unsigned integer into which the port will be set from the ssh session. 0 on success, < 0 on error.
References ssh_session_struct::opts, ssh_session_struct::port, session.
Referenced by torture_options_get_port.
int ssh_options_get(ssh_session session, enum ssh_options_e type, char **value)
This function can get ssh options, it does not support all options provided for ssh options set, but mostly those which a user-space program may care about having trusted the ssh driver to infer these values from underlaying configuration files. It operates only on those SSH_OPTIONS_* which return char*. If you wish to receive the port then please use ssh_options_get_port() which returns an unsigned int.
session An allocated SSH session structure. type The option type to get. This could be one of the following: SSH_OPTIONS_HOST: The hostname or ip address to connect to (const char *). SSH_OPTIONS_USER: The username for authentication (const char *). when not explicitly set this will be inferred from the ~/.ssh/config file. SSH_OPTIONS_IDENTITY: Get the first identity file name (const char *). By default identity, id_dsa and id_rsa are checked. SSH_OPTIONS_PROXYCOMMAND: Get the proxycommand necessary to log into the remote host. When not explicitly set, it will be read from the ~/.ssh/config file. SSH_OPTIONS_GLOBAL_KNOWNHOSTS: Get the path to the global known_hosts file being used. SSH_OPTIONS_KNOWNHOSTS: Get the path to the known_hosts file being used. value The value to get into. As a char**, space will be allocated by the function for the value, it is your responsibility to free the memory using ssh_string_free_char(). SSH_OK on success, SSH_ERROR on error.
References ssh_session_struct::global_knownhosts, ssh_session_struct::host, ssh_session_struct::identity, ssh_session_struct::knownhosts, ssh_session_struct::opts, ssh_session_struct::ProxyCommand, session, SSH_ERROR, ssh_iterator_value, ssh_list_get_iterator, SSH_OK, SSH_OPTIONS_GLOBAL_KNOWNHOSTS, SSH_OPTIONS_HOST, SSH_OPTIONS_IDENTITY, SSH_OPTIONS_KNOWNHOSTS, SSH_OPTIONS_PROXYCOMMAND, SSH_OPTIONS_USER, SSH_REQUEST_DENIED, ssh_set_error, ssh_set_error_invalid, ssh_set_error_oom, ssh_session_struct::username.
Referenced by torture_config_from_file, torture_config_glob, torture_options_get_global_knownhosts, torture_options_get_host, torture_options_get_identity, torture_options_get_knownhosts, torture_options_get_user.
int ssh_options_getopt(ssh_session session, int *argcptr, char **argv)
Parse command line arguments.
This is a helper for your application to generate the appropriate options from the command line arguments. The argv array and argc value are changed so that the parsed arguments wont appear anymore in them. The single arguments (without switches) are not parsed. thus, myssh -l user localhost The command wont set the hostname value of options to localhost. session The session to configure. argcptr The pointer to the argument count. argv The arguments list pointer. 0 on success, < 0 on error. ssh_session_new()
References port, SAFE_FREE, session, SSH_ERROR, SSH_FATAL, SSH_OK, SSH_OPTIONS_CIPHERS_C_S, SSH_OPTIONS_CIPHERS_S_C, SSH_OPTIONS_COMPRESSION, SSH_OPTIONS_IDENTITY, SSH_OPTIONS_PORT_STR, ssh_options_set, SSH_OPTIONS_USER, ssh_set_error, ssh_set_error_oom, ssh_set_log_level, user.
Referenced by main, set_opts.
int ssh_options_parse_config(ssh_session session, const char *filename)
Parse the ssh config file.
This should be the last call of all options, it may overwrite options which are already set. It requires that the host name is already set with ssh_options_set_host(). session SSH session handle filename The options file to use, if NULL the default ~/.ssh/config will be used. 0 on success, < 0 on error. ssh_options_set_host()
References ssh_session_struct::config_processed, ssh_session_struct::host, ssh_session_struct::opts, session, ssh_config_parse_file, ssh_options_set, SSH_OPTIONS_SSH_DIR, ssh_path_expand_escape, ssh_set_error_invalid, ssh_set_error_oom, ssh_session_struct::sshdir.
Referenced by client, connect_host, ssh::Session::optionsParseConfig, ssh_connect, torture_client_config_emulate, torture_client_config_system, torture_options_config_host, torture_options_config_match, torture_options_config_match_multi, torture_options_copy.
int ssh_options_apply(ssh_session session)
References ssh_iterator::data, ssh_session_struct::global_knownhosts, ssh_session_struct::identity, if, ssh_session_struct::knownhosts, ssh_iterator::next, ssh_session_struct::opts, ssh_session_struct::ProxyCommand, rc, session, ssh_list_get_iterator, ssh_options_set, SSH_OPTIONS_SSH_DIR, SSH_OPTIONS_USER, ssh_path_expand_escape, ssh_session_struct::sshdir, ssh_session_struct::username.
Referenced by ssh_connect, ssh_is_server_known, ssh_known_hosts_check_server_key, ssh_known_hosts_get_algorithms, ssh_known_hosts_get_algorithms_names, ssh_try_publickey_from_file, ssh_write_knownhost, torture_options_set_knownhosts.
ssh_session ssh_new(void)
Create a new ssh session.
A new ssh_session pointer, NULL on error.
References ssh_session_struct::agent, ssh_session_struct::alive, ssh_session_struct::auth, ssh_session_struct::compressionlevel, crypto_new, ssh_session_struct::dh_handshake_state, DH_STATE_INIT, ssh_session_struct::fd, FIRST_CHANNEL, ssh_session_struct::flags, ssh_session_struct::global_req_state, ssh_session_struct::identity, ssh_session_struct::in_buffer, ssh_session_struct::maxchannel, ssh_session_struct::next_crypto, ssh_session_struct::nodelay, ssh_session_struct::opts, ssh_session_struct::out_buffer, ssh_session_struct::out_queue, ssh_session_struct::packet_state, PACKET_STATE_INIT, ssh_session_struct::pending_call_state, ssh_session_struct::port, rc, ssh_session_struct::service_state, session, ssh_session_struct::session_state, ssh_session_struct::socket, ssh_agent_new, SSH_AUTH_SERVICE_NONE, SSH_AUTH_STATE_NONE, ssh_buffer_new, SSH_CHANNEL_REQ_STATE_NONE, SSH_ERROR, ssh_free, ssh_list_append, ssh_list_new, SSH_OPT_FLAG_GSSAPI_AUTH, SSH_OPT_FLAG_KBDINT_AUTH, SSH_OPT_FLAG_PASSWORD_AUTH, SSH_OPT_FLAG_PUBKEY_AUTH, SSH_PENDING_CALL_NONE, SSH_SESSION_STATE_NONE, ssh_set_blocking, ssh_socket_new, ssh_session_struct::state, ssh_session_struct::StrictHostKeyChecking, ssh_session_struct::supported_methods.
Referenced by check_message_in_all_states, connect_host, connect_ssh, LLVMFuzzerTestOneInput, main, pkd_exec_hello, run_server, ssh::Session::Session, session_setup, setup, setup_both_keys_passphrase, setup_config_files, setup_rsa_key, ssh_client, ssh_options_copy, ssh_server, test_ssh_channel_request_x11, thread_pki_rsa_generate_key, torture_ecdsa_sign_verify_uri, torture_knownhosts_algorithms, torture_knownhosts_algorithms_global, torture_knownhosts_algorithms_negative, torture_knownhosts_algorithms_wanted, torture_knownhosts_conflict, torture_knownhosts_get_algorithms_names, torture_knownhosts_host_exists, torture_knownhosts_host_exists_global, torture_knownhosts_other_auto, torture_knownhosts_port, torture_knownhosts_unknown, torture_packet, torture_packet_filter_check_unfiltered, torture_pki_dsa_cert_verify, torture_pki_dsa_generate_key, torture_pki_ecdsa_cert_verify, torture_pki_ed25519_cert_verify, torture_pki_ed25519_generate_key, torture_pki_ed25519_verify, torture_pki_ed25519_verify_bad, torture_pki_generate_key_ecdsa, torture_pki_rsa_generate_key, torture_pki_rsa_sha2, torture_pki_sign_verify_uri, torture_pki_verify_mismatch, torture_run_tests, torture_ssh_session.
void ssh_free(ssh_session session)
Deallocate a SSH session handle.
session The SSH session to free. ssh_disconnect() ssh_new()
References ssh_session_struct::agent, ssh_session_struct::agent_state, ssh_session_struct::auth, ssh_session_struct::auto_state, ssh_session_struct::banner, ssh_session_struct::bindaddr, ssh_session_struct::channels, ssh_session_struct::clientbanner, crypto_free, ssh_session_struct::current_crypto, ssh_session_struct::custombanner, ssh_session_struct::default_poll_ctx, ssh_session_struct::dsa_key, ssh_session_struct::ecdsa_key, ssh_session_struct::ed25519_key, explicit_bzero, ssh_session_struct::global_knownhosts, ssh_session_struct::gss_client_identity, ssh_session_struct::gss_server_identity, ssh_session_struct::host, ssh_session_struct::identity, ssh_session_struct::in_buffer, ssh_session_struct::in_hashbuf, ssh_session_struct::kbdint, ssh_session_struct::knownhosts, ssh_session_struct::next_crypto, ssh_session_struct::opts, ssh_session_struct::out_buffer, ssh_session_struct::out_hashbuf, ssh_session_struct::out_queue, ssh_session_struct::packet_callbacks, ssh_session_struct::ProxyCommand, ssh_session_struct::pubkey_accepted_types, ssh_session_struct::rsa_key, SAFE_FREE, ssh_session_struct::serverbanner, session, ssh_session_struct::socket, ssh_session_struct::srv, ssh_agent_free, ssh_agent_state_free, SSH_BUFFER_FREE, ssh_channel_do_free, ssh_iterator_value, ssh_kbdint_free, SSH_KEX_METHODS, ssh_key_free, ssh_list_free, ssh_list_get_iterator, ssh_list_pop_head, ssh_list_remove, ssh_message_free, ssh_session_struct::ssh_message_list, ssh_poll_ctx_free, ssh_socket_free, ssh_session_struct::sshdir, ssh_session_struct::username, ssh_session_struct::wanted_methods.
Referenced by check_message_in_all_states, client_thread, connect_host, connect_ssh, LLVMFuzzerTestOneInput, main, pkd_exec_hello, run_server, session_teardown, setup_both_keys, ssh_new, ssh_options_copy, teardown, test_ssh_channel_request_x11, thread_pki_rsa_generate_key, torture_knownhosts_algorithms, torture_knownhosts_algorithms_global, torture_knownhosts_algorithms_negative, torture_knownhosts_algorithms_wanted, torture_knownhosts_conflict, torture_knownhosts_get_algorithms_names, torture_knownhosts_host_exists, torture_knownhosts_host_exists_global, torture_knownhosts_other_auto, torture_knownhosts_port, torture_knownhosts_unknown, torture_options_copy, torture_packet, torture_packet_filter_check_unfiltered, torture_pki_dsa_cert_verify, torture_pki_dsa_generate_key, torture_pki_ecdsa_cert_verify, torture_pki_ed25519_cert_verify, torture_pki_ed25519_generate_key, torture_pki_ed25519_verify, torture_pki_ed25519_verify_bad, torture_pki_generate_key_ecdsa, torture_pki_rsa_generate_key, torture_pki_rsa_sha2, torture_pki_sign_verify_uri, torture_pki_verify_mismatch, torture_ssh_analyze_banner, torture_ssh_session, ssh::Session::~Session.
const char* ssh_get_clientbanner(ssh_session session)
get the client banner
session The SSH session Returns the client banner string or NULL.
References ssh_session_struct::clientbanner, session.
const char* ssh_get_serverbanner(ssh_session session)
get the server banner
session The SSH session Returns the server banner string or NULL.
References ssh_session_struct::serverbanner, session.
Referenced by main.
const char* ssh_get_kex_algo(ssh_session session)
get the name of the current key exchange algorithm.
session The SSH session Returns the key exchange algorithm string or NULL.
References ssh_session_struct::current_crypto, ssh_crypto_struct::kex_type, session, SSH_KEX_CURVE25519_SHA256, SSH_KEX_CURVE25519_SHA256_LIBSSH_ORG, SSH_KEX_DH_GROUP14_SHA1, SSH_KEX_DH_GROUP16_SHA512, SSH_KEX_DH_GROUP18_SHA512, SSH_KEX_DH_GROUP1_SHA1, SSH_KEX_ECDH_SHA2_NISTP256, SSH_KEX_ECDH_SHA2_NISTP384, SSH_KEX_ECDH_SHA2_NISTP521.
const char* ssh_get_cipher_in(ssh_session session)
get the name of the input cipher for the given session.
session The SSH session. Returns cipher name or NULL.
References ssh_session_struct::current_crypto, ssh_crypto_struct::in_cipher, ssh_cipher_struct::name, session.
const char* ssh_get_cipher_out(ssh_session session)
get the name of the output cipher for the given session.
session The SSH session. Returns cipher name or NULL.
References ssh_session_struct::current_crypto, ssh_cipher_struct::name, ssh_crypto_struct::out_cipher, session.
const char* ssh_get_hmac_in(ssh_session session)
get the name of the input HMAC algorithm for the given session.
session The SSH session. Returns HMAC algorithm name or NULL if unknown.
References ssh_session_struct::current_crypto, ssh_crypto_struct::in_hmac_etm, session, ssh_hmac_type_to_string.
const char* ssh_get_hmac_out(ssh_session session)
get the name of the output HMAC algorithm for the given session.
session The SSH session. Returns HMAC algorithm name or NULL if unknown.
References ssh_session_struct::current_crypto, ssh_crypto_struct::out_hmac, ssh_crypto_struct::out_hmac_etm, session, ssh_hmac_type_to_string.
void ssh_silent_disconnect(ssh_session session)
Disconnect impolitely from a remote host by closing the socket.
Suitable if you forked and want to destroy this session. session The SSH session to disconnect.
References ssh_session_struct::alive, session, ssh_session_struct::socket, ssh_disconnect, ssh_socket_close.
Referenced by ssh::Session::silentDisconnect.
void ssh_set_blocking(ssh_session session, int blocking)
Set the session in blocking/nonblocking mode.
session The ssh session to change. blocking Zero for nonblocking mode.
References ssh_session_struct::flags, session, SSH_SESSION_FLAG_BLOCKING.
Referenced by my_fd_data_function, ssh_channel_read_nonblocking, ssh_channel_set_blocking, ssh_new, torture_auth_agent_nonblocking, torture_auth_autopubkey_nonblocking, torture_auth_kbdint_nonblocking, torture_auth_none_nonblocking, torture_auth_password_nonblocking, torture_auth_pubkey_types_ecdsa_nonblocking, torture_auth_pubkey_types_ed25519_nonblocking, torture_auth_pubkey_types_nonblocking, torture_connect_nonblocking.
int ssh_is_blocking(ssh_session session)
Return the blocking mode of libssh.
session The SSH session 0 if the session is nonblocking, 1 if the functions may block.
References ssh_session_struct::flags, session, SSH_SESSION_FLAG_BLOCKING.
Referenced by my_fd_data_function, ssh_channel_read_nonblocking, ssh_connect, ssh_handle_packets, ssh_handle_packets_termination.
static int ssh_flush_termination(void *c)
References session, ssh_session_struct::session_state, ssh_session_struct::socket, SSH_SESSION_STATE_ERROR, ssh_socket_buffered_write_bytes.
Referenced by ssh_blocking_flush.
int ssh_blocking_flush(ssh_session session, int timeout)
Blocking flush of the outgoing buffer.
session The SSH session timeout Set an upper limit on the time for which this function will block, in milliseconds. Specifying -1 means an infinite timeout. This parameter is passed to the poll() function. SSH_OK on success, SSH_AGAIN if timeout occurred, SSH_ERROR otherwise.
References rc, session, SSH_AGAIN, SSH_ERROR, ssh_flush_termination, ssh_handle_packets_termination.
Referenced by ssh_channel_flush.
int ssh_is_connected(ssh_session session)
Check if we are connected.
session The session to check if it is connected. 1 if we are connected, 0 if not.
References ssh_session_struct::alive, session.
Referenced by pkd_exec_hello, torture_ssh_session.
socket_t ssh_get_fd(ssh_session session)
Get the fd of a connection.
In case you'd need the file descriptor of the connection to the server/client. session The ssh session to use. The file descriptor of the connection, or -1 if it is not connected
References session, ssh_session_struct::socket, ssh_socket_get_fd.
Referenced by ssh::Session::getSocket, select_loop, torture_channel_read_error, torture_options_set_proxycommand_ssh, torture_options_set_proxycommand_ssh_stderr.
void ssh_set_fd_toread(ssh_session session)
Tell the session it has data to read on the file descriptor without blocking.
session The ssh session to use.
References session, ssh_session_struct::socket, ssh_socket_set_read_wontblock.
void ssh_set_fd_towrite(ssh_session session)
Tell the session it may write to the file descriptor without blocking.
session The ssh session to use.
References session, ssh_session_struct::socket, ssh_socket_set_write_wontblock.
Referenced by ssh_client_connection_callback.
void ssh_set_fd_except(ssh_session session)
Tell the session it has an exception to catch on the file descriptor.
session The ssh session to use.
References session, ssh_session_struct::socket, ssh_socket_set_except.
int ssh_handle_packets(ssh_session session, int timeout)
References ctx, ssh_session_struct::opts, POLLIN, rc, session, ssh_session_struct::session_state, ssh_session_struct::socket, SSH_ERROR, ssh_is_blocking, ssh_make_milliseconds, ssh_poll_add_events, ssh_poll_ctx_add, ssh_poll_ctx_dopoll, ssh_poll_get_ctx, ssh_poll_get_default_ctx, SSH_SESSION_STATE_ERROR, ssh_socket_get_poll_handle, SSH_TIMEOUT_USER, ssh_session_struct::timeout, ssh_session_struct::timeout_usec.
Referenced by channel_protocol_select, channel_read_buffer, ssh_channel_accept, ssh_channel_poll, ssh_execute_message_callbacks, ssh_handle_packets_termination, ssh_send_debug, ssh_send_ignore, test_algorithm, torture_rekey_send, torture_rekey_server_send, torture_rekey_time.
int ssh_handle_packets_termination(ssh_session session, long timeout, ssh_termination_function fct, void *user)
References ssh_session_struct::opts, session, SSH_AGAIN, SSH_ERROR, ssh_handle_packets, ssh_is_blocking, ssh_make_milliseconds, SSH_OK, SSH_TIMEOUT_DEFAULT, ssh_timeout_elapsed, SSH_TIMEOUT_INFINITE, SSH_TIMEOUT_NONBLOCKING, ssh_timeout_update, SSH_TIMEOUT_USER, ssh_timestamp_init, ssh_session_struct::timeout, ssh_session_struct::timeout_usec, user.
Referenced by channel_open, channel_request, channel_write_common, ssh_blocking_flush, ssh_channel_get_exit_status, ssh_channel_poll_timeout, ssh_channel_read_timeout, ssh_connect, ssh_global_request, ssh_handle_key_exchange, ssh_message_get, ssh_service_request, ssh_userauth_get_response.
int ssh_get_status(ssh_session session)
Get session status.
session The ssh session to use. A bitmask including SSH_CLOSED, SSH_READ_PENDING, SSH_WRITE_PENDING or SSH_CLOSED_ERROR which respectively means the session is closed, has data to read on the connection socket and session was closed due to an error.
References session, ssh_session_struct::session_state, ssh_session_struct::socket, SSH_CLOSED, SSH_CLOSED_ERROR, SSH_READ_PENDING, SSH_SESSION_STATE_DISCONNECTED, SSH_SESSION_STATE_ERROR, ssh_socket_get_status, SSH_WRITE_PENDING.
Referenced by default_handle_session_cb, handle_kbdint_session_cb, handle_session.
int ssh_get_poll_flags(ssh_session session)
Get poll flags for an external mainloop.
session The ssh session to use. A bitmask including SSH_READ_PENDING or SSH_WRITE_PENDING. For SSH_READ_PENDING, your invocation of poll() should include POLLIN. For SSH_WRITE_PENDING, your invocation of poll() should include POLLOUT.
References session, ssh_session_struct::socket, ssh_socket_get_poll_flags.
const char* ssh_get_disconnect_message(ssh_session session)
Get the disconnect message from the server.
session The ssh session to use. The message sent by the server along with the disconnect, or NULL in which case the reason of the disconnect may be found with ssh_get_error. ssh_get_error()
References ssh_session_struct::discon_msg, session, ssh_session_struct::session_state, SSH_FATAL, SSH_REQUEST_DENIED, SSH_SESSION_STATE_DISCONNECTED, ssh_set_error.
Referenced by ssh::Session::getDisconnectMessage.
int ssh_get_version(ssh_session session)
Get the protocol version of the session.
session The ssh session to use. The SSH version as integer, < 0 on error.
References session.
Referenced by ssh::Session::getVersion.
void ssh_socket_exception_callback(int code, int errno_code, void *user)
References session, ssh_session_struct::session_state, ssh_session_struct::ssh_connection_callback, SSH_FATAL, SSH_LOG, SSH_LOG_RARE, SSH_SESSION_STATE_ERROR, ssh_set_error, SSH_SOCKET_EXCEPTION_EOF, user.
Referenced by ssh_connect, ssh_handle_key_exchange.
int ssh_send_ignore(ssh_session session, const char *data)
Send a message that should be ignored.
session The SSH session data Data to be sent SSH_OK on success, SSH_ERROR otherwise.
References error, ssh_session_struct::out_buffer, rc, session, ssh_session_struct::socket, SSH2_MSG_IGNORE, ssh_buffer_pack, ssh_buffer_reinit, SSH_ERROR, ssh_handle_packets, SSH_OK, ssh_packet_send, ssh_set_error_oom, ssh_socket_is_open.
Referenced by test_algorithm, torture_rekey_send, torture_rekey_server_send, torture_rekey_time.
int ssh_send_debug(ssh_session session, const char *message, int always_display)
Send a debug message.
session The SSH session message Data to be sent always_display Message SHOULD be displayed by the server. It SHOULD NOT be displayed unless debugging information has been explicitly requested. SSH_OK on success, SSH_ERROR otherwise.
References error, ssh_session_struct::out_buffer, rc, session, ssh_session_struct::socket, SSH2_MSG_DEBUG, ssh_buffer_pack, ssh_buffer_reinit, SSH_ERROR, ssh_handle_packets, SSH_OK, ssh_packet_send, ssh_set_error_oom, ssh_socket_is_open.
void ssh_set_counters(ssh_session session, ssh_counter scounter, ssh_counter rcounter)
Set the session data counters.
This functions sets the counter structures to be used to calculate data which comes in and goes out through the session at different levels. structssh_counter_structscounter={ .in_bytes=0, .out_bytes=0, .in_packets=0, .out_packets=0 }; structssh_counter_structrcounter={ .in_bytes=0, .out_bytes=0, .in_packets=0, .out_packets=0 }; ssh_set_counters(session,&scounter,&rcounter); session The SSH session. scounter Counter for byte data handled by the session sockets. rcounter Counter for byte and packet data handled by the session, prior compression and SSH overhead.
References ssh_session_struct::raw_counter, session, ssh_session_struct::socket_counter.
int ssh_get_pubkey_hash(ssh_session session, unsigned char **hash)
DeprecatedUse ssh_get_publickey_hash()
References ctx, ssh_session_struct::current_crypto, MD5_DIGEST_LEN, md5_final, md5_init, md5_update, pubkey, rc, SAFE_FREE, ssh_crypto_struct::server_pubkey, session, SSH_ERROR, SSH_FATAL, ssh_get_server_publickey, ssh_key_free, SSH_OK, ssh_pki_export_pubkey_blob, ssh_set_error, ssh_string_data, SSH_STRING_FREE, ssh_string_len.
void ssh_clean_pubkey_hash(unsigned char **hash)
Deallocate the hash obtained by ssh_get_pubkey_hash.
This is required under Microsoft platform as this library might use a different C library than your software, hence a different heap. hash The buffer to deallocate. ssh_get_pubkey_hash()
References SAFE_FREE.
Referenced by verify_knownhost.
int ssh_get_server_publickey(ssh_session session, ssh_key *key)
Get the server public key from a session.
session The session to get the key from. key A pointer to store the allocated key. You need to free the key. SSH_OK on success, SSH_ERROR on errror. ssh_key_free()
References ssh_session_struct::current_crypto, key, pubkey, ssh_crypto_struct::server_pubkey, session, SSH_ERROR, ssh_key_dup, SSH_OK.
Referenced by ssh_get_pubkey_hash, ssh_get_publickey, verify_knownhost.
int ssh_get_publickey(ssh_session session, ssh_key *key)
DeprecatedUse ssh_get_server_publickey()
References key, session, ssh_get_server_publickey.
int ssh_get_publickey_hash(const ssh_key key, enum ssh_publickey_hash_type type, unsigned char **hash, size_t *hlen)
Allocates a buffer with the hash of the public key.
This function allows you to get a hash of the public key. You can then print this hash in a human-readable form to the user so that he is able to verify it. Use ssh_get_hexa() or ssh_print_hash() to display it. key The public key to create the hash for. type The type of the hash you want. hash A pointer to store the allocated buffer. It can be freed using ssh_clean_pubkey_hash(). hlen The length of the hash. 0 on success, -1 if an error occured. It is very important that you verify at some moment that the hash matches a known server. If you don't do it, cryptography wont help you at making things secure. OpenSSH uses SHA256 to print public key digests. ssh_session_update_known_hosts() ssh_get_hexa() ssh_print_hash() ssh_clean_pubkey_hash()
References ctx, key, MD5_DIGEST_LEN, md5_final, md5_init, md5_update, rc, sha1_final, sha1_init, sha1_update, sha256_final, sha256_init, sha256_update, SSH_ERROR, SSH_LOG, SSH_LOG_WARN, ssh_pki_export_pubkey_blob, SSH_PUBLICKEY_HASH_MD5, SSH_PUBLICKEY_HASH_SHA1, SSH_PUBLICKEY_HASH_SHA256, ssh_string_data, SSH_STRING_FREE, ssh_string_len.
Referenced by torture_md5_hash, torture_sha1_hash, torture_sha256_fingerprint, torture_sha256_hash, verify_knownhost.
KNOWNHOSTS_MAXTYPES