libssh_misc
int ssh_getpass(const char *prompt, char *buf, size_t len, int echo, int verify)
Get a password from the console.
You should make sure that the buffer is an empty string! You can also use this function to ask for a username. Then you can fill the buffer with the username and it is shows to the users. If the users just presses enter the buffer will be untouched. charusername[128]; snprintf(username,sizeof(username),"john"); ssh_getpass("Username:",username,sizeof(username),1,0); The prompt will look like this: Username: [john] If you press enter then john is used as the username, or you can type it in to change it. prompt The prompt to show to ask for the password. buf The buffer the password should be stored. It NEEDS to be empty or filled out. len The length of the buffer. echo Should we echo what you type. verify Should we ask for the password twice. 0 on success, -1 on error.
References echo, explicit_bzero, ssh_gets, ZERO_STRUCT.
Referenced by auth_callback, authenticate_console, authenticate_kbdint.
char* ssh_get_user_home_dir(void)
References NSS_BUFLEN_PASSWD, rc.
Referenced by ssh_path_expand_tilde, torture_get_user_home_dir.
int ssh_file_readaccess_ok(const char *file)
Referenced by ssh_try_publickey_from_file.
int ssh_dir_writeable(const char *path)
Check if the given path is an existing directory and that is accessible for writing.
path Path to the directory to be checked Return 1 if the directory exists and is accessible; 0 otherwise
References buffer, rc.
Referenced by torture_ssh_dir_writeable, torture_ssh_mkdirs.
char* ssh_get_local_username(void)
References name, NSS_BUFLEN_PASSWD, rc.
Referenced by ssh_config_parse_line, ssh_options_set, ssh_path_expand_escape, ssh_pki_export_pubkey_file, ssh_publickey_to_file, torture_config_match, torture_options_config_match.
int ssh_is_ipaddr_v4(const char *str)
References rc.
Referenced by ssh_is_ipaddr.
int ssh_is_ipaddr(const char *str)
References rc, ssh_is_ipaddr_v4.
Referenced by getai, torture_ssh_is_ipaddr.
char* ssh_lowercase(const char *str)
Referenced by ssh_config_parse_line, ssh_dump_knownhost, ssh_is_server_known, ssh_session_get_host_port.
char* ssh_hostport(const char *host, int port)
References host, port.
Referenced by ssh_dump_knownhost, ssh_is_server_known, ssh_known_hosts_parse_line, ssh_session_get_host_port.
char* ssh_get_hexa(const unsigned char *what, size_t len)
Convert a buffer into a colon separated hex string. The caller has to free the memory.
what What should be converted to a hex string. len Length of the buffer to convert. The hex string or NULL on error. ssh_string_free_char()
Referenced by ssh_get_fingerprint_hash, ssh_gssapi_match, SSH_PACKET_CALLBACK, ssh_print_hexa, torture_md5_hash.
void ssh_print_hexa(const char *descr, const unsigned char *what, size_t len)
DeprecatedPlease use ssh_print_hash() instead
References ssh_get_hexa.
void ssh_log_hexdump(const char *descr, const unsigned char *what, size_t len)
Log the content of a buffer in hexadecimal format, similar to the output of 'hexdump -C' command.
The first logged line is the given description followed by the length. Then the content of the buffer is logged 16 bytes per line in the following format: (offset) (first 8 bytes) (last 8 bytes) (the 16 bytes as ASCII char values) The output for a 16 bytes array containing values from 0x00 to 0x0f would be: "Example (16 bytes):" " 00000000 00 01 02 03 04 05 06 07 08 09 0a 0b 0c 0d 0e 0f ................" The value for each byte as corresponding ASCII character is printed at the end if the value is printable. Otherwise it is replace with '.'. descr A description for the content to be logged what The buffer to be logged len The length of the buffer given in what If a too long description is provided (which would result in a first line longer than 80 bytes), the function will fail.
References buffer, error, SSH_LOG, SSH_LOG_DEBUG, SSH_LOG_WARN.
Referenced by chacha20_poly1305_aead_decrypt, pki_import_privkey_buffer, pki_import_pubkey_buffer, pki_sign_data, pki_signature_from_dsa_blob, pki_signature_from_ecdsa_blob, pki_signature_from_rsa_blob, ssh_dh_debug_crypto, ssh_generate_session_keys, ssh_list_kex, ssh_make_sessionid, ssh_packet_encrypt, ssh_packet_hmac_verify.
const char* ssh_version(int req_version)
Check if libssh is the required version or get the version string.
req_version The version required. If the version of libssh is newer than the version required it will return a version string. NULL if the version is older. Example: if(ssh_version(SSH_VERSION_INT(0,2,1))==NULL){ fprintf(stderr,"libsshversionistooold!\n"); exit(1); } if(debug){ printf("libssh%s\n",ssh_version(0)); }
References CRYPTO_STRING, GCRYPT_STRING, LIBSSH_VERSION, LIBSSH_VERSION_INT, MBED_STRING, SSH_STRINGIFY, ZLIB_STRING.
Referenced by usage.
struct ssh_list* ssh_list_new(void)
References ssh_list::end, ssh_list::root.
Referenced by ssh_add_set_channel_callbacks, ssh_channel_new, ssh_event_new, ssh_known_hosts_get_algorithms, ssh_known_hosts_read_entries, ssh_message_get, ssh_message_queue, ssh_new, ssh_packet_set_callbacks, torture_callbacks_execute_list, torture_callbacks_iterate, torture_ssh_list_append, torture_ssh_list_new, torture_ssh_list_prepend.
void ssh_list_free(struct ssh_list *list)
References ssh_iterator::next, ssh_list::root, SAFE_FREE.
Referenced by ssh_channel_do_free, ssh_disconnect, ssh_event_free, ssh_free, ssh_known_hosts_get_algorithms, ssh_known_hosts_get_algorithms_names, torture_callbacks_execute_list, torture_callbacks_iterate, torture_knownhosts_duplicate, torture_knownhosts_precheck, torture_knownhosts_read_file, torture_ssh_list_append, torture_ssh_list_new, torture_ssh_list_prepend.
struct ssh_iterator* ssh_list_get_iterator(const struct ssh_list *list)
References ssh_list::root.
Referenced by ssh_channel_accept, ssh_channel_from_local, ssh_disconnect, ssh_event_add_session, ssh_event_remove_session, ssh_free, ssh_known_hosts_get_algorithms, ssh_known_hosts_get_algorithms_names, ssh_known_hosts_read_entries, ssh_list_count, ssh_list_find, ssh_message_pop_head, ssh_message_termination, ssh_options_apply, ssh_options_copy, ssh_options_get, ssh_packet_process, ssh_packet_send, ssh_packet_socket_controlflow_callback, ssh_userauth_publickey_auto, torture_knownhosts_duplicate, torture_knownhosts_precheck, torture_knownhosts_read_file, torture_options_copy.
struct ssh_iterator* ssh_list_find(const struct ssh_list *list, void *value)
References ssh_iterator::data, ssh_iterator::next, ssh_list_get_iterator.
Referenced by ssh_channel_do_free, ssh_packet_remove_callbacks, ssh_remove_channel_callbacks.
size_t ssh_list_count(const struct ssh_list *list)
Get the number of elements in the list.
list The list to count. The number of elements in the list.
References ssh_iterator::next, ssh_list_get_iterator.
Referenced by ssh_known_hosts_get_algorithms, ssh_known_hosts_get_algorithms_names, torture_knownhosts_duplicate, torture_knownhosts_precheck, torture_ssh_list_append, torture_ssh_list_new, torture_ssh_list_prepend.
static struct ssh_iterator* ssh_iterator_new(const void *data)
References ssh_iterator::data, ssh_iterator::next.
Referenced by ssh_list_append, ssh_list_prepend.
int ssh_list_append(struct ssh_list *list, const void *data)
References ssh_iterator::data, ssh_list::end, ssh_iterator::next, ssh_list::root, SSH_ERROR, ssh_iterator_new, SSH_OK.
Referenced by ssh_add_set_channel_callbacks, ssh_event_add_session, ssh_known_hosts_get_algorithms, ssh_known_hosts_read_entries, ssh_message_queue, ssh_new, ssh_options_copy, ssh_packet_send, ssh_packet_set_callbacks, torture_callbacks_execute_list, torture_callbacks_iterate, torture_ssh_list_append, torture_ssh_list_prepend.
int ssh_list_prepend(struct ssh_list *list, const void *data)
References ssh_iterator::data, ssh_list::end, ssh_iterator::next, ssh_list::root, SSH_ERROR, ssh_iterator_new, SSH_OK.
Referenced by ssh_add_set_channel_callbacks, ssh_channel_new, ssh_options_set, torture_ssh_list_prepend.
void ssh_list_remove(struct ssh_list *list, struct ssh_iterator *iterator)
References ssh_list::end, ssh_iterator::next, ssh_list::root, SAFE_FREE.
Referenced by ssh_channel_accept, ssh_channel_do_free, ssh_disconnect, ssh_event_remove_session, ssh_free, ssh_known_hosts_get_algorithms, ssh_known_hosts_get_algorithms_names, ssh_message_pop_head, ssh_packet_remove_callbacks, ssh_remove_channel_callbacks, torture_knownhosts_precheck.
const void* _ssh_list_pop_head(struct ssh_list *list)
References ssh_iterator::data, ssh_list::end, ssh_iterator::next, ssh_list::root, SAFE_FREE.
char* ssh_dirname(const char *path)
Parse directory component.
dirname breaks a null-terminated pathname string into a directory component. In the usual case, ssh_dirname() returns the string up to, but not including, the final '/'. Trailing '/' characters are not counted as part of the pathname. The caller must free the memory. path The path to parse. The dirname of path or NULL if we can't allocate memory. If path does not contain a slash, c_dirname() returns the string ".". If path is the string "/", it returns the string "/". If path is NULL or an empty string, "." is returned.
Referenced by ssh_known_hosts_check_server_key, ssh_mkdirs, ssh_write_knownhost, torture_dirname.
char* ssh_basename(const char *path)
basename - parse filename component.
basename breaks a null-terminated pathname string into a filename component. ssh_basename() returns the component following the final '/'. Trailing '/' characters are not counted as part of the pathname. path The path to parse. The filename of path or NULL if we can't allocate memory. If path is a the string "/", basename returns the string "/". If path is NULL or an empty string, "." is returned.
References s.
Referenced by session_setup, ssh_scp_push_directory, ssh_scp_push_file64, torture_basename.
int ssh_mkdir(const char *pathname, mode_t mode)
Attempts to create a directory with the given pathname.
This is the portable version of mkdir, mode is ignored on Windows systems. pathname The path name to create the directory. mode The permissions to use. 0 on success, < 0 on error with errno set.
Referenced by torture_ssh_dir_writeable.
int ssh_mkdirs(const char *pathname, mode_t mode)
Attempts to create a directory with the given pathname. The missing directories in the given pathname are created recursively.
pathname The path name to create the directory. mode The permissions to use. 0 on success, < 0 on error with errno set. mode is ignored on Windows systems.
References rc, SAFE_FREE, ssh_dirname, ssh_mkdirs.
Referenced by ssh_known_hosts_check_server_key, ssh_mkdirs, ssh_write_knownhost, torture_ssh_mkdirs.
char* ssh_path_expand_tilde(const char *d)
Expand a directory starting with a tilde '~'.
d The directory to expand. The expanded directory, NULL on error.
References s, SAFE_FREE, ssh_get_user_home_dir.
Referenced by setup_config_files, ssh_options_set, ssh_path_expand_escape, teardown, torture_client_config_emulate, torture_path_expand_tilde_unix.
char* ssh_path_expand_escape(ssh_session session, const char *s)
References host, ssh_session_struct::host, MAX_BUF_SIZE, ssh_session_struct::opts, ssh_session_struct::port, s, SAFE_FREE, session, SSH_FATAL, ssh_get_local_username, ssh_path_expand_tilde, ssh_set_error, ssh_set_error_oom, ssh_session_struct::sshdir, ssh_session_struct::username.
Referenced by ssh_config_parse_line, ssh_match_exec, ssh_options_apply, ssh_options_parse_config, torture_path_expand_escape, torture_path_expand_known_hosts, torture_path_expand_percent.
int ssh_analyze_banner(ssh_session session, int server)
References ssh_session_struct::clientbanner, FALL_THROUGH, ssh_session_struct::openssh, ssh_session_struct::serverbanner, session, SSH_FATAL, SSH_LOG, SSH_LOG_PROTOCOL, ssh_set_error, SSH_VERSION_INT.
Referenced by ssh_client_connection_callback, ssh_server_connection_callback.
void ssh_timestamp_init(struct ssh_timestamp *ts)
References CLOCK, ssh_timestamp::seconds, ssh_timestamp::useconds.
Referenced by ssh_channel_select, ssh_handle_packets_termination, ssh_packet_set_newkeys, ssh_poll_ctx_dopoll, ssh_select, ssh_timeout_elapsed, ssh_timeout_update, torture_timeout_elapsed, torture_timeout_update, torture_wait_for_daemon.
static int ssh_timestamp_difference(struct ssh_timestamp *old, struct ssh_timestamp *new)
References ssh_timestamp::seconds, ssh_timestamp::useconds.
Referenced by ssh_timeout_elapsed, ssh_timeout_update.
int ssh_make_milliseconds(long sec, long usec)
Referenced by ssh_handle_packets, ssh_handle_packets_termination.
int ssh_timeout_elapsed(struct ssh_timestamp *ts, int timeout)
References SSH_LOG, SSH_LOG_WARN, ssh_timestamp_difference, ssh_timestamp_init.
Referenced by ssh_channel_select, ssh_handle_packets_termination, ssh_packet_need_rekey, ssh_select, torture_timeout_elapsed, torture_wait_for_daemon.
int ssh_timeout_update(struct ssh_timestamp *ts, int timeout)
updates a timeout value so it reflects the remaining time
ts pointer to an existing timestamp timeout timeout in milliseconds. Negative values mean infinite timeout remaining time in milliseconds, 0 if elapsed, -1 if never.
References ssh_timestamp_difference, ssh_timestamp_init.
Referenced by ssh_channel_select, ssh_handle_packets_termination, ssh_poll_ctx_dopoll, ssh_select, torture_timeout_update.
int ssh_match_group(const char *group, const char *object)
References generate.a.
Referenced by ssh_key_algorithm_allowed, SSH_PACKET_CALLBACK.
void explicit_bzero(void *s, size_t n)
References s.
Referenced by bcrypt_hash, bcrypt_pbkdf, buffer_shift, crypto_free, pki_ed25519_verify, pki_private_key_decrypt, pki_private_key_encrypt, pki_sign_data, pki_signature_from_dsa_blob, pki_signature_from_ecdsa_blob, pki_signature_from_rsa_blob, realloc_buffer, ssh_buffer_free, ssh_buffer_reinit, ssh_buffer_unpack_va, ssh_free, ssh_getpass, ssh_gets, ssh_kbdint_clean, ssh_kbdint_free, ssh_key_clean, ssh_message_free, ssh_packet_encrypt, ssh_pki_openssh_privkey_export, ssh_pki_signature_verify, ssh_string_burn, ssh_tokens_free, ssh_userauth_kbdint_setanswer, torture_packet.
char* strndup(const char *s, size_t n)
References s.
Referenced by ssh_config_parse_uri, ssh_get_b64_unpadded, ssh_pki_export_privkey_base64.
void uint64_inc(unsigned char *counter)
int ssh_quote_file_name(const char *file_name, char *buf, size_t buf_len)
References DOUBLE_QUOTE, error, NO_QUOTE, SINGLE_QUOTE, SSH_ERROR, SSH_LOG, SSH_LOG_WARNING.
Referenced by ssh_scp_init, torture_ssh_quote_file_name.
int ssh_newline_vis(const char *string, char *buf, size_t buf_len)
References SSH_ERROR, SSH_LOG, SSH_LOG_WARNING.
Referenced by ssh_scp_push_directory, ssh_scp_push_file64, torture_ssh_newline_vis.
int ssh_tmpname(char *template)
References SSH_LOG, SSH_LOG_WARNING, time.
Referenced by setup_tokens.
char* ssh_strreplace(const char *src, const char *pattern, const char *replace)
References pattern.
Referenced by ssh_pki_export_pub_uri_from_priv_uri, torture_ssh_strreplace.
NSS_BUFLEN_PASSWD
CLOCK