libssh_scp
ssh_scp ssh_scp_new(ssh_session session, int mode, const char *location)
Create a new scp session.
session The SSH session to use. mode One of SSH_SCP_WRITE or SSH_SCP_READ, depending if you need to drop files remotely or read them. It is not possible to combine read and write. SSH_SCP_RECURSIVE Flag can be or'ed to this to indicate that you're going to use recursion. Browsing through directories is not possible without this. location The directory in which write or read will be done. Any push or pull will be relative to this place. This can also be a pattern of files to download (read). A ssh_scp handle, NULL if the creation was impossible.
References ssh_scp_struct::channel, error, ssh_scp_struct::location, ssh_scp_struct::mode, ssh_scp_struct::recursive, ssh_scp_struct::session, session, SSH_FATAL, ssh_scp_free, SSH_SCP_NEW, SSH_SCP_READ, SSH_SCP_RECURSIVE, SSH_SCP_WRITE, ssh_set_error, ssh_scp_struct::state.
Referenced by benchmarks_scp_down, benchmarks_scp_up, fetch_files, torture_scp_download, torture_scp_download_recursive, torture_scp_upload, torture_scp_upload_newline, torture_scp_upload_recursive.
int ssh_scp_init(ssh_scp scp)
Initialize the scp channel.
scp The scp context to initialize. SSH_OK on success or an SSH error code. ssh_scp_new()
References ssh_scp_struct::channel, ssh_scp_struct::location, ssh_scp_struct::mode, rc, ssh_scp_struct::recursive, SAFE_FREE, ssh_scp_struct::session, ssh_channel_new, ssh_channel_open_session, ssh_channel_request_exec, ssh_channel_write, SSH_ERROR, SSH_FATAL, SSH_LOG, SSH_LOG_DEBUG, SSH_LOG_PROTOCOL, SSH_OK, ssh_quote_file_name, SSH_SCP_ERROR, SSH_SCP_NEW, SSH_SCP_READ_INITED, ssh_scp_response, SSH_SCP_WRITE, SSH_SCP_WRITE_INITED, ssh_set_error, ssh_scp_struct::state.
Referenced by benchmarks_scp_down, benchmarks_scp_up, fetch_files, torture_scp_download, torture_scp_download_recursive, torture_scp_upload, torture_scp_upload_newline, torture_scp_upload_recursive.
int ssh_scp_close(ssh_scp scp)
Close the scp channel.
scp The scp context to close. SSH_OK on success or an SSH error code. ssh_scp_init()
References buffer, ssh_scp_struct::channel, rc, ssh_channel_close, ssh_channel_free, ssh_channel_is_eof, ssh_channel_read, ssh_channel_send_eof, SSH_ERROR, SSH_OK, SSH_SCP_ERROR, SSH_SCP_NEW, ssh_scp_struct::state.
Referenced by benchmarks_scp_down, benchmarks_scp_up, fetch_files, ssh_scp_free, torture_scp_download, torture_scp_download_recursive, torture_scp_upload, torture_scp_upload_newline, torture_scp_upload_recursive.
void ssh_scp_free(ssh_scp scp)
Free a scp context.
scp The context to free. ssh_scp_new()
References ssh_scp_struct::channel, ssh_scp_struct::location, ssh_scp_struct::request_name, SAFE_FREE, ssh_channel_free, ssh_scp_close, SSH_SCP_NEW, ssh_scp_struct::state, ssh_scp_struct::warning.
Referenced by benchmarks_scp_down, benchmarks_scp_up, fetch_files, ssh_scp_new, torture_scp_download, torture_scp_download_recursive, torture_scp_upload, torture_scp_upload_newline, torture_scp_upload_recursive.
int ssh_scp_push_directory(ssh_scp scp, const char *dirname, int mode)
Create a directory in a scp in sink mode.
scp The scp handle. dirname The name of the directory being created. mode The UNIX permissions for the new directory, e.g. 0755. SSH_OK if the directory has been created, SSH_ERROR if an error occured. ssh_scp_leave_directory()
References buffer, ssh_scp_struct::channel, error, rc, SAFE_FREE, ssh_scp_struct::session, ssh_basename, ssh_channel_write, SSH_ERROR, SSH_FATAL, SSH_LOG, SSH_LOG_PROTOCOL, ssh_newline_vis, SSH_OK, SSH_SCP_ERROR, ssh_scp_response, ssh_scp_string_mode, SSH_SCP_WRITE_INITED, ssh_set_error, ssh_set_error_oom, ssh_scp_struct::state.
Referenced by torture_scp_upload_newline, torture_scp_upload_recursive.
int ssh_scp_leave_directory(ssh_scp scp)
Leave a directory.
SSH_OK if the directory has been left, SSH_ERROR if an error occured. ssh_scp_push_directory()
References buffer, ssh_scp_struct::channel, rc, ssh_scp_struct::session, ssh_channel_write, SSH_ERROR, SSH_FATAL, SSH_OK, SSH_SCP_ERROR, ssh_scp_response, SSH_SCP_WRITE_INITED, ssh_set_error, ssh_scp_struct::state.
Referenced by torture_scp_upload_newline, torture_scp_upload_recursive.
int ssh_scp_push_file64(ssh_scp scp, const char *filename, uint64_t size, int mode)
Initialize the sending of a file to a scp in sink mode, using a 64-bit size.
scp The scp handle. filename The name of the file being sent. It should not contain any path indicator size Exact size in bytes of the file being sent. mode The UNIX permissions for the new file, e.g. 0644. SSH_OK if the file is ready to be sent, SSH_ERROR if an error occured. ssh_scp_push_file()
References buffer, ssh_scp_struct::channel, error, ssh_scp_struct::filelen, ssh_scp_struct::processed, rc, SAFE_FREE, ssh_scp_struct::session, ssh_basename, ssh_channel_write, SSH_ERROR, SSH_FATAL, SSH_LOG, SSH_LOG_PROTOCOL, ssh_newline_vis, SSH_OK, SSH_SCP_ERROR, ssh_scp_response, ssh_scp_string_mode, SSH_SCP_WRITE_INITED, SSH_SCP_WRITE_WRITING, ssh_set_error, ssh_set_error_oom, ssh_scp_struct::state.
Referenced by ssh_scp_push_file.
int ssh_scp_push_file(ssh_scp scp, const char *filename, size_t size, int mode)
Initialize the sending of a file to a scp in sink mode.
scp The scp handle. filename The name of the file being sent. It should not contain any path indicator size Exact size in bytes of the file being sent. mode The UNIX permissions for the new file, e.g. 0644. SSH_OK if the file is ready to be sent, SSH_ERROR if an error occured.
References ssh_scp_push_file64.
Referenced by benchmarks_scp_up, torture_scp_upload, torture_scp_upload_newline, torture_scp_upload_recursive.
int ssh_scp_response(ssh_scp scp, char **response)
References ssh_scp_struct::channel, rc, ssh_scp_struct::session, ssh_channel_read, SSH_ERROR, SSH_FATAL, SSH_LOG, SSH_LOG_RARE, SSH_REQUEST_DENIED, SSH_SCP_ERROR, ssh_scp_read_string, ssh_set_error, ssh_scp_struct::state.
Referenced by ssh_scp_init, ssh_scp_leave_directory, ssh_scp_push_directory, ssh_scp_push_file64, ssh_scp_read, ssh_scp_write.
int ssh_scp_write(ssh_scp scp, const void *buffer, size_t len)
Write into a remote scp file.
scp The scp handle. buffer The buffer to write. len The number of bytes to write. SSH_OK if the write was successful, SSH_ERROR an error occured while writing.
References buffer, ssh_scp_struct::channel, ssh_scp_struct::filelen, ssh_scp_struct::processed, rc, ssh_scp_struct::session, ssh_channel_poll, ssh_channel_write, SSH_ERROR, SSH_FATAL, SSH_OK, SSH_SCP_ERROR, ssh_scp_response, SSH_SCP_WRITE_INITED, SSH_SCP_WRITE_WRITING, ssh_set_error, ssh_scp_struct::state.
Referenced by benchmarks_scp_up, torture_scp_upload, torture_scp_upload_newline, torture_scp_upload_recursive.
int ssh_scp_read_string(ssh_scp scp, char *buffer, size_t len)
Read a string on a channel, terminated by ' '.
scp The scp handle. buffer A pointer to a buffer to place the string. len The size of the buffer in bytes. If the string is bigger than len-1, only len-1 bytes are read and the string is null-terminated. SSH_OK if the string was read, SSH_ERROR if an error occured while reading.
References buffer, ssh_scp_struct::channel, ssh_scp_struct::session, ssh_channel_read, SSH_ERROR, SSH_FATAL, SSH_OK, ssh_set_error.
Referenced by ssh_scp_pull_request, ssh_scp_response.
int ssh_scp_pull_request(ssh_scp scp)
Wait for a scp request (file, directory).
SSH_SCP_REQUEST_NEWFILE: The other side is sending a file SSH_SCP_REQUEST_NEWDIR: The other side is sending a directory SSH_SCP_REQUEST_ENDDIR: The other side has finished with the current directory SSH_SCP_REQUEST_WARNING: The other side sent us a warning SSH_SCP_REQUEST_EOF: The other side finished sending us files and data. SSH_ERROR: Some error happened ssh_scp_read() ssh_scp_deny_request() ssh_scp_accept_request() ssh_scp_request_get_warning()
References buffer, ssh_scp_struct::channel, error, ssh_scp_struct::filelen, MAX_BUF_SIZE, name, ssh_scp_struct::processed, rc, ssh_scp_struct::request_mode, ssh_scp_struct::request_name, ssh_scp_struct::request_type, SAFE_FREE, ssh_scp_struct::session, ssh_channel_is_eof, ssh_channel_write, SSH_ERROR, SSH_FATAL, SSH_LOG, SSH_LOG_PROTOCOL, SSH_REQUEST_DENIED, ssh_scp_integer_mode, SSH_SCP_READ_INITED, SSH_SCP_READ_REQUESTED, ssh_scp_read_string, SSH_SCP_REQUEST_ENDDIR, SSH_SCP_REQUEST_EOF, SSH_SCP_REQUEST_NEWDIR, SSH_SCP_REQUEST_NEWFILE, SSH_SCP_REQUEST_WARNING, SSH_SCP_TERMINATED, ssh_set_error, ssh_scp_struct::state, ssh_scp_struct::warning.
Referenced by benchmarks_scp_down, fetch_files, torture_scp_download, torture_scp_download_recursive.
int ssh_scp_deny_request(ssh_scp scp, const char *reason)
Deny the transfer of a file or creation of a directory coming from the remote party.
scp The scp handle. reason A nul-terminated string with a human-readable explanation of the deny. SSH_OK if the message was sent, SSH_ERROR if the sending the message failed, or sending it in a bad state.
References buffer, ssh_scp_struct::channel, MAX_BUF_SIZE, rc, ssh_scp_struct::session, ssh_channel_write, SSH_ERROR, SSH_FATAL, SSH_OK, SSH_SCP_READ_INITED, SSH_SCP_READ_REQUESTED, ssh_set_error, ssh_scp_struct::state.
int ssh_scp_accept_request(ssh_scp scp)
Accepts transfer of a file or creation of a directory coming from the remote party.
scp The scp handle. SSH_OK if the message was sent, SSH_ERROR if sending the message failed, or sending it in a bad state.
References buffer, ssh_scp_struct::channel, rc, ssh_scp_struct::request_type, ssh_scp_struct::session, ssh_channel_write, SSH_ERROR, SSH_FATAL, SSH_OK, SSH_SCP_READ_INITED, SSH_SCP_READ_READING, SSH_SCP_READ_REQUESTED, SSH_SCP_REQUEST_NEWFILE, ssh_set_error, ssh_scp_struct::state.
Referenced by benchmarks_scp_down, fetch_files, ssh_scp_read, torture_scp_download, torture_scp_download_recursive.
int ssh_scp_read(ssh_scp scp, void *buffer, size_t size)
Read from a remote scp file.
scp The scp handle. buffer The destination buffer. size The size of the buffer. The nNumber of bytes read, SSH_ERROR if an error occured while reading.
References buffer, ssh_scp_struct::channel, ssh_scp_struct::filelen, ssh_scp_struct::processed, rc, ssh_scp_struct::request_type, ssh_scp_struct::session, ssh_channel_read, ssh_channel_write, SSH_ERROR, SSH_FATAL, ssh_scp_accept_request, SSH_SCP_ERROR, SSH_SCP_READ_INITED, SSH_SCP_READ_READING, SSH_SCP_READ_REQUESTED, SSH_SCP_REQUEST_NEWFILE, ssh_scp_response, ssh_set_error, ssh_scp_struct::state.
Referenced by benchmarks_scp_down, fetch_files, torture_scp_download, torture_scp_download_recursive.
const char* ssh_scp_request_get_filename(ssh_scp scp)
Get the name of the directory or file being pushed from the other party.
The file name, NULL on error. The string should not be freed.
References ssh_scp_struct::request_name.
Referenced by fetch_files, torture_scp_download, torture_scp_download_recursive.
int ssh_scp_request_get_permissions(ssh_scp scp)
Get the permissions of the directory or file being pushed from the other party.
The UNIX permission, e.g 0644, -1 on error.
References ssh_scp_struct::request_mode.
Referenced by fetch_files, torture_scp_download, torture_scp_download_recursive.
size_t ssh_scp_request_get_size(ssh_scp scp)
Get the size of the file being pushed from the other party.
The numeric size of the file being read. The real size may not fit in a 32 bits field and may be truncated. ssh_scp_request_get_size64()
References ssh_scp_struct::filelen.
Referenced by benchmarks_scp_down, fetch_files, torture_scp_download, torture_scp_download_recursive.
uint64_t ssh_scp_request_get_size64(ssh_scp scp)
Get the size of the file being pushed from the other party.
The numeric size of the file being read.
References ssh_scp_struct::filelen.
int ssh_scp_integer_mode(const char *mode)
Convert a scp text mode to an integer.
mode The mode to convert, e.g. "0644". An integer value, e.g. 420 for "0644".
Referenced by ssh_scp_pull_request.
char* ssh_scp_string_mode(int mode)
Convert a unix mode into a scp string.
mode The mode to convert, e.g. 420 or 0644. A pointer to a malloc'ed string containing the scp mode, e.g. "0644".
References buffer.
Referenced by ssh_scp_push_directory, ssh_scp_push_file64.
const char* ssh_scp_request_get_warning(ssh_scp scp)
Get the warning string from a scp handle.
scp The scp handle. A warning string, or NULL on error. The string should not be freed.
References ssh_scp_struct::warning.
Referenced by fetch_files.