libssh_auth
ssh_agent_state_e
ssh_auth_auto_state_e
static int ssh_userauth_request_service(ssh_session session)
References rc, session, SSH_AGAIN, SSH_LOG, SSH_LOG_WARN, SSH_OK, ssh_service_request.
Referenced by ssh_userauth_agent_publickey, ssh_userauth_kbdint_init, ssh_userauth_none, ssh_userauth_password, ssh_userauth_publickey, ssh_userauth_try_publickey.
static int ssh_auth_response_termination(void *user)
References ssh_session_struct::auth, session, SSH_AUTH_STATE_AUTH_NONE_SENT, SSH_AUTH_STATE_GSSAPI_MIC_SENT, SSH_AUTH_STATE_GSSAPI_REQUEST_SENT, SSH_AUTH_STATE_GSSAPI_TOKEN, SSH_AUTH_STATE_KBDINT_SENT, SSH_AUTH_STATE_NONE, SSH_AUTH_STATE_PASSWORD_AUTH_SENT, SSH_AUTH_STATE_PUBKEY_AUTH_SENT, SSH_AUTH_STATE_PUBKEY_OFFER_SENT, ssh_session_struct::state, user.
Referenced by ssh_userauth_get_response.
static const char* ssh_auth_get_current_method(ssh_session session)
References ssh_session_struct::auth, ssh_session_struct::current_method, session, SSH_AUTH_METHOD_GSSAPI_MIC, SSH_AUTH_METHOD_HOSTBASED, SSH_AUTH_METHOD_INTERACTIVE, SSH_AUTH_METHOD_NONE, SSH_AUTH_METHOD_PASSWORD, SSH_AUTH_METHOD_PUBLICKEY.
Referenced by SSH_PACKET_CALLBACK.
static int ssh_userauth_get_response(ssh_session session)
References ssh_session_struct::auth, rc, session, SSH_AUTH_AGAIN, SSH_AUTH_DENIED, SSH_AUTH_ERROR, SSH_AUTH_INFO, SSH_AUTH_PARTIAL, ssh_auth_response_termination, SSH_AUTH_STATE_AUTH_NONE_SENT, SSH_AUTH_STATE_ERROR, SSH_AUTH_STATE_FAILED, SSH_AUTH_STATE_GSSAPI_MIC_SENT, SSH_AUTH_STATE_GSSAPI_REQUEST_SENT, SSH_AUTH_STATE_GSSAPI_TOKEN, SSH_AUTH_STATE_INFO, SSH_AUTH_STATE_KBDINT_SENT, SSH_AUTH_STATE_NONE, SSH_AUTH_STATE_PARTIAL, SSH_AUTH_STATE_PASSWORD_AUTH_SENT, SSH_AUTH_STATE_PK_OK, SSH_AUTH_STATE_PUBKEY_AUTH_SENT, SSH_AUTH_STATE_PUBKEY_OFFER_SENT, SSH_AUTH_STATE_SUCCESS, SSH_AUTH_SUCCESS, SSH_ERROR, ssh_handle_packets_termination, SSH_TIMEOUT_USER, ssh_session_struct::state.
Referenced by ssh_userauth_agent_publickey, ssh_userauth_kbdint_init, ssh_userauth_kbdint_send, ssh_userauth_none, ssh_userauth_password, ssh_userauth_publickey, ssh_userauth_try_publickey.
SSH_PACKET_CALLBACK(ssh_packet_userauth_banner)
References ssh_session_struct::banner, session, ssh_buffer_get_ssh_string, SSH_LOG, SSH_LOG_DEBUG, SSH_LOG_WARN, SSH_PACKET_USED, SSH_STRING_FREE, user.
SSH_PACKET_CALLBACK(ssh_packet_userauth_failure)
References ssh_session_struct::auth, ssh_session_struct::current_method, rc, SAFE_FREE, session, ssh_auth_get_current_method, SSH_AUTH_METHOD_GSSAPI_MIC, SSH_AUTH_METHOD_HOSTBASED, SSH_AUTH_METHOD_INTERACTIVE, SSH_AUTH_METHOD_PASSWORD, SSH_AUTH_METHOD_PUBLICKEY, SSH_AUTH_METHOD_UNKNOWN, SSH_AUTH_STATE_ERROR, SSH_AUTH_STATE_FAILED, SSH_AUTH_STATE_PARTIAL, ssh_buffer_unpack, SSH_FATAL, ssh_get_error, SSH_LOG, SSH_LOG_INFO, SSH_OK, SSH_PACKET_USED, SSH_REQUEST_DENIED, ssh_set_error, ssh_session_struct::state, ssh_session_struct::supported_methods, user.
SSH_PACKET_CALLBACK(ssh_packet_userauth_success)
References ssh_session_struct::auth, ssh_session_struct::current_method, ssh_crypto_struct::delayed_compress_in, ssh_crypto_struct::delayed_compress_out, ssh_crypto_struct::do_compress_in, ssh_crypto_struct::do_compress_out, ssh_session_struct::flags, session, ssh_session_struct::session_state, SSH_AUTH_METHOD_UNKNOWN, SSH_AUTH_STATE_SUCCESS, SSH_DIRECTION_IN, SSH_DIRECTION_OUT, SSH_LOG, SSH_LOG_DEBUG, SSH_LOG_TRACE, ssh_packet_get_current_crypto, SSH_PACKET_USED, ssh_reset_error, SSH_SESSION_FLAG_AUTHENTICATED, SSH_SESSION_STATE_AUTHENTICATED, ssh_session_struct::state, user.
SSH_PACKET_CALLBACK(ssh_packet_userauth_pk_ok)
References ssh_session_struct::auth, rc, session, SSH_AUTH_STATE_ERROR, SSH_AUTH_STATE_GSSAPI_REQUEST_SENT, SSH_AUTH_STATE_KBDINT_SENT, SSH_AUTH_STATE_PK_OK, SSH_AUTH_STATE_PUBKEY_OFFER_SENT, SSH_LOG, SSH_LOG_TRACE, SSH_PACKET_USED, ssh_session_struct::state, user.
int ssh_userauth_list(ssh_session session, const char *username)
Get available authentication methods from the server.
This requires the function ssh_userauth_none() to be called before the methods are available. The server MAY return a list of methods that may continue. session The SSH session. username Deprecated, set to NULL. A bitfield of the fllowing values: SSH_AUTH_METHOD_PASSWORD SSH_AUTH_METHOD_PUBLICKEY SSH_AUTH_METHOD_HOSTBASED SSH_AUTH_METHOD_INTERACTIVE Other reserved flags may appear in future versions. ssh_userauth_none()
References ssh_session_struct::auth, session, ssh_session_struct::supported_methods, username.
Referenced by authenticate_console, ssh::Session::getAuthList, ssh_auth_list, torture_auth_agent, torture_auth_agent_nonblocking, torture_auth_autopubkey, torture_auth_autopubkey_nonblocking, torture_auth_kbdint, torture_auth_kbdint_nonblocking, torture_auth_password, torture_auth_password_nonblocking, torture_auth_pubkey_types, torture_auth_pubkey_types_ecdsa, torture_auth_pubkey_types_ecdsa_nonblocking, torture_auth_pubkey_types_ed25519, torture_auth_pubkey_types_ed25519_nonblocking, torture_auth_pubkey_types_nonblocking, torture_rekey_send, torture_rekey_server_send, torture_rekey_time, torture_server_auth_kbdint, torture_server_auth_password, torture_server_auth_pubkey, torture_ssh_session, try_config_content.
int ssh_userauth_none(ssh_session session, const char *username)
Try to authenticate through the "none" method.
session The ssh session to use. username The username, this SHOULD be NULL. SSH_AUTH_ERROR: A serious error happened. SSH_AUTH_DENIED: Authentication failed: use another method SSH_AUTH_PARTIAL: You've been partially authenticated, you still have to use another method SSH_AUTH_SUCCESS: Authentication success SSH_AUTH_AGAIN: In nonblocking mode, you've got to call this again later. Most server implementations do not permit changing the username during authentication. The username should only be set with ssh_options_set() only before you connect to the server.
References ssh_session_struct::auth, ssh_session_struct::current_method, ssh_session_struct::opts, ssh_session_struct::out_buffer, ssh_session_struct::pending_call_state, rc, session, SSH2_MSG_USERAUTH_REQUEST, SSH_AGAIN, SSH_AUTH_AGAIN, SSH_AUTH_ERROR, SSH_AUTH_METHOD_NONE, SSH_AUTH_STATE_AUTH_NONE_SENT, ssh_buffer_pack, ssh_buffer_reinit, SSH_ERROR, SSH_FATAL, ssh_packet_send, SSH_PENDING_CALL_AUTH_NONE, SSH_PENDING_CALL_NONE, ssh_set_error, ssh_set_error_oom, ssh_userauth_get_response, ssh_userauth_request_service, ssh_session_struct::state, username, ssh_session_struct::username.
Referenced by authenticate_console, client, connect_host, LLVMFuzzerTestOneInput, main, test_algorithm, torture_algorithms_zlib, torture_algorithms_zlib_openssh, torture_auth_agent, torture_auth_agent_nonblocking, torture_auth_autopubkey, torture_auth_autopubkey_nonblocking, torture_auth_kbdint, torture_auth_kbdint_nonblocking, torture_auth_none, torture_auth_none_nonblocking, torture_auth_password, torture_auth_password_nonblocking, torture_auth_pubkey_types, torture_auth_pubkey_types_ecdsa, torture_auth_pubkey_types_ecdsa_nonblocking, torture_auth_pubkey_types_ed25519, torture_auth_pubkey_types_ed25519_nonblocking, torture_auth_pubkey_types_nonblocking, torture_rekey_send, torture_rekey_server_send, torture_rekey_time, torture_server_auth_kbdint, torture_server_auth_none, torture_server_auth_password, torture_server_auth_pubkey, torture_ssh_session, try_config_content, ssh::Session::userauthNone.
int ssh_userauth_try_publickey(ssh_session session, const char *username, const ssh_key pubkey)
Try to authenticate with the given public key.
To avoid unnecessary processing and user interaction, the following method is provided for querying whether authentication using the 'pubkey' would be possible. session The SSH session. username The username, this SHOULD be NULL. pubkey The public key to try. SSH_AUTH_ERROR: A serious error happened. SSH_AUTH_DENIED: The server doesn't accept that public key as an authentication token. Try another key or another method. SSH_AUTH_PARTIAL: You've been partially authenticated, you still have to use another method. SSH_AUTH_SUCCESS: The public key is accepted, you want now to use ssh_userauth_publickey(). SSH_AUTH_AGAIN: In nonblocking mode, you've got to call this again later. Most server implementations do not permit changing the username during authentication. The username should only be set with ssh_options_set() only before you connect to the server.
References ssh_session_struct::auth, ssh_session_struct::current_method, ssh_session_struct::opts, ssh_session_struct::out_buffer, ssh_session_struct::pending_call_state, pubkey, rc, session, SSH2_MSG_USERAUTH_REQUEST, SSH_AGAIN, SSH_AUTH_AGAIN, SSH_AUTH_DENIED, SSH_AUTH_ERROR, SSH_AUTH_METHOD_PUBLICKEY, SSH_AUTH_STATE_PUBKEY_OFFER_SENT, ssh_buffer_pack, ssh_buffer_reinit, SSH_ERROR, SSH_FATAL, ssh_key_algorithm_allowed, ssh_key_get_signature_algorithm, ssh_key_is_public, ssh_packet_send, SSH_PENDING_CALL_AUTH_OFFER_PUBKEY, SSH_PENDING_CALL_NONE, ssh_pki_export_pubkey_blob, SSH_REQUEST_DENIED, ssh_set_error, ssh_set_error_oom, SSH_STRING_FREE, ssh_userauth_get_response, ssh_userauth_request_service, ssh_session_struct::state, username, ssh_session_struct::username.
Referenced by auth_keyfile, ssh_userauth_agent, ssh_userauth_offer_pubkey, ssh_userauth_publickey_auto, torture_auth_cert, ssh::Session::userauthTryPublickey.
int ssh_userauth_publickey(ssh_session session, const char *username, const ssh_key privkey)
Authenticate with public/private key or certificate.
session The SSH session. username The username, this SHOULD be NULL. privkey The private key for authentication. SSH_AUTH_ERROR: A serious error happened. SSH_AUTH_DENIED: The server doesn't accept that public key as an authentication token. Try another key or another method. SSH_AUTH_PARTIAL: You've been partially authenticated, you still have to use another method. SSH_AUTH_SUCCESS: The public key is accepted. SSH_AUTH_AGAIN: In nonblocking mode, you've got to call this again later. Most server implementations do not permit changing the username during authentication. The username should only be set with ssh_options_set() only before you connect to the server.
References ssh_session_struct::auth, ssh_session_struct::current_method, ssh_session_struct::opts, ssh_session_struct::out_buffer, ssh_session_struct::pending_call_state, privkey, rc, session, SSH2_MSG_USERAUTH_REQUEST, SSH_AGAIN, SSH_AUTH_AGAIN, SSH_AUTH_DENIED, SSH_AUTH_ERROR, SSH_AUTH_METHOD_PUBLICKEY, SSH_AUTH_STATE_PUBKEY_AUTH_SENT, ssh_buffer_add_ssh_string, ssh_buffer_pack, ssh_buffer_reinit, SSH_ERROR, SSH_FATAL, ssh_key_algorithm_allowed, ssh_key_get_signature_algorithm, ssh_key_is_private, ssh_key_type_to_hash, ssh_packet_send, SSH_PENDING_CALL_AUTH_PUBKEY, SSH_PENDING_CALL_NONE, ssh_pki_do_sign, ssh_pki_export_pubkey_blob, SSH_REQUEST_DENIED, ssh_set_error, ssh_set_error_oom, SSH_STRING_FREE, ssh_userauth_get_response, ssh_userauth_request_service, ssh_session_struct::state, username, ssh_session_struct::username.
Referenced by auth_keyfile, ssh_userauth_pubkey, ssh_userauth_publickey_auto, torture_auth_cert, torture_auth_pubkey_types_ed25519, torture_auth_pubkey_types_ed25519_nonblocking, ssh::Session::userauthPublickey.
static int ssh_userauth_agent_publickey(ssh_session session, const char *username, ssh_key pubkey)
References ssh_session_struct::auth, ssh_session_struct::current_method, ssh_session_struct::opts, ssh_session_struct::out_buffer, ssh_session_struct::pending_call_state, pubkey, rc, session, SSH2_MSG_USERAUTH_REQUEST, SSH_AGAIN, SSH_AUTH_AGAIN, SSH_AUTH_DENIED, SSH_AUTH_ERROR, SSH_AUTH_METHOD_PUBLICKEY, SSH_AUTH_STATE_PUBKEY_AUTH_SENT, ssh_buffer_add_ssh_string, ssh_buffer_pack, ssh_buffer_reinit, SSH_ERROR, SSH_FATAL, ssh_key_algorithm_allowed, ssh_key_get_signature_algorithm, ssh_packet_send, SSH_PENDING_CALL_AUTH_AGENT, SSH_PENDING_CALL_NONE, ssh_pki_do_sign_agent, ssh_pki_export_pubkey_blob, SSH_REQUEST_DENIED, ssh_set_error, ssh_set_error_oom, SSH_STRING_FREE, ssh_userauth_get_response, ssh_userauth_request_service, ssh_session_struct::state, username, ssh_session_struct::username.
Referenced by ssh_userauth_agent, ssh_userauth_agent_pubkey.
void ssh_agent_state_free(void *data)
References ssh_key_free, SSH_STRING_FREE_CHAR, ssh_agent_state_struct::state.
Referenced by ssh_free, ssh_userauth_agent.
int ssh_userauth_agent(ssh_session session, const char *username)
Try to do public key authentication with ssh agent.
session The ssh session to use. username The username, this SHOULD be NULL. SSH_AUTH_ERROR: A serious error happened. SSH_AUTH_DENIED: The server doesn't accept that public key as an authentication token. Try another key or another method. SSH_AUTH_PARTIAL: You've been partially authenticated, you still have to use another method. SSH_AUTH_SUCCESS: The public key is accepted, you want now to use ssh_userauth_publickey(). SSH_AUTH_AGAIN: In nonblocking mode, you've got to call this again later. Most server implementations do not permit changing the username during authentication. The username should only be set with ssh_options_set() only before you connect to the server.
References ssh_session_struct::agent_state, rc, session, ssh_agent_get_first_ident, ssh_agent_get_next_ident, ssh_agent_is_running, SSH_AGENT_STATE_AUTH, ssh_agent_state_free, SSH_AGENT_STATE_NONE, SSH_AGENT_STATE_PUBKEY, SSH_AUTH_AGAIN, SSH_AUTH_DENIED, SSH_AUTH_ERROR, SSH_AUTH_PARTIAL, SSH_AUTH_SUCCESS, ssh_key_free, SSH_LOG, SSH_LOG_DEBUG, SSH_LOG_INFO, ssh_set_error_oom, SSH_STRING_FREE_CHAR, ssh_userauth_agent_publickey, ssh_userauth_try_publickey, ssh_agent_state_struct::state, username, ZERO_STRUCTP.
Referenced by ssh_userauth_publickey_auto, torture_auth_agent, torture_auth_agent_nonblocking.
int ssh_userauth_publickey_auto(ssh_session session, const char *username, const char *passphrase)
Tries to automatically authenticate with public key and "none".
It may fail, for instance it doesn't ask for a password and uses a default asker for passphrases (in case the private key is encrypted). session The SSH session. username The username, this SHOULD be NULL. passphrase Use this passphrase to unlock the privatekey. Use NULL if you don't want to use a passphrase or the user should be asked. SSH_AUTH_ERROR: A serious error happened. SSH_AUTH_DENIED: The server doesn't accept that public key as an authentication token. Try another key or another method. SSH_AUTH_PARTIAL: You've been partially authenticated, you still have to use another method. SSH_AUTH_SUCCESS: The public key is accepted, you want now to use ssh_userauth_publickey(). SSH_AUTH_AGAIN: In nonblocking mode, you've got to call this again later. Most server implementations do not permit changing the username during authentication. The username should only be set with ssh_options_set() only before you connect to the server.
References ssh_session_struct::auth, ssh_callbacks_struct::auth_function, ssh_session_struct::auto_state, ssh_common_struct::callbacks, ssh_session_struct::common, ssh_session_struct::flags, ssh_session_struct::identity, ssh_session_struct::opts, rc, SAFE_FREE, session, SSH_AUTH_AGAIN, SSH_AUTH_AUTO_STATE_KEY_IMPORTED, SSH_AUTH_AUTO_STATE_NONE, SSH_AUTH_AUTO_STATE_PUBKEY, SSH_AUTH_AUTO_STATE_PUBKEY_ACCEPTED, SSH_AUTH_DENIED, SSH_AUTH_ERROR, SSH_AUTH_METHOD_PUBLICKEY, SSH_AUTH_PARTIAL, SSH_AUTH_SUCCESS, SSH_EOF, SSH_ERROR, SSH_FATAL, ssh_key_free, ssh_list_get_iterator, SSH_LOG, SSH_LOG_DEBUG, SSH_LOG_INFO, SSH_LOG_WARN, SSH_OPT_FLAG_PUBKEY_AUTH, ssh_pki_export_privkey_to_pubkey, ssh_pki_export_pub_uri_from_priv_uri, ssh_pki_export_pubkey_file, ssh_pki_import_privkey_file, ssh_pki_import_pubkey_file, ssh_pki_is_uri, ssh_set_error, ssh_set_error_oom, ssh_userauth_agent, ssh_userauth_publickey, ssh_userauth_try_publickey, ssh_auth_auto_state_struct::state, ssh_session_struct::supported_methods, ssh_callbacks_struct::userdata, username.
Referenced by authenticate_console, ssh_userauth_autopubkey, torture_auth_autopubkey, torture_auth_autopubkey_nonblocking, torture_auth_pubkey_types, torture_auth_pubkey_types_ecdsa, torture_auth_pubkey_types_ecdsa_nonblocking, torture_auth_pubkey_types_nonblocking, torture_rekey_send, torture_rekey_server_send, torture_rekey_time, torture_server_auth_pubkey, torture_ssh_session, try_config_content, ssh::Session::userauthPublickeyAuto.
int ssh_userauth_password(ssh_session session, const char *username, const char *password)
Try to authenticate by password.
This authentication method is normally disabled on SSHv2 server. You should use keyboard-interactive mode. The 'password' value MUST be encoded UTF-8. It is up to the server how to interpret the password and validate it against the password database. However, if you read the password in some other encoding, you MUST convert the password to UTF-8. session The ssh session to use. username The username, this SHOULD be NULL. password The password to authenticate in UTF-8. SSH_AUTH_ERROR: A serious error happened. SSH_AUTH_DENIED: Authentication failed: use another method SSH_AUTH_PARTIAL: You've been partially authenticated, you still have to use another method SSH_AUTH_SUCCESS: Authentication success SSH_AUTH_AGAIN: In nonblocking mode, you've got to call this again later. Most server implementations do not permit changing the username during authentication. The username should only be set with ssh_options_set() only before you connect to the server. ssh_userauth_none() ssh_userauth_kbdint()
References ssh_session_struct::auth, ssh_session_struct::current_method, ssh_session_struct::opts, ssh_session_struct::out_buffer, ssh_session_struct::pending_call_state, rc, session, SSH2_MSG_USERAUTH_REQUEST, SSH_AGAIN, SSH_AUTH_AGAIN, SSH_AUTH_ERROR, SSH_AUTH_METHOD_PASSWORD, SSH_AUTH_STATE_PASSWORD_AUTH_SENT, ssh_buffer_pack, ssh_buffer_reinit, ssh_buffer_set_secure, SSH_ERROR, SSH_FATAL, ssh_packet_send, SSH_PENDING_CALL_AUTH_PASSWORD, SSH_PENDING_CALL_NONE, ssh_set_error, ssh_set_error_oom, ssh_userauth_get_response, ssh_userauth_request_service, ssh_session_struct::state, username, ssh_session_struct::username.
Referenced by authenticate, authenticate_console, torture_auth_password, torture_auth_password_nonblocking, torture_server_auth_password, torture_server_unknown_global_request, torture_ssh_session, ssh::Session::userauthPassword.
int ssh_userauth_agent_pubkey(ssh_session session, const char *username, ssh_public_key publickey)
References key, rc, session, SSH_AUTH_ERROR, SSH_KEY_FLAG_PUBLIC, ssh_key_free, ssh_key_new, ssh_key_type_to_char, ssh_userauth_agent_publickey, ssh_public_key_struct::type, username.
ssh_kbdint ssh_kbdint_new(void)
Referenced by ssh_message_auth_interactive_request, SSH_PACKET_CALLBACK.
void ssh_kbdint_free(ssh_kbdint kbd)
References ssh_kbdint_struct::answers, ssh_kbdint_struct::echo, explicit_bzero, ssh_kbdint_struct::instruction, ssh_kbdint_struct::name, ssh_kbdint_struct::nanswers, ssh_kbdint_struct::nprompts, ssh_kbdint_struct::prompts, SAFE_FREE.
Referenced by ssh_free, ssh_message_auth_interactive_request, SSH_PACKET_CALLBACK, ssh_userauth_kbdint_send.
void ssh_kbdint_clean(ssh_kbdint kbd)
References ssh_kbdint_struct::answers, ssh_kbdint_struct::echo, explicit_bzero, ssh_kbdint_struct::instruction, ssh_kbdint_struct::name, ssh_kbdint_struct::nanswers, ssh_kbdint_struct::nprompts, ssh_kbdint_struct::prompts, SAFE_FREE.
Referenced by ssh_message_auth_interactive_request, SSH_PACKET_CALLBACK.
static int ssh_userauth_kbdint_init(ssh_session session, const char *username, const char *submethods)
References ssh_session_struct::auth, ssh_session_struct::opts, ssh_session_struct::out_buffer, ssh_session_struct::pending_call_state, rc, session, SSH2_MSG_USERAUTH_REQUEST, SSH_AGAIN, SSH_AUTH_AGAIN, SSH_AUTH_ERROR, SSH_AUTH_STATE_KBDINT_SENT, ssh_buffer_pack, ssh_buffer_reinit, SSH_ERROR, SSH_LOG, SSH_LOG_DEBUG, SSH_OK, ssh_packet_send, SSH_PENDING_CALL_AUTH_KBDINT_INIT, SSH_PENDING_CALL_NONE, ssh_set_error_invalid, ssh_set_error_oom, ssh_userauth_get_response, ssh_userauth_request_service, ssh_session_struct::state, username, ssh_session_struct::username.
Referenced by ssh_userauth_kbdint.
static int ssh_userauth_kbdint_send(ssh_session session)
References ssh_kbdint_struct::answers, ssh_session_struct::auth, ssh_session_struct::current_method, ssh_session_struct::kbdint, ssh_kbdint_struct::nprompts, ssh_session_struct::out_buffer, ssh_session_struct::pending_call_state, rc, session, SSH2_MSG_USERAUTH_INFO_RESPONSE, SSH_AUTH_AGAIN, SSH_AUTH_ERROR, SSH_AUTH_METHOD_INTERACTIVE, SSH_AUTH_STATE_KBDINT_SENT, ssh_buffer_pack, ssh_buffer_reinit, SSH_ERROR, ssh_kbdint_free, SSH_LOG, SSH_LOG_DEBUG, ssh_packet_send, SSH_PENDING_CALL_AUTH_KBDINT_SEND, SSH_PENDING_CALL_NONE, ssh_set_error_invalid, ssh_set_error_oom, ssh_userauth_get_response, ssh_session_struct::state.
Referenced by ssh_userauth_kbdint.
SSH_PACKET_CALLBACK(ssh_packet_userauth_info_request)
References ssh_session_struct::auth, ssh_kbdint_struct::echo, ssh_kbdint_struct::instruction, ssh_session_struct::kbdint, KBDINT_MAX_PROMPT, ssh_kbdint_struct::name, ssh_kbdint_struct::nanswers, ssh_kbdint_struct::nprompts, ssh_kbdint_struct::prompts, rc, session, SSH_AUTH_STATE_INFO, ssh_buffer_unpack, SSH_ERROR, SSH_FATAL, ssh_kbdint_clean, ssh_kbdint_free, ssh_kbdint_new, SSH_LOG, SSH_LOG_DEBUG, SSH_OK, SSH_PACKET_USED, ssh_set_error, ssh_set_error_oom, SSH_STRING_FREE, ssh_session_struct::state, user.
int ssh_userauth_kbdint(ssh_session session, const char *user, const char *submethods)
Try to authenticate through the "keyboard-interactive" method.
session The ssh session to use. user The username to authenticate. You can specify NULL if ssh_option_set_username() has been used. You cannot try two different logins in a row. submethods Undocumented. Set it to NULL. SSH_AUTH_ERROR: A serious error happened SSH_AUTH_DENIED: Authentication failed : use another method SSH_AUTH_PARTIAL: You've been partially authenticated, you still have to use another method SSH_AUTH_SUCCESS: Authentication success SSH_AUTH_INFO: The server asked some questions. Use ssh_userauth_kbdint_getnprompts() and such. SSH_AUTH_AGAIN: In nonblocking mode, you've got to call this again later. ssh_userauth_kbdint_getnprompts() ssh_userauth_kbdint_getname() ssh_userauth_kbdint_getinstruction() ssh_userauth_kbdint_getprompt() ssh_userauth_kbdint_setanswer()
References ssh_session_struct::kbdint, ssh_session_struct::pending_call_state, rc, session, SSH_AUTH_ERROR, SSH_FATAL, SSH_PENDING_CALL_AUTH_KBDINT_INIT, SSH_PENDING_CALL_AUTH_KBDINT_SEND, SSH_PENDING_CALL_NONE, ssh_set_error, ssh_userauth_kbdint_init, ssh_userauth_kbdint_send, user.
Referenced by _torture_auth_kbdint, auth_kbdint, authenticate_kbdint, torture_auth_kbdint, torture_auth_kbdint_nonblocking, torture_server_auth_kbdint, ssh::Session::userauthKbdint.
int ssh_userauth_kbdint_getnprompts(ssh_session session)
Get the number of prompts (questions) the server has given.
Once you have called ssh_userauth_kbdint() and received SSH_AUTH_INFO return code, this function can be used to retrieve information about the keyboard interactive authentication questions sent by the remote host. session The ssh session to use. The number of prompts.
References ssh_session_struct::kbdint, ssh_kbdint_struct::nprompts, session, SSH_ERROR, ssh_set_error_invalid.
Referenced by _torture_auth_kbdint, auth_kbdint, authenticate_kbdint, torture_auth_kbdint, torture_auth_kbdint_nonblocking, torture_server_auth_kbdint, ssh::Session::userauthKbdintGetNPrompts.
const char* ssh_userauth_kbdint_getname(ssh_session session)
Get the "name" of the message block.
Once you have called ssh_userauth_kbdint() and received SSH_AUTH_INFO return code, this function can be used to retrieve information about the keyboard interactive authentication questions sent by the remote host. session The ssh session to use. The name of the message block. Do not free it.
References ssh_session_struct::kbdint, ssh_kbdint_struct::name, session, ssh_set_error_invalid.
Referenced by auth_kbdint, authenticate_kbdint.
const char* ssh_userauth_kbdint_getinstruction(ssh_session session)
Get the "instruction" of the message block.
Once you have called ssh_userauth_kbdint() and received SSH_AUTH_INFO return code, this function can be used to retrieve information about the keyboard interactive authentication questions sent by the remote host. session The ssh session to use. The instruction of the message block.
References ssh_kbdint_struct::instruction, ssh_session_struct::kbdint, session, ssh_set_error_invalid.
Referenced by auth_kbdint, authenticate_kbdint.
const char* ssh_userauth_kbdint_getprompt(ssh_session session, unsigned int i, char *echo)
Get a prompt from a message block.
Once you have called ssh_userauth_kbdint() and received SSH_AUTH_INFO return code, this function can be used to retrieve information about the keyboard interactive authentication questions sent by the remote host. session The ssh session to use. i The index number of the i'th prompt. echo This is an optional variable. You can obtain a boolean if the user input should be echoed or hidden. For passwords it is usually hidden. A pointer to the prompt. Do not free it. constcharprompt; charecho; prompt=ssh_userauth_kbdint_getprompt(session,0,&echo); if(echo)...
References echo, ssh_kbdint_struct::echo, ssh_session_struct::kbdint, ssh_kbdint_struct::nprompts, ssh_kbdint_struct::prompts, session, ssh_set_error_invalid.
Referenced by _torture_auth_kbdint, auth_kbdint, authenticate_kbdint.
int ssh_userauth_kbdint_setanswer(ssh_session session, unsigned int i, const char *answer)
Set the answer for a question from a message block.
If you have called ssh_userauth_kbdint() and got SSH_AUTH_INFO, this function returns the questions from the server. session The ssh session to use. i index The number of the ith prompt. answer The answer to give to the server. The answer MUST be encoded UTF-8. It is up to the server how to interpret the value and validate it. However, if you read the answer in some other encoding, you MUST convert it to UTF-8. 0 on success, < 0 on error.
References ssh_kbdint_struct::answers, explicit_bzero, ssh_session_struct::kbdint, ssh_kbdint_struct::nprompts, SAFE_FREE, session, ssh_set_error_invalid, ssh_set_error_oom.
Referenced by _torture_auth_kbdint, auth_kbdint, authenticate_kbdint, torture_auth_kbdint, torture_auth_kbdint_nonblocking, torture_server_auth_kbdint, ssh::Session::userauthKbdintSetAnswer.
int ssh_userauth_gssapi(ssh_session session)
Try to authenticate through the "gssapi-with-mic" method.
session The ssh session to use. SSH_AUTH_ERROR: A serious error happened SSH_AUTH_DENIED: Authentication failed : use another method SSH_AUTH_PARTIAL: You've been partially authenticated, you still have to use another method SSH_AUTH_SUCCESS: Authentication success SSH_AUTH_AGAIN: In nonblocking mode, you've got to call this again later.
Referenced by authenticate_console, main.