libssh_sftp
SSH_FX_OK
No error
SSH_FX_EOF
End-of-file encountered
SSH_FX_NO_SUCH_FILE
File doesn't exist
SSH_FX_PERMISSION_DENIED
Permission denied
SSH_FX_FAILURE
Generic failure
SSH_FX_BAD_MESSAGE
Garbage received from server
SSH_FX_NO_CONNECTION
No connection has been set up
SSH_FX_CONNECTION_LOST
There was a connection, but we lost it
SSH_FX_OP_UNSUPPORTED
Operation not supported by the server
SSH_FX_INVALID_HANDLE
Invalid file handle
SSH_FX_NO_SUCH_PATH
No such file or directory path exists
SSH_FX_FILE_ALREADY_EXISTS
An attempt to create an already existing file or directory has been made
SSH_FX_WRITE_PROTECT
We are trying to write on a write-protected filesystem
SSH_FX_NO_MEDIA
No media in remote drive
typedef struct sftp_attributes_struct* sftp_attributes
typedef struct sftp_client_message_struct* sftp_client_message
typedef struct sftp_dir_struct* sftp_dir
typedef struct sftp_ext_struct* sftp_ext
typedef struct sftp_file_struct* sftp_file
typedef struct sftp_message_struct* sftp_message
typedef struct sftp_packet_struct* sftp_packet
typedef struct sftp_request_queue_struct* sftp_request_queue
typedef struct sftp_session_struct* sftp_session
typedef struct sftp_status_message_struct* sftp_status_message
typedef struct sftp_statvfs_struct* sftp_statvfs_t
LIBSSH_API sftp_session sftp_new(ssh_session session)
Creates a new sftp session.
This function creates a new sftp session and allocates a new sftp channel with the server inside of the provided ssh session. This function call is usually followed by the sftp_init(), which initializes SFTP protocol itself. session The ssh session to use. A new sftp session or NULL on error. sftp_free() sftp_init()
Referenced by benchmarks_async_sftp_down, benchmarks_sync_sftp_down, benchmarks_sync_sftp_up, main, sftp_test.
LIBSSH_API sftp_session sftp_new_channel(ssh_session session, ssh_channel channel)
Start a new sftp session with an existing channel.
session The ssh session to use. channel An open session channel with subsystem already allocated A new sftp session or NULL on error. sftp_free()
LIBSSH_API void sftp_free(sftp_session sftp)
Close and deallocate a sftp session.
sftp The sftp session handle to free.
Referenced by benchmarks_async_sftp_down, benchmarks_sync_sftp_down, benchmarks_sync_sftp_up, sftp_test.
LIBSSH_API int sftp_init(sftp_session sftp)
Initialize the sftp protocol with the server.
This function involves the SFTP protocol initialization (as described in the SFTP specification), including the version and extensions negotiation. sftp The sftp session to initialize. 0 on success, < 0 on error with ssh error set. sftp_new()
Referenced by benchmarks_async_sftp_down, benchmarks_sync_sftp_down, benchmarks_sync_sftp_up, main, sftp_test.
LIBSSH_API int sftp_get_error(sftp_session sftp)
Get the last sftp error.
Use this function to get the latest error set by a posix like sftp function. sftp The sftp session where the error is saved. The saved error (see server responses), < 0 if an error in the function occured. Server responses
LIBSSH_API unsigned int sftp_extensions_get_count(sftp_session sftp)
Get the count of extensions provided by the server.
sftp The sftp session to use. The count of extensions provided by the server, 0 on error or not available.
LIBSSH_API const char* sftp_extensions_get_name(sftp_session sftp, unsigned int indexn)
Get the name of the extension provided by the server.
sftp The sftp session to use. indexn The index number of the extension name you want. The name of the extension.
LIBSSH_API const char* sftp_extensions_get_data(sftp_session sftp, unsigned int indexn)
Get the data of the extension provided by the server.
This is normally the version number of the extension. sftp The sftp session to use. indexn The index number of the extension data you want. The data of the extension.
LIBSSH_API int sftp_extension_supported(sftp_session sftp, const char *name, const char *data)
Check if the given extension is supported.
sftp The sftp session to use. name The name of the extension. data The data of the extension. 1 if supported, 0 if not. Example: sftp_extension_supported(sftp,"statvfs@openssh.com","2");
LIBSSH_API sftp_dir sftp_opendir(sftp_session session, const char *path)
Open a directory used to obtain directory entries.
session The sftp session handle to open the directory. path The path of the directory to open. A sftp directory handle or NULL on error with ssh and sftp error set. sftp_readdir sftp_closedir
LIBSSH_API sftp_attributes sftp_readdir(sftp_session session, sftp_dir dir)
Get a single file attributes structure of a directory.
session The sftp session handle to read the directory entry. dir The opened sftp directory handle to read from. A file attribute structure or NULL at the end of the directory. sftp_opendir() sftp_attribute_free() sftp_closedir()
LIBSSH_API int sftp_dir_eof(sftp_dir dir)
Tell if the directory has reached EOF (End Of File).
dir The sftp directory handle. 1 if the directory is EOF, 0 if not. sftp_readdir()
LIBSSH_API sftp_attributes sftp_stat(sftp_session session, const char *path)
Get information about a file or directory.
session The sftp session handle. path The path to the file or directory to obtain the information. The sftp attributes structure of the file or directory, NULL on error with ssh and sftp error set. sftp_get_error()
LIBSSH_API sftp_attributes sftp_lstat(sftp_session session, const char *path)
Get information about a file or directory.
Identical to sftp_stat, but if the file or directory is a symbolic link, then the link itself is stated, not the file that it refers to. session The sftp session handle. path The path to the file or directory to obtain the information. The sftp attributes structure of the file or directory, NULL on error with ssh and sftp error set. sftp_get_error()
LIBSSH_API sftp_attributes sftp_fstat(sftp_file file)
Get information about a file or directory from a file handle.
file The sftp file handle to get the stat information. The sftp attributes structure of the file or directory, NULL on error with ssh and sftp error set. sftp_get_error()
LIBSSH_API void sftp_attributes_free(sftp_attributes file)
Free a sftp attribute structure.
file The sftp attribute structure to free.
Referenced by sftp_client_message_free.
LIBSSH_API int sftp_closedir(sftp_dir dir)
Close a directory handle opened by sftp_opendir().
dir The sftp directory handle to close. Returns SSH_NO_ERROR or SSH_ERROR if an error occured.
LIBSSH_API int sftp_close(sftp_file file)
Close an open file handle.
file The open sftp file handle to close. Returns SSH_NO_ERROR or SSH_ERROR if an error occured. sftp_open()
Referenced by benchmarks_async_sftp_down, benchmarks_sync_sftp_down, benchmarks_sync_sftp_up, sftp_test, torture_sftp_benchmark_write_read, torture_sftp_fsync, torture_sftp_read_blocking.
LIBSSH_API sftp_file sftp_open(sftp_session session, const char *file, int accesstype, mode_t mode)
Open a file on the server.
session The sftp session handle. file The file to be opened. accesstype Is one of O_RDONLY, O_WRONLY or O_RDWR which request opening the file read-only,write-only or read/write. Acesss may also be bitwise-or'd with one or more of the following: O_CREAT - If the file does not exist it will be created. O_EXCL - When used with O_CREAT, if the file already exists it is an error and the open will fail. O_TRUNC - If the file already exists it will be truncated. mode Mode specifies the permissions to use if a new file is created. It is modified by the process's umask in the usual way: The permissions of the created file are (mode & ~umask) A sftp file handle, NULL on error with ssh and sftp error set. sftp_get_error()
Referenced by benchmarks_async_sftp_down, benchmarks_sync_sftp_down, benchmarks_sync_sftp_up, sftp_test, torture_sftp_benchmark_write_read, torture_sftp_fsync, torture_sftp_read_blocking.
LIBSSH_API void sftp_file_set_nonblocking(sftp_file handle)
Make the sftp communication for this file handle non blocking.
handle The file handle to set non blocking.
LIBSSH_API void sftp_file_set_blocking(sftp_file handle)
Make the sftp communication for this file handle blocking.
handle The file handle to set blocking.
LIBSSH_API ssize_t sftp_read(sftp_file file, void *buf, size_t count)
Read from a file using an opened sftp file handle.
file The opened sftp file handle to be read from. buf Pointer to buffer to recieve read data. count Size of the buffer in bytes. Number of bytes written, < 0 on error with ssh and sftp error set. sftp_get_error()
Referenced by benchmarks_sync_sftp_down, torture_sftp_benchmark_write_read, torture_sftp_read_blocking.
LIBSSH_API int sftp_async_read_begin(sftp_file file, uint32_t len)
Start an asynchronous read from a file using an opened sftp file handle.
Its goal is to avoid the slowdowns related to the request/response pattern of a synchronous read. To do so, you must call 2 functions: sftp_async_read_begin() and sftp_async_read(). The first step is to call sftp_async_read_begin(). This function returns a request identifier. The second step is to call sftp_async_read() using the returned identifier. file The opened sftp file handle to be read from. len Size to read in bytes. An identifier corresponding to the sent request, < 0 on error. When calling this function, the internal offset is updated corresponding to the len parameter. A call to sftp_async_read_begin() sends a request to the server. When the server answers, libssh allocates memory to store it until sftp_async_read() is called. Not calling sftp_async_read() will lead to memory leaks. sftp_async_read() sftp_open()
Referenced by benchmarks_async_sftp_down.
LIBSSH_API int sftp_async_read(sftp_file file, void *data, uint32_t len, uint32_t id)
Wait for an asynchronous read to complete and save the data.
file The opened sftp file handle to be read from. data Pointer to buffer to recieve read data. len Size of the buffer in bytes. It should be bigger or equal to the length parameter of the sftp_async_read_begin() call. id The identifier returned by the sftp_async_read_begin() function. Number of bytes read, 0 on EOF, SSH_ERROR if an error occured, SSH_AGAIN if the file is opened in nonblocking mode and the request hasn't been executed yet. A call to this function with an invalid identifier will never return. sftp_async_read_begin()
Referenced by benchmarks_async_sftp_down.
LIBSSH_API ssize_t sftp_write(sftp_file file, const void *buf, size_t count)
Write to a file using an opened sftp file handle.
file Open sftp file handle to write to. buf Pointer to buffer to write data. count Size of buffer in bytes. Number of bytes written, < 0 on error with ssh and sftp error set. sftp_open() sftp_read() sftp_close()
Referenced by benchmarks_sync_sftp_up, sftp_test, torture_sftp_benchmark_write_read, torture_sftp_fsync.
LIBSSH_API int sftp_seek(sftp_file file, uint32_t new_offset)
Seek to a specific location in a file.
file Open sftp file handle to seek in. new_offset Offset in bytes to seek. 0 on success, < 0 on error.
LIBSSH_API int sftp_seek64(sftp_file file, uint64_t new_offset)
Seek to a specific location in a file. This is the 64bit version.
file Open sftp file handle to seek in. new_offset Offset in bytes to seek. 0 on success, < 0 on error.
LIBSSH_API unsigned long sftp_tell(sftp_file file)
Report current byte position in file.
file Open sftp file handle. The offset of the current byte relative to the beginning of the file associated with the file descriptor. < 0 on error.
LIBSSH_API uint64_t sftp_tell64(sftp_file file)
Report current byte position in file.
file Open sftp file handle. The offset of the current byte relative to the beginning of the file associated with the file descriptor. < 0 on error.
LIBSSH_API void sftp_rewind(sftp_file file)
Rewinds the position of the file pointer to the beginning of the file.
file Open sftp file handle.
LIBSSH_API int sftp_unlink(sftp_session sftp, const char *file)
Unlink (delete) a file.
sftp The sftp session handle. file The file to unlink/delete. 0 on success, < 0 on error with ssh and sftp error set. sftp_get_error()
LIBSSH_API int sftp_rmdir(sftp_session sftp, const char *directory)
Remove a directoy.
sftp The sftp session handle. directory The directory to remove. 0 on success, < 0 on error with ssh and sftp error set. sftp_get_error()
Referenced by torture_sftp_mkdir.
LIBSSH_API int sftp_mkdir(sftp_session sftp, const char *directory, mode_t mode)
Create a directory.
sftp The sftp session handle. directory The directory to create. mode Specifies the permissions to use. It is modified by the process's umask in the usual way: The permissions of the created file are (mode & ~umask) 0 on success, < 0 on error with ssh and sftp error set. sftp_get_error()
Referenced by torture_sftp_mkdir.
LIBSSH_API int sftp_rename(sftp_session sftp, const char *original, const char *newname)
Rename or move a file or directory.
sftp The sftp session handle. original The original url (source url) of file or directory to be moved. newname The new url (destination url) of the file or directory after the move. 0 on success, < 0 on error with ssh and sftp error set. sftp_get_error()
Referenced by main.
LIBSSH_API int sftp_setstat(sftp_session sftp, const char *file, sftp_attributes attr)
Set file attributes on a file, directory or symbolic link.
sftp The sftp session handle. file The file which attributes should be changed. attr The file attributes structure with the attributes set which should be changed. 0 on success, < 0 on error with ssh and sftp error set. sftp_get_error()
LIBSSH_API int sftp_chown(sftp_session sftp, const char *file, uid_t owner, gid_t group)
Change the file owner and group.
sftp The sftp session handle. file The file which owner and group should be changed. owner The new owner which should be set. group The new group which should be set. 0 on success, < 0 on error with ssh and sftp error set. sftp_get_error()
LIBSSH_API int sftp_chmod(sftp_session sftp, const char *file, mode_t mode)
Change permissions of a file.
sftp The sftp session handle. file The file which owner and group should be changed. mode Specifies the permissions to use. It is modified by the process's umask in the usual way: The permissions of the created file are (mode & ~umask) 0 on success, < 0 on error with ssh and sftp error set. sftp_get_error()
Referenced by main.
LIBSSH_API int sftp_utimes(sftp_session sftp, const char *file, const struct timeval *times)
Change the last modification and access time of a file.
sftp The sftp session handle. file The file which owner and group should be changed. times A timeval structure which contains the desired access and modification time. 0 on success, < 0 on error with ssh and sftp error set. sftp_get_error()
LIBSSH_API int sftp_symlink(sftp_session sftp, const char *target, const char *dest)
Create a symbolic link.
sftp The sftp session handle. target Specifies the target of the symlink. dest Specifies the path name of the symlink to be created. 0 on success, < 0 on error with ssh and sftp error set. sftp_get_error()
LIBSSH_API char* sftp_readlink(sftp_session sftp, const char *path)
Read the value of a symbolic link.
sftp The sftp session handle. path Specifies the path name of the symlink to be read. The target of the link, NULL on error. sftp_get_error()
LIBSSH_API sftp_statvfs_t sftp_statvfs(sftp_session sftp, const char *path)
Get information about a mounted file system.
sftp The sftp session handle. path The pathname of any file within the mounted file system. A statvfs structure or NULL on error. sftp_get_error()
LIBSSH_API sftp_statvfs_t sftp_fstatvfs(sftp_file file)
Get information about a mounted file system.
file An opened file. A statvfs structure or NULL on error. sftp_get_error()
LIBSSH_API void sftp_statvfs_free(sftp_statvfs_t statvfs_o)
Free the memory of an allocated statvfs.
statvfs_o The statvfs to free.
LIBSSH_API int sftp_fsync(sftp_file file)
Synchronize a file's in-core state with storage device.
This calls the "fsync@openssh.com" extention. You should check if the extensions is supported using: intsupported=sftp_extension_supported(sftp,"fsync@openssh.com","1"); file The opened sftp file handle to sync 0 on success, < 0 on error with ssh and sftp error set.
Referenced by torture_sftp_fsync.
LIBSSH_API char* sftp_canonicalize_path(sftp_session sftp, const char *path)
Canonicalize a sftp path.
sftp The sftp session handle. path The path to be canonicalized. A pointer to the newly allocated canonicalized path, NULL on error. The caller needs to free the memory using ssh_string_free_char().
Referenced by torture_sftp_canonicalize_path.
LIBSSH_API int sftp_server_version(sftp_session sftp)
Get the version of the SFTP protocol supported by the server.
sftp The sftp session handle. The server version.
LIBSSH_API sftp_client_message sftp_get_client_message(sftp_session sftp)
References sftp_client_message_struct::attr, sftp_client_message_struct::complete_message, sftp_client_message_struct::data, sftp_client_message_struct::filename, sftp_client_message_struct::flags, sftp_client_message_struct::handle, sftp_client_message_struct::id, sftp_client_message_struct::len, sftp_client_message_struct::offset, sftp_packet_struct::payload, rc, sftp_session_struct::session, session, sftp_client_message_struct::sftp, sftp_client_message_free, sftp_packet_read, sftp_parse_attr, ssh_buffer_add_data, ssh_buffer_get, ssh_buffer_get_len, ssh_buffer_get_ssh_string, ssh_buffer_get_u32, ssh_buffer_new, ssh_buffer_unpack, SSH_FATAL, SSH_FXP_CLOSE, SSH_FXP_EXTENDED, SSH_FXP_FSETSTAT, SSH_FXP_FSTAT, SSH_FXP_LSTAT, SSH_FXP_MKDIR, SSH_FXP_OPEN, SSH_FXP_OPENDIR, SSH_FXP_READ, SSH_FXP_READDIR, SSH_FXP_READLINK, SSH_FXP_REALPATH, SSH_FXP_REMOVE, SSH_FXP_RENAME, SSH_FXP_RMDIR, SSH_FXP_SETSTAT, SSH_FXP_STAT, SSH_FXP_SYMLINK, SSH_FXP_WRITE, SSH_OK, ssh_set_error, ssh_set_error_oom, sftp_client_message_struct::submessage, sftp_packet_struct::type, sftp_client_message_struct::type, sftp_session_struct::version, ZERO_STRUCTP.
LIBSSH_API void sftp_client_message_free(sftp_client_message msg)
References sftp_client_message_struct::attr, sftp_client_message_struct::complete_message, sftp_client_message_struct::data, sftp_client_message_struct::filename, sftp_client_message_struct::handle, SAFE_FREE, sftp_attributes_free, SSH_BUFFER_FREE, SSH_STRING_FREE, sftp_client_message_struct::str_data, sftp_client_message_struct::submessage, ZERO_STRUCTP.
Referenced by sftp_get_client_message.
LIBSSH_API uint8_t sftp_client_message_get_type(sftp_client_message msg)
References sftp_client_message_struct::type.
LIBSSH_API const char* sftp_client_message_get_filename(sftp_client_message msg)
References sftp_client_message_struct::filename.
LIBSSH_API void sftp_client_message_set_filename(sftp_client_message msg, const char *newname)
References sftp_client_message_struct::filename.
LIBSSH_API const char* sftp_client_message_get_data(sftp_client_message msg)
References sftp_client_message_struct::data, ssh_string_to_char, sftp_client_message_struct::str_data.
LIBSSH_API uint32_t sftp_client_message_get_flags(sftp_client_message msg)
References sftp_client_message_struct::flags.
LIBSSH_API const char* sftp_client_message_get_submessage(sftp_client_message msg)
References sftp_client_message_struct::submessage.
LIBSSH_API int sftp_send_client_message(sftp_session sftp, sftp_client_message msg)
References sftp_client_message_struct::complete_message, sftp_packet_write, sftp_client_message_struct::type.
LIBSSH_API int sftp_reply_name(sftp_client_message msg, const char *name, sftp_attributes attr)
References buffer_add_attributes, sftp_client_message_struct::id, name, sftp_client_message_struct::sftp, sftp_packet_write, ssh_buffer_add_ssh_string, ssh_buffer_add_u32, SSH_BUFFER_FREE, ssh_buffer_new, SSH_FXP_NAME, SSH_STRING_FREE, ssh_string_from_char.
LIBSSH_API int sftp_reply_handle(sftp_client_message msg, ssh_string handle)
References sftp_client_message_struct::id, sftp_client_message_struct::sftp, sftp_packet_write, ssh_buffer_add_ssh_string, ssh_buffer_add_u32, SSH_BUFFER_FREE, ssh_buffer_new, SSH_FXP_HANDLE.
LIBSSH_API ssh_string sftp_handle_alloc(sftp_session sftp, void *info)
References sftp_session_struct::handles, SFTP_HANDLES, ssh_string_data, ssh_string_new.
LIBSSH_API int sftp_reply_attr(sftp_client_message msg, sftp_attributes attr)
References buffer_add_attributes, sftp_client_message_struct::id, sftp_client_message_struct::sftp, sftp_packet_write, ssh_buffer_add_u32, SSH_BUFFER_FREE, ssh_buffer_new, SSH_FXP_ATTRS.
LIBSSH_API void* sftp_handle(sftp_session sftp, ssh_string handle)
References sftp_session_struct::handles, SFTP_HANDLES, ssh_string_data, ssh_string_len.
LIBSSH_API int sftp_reply_status(sftp_client_message msg, uint32_t status, const char *message)
References sftp_client_message_struct::id, s, sftp_client_message_struct::sftp, sftp_packet_write, ssh_buffer_add_ssh_string, ssh_buffer_add_u32, SSH_BUFFER_FREE, ssh_buffer_new, SSH_FXP_STATUS, SSH_STRING_FREE, ssh_string_from_char.
LIBSSH_API int sftp_reply_names_add(sftp_client_message msg, const char *file, const char *longname, sftp_attributes attr)
References sftp_client_message_struct::attr_num, sftp_client_message_struct::attrbuf, buffer_add_attributes, name, ssh_buffer_add_ssh_string, ssh_buffer_new, SSH_STRING_FREE, ssh_string_from_char.
LIBSSH_API int sftp_reply_names(sftp_client_message msg)
References sftp_client_message_struct::attr_num, sftp_client_message_struct::attrbuf, sftp_client_message_struct::id, sftp_client_message_struct::sftp, sftp_packet_write, ssh_buffer_add_data, ssh_buffer_add_u32, SSH_BUFFER_FREE, ssh_buffer_get, ssh_buffer_get_len, ssh_buffer_new, SSH_FXP_NAME.
LIBSSH_API int sftp_reply_data(sftp_client_message msg, const void *data, int len)
References sftp_client_message_struct::id, sftp_client_message_struct::sftp, sftp_packet_write, ssh_buffer_add_data, ssh_buffer_add_u32, SSH_BUFFER_FREE, ssh_buffer_new, SSH_FXP_DATA.
LIBSSH_API void sftp_handle_remove(sftp_session sftp, void *handle)
References sftp_session_struct::handles, SFTP_HANDLES.
LIBSFTP_VERSION
SSH_FXP_INIT
SSH_FXP_VERSION
SSH_FXP_OPEN
SSH_FXP_CLOSE
SSH_FXP_READ
SSH_FXP_WRITE
SSH_FXP_LSTAT
SSH_FXP_FSTAT
SSH_FXP_SETSTAT
SSH_FXP_FSETSTAT
SSH_FXP_OPENDIR
SSH_FXP_READDIR
SSH_FXP_REMOVE
SSH_FXP_MKDIR
SSH_FXP_RMDIR
SSH_FXP_REALPATH
SSH_FXP_STAT
SSH_FXP_RENAME
SSH_FXP_READLINK
SSH_FXP_SYMLINK
SSH_FXP_STATUS
SSH_FXP_HANDLE
SSH_FXP_DATA
SSH_FXP_NAME
SSH_FXP_ATTRS
SSH_FXP_EXTENDED
SSH_FXP_EXTENDED_REPLY
SSH_FILEXFER_ATTR_SIZE
SSH_FILEXFER_ATTR_PERMISSIONS
SSH_FILEXFER_ATTR_ACCESSTIME
SSH_FILEXFER_ATTR_ACMODTIME
SSH_FILEXFER_ATTR_CREATETIME
SSH_FILEXFER_ATTR_MODIFYTIME
SSH_FILEXFER_ATTR_ACL
SSH_FILEXFER_ATTR_OWNERGROUP
SSH_FILEXFER_ATTR_SUBSECOND_TIMES
SSH_FILEXFER_ATTR_EXTENDED
SSH_FILEXFER_ATTR_UIDGID
SSH_FILEXFER_TYPE_REGULAR
SSH_FILEXFER_TYPE_DIRECTORY
SSH_FILEXFER_TYPE_SYMLINK
SSH_FILEXFER_TYPE_SPECIAL
SSH_FILEXFER_TYPE_UNKNOWN
SSH_FXF_READ
SSH_FXF_WRITE
SSH_FXF_APPEND
SSH_FXF_CREAT
SSH_FXF_TRUNC
SSH_FXF_EXCL
SSH_FXF_TEXT
SSH_S_IFMT
SSH_S_IFSOCK
SSH_S_IFLNK
SSH_S_IFREG
SSH_S_IFBLK
SSH_S_IFDIR
SSH_S_IFCHR
SSH_S_IFIFO
SSH_FXF_RENAME_OVERWRITE
SSH_FXF_RENAME_ATOMIC
SSH_FXF_RENAME_NATIVE
SFTP_OPEN
SFTP_CLOSE
SFTP_READ
SFTP_WRITE
SFTP_LSTAT
SFTP_FSTAT
SFTP_SETSTAT
SFTP_FSETSTAT
SFTP_OPENDIR
SFTP_READDIR
SFTP_REMOVE
SFTP_MKDIR
SFTP_RMDIR
SFTP_REALPATH
SFTP_STAT
SFTP_RENAME
SFTP_READLINK
SFTP_SYMLINK
SFTP_EXTENDED
SSH_FXE_STATVFS_ST_RDONLY
SSH_FXE_STATVFS_ST_NOSUID