gzip.c
BLOCKSIZE
static z_stream* initcompress(ssh_session session, int level)
References SAFE_FREE, session, SSH_FATAL, ssh_set_error.
Referenced by gzip_compress.
static ssh_buffer gzip_compress(ssh_session session, ssh_buffer source, int level)
References BLOCKSIZE, ssh_crypto_struct::compress_out_ctx, initcompress, session, ssh_buffer_add_data, SSH_BUFFER_FREE, ssh_buffer_get, ssh_buffer_get_len, ssh_buffer_new, SSH_DIRECTION_OUT, SSH_FATAL, ssh_packet_get_current_crypto, ssh_set_error.
Referenced by compress_buffer.
int compress_buffer(ssh_session session, ssh_buffer buf)
References ssh_session_struct::compressionlevel, gzip_compress, ssh_session_struct::opts, session, ssh_buffer_add_data, SSH_BUFFER_FREE, ssh_buffer_get, ssh_buffer_get_len, ssh_buffer_reinit.
Referenced by packet_send2.
static z_stream* initdecompress(ssh_session session)
References SAFE_FREE, session, SSH_FATAL, ssh_set_error.
Referenced by gzip_decompress.
static ssh_buffer gzip_decompress(ssh_session session, ssh_buffer source, size_t maxlen)
References BLOCKSIZE, ssh_crypto_struct::compress_in_ctx, initdecompress, session, ssh_buffer_add_data, SSH_BUFFER_FREE, ssh_buffer_get, ssh_buffer_get_len, ssh_buffer_new, SSH_DIRECTION_IN, SSH_FATAL, ssh_packet_get_current_crypto, ssh_set_error.
Referenced by decompress_buffer.
int decompress_buffer(ssh_session session, ssh_buffer buf, size_t maxlen)
References gzip_decompress, session, ssh_buffer_add_data, SSH_BUFFER_FREE, ssh_buffer_get, ssh_buffer_get_len, ssh_buffer_reinit.
Referenced by ssh_packet_socket_callback.