init.c
CONSTRUCTOR_ATTRIBUTE
DESTRUCTOR_ATTRIBUTE
SSH_MUTEX ssh_init_mutex
Referenced by _ssh_finalize, libssh_constructor.
int _ssh_initialized
Referenced by _ssh_finalize, libssh_constructor.
int _ssh_init_ret
Referenced by _ssh_finalize, libssh_constructor.
void libssh_constructor(void)
Initialize global cryptographic data structures.
This functions is automatically called when the library is loaded.
References _ssh_init_ret, _ssh_initialized, rc, ssh_crypto_init, ssh_dh_init, ssh_init_mutex, ssh_mutex_lock, ssh_mutex_unlock, ssh_socket_init, ssh_threads_init.
int ssh_init(void)
Initialize global cryptographic data structures.
Since version 0.8.0, it is not necessary to call this function on systems which are fully supported with regards to threading (that is, system with pthreads available). If the library is already initialized, increments the _ssh_initialized counter and return the error code cached in _ssh_init_ret. SSH_OK on success, SSH_ERROR if an error occurred.
Referenced by LLVMFuzzerTestOneInput, main, setup, thread_ssh_init, torture_run_tests, torture_ssh_init, torture_ssh_init_after_finalize.
static int _ssh_finalize(unsigned destructor)
References _ssh_init_ret, _ssh_initialized, ssh_crypto_finalize, ssh_dh_finalize, ssh_init_mutex, ssh_mutex_lock, ssh_mutex_unlock, ssh_socket_cleanup, ssh_threads_finalize.
Referenced by libssh_destructor, ssh_finalize.
void libssh_destructor(void)
Finalize and cleanup all libssh and cryptographic data structures.
This function is automatically called when the library is unloaded.
References _ssh_finalize, rc.
int ssh_finalize(void)
Finalize and cleanup all libssh and cryptographic data structures.
Since version 0.8.0, it is not necessary to call this function, since it is automatically called when the library is unloaded. If ssh_init() is called explicitly, then ssh_finalize() must be called explicitly. When called, decrements the counter _ssh_initialized. If the counter reaches zero, then the libssh and cryptographic data structures are cleaned up. 0 on succes, -1 if an error occured. 0 otherwise
References _ssh_finalize.
Referenced by connect_host, LLVMFuzzerTestOneInput, main, teardown, thread_ssh_init, torture_run_tests, torture_ssh_init, torture_ssh_init_after_finalize.