knownhosts.h
struct ssh_list* ssh_known_hosts_get_algorithms(ssh_session session)
References error, ssh_session_struct::global_knownhosts, ssh_session_struct::knownhosts, ssh_iterator::next, ssh_session_struct::opts, ssh_knownhosts_entry::publickey, rc, SAFE_FREE, session, ssh_iterator_value, ssh_known_hosts_read_entries, ssh_knownhosts_entry_free, ssh_list_append, ssh_list_count, ssh_list_free, ssh_list_get_iterator, ssh_list_new, ssh_list_remove, SSH_OK, ssh_options_apply, SSH_REQUEST_DENIED, ssh_session_get_host_port, ssh_set_error, ssh_key_struct::type_c.
Referenced by torture_knownhosts_duplicate, torture_knownhosts_precheck.
char* ssh_known_hosts_get_algorithms_names(ssh_session session)
References ssh_session_struct::global_knownhosts, ssh_session_struct::knownhosts, ssh_session_struct::opts, ssh_knownhosts_entry::publickey, rc, SAFE_FREE, session, ssh_iterator_value, ssh_known_host_sigs_from_hostkey_type, ssh_known_hosts_read_entries, ssh_knownhosts_entry_free, ssh_list_count, ssh_list_free, ssh_list_get_iterator, ssh_list_remove, ssh_options_apply, ssh_remove_duplicates, SSH_REQUEST_DENIED, ssh_session_get_host_port, ssh_set_error, ssh_key_struct::type.
Referenced by ssh_client_select_hostkeys, torture_knownhosts_get_algorithms_names.
enum ssh_known_hosts_e ssh_session_get_known_hosts_entry_file(ssh_session session, const char *filename, struct ssh_knownhosts_entry **pentry)
Get the known_hosts entry for the current connected session from the given known_hosts file.
session The session to validate. filename The filename to parse. pentry A pointer to store the allocated known hosts entry. SSH_KNOWN_HOSTS_OK: The server is known and has not changed. SSH_KNOWN_HOSTS_CHANGED: The server key has changed. Either you are under attack or the administrator changed the key. You HAVE to warn the user about a possible attack. SSH_KNOWN_HOSTS_OTHER: The server gave use a key of a type while we had an other type recorded. It is a possible attack. SSH_KNOWN_HOSTS_UNKNOWN: The server is unknown. User should confirm the public key hash is correct. SSH_KNOWN_HOSTS_NOT_FOUND: The known host file does not exist. The host is thus unknown. File will be created if host key is accepted. SSH_KNOWN_HOSTS_ERROR: There had been an eror checking the host. ssh_knownhosts_entry_free()