known_hosts.c
KNOWNHOSTS_MAXTYPES
static struct ssh_tokens_st* ssh_get_knownhost_line(FILE **file, const char *filename, const char **found_type)
References buffer, ssh_tokenize, ssh_tokens_free, ssh_tokens_st::tokens.
Referenced by ssh_is_server_known.
static int check_public_key(ssh_session session, char **tokens)
References base64_to_bin, rc, session, ssh_buffer_free, ssh_buffer_get, ssh_buffer_get_len, ssh_dh_get_current_server_publickey_blob, SSH_FATAL, ssh_set_error, ssh_string_data, ssh_string_free, ssh_string_len, ssh_tokens_st::tokens.
Referenced by ssh_is_server_known.
static int match_hashed_host(const char *host, const char *sourcehash)
References base64_to_bin, buffer, hmac_final, hmac_init, hmac_update, host, mac, SAFE_FREE, ssh_buffer_free, ssh_buffer_get, ssh_buffer_get_len, SSH_HMAC_SHA1, SSH_LOG, SSH_LOG_PACKET.
Referenced by ssh_is_server_known.
int ssh_is_server_known(ssh_session session)
This function is deprecated.
DeprecatedPlease use ssh_session_is_known_server() ssh_session_is_known_server()
References check_public_key, ssh_session_struct::current_crypto, ssh_session_struct::global_knownhosts, host, ssh_session_struct::host, ssh_session_struct::knownhosts, match_hashed_host, match_hostname, ssh_session_struct::opts, ssh_session_struct::port, pubkey, SAFE_FREE, session, ssh_dh_get_current_server_publickey, SSH_FATAL, ssh_get_knownhost_line, ssh_hostport, ssh_key_type, ssh_key_type_to_char, SSH_LOG, SSH_LOG_PACKET, ssh_lowercase, SSH_OK, ssh_options_apply, SSH_REQUEST_DENIED, SSH_SERVER_ERROR, SSH_SERVER_FILE_NOT_FOUND, SSH_SERVER_FOUND_OTHER, SSH_SERVER_KNOWN_CHANGED, SSH_SERVER_KNOWN_OK, SSH_SERVER_NOT_KNOWN, ssh_session_update_known_hosts, ssh_set_error, ssh_set_error_oom, ssh_tokens_free, ssh_session_struct::StrictHostKeyChecking, ssh_tokens_st::tokens.
Referenced by torture_knownhosts_conflict, torture_knownhosts_fail, torture_knownhosts_other, torture_knownhosts_other_auto, torture_knownhosts_port, torture_knownhosts_standard_port, torture_knownhosts_wildcard.
char* ssh_dump_knownhost(ssh_session session)
This function is deprecated.
DeprecatedPlease use ssh_session_export_known_hosts_entry()
References buffer, ssh_session_struct::current_crypto, host, ssh_session_struct::host, ssh_session_struct::opts, ssh_session_struct::port, rc, SAFE_FREE, session, ssh_dh_get_current_server_publickey, SSH_FATAL, ssh_hostport, ssh_lowercase, ssh_pki_export_pubkey_base64, ssh_set_error, ssh_key_struct::type_c.
int ssh_write_knownhost(ssh_session session)
This function is deprecated.
DeprecatedPlease use ssh_session_update_known_hosts()
References buffer, ssh_session_struct::knownhosts, ssh_session_struct::opts, rc, SAFE_FREE, session, ssh_dirname, SSH_ERROR, SSH_FATAL, ssh_mkdirs, SSH_OK, ssh_options_apply, ssh_session_export_known_hosts_entry, ssh_set_error.
Referenced by torture_knownhosts_conflict, torture_knownhosts_other_auto, torture_knownhosts_port.