latency.c
PING_PROGRAM
int benchmarks_ping_latency(const char *host, float *average)
References host, PING_PROGRAM.
Referenced by do_benchmarks.
void timestamp_init(struct timestamp_struct *ts)
References timestamp_struct::timestamp.
Referenced by benchmarks_async_sftp_down, benchmarks_raw_down, benchmarks_raw_up, benchmarks_scp_down, benchmarks_scp_up, benchmarks_ssh_latency, benchmarks_sync_sftp_down, benchmarks_sync_sftp_up.
float elapsed_time(struct timestamp_struct *ts)
References timestamp_struct::timestamp.
Referenced by benchmarks_async_sftp_down, benchmarks_raw_down, benchmarks_raw_up, benchmarks_scp_down, benchmarks_scp_up, benchmarks_ssh_latency, benchmarks_sync_sftp_down, benchmarks_sync_sftp_up.
int benchmarks_ssh_latency(ssh_session session, float *average)
References elapsed_time, error, session, ssh_channel_close, ssh_channel_free, ssh_channel_new, ssh_channel_open_session, ssh_channel_request_env, SSH_ERROR, SSH_FATAL, ssh_get_error, ssh_get_error_code, timestamp_init.
Referenced by do_benchmarks.