libcrypto-compat.c
static void* OPENSSL_zalloc(size_t num)
Referenced by EVP_CIPHER_CTX_new, EVP_MD_CTX_new, HMAC_CTX_new.
int RSA_set0_key(RSA *r, BIGNUM *n, BIGNUM *e, BIGNUM *d)
Referenced by pki_key_dup, pki_privkey_build_rsa, pki_pubkey_build_rsa.
int RSA_set0_factors(RSA *r, BIGNUM *p, BIGNUM *q)
Referenced by pki_key_dup, pki_privkey_build_rsa.
int RSA_set0_crt_params(RSA *r, BIGNUM *dmp1, BIGNUM *dmq1, BIGNUM *iqmp)
Referenced by pki_key_dup.
void RSA_get0_key(const RSA *r, const BIGNUM **n, const BIGNUM **e, const BIGNUM **d)
Referenced by pki_key_compare, pki_key_dup, pki_publickey_to_blob.
void RSA_get0_factors(const RSA *r, const BIGNUM **p, const BIGNUM **q)
Referenced by pki_key_compare, pki_key_dup.
void RSA_get0_crt_params(const RSA *r, const BIGNUM **dmp1, const BIGNUM **dmq1, const BIGNUM **iqmp)
Referenced by pki_key_dup.
void DSA_get0_pqg(const DSA *d, const BIGNUM **p, const BIGNUM **q, const BIGNUM **g)
Referenced by pki_key_compare, pki_key_dup, pki_publickey_to_blob.
int DSA_set0_pqg(DSA *d, BIGNUM *p, BIGNUM *q, BIGNUM *g)
Referenced by pki_key_dup, pki_privkey_build_dss, pki_pubkey_build_dss.
void DSA_get0_key(const DSA *d, const BIGNUM **pub_key, const BIGNUM **priv_key)
Referenced by pki_key_compare, pki_key_dup, pki_publickey_to_blob.
int DSA_set0_key(DSA *d, BIGNUM *pub_key, BIGNUM *priv_key)
Referenced by pki_key_dup, pki_privkey_build_dss, pki_pubkey_build_dss.
void DSA_SIG_get0(const DSA_SIG *sig, const BIGNUM **pr, const BIGNUM **ps)
Referenced by pki_dsa_signature_to_blob.
int DSA_SIG_set0(DSA_SIG *sig, BIGNUM *r, BIGNUM *s)
References s.
Referenced by pki_signature_from_dsa_blob.
void ECDSA_SIG_get0(const ECDSA_SIG *sig, const BIGNUM **pr, const BIGNUM **ps)
Referenced by pki_ecdsa_signature_to_blob.
int ECDSA_SIG_set0(ECDSA_SIG *sig, BIGNUM *r, BIGNUM *s)
References s.
Referenced by pki_signature_from_ecdsa_blob.
EVP_MD_CTX* EVP_MD_CTX_new(void)
References OPENSSL_zalloc.
static void OPENSSL_clear_free(void *str, size_t num)
Referenced by EVP_MD_CTX_reset.
int EVP_MD_CTX_reset(EVP_MD_CTX *ctx)
References ctx, OPENSSL_clear_free.
Referenced by EVP_MD_CTX_free, hmac_ctx_cleanup.
void EVP_MD_CTX_free(EVP_MD_CTX *ctx)
References ctx, EVP_MD_CTX_reset.
Referenced by HMAC_CTX_free, pki_sign_data, pki_verify_data_signature.
HMAC_CTX* HMAC_CTX_new(void)
References ctx, HMAC_CTX_free, HMAC_CTX_reset, OPENSSL_zalloc.
static void hmac_ctx_cleanup(HMAC_CTX *ctx)
References ctx, EVP_MD_CTX_reset.
Referenced by HMAC_CTX_free.
void HMAC_CTX_free(HMAC_CTX *ctx)
References ctx, EVP_MD_CTX_free, hmac_ctx_cleanup.
Referenced by HMAC_CTX_new.
int HMAC_CTX_reset(HMAC_CTX *ctx)
References ctx.
Referenced by HMAC_CTX_new.
EVP_CIPHER_CTX* EVP_CIPHER_CTX_new(void)
References OPENSSL_zalloc.
void EVP_CIPHER_CTX_free(EVP_CIPHER_CTX *ctx)
References ctx.
void DH_get0_pqg(const DH *dh, const BIGNUM **p, const BIGNUM **q, const BIGNUM **g)
Referenced by ssh_dh_get_parameters.
int DH_set0_pqg(DH *dh, BIGNUM *p, BIGNUM *q, BIGNUM *g)
Referenced by ssh_dh_set_parameters.
void DH_get0_key(const DH *dh, const BIGNUM **pub_key, const BIGNUM **priv_key)
Referenced by ssh_dh_keypair_get_keys.
int DH_set0_key(DH *dh, BIGNUM *pub_key, BIGNUM *priv_key)
Referenced by ssh_dh_keypair_set_keys.