match.c
MAX_MATCH_RECURSION
static int match_pattern(const char *s, const char *pattern, size_t limit)
References pattern, s.
Referenced by match_pattern_list, torture_config_match_pattern.
int match_pattern_list(const char *string, const char *pattern, unsigned int len, int dolower)
References match_pattern, MAX_MATCH_RECURSION, pattern, sub.
Referenced by match_hostname, ssh_config_match.
int match_hostname(const char *host, const char *pattern, unsigned int len)
References host, match_pattern_list, pattern.
Referenced by ssh_config_parse_line, ssh_is_server_known, ssh_known_hosts_parse_line.