options.h
int ssh_config_parse_file(ssh_session session, const char *filename)
References MAX_LINE_SIZE, session, ssh_config_parse_line, SSH_LOG, SSH_LOG_PACKET.
Referenced by ssh_options_parse_config, torture_config_auth_methods, torture_config_double_ports, torture_config_from_file, torture_config_glob, torture_config_match, torture_config_new, torture_config_proxyjump, torture_config_pubkeyacceptedkeytypes, torture_config_rekey, torture_config_unknown.
int ssh_options_set_algo(ssh_session session, enum ssh_kex_types_e algo, const char *list)
References ssh_session_struct::opts, SAFE_FREE, session, ssh_keep_fips_algos, ssh_keep_known_algos, ssh_kex_get_description, SSH_REQUEST_DENIED, ssh_set_error, ssh_session_struct::wanted_methods.
Referenced by server_set_kex, ssh_options_set.
int ssh_options_apply(ssh_session session)
References ssh_iterator::data, ssh_session_struct::global_knownhosts, ssh_session_struct::identity, if, ssh_session_struct::knownhosts, ssh_iterator::next, ssh_session_struct::opts, ssh_session_struct::ProxyCommand, rc, session, ssh_list_get_iterator, ssh_options_set, SSH_OPTIONS_SSH_DIR, SSH_OPTIONS_USER, ssh_path_expand_escape, ssh_session_struct::sshdir, ssh_session_struct::username.
Referenced by ssh_connect, ssh_is_server_known, ssh_known_hosts_check_server_key, ssh_known_hosts_get_algorithms, ssh_known_hosts_get_algorithms_names, ssh_try_publickey_from_file, ssh_write_knownhost, torture_options_set_knownhosts.