pkd_util.c
int system_checked(const char *cmd)
runs system(3); exits if that is interrupted with SIGINT/QUIT
0 upon success, non-zero otherwise
References rc.
Referenced by bin_exists, pkd_rmfiles, setup_dropbear_client_rsa_key, setup_ecdsa_keys, setup_ed25519_key, setup_openssh_client_keys, setup_rsa_key, torture_pkd_runtest.
static int bin_exists(const char *binary)
References system_checked.
Referenced by is_dropbear_client_enabled, is_openssh_client_enabled.
static int is_openssh_client_new_enough(void)
References rc.
Referenced by is_openssh_client_enabled.
int is_openssh_client_enabled(void)
References bin_exists, is_openssh_client_new_enough, OPENSSH_BINARY, OPENSSH_KEYGEN.
Referenced by pkd_run_tests.
int is_dropbear_client_enabled(void)
References bin_exists, DROPBEAR_BINARY, DROPBEAR_KEYGEN.
Referenced by pkd_run_tests.