pkd_keyutil.h
LIBSSH_RSA_TESTKEY
LIBSSH_ED25519_TESTKEY
LIBSSH_ECDSA_256_TESTKEY
LIBSSH_ECDSA_384_TESTKEY
LIBSSH_ECDSA_521_TESTKEY
OPENSSH_RSA_TESTKEY
OPENSSH_ECDSA256_TESTKEY
OPENSSH_ECDSA384_TESTKEY
OPENSSH_ECDSA521_TESTKEY
OPENSSH_ED25519_TESTKEY
OPENSSH_CA_TESTKEY
DROPBEAR_RSA_TESTKEY
cleanup_file
cleanup_key
void setup_rsa_key(void)
References LIBSSH_RSA_TESTKEY, OPENSSH_KEYGEN, rc, system_checked.
Referenced by torture_pkd_setup_rsa.
void setup_ed25519_key(void)
References LIBSSH_ED25519_TESTKEY, OPENSSH_KEYGEN, rc, system_checked.
Referenced by torture_pkd_setup_ed25519.
void setup_ecdsa_keys(void)
References LIBSSH_ECDSA_256_TESTKEY, LIBSSH_ECDSA_384_TESTKEY, LIBSSH_ECDSA_521_TESTKEY, OPENSSH_KEYGEN, rc, system_checked.
Referenced by torture_pkd_setup_ecdsa_256, torture_pkd_setup_ecdsa_384, torture_pkd_setup_ecdsa_521.
void cleanup_rsa_key(void)
References cleanup_key, LIBSSH_RSA_TESTKEY.
Referenced by pkd_run_tests.
void cleanup_ed25519_key(void)
References cleanup_key, LIBSSH_ED25519_TESTKEY.
Referenced by pkd_run_tests.
void cleanup_ecdsa_keys(void)
References cleanup_key, LIBSSH_ECDSA_256_TESTKEY, LIBSSH_ECDSA_384_TESTKEY, LIBSSH_ECDSA_521_TESTKEY.
Referenced by pkd_run_tests.
void setup_openssh_client_keys(void)
References OPENSSH_CA_TESTKEY, OPENSSH_ECDSA256_TESTKEY, OPENSSH_ECDSA384_TESTKEY, OPENSSH_ECDSA521_TESTKEY, OPENSSH_ED25519_TESTKEY, OPENSSH_KEYGEN, OPENSSH_RSA_TESTKEY, rc, system_checked.
Referenced by pkd_run_tests.
void cleanup_openssh_client_keys(void)
References cleanup_file, cleanup_key, OPENSSH_CA_TESTKEY, OPENSSH_ECDSA256_TESTKEY, OPENSSH_ECDSA384_TESTKEY, OPENSSH_ECDSA521_TESTKEY, OPENSSH_ED25519_TESTKEY, OPENSSH_RSA_TESTKEY.
Referenced by pkd_run_tests.
void setup_dropbear_client_rsa_key(void)
References DROPBEAR_KEYGEN, DROPBEAR_RSA_TESTKEY, rc, system_checked.
Referenced by pkd_run_tests.
void cleanup_dropbear_client_rsa_key(void)
References DROPBEAR_RSA_TESTKEY.
Referenced by pkd_run_tests.