pki_container_openssh.c
static int pki_openssh_import_privkey_blob(ssh_buffer key_blob_buffer, ssh_key *pkey)
References key, pki_import_privkey_buffer, rc, SAFE_FREE, ssh_buffer_unpack, SSH_ERROR, ssh_key_free, ssh_key_type_from_name, SSH_KEYTYPE_UNKNOWN, SSH_LOG, SSH_LOG_WARN, SSH_OK.
Referenced by ssh_pki_openssh_import.
static int pki_private_key_decrypt(ssh_string blob, const char *passphrase, const char *ciphername, const char *kdfname, ssh_string kdfoptions, ssh_auth_callback auth_fn, void *auth_data)
decrypts an encrypted private key blob in OpenSSH format.
References bcrypt_pbkdf, ssh_cipher_struct::blocksize, buffer, ssh_cipher_struct::decrypt, explicit_bzero, ssh_cipher_struct::keysize, name, ssh_cipher_struct::name, rc, SAFE_FREE, ssh_cipher_struct::set_decrypt_key, ssh_buffer_add_data, SSH_BUFFER_FREE, ssh_buffer_new, ssh_buffer_unpack, ssh_cipher_clear, SSH_ERROR, ssh_get_ciphertab, SSH_LOG, SSH_LOG_DEBUG, SSH_LOG_WARN, SSH_OK, ssh_string_data, ssh_string_len.
Referenced by ssh_pki_openssh_import.
static ssh_key ssh_pki_openssh_import(const char *text_key, const char *passphrase, ssh_auth_callback auth_fn, void *auth_data, bool private)
References base64_to_bin, buffer, key, OPENSSH_AUTH_MAGIC, OPENSSH_HEADER_BEGIN, OPENSSH_HEADER_END, pki_openssh_import_privkey_blob, pki_private_key_decrypt, rc, SAFE_FREE, ssh_buffer_add_data, SSH_BUFFER_FREE, ssh_buffer_get_len, ssh_buffer_get_ssh_string, ssh_buffer_get_u8, ssh_buffer_new, ssh_buffer_set_secure, ssh_buffer_unpack, SSH_ERROR, ssh_key_free, SSH_LOG, SSH_LOG_INFO, SSH_LOG_WARN, SSH_OK, ssh_pki_import_pubkey_blob, ssh_string_data, ssh_string_len.
Referenced by ssh_pki_openssh_privkey_import, ssh_pki_openssh_pubkey_import.
ssh_key ssh_pki_openssh_privkey_import(const char *text_key, const char *passphrase, ssh_auth_callback auth_fn, void *auth_data)
References ssh_pki_openssh_import.
Referenced by ssh_pki_import_privkey_base64.
ssh_key ssh_pki_openssh_pubkey_import(const char *text_key)
References ssh_pki_openssh_import.
Referenced by ssh_pki_import_pubkey_file.
static int pki_openssh_export_privkey_blob(const ssh_key privkey, ssh_buffer buffer)
References buffer, ED25519_KEY_LEN, privkey, rc, ssh_buffer_pack, SSH_ERROR, SSH_KEYTYPE_ED25519, SSH_LOG, SSH_LOG_WARN.
Referenced by ssh_pki_openssh_privkey_export.
static int pki_private_key_encrypt(ssh_buffer privkey_buffer, const char *passphrase, const char *ciphername, const char *kdfname, ssh_auth_callback auth_fn, void *auth_data, uint32_t rounds, ssh_string salt)
References bcrypt_pbkdf, ssh_cipher_struct::blocksize, ssh_cipher_struct::encrypt, explicit_bzero, ssh_cipher_struct::keysize, name, ssh_cipher_struct::name, rc, ssh_cipher_struct::set_encrypt_key, ssh_buffer_get, ssh_buffer_get_len, ssh_cipher_clear, SSH_ERROR, ssh_get_ciphertab, SSH_LOG, SSH_LOG_WARN, SSH_OK, ssh_string_data, ssh_string_len.
Referenced by ssh_pki_openssh_privkey_export.
ssh_string ssh_pki_openssh_privkey_export(const ssh_key privkey, const char *passphrase, ssh_auth_callback auth_fn, void *auth_data)
References bin_to_base64, buffer, error, explicit_bzero, OPENSSH_AUTH_MAGIC, OPENSSH_HEADER_BEGIN, OPENSSH_HEADER_END, pki_openssh_export_privkey_blob, pki_private_key_encrypt, pki_publickey_to_blob, privkey, rc, SAFE_FREE, ssh_buffer_add_u8, SSH_BUFFER_FREE, ssh_buffer_get, ssh_buffer_get_data, ssh_buffer_get_len, ssh_buffer_new, ssh_buffer_pack, ssh_buffer_reinit, SSH_ERROR, ssh_get_random, SSH_KEYTYPE_ED25519, SSH_LOG, SSH_LOG_INFO, SSH_LOG_WARN, SSH_OK, ssh_string_data, SSH_STRING_FREE, ssh_string_new.
Referenced by ssh_pki_export_privkey_base64, ssh_pki_export_privkey_file.