pki_crypto.c
_PKI_CRYPTO_H
static int pem_get_password(char *buf, int size, int rwflag, void *userdata)
References pem_get_password_struct::data, pem_get_password_struct::fn, rc.
Referenced by pki_private_key_from_base64, pki_private_key_to_pem.
ssh_key pki_key_dup(const ssh_key key, int demote)
References DSA_get0_key, DSA_get0_pqg, DSA_set0_key, DSA_set0_pqg, key, pki_ed25519_key_dup, rc, RSA_get0_crt_params, RSA_get0_factors, RSA_get0_key, RSA_set0_crt_params, RSA_set0_factors, RSA_set0_key, SSH_KEY_FLAG_PRIVATE, SSH_KEY_FLAG_PUBLIC, ssh_key_free, ssh_key_is_private, ssh_key_new, SSH_KEYTYPE_DSS, SSH_KEYTYPE_ECDSA_P256, SSH_KEYTYPE_ECDSA_P384, SSH_KEYTYPE_ECDSA_P521, SSH_KEYTYPE_ED25519, SSH_KEYTYPE_RSA, SSH_KEYTYPE_RSA1, SSH_KEYTYPE_UNKNOWN, SSH_OK.
Referenced by ssh_key_dup, ssh_pki_export_privkey_to_pubkey.
int pki_key_generate_rsa(ssh_key key, int parameter)
References key, rc, SSH_ERROR, SSH_OK.
Referenced by ssh_pki_generate.
int pki_key_generate_dss(ssh_key key, int parameter)
References key, rc, SSH_ERROR, SSH_OK.
Referenced by ssh_pki_generate.
int pki_key_compare(const ssh_key k1, const ssh_key k2, enum ssh_keycmp_e what)
References DSA_get0_key, DSA_get0_pqg, RSA_get0_factors, RSA_get0_key, SSH_KEY_CMP_PRIVATE, SSH_KEYTYPE_DSS, SSH_KEYTYPE_ECDSA_P256, SSH_KEYTYPE_ECDSA_P384, SSH_KEYTYPE_ECDSA_P521, SSH_KEYTYPE_ED25519, SSH_KEYTYPE_RSA, SSH_KEYTYPE_RSA1, SSH_KEYTYPE_SK_ECDSA, SSH_KEYTYPE_SK_ED25519, SSH_KEYTYPE_UNKNOWN, ssh_key_struct::type.
Referenced by ssh_key_cmp.
ssh_string pki_private_key_to_pem(const ssh_key key, const char *passphrase, ssh_auth_callback auth_fn, void *auth_data)
References ssh_string_struct::data, ED25519_KEY_LEN, key, pem_get_password, rc, SSH_KEYTYPE_DSS, SSH_KEYTYPE_DSS_CERT01, SSH_KEYTYPE_ECDSA_P256, SSH_KEYTYPE_ECDSA_P256_CERT01, SSH_KEYTYPE_ECDSA_P384, SSH_KEYTYPE_ECDSA_P384_CERT01, SSH_KEYTYPE_ECDSA_P521, SSH_KEYTYPE_ECDSA_P521_CERT01, SSH_KEYTYPE_ED25519, SSH_KEYTYPE_ED25519_CERT01, SSH_KEYTYPE_RSA, SSH_KEYTYPE_RSA1, SSH_KEYTYPE_RSA_CERT01, SSH_KEYTYPE_UNKNOWN, SSH_LOG, SSH_LOG_TRACE, SSH_LOG_WARN, ssh_string_fill, ssh_string_new.
Referenced by ssh_pki_export_privkey_base64, ssh_pki_export_privkey_file.
ssh_key pki_private_key_from_base64(const char *b64_key, const char *passphrase, ssh_auth_callback auth_fn, void *auth_data)
References ED25519_KEY_LEN, is_ecdsa_key_type, key, pem_get_password, SAFE_FREE, SSH_KEY_FLAG_PRIVATE, SSH_KEY_FLAG_PUBLIC, ssh_key_free, ssh_key_new, ssh_key_type_to_char, SSH_KEYTYPE_DSS, SSH_KEYTYPE_ED25519, SSH_KEYTYPE_RSA, SSH_KEYTYPE_UNKNOWN, SSH_LOG, SSH_LOG_TRACE, SSH_LOG_WARN.
Referenced by ssh_pki_import_privkey_base64.
int pki_privkey_build_dss(ssh_key key, ssh_string p, ssh_string q, ssh_string g, ssh_string pubkey, ssh_string privkey)
References DSA_set0_key, DSA_set0_pqg, key, privkey, pubkey, rc, SSH_ERROR, ssh_make_string_bn, SSH_OK.
Referenced by pki_import_privkey_buffer.
int pki_pubkey_build_dss(ssh_key key, ssh_string p, ssh_string q, ssh_string g, ssh_string pubkey)
References DSA_set0_key, DSA_set0_pqg, key, pubkey, rc, SSH_ERROR, ssh_make_string_bn, SSH_OK.
Referenced by pki_import_pubkey_buffer.
int pki_privkey_build_rsa(ssh_key key, ssh_string n, ssh_string e, ssh_string d, UNUSED_PARAM(ssh_string iqmp), ssh_string p, ssh_string q)
References key, rc, RSA_set0_factors, RSA_set0_key, SSH_ERROR, ssh_make_string_bn, SSH_OK.
int pki_pubkey_build_rsa(ssh_key key, ssh_string e, ssh_string n)
References key, rc, RSA_set0_key, SSH_ERROR, ssh_make_string_bn, SSH_OK.
Referenced by pki_import_pubkey_buffer.
ssh_string pki_publickey_to_blob(const ssh_key key)
References buffer, DSA_get0_key, DSA_get0_pqg, key, pki_ed25519_public_key_to_blob, rc, RSA_get0_key, ssh_buffer_add_buffer, ssh_buffer_add_ssh_string, SSH_BUFFER_FREE, ssh_buffer_get, ssh_buffer_get_len, ssh_buffer_new, SSH_ERROR, SSH_KEYTYPE_DSS, SSH_KEYTYPE_ECDSA_P256, SSH_KEYTYPE_ECDSA_P384, SSH_KEYTYPE_ECDSA_P521, SSH_KEYTYPE_ED25519, SSH_KEYTYPE_RSA, SSH_KEYTYPE_RSA1, SSH_KEYTYPE_SK_ECDSA, SSH_KEYTYPE_SK_ED25519, SSH_KEYTYPE_UNKNOWN, ssh_make_bignum_string, ssh_string_burn, ssh_string_fill, SSH_STRING_FREE, ssh_string_from_char, ssh_string_new.
Referenced by ssh_pki_export_pubkey_base64, ssh_pki_export_pubkey_blob, ssh_pki_openssh_privkey_export.
static ssh_string pki_dsa_signature_to_blob(const ssh_signature sig)
References buffer, DSA_SIG_get0, error, ssh_signature_struct::raw_sig, s, ssh_make_bignum_string, ssh_string_data, ssh_string_fill, SSH_STRING_FREE, ssh_string_len, ssh_string_new.
Referenced by pki_signature_to_blob.
static ssh_string pki_ecdsa_signature_to_blob(const ssh_signature sig)
References ECDSA_SIG_get0, error, ssh_signature_struct::raw_sig, rc, s, ssh_buffer_add_ssh_string, SSH_BUFFER_FREE, ssh_buffer_get, ssh_buffer_get_len, ssh_buffer_new, ssh_make_bignum_string, ssh_string_data, ssh_string_fill, SSH_STRING_FREE, ssh_string_len, ssh_string_new.
Referenced by pki_signature_to_blob.
ssh_string pki_signature_to_blob(const ssh_signature sig)
References pki_dsa_signature_to_blob, pki_ecdsa_signature_to_blob, pki_ed25519_signature_to_blob, ssh_signature_struct::raw_sig, SSH_KEYTYPE_DSS, SSH_KEYTYPE_ECDSA_P256, SSH_KEYTYPE_ECDSA_P384, SSH_KEYTYPE_ECDSA_P521, SSH_KEYTYPE_ED25519, SSH_KEYTYPE_RSA, SSH_KEYTYPE_RSA1, SSH_KEYTYPE_UNKNOWN, SSH_LOG, SSH_LOG_WARN, ssh_string_copy, ssh_signature_struct::type, ssh_signature_struct::type_c.
Referenced by ssh_pki_export_signature_blob, torture_pki_ed25519_sign, torture_pki_ed25519_sign_openssh_privkey_passphrase, torture_pki_verify_mismatch.
static int pki_signature_from_rsa_blob(const ssh_key pubkey, const ssh_string sig_blob, ssh_signature sig)
References explicit_bzero, pubkey, ssh_signature_struct::raw_sig, SSH_ERROR, SSH_LOG, SSH_LOG_DEBUG, ssh_log_hexdump, SSH_LOG_WARN, SSH_OK, ssh_string_copy, ssh_string_data, SSH_STRING_FREE, ssh_string_len, ssh_string_new.
Referenced by pki_signature_from_blob.
static int pki_signature_from_dsa_blob(UNUSED_PARAM(const ssh_key pubkey), const ssh_string sig_blob, ssh_signature sig)
References DSA_SIG_set0, error, explicit_bzero, ssh_signature_struct::raw_sig, rc, s, SAFE_FREE, SSH_ERROR, SSH_LOG, ssh_log_hexdump, SSH_LOG_WARN, ssh_make_string_bn, SSH_OK, ssh_string_burn, ssh_string_data, ssh_string_fill, SSH_STRING_FREE, ssh_string_len, ssh_string_new.
Referenced by pki_signature_from_blob.
static int pki_signature_from_ecdsa_blob(UNUSED_PARAM(const ssh_key pubkey), const ssh_string sig_blob, ssh_signature sig)
References ECDSA_SIG_set0, error, explicit_bzero, ssh_signature_struct::raw_sig, rc, s, SAFE_FREE, ssh_buffer_add_data, SSH_BUFFER_FREE, ssh_buffer_get_len, ssh_buffer_get_ssh_string, ssh_buffer_new, SSH_ERROR, SSH_LOG, ssh_log_hexdump, SSH_LOG_WARN, ssh_make_string_bn, SSH_OK, ssh_string_burn, ssh_string_data, ssh_string_fill, SSH_STRING_FREE, ssh_string_len, ssh_string_new.
Referenced by pki_signature_from_blob.
ssh_signature pki_signature_from_blob(const ssh_key pubkey, const ssh_string sig_blob, enum ssh_keytypes_e type, enum ssh_digest_e hash_type)
References error, ssh_signature_struct::hash_type, pki_signature_from_dsa_blob, pki_signature_from_ecdsa_blob, pki_signature_from_ed25519_blob, pki_signature_from_rsa_blob, pubkey, rc, ssh_key_signature_to_char, ssh_key_type_plain, SSH_KEYTYPE_DSS, SSH_KEYTYPE_ECDSA_P256, SSH_KEYTYPE_ECDSA_P256_CERT01, SSH_KEYTYPE_ECDSA_P384, SSH_KEYTYPE_ECDSA_P384_CERT01, SSH_KEYTYPE_ECDSA_P521, SSH_KEYTYPE_ECDSA_P521_CERT01, SSH_KEYTYPE_ED25519, SSH_KEYTYPE_RSA, SSH_KEYTYPE_RSA1, SSH_KEYTYPE_SK_ECDSA, SSH_KEYTYPE_SK_ECDSA_CERT01, SSH_KEYTYPE_SK_ED25519, SSH_KEYTYPE_UNKNOWN, SSH_LOG, SSH_LOG_WARN, SSH_OK, ssh_signature_free, ssh_signature_new, ssh_signature_struct::type, ssh_signature_struct::type_c.
Referenced by ssh_pki_import_signature_blob, torture_pki_ed25519_verify, torture_pki_ed25519_verify_bad, torture_pki_verify_mismatch.
static const EVP_MD* pki_digest_to_md(enum ssh_digest_e hash_type)
References SSH_DIGEST_AUTO, SSH_DIGEST_SHA1, SSH_DIGEST_SHA256, SSH_DIGEST_SHA384, SSH_DIGEST_SHA512, SSH_LOG, SSH_LOG_TRACE.
Referenced by pki_sign_data, pki_verify_data_signature.
static EVP_PKEY* pki_key_to_pkey(ssh_key key)
References ED25519_KEY_LEN, error, key, SSH_KEY_FLAG_PKCS11_URI, ssh_key_is_private, SSH_KEYTYPE_DSS, SSH_KEYTYPE_DSS_CERT01, SSH_KEYTYPE_ECDSA_P256, SSH_KEYTYPE_ECDSA_P256_CERT01, SSH_KEYTYPE_ECDSA_P384, SSH_KEYTYPE_ECDSA_P384_CERT01, SSH_KEYTYPE_ECDSA_P521, SSH_KEYTYPE_ECDSA_P521_CERT01, SSH_KEYTYPE_ED25519, SSH_KEYTYPE_ED25519_CERT01, SSH_KEYTYPE_RSA, SSH_KEYTYPE_RSA1, SSH_KEYTYPE_RSA_CERT01, SSH_KEYTYPE_SK_ECDSA, SSH_KEYTYPE_SK_ECDSA_CERT01, SSH_KEYTYPE_SK_ED25519, SSH_KEYTYPE_SK_ED25519_CERT01, SSH_KEYTYPE_UNKNOWN, SSH_LOG, SSH_LOG_TRACE.
Referenced by pki_sign_data, pki_verify_data_signature.
ssh_signature pki_sign_data(const ssh_key privkey, enum ssh_digest_e hash_type, const unsigned char *input, size_t input_len)
References ctx, EVP_MD_CTX_free, explicit_bzero, ssh_signature_struct::hash_type, pki_digest_to_md, pki_do_sign_hash, pki_key_check_hash_compatible, pki_key_to_pkey, privkey, ssh_signature_struct::raw_sig, rc, SAFE_FREE, SSH_DIGEST_AUTO, ssh_key_is_private, ssh_key_signature_to_char, SSH_KEYTYPE_ED25519, SSH_KEYTYPE_ED25519_CERT01, SSH_LOG, ssh_log_hexdump, SSH_LOG_TRACE, SSH_OK, ssh_signature_free, ssh_signature_new, ssh_string_fill, ssh_string_new, ssh_signature_struct::type, ssh_signature_struct::type_c.
Referenced by pki_do_sign, test_sign_verify_data, torture_pki_fail_sign_with_incompatible_hash.
int pki_verify_data_signature(ssh_signature signature, const ssh_key pubkey, const unsigned char *input, size_t input_len)
References ctx, ssh_signature_struct::ed25519_sig, endif, EVP_MD_CTX_free, ssh_signature_struct::hash_type, pki_digest_to_md, pki_ed25519_verify, pki_key_check_hash_compatible, pki_key_to_pkey, pubkey, ssh_signature_struct::raw_sig, rc, SSH_DIGEST_AUTO, SSH_ERROR, ssh_key_is_private, SSH_KEYTYPE_ED25519, SSH_KEYTYPE_ED25519_CERT01, SSH_KEYTYPE_SK_ED25519, SSH_KEYTYPE_SK_ED25519_CERT01, SSH_LOG, SSH_LOG_TRACE, SSH_OK, ssh_string_data, ssh_string_len.
Referenced by ssh_pki_signature_verify, test_sign_verify_data, torture_pki_fail_sign_with_incompatible_hash.
ssh_signature pki_do_sign_hash(const ssh_key privkey, const unsigned char *hash, size_t hlen, enum ssh_digest_e hash_type)
References ssh_signature_struct::hash_type, pki_ed25519_sign, privkey, rc, ssh_key_signature_to_char, SSH_KEYTYPE_ED25519, SSH_OK, ssh_signature_free, ssh_signature_new, ssh_signature_struct::type, ssh_signature_struct::type_c.
Referenced by pki_sign_data.
int pki_uri_import(const char *uri_name, ssh_key *nkey, enum ssh_key_e key_type)
References is_ecdsa_key_type, key, SSH_ERROR, SSH_KEY_CMP_PRIVATE, SSH_KEY_CMP_PUBLIC, SSH_KEY_FLAG_PKCS11_URI, SSH_KEY_FLAG_PRIVATE, SSH_KEY_FLAG_PUBLIC, ssh_key_free, ssh_key_new, SSH_KEY_PRIVATE, ssh_key_type_to_char, SSH_KEYTYPE_RSA, SSH_KEYTYPE_UNKNOWN, SSH_LOG, SSH_LOG_INFO, SSH_LOG_WARN, SSH_OK.
Referenced by ssh_pki_import_privkey_file, ssh_pki_import_pubkey_file.