pki_ed25519_common.c
int pki_privkey_build_ed25519(ssh_key key, ssh_string pubkey, ssh_string privkey)
References ED25519_KEY_LEN, error, key, privkey, pubkey, SAFE_FREE, SSH_ERROR, SSH_LOG, SSH_LOG_WARN, SSH_OK, ssh_string_data, ssh_string_len.
Referenced by pki_import_privkey_buffer.
int pki_ed25519_key_cmp(const ssh_key k1, const ssh_key k2, enum ssh_keycmp_e what)
References ED25519_KEY_LEN, ssh_key_struct::ed25519_privkey, ssh_key_struct::ed25519_pubkey, SSH_KEY_CMP_PRIVATE, SSH_KEY_CMP_PUBLIC.
Referenced by ssh_key_cmp.
int pki_ed25519_key_dup(ssh_key new, const ssh_key key)
References ED25519_KEY_LEN, key, SAFE_FREE, SSH_ERROR, SSH_OK.
Referenced by pki_key_dup.
int pki_ed25519_public_key_to_blob(ssh_buffer buffer, ssh_key key)
References buffer, ED25519_KEY_LEN, key, rc, ssh_buffer_pack, SSH_ERROR.
Referenced by pki_publickey_to_blob.
ssh_string pki_ed25519_signature_to_blob(ssh_signature sig)
References ssh_signature_struct::ed25519_sig, ED25519_SIG_LEN, ssh_signature_struct::raw_sig, ssh_string_data, ssh_string_fill, ssh_string_len, ssh_string_new.
Referenced by pki_signature_to_blob.
int pki_signature_from_ed25519_blob(ssh_signature sig, ssh_string sig_blob)
References ssh_signature_struct::ed25519_sig, ED25519_SIG_LEN, ssh_signature_struct::raw_sig, SSH_ERROR, SSH_LOG, SSH_LOG_WARN, SSH_OK, ssh_string_copy, ssh_string_data, ssh_string_len.
Referenced by pki_signature_from_blob.