poll.h
POLLIN
POLLPRI
POLLOUT
POLLERR
POLLHUP
POLLNVAL
POLLRDNORM
POLLRDBAND
POLLWRNORM
POLLWRBAND
typedef struct ssh_pollfd_struct ssh_pollfd_t
typedef unsigned long int nfds_t
typedef struct ssh_poll_ctx_struct* ssh_poll_ctx
typedef struct ssh_poll_handle_struct* ssh_poll_handle
typedef int(* ssh_poll_callback) (ssh_poll_handle p, socket_t fd, int revents, void *userdata))(ssh_poll_handle p, socket_t fd, int revents, void *userdata)
SSH poll callback. This callback will be used when an event caught on the socket.
p Poll object this callback belongs to. fd The raw socket. revents The current poll events on the socket. userdata Userdata to be passed to the callback function. 0 on success, < 0 if you removed the poll object from its poll context.
void ssh_poll_init(void)
References bsd_poll, ssh_poll_emu.
Referenced by ssh_socket_init.
void ssh_poll_cleanup(void)
References bsd_poll, ssh_poll_emu.
Referenced by ssh_socket_cleanup.
int ssh_poll(ssh_pollfd_t *fds, nfds_t nfds, int timeout)
References ssh_poll_emu.
Referenced by atomicio, ssh_poll_ctx_dopoll.
ssh_poll_handle ssh_poll_new(socket_t fd, short events, ssh_poll_callback cb, void *userdata)
Allocate a new poll object, which could be used within a poll context.
fd Socket that will be polled. events Poll events that will be monitored for the socket. i.e. POLLIN, POLLPRI, POLLOUT cb Function to be called if any of the events are set. The prototype of cb is: int (*ssh_poll_callback)(ssh_poll_handle p, socket_t fd, int revents, void *userdata); userdata Userdata to be passed to the callback function. NULL if not needed. A new poll object, NULL on error
References cb, ssh_poll_handle_struct::cb, ssh_poll_handle_struct::cb_data, ssh_poll_handle_struct::events, ssh_poll_handle_struct::fd, ssh_poll_handle_struct::x, ZERO_STRUCTP.
Referenced by ssh_bind_get_poll, ssh_connector_set_event, ssh_event_add_fd, ssh_socket_get_poll_handle.
void ssh_poll_free(ssh_poll_handle p)
Free a poll object.
p Pointer to an already allocated poll object.
References ssh_poll_handle_struct::ctx, SAFE_FREE, ssh_poll_ctx_remove.
Referenced by ssh_connector_free, ssh_connector_remove_event, ssh_event_add_fd, ssh_event_remove_fd, ssh_poll_ctx_free, ssh_socket_close.
ssh_poll_ctx ssh_poll_get_ctx(ssh_poll_handle p)
Get the poll context of a poll object.
p Pointer to an already allocated poll object. Poll context or NULL if the poll object isn't attached.
References ssh_poll_handle_struct::ctx.
Referenced by ssh_handle_packets.
short ssh_poll_get_events(ssh_poll_handle p)
Get the events of a poll object.
p Pointer to an already allocated poll object. Poll events.
References ssh_poll_handle_struct::events.
Referenced by ssh_poll_add_events, ssh_poll_remove_events, ssh_socket_get_poll_flags, ssh_socket_unbuffered_write.
void ssh_poll_set_events(ssh_poll_handle p, short events)
Set the events of a poll object. The events will also be propagated to an associated poll context.
p Pointer to an already allocated poll object. events Poll events.
References ssh_poll_handle_struct::ctx, ssh_pollfd_struct::events, ssh_poll_handle_struct::events, ssh_poll_handle_struct::idx, ssh_poll_handle_struct::lock, ssh_poll_ctx_struct::pollfds, ssh_poll_handle_struct::x.
Referenced by ssh_poll_add_events, ssh_poll_remove_events, ssh_socket_connect_proxycommand, ssh_socket_pollcallback, ssh_socket_set_fd, ssh_socket_unbuffered_write.
void ssh_poll_add_events(ssh_poll_handle p, short events)
Add extra events to a poll object. Duplicates are ignored. The events will also be propagated to an associated poll context.
p Pointer to an already allocated poll object. events Poll events.
References ssh_poll_get_events, ssh_poll_set_events.
Referenced by ssh_connector_reset_pollevents, ssh_handle_packets, ssh_socket_nonblocking_flush, ssh_socket_set_fd.
void ssh_poll_remove_events(ssh_poll_handle p, short events)
Remove events from a poll object. Non-existent are ignored. The events will also be propagated to an associated poll context.
p Pointer to an already allocated poll object. events Poll events.
References ssh_poll_get_events, ssh_poll_set_events.
Referenced by ssh_connector_reset_pollevents, ssh_socket_pollcallback.
socket_t ssh_poll_get_fd(ssh_poll_handle p)
Get the raw socket of a poll object.
p Pointer to an already allocated poll object. Raw socket.
References ssh_poll_handle_struct::ctx, ssh_pollfd_struct::fd, ssh_poll_handle_struct::fd, ssh_poll_handle_struct::idx, ssh_poll_ctx_struct::pollfds, ssh_poll_handle_struct::x.
void ssh_poll_set_fd(ssh_poll_handle p, socket_t fd)
Set the file descriptor of a poll object. The FD will also be propagated to an associated poll context.
p Pointer to an already allocated poll object. fd New file descriptor.
References ssh_poll_handle_struct::ctx, ssh_pollfd_struct::fd, ssh_poll_handle_struct::fd, ssh_poll_handle_struct::idx, ssh_poll_ctx_struct::pollfds, ssh_poll_handle_struct::x.
Referenced by ssh_socket_set_fd.
void ssh_poll_set_callback(ssh_poll_handle p, ssh_poll_callback cb, void *userdata)
Set the callback of a poll object.
p Pointer to an already allocated poll object. cb Function to be called if any of the events are set. userdata Userdata to be passed to the callback function. NULL if not needed.
References cb, ssh_poll_handle_struct::cb, ssh_poll_handle_struct::cb_data.
ssh_poll_ctx ssh_poll_ctx_new(size_t chunk_size)
Create a new poll context. It could be associated with many poll object which are going to be polled at the same time as the poll context. You would need a single poll context per thread.
chunk_size The size of the memory chunk that will be allocated, when more memory is needed. This is for efficiency reasons, i.e. don't allocate memory for each new poll object, but for the next 5. Set it to 0 if you want to use the library's default value.
References ctx, SSH_POLL_CTX_CHUNK, ZERO_STRUCTP.
Referenced by main, ssh_event_new, ssh_poll_get_default_ctx.
void ssh_poll_ctx_free(ssh_poll_ctx ctx)
Free a poll context.
ctx Pointer to an already allocated poll context.
References ctx, SAFE_FREE, ssh_poll_free.
Referenced by ssh_event_free, ssh_event_new, ssh_free.
int ssh_poll_ctx_add(ssh_poll_ctx ctx, ssh_poll_handle p)
Add a poll object to a poll context.
ctx Pointer to an already allocated poll context. p Pointer to an already allocated poll object. 0 on success, < 0 on error
References ssh_poll_handle_struct::ctx, ctx, ssh_poll_handle_struct::events, ssh_poll_handle_struct::fd, ssh_poll_handle_struct::idx, ssh_poll_ctx_resize, ssh_poll_handle_struct::x.
Referenced by ssh_event_add_fd, ssh_event_add_poll, ssh_event_add_session, ssh_event_free, ssh_event_remove_session, ssh_handle_packets, ssh_poll_ctx_add_socket.
int ssh_poll_ctx_add_socket(ssh_poll_ctx ctx, struct ssh_socket_struct *s)
Referenced by main.
void ssh_poll_ctx_remove(ssh_poll_ctx ctx, ssh_poll_handle p)
Remove a poll object from a poll context.
ctx Pointer to an already allocated poll context. p Pointer to an already allocated poll object.
References ssh_poll_handle_struct::ctx, ctx, ssh_poll_handle_struct::fd, ssh_poll_handle_struct::idx, ssh_poll_ctx_resize, ssh_poll_handle_struct::x.
Referenced by ssh_event_add_session, ssh_event_free, ssh_event_remove_poll, ssh_event_remove_session, ssh_poll_free.
int ssh_poll_ctx_dopoll(ssh_poll_ctx ctx, int timeout)
Poll all the sockets associated through a poll object with a poll context. If any of the events are set after the poll, the call back function of the socket will be called. This function should be called once within the programs main loop.
ctx Pointer to an already allocated poll context. timeout An upper limit on the time for which ssh_poll_ctx() will block, in milliseconds. Specifying a negative value means an infinite timeout. This parameter is passed to the poll() function. SSH_OK No error. SSH_ERROR Error happened during the poll. SSH_AGAIN Timeout occured
References ssh_poll_handle_struct::cb, ssh_poll_handle_struct::cb_data, ctx, ssh_poll_handle_struct::events, ssh_poll_handle_struct::lock, rc, SSH_AGAIN, SSH_ERROR, ssh_poll, ssh_timeout_update, ssh_timestamp_init.
Referenced by main, ssh_event_dopoll, ssh_handle_packets.
ssh_poll_ctx ssh_poll_get_default_ctx(ssh_session session)
References ssh_session_struct::default_poll_ctx, session, ssh_poll_ctx_new.
Referenced by ssh_channel_select, ssh_handle_packets.
int ssh_event_add_poll(ssh_event event, ssh_poll_handle p)
Add a poll handle to the event.
event the ssh_event p the poll handle SSH_OK on success SSH_ERROR on failure
References ssh_event_struct::ctx, ssh_poll_ctx_add.
Referenced by ssh_connector_set_event.
void ssh_event_remove_poll(ssh_event event, ssh_poll_handle p)
remove a poll handle to the event.
event the ssh_event p the poll handle
References ssh_event_struct::ctx, ssh_poll_ctx_remove.
Referenced by ssh_connector_remove_event.