poll.c
SSH_POLL_CTX_CHUNK
typedef int(* poll_fn) (ssh_pollfd_t *, nfds_t, int))(ssh_pollfd_t *, nfds_t, int)
poll_fn ssh_poll_emu
Referenced by ssh_poll, ssh_poll_cleanup, ssh_poll_init.
static bool bsd_socket_not_connected(int sock_err)
Referenced by bsd_socket_compute_revents.
static bool bsd_socket_reset(int sock_err)
Referenced by bsd_socket_compute_revents.
static short bsd_socket_compute_revents(int fd, short events)
References bsd_socket_not_connected, bsd_socket_reset, POLLERR, POLLHUP, POLLIN, POLLRDNORM.
Referenced by bsd_poll.
static int bsd_poll(ssh_pollfd_t *fds, nfds_t nfds, int timeout)
References bsd_socket_compute_revents, ssh_pollfd_struct::events, ssh_pollfd_struct::fd, POLLIN, POLLNVAL, POLLOUT, POLLPRI, POLLRDBAND, POLLRDNORM, POLLWRBAND, POLLWRNORM, rc, ssh_pollfd_struct::revents, SSH_INVALID_SOCKET, ZERO_STRUCT.
Referenced by ssh_poll_cleanup, ssh_poll_init.
void ssh_poll_init(void)
References bsd_poll, ssh_poll_emu.
Referenced by ssh_socket_init.
void ssh_poll_cleanup(void)
References bsd_poll, ssh_poll_emu.
Referenced by ssh_socket_cleanup.
int ssh_poll(ssh_pollfd_t *fds, nfds_t nfds, int timeout)
References ssh_poll_emu.
Referenced by atomicio, ssh_poll_ctx_dopoll.
ssh_poll_handle ssh_poll_new(socket_t fd, short events, ssh_poll_callback cb, void *userdata)
Allocate a new poll object, which could be used within a poll context.
fd Socket that will be polled. events Poll events that will be monitored for the socket. i.e. POLLIN, POLLPRI, POLLOUT cb Function to be called if any of the events are set. The prototype of cb is: int (*ssh_poll_callback)(ssh_poll_handle p, socket_t fd, int revents, void *userdata); userdata Userdata to be passed to the callback function. NULL if not needed. A new poll object, NULL on error
References cb, ssh_poll_handle_struct::cb, ssh_poll_handle_struct::cb_data, ssh_poll_handle_struct::events, ssh_poll_handle_struct::fd, ssh_poll_handle_struct::x, ZERO_STRUCTP.
Referenced by ssh_bind_get_poll, ssh_connector_set_event, ssh_event_add_fd, ssh_socket_get_poll_handle.
void ssh_poll_free(ssh_poll_handle p)
Free a poll object.
p Pointer to an already allocated poll object.
References ssh_poll_handle_struct::ctx, SAFE_FREE, ssh_poll_ctx_remove.
Referenced by ssh_connector_free, ssh_connector_remove_event, ssh_event_add_fd, ssh_event_remove_fd, ssh_poll_ctx_free, ssh_socket_close.
ssh_poll_ctx ssh_poll_get_ctx(ssh_poll_handle p)
Get the poll context of a poll object.
p Pointer to an already allocated poll object. Poll context or NULL if the poll object isn't attached.
References ssh_poll_handle_struct::ctx.
Referenced by ssh_handle_packets.
short ssh_poll_get_events(ssh_poll_handle p)
Get the events of a poll object.
p Pointer to an already allocated poll object. Poll events.
References ssh_poll_handle_struct::events.
Referenced by ssh_poll_add_events, ssh_poll_remove_events, ssh_socket_get_poll_flags, ssh_socket_unbuffered_write.
void ssh_poll_set_events(ssh_poll_handle p, short events)
Set the events of a poll object. The events will also be propagated to an associated poll context.
p Pointer to an already allocated poll object. events Poll events.
References ssh_poll_handle_struct::ctx, ssh_pollfd_struct::events, ssh_poll_handle_struct::events, ssh_poll_handle_struct::idx, ssh_poll_handle_struct::lock, ssh_poll_ctx_struct::pollfds, ssh_poll_handle_struct::x.
Referenced by ssh_poll_add_events, ssh_poll_remove_events, ssh_socket_connect_proxycommand, ssh_socket_pollcallback, ssh_socket_set_fd, ssh_socket_unbuffered_write.
void ssh_poll_set_fd(ssh_poll_handle p, socket_t fd)
Set the file descriptor of a poll object. The FD will also be propagated to an associated poll context.
p Pointer to an already allocated poll object. fd New file descriptor.
References ssh_poll_handle_struct::ctx, ssh_pollfd_struct::fd, ssh_poll_handle_struct::fd, ssh_poll_handle_struct::idx, ssh_poll_ctx_struct::pollfds, ssh_poll_handle_struct::x.
Referenced by ssh_socket_set_fd.
void ssh_poll_add_events(ssh_poll_handle p, short events)
Add extra events to a poll object. Duplicates are ignored. The events will also be propagated to an associated poll context.
p Pointer to an already allocated poll object. events Poll events.
References ssh_poll_get_events, ssh_poll_set_events.
Referenced by ssh_connector_reset_pollevents, ssh_handle_packets, ssh_socket_nonblocking_flush, ssh_socket_set_fd.
void ssh_poll_remove_events(ssh_poll_handle p, short events)
Remove events from a poll object. Non-existent are ignored. The events will also be propagated to an associated poll context.
p Pointer to an already allocated poll object. events Poll events.
References ssh_poll_get_events, ssh_poll_set_events.
Referenced by ssh_connector_reset_pollevents, ssh_socket_pollcallback.
socket_t ssh_poll_get_fd(ssh_poll_handle p)
Get the raw socket of a poll object.
p Pointer to an already allocated poll object. Raw socket.
References ssh_poll_handle_struct::ctx, ssh_pollfd_struct::fd, ssh_poll_handle_struct::fd, ssh_poll_handle_struct::idx, ssh_poll_ctx_struct::pollfds, ssh_poll_handle_struct::x.
void ssh_poll_set_callback(ssh_poll_handle p, ssh_poll_callback cb, void *userdata)
Set the callback of a poll object.
p Pointer to an already allocated poll object. cb Function to be called if any of the events are set. userdata Userdata to be passed to the callback function. NULL if not needed.
References cb, ssh_poll_handle_struct::cb, ssh_poll_handle_struct::cb_data.
ssh_poll_ctx ssh_poll_ctx_new(size_t chunk_size)
Create a new poll context. It could be associated with many poll object which are going to be polled at the same time as the poll context. You would need a single poll context per thread.
chunk_size The size of the memory chunk that will be allocated, when more memory is needed. This is for efficiency reasons, i.e. don't allocate memory for each new poll object, but for the next 5. Set it to 0 if you want to use the library's default value.
References ctx, SSH_POLL_CTX_CHUNK, ZERO_STRUCTP.
Referenced by main, ssh_event_new, ssh_poll_get_default_ctx.
void ssh_poll_ctx_free(ssh_poll_ctx ctx)
Free a poll context.
ctx Pointer to an already allocated poll context.
References ctx, SAFE_FREE, ssh_poll_free.
Referenced by ssh_event_free, ssh_event_new, ssh_free.
static int ssh_poll_ctx_resize(ssh_poll_ctx ctx, size_t new_size)
References ctx.
Referenced by ssh_poll_ctx_add, ssh_poll_ctx_remove.
int ssh_poll_ctx_add(ssh_poll_ctx ctx, ssh_poll_handle p)
Add a poll object to a poll context.
ctx Pointer to an already allocated poll context. p Pointer to an already allocated poll object. 0 on success, < 0 on error
References ssh_poll_handle_struct::ctx, ctx, ssh_poll_handle_struct::events, ssh_poll_handle_struct::fd, ssh_poll_handle_struct::idx, ssh_poll_ctx_resize, ssh_poll_handle_struct::x.
Referenced by ssh_event_add_fd, ssh_event_add_poll, ssh_event_add_session, ssh_event_free, ssh_event_remove_session, ssh_handle_packets, ssh_poll_ctx_add_socket.
int ssh_poll_ctx_add_socket(ssh_poll_ctx ctx, ssh_socket s)
Add a socket object to a poll context.
ctx Pointer to an already allocated poll context. s A SSH socket handle 0 on success, < 0 on error
References ctx, s, ssh_poll_ctx_add, ssh_socket_get_poll_handle.
void ssh_poll_ctx_remove(ssh_poll_ctx ctx, ssh_poll_handle p)
Remove a poll object from a poll context.
ctx Pointer to an already allocated poll context. p Pointer to an already allocated poll object.
References ssh_poll_handle_struct::ctx, ctx, ssh_poll_handle_struct::fd, ssh_poll_handle_struct::idx, ssh_poll_ctx_resize, ssh_poll_handle_struct::x.
Referenced by ssh_event_add_session, ssh_event_free, ssh_event_remove_poll, ssh_event_remove_session, ssh_poll_free.
int ssh_poll_ctx_dopoll(ssh_poll_ctx ctx, int timeout)
Poll all the sockets associated through a poll object with a poll context. If any of the events are set after the poll, the call back function of the socket will be called. This function should be called once within the programs main loop.
ctx Pointer to an already allocated poll context. timeout An upper limit on the time for which ssh_poll_ctx() will block, in milliseconds. Specifying a negative value means an infinite timeout. This parameter is passed to the poll() function. SSH_OK No error. SSH_ERROR Error happened during the poll. SSH_AGAIN Timeout occured
References ssh_poll_handle_struct::cb, ssh_poll_handle_struct::cb_data, ctx, ssh_poll_handle_struct::events, ssh_poll_handle_struct::lock, rc, SSH_AGAIN, SSH_ERROR, ssh_poll, ssh_timeout_update, ssh_timestamp_init.
Referenced by main, ssh_event_dopoll, ssh_handle_packets.
ssh_poll_ctx ssh_poll_get_default_ctx(ssh_session session)
References ssh_session_struct::default_poll_ctx, session, ssh_poll_ctx_new.
Referenced by ssh_channel_select, ssh_handle_packets.
ssh_event ssh_event_new(void)
Create a new event context. It could be associated with many ssh_session objects and socket fd which are going to be polled at the same time as the event context. You would need a single event context per thread.
The ssh_event object on success, NULL on failure.
References ssh_event_struct::ctx, ssh_list_new, ssh_poll_ctx_free, ssh_poll_ctx_new, ZERO_STRUCTP.
Referenced by LLVMFuzzerTestOneInput, main, pkd_exec_hello, run_server, select_loop, ssh_channel_select, ssh_select, test_ssh_channel_request_x11.
static int ssh_event_fd_wrapper_callback(ssh_poll_handle p, socket_t fd, int revents, void *userdata)
References ssh_event_fd_wrapper::cb, ssh_event_fd_wrapper::userdata.
Referenced by ssh_event_add_fd, ssh_event_remove_fd.
int ssh_event_add_fd(ssh_event event, socket_t fd, short events, ssh_event_callback cb, void *userdata)
Add a fd to the event and assign it a callback, when used in blocking mode.
event The ssh_event fd Socket that will be polled. events Poll events that will be monitored for the socket. i.e. POLLIN, POLLPRI, POLLOUT cb Function to be called if any of the events are set. The prototype of cb is: int (*ssh_event_callback)(socket_t fd, int revents, void *userdata); userdata Userdata to be passed to the callback function. NULL if not needed. SSH_OK on success SSH_ERROR on failure
References cb, ssh_event_fd_wrapper::cb, ssh_event_struct::ctx, SSH_ERROR, ssh_event_fd_wrapper_callback, SSH_INVALID_SOCKET, SSH_OK, ssh_poll_ctx_add, ssh_poll_free, ssh_poll_new, ssh_event_fd_wrapper::userdata.
Referenced by default_handle_session_cb, handle_kbdint_session_cb, handle_session, message_callback, ssh_select.
int ssh_event_add_poll(ssh_event event, ssh_poll_handle p)
Add a poll handle to the event.
event the ssh_event p the poll handle SSH_OK on success SSH_ERROR on failure
References ssh_event_struct::ctx, ssh_poll_ctx_add.
Referenced by ssh_connector_set_event.
void ssh_event_remove_poll(ssh_event event, ssh_poll_handle p)
remove a poll handle to the event.
event the ssh_event p the poll handle
References ssh_event_struct::ctx, ssh_poll_ctx_remove.
Referenced by ssh_connector_remove_event.
int ssh_event_add_session(ssh_event event, ssh_session session)
remove the poll handle from session and assign them to a event, when used in blocking mode.
event The ssh_event object session The session to add to the event. SSH_OK on success SSH_ERROR on failure
References ssh_event_struct::ctx, ssh_iterator::data, ssh_session_struct::default_poll_ctx, ssh_iterator::next, ssh_poll_ctx_struct::pollptrs, ssh_poll_ctx_struct::polls_used, ssh_poll_handle_struct::session, session, SSH_ERROR, ssh_list_append, ssh_list_get_iterator, SSH_OK, ssh_poll_ctx_add, ssh_poll_ctx_remove.
Referenced by default_handle_session_cb, handle_kbdint_session_cb, handle_session, LLVMFuzzerTestOneInput, main, pkd_exec_hello, ssh_channel_select, ssh_connector_set_event, ssh_select, test_ssh_channel_request_x11.
int ssh_event_add_connector(ssh_event event, ssh_connector connector)
Add a connector to the SSH event loop.
event The SSH event loop connector The connector object SSH_OK SSH_ERROR in case of error
References ssh_connector_set_event.
Referenced by select_loop.
int ssh_event_dopoll(ssh_event event, int timeout)
Poll all the sockets and sessions associated through an event object.i.
If any of the events are set after the poll, the call back functions of the sessions or sockets will be called. This function should be called once within the programs main loop. event The ssh_event object to poll. timeout An upper limit on the time for which the poll will block, in milliseconds. Specifying a negative value means an infinite timeout. This parameter is passed to the poll() function. SSH_OK on success. SSH_ERROR Error happened during the poll. SSH_AGAIN Timeout occured
References ssh_event_struct::ctx, rc, SSH_ERROR, ssh_poll_ctx_dopoll.
Referenced by default_handle_session_cb, handle_kbdint_session_cb, handle_session, LLVMFuzzerTestOneInput, main, pkd_exec_hello, select_loop, ssh_channel_select, ssh_select, test_ssh_channel_request_x11.
int ssh_event_remove_fd(ssh_event event, socket_t fd)
Remove a socket fd from an event context.
event The ssh_event object. fd The fd to remove. SSH_OK on success SSH_ERROR on failure
References ssh_poll_handle_struct::cb, ssh_poll_handle_struct::cb_data, ssh_poll_handle_struct::ctx, ssh_event_struct::ctx, ssh_pollfd_struct::fd, ssh_poll_ctx_struct::pollfds, ssh_poll_ctx_struct::pollptrs, rc, SAFE_FREE, ssh_poll_handle_struct::session, SSH_ERROR, ssh_event_fd_wrapper_callback, SSH_OK, ssh_poll_free.
Referenced by _close_socket, default_handle_session_cb, handle_kbdint_session_cb, handle_session, ssh_select.
int ssh_event_remove_session(ssh_event event, ssh_session session)
Remove a session object from an event context.
event The ssh_event object. session The session to remove. SSH_OK on success SSH_ERROR on failure
References ssh_poll_handle_struct::ctx, ssh_event_struct::ctx, ssh_iterator::data, ssh_session_struct::default_poll_ctx, ssh_iterator::next, ssh_poll_ctx_struct::pollptrs, rc, ssh_poll_handle_struct::session, session, SSH_ERROR, ssh_list_get_iterator, ssh_list_remove, SSH_OK, ssh_poll_ctx_add, ssh_poll_ctx_remove.
Referenced by pkd_exec_hello, ssh_connector_remove_event.
int ssh_event_remove_connector(ssh_event event, ssh_connector connector)
Remove a connector from an event context.
event The ssh_event object. connector connector object to remove SSH_OK on success SSH_ERROR on failure
References ssh_connector_remove_event.
Referenced by select_loop.
void ssh_event_free(ssh_event event)
Free an event context.
event The ssh_event object to free. Note: you have to manually remove sessions and socket fds before freeing the event object.
References ssh_poll_handle_struct::ctx, ssh_event_struct::ctx, ssh_session_struct::default_poll_ctx, ssh_poll_ctx_struct::pollptrs, ssh_poll_ctx_struct::polls_used, ssh_poll_handle_struct::session, ssh_list_free, ssh_poll_ctx_add, ssh_poll_ctx_free, ssh_poll_ctx_remove.
Referenced by LLVMFuzzerTestOneInput, main, pkd_exec_hello, run_server, select_loop, ssh_channel_select, ssh_select, test_ssh_channel_request_x11.