samplesshd-cb.c
KEYS_FOLDER
USER
PASSWORD
int authenticated
Referenced by auth_gssapi_mic, auth_password, main.
int tries
Referenced by auth_password.
int error
Referenced by auth_password, main.
ssh_channel chan
Referenced by main, new_session_channel.
struct ssh_channel_callbacks_struct channel_cb
Referenced by new_session_channel.
static int auth_password(ssh_session session, const char *user, const char *password, void *userdata)
References authenticated, error, PASSWORD, session, SSH_AUTH_DENIED, SSH_AUTH_SUCCESS, ssh_disconnect, tries, USER, user.
Referenced by main.
static int auth_gssapi_mic(ssh_session session, const char *user, const char *principal, void *userdata)
References authenticated, session, SSH_AUTH_SUCCESS, ssh_gssapi_get_creds, user.
Referenced by main.
static int pty_request(ssh_session session, ssh_channel channel, const char *term, int x, int y, int px, int py, void *userdata)
References session.
static int shell_request(ssh_session session, ssh_channel channel, void *userdata)
static ssh_channel new_session_channel(ssh_session session, void *userdata)
References chan, channel_cb, session, ssh_callbacks_init, ssh_channel_new, ssh_set_channel_callbacks, ssh_channel_callbacks_struct::userdata.
Referenced by main.
int main(int argc, char **argv)
References argp, auth_gssapi_mic, auth_password, authenticated, cb, chan, error, KEYS_FOLDER, mainloop, new_session_channel, session, SSH_AUTH_METHOD_GSSAPI_MIC, SSH_AUTH_METHOD_PASSWORD, ssh_bind_accept, ssh_bind_free, ssh_bind_listen, ssh_bind_new, SSH_BIND_OPTIONS_DSAKEY, SSH_BIND_OPTIONS_RSAKEY, ssh_bind_options_set, ssh_callbacks_init, ssh_channel_read, ssh_channel_write, ssh_disconnect, SSH_ERROR, ssh_event_add_session, ssh_event_dopoll, ssh_event_new, ssh_finalize, ssh_get_error, ssh_handle_key_exchange, ssh_new, ssh_set_auth_methods, ssh_set_server_callbacks, ssh_callbacks_struct::userdata.