main.c
TEST_READ
TEST_WRITE
NTHREADS
FILESIZE
unsigned char samplefile[FILESIZE][FILESIZE]
Referenced by main, sftp_test.
volatile int stop
Referenced by signal_stop, thread.
const char* hosts[][]
Referenced by thread.
void signal_stop()
References stop.
Referenced by main.
SSH_SESSION * connect_host(const char *hostname)
References options, session, SSH_AUTH_ERROR, SSH_AUTH_SUCCESS, ssh_connect, ssh_disconnect, ssh_finalize, ssh_get_error, ssh_log, SSH_LOG_FUNCTIONS, ssh_new, SSH_SERVER_ERROR, SSH_SERVER_FOUND_OTHER, SSH_SERVER_KNOWN_CHANGED, SSH_SERVER_KNOWN_OK, SSH_SERVER_NOT_KNOWN, ssh_session_is_known_server, ssh_userauth_autopubkey, ssh_userauth_none.
Referenced by docycle.
int sftp_test(SSH_SESSION *session, int test)
References FILESIZE, name, samplefile, session, sftp_close, sftp_free, sftp_init, sftp_new, sftp_open, sftp_write, SSH_ERROR, ssh_get_error, SSH_OK, test, TEST_WRITE.
Referenced by docycle.
int docycle(const char *host, int test)
References connect_host, host, session, sftp_test, ssh_disconnect, SSH_ERROR, SSH_OK, test.
Referenced by thread.
int thread()
References docycle, hosts, SSH_OK, stop, TEST_WRITE.
Referenced by main.
int main(int argc, char **argv)
References FILESIZE, NTHREADS, samplefile, signal_stop, ssh_finalize, ssh_init, thread, time.