socket.c
ssh_socket_states_e
int sockets_initialized
Referenced by ssh_socket_cleanup, ssh_socket_init.
static ssize_t ssh_socket_unbuffered_read(ssh_socket s, void *buffer, uint32_t len)
References buffer, ssh_socket_struct::data_except, ssh_socket_struct::fd, ssh_socket_struct::fd_is_socket, ssh_socket_struct::last_errno, rc, ssh_socket_struct::read_wontblock, s.
Referenced by ssh_socket_pollcallback.
static ssize_t ssh_socket_unbuffered_write(ssh_socket s, const void *buffer, uint32_t len)
References buffer, ssh_socket_struct::data_except, ssh_socket_struct::fd, ssh_socket_struct::fd_is_socket, ssh_socket_struct::last_errno, ssh_socket_struct::poll_handle, POLLOUT, s, SSH_LOG, SSH_LOG_PACKET, ssh_poll_get_events, ssh_poll_set_events, ssh_socket_struct::write_wontblock.
Referenced by ssh_socket_nonblocking_flush.
int ssh_socket_init(void)
References sockets_initialized, ssh_poll_init.
Referenced by libssh_constructor.
void ssh_socket_cleanup(void)
Cleanup the socket system.
References sockets_initialized, ssh_poll_cleanup.
Referenced by _ssh_finalize.
ssh_socket ssh_socket_new(ssh_session session)
References ssh_socket_struct::data_except, ssh_socket_struct::fd, ssh_socket_struct::fd_is_socket, ssh_socket_struct::in_buffer, ssh_socket_struct::last_errno, ssh_socket_struct::out_buffer, ssh_socket_struct::poll_handle, ssh_socket_struct::read_wontblock, s, SAFE_FREE, ssh_socket_struct::session, session, SSH_BUFFER_FREE, ssh_buffer_new, SSH_INVALID_SOCKET, ssh_set_error_oom, SSH_SOCKET_NONE, ssh_socket_struct::state, ssh_socket_struct::write_wontblock.
Referenced by main, ssh_agent_new, ssh_bind_accept_fd, ssh_new.
void ssh_socket_reset(ssh_socket s)
References ssh_socket_struct::data_except, ssh_socket_struct::fd, ssh_socket_struct::fd_is_socket, ssh_socket_struct::in_buffer, ssh_socket_struct::last_errno, ssh_socket_struct::out_buffer, ssh_socket_struct::poll_handle, ssh_socket_struct::proxy_pid, ssh_socket_struct::read_wontblock, s, ssh_buffer_reinit, SSH_INVALID_SOCKET, SSH_SOCKET_NONE, ssh_socket_struct::state, ssh_socket_struct::write_wontblock.
Referenced by ssh_disconnect.
void ssh_socket_set_callbacks(ssh_socket s, ssh_socket_callbacks callbacks)
References ssh_socket_struct::callbacks, callbacks, s.
Referenced by main, ssh_connect, ssh_handle_key_exchange, ssh_packet_register_socket_callback.
int ssh_socket_pollcallback(struct ssh_poll_handle_struct *p, socket_t fd, int revents, void *v_s)
SSH poll callback. This callback will be used when an event caught on the socket.
p Poll object this callback belongs to. fd The raw socket. revents The current poll events on the socket. userdata Userdata to be passed to the callback function, in this case the socket object. 0 on success, < 0 when the poll object has been removed from its poll context.
References buffer, ssh_socket_struct::callbacks, ssh_socket_callbacks_struct::connected, ssh_socket_callbacks_struct::controlflow, ssh_socket_callbacks_struct::data, ssh_socket_callbacks_struct::exception, ssh_socket_struct::in_buffer, ssh_counter_struct::in_bytes, ssh_socket_struct::last_errno, MAX_BUF_SIZE, ssh_socket_struct::out_buffer, ssh_socket_struct::poll_handle, POLLERR, POLLHUP, POLLIN, POLLOUT, POLLWRNORM, rc, ssh_socket_struct::read_wontblock, s, ssh_socket_struct::session, ssh_session_struct::socket_counter, ssh_buffer_add_data, ssh_buffer_get, ssh_buffer_get_len, ssh_buffer_pass_bytes, SSH_LOG, SSH_LOG_PACKET, SSH_LOG_TRACE, ssh_poll_remove_events, ssh_poll_set_events, ssh_socket_close, SSH_SOCKET_CONNECTED, SSH_SOCKET_CONNECTED_ERROR, SSH_SOCKET_CONNECTED_OK, SSH_SOCKET_CONNECTING, SSH_SOCKET_ERROR, SSH_SOCKET_EXCEPTION_EOF, SSH_SOCKET_EXCEPTION_ERROR, SSH_SOCKET_FLOW_WRITEWONTBLOCK, ssh_socket_get_fd, ssh_socket_is_open, ssh_socket_nonblocking_flush, ssh_socket_set_blocking, ssh_socket_unbuffered_read, ssh_socket_struct::state, ssh_socket_callbacks_struct::userdata, ssh_socket_struct::write_wontblock.
Referenced by ssh_socket_get_poll_handle.
ssh_poll_handle ssh_socket_get_poll_handle(ssh_socket s)
References ssh_socket_struct::fd, ssh_socket_struct::poll_handle, s, ssh_poll_new, ssh_socket_pollcallback.
Referenced by ssh_bind_accept_fd, ssh_handle_packets, ssh_poll_ctx_add_socket, ssh_socket_connect_proxycommand, ssh_socket_set_fd.
void ssh_socket_free(ssh_socket s)
References ssh_socket_struct::in_buffer, ssh_socket_struct::out_buffer, s, SAFE_FREE, SSH_BUFFER_FREE, ssh_socket_close.
Referenced by ssh_agent_free, ssh_bind_accept, ssh_bind_accept_fd, ssh_free.
int ssh_socket_unix(ssh_socket s, const char *path)
References s, ssh_socket_struct::session, SSH_FATAL, SSH_INVALID_SOCKET, ssh_set_error, ssh_socket_set_fd.
Referenced by agent_connect.
void ssh_socket_close(ssh_socket s)
References CLOSE_SOCKET, ssh_socket_struct::fd, ssh_socket_struct::last_errno, ssh_socket_struct::poll_handle, ssh_socket_struct::proxy_pid, s, SSH_LOG, SSH_LOG_TRACE, SSH_LOG_WARN, ssh_poll_free, SSH_SOCKET_CLOSED, ssh_socket_is_open, ssh_socket_struct::state.
Referenced by ssh_agent_close, ssh_client_connection_callback, ssh_disconnect, SSH_PACKET_CALLBACK, ssh_server_connection_callback, ssh_silent_disconnect, ssh_socket_free, ssh_socket_nonblocking_flush, ssh_socket_pollcallback.
void ssh_socket_set_fd(ssh_socket s, socket_t fd)
References ssh_socket_struct::fd, ssh_socket_struct::poll_handle, POLLOUT, POLLWRNORM, s, ssh_poll_add_events, ssh_poll_set_events, ssh_poll_set_fd, SSH_SOCKET_CONNECTING, ssh_socket_get_poll_handle, ssh_socket_struct::state.
Referenced by ssh_bind_accept_fd, ssh_connect, ssh_set_agent_socket, ssh_socket_connect, ssh_socket_connect_proxycommand, ssh_socket_unix.
socket_t ssh_socket_get_fd(ssh_socket s)
References ssh_socket_struct::fd, s.
Referenced by atomicio, ssh_get_fd, ssh_socket_pollcallback.
int ssh_socket_is_open(ssh_socket s)
References ssh_socket_struct::fd, s, SSH_INVALID_SOCKET.
Referenced by channel_protocol_select, ssh_agent_is_running, ssh_disconnect, ssh_send_debug, ssh_send_ignore, ssh_socket_close, ssh_socket_nonblocking_flush, ssh_socket_pollcallback.
int ssh_socket_fd_isset(ssh_socket s, fd_set *set)
References ssh_socket_struct::fd, s, set, SSH_INVALID_SOCKET.
void ssh_socket_fd_set(ssh_socket s, fd_set *set, socket_t *max_fd)
References ssh_socket_struct::fd, s, set, SSH_INVALID_SOCKET.
int ssh_socket_write(ssh_socket s, const void *buffer, int len)
References buffer, ssh_socket_struct::out_buffer, s, ssh_socket_struct::session, ssh_buffer_add_data, SSH_ERROR, SSH_OK, ssh_set_error_oom, ssh_socket_nonblocking_flush.
Referenced by data_rcv, ssh_packet_write, ssh_send_banner.
int ssh_socket_nonblocking_flush(ssh_socket s)
References ssh_session_struct::alive, ssh_socket_struct::callbacks, ssh_socket_callbacks_struct::exception, ssh_socket_struct::last_errno, ssh_socket_struct::out_buffer, ssh_counter_struct::out_bytes, ssh_socket_struct::poll_handle, POLLOUT, s, ssh_socket_struct::session, session, ssh_session_struct::socket_counter, SSH_AGAIN, ssh_buffer_get, ssh_buffer_get_len, ssh_buffer_pass_bytes, SSH_ERROR, SSH_FATAL, SSH_OK, ssh_poll_add_events, ssh_set_error, ssh_socket_close, SSH_SOCKET_EXCEPTION_ERROR, ssh_socket_is_open, ssh_socket_unbuffered_write, ssh_socket_callbacks_struct::userdata, ssh_socket_struct::write_wontblock.
Referenced by data_rcv, ssh_socket_pollcallback, ssh_socket_write.
void ssh_socket_set_write_wontblock(ssh_socket s)
References s, ssh_socket_struct::write_wontblock.
Referenced by ssh_set_fd_towrite.
void ssh_socket_set_read_wontblock(ssh_socket s)
References ssh_socket_struct::read_wontblock, s.
Referenced by ssh_set_fd_toread.
void ssh_socket_set_except(ssh_socket s)
References ssh_socket_struct::data_except, s.
Referenced by ssh_set_fd_except.
int ssh_socket_data_available(ssh_socket s)
References ssh_socket_struct::read_wontblock, s.
Referenced by channel_protocol_select.
int ssh_socket_data_writable(ssh_socket s)
References s, ssh_socket_struct::write_wontblock.
Referenced by channel_protocol_select.
int ssh_socket_buffered_write_bytes(ssh_socket s)
References ssh_socket_struct::out_buffer, s, ssh_buffer_get_len.
Referenced by ssh_flush_termination.
int ssh_socket_get_status(ssh_socket s)
References ssh_socket_struct::data_except, ssh_socket_struct::in_buffer, ssh_socket_struct::out_buffer, s, ssh_buffer_get_len, SSH_CLOSED_ERROR, SSH_READ_PENDING, SSH_WRITE_PENDING.
Referenced by ssh_get_status.
int ssh_socket_get_poll_flags(ssh_socket s)
References ssh_socket_struct::poll_handle, POLLIN, POLLOUT, s, ssh_poll_get_events, SSH_READ_PENDING, SSH_WRITE_PENDING.
Referenced by ssh_get_poll_flags.
int ssh_socket_set_nonblocking(socket_t fd)
Referenced by ssh_connect_host_nonblocking.
int ssh_socket_set_blocking(socket_t fd)
Referenced by ssh_socket_pollcallback.
int ssh_socket_connect(ssh_socket s, const char *host, uint16_t port, const char *bind_addr)
References host, port, s, ssh_socket_struct::session, ssh_connect_host_nonblocking, SSH_ERROR, SSH_FATAL, SSH_INVALID_SOCKET, SSH_LOG, SSH_LOG_PROTOCOL, SSH_OK, ssh_set_error, SSH_SOCKET_NONE, ssh_socket_set_fd, ssh_socket_struct::state.
Referenced by main, ssh_connect.
void ssh_execute_command(const char *command, socket_t in, socket_t out)
References shell, SSH_LOG, SSH_LOG_WARNING.
Referenced by ssh_socket_connect_proxycommand.
int ssh_socket_connect_proxycommand(ssh_socket s, const char *command)
References ssh_socket_struct::callbacks, ssh_socket_callbacks_struct::connected, ssh_socket_struct::fd_is_socket, POLLIN, POLLOUT, ssh_socket_struct::proxy_pid, rc, s, SSH_ERROR, ssh_execute_command, SSH_LOG, SSH_LOG_PROTOCOL, SSH_OK, ssh_poll_set_events, SSH_SOCKET_CONNECTED, SSH_SOCKET_CONNECTED_OK, ssh_socket_get_poll_handle, SSH_SOCKET_NONE, ssh_socket_set_fd, ssh_socket_struct::state, ssh_socket_callbacks_struct::userdata.
Referenced by ssh_connect.