ssh_server_fork.c
KEYS_FOLDER
USER
PASS
BUF_SIZE
SESSION_END
SFTP_SERVER_PATH
DEF_STR_SIZE
char authorizedkeys[DEF_STR_SIZE][DEF_STR_SIZE]
Referenced by auth_publickey, handle_session.
static void set_default_keys(ssh_bind sshbind, int rsa_already_set, int dsa_already_set, int ecdsa_already_set)
References KEYS_FOLDER, SSH_BIND_OPTIONS_DSAKEY, SSH_BIND_OPTIONS_ECDSAKEY, SSH_BIND_OPTIONS_HOSTKEY, SSH_BIND_OPTIONS_RSAKEY, ssh_bind_options_set.
Referenced by main.
static int data_function(ssh_session session, ssh_channel channel, void *data, uint32_t len, int is_stderr, void *userdata)
References channel_data_struct::child_stdin, channel_data_struct::pid, session.
Referenced by handle_session.
static int pty_request(ssh_session session, ssh_channel channel, const char *term, int cols, int rows, int py, int px, void *userdata)
References channel_data_struct::pty_master, channel_data_struct::pty_slave, session, SSH_ERROR, SSH_OK, channel_data_struct::winsize.
Referenced by handle_session.
static int pty_resize(ssh_session session, ssh_channel channel, int cols, int rows, int py, int px, void *userdata)
References channel_data_struct::pty_master, session, SSH_ERROR, channel_data_struct::winsize.
Referenced by handle_session.
static int exec_pty(const char *mode, const char *command, struct channel_data_struct *cdata)
References channel_data_struct::child_stdin, channel_data_struct::child_stdout, channel_data_struct::pid, channel_data_struct::pty_master, channel_data_struct::pty_slave, SSH_ERROR, SSH_OK.
Referenced by exec_request, shell_request.
static int exec_nopty(const char *command, struct channel_data_struct *cdata)
References channel_data_struct::child_stderr, channel_data_struct::child_stdin, channel_data_struct::child_stdout, channel_data_struct::pid, SSH_ERROR, SSH_OK.
Referenced by exec_request.
static int exec_request(ssh_session session, ssh_channel channel, const char *command, void *userdata)
References exec_nopty, exec_pty, channel_data_struct::pid, channel_data_struct::pty_master, channel_data_struct::pty_slave, session, SSH_ERROR.
Referenced by handle_session, subsystem_request.
static int shell_request(ssh_session session, ssh_channel channel, void *userdata)
References exec_pty, channel_data_struct::pid, channel_data_struct::pty_master, channel_data_struct::pty_slave, session, SSH_ERROR, SSH_OK.
Referenced by handle_session.
static int subsystem_request(ssh_session session, ssh_channel channel, const char *subsystem, void *userdata)
References exec_request, session, SFTP_SERVER_PATH, SSH_ERROR.
Referenced by handle_session.
static int auth_password(ssh_session session, const char *user, const char *pass, void *userdata)
References session_data_struct::auth_attempts, session_data_struct::authenticated, PASS, session, SSH_AUTH_DENIED, SSH_AUTH_SUCCESS, user, USER.
Referenced by handle_session.
static int auth_publickey(ssh_session session, const char *user, struct ssh_key_struct *pubkey, char signature_state, void *userdata)
References session_data_struct::authenticated, authorizedkeys, key, pubkey, session, SSH_AUTH_DENIED, SSH_AUTH_SUCCESS, ssh_key_cmp, SSH_KEY_CMP_PUBLIC, ssh_key_free, SSH_OK, ssh_pki_import_pubkey_file, SSH_PUBLICKEY_STATE_NONE, SSH_PUBLICKEY_STATE_VALID, user.
Referenced by handle_session.
static ssh_channel channel_open(ssh_session session, void *userdata)
References session_data_struct::channel, session, ssh_channel_new.
Referenced by handle_session.
static int process_stdout(socket_t fd, int revents, void *userdata)
References BUF_SIZE, session_data_struct::channel, POLLIN, ssh_channel_write.
Referenced by handle_session.
static int process_stderr(socket_t fd, int revents, void *userdata)
References BUF_SIZE, session_data_struct::channel, POLLIN, ssh_channel_write_stderr.
Referenced by handle_session.
static void handle_session(ssh_event event, ssh_session session)
References session_data_struct::auth_attempts, auth_password, ssh_server_callbacks_struct::auth_pubkey_function, auth_publickey, session_data_struct::authenticated, authorizedkeys, session_data_struct::channel, channel_cb, channel_open, channel_data_struct::child_stderr, channel_data_struct::child_stdin, channel_data_struct::child_stdout, data_function, channel_data_struct::event, exec_request, channel_data_struct::pid, POLLIN, process_stderr, process_stdout, channel_data_struct::pty_master, pty_request, pty_resize, rc, session, SESSION_END, shell_request, SSH_AUTH_METHOD_PASSWORD, SSH_AUTH_METHOD_PUBLICKEY, ssh_callbacks_init, ssh_channel_close, ssh_channel_is_open, ssh_channel_request_send_exit_status, ssh_channel_send_eof, SSH_ERROR, ssh_event_add_fd, ssh_event_add_session, ssh_event_dopoll, ssh_event_remove_fd, ssh_get_error, ssh_get_status, ssh_handle_key_exchange, SSH_OK, ssh_set_auth_methods, ssh_set_channel_callbacks, ssh_set_server_callbacks, subsystem_request, ssh_server_callbacks_struct::userdata, ssh_channel_callbacks_struct::userdata.
Referenced by main.
static void sigchld_handler(int signo)
Referenced by main.
int main(int argc, char **argv)
References argp, handle_session, rc, session, set_default_keys, sigchld_handler, ssh_bind_accept, ssh_bind_free, ssh_bind_listen, ssh_bind_new, ssh_disconnect, SSH_ERROR, ssh_event_free, ssh_event_new, ssh_finalize, ssh_free, ssh_get_error, ssh_init, ssh_new.