sshd_direct-tcpip.c
SAFE_FREE
__unused__
UNUSED_PARAM
KEYS_FOLDER
USER
PASSWORD
bool authenticated
Referenced by auth_gssapi_mic, auth_password, main.
int tries
Referenced by auth_password.
bool error_set
Referenced by auth_password, main.
int sockets_cnt
Referenced by _close_socket, open_tcp_socket, stack_socket_close.
ssh_event mainloop
Referenced by _close_socket, main, message_callback.
struct cleanup_node_struct* cleanup_stack
Referenced by main, stack_socket_close.
struct ssh_channel_callbacks_struct channel_cb
static void _close_socket(struct event_fd_data_struct event_fd_data)
References _ssh_log, mainloop, event_fd_data_struct::p_fd, sockets_cnt, ssh_event_remove_fd, SSH_INVALID_SOCKET, SSH_LOG_FUNCTIONS.
Referenced by do_cleanup.
static void cleanup_push(struct cleanup_node_struct **head_ref, struct event_fd_data_struct *new_data)
References cleanup_node_struct::data, cleanup_node_struct::next.
Referenced by stack_socket_close.
static void do_cleanup(struct cleanup_node_struct **head_ref)
References _close_socket, _ssh_log, event_fd_data_struct::channel, cleanup_node_struct::data, cleanup_node_struct::next, SAFE_FREE, ssh_channel_close, ssh_channel_free, ssh_channel_is_closed, SSH_LOG_FUNCTIONS, ssh_remove_channel_callbacks.
Referenced by main.
static int auth_password(ssh_session session, const char *user, const char *password, void *userdata)
References _ssh_log, authenticated, error_set, PASSWORD, session, SSH_AUTH_DENIED, SSH_AUTH_SUCCESS, ssh_disconnect, SSH_LOG_PROTOCOL, tries, user, USER.
Referenced by main.
static int auth_gssapi_mic(ssh_session session, const char *user, const char *principal, void *userdata)
References authenticated, session, SSH_AUTH_SUCCESS, ssh_gssapi_get_creds, user.
Referenced by main.
static int subsystem_request(ssh_session session, ssh_channel channel, const char *subsystem, void *userdata)
static ssh_channel new_session_channel(ssh_session session, void *userdata)
References _ssh_log, session, SSH_LOG_PROTOCOL, ssh_channel_callbacks_struct::userdata.
Referenced by main.
static void stack_socket_close(UNUSED_PARAM(ssh_session session), struct event_fd_data_struct *event_fd_data)
References _ssh_log, cleanup_push, cleanup_stack, event_fd_data_struct::p_fd, sockets_cnt, SSH_LOG_FUNCTIONS, event_fd_data_struct::stacked.
Referenced by my_channel_close_function, my_channel_data_function, my_channel_eof_function, my_fd_data_function.
static int service_request(ssh_session session, const char *service, void *userdata)
References _ssh_log, session, SSH_LOG_PROTOCOL, ssh_channel_callbacks_struct::userdata.
Referenced by main.
static void global_request(ssh_session session, ssh_message message, void *userdata)
References _ssh_log, session, SSH_LOG_PROTOCOL, ssh_message_type, ssh_channel_callbacks_struct::userdata.
Referenced by main.
static void my_channel_close_function(ssh_session session, ssh_channel channel, void *userdata)
References _ssh_log, session, SSH_LOG_PROTOCOL, stack_socket_close.
Referenced by message_callback.
static void my_channel_eof_function(ssh_session session, ssh_channel channel, void *userdata)
References _ssh_log, event_fd_data_struct::p_fd, session, SSH_LOG_PROTOCOL, stack_socket_close.
Referenced by message_callback.
static void my_channel_exit_status_function(ssh_session session, ssh_channel channel, int exit_status, void *userdata)
References _ssh_log, event_fd_data_struct::p_fd, session, SSH_LOG_PROTOCOL.
Referenced by message_callback.
static int my_channel_data_function(ssh_session session, ssh_channel channel, void *data, uint32_t len, UNUSED_PARAM(int is_stderr), void *userdata)
References _ssh_log, event_fd_data_struct::channel, event_fd_data_struct::p_fd, session, SSH_LOG_FUNCTIONS, SSH_LOG_PROTOCOL, SSH_LOG_WARNING, stack_socket_close, event_fd_data_struct::stacked.
Referenced by message_callback.
static int my_fd_data_function(UNUSED_PARAM(socket_t fd), int revents, void *userdata)
References _ssh_log, event_fd_data_struct::channel, event_fd_data_struct::p_fd, POLLERR, POLLHUP, POLLIN, POLLNVAL, POLLOUT, POLLPRI, session, ssh_channel_close, ssh_channel_get_session, ssh_channel_is_closed, ssh_channel_is_open, ssh_channel_send_eof, ssh_channel_write, ssh_is_blocking, SSH_LOG_FUNCTIONS, SSH_LOG_PROTOCOL, SSH_LOG_WARNING, ssh_set_blocking, stack_socket_close.
Referenced by message_callback.
static int open_tcp_socket(ssh_message msg)
References _ssh_log, host, sockets_cnt, SSH_LOG_FUNCTIONS, SSH_LOG_PROTOCOL, SSH_LOG_WARNING, ssh_message_channel_request_open_destination, ssh_message_channel_request_open_destination_port.
Referenced by message_callback.
static int message_callback(ssh_session session, ssh_message message, void *userdata)
References _ssh_log, event_fd_data_struct::cb_chan, event_fd_data_struct::channel, ssh_channel_callbacks_struct::channel_close_function, ssh_channel_callbacks_struct::channel_data_function, ssh_channel_callbacks_struct::channel_eof_function, ssh_channel_callbacks_struct::channel_exit_status_function, mainloop, my_channel_close_function, my_channel_data_function, my_channel_eof_function, my_channel_exit_status_function, my_fd_data_function, open_tcp_socket, event_fd_data_struct::p_fd, POLLIN, session, ssh_callbacks_init, SSH_CHANNEL_DIRECT_TCPIP, ssh_event_add_fd, SSH_LOG_PACKET, SSH_LOG_PROTOCOL, SSH_LOG_WARNING, ssh_message_channel_request_open_reply_accept, ssh_message_subtype, ssh_message_type, SSH_REQUEST_CHANNEL_OPEN, ssh_set_channel_callbacks, event_fd_data_struct::stacked, ssh_channel_callbacks_struct::userdata.
Referenced by main.
int main(int argc, char **argv)
References argp, auth_gssapi_mic, auth_password, authenticated, cb, cleanup_stack, do_cleanup, error_set, global_request, KEYS_FOLDER, mainloop, message_callback, new_session_channel, service_request, session, SSH_AUTH_METHOD_GSSAPI_MIC, SSH_AUTH_METHOD_PASSWORD, ssh_bind_accept, ssh_bind_free, ssh_bind_listen, ssh_bind_new, SSH_BIND_OPTIONS_DSAKEY, SSH_BIND_OPTIONS_RSAKEY, ssh_bind_options_set, ssh_callbacks_init, ssh_disconnect, SSH_ERROR, ssh_event_add_session, ssh_event_dopoll, ssh_event_new, ssh_finalize, ssh_get_error, ssh_handle_key_exchange, ssh_new, ssh_set_auth_methods, ssh_set_callbacks, ssh_set_message_callback, ssh_set_server_callbacks, ssh_callbacks_struct::userdata.