test_server.h
void free_server_state(struct server_state_st *state)
References server_state_st::address, server_state_st::config_file, server_state_st::dsa_key, server_state_st::ecdsa_key, server_state_st::ed25519_key, server_state_st::expected_password, server_state_st::expected_username, server_state_st::host_key, server_state_st::pcap_file, server_state_st::rsa_key, SAFE_FREE.
Referenced by main, run_server, teardown_default_server, teardown_kbdint_server, try_config_content.
int run_server(struct server_state_st *state)
References server_state_st::address, server_state_st::config_file, server_state_st::dsa_key, server_state_st::ecdsa_key, free_server_state, server_state_st::handle_session, server_state_st::host_key, server_state_st::parse_global_config, server_state_st::port, rc, server_state_st::rsa_key, session, sigchld_handler, ssh_bind_accept, ssh_bind_free, ssh_bind_listen, ssh_bind_new, SSH_BIND_OPTIONS_BINDADDR, SSH_BIND_OPTIONS_BINDPORT, SSH_BIND_OPTIONS_DSAKEY, SSH_BIND_OPTIONS_ECDSAKEY, SSH_BIND_OPTIONS_HOSTKEY, SSH_BIND_OPTIONS_LOG_VERBOSITY, ssh_bind_options_parse_config, SSH_BIND_OPTIONS_PROCESS_CONFIG, SSH_BIND_OPTIONS_RSAKEY, ssh_bind_options_set, ssh_disconnect, SSH_ERROR, ssh_event_free, ssh_event_new, ssh_free, ssh_get_error, ssh_new, server_state_st::verbosity.
Referenced by fork_run_server, main.
pid_t fork_run_server(struct server_state_st *state)
References rc, run_server, sigchld_handler.
Referenced by setup_default_server, setup_kbdint_server, start_server.