threads.h
SSH_MUTEX
SSH_MUTEX_STATIC_INIT
int ssh_threads_init(void)
References crypto_thread_init, rc, SSH_OK, ssh_threads_get_default, user_callbacks.
Referenced by libssh_constructor.
void ssh_threads_finalize(void)
References crypto_thread_finalize.
Referenced by _ssh_finalize.
const char* ssh_threads_get_type(void)
References ssh_threads_callbacks_struct::type, user_callbacks.
Referenced by ssh_connect.
void ssh_mutex_lock(SSH_MUTEX *mutex)
References rc.
Referenced by _ssh_finalize, libssh_constructor.
void ssh_mutex_unlock(SSH_MUTEX *mutex)
Referenced by _ssh_finalize, libssh_constructor.
struct ssh_threads_callbacks_struct* ssh_threads_get_default(void)
Returns a pointer to the appropriate callbacks structure for the environment, to be used with ssh_threads_set_callbacks.
A pointer to a ssh_threads_callbacks_struct to be used with ssh_threads_set_callbacks. ssh_threads_set_callbacks
References ssh_threads_winlock.
int crypto_thread_init(struct ssh_threads_callbacks_struct *user_callbacks)
References cb, crypto_thread_finalize, gcrypt_threads_callbacks, libcrypto_lock_callback, libcrypto_mutexes, ssh_threads_callbacks_struct::mutex_destroy, ssh_threads_callbacks_struct::mutex_init, ssh_threads_callbacks_struct::mutex_lock, ssh_threads_callbacks_struct::mutex_unlock, SSH_ERROR, SSH_OK, ssh_threads_callbacks_struct::thread_id, ssh_threads_callbacks_struct::type, user_callbacks.
Referenced by ssh_threads_init, ssh_threads_set_callbacks.
void crypto_thread_finalize(void)
References libcrypto_mutexes, ssh_threads_callbacks_struct::mutex_destroy, SAFE_FREE, user_callbacks.
Referenced by crypto_thread_init, ssh_threads_finalize, ssh_threads_set_callbacks.