token.c
void ssh_tokens_free(struct ssh_tokens_st *tokens)
References ssh_tokens_st::buffer, explicit_bzero, SAFE_FREE, ssh_tokens_st::tokens.
Referenced by ssh_find_all_matching, ssh_find_matching, ssh_get_knownhost_line, ssh_is_server_known, ssh_remove_duplicates, ssh_tokenize, tokenize_compare_expected, torture_server_config_ciphers, torture_server_config_kex, torture_server_config_macs.
struct ssh_tokens_st* ssh_tokenize(const char *chain, char separator)
References error, ssh_tokens_free, ssh_tokens_st::tokens.
Referenced by ssh_find_all_matching, ssh_find_matching, ssh_get_knownhost_line, ssh_remove_duplicates, tokenize_compare_expected, torture_server_config_ciphers, torture_server_config_kex, torture_server_config_macs.
char* ssh_find_matching(const char *available_list, const char *preferred_list)
References ssh_tokenize, ssh_tokens_free, ssh_tokens_st::tokens.
Referenced by ssh_kex_select_methods, SSH_PACKET_CALLBACK, torture_find_matching.
char* ssh_find_all_matching(const char *available_list, const char *preferred_list)
References MAX, SAFE_FREE, ssh_tokenize, ssh_tokens_free, ssh_tokens_st::tokens.
Referenced by server_set_kex, ssh_bind_accept_fd, ssh_client_select_hostkeys, ssh_keep_fips_algos, ssh_keep_known_algos, torture_find_all_matching.
char* ssh_remove_duplicates(const char *list)
References SAFE_FREE, ssh_tokenize, ssh_tokens_free, ssh_tokens_st::tokens.
Referenced by ssh_append_without_duplicates, ssh_known_hosts_get_algorithms_names, torture_remove_duplicate.
char* ssh_append_without_duplicates(const char *list, const char *appended_list)
References SAFE_FREE, ssh_remove_duplicates.
Referenced by ssh_client_select_hostkeys, torture_append_without_duplicate.