torture_options.c
LIBSSH_STATIC
_POSIX_PTHREAD_SEMANTICS
LIBSSH_RSA_TESTKEY
LIBSSH_ED25519_TESTKEY
NSS_BUFLEN_PASSWD
static int setup(void **state)
References ssh_session_struct::client, session, ssh_new, SSH_OPTIONS_LOG_VERBOSITY, ssh_options_set, torture_libssh_verbosity, verbosity.
Referenced by torture_run_tests.
static int teardown(void **state)
References ssh_free.
Referenced by torture_run_tests.
static void torture_options_set_host(void **state)
References ssh_session_struct::host, ssh_session_struct::opts, rc, session, SSH_OPTIONS_HOST, ssh_options_set, ssh_session_struct::username.
Referenced by torture_run_tests.
static void torture_options_set_ciphers(void **state)
References ssh_session_struct::opts, rc, session, SSH_CRYPT_C_S, SSH_OPTIONS_CIPHERS_C_S, ssh_options_set, ssh_session_struct::wanted_methods.
Referenced by torture_run_tests.
static void torture_options_set_key_exchange(void **state)
References ssh_session_struct::opts, rc, session, SSH_KEX, SSH_OPTIONS_KEY_EXCHANGE, ssh_options_set, ssh_session_struct::wanted_methods.
Referenced by torture_run_tests.
static void torture_options_set_hostkey(void **state)
References ssh_session_struct::opts, rc, session, SSH_HOSTKEYS, SSH_OPTIONS_HOSTKEYS, ssh_options_set, ssh_session_struct::wanted_methods.
Referenced by torture_run_tests.
static void torture_options_set_pubkey_accepted_types(void **state)
References ssh_session_struct::extensions, ssh_session_struct::opts, ssh_session_struct::pubkey_accepted_types, rc, session, SSH_DIGEST_SHA1, SSH_DIGEST_SHA256, SSH_EXT_SIG_RSA_SHA256, ssh_key_type_to_hash, SSH_KEYTYPE_RSA, SSH_OPTIONS_PUBLICKEY_ACCEPTED_TYPES, ssh_options_set.
Referenced by torture_run_tests.
static void torture_options_set_macs(void **state)
References ssh_session_struct::opts, rc, session, SSH_MAC_S_C, SSH_OPTIONS_HMAC_S_C, ssh_options_set, ssh_session_struct::wanted_methods.
Referenced by torture_run_tests.
static void torture_options_get_host(void **state)
References host, ssh_session_struct::host, ssh_session_struct::opts, rc, session, ssh_options_get, SSH_OPTIONS_HOST, ssh_options_set.
Referenced by torture_run_tests.
static void torture_options_set_port(void **state)
References ssh_session_struct::opts, port, ssh_session_struct::port, rc, session, SSH_OPTIONS_PORT, SSH_OPTIONS_PORT_STR, ssh_options_set.
Referenced by torture_run_tests.
static void torture_options_get_port(void **state)
References rc, session, ssh_options_get_port, SSH_OPTIONS_PORT, ssh_options_set.
Referenced by torture_run_tests.
static void torture_options_get_user(void **state)
References rc, session, SSH_OK, ssh_options_get, ssh_options_set, SSH_OPTIONS_USER, user.
Referenced by torture_run_tests.
static void torture_options_set_fd(void **state)
References ssh_session_struct::fd, ssh_session_struct::opts, rc, session, SSH_ERROR, SSH_INVALID_SOCKET, SSH_OPTIONS_FD, ssh_options_set.
Referenced by torture_run_tests.
static void torture_options_set_user(void **state)
References NSS_BUFLEN_PASSWD, ssh_session_struct::opts, rc, session, ssh_options_set, SSH_OPTIONS_USER, ssh_session_struct::username.
Referenced by torture_run_tests.
static void torture_options_set_identity(void **state)
References ssh_iterator::data, ssh_session_struct::identity, ssh_iterator::next, ssh_session_struct::opts, rc, ssh_list::root, session, SSH_OPTIONS_ADD_IDENTITY, SSH_OPTIONS_IDENTITY, ssh_options_set.
Referenced by torture_run_tests.
static void torture_options_get_identity(void **state)
References ssh_iterator::data, ssh_session_struct::identity, ssh_session_struct::opts, rc, ssh_list::root, SAFE_FREE, session, SSH_OK, SSH_OPTIONS_ADD_IDENTITY, ssh_options_get, SSH_OPTIONS_IDENTITY, ssh_options_set.
Referenced by torture_run_tests.
static void torture_options_set_global_knownhosts(void **state)
References assert_ssh_return_code, ssh_session_struct::global_knownhosts, ssh_session_struct::opts, rc, session, SSH_OPTIONS_GLOBAL_KNOWNHOSTS, ssh_options_set.
Referenced by torture_run_tests.
static void torture_options_get_global_knownhosts(void **state)
References assert_ssh_return_code, ssh_session_struct::global_knownhosts, ssh_session_struct::opts, rc, session, ssh_options_get, SSH_OPTIONS_GLOBAL_KNOWNHOSTS, ssh_options_set, SSH_STRING_FREE_CHAR.
Referenced by torture_run_tests.
static void torture_options_set_knownhosts(void **state)
References assert_ssh_return_code, ssh_session_struct::knownhosts, ssh_session_struct::opts, rc, session, ssh_options_apply, SSH_OPTIONS_KNOWNHOSTS, ssh_options_set.
Referenced by torture_run_tests.
static void torture_options_get_knownhosts(void **state)
References assert_ssh_return_code, ssh_session_struct::knownhosts, ssh_session_struct::opts, rc, session, ssh_options_get, SSH_OPTIONS_KNOWNHOSTS, ssh_options_set, SSH_STRING_FREE_CHAR.
Referenced by torture_run_tests.
static void torture_options_proxycommand(void **state)
References ssh_session_struct::opts, ssh_session_struct::ProxyCommand, rc, session, SSH_OPTIONS_PROXYCOMMAND, ssh_options_set.
Referenced by torture_run_tests.
static void torture_options_config_host(void **state)
References ssh_session_struct::opts, ssh_session_struct::port, session, SSH_OPTIONS_HOST, ssh_options_parse_config, ssh_options_set, torture_reset_config.
Referenced by torture_run_tests.
static void torture_options_config_match(void **state)
References assert_ssh_return_code, assert_ssh_return_code_equal, ssh_session_struct::opts, ssh_session_struct::port, session, SSH_ERROR, ssh_get_local_username, SSH_OK, SSH_OPTIONS_HOST, ssh_options_parse_config, ssh_options_set, torture_reset_config.
Referenced by torture_run_tests.
static void torture_options_config_match_multi(void **state)
References assert_ssh_return_code, ssh_session_struct::opts, ssh_session_struct::port, session, SSH_OPTIONS_HOST, ssh_options_parse_config, ssh_options_set, torture_reset_config.
Referenced by torture_run_tests.
static void torture_options_copy(void **state)
References assert_ssh_return_code, ssh_session_struct::bindaddr, ssh_session_struct::compressionlevel, ssh_session_struct::config_processed, ssh_iterator::data, ssh_session_struct::flags, ssh_session_struct::global_knownhosts, ssh_session_struct::gss_client_identity, ssh_session_struct::gss_delegate_creds, ssh_session_struct::gss_server_identity, ssh_session_struct::host, ssh_session_struct::identity, ssh_session_struct::knownhosts, ssh_iterator::next, ssh_session_struct::nodelay, ssh_session_struct::options_seen, ssh_session_struct::opts, ssh_session_struct::port, ssh_session_struct::ProxyCommand, ssh_session_struct::pubkey_accepted_types, session, ssh_free, SSH_KEX_METHODS, ssh_list_get_iterator, SSH_OPTIONS_COMPRESSION_LEVEL, ssh_options_copy, SSH_OPTIONS_HOST, SSH_OPTIONS_NODELAY, ssh_options_parse_config, ssh_options_set, ssh_session_struct::sshdir, ssh_session_struct::StrictHostKeyChecking, ssh_session_struct::timeout, ssh_session_struct::timeout_usec, ssh_session_struct::username, ssh_session_struct::wanted_methods.
Referenced by torture_run_tests.
int torture_run_tests(void)
References rc, setup, ssh_finalize, ssh_init, sshbind_setup, sshbind_teardown, teardown, torture_filter_tests, torture_options_config_host, torture_options_config_match, torture_options_config_match_multi, torture_options_copy, torture_options_get_global_knownhosts, torture_options_get_host, torture_options_get_identity, torture_options_get_knownhosts, torture_options_get_port, torture_options_get_user, torture_options_proxycommand, torture_options_set_ciphers, torture_options_set_fd, torture_options_set_global_knownhosts, torture_options_set_host, torture_options_set_hostkey, torture_options_set_identity, torture_options_set_key_exchange, torture_options_set_knownhosts, torture_options_set_macs, torture_options_set_port, torture_options_set_pubkey_accepted_types, torture_options_set_user.