torture_knownhosts.c
LIBSSH_STATIC
TMP_FILE_TEMPLATE
BADRSA
BADED25519
static int sshd_setup(void **state)
References torture_setup_sshd_server.
Referenced by torture_run_tests.
static int sshd_teardown(void **state)
References torture_teardown_sshd_server.
Referenced by torture_run_tests.
static int session_setup(void **state)
References assert_return_code, rc, s, ssh_socket_struct::session, ssh_new, SSH_OPTIONS_HOST, SSH_OPTIONS_LOG_VERBOSITY, SSH_OPTIONS_PROCESS_CONFIG, ssh_options_set, SSH_OPTIONS_USER, torture_libssh_verbosity, TORTURE_SSH_SERVER, TORTURE_SSH_USER_ALICE, verbosity.
Referenced by torture_run_tests.
static int session_teardown(void **state)
References s, ssh_socket_struct::session, ssh_disconnect, ssh_free.
Referenced by torture_run_tests.
static void torture_knownhosts_port(void **state)
References assert_ssh_return_code, buffer, ssh_session_struct::opts, ssh_session_struct::port, rc, s, ssh_socket_struct::session, session, ssh_connect, ssh_disconnect, ssh_free, ssh_is_server_known, ssh_new, SSH_OPTIONS_HOST, SSH_OPTIONS_KNOWNHOSTS, SSH_OPTIONS_PROCESS_CONFIG, ssh_options_set, SSH_SERVER_KNOWN_OK, ssh_write_knownhost, TMP_FILE_TEMPLATE, torture_create_temp_file, TORTURE_SSH_SERVER.
Referenced by torture_run_tests.
static void torture_knownhosts_wildcard(void **state)
References assert_ssh_return_code, key, rc, s, ssh_socket_struct::session, session, ssh_connect, ssh_is_server_known, SSH_KEYTYPE_RSA, SSH_OPTIONS_HOST, SSH_OPTIONS_KNOWNHOSTS, ssh_options_set, SSH_SERVER_KNOWN_OK, TMP_FILE_TEMPLATE, torture_create_temp_file, torture_get_testkey_pub, TORTURE_SSH_SERVER.
Referenced by torture_run_tests.
static void torture_knownhosts_standard_port(void **state)
References assert_ssh_return_code, key, rc, s, ssh_socket_struct::session, session, ssh_connect, ssh_is_server_known, SSH_KEYTYPE_RSA, SSH_OPTIONS_HOST, SSH_OPTIONS_KNOWNHOSTS, ssh_options_set, SSH_SERVER_KNOWN_OK, TMP_FILE_TEMPLATE, torture_create_temp_file, torture_get_testkey_pub, TORTURE_SSH_SERVER.
Referenced by torture_run_tests.
static void torture_knownhosts_fail(void **state)
References assert_ssh_return_code, BADRSA, rc, s, ssh_socket_struct::session, session, ssh_connect, ssh_is_server_known, SSH_OPTIONS_HOSTKEYS, SSH_OPTIONS_KNOWNHOSTS, ssh_options_set, SSH_SERVER_KNOWN_CHANGED, TMP_FILE_TEMPLATE, torture_create_temp_file.
Referenced by torture_run_tests.
static void torture_knownhosts_other(void **state)
References assert_ssh_return_code, BADRSA, rc, s, ssh_socket_struct::session, session, ssh_connect, ssh_is_server_known, SSH_OPTIONS_HOSTKEYS, SSH_OPTIONS_KNOWNHOSTS, ssh_options_set, SSH_SERVER_FOUND_OTHER, TMP_FILE_TEMPLATE, torture_create_temp_file.
Referenced by torture_run_tests.
static void torture_knownhosts_other_auto(void **state)
References assert_ssh_return_code, rc, s, ssh_socket_struct::session, session, ssh_connect, ssh_disconnect, ssh_free, ssh_is_server_known, ssh_new, SSH_OPTIONS_HOST, SSH_OPTIONS_HOSTKEYS, SSH_OPTIONS_KNOWNHOSTS, ssh_options_set, SSH_SERVER_KNOWN_OK, SSH_SERVER_NOT_KNOWN, ssh_write_knownhost, TMP_FILE_TEMPLATE, torture_create_temp_file, TORTURE_SSH_SERVER.
Referenced by torture_run_tests.
static void torture_knownhosts_conflict(void **state)
References assert_ssh_return_code, BADED25519, BADRSA, rc, s, ssh_socket_struct::session, session, ssh_connect, ssh_disconnect, ssh_free, ssh_is_server_known, ssh_new, SSH_OPTIONS_HOST, SSH_OPTIONS_HOSTKEYS, SSH_OPTIONS_KNOWNHOSTS, ssh_options_set, SSH_SERVER_KNOWN_CHANGED, SSH_SERVER_KNOWN_OK, ssh_write_knownhost, TMP_FILE_TEMPLATE, torture_create_temp_file, TORTURE_SSH_SERVER.
Referenced by torture_run_tests.
static void torture_knownhosts_no_hostkeychecking(void **state)
References assert_ssh_return_code, rc, s, ssh_socket_struct::session, session, ssh_connect, SSH_KNOWN_HOSTS_OK, SSH_KNOWN_HOSTS_UNKNOWN, SSH_OPTIONS_HOSTKEYS, SSH_OPTIONS_KNOWNHOSTS, ssh_options_set, SSH_OPTIONS_STRICTHOSTKEYCHECK, ssh_session_is_known_server, TMP_FILE_TEMPLATE, torture_create_temp_file.
Referenced by torture_run_tests.
int torture_run_tests(void)
References rc, session_setup, session_teardown, ssh_finalize, ssh_init, sshd_setup, sshd_teardown, torture_filter_tests, torture_knownhosts_conflict, torture_knownhosts_fail, torture_knownhosts_no_hostkeychecking, torture_knownhosts_other, torture_knownhosts_other_auto, torture_knownhosts_port, torture_knownhosts_standard_port, torture_knownhosts_wildcard.