torture_config.c
LIBSSH_STATIC
LIBSSH_TESTCONFIG1
LIBSSH_TESTCONFIG2
LIBSSH_TESTCONFIG3
LIBSSH_TESTCONFIG4
LIBSSH_TESTCONFIG5
LIBSSH_TESTCONFIG6
LIBSSH_TESTCONFIG7
LIBSSH_TESTCONFIG8
LIBSSH_TESTCONFIG9
LIBSSH_TESTCONFIG10
LIBSSH_TESTCONFIG11
LIBSSH_TESTCONFIG12
LIBSSH_TESTCONFIGGLOB
LIBSSH_TEST_PUBKEYACCEPTEDKEYTYPES
USERNAME
PROXYCMD
ID_FILE
KEXALGORITHMS
HOSTKEYALGORITHMS
PUBKEYACCEPTEDTYPES
MACS
USER_KNOWN_HOSTS
GLOBAL_KNOWN_HOSTS
BIND_ADDRESS
LIBSSH_THREAD int ssh_log_level
static int setup_config_files(void **state)
References BIND_ADDRESS, GLOBAL_KNOWN_HOSTS, HOSTKEYALGORITHMS, ID_FILE, KEXALGORITHMS, LIBSSH_TEST_PUBKEYACCEPTEDKEYTYPES, LIBSSH_TESTCONFIG1, LIBSSH_TESTCONFIG10, LIBSSH_TESTCONFIG11, LIBSSH_TESTCONFIG12, LIBSSH_TESTCONFIG2, LIBSSH_TESTCONFIG3, LIBSSH_TESTCONFIG4, LIBSSH_TESTCONFIG5, LIBSSH_TESTCONFIG6, LIBSSH_TESTCONFIG7, LIBSSH_TESTCONFIG8, LIBSSH_TESTCONFIG9, LIBSSH_TESTCONFIGGLOB, MACS, PROXYCMD, PUBKEYACCEPTEDTYPES, session, ssh_new, SSH_OPTIONS_LOG_VERBOSITY, ssh_options_set, torture_libssh_verbosity, torture_write_file, USER_KNOWN_HOSTS, USERNAME, verbosity.
Referenced by torture_run_tests.
static int teardown(void **state)
References LIBSSH_TEST_PUBKEYACCEPTEDKEYTYPES, LIBSSH_TESTCONFIG1, LIBSSH_TESTCONFIG10, LIBSSH_TESTCONFIG11, LIBSSH_TESTCONFIG12, LIBSSH_TESTCONFIG2, LIBSSH_TESTCONFIG3, LIBSSH_TESTCONFIG4, LIBSSH_TESTCONFIG5, LIBSSH_TESTCONFIG6, LIBSSH_TESTCONFIG7, LIBSSH_TESTCONFIG8, LIBSSH_TESTCONFIG9, ssh_free.
Referenced by torture_run_tests.
static void torture_config_from_file(void **state)
tests ssh_config_parse_file with Include directives
References HOSTKEYALGORITHMS, ID_FILE, KEXALGORITHMS, LIBSSH_TESTCONFIG1, MACS, ssh_session_struct::opts, PROXYCMD, ssh_session_struct::pubkey_accepted_types, PUBKEYACCEPTEDTYPES, SAFE_FREE, session, ssh_config_parse_file, SSH_HOSTKEYS, ssh_keep_fips_algos, SSH_KEX, SSH_MAC_C_S, SSH_MAC_S_C, ssh_options_get, SSH_OPTIONS_IDENTITY, SSH_OPTIONS_PROXYCOMMAND, SSH_OPTIONS_USER, SSH_STRING_FREE_CHAR, USERNAME, ssh_session_struct::wanted_methods.
Referenced by torture_run_tests.
static void torture_config_double_ports(void **state)
tests ssh_config_parse_file with multiple Port settings.
References LIBSSH_TESTCONFIG4, session, ssh_config_parse_file.
Referenced by torture_run_tests.
static void torture_config_glob(void **state)
References ID_FILE, LIBSSH_TESTCONFIG5, PROXYCMD, session, ssh_config_parse_file, ssh_options_get, SSH_OPTIONS_IDENTITY, SSH_OPTIONS_PROXYCOMMAND, SSH_STRING_FREE_CHAR.
Referenced by torture_run_tests.
static void torture_config_new(void **state)
Verify the new options are passed from configuration.
References BIND_ADDRESS, ssh_session_struct::bindaddr, ssh_session_struct::common, GLOBAL_KNOWN_HOSTS, ssh_session_struct::global_knownhosts, ssh_session_struct::gss_client_identity, ssh_session_struct::gss_delegate_creds, ssh_session_struct::gss_server_identity, ssh_session_struct::knownhosts, LIBSSH_TESTCONFIG7, ssh_common_struct::log_verbosity, ssh_session_struct::opts, session, SSH_COMP_C_S, SSH_COMP_S_C, ssh_config_parse_file, ssh_get_log_level, SSH_LOG_TRACE, ssh_session_struct::StrictHostKeyChecking, ssh_session_struct::timeout, USER_KNOWN_HOSTS, ssh_session_struct::wanted_methods.
Referenced by torture_run_tests.
static void torture_config_auth_methods(void **state)
Verify the authentication methods from configuration are effective.
References ssh_session_struct::flags, LIBSSH_TESTCONFIG8, ssh_session_struct::opts, session, ssh_config_parse_file, SSH_OPT_FLAG_GSSAPI_AUTH, SSH_OPT_FLAG_KBDINT_AUTH, SSH_OPT_FLAG_PASSWORD_AUTH, SSH_OPT_FLAG_PUBKEY_AUTH, SSH_OPTIONS_HOST, ssh_options_set, torture_reset_config.
Referenced by torture_run_tests.
static void torture_config_unknown(void **state)
Verify the configuration parser does not choke on unknown or unsupported configuration options.
References LIBSSH_TESTCONFIG9, session, ssh_config_parse_file.
Referenced by torture_run_tests.
static void torture_config_match(void **state)
Verify the configuration parser accepts Match keyword with full OpenSSH syntax.
References assert_ssh_return_code, assert_ssh_return_code_equal, ssh_session_struct::host, LIBSSH_TESTCONFIG10, ssh_session_struct::opts, session, ssh_config_parse_file, SSH_ERROR, ssh_get_local_username, SSH_OPTIONS_HOST, ssh_options_set, SSH_OPTIONS_USER, torture_reset_config, torture_write_file.
Referenced by torture_run_tests.
static void torture_config_proxyjump(void **state)
Verify we can parse ProxyJump configuration option.
References assert_ssh_return_code, assert_ssh_return_code_equal, LIBSSH_TESTCONFIG11, ssh_session_struct::opts, PROXYCMD, ssh_session_struct::ProxyCommand, session, ssh_config_parse_file, SSH_ERROR, SSH_OPTIONS_HOST, ssh_options_set, torture_reset_config, torture_write_file.
Referenced by torture_run_tests.
static void torture_config_rekey(void **state)
Verify the configuration parser handles all the possible versions of RekeyLimit configuration option.
References assert_ssh_return_code, LIBSSH_TESTCONFIG12, ssh_session_struct::opts, ssh_session_struct::rekey_data, ssh_session_struct::rekey_time, session, ssh_config_parse_file, SSH_OPTIONS_HOST, ssh_options_set, torture_reset_config.
Referenced by torture_run_tests.
static void torture_config_pubkeyacceptedkeytypes(void **state)
test ssh_config_parse_file with PubkeyAcceptedKeyTypes
References LIBSSH_TEST_PUBKEYACCEPTEDKEYTYPES, ssh_session_struct::opts, ssh_session_struct::pubkey_accepted_types, PUBKEYACCEPTEDTYPES, rc, SAFE_FREE, session, ssh_config_parse_file, SSH_HOSTKEYS, ssh_keep_fips_algos, SSH_OK.
Referenced by torture_run_tests.
static void torture_config_parser_get_cmd(void **state)
References ssh_config_get_cmd.
Referenced by torture_run_tests.
static void torture_config_parser_get_token(void **state)
References ssh_config_get_token.
Referenced by torture_run_tests.
static void torture_config_match_pattern(void **state)
References match_pattern, MAX_MATCH_RECURSION.
Referenced by torture_run_tests.
int torture_run_tests(void)
References rc, setup_config_files, ssh_finalize, ssh_init, teardown, torture_config_auth_methods, torture_config_double_ports, torture_config_from_file, torture_config_glob, torture_config_match, torture_config_match_pattern, torture_config_new, torture_config_parser_get_cmd, torture_config_parser_get_token, torture_config_proxyjump, torture_config_pubkeyacceptedkeytypes, torture_config_rekey, torture_config_unknown, torture_filter_tests.