torture_keyfiles.c
LIBSSH_STATIC
LIBSSH_RSA_TESTKEY
static int setup_rsa_key(void **state)
References LIBSSH_RSA_TESTKEY, session, SSH_KEYTYPE_RSA, ssh_new, torture_get_testkey, torture_get_testkey_pub, torture_write_file.
Referenced by setup_both_keys, torture_run_tests.
static int setup_both_keys(void **state)
References rc, setup_dsa_key, setup_rsa_key, ssh_free.
Referenced by torture_run_tests.
static int setup_both_keys_passphrase(void **state)
References LIBSSH_DSA_TESTKEY, LIBSSH_RSA_TESTKEY, session, SSH_KEYTYPE_DSS, SSH_KEYTYPE_RSA, ssh_new, torture_get_testkey, torture_get_testkey_pub, torture_write_file.
Referenced by torture_run_tests.
static int teardown(void **state)
References LIBSSH_DSA_TESTKEY, LIBSSH_RSA_TESTKEY, ssh_free.
Referenced by torture_run_tests.
static void torture_pubkey_from_file(void **state)
References LIBSSH_RSA_TESTKEY, pubkey, rc, session, SSH_STRING_FREE, ssh_try_publickey_from_file.
Referenced by torture_run_tests.
static int torture_read_one_line(const char *filename, char *buffer, size_t len)
References buffer.
Referenced by torture_pubkey_generate_from_privkey.
static void torture_pubkey_generate_from_privkey(void **state)
References LIBSSH_RSA_TESTKEY, privatekey_free, privatekey_from_file, privkey, pubkey, publickey_free, publickey_from_privatekey, publickey_to_string, rc, session, ssh_publickey_to_file, ssh_string_data, SSH_STRING_FREE, ssh_string_len, ssh_try_publickey_from_file, torture_read_one_line.
Referenced by torture_run_tests.
static void torture_privatekey_from_file(void **state)
tests the privatekey_from_file function without passphrase
References key, LIBSSH_DSA_TESTKEY, LIBSSH_RSA_TESTKEY, privatekey_free, privatekey_from_file, session, SSH_KEYTYPE_DSS, SSH_KEYTYPE_RSA.
Referenced by torture_run_tests.
static void torture_privatekey_from_file_passphrase(void **state)
tests the privatekey_from_file function with passphrase
References key, LIBSSH_DSA_TESTKEY, LIBSSH_RSA_TESTKEY, privatekey_free, privatekey_from_file, session, SSH_KEYTYPE_DSS, SSH_KEYTYPE_RSA, TORTURE_TESTKEY_PASSWORD.
Referenced by torture_run_tests.
int torture_run_tests(void)
References rc, setup_both_keys, setup_both_keys_passphrase, setup_rsa_key, ssh_finalize, ssh_init, teardown, torture_filter_tests, torture_privatekey_from_file, torture_privatekey_from_file_passphrase, torture_pubkey_from_file, torture_pubkey_generate_from_privkey.