torture_key.c
const char torture_rsa_private_testkey[][]
Referenced by torture_get_testkey_internal.
const char torture_rsa_private_testkey_passphrase[][]
Referenced by torture_get_testkey_internal.
const char torture_rsa_private_pkcs8_testkey_passphrase[][]
Referenced by torture_get_testkey_internal.
const char torture_rsa_private_openssh_testkey_passphrase[][]
Referenced by torture_get_testkey_internal.
const char torture_rsa_private_openssh_testkey[][]
Referenced by torture_get_testkey_internal.
const char torture_rsa_public_testkey[][]
Referenced by torture_get_testkey_internal.
const char torture_rsa_public_testkey_pem[][]
Referenced by torture_get_testkey_internal.
const char torture_rsa_testkey_cert[][]
Referenced by torture_get_testkey_internal.
const char torture_dsa_private_testkey[][]
Referenced by torture_get_testkey_internal.
const char torture_dsa_private_testkey_passphrase[][]
Referenced by torture_get_testkey_internal.
const char torture_dsa_private_pkcs8_testkey_passphrase[][]
Referenced by torture_get_testkey_internal.
const char torture_dsa_private_openssh_testkey_passphrase[][]
Referenced by torture_get_testkey_internal.
const char torture_dsa_private_openssh_testkey[][]
Referenced by torture_get_testkey_internal.
const char torture_dsa_public_testkey[][]
Referenced by torture_get_testkey_internal.
const char torture_dsa_testkey_cert[][]
Referenced by torture_get_testkey_internal.
const char torture_ecdsa256_private_testkey[][]
Referenced by torture_get_testkey_internal.
const char torture_ecdsa256_private_testkey_passphrase[][]
Referenced by torture_get_testkey_internal.
const char torture_ecdsa256_private_pkcs8_testkey_passphrase[][]
Referenced by torture_get_testkey_internal.
const char torture_ecdsa256_private_openssh_testkey[][]
Referenced by torture_get_testkey_internal.
const char torture_ecdsa256_private_openssh_testkey_pasphrase[][]
Referenced by torture_get_testkey_internal.
const char torture_ecdsa256_public_testkey[][]
Referenced by torture_get_testkey_internal.
const char torture_ecdsa256_public_testkey_pem[][]
Referenced by torture_get_testkey_internal.
const char torture_ecdsa256_testkey_cert[][]
Referenced by torture_get_testkey_internal.
const char torture_ecdsa384_private_testkey[][]
Referenced by torture_get_testkey_internal.
const char torture_ecdsa384_private_testkey_passphrase[][]
Referenced by torture_get_testkey_internal.
const char torture_ecdsa384_private_pkcs8_testkey_passphrase[][]
Referenced by torture_get_testkey_internal.
const char torture_ecdsa384_private_openssh_testkey[][]
Referenced by torture_get_testkey_internal.
const char torture_ecdsa384_private_openssh_testkey_passphrase[][]
Referenced by torture_get_testkey_internal.
const char torture_ecdsa384_public_testkey[][]
Referenced by torture_get_testkey_internal.
const char torture_ecdsa384_public_testkey_pem[][]
Referenced by torture_get_testkey_internal.
const char torture_ecdsa384_testkey_cert[][]
Referenced by torture_get_testkey_internal.
const char torture_ecdsa521_private_testkey[][]
Referenced by torture_get_testkey_internal.
const char torture_ecdsa521_private_testkey_passphrase[][]
Referenced by torture_get_testkey_internal.
const char torture_ecdsa521_private_pkcs8_testkey_passphrase[][]
Referenced by torture_get_testkey_internal.
const char torture_ecdsa521_private_openssh_testkey[][]
Referenced by torture_get_testkey_internal.
const char torture_ecdsa521_private_openssh_testkey_passphrase[][]
Referenced by torture_get_testkey_internal.
const char torture_ecdsa521_public_testkey[][]
Referenced by torture_get_testkey_internal.
const char torture_ecdsa521_public_testkey_pem[][]
Referenced by torture_get_testkey_internal.
const char torture_ecdsa521_testkey_cert[][]
Referenced by torture_get_testkey_internal.
const char torture_ed25519_private_pkcs8_testkey[][]
Referenced by torture_get_testkey_internal.
const char torture_ed25519_private_openssh_testkey[][]
Referenced by torture_get_testkey_internal.
const char torture_ed25519_private_openssh_testkey_passphrase[][]
Referenced by torture_get_testkey_internal.
const char torture_ed25519_private_pkcs8_testkey_passphrase[][]
Referenced by torture_get_testkey_internal.
const char torture_ed25519_public_testkey[][]
Referenced by torture_get_testkey_internal.
const char torture_ed25519_testkey_cert[][]
Referenced by torture_get_testkey_internal.
static const char* torture_get_testkey_internal(enum ssh_keytypes_e type, bool with_passphrase, int pubkey, int format)
References pubkey, SSH_KEYTYPE_DSS, SSH_KEYTYPE_DSS_CERT01, SSH_KEYTYPE_ECDSA, SSH_KEYTYPE_ECDSA_P256, SSH_KEYTYPE_ECDSA_P256_CERT01, SSH_KEYTYPE_ECDSA_P384, SSH_KEYTYPE_ECDSA_P384_CERT01, SSH_KEYTYPE_ECDSA_P521, SSH_KEYTYPE_ECDSA_P521_CERT01, SSH_KEYTYPE_ED25519, SSH_KEYTYPE_ED25519_CERT01, SSH_KEYTYPE_RSA, SSH_KEYTYPE_RSA1, SSH_KEYTYPE_RSA_CERT01, SSH_KEYTYPE_SK_ECDSA, SSH_KEYTYPE_SK_ECDSA_CERT01, SSH_KEYTYPE_SK_ED25519, SSH_KEYTYPE_SK_ED25519_CERT01, SSH_KEYTYPE_UNKNOWN, torture_dsa_private_openssh_testkey, torture_dsa_private_openssh_testkey_passphrase, torture_dsa_private_pkcs8_testkey_passphrase, torture_dsa_private_testkey, torture_dsa_private_testkey_passphrase, torture_dsa_public_testkey, torture_dsa_testkey_cert, torture_ecdsa256_private_openssh_testkey, torture_ecdsa256_private_openssh_testkey_pasphrase, torture_ecdsa256_private_pkcs8_testkey_passphrase, torture_ecdsa256_private_testkey, torture_ecdsa256_private_testkey_passphrase, torture_ecdsa256_public_testkey, torture_ecdsa256_public_testkey_pem, torture_ecdsa256_testkey_cert, torture_ecdsa384_private_openssh_testkey, torture_ecdsa384_private_openssh_testkey_passphrase, torture_ecdsa384_private_pkcs8_testkey_passphrase, torture_ecdsa384_private_testkey, torture_ecdsa384_private_testkey_passphrase, torture_ecdsa384_public_testkey, torture_ecdsa384_public_testkey_pem, torture_ecdsa384_testkey_cert, torture_ecdsa521_private_openssh_testkey, torture_ecdsa521_private_openssh_testkey_passphrase, torture_ecdsa521_private_pkcs8_testkey_passphrase, torture_ecdsa521_private_testkey, torture_ecdsa521_private_testkey_passphrase, torture_ecdsa521_public_testkey, torture_ecdsa521_public_testkey_pem, torture_ecdsa521_testkey_cert, torture_ed25519_private_openssh_testkey, torture_ed25519_private_openssh_testkey_passphrase, torture_ed25519_private_pkcs8_testkey, torture_ed25519_private_pkcs8_testkey_passphrase, torture_ed25519_public_testkey, torture_ed25519_testkey_cert, torture_rsa_private_openssh_testkey, torture_rsa_private_openssh_testkey_passphrase, torture_rsa_private_pkcs8_testkey_passphrase, torture_rsa_private_testkey, torture_rsa_private_testkey_passphrase, torture_rsa_public_testkey, torture_rsa_public_testkey_pem, torture_rsa_testkey_cert.
Referenced by torture_get_openssh_testkey, torture_get_testkey, torture_get_testkey_pub, torture_get_testkey_pub_pem.
const char* torture_get_openssh_testkey(enum ssh_keytypes_e type, bool with_passphrase)
References torture_get_testkey_internal.
Referenced by setup_config_files, setup_default_server, setup_ed25519_key, setup_files, setup_kbdint_server, setup_openssh_dsa_key, setup_openssh_ecdsa_key, setup_openssh_rsa_key, torture_pki_dsa_import_openssh_privkey_base64_passphrase, torture_pki_ed25519_import_export_privkey_base64, torture_pki_ed25519_import_privkey_base64_passphrase, torture_pki_ed25519_privkey_dup, torture_pki_ed25519_publickey_from_privatekey, torture_pki_ed25519_sign, torture_pki_ed25519_sign_openssh_privkey_passphrase, torture_pki_rsa_import_openssh_privkey_base64_passphrase, torture_setup_create_sshd_config.
const char* torture_get_testkey(enum ssh_keytypes_e type, bool with_passphrase)
References torture_get_testkey_internal.
Referenced by setup, setup_both_keys_passphrase, setup_default_server, setup_dsa_key, setup_ecdsa_key, setup_files, setup_rsa_key, setup_tokens, setup_tokens_ecdsa, thread_pki_rsa_copy_cert_to_privkey, thread_pki_rsa_import_privkey_base64_NULL_key, thread_pki_rsa_import_privkey_base64_passphrase, thread_pki_rsa_publickey_from_privatekey, torture_pki_dsa_import_privkey_base64, torture_pki_dsa_import_privkey_base64_comment, torture_pki_dsa_import_privkey_base64_passphrase, torture_pki_dsa_import_privkey_base64_whitespace, torture_pki_dsa_publickey_from_privatekey, torture_pki_rsa_copy_cert_to_privkey, torture_pki_rsa_import_privkey_base64_NULL_key, torture_pki_rsa_import_privkey_base64_passphrase, torture_pki_rsa_publickey_from_privatekey, torture_setup_create_sshd_config.
const char* torture_get_testkey_pub(enum ssh_keytypes_e type)
References torture_get_testkey_internal.
Referenced by setup_both_keys_passphrase, setup_dsa_key, setup_ecdsa_key, setup_ed25519_key, setup_openssh_dsa_key, setup_openssh_ecdsa_key, setup_openssh_rsa_key, setup_rsa_key, thread_pki_rsa_publickey_base64, torture_knownhosts_duplicate, torture_knownhosts_other, torture_knownhosts_precheck, torture_knownhosts_standard_port, torture_knownhosts_wildcard, torture_pki_dsa_generate_pubkey_from_privkey, torture_pki_dsa_publickey_base64, torture_pki_ed25519_generate_pubkey_from_privkey, torture_pki_ed25519_pubkey_dup, torture_pki_ed25519_publickey_base64, torture_pki_ed25519_verify, torture_pki_ed25519_verify_bad, torture_pki_rsa_generate_pubkey_from_privkey, torture_pki_rsa_publickey_base64, torture_pki_verify_mismatch, torture_server_hostkey_mismatch.
const char* torture_get_testkey_pub_pem(enum ssh_keytypes_e type)
References torture_get_testkey_internal.
Referenced by setup_tokens, setup_tokens_ecdsa.
const char* torture_get_testkey_passphrase(void)
References TORTURE_TESTKEY_PASSWORD.
Referenced by thread_pki_rsa_copy_cert_to_privkey, thread_pki_rsa_import_privkey_base64, thread_pki_rsa_import_privkey_base64_NULL_key, thread_pki_rsa_import_privkey_base64_NULL_str, thread_pki_rsa_import_privkey_base64_passphrase, torture_pki_dsa_import_openssh_privkey_base64_passphrase, torture_pki_dsa_import_privkey_base64, torture_pki_dsa_import_privkey_base64_comment, torture_pki_dsa_import_privkey_base64_passphrase, torture_pki_dsa_import_privkey_base64_whitespace, torture_pki_ecdsa_import_privkey_base64, torture_pki_ecdsa_import_privkey_base64_comment, torture_pki_ecdsa_import_privkey_base64_whitespace, torture_pki_ed25519_import_export_privkey_base64, torture_pki_ed25519_import_privkey_base64, torture_pki_ed25519_import_privkey_base64_comment, torture_pki_ed25519_import_privkey_base64_passphrase, torture_pki_ed25519_import_privkey_base64_whitespace, torture_pki_ed25519_privkey_dup, torture_pki_ed25519_sign_openssh_privkey_passphrase, torture_pki_ed25519_write_privkey, torture_pki_rsa_copy_cert_to_privkey, torture_pki_rsa_import_openssh_privkey_base64_passphrase, torture_pki_rsa_import_privkey_base64, torture_pki_rsa_import_privkey_base64_comment, torture_pki_rsa_import_privkey_base64_NULL_key, torture_pki_rsa_import_privkey_base64_NULL_str, torture_pki_rsa_import_privkey_base64_passphrase, torture_pki_rsa_import_privkey_base64_whitespace.