torture_hashes.c
LIBSSH_STATIC
static int setup_rsa_key(void **state)
References key, rc, ssh_key_type_from_name, SSH_KEYTYPE_RSA, ssh_pki_import_pubkey_base64, torture_get_testkey_pub.
Referenced by torture_run_tests.
static int teardown(void **state)
References SSH_KEY_FREE.
Referenced by torture_run_tests.
static void torture_md5_hash(void **state)
References pubkey, rc, SSH_ERROR, ssh_get_hexa, ssh_get_publickey_hash, SSH_OK, SSH_PUBLICKEY_HASH_MD5, SSH_STRING_FREE_CHAR.
Referenced by torture_run_tests.
static void torture_sha1_hash(void **state)
References pubkey, rc, sha1, ssh_get_b64_unpadded, ssh_get_publickey_hash, SSH_PUBLICKEY_HASH_SHA1, SSH_STRING_FREE_CHAR.
Referenced by torture_run_tests.
static void torture_sha256_hash(void **state)
References pubkey, rc, sha256, ssh_get_b64_unpadded, ssh_get_publickey_hash, SSH_PUBLICKEY_HASH_SHA256, SSH_STRING_FREE_CHAR.
Referenced by torture_run_tests.
static void torture_sha256_fingerprint(void **state)
References pubkey, rc, sha256, ssh_get_fingerprint_hash, ssh_get_publickey_hash, SSH_PUBLICKEY_HASH_SHA256, SSH_STRING_FREE_CHAR.
Referenced by torture_run_tests.
int torture_run_tests(void)
References rc, setup_rsa_key, teardown, torture_filter_tests, torture_md5_hash, torture_sha1_hash, torture_sha256_fingerprint, torture_sha256_hash.