torture.c
TORTURE_SSHD_SRV_IPV4
TORTURE_SSHD_SRV_IPV6
TORTURE_SSHD_SRV_PORT
TORTURE_SOCKET_DIR
TORTURE_SSHD_PIDFILE
TORTURE_SSHD_CONFIG
TORTURE_PCAP_FILE
const char torture_rsa_certauth_pub[][]
Referenced by torture_setup_create_sshd_config.
int verbosity
Referenced by main, torture_libssh_verbosity, torture_ssh_session.
const char* pattern
Referenced by main, match_hostname, match_pattern, match_pattern_list, ssh_config_match, ssh_strreplace.
static int _torture_auth_kbdint(ssh_session session, const char *password)
References echo, session, SSH_AUTH_ERROR, SSH_AUTH_INFO, ssh_userauth_kbdint, ssh_userauth_kbdint_getnprompts, ssh_userauth_kbdint_getprompt, ssh_userauth_kbdint_setanswer.
Referenced by torture_ssh_session.
int torture_rmdirs(const char *path)
References SAFE_FREE.
Referenced by session_teardown, sshbind_teardown, sshd_teardown, teardown, teardown_cert_dir, teardown_directory_structure, teardown_temp_dir, torture_knownhosts_algorithms_negative, torture_knownhosts_new_file, torture_ssh_dir_writeable, torture_ssh_mkdirs, torture_teardown_socket_dir.
int torture_isdir(const char *path)
Referenced by torture_sftp_mkdir.
static pid_t torture_read_pidfile(const char *pidfile)
References rc.
Referenced by torture_reload_sshd_server, torture_terminate_process.
int torture_terminate_process(const char *pidfile)
References rc, torture_read_pidfile.
Referenced by agent_teardown, stop_server, torture_teardown_sshd_server.
ssh_session torture_ssh_session(struct torture_state *s, const char *host, const unsigned int *port, const char *user, const char *password)
References _torture_auth_kbdint, host, port, rc, s, session, SSH_AUTH_ERROR, SSH_AUTH_METHOD_INTERACTIVE, SSH_AUTH_METHOD_PASSWORD, SSH_AUTH_SUCCESS, ssh_connect, ssh_disconnect, SSH_ERROR, ssh_free, ssh_is_connected, ssh_new, SSH_OPTIONS_HOST, SSH_OPTIONS_LOG_VERBOSITY, SSH_OPTIONS_PORT, SSH_OPTIONS_PROCESS_CONFIG, ssh_options_set, SSH_OPTIONS_USER, ssh_set_pcap_file, ssh_userauth_list, ssh_userauth_none, ssh_userauth_password, ssh_userauth_publickey_auto, user, verbosity.
Referenced by client_thread, session_setup.
int torture_server_port(void)
References port, TORTURE_SSHD_SRV_PORT.
const char* torture_server_address(int family)
References TORTURE_SSHD_SRV_IPV4, TORTURE_SSHD_SRV_IPV6.
Referenced by torture_options_set_proxycommand_ssh, torture_options_set_proxycommand_ssh_stderr.
void torture_setup_socket_dir(void **state)
References rc, s, SSH_OK, ssh_pcap_file_new, ssh_pcap_file_open, torture_make_temp_dir, TORTURE_PCAP_FILE, TORTURE_SOCKET_DIR, TORTURE_SSHD_CONFIG, TORTURE_SSHD_PIDFILE.
Referenced by setup_default_server, setup_files, setup_kbdint_server, torture_setup_sshd_server.
static void torture_setup_create_sshd_config(void **state, bool pam)
References ARRAY_SIZE, assert_return_code, endif, rc, s, SSH_KEYTYPE_DSS, SSH_KEYTYPE_ECDSA_P521, SSH_KEYTYPE_ED25519, SSH_KEYTYPE_RSA, torture_get_openssh_testkey, torture_get_testkey, torture_rsa_certauth_pub, torture_write_file.
Referenced by torture_setup_sshd_server, torture_update_sshd_config.
static int torture_wait_for_daemon(unsigned int seconds)
References rc, ssh_timeout_elapsed, ssh_timestamp_init, TORTURE_SSH_SERVER.
Referenced by torture_reload_sshd_server, torture_setup_sshd_server.
void torture_setup_sshd_server(void **state, bool pam)
References assert_return_code, rc, s, torture_setup_create_sshd_config, torture_setup_socket_dir, torture_wait_for_daemon.
Referenced by sshd_group_setup, sshd_setup.
void torture_setup_tokens(const char *temp_dir, const char *filename, const char object_name[])
References assert_return_code, rc.
Referenced by setup_tokens, setup_tokens_ecdsa.
void torture_teardown_socket_dir(void **state)
References rc, s, ssh_pcap_file_free, torture_rmdirs.
Referenced by teardown_files, torture_teardown_sshd_server.
static int torture_reload_sshd_server(void **state)
References rc, s, SSH_ERROR, SSH_OK, torture_read_pidfile, torture_wait_for_daemon.
Referenced by torture_update_sshd_config.
int torture_update_sshd_config(void **state, const char *config)
References rc, s, SAFE_FREE, SSH_OK, torture_reload_sshd_server, torture_setup_create_sshd_config.
Referenced by torture_rekey_server_send.
void torture_teardown_sshd_server(void **state)
References rc, s, torture_teardown_socket_dir, torture_terminate_process.
Referenced by sshd_group_teardown, sshd_teardown, teardown_default_server, teardown_kbdint_server.
char* torture_make_temp_dir(const char *template)
References SAFE_FREE.
Referenced by session_setup, setup, setup_cert_dir, setup_config_files, setup_directory_structure, setup_dsa_key, setup_ecdsa_key, setup_ed25519_key, setup_openssh_dsa_key, setup_openssh_ecdsa_key, setup_openssh_rsa_key, setup_rsa_key, setup_session, setup_temp_dir, torture_knownhosts_algorithms_negative, torture_knownhosts_new_file, torture_setup_socket_dir, torture_ssh_dir_writeable, torture_ssh_mkdirs.
char* torture_create_temp_file(const char *template)
References SAFE_FREE.
Referenced by setup, setup_knownhosts_file, setup_knownhosts_file_duplicate, torture_knownhosts_conflict, torture_knownhosts_duplicate, torture_knownhosts_fail, torture_knownhosts_no_hostkeychecking, torture_knownhosts_other, torture_knownhosts_other_auto, torture_knownhosts_port, torture_knownhosts_precheck, torture_knownhosts_standard_port, torture_knownhosts_unknown, torture_knownhosts_wildcard.
char* torture_get_current_working_dir(void)
References SAFE_FREE.
Referenced by session_setup, setup_cert_dir, setup_config_files, setup_directory_structure, setup_dsa_key, setup_ecdsa_key, setup_ed25519_key, setup_openssh_dsa_key, setup_openssh_ecdsa_key, setup_openssh_rsa_key, setup_rsa_key, setup_session, setup_temp_dir, torture_back_and_forth, torture_knownhosts_algorithms_negative, torture_ssh_mkdirs.
int torture_change_dir(char *path)
References rc.
Referenced by session_teardown, setup_cert_dir, setup_config_files, setup_directory_structure, setup_dsa_key, setup_ecdsa_key, setup_ed25519_key, setup_openssh_dsa_key, setup_openssh_ecdsa_key, setup_openssh_rsa_key, setup_rsa_key, setup_session, sshbind_teardown, sshd_teardown, teardown, teardown_cert_dir, teardown_directory_structure, teardown_temp_dir, torture_back_and_forth, torture_knownhosts_algorithms_negative, torture_ssh_mkdirs.
int torture_libssh_verbosity(void)
References verbosity.
Referenced by session_setup, setup, setup_config_files, setup_default_server, setup_kbdint_server, setup_server_state, torture_packet, torture_pki_verify_mismatch.
void _torture_filter_tests(struct CMUnitTest *tests, size_t ntests)
void torture_write_file(const char *filename, const char *data)
References rc.
Referenced by setup, setup_both_keys_passphrase, setup_config_files, setup_default_server, setup_dsa_key, setup_ecdsa_key, setup_ed25519_key, setup_files, setup_kbdint_server, setup_openssh_dsa_key, setup_openssh_ecdsa_key, setup_openssh_rsa_key, setup_rsa_key, setup_tokens, setup_tokens_ecdsa, start_server, torture_config_match, torture_config_proxyjump, torture_knownhosts_algorithms_negative, torture_pki_verify_mismatch, torture_setup_create_sshd_config, try_config_content.
void torture_reset_config(ssh_session session)
References ssh_session_struct::options_seen, ssh_session_struct::opts, session.
Referenced by torture_config_auth_methods, torture_config_match, torture_config_proxyjump, torture_config_rekey, torture_options_config_host, torture_options_config_match, torture_options_config_match_multi.
int main(int argc, char **argv)
References pattern, argument_s::pattern, torture_cmdline_parse, torture_run_tests, argument_s::verbose, verbosity.