torture_temp_dir.c
LIBSSH_STATIC
const char template[][]
static int setup(void **state)
References torture_make_temp_dir.
Referenced by torture_run_tests.
static int teardown(void **state)
References torture_rmdirs.
Referenced by torture_run_tests.
static void torture_create_temp_dir(void **state)
Referenced by torture_run_tests.
int torture_run_tests(void)
References rc, setup, teardown, torture_create_temp_dir, torture_filter_tests.