torture_auth_pkcs11.c
LIBSSH_STATIC
LIBSSH_RSA_TESTKEY
LIBSSH_ECDSA_256_TESTKEY
LIBSSH_ECDSA_384_TESTKEY
LIBSSH_ECDSA_521_TESTKEY
SOFTHSM_CONF
const char template[][]
static int setup_tokens(void **state, const char *type, const char *obj_name)
References pki_st::keys_dir, s, pki_st::temp_dir, torture_setup_tokens.
Referenced by setup_session.
static int session_setup(void **state)
References assert_return_code, assert_ssh_return_code, rc, s, ssh_socket_struct::session, ssh_new, SSH_OPTIONS_HOST, SSH_OPTIONS_LOG_VERBOSITY, SSH_OPTIONS_PROCESS_CONFIG, ssh_options_set, torture_libssh_verbosity, TORTURE_SSH_SERVER, verbosity.
Referenced by torture_run_tests.
static int session_teardown(void **state)
References s, ssh_socket_struct::session, ssh_disconnect, ssh_free.
Referenced by torture_run_tests.
static int setup_session(void **state)
References pki_st::keys_dir, LIBSSH_ECDSA_256_TESTKEY, LIBSSH_ECDSA_384_TESTKEY, LIBSSH_ECDSA_521_TESTKEY, LIBSSH_RSA_TESTKEY, pki_st::orig_dir, rc, s, setup_tokens, pki_st::temp_dir, torture_change_dir, torture_get_current_working_dir, torture_make_temp_dir.
Referenced by sshd_setup.
static int sshd_setup(void **state)
References setup_session, torture_setup_sshd_server.
Referenced by torture_run_tests.
static int sshd_teardown(void **state)
References pki_st::keys_dir, pki_st::orig_dir, rc, s, SAFE_FREE, pki_st::temp_dir, torture_change_dir, torture_rmdirs, torture_teardown_sshd_server.
Referenced by torture_run_tests.
static void torture_auth_autopubkey(void **state, const char *obj_name, const char *pin)
References ssh_iterator::data, ssh_session_struct::identity, ssh_session_struct::opts, rc, ssh_list::root, s, ssh_socket_struct::session, session, SSH_AUTH_METHOD_PUBLICKEY, SSH_AUTH_SUCCESS, ssh_connect, SSH_ERROR, ssh_get_error_code, SSH_OK, SSH_OPTIONS_IDENTITY, SSH_OPTIONS_LOG_VERBOSITY, ssh_options_set, SSH_OPTIONS_USER, SSH_REQUEST_DENIED, ssh_userauth_list, ssh_userauth_none, ssh_userauth_publickey_auto, TORTURE_SSH_USER_CHARLIE, verbosity.
Referenced by torture_auth_autopubkey_ecdsa_key_256, torture_auth_autopubkey_ecdsa_key_384, torture_auth_autopubkey_ecdsa_key_521, torture_auth_autopubkey_rsa.
static void torture_auth_autopubkey_rsa(void **state)
References torture_auth_autopubkey.
Referenced by torture_run_tests.
static void torture_auth_autopubkey_ecdsa_key_256(void **state)
References torture_auth_autopubkey.
Referenced by torture_run_tests.
static void torture_auth_autopubkey_ecdsa_key_384(void **state)
References torture_auth_autopubkey.
Referenced by torture_run_tests.
static void torture_auth_autopubkey_ecdsa_key_521(void **state)
References torture_auth_autopubkey.
Referenced by torture_run_tests.
int torture_run_tests(void)
References rc, session, session_setup, session_teardown, ssh_finalize, ssh_init, SSH_LOG_FUNCTIONS, ssh_new, SSH_OPTIONS_LOG_VERBOSITY, ssh_options_set, sshd_setup, sshd_teardown, torture_auth_autopubkey_ecdsa_key_256, torture_auth_autopubkey_ecdsa_key_384, torture_auth_autopubkey_ecdsa_key_521, torture_auth_autopubkey_rsa, torture_filter_tests, verbosity.