torture_push_pop_dir.c
LIBSSH_STATIC
const char template[][]
static int setup(void **state)
References torture_make_temp_dir.
Referenced by torture_run_tests.
static int teardown(void **state)
References torture_rmdirs.
Referenced by torture_run_tests.
static void torture_back_and_forth(void **state)
References rc, SAFE_FREE, torture_change_dir, torture_get_current_working_dir.
Referenced by torture_run_tests.
int torture_run_tests(void)
References rc, setup, teardown, torture_back_and_forth, torture_filter_tests.