torture_pki_ecdsa_uri.c
LIBSSH_STATIC
LIBSSH_ECDSA_TESTKEY
LIBSSH_ECDSA_TESTKEY_PEM
SOFTHSM_CONF
PUB_URI_FMT_256
PRIV_URI_FMT_256
PUB_URI_FMT_384
PRIV_URI_FMT_384
PUB_URI_FMT_521
PRIV_URI_FMT_521
PRIV_URI_FMT_384_INVALID_TOKEN
PKCS#11 URIs with invalid fields
PRIV_URI_FMT_521_INVALID_OBJECT
PUB_URI_FMT_384_INVALID_TOKEN
PUB_URI_FMT_521_INVALID_OBJECT
const char template[][]
const unsigned char INPUT[][]
Referenced by torture_ecdsa_sign_verify_uri.
static int setup_tokens_ecdsa(void **state, int ecdsa_bits, const char *obj_tempname)
References LIBSSH_ECDSA_TESTKEY, SSH_KEYTYPE_ECDSA_P256, SSH_KEYTYPE_ECDSA_P384, SSH_KEYTYPE_ECDSA_P521, pki_st::temp_dir, torture_get_testkey, torture_get_testkey_pub_pem, torture_setup_tokens, torture_write_file, pki_st::type.
Referenced by setup_directory_structure.
static int setup_directory_structure(void **state)
References pki_st::orig_dir, rc, setup_tokens_ecdsa, pki_st::temp_dir, torture_change_dir, torture_get_current_working_dir, torture_make_temp_dir.
Referenced by torture_run_tests.
static int teardown_directory_structure(void **state)
References pki_st::orig_dir, rc, SAFE_FREE, pki_st::temp_dir, torture_change_dir, torture_rmdirs.
Referenced by torture_run_tests.
static void torture_pki_ecdsa_import_pubkey_uri(void **state, const char *uri)
References assert_return_code, pubkey, rc, SSH_KEY_FREE, ssh_key_is_public, ssh_pki_import_pubkey_file.
Referenced by torture_pki_ecdsa_import_pubkey_uri_256, torture_pki_ecdsa_import_pubkey_uri_384, torture_pki_ecdsa_import_pubkey_uri_521.
static void torture_pki_ecdsa_import_pubkey_uri_256(void **state)
References PUB_URI_FMT_256, torture_pki_ecdsa_import_pubkey_uri.
Referenced by torture_run_tests.
static void torture_pki_ecdsa_import_pubkey_uri_384(void **state)
References PUB_URI_FMT_384, torture_pki_ecdsa_import_pubkey_uri.
Referenced by torture_run_tests.
static void torture_pki_ecdsa_import_pubkey_uri_521(void **state)
References PUB_URI_FMT_521, torture_pki_ecdsa_import_pubkey_uri.
Referenced by torture_run_tests.
static void torture_pki_ecdsa_publickey_from_privatekey_uri(void **state, const char *uri, const char *type)
References assert_return_code, LIBSSH_ECDSA_TESTKEY, LIBSSH_ECDSA_TESTKEY_PEM, privkey, pubkey, rc, SSH_KEY_FREE, SSH_OK, ssh_pki_export_privkey_to_pubkey, ssh_pki_export_pubkey_file, ssh_pki_import_privkey_file, torture_read_one_line.
Referenced by torture_pki_ecdsa_publickey_from_privatekey_uri_256, torture_pki_ecdsa_publickey_from_privatekey_uri_384, torture_pki_ecdsa_publickey_from_privatekey_uri_521.
static void torture_pki_ecdsa_publickey_from_privatekey_uri_256(void **state)
References PRIV_URI_FMT_256, torture_pki_ecdsa_publickey_from_privatekey_uri.
Referenced by torture_run_tests.
static void torture_pki_ecdsa_publickey_from_privatekey_uri_384(void **state)
References PRIV_URI_FMT_384, torture_pki_ecdsa_publickey_from_privatekey_uri.
Referenced by torture_run_tests.
static void torture_pki_ecdsa_publickey_from_privatekey_uri_521(void **state)
References PRIV_URI_FMT_521, torture_pki_ecdsa_publickey_from_privatekey_uri.
Referenced by torture_run_tests.
static void torture_ecdsa_sign_verify_uri(void **state, const char *uri, enum ssh_digest_e dig_type)
References assert_return_code, INPUT, pki_do_sign, privkey, pubkey, rc, session, SSH_DIGEST_SHA256, SSH_DIGEST_SHA384, SSH_DIGEST_SHA512, SSH_KEY_FREE, ssh_key_type, ssh_key_type_to_char, SSH_KEYTYPE_ECDSA_P256, SSH_KEYTYPE_ECDSA_P384, SSH_KEYTYPE_ECDSA_P521, SSH_KEYTYPE_UNKNOWN, ssh_new, SSH_OK, ssh_pki_export_privkey_to_pubkey, ssh_pki_import_privkey_file, ssh_pki_key_ecdsa_name, ssh_pki_signature_verify, ssh_signature_free.
Referenced by torture_ecdsa_sign_verify_uri_256, torture_ecdsa_sign_verify_uri_384, torture_ecdsa_sign_verify_uri_521.
static void torture_ecdsa_sign_verify_uri_256(void **state)
References PRIV_URI_FMT_256, SSH_DIGEST_SHA256, torture_ecdsa_sign_verify_uri.
Referenced by torture_run_tests.
static void torture_ecdsa_sign_verify_uri_384(void **state)
References PRIV_URI_FMT_384, SSH_DIGEST_SHA384, torture_ecdsa_sign_verify_uri.
Referenced by torture_run_tests.
static void torture_ecdsa_sign_verify_uri_521(void **state)
References PRIV_URI_FMT_521, SSH_DIGEST_SHA512, torture_ecdsa_sign_verify_uri.
Referenced by torture_run_tests.
static void torture_pki_ecdsa_duplicate_key_uri(void **state, const char *priv_uri, const char *pub_uri)
References privkey, pubkey, rc, ssh_key_cmp, SSH_KEY_CMP_PRIVATE, SSH_KEY_CMP_PUBLIC, ssh_key_dup, SSH_KEY_FREE, SSH_OK, ssh_pki_export_privkey_to_pubkey, ssh_pki_export_pubkey_base64, ssh_pki_import_privkey_file, ssh_pki_import_pubkey_file, SSH_STRING_FREE_CHAR.
Referenced by torture_pki_ecdsa_duplicate_key_uri_256, torture_pki_ecdsa_duplicate_key_uri_384, torture_pki_ecdsa_duplicate_key_uri_521.
static void torture_pki_ecdsa_duplicate_key_uri_256(void **state)
References PRIV_URI_FMT_256, PUB_URI_FMT_256, torture_pki_ecdsa_duplicate_key_uri.
Referenced by torture_run_tests.
static void torture_pki_ecdsa_duplicate_key_uri_384(void **state)
References PRIV_URI_FMT_384, PUB_URI_FMT_384, torture_pki_ecdsa_duplicate_key_uri.
Referenced by torture_run_tests.
static void torture_pki_ecdsa_duplicate_key_uri_521(void **state)
References PRIV_URI_FMT_521, PUB_URI_FMT_521, torture_pki_ecdsa_duplicate_key_uri.
Referenced by torture_run_tests.
static void torture_pki_ecdsa_duplicate_then_demote_uri(void **state, const char *priv_uri)
References ssh_key_struct::ecdsa_nid, privkey, pubkey, rc, ssh_key_dup, SSH_KEY_FREE, ssh_pki_export_privkey_to_pubkey, ssh_pki_import_privkey_file.
Referenced by torture_pki_ecdsa_duplicate_then_demote_uri_256, torture_pki_ecdsa_duplicate_then_demote_uri_384, torture_pki_ecdsa_duplicate_then_demote_uri_521.
static void torture_pki_ecdsa_duplicate_then_demote_uri_256(void **state)
References PRIV_URI_FMT_256, torture_pki_ecdsa_duplicate_then_demote_uri.
Referenced by torture_run_tests.
static void torture_pki_ecdsa_duplicate_then_demote_uri_384(void **state)
References PRIV_URI_FMT_384, torture_pki_ecdsa_duplicate_then_demote_uri.
Referenced by torture_run_tests.
static void torture_pki_ecdsa_duplicate_then_demote_uri_521(void **state)
References PRIV_URI_FMT_521, torture_pki_ecdsa_duplicate_then_demote_uri.
Referenced by torture_run_tests.
static void torture_pki_ecdsa_import_pubkey_uri_invalid_configurations(void **state)
References PRIV_URI_FMT_384_INVALID_TOKEN, PRIV_URI_FMT_521_INVALID_OBJECT, privkey, PUB_URI_FMT_384_INVALID_TOKEN, PUB_URI_FMT_521_INVALID_OBJECT, pubkey, rc, SSH_KEY_FREE, ssh_pki_import_privkey_file, ssh_pki_import_pubkey_file.
Referenced by torture_run_tests.
int torture_run_tests(void)
References rc, session, setup_directory_structure, ssh_finalize, ssh_init, SSH_LOG_FUNCTIONS, ssh_new, SSH_OPTIONS_LOG_VERBOSITY, ssh_options_set, teardown_directory_structure, torture_ecdsa_sign_verify_uri_256, torture_ecdsa_sign_verify_uri_384, torture_ecdsa_sign_verify_uri_521, torture_filter_tests, torture_pki_ecdsa_duplicate_key_uri_256, torture_pki_ecdsa_duplicate_key_uri_384, torture_pki_ecdsa_duplicate_key_uri_521, torture_pki_ecdsa_duplicate_then_demote_uri_256, torture_pki_ecdsa_duplicate_then_demote_uri_384, torture_pki_ecdsa_duplicate_then_demote_uri_521, torture_pki_ecdsa_import_pubkey_uri_256, torture_pki_ecdsa_import_pubkey_uri_384, torture_pki_ecdsa_import_pubkey_uri_521, torture_pki_ecdsa_import_pubkey_uri_invalid_configurations, torture_pki_ecdsa_publickey_from_privatekey_uri_256, torture_pki_ecdsa_publickey_from_privatekey_uri_384, torture_pki_ecdsa_publickey_from_privatekey_uri_521, verbosity.