torture_callbacks.c
LIBSSH_STATIC
static int myauthcallback(const char *prompt, char *buf, size_t len, int echo, int verify, void *userdata)
References echo.
Referenced by setup.
static int setup(void **state)
References ssh_callbacks_struct::auth_function, cb, myauthcallback, ssh_callbacks_init, ssh_callbacks_struct::userdata, ZERO_STRUCTP.
Referenced by torture_run_tests.
static int teardown(void **state)
Referenced by torture_run_tests.
static void torture_callbacks_size(void **state)
References cb, ssh_callbacks_struct::size.
Referenced by torture_run_tests.
static void torture_callbacks_exists(void **state)
References ssh_callbacks_struct::auth_function, cb, ssh_callbacks_struct::log_function, ssh_callbacks_struct::size, ssh_callbacks_exists.
Referenced by torture_run_tests.
static void test_mock_ssh_logging_callback(int priority, const char *function, const char *buffer, void *userdata)
References buffer, test_mock_state::executed.
Referenced by torture_log_callback.
static void torture_log_callback(void **state)
References buffer, test_mock_state::executed, SSH_LOG, SSH_LOG_WARN, ssh_set_log_callback, ssh_set_log_level, ssh_set_log_userdata, test_mock_ssh_logging_callback.
Referenced by torture_run_tests.
static void cb1(ssh_session session, ssh_channel channel, void *userdata)
References session.
Referenced by torture_callbacks_execute_list, torture_callbacks_iterate.
static void cb2(ssh_session session, ssh_channel channel, int status, void *userdata)
References session.
Referenced by torture_callbacks_execute_list.
static void torture_callbacks_execute_list(void **state)
References cb1, cb2, ssh_channel_callbacks_struct::channel_eof_function, ssh_channel_callbacks_struct::channel_exit_status_function, ssh_callbacks_execute_list, ssh_callbacks_init, ssh_list_append, ssh_list_free, ssh_list_new.
Referenced by torture_run_tests.
static int cb3(ssh_session session, ssh_channel channel, void *userdata)
References session, ssh_channel_callbacks_struct::userdata.
Referenced by torture_callbacks_iterate.
static void torture_callbacks_iterate(void **state)
References cb1, cb3, ssh_channel_callbacks_struct::channel_eof_function, ssh_channel_callbacks_struct::channel_shell_request_function, ssh_callbacks_init, ssh_callbacks_iterate, ssh_callbacks_iterate_end, ssh_callbacks_iterate_exec, ssh_list_append, ssh_list_free, ssh_list_new.
Referenced by torture_run_tests.
int torture_run_tests(void)
References rc, setup, ssh_finalize, ssh_init, teardown, torture_callbacks_execute_list, torture_callbacks_exists, torture_callbacks_iterate, torture_callbacks_size, torture_filter_tests, torture_log_callback.