torture_threads_crypto.c
LIBSSH_STATIC
NUM_THREADS
int8_t key[32][32]
Referenced by thread_crypto_aes256_cbc.
uint8_t IV[16][16]
Referenced by thread_crypto_aes256_cbc.
uint8_t cleartext[144][144]
Referenced by thread_crypto_aes256_cbc.
uint8_t aes256_cbc_encrypted[144][144]
Referenced by thread_crypto_aes256_cbc.
static int run_on_threads(void *(*func)(void *))
References NUM_THREADS, rc.
Referenced by torture_crypto_aes256_cbc.
static int get_cipher(struct ssh_cipher_struct *cipher, const char *ciphername)
References name, ssh_cipher_struct::name, SSH_ERROR, ssh_get_ciphertab, SSH_OK.
Referenced by thread_crypto_aes256_cbc.
static void* thread_crypto_aes256_cbc(void *threadid)
References aes256_cbc_encrypted, cleartext, ssh_cipher_struct::decrypt, ssh_cipher_struct::encrypt, get_cipher, IV, iv, key, ssh_cipher_struct::name, rc, ssh_cipher_struct::set_decrypt_key, ssh_cipher_struct::set_encrypt_key, ssh_cipher_clear, SSH_OK.
Referenced by torture_crypto_aes256_cbc.
static void torture_crypto_aes256_cbc(void **state)
References rc, run_on_threads, thread_crypto_aes256_cbc.
Referenced by torture_run_tests.
int torture_run_tests(void)
References rc, ssh_finalize, ssh_init, torture_crypto_aes256_cbc.