torture_crypto.c
LIBSSH_STATIC
CLEARTEXT_LENGTH
uint8_t key[32][32]
Referenced by auth_keyfile, auth_publickey, bcrypt_pbkdf, Blowfish_expand0state, Blowfish_expandstate, chacha20_set_encrypt_key, check_message_in_all_states, cmp_state_search, main, parse_opt, pkd_auth_pubkey_cb, pki_ed25519_key_dup, pki_ed25519_public_key_to_blob, pki_import_cert_buffer, pki_import_privkey_buffer, pki_import_pubkey_buffer, pki_key_check_hash_compatible, pki_key_dup, pki_key_generate_dss, pki_key_generate_ed25519, pki_key_generate_rsa, pki_key_to_pkey, pki_openssh_import_privkey_blob, pki_private_key_from_base64, pki_private_key_to_pem, pki_privkey_build_dss, pki_privkey_build_ed25519, pki_privkey_build_rsa, pki_pubkey_build_dss, pki_pubkey_build_rsa, pki_publickey_to_blob, pki_uri_import, poly1305_auth, privatekey_from_file, publickey_free, publickey_from_file, publickey_from_string, publickey_to_string, setup_rsa_key, ssh_agent_get_next_ident, ssh_generate_session_keys, ssh_get_publickey, ssh_get_publickey_hash, ssh_get_server_publickey, ssh_key_clean, ssh_key_dup, ssh_key_free, ssh_pki_convert_key_to_privatekey, ssh_pki_convert_key_to_publickey, ssh_pki_export_pubkey_base64, ssh_pki_export_pubkey_blob, ssh_pki_export_pubkey_file, ssh_pki_generate, ssh_pki_import_privkey_base64, ssh_pki_key_ecdsa_name, ssh_pki_openssh_import, ssh_pki_signature_verify, ssh_userauth_agent_pubkey, ssh_userauth_offer_pubkey, ssh_userauth_pubkey, test_sign_verify_data, thread_pki_rsa_generate_key, thread_pki_rsa_import_privkey_base64, thread_pki_rsa_import_privkey_base64_NULL_str, thread_pki_rsa_import_privkey_base64_passphrase, thread_pki_rsa_publickey_base64, thread_pki_rsa_publickey_from_privatekey, torture_crypto_aes256_cbc, torture_knownhosts_standard_port, torture_knownhosts_wildcard, torture_pki_dsa_generate_key, torture_pki_dsa_import_openssh_privkey_base64_passphrase, torture_pki_dsa_import_privkey_base64, torture_pki_dsa_import_privkey_base64_comment, torture_pki_dsa_import_privkey_base64_passphrase, torture_pki_dsa_import_privkey_base64_whitespace, torture_pki_dsa_publickey_base64, torture_pki_dsa_publickey_from_privatekey, torture_pki_ecdsa_import_privkey_base64, torture_pki_ecdsa_import_privkey_base64_comment, torture_pki_ecdsa_import_privkey_base64_whitespace, torture_pki_ecdsa_name, torture_pki_ecdsa_publickey_base64, torture_pki_ecdsa_publickey_from_privatekey, torture_pki_ed25519_generate_key, torture_pki_ed25519_import_export_privkey_base64, torture_pki_ed25519_import_privkey_base64, torture_pki_ed25519_import_privkey_base64_comment, torture_pki_ed25519_import_privkey_base64_passphrase, torture_pki_ed25519_import_privkey_base64_whitespace, torture_pki_ed25519_privkey_dup, torture_pki_ed25519_publickey_base64, torture_pki_ed25519_publickey_from_privatekey, torture_pki_fail_sign_with_incompatible_hash, torture_pki_generate_key_ecdsa, torture_pki_read_file, torture_pki_rsa_generate_key, torture_pki_rsa_import_openssh_privkey_base64_passphrase, torture_pki_rsa_import_privkey_base64, torture_pki_rsa_import_privkey_base64_comment, torture_pki_rsa_import_privkey_base64_NULL_str, torture_pki_rsa_import_privkey_base64_passphrase, torture_pki_rsa_import_privkey_base64_whitespace, torture_pki_rsa_publickey_base64, torture_pki_rsa_publickey_from_privatekey, torture_pki_rsa_sha2, torture_pki_sign_data_dsa, torture_pki_sign_data_ecdsa, torture_pki_sign_data_rsa, torture_pki_verify_mismatch, torture_privatekey_from_file, torture_privatekey_from_file_passphrase.
uint8_t IV[16][16]
Referenced by chacha20_set_encrypt_key, torture_crypto_aes256_cbc.
uint8_t cleartext[144][144]
Referenced by torture_crypto_aes256_cbc, torture_crypto_chacha20poly1305, torture_crypto_chacha20poly1305_bad_data, torture_crypto_chacha20poly1305_bad_packet_length, torture_crypto_chacha20poly1305_bad_tag.
uint8_t aes256_cbc_encrypted[144][144]
Referenced by torture_crypto_aes256_cbc.
uint8_t chacha20poly1305_key[CHACHA20_KEYLEN *2][CHACHA20_KEYLEN *2]
Referenced by torture_crypto_chacha20poly1305, torture_crypto_chacha20poly1305_bad_data, torture_crypto_chacha20poly1305_bad_packet_length, torture_crypto_chacha20poly1305_bad_tag.
uint8_t chacha20poly1305_cleartext[CLEARTEXT_LENGTH][CLEARTEXT_LENGTH]
Referenced by torture_crypto_chacha20poly1305, torture_crypto_chacha20poly1305_bad_data, torture_crypto_chacha20poly1305_bad_packet_length, torture_crypto_chacha20poly1305_bad_tag.
uint64_t chacha20poly1305_seq
Referenced by torture_crypto_chacha20poly1305, torture_crypto_chacha20poly1305_bad_data, torture_crypto_chacha20poly1305_bad_packet_length, torture_crypto_chacha20poly1305_bad_tag.
uint8_t chacha20poly1305_encrypted[sizeof(uint32_t)+CLEARTEXT_LENGTH+POLY1305_TAGLEN][sizeof(uint32_t)+CLEARTEXT_LENGTH+POLY1305_TAGLEN]
Referenced by torture_crypto_chacha20poly1305, torture_crypto_chacha20poly1305_bad_data, torture_crypto_chacha20poly1305_bad_packet_length, torture_crypto_chacha20poly1305_bad_tag.
static int get_cipher(struct ssh_cipher_struct *cipher, const char *ciphername)
References name, ssh_cipher_struct::name, SSH_ERROR, ssh_get_ciphertab, SSH_OK.
Referenced by torture_crypto_aes256_cbc, torture_crypto_chacha20poly1305, torture_crypto_chacha20poly1305_bad_data, torture_crypto_chacha20poly1305_bad_packet_length, torture_crypto_chacha20poly1305_bad_tag.
static void torture_crypto_aes256_cbc(void **state)
References aes256_cbc_encrypted, cleartext, ssh_cipher_struct::decrypt, ssh_cipher_struct::encrypt, get_cipher, IV, iv, key, rc, ssh_cipher_struct::set_decrypt_key, ssh_cipher_struct::set_encrypt_key, ssh_cipher_clear, SSH_OK.
Referenced by torture_run_tests.
static void torture_crypto_chacha20poly1305(void **state)
References ssh_cipher_struct::aead_decrypt, ssh_cipher_struct::aead_decrypt_length, ssh_cipher_struct::aead_encrypt, chacha20poly1305_cleartext, chacha20poly1305_encrypted, chacha20poly1305_key, chacha20poly1305_seq, cleartext, get_cipher, ssh_cipher_struct::keysize, POLY1305_TAGLEN, rc, ssh_cipher_struct::set_decrypt_key, ssh_cipher_struct::set_encrypt_key, ssh_cipher_clear, SSH_OK.
Referenced by torture_run_tests.
static void torture_crypto_chacha20poly1305_bad_packet_length(void **state)
References ssh_cipher_struct::aead_decrypt, ssh_cipher_struct::aead_decrypt_length, chacha20poly1305_cleartext, chacha20poly1305_encrypted, chacha20poly1305_key, chacha20poly1305_seq, cleartext, get_cipher, rc, ssh_cipher_struct::set_decrypt_key, ssh_cipher_clear, SSH_ERROR, SSH_OK.
Referenced by torture_run_tests.
static void torture_crypto_chacha20poly1305_bad_data(void **state)
References ssh_cipher_struct::aead_decrypt, ssh_cipher_struct::aead_decrypt_length, chacha20poly1305_cleartext, chacha20poly1305_encrypted, chacha20poly1305_key, chacha20poly1305_seq, cleartext, get_cipher, rc, ssh_cipher_struct::set_decrypt_key, ssh_cipher_clear, SSH_ERROR, SSH_OK.
Referenced by torture_run_tests.
static void torture_crypto_chacha20poly1305_bad_tag(void **state)
References ssh_cipher_struct::aead_decrypt, ssh_cipher_struct::aead_decrypt_length, chacha20poly1305_cleartext, chacha20poly1305_encrypted, chacha20poly1305_key, chacha20poly1305_seq, cleartext, get_cipher, rc, ssh_cipher_struct::set_decrypt_key, ssh_cipher_clear, SSH_ERROR, SSH_OK.
Referenced by torture_run_tests.
int torture_run_tests(void)
References rc, ssh_finalize, ssh_init, torture_crypto_aes256_cbc, torture_crypto_chacha20poly1305, torture_crypto_chacha20poly1305_bad_data, torture_crypto_chacha20poly1305_bad_packet_length, torture_crypto_chacha20poly1305_bad_tag.