torture_packet_filter.c
LIBSSH_STATIC
COMPARE_SESSION_STATE
COMPARE_ROLE
COMPARE_DH_STATE
COMPARE_AUTH_STATE
COMPARE_GLOBAL_REQ_STATE
COMPARE_CURRENT_METHOD
SESSION_STATE_COUNT
DH_STATE_COUNT
AUTH_STATE_COUNT
GLOBAL_REQ_STATE_COUNT
MESSAGE_COUNT
ROLE_CLIENT
ROLE_SERVER
typedef struct global_state_st global_state
uint8_t unfiltered[][]
Referenced by check_unfiltered.
static int cmp_state(const void *e1, const void *e2)
References global_state_st::auth, global_state_st::dh, global_state_st::global_req, global_state_st::role, global_state_st::session.
Referenced by check_message_in_all_states.
static int cmp_state_search(const void *key, const void *array_element)
References global_state_st::auth, COMPARE_AUTH_STATE, COMPARE_DH_STATE, COMPARE_GLOBAL_REQ_STATE, COMPARE_ROLE, COMPARE_SESSION_STATE, global_state_st::dh, global_state_st::flags, global_state_st::global_req, key, global_state_st::role, global_state_st::session.
Referenced by is_state_accepted.
static int is_state_accepted(global_state *tested, global_state *accepted, int accepted_len)
References cmp_state_search.
Referenced by check_message_in_all_states.
static int cmp_uint8(const void *i, const void *j)
Referenced by check_unfiltered.
static int check_unfiltered(uint8_t msg_type)
References cmp_uint8, unfiltered.
Referenced by torture_packet_filter_check_unfiltered.
static void torture_packet_filter_check_unfiltered(void **state)
References ssh_session_struct::auth, AUTH_STATE_COUNT, check_unfiltered, ssh_session_struct::dh_handshake_state, DH_STATE_COUNT, ssh_session_struct::global_req_state, GLOBAL_REQ_STATE_COUNT, ssh_session_struct::in_packet, MESSAGE_COUNT, rc, ssh_session_struct::server, session, ssh_session_struct::session_state, SESSION_STATE_COUNT, ssh_free, ssh_new, ssh_packet_incoming_filter, SSH_PACKET_UNKNOWN, ssh_session_struct::state, packet_struct::type.
Referenced by torture_run_tests.
static int check_message_in_all_states(global_state accepted[], int accepted_count, uint8_t msg_type)
References ssh_session_struct::auth, AUTH_STATE_COUNT, cmp_state, ssh_session_struct::dh_handshake_state, DH_STATE_COUNT, ssh_session_struct::global_req_state, GLOBAL_REQ_STATE_COUNT, ssh_session_struct::in_packet, is_state_accepted, key, rc, ssh_session_struct::server, session, ssh_session_struct::session_state, SESSION_STATE_COUNT, ssh_free, ssh_new, SSH_PACKET_ALLOWED, SSH_PACKET_DENIED, ssh_packet_incoming_filter, ssh_session_struct::state, packet_struct::type.
Referenced by torture_packet_filter_check_auth_success, torture_packet_filter_check_channel_open, torture_packet_filter_check_msg_ext_info.
static void torture_packet_filter_check_auth_success(void **state)
References check_message_in_all_states, COMPARE_AUTH_STATE, COMPARE_CURRENT_METHOD, COMPARE_DH_STATE, COMPARE_ROLE, COMPARE_SESSION_STATE, DH_STATE_FINISHED, global_state_st::flags, rc, ROLE_CLIENT, session, SSH2_MSG_USERAUTH_SUCCESS, SSH_AUTH_STATE_AUTH_NONE_SENT, SSH_AUTH_STATE_GSSAPI_MIC_SENT, SSH_AUTH_STATE_KBDINT_SENT, SSH_AUTH_STATE_PASSWORD_AUTH_SENT, SSH_AUTH_STATE_PUBKEY_AUTH_SENT, SSH_SESSION_STATE_AUTHENTICATING.
Referenced by torture_run_tests.
static void torture_packet_filter_check_msg_ext_info(void **state)
References check_message_in_all_states, COMPARE_DH_STATE, COMPARE_SESSION_STATE, DH_STATE_FINISHED, global_state_st::flags, rc, session, SSH2_MSG_EXT_INFO, SSH_SESSION_STATE_AUTHENTICATED, SSH_SESSION_STATE_AUTHENTICATING.
Referenced by torture_run_tests.
static void torture_packet_filter_check_channel_open(void **state)
References check_message_in_all_states, COMPARE_SESSION_STATE, global_state_st::flags, rc, SSH2_MSG_CHANNEL_OPEN, SSH_SESSION_STATE_AUTHENTICATED.
Referenced by torture_run_tests.
int torture_run_tests(void)
References rc, ssh_finalize, ssh_init, torture_filter_tests, torture_packet_filter_check_auth_success, torture_packet_filter_check_channel_open, torture_packet_filter_check_msg_ext_info, torture_packet_filter_check_unfiltered.