torture_pki_rsa_uri.c
LIBSSH_STATIC
LIBSSH_RSA_TESTKEY
LIBSSH_RSA_TESTKEY_PASSPHRASE
SOFTHSM_CONF
PUB_URI_FMT
PRIV_URI_FMT
const char template[][]
const unsigned char INPUT[][]
Referenced by torture_pki_sign_verify_uri.
static int setup_tokens(void **state)
References LIBSSH_RSA_TESTKEY, pki_st::priv_uri, PRIV_URI_FMT, pki_st::priv_uri_invalid_object, pki_st::priv_uri_invalid_token, pki_st::pub_uri, PUB_URI_FMT, pki_st::pub_uri_invalid_object, pki_st::pub_uri_invalid_token, SSH_KEYTYPE_RSA, ssh_tmpname, pki_st::temp_dir, torture_get_testkey, torture_get_testkey_pub_pem, torture_setup_tokens, torture_write_file.
Referenced by setup_directory_structure.
static int setup_directory_structure(void **state)
References pki_st::orig_dir, rc, setup_tokens, pki_st::temp_dir, torture_change_dir, torture_get_current_working_dir, torture_make_temp_dir.
Referenced by torture_run_tests.
static int teardown_directory_structure(void **state)
References pki_st::orig_dir, pki_st::priv_uri, pki_st::priv_uri_invalid_object, pki_st::priv_uri_invalid_token, pki_st::pub_uri, pki_st::pub_uri_invalid_object, pki_st::pub_uri_invalid_token, rc, SAFE_FREE, pki_st::temp_dir, torture_change_dir, torture_rmdirs.
Referenced by torture_run_tests.
static void torture_pki_rsa_import_pubkey_uri(void **state)
References assert_return_code, pki_st::pub_uri, pubkey, rc, SSH_KEY_FREE, ssh_key_is_public, ssh_pki_import_pubkey_file.
Referenced by torture_run_tests.
static void torture_pki_rsa_import_privkey_uri(void **state)
References pki_st::priv_uri, privkey, rc, SSH_KEY_FREE, ssh_key_is_private, ssh_pki_import_privkey_file.
Referenced by torture_run_tests.
static void torture_pki_sign_verify_uri(void **state)
References INPUT, pki_do_sign, pki_st::priv_uri, privkey, pki_st::pub_uri, pubkey, rc, session, SSH_DIGEST_SHA256, ssh_free, SSH_KEY_FREE, ssh_new, SSH_OK, ssh_pki_import_privkey_file, ssh_pki_import_pubkey_file, ssh_pki_signature_verify, ssh_signature_free.
Referenced by torture_run_tests.
static void torture_pki_rsa_publickey_from_privatekey_uri(void **state)
References pki_st::priv_uri, privkey, pubkey, rc, SSH_KEY_FREE, ssh_key_is_private, SSH_OK, ssh_pki_export_privkey_to_pubkey, ssh_pki_import_privkey_file.
Referenced by torture_run_tests.
static void torture_pki_rsa_uri_invalid_configurations(void **state)
References pki_st::priv_uri_invalid_object, pki_st::priv_uri_invalid_token, privkey, pki_st::pub_uri_invalid_object, pki_st::pub_uri_invalid_token, pubkey, rc, SSH_KEY_FREE, ssh_pki_import_privkey_file, ssh_pki_import_pubkey_file.
Referenced by torture_run_tests.
int torture_run_tests(void)
References rc, session, setup_directory_structure, ssh_finalize, ssh_init, SSH_LOG_FUNCTIONS, ssh_new, SSH_OPTIONS_LOG_VERBOSITY, ssh_options_set, teardown_directory_structure, torture_filter_tests, torture_pki_rsa_import_privkey_uri, torture_pki_rsa_import_pubkey_uri, torture_pki_rsa_publickey_from_privatekey_uri, torture_pki_rsa_uri_invalid_configurations, torture_pki_sign_verify_uri, verbosity.