torture_auth.c
LIBSSH_STATIC
static int sshd_setup(void **state)
References torture_setup_sshd_server.
Referenced by torture_run_tests.
static int sshd_teardown(void **state)
References torture_teardown_sshd_server.
Referenced by torture_run_tests.
static int session_setup(void **state)
References assert_return_code, assert_ssh_return_code, rc, s, ssh_socket_struct::session, ssh_new, SSH_OPTIONS_HOST, SSH_OPTIONS_LOG_VERBOSITY, SSH_OPTIONS_PROCESS_CONFIG, ssh_options_set, torture_libssh_verbosity, TORTURE_SSH_SERVER, verbosity.
Referenced by pubkey_setup, torture_run_tests.
static int session_teardown(void **state)
References s, ssh_socket_struct::session, ssh_disconnect, ssh_free.
Referenced by agent_teardown, torture_run_tests.
static int pubkey_setup(void **state)
References rc, session_setup.
Referenced by agent_setup, torture_run_tests.
static int agent_setup(void **state)
References assert_return_code, pubkey_setup, rc, s.
Referenced by agent_cert_setup, torture_run_tests.
static int agent_cert_setup(void **state)
References agent_setup, assert_return_code, rc.
Referenced by torture_run_tests.
static int agent_teardown(void **state)
References rc, session_teardown, torture_terminate_process.
Referenced by torture_run_tests.
static void torture_auth_none(void **state)
References rc, s, ssh_socket_struct::session, session, SSH_AUTH_DENIED, ssh_connect, SSH_ERROR, ssh_get_error_code, SSH_OK, ssh_options_set, SSH_OPTIONS_USER, SSH_REQUEST_DENIED, ssh_userauth_none, TORTURE_SSH_USER_BOB.
Referenced by torture_run_tests.
static void torture_auth_none_nonblocking(void **state)
References rc, s, ssh_socket_struct::session, session, SSH_AUTH_AGAIN, SSH_AUTH_DENIED, ssh_connect, SSH_ERROR, ssh_get_error_code, SSH_OK, ssh_options_set, SSH_OPTIONS_USER, SSH_REQUEST_DENIED, ssh_set_blocking, ssh_userauth_none, TORTURE_SSH_USER_ALICE.
Referenced by torture_run_tests.
static void torture_auth_autopubkey(void **state)
References rc, s, ssh_socket_struct::session, session, SSH_AUTH_METHOD_PUBLICKEY, SSH_AUTH_SUCCESS, ssh_connect, SSH_ERROR, ssh_get_error_code, SSH_OK, ssh_options_set, SSH_OPTIONS_USER, SSH_REQUEST_DENIED, ssh_userauth_list, ssh_userauth_none, ssh_userauth_publickey_auto, TORTURE_SSH_USER_ALICE.
Referenced by torture_run_tests.
static void torture_auth_autopubkey_nonblocking(void **state)
References rc, s, ssh_socket_struct::session, session, SSH_AUTH_AGAIN, SSH_AUTH_METHOD_PUBLICKEY, SSH_AUTH_SUCCESS, ssh_connect, SSH_ERROR, ssh_get_error_code, SSH_OK, ssh_options_set, SSH_OPTIONS_USER, SSH_REQUEST_DENIED, ssh_set_blocking, ssh_userauth_list, ssh_userauth_none, ssh_userauth_publickey_auto, TORTURE_SSH_USER_ALICE.
Referenced by torture_run_tests.
static void torture_auth_kbdint(void **state)
References rc, s, ssh_socket_struct::session, session, SSH_AUTH_INFO, SSH_AUTH_METHOD_INTERACTIVE, SSH_AUTH_SUCCESS, ssh_connect, SSH_ERROR, ssh_get_error_code, SSH_OK, ssh_options_set, SSH_OPTIONS_USER, SSH_REQUEST_DENIED, ssh_userauth_kbdint, ssh_userauth_kbdint_getnprompts, ssh_userauth_kbdint_setanswer, ssh_userauth_list, ssh_userauth_none, TORTURE_SSH_USER_BOB, TORTURE_SSH_USER_BOB_PASSWORD.
Referenced by torture_run_tests.
static void torture_auth_kbdint_nonblocking(void **state)
References rc, s, ssh_socket_struct::session, session, SSH_AUTH_AGAIN, SSH_AUTH_INFO, SSH_AUTH_METHOD_INTERACTIVE, SSH_AUTH_SUCCESS, ssh_connect, SSH_ERROR, ssh_get_error_code, SSH_OK, ssh_options_set, SSH_OPTIONS_USER, SSH_REQUEST_DENIED, ssh_set_blocking, ssh_userauth_kbdint, ssh_userauth_kbdint_getnprompts, ssh_userauth_kbdint_setanswer, ssh_userauth_list, ssh_userauth_none, TORTURE_SSH_USER_BOB, TORTURE_SSH_USER_BOB_PASSWORD.
Referenced by torture_run_tests.
static void torture_auth_password(void **state)
References rc, s, ssh_socket_struct::session, session, SSH_AUTH_ERROR, SSH_AUTH_METHOD_PASSWORD, SSH_AUTH_SUCCESS, ssh_connect, ssh_get_error_code, SSH_OK, ssh_options_set, SSH_OPTIONS_USER, SSH_REQUEST_DENIED, ssh_userauth_list, ssh_userauth_none, ssh_userauth_password, TORTURE_SSH_USER_BOB, TORTURE_SSH_USER_BOB_PASSWORD.
Referenced by torture_run_tests.
static void torture_auth_password_nonblocking(void **state)
References rc, s, ssh_socket_struct::session, session, SSH_AUTH_AGAIN, SSH_AUTH_ERROR, SSH_AUTH_METHOD_PASSWORD, SSH_AUTH_SUCCESS, ssh_connect, ssh_get_error_code, SSH_OK, ssh_options_set, SSH_OPTIONS_USER, SSH_REQUEST_DENIED, ssh_set_blocking, ssh_userauth_list, ssh_userauth_none, ssh_userauth_password, TORTURE_SSH_USER_BOB, TORTURE_SSH_USER_BOB_PASSWORD.
Referenced by torture_run_tests.
static void torture_auth_agent(void **state)
References rc, s, ssh_socket_struct::session, session, ssh_agent_is_running, SSH_AUTH_METHOD_PUBLICKEY, SSH_AUTH_SUCCESS, ssh_connect, SSH_ERROR, ssh_get_error_code, SSH_OK, ssh_options_set, SSH_OPTIONS_USER, SSH_REQUEST_DENIED, ssh_userauth_agent, ssh_userauth_list, ssh_userauth_none, TORTURE_SSH_USER_ALICE.
Referenced by torture_auth_agent_cert, torture_run_tests.
static void torture_auth_agent_nonblocking(void **state)
References rc, s, ssh_socket_struct::session, session, ssh_agent_is_running, SSH_AUTH_AGAIN, SSH_AUTH_METHOD_PUBLICKEY, SSH_AUTH_SUCCESS, ssh_connect, SSH_ERROR, ssh_get_error_code, SSH_OK, ssh_options_set, SSH_OPTIONS_USER, SSH_REQUEST_DENIED, ssh_set_blocking, ssh_userauth_agent, ssh_userauth_list, ssh_userauth_none, TORTURE_SSH_USER_ALICE.
Referenced by torture_auth_agent_cert_nonblocking, torture_run_tests.
static void torture_auth_cert(void **state)
References privkey, rc, s, ssh_socket_struct::session, session, SSH_AUTH_SUCCESS, ssh_connect, SSH_KEY_FREE, SSH_OK, ssh_options_set, SSH_OPTIONS_USER, ssh_pki_copy_cert_to_privkey, ssh_pki_import_cert_file, ssh_pki_import_privkey_file, ssh_userauth_publickey, ssh_userauth_try_publickey, TORTURE_SSH_USER_ALICE.
Referenced by torture_run_tests.
static void torture_auth_agent_cert(void **state)
References rc, s, ssh_socket_struct::session, session, SSH_OK, SSH_OPTIONS_PUBLICKEY_ACCEPTED_TYPES, ssh_options_set, torture_auth_agent.
Referenced by torture_run_tests.
static void torture_auth_agent_cert_nonblocking(void **state)
References rc, s, ssh_socket_struct::session, session, SSH_OK, SSH_OPTIONS_PUBLICKEY_ACCEPTED_TYPES, ssh_options_set, torture_auth_agent_nonblocking.
Referenced by torture_run_tests.
static void torture_auth_pubkey_types(void **state)
References assert_ssh_return_code, rc, s, ssh_socket_struct::session, session, SSH_AUTH_DENIED, SSH_AUTH_METHOD_PUBLICKEY, SSH_AUTH_SUCCESS, ssh_connect, SSH_ERROR, ssh_get_error_code, SSH_OPTIONS_PUBLICKEY_ACCEPTED_TYPES, ssh_options_set, SSH_OPTIONS_USER, SSH_REQUEST_DENIED, ssh_userauth_list, ssh_userauth_none, ssh_userauth_publickey_auto, TORTURE_SSH_USER_ALICE.
Referenced by torture_run_tests.
static void torture_auth_pubkey_types_ecdsa(void **state)
References assert_ssh_return_code, rc, s, ssh_socket_struct::session, session, SSH_AUTH_DENIED, SSH_AUTH_METHOD_PUBLICKEY, SSH_AUTH_SUCCESS, ssh_connect, SSH_ERROR, ssh_get_error_code, SSH_OPTIONS_PUBLICKEY_ACCEPTED_TYPES, ssh_options_set, SSH_OPTIONS_USER, SSH_REQUEST_DENIED, ssh_userauth_list, ssh_userauth_none, ssh_userauth_publickey_auto, TORTURE_SSH_USER_ALICE.
Referenced by torture_run_tests.
static void torture_auth_pubkey_types_ed25519(void **state)
References assert_ssh_return_code, privkey, rc, s, ssh_socket_struct::session, session, SSH_AUTH_DENIED, SSH_AUTH_METHOD_PUBLICKEY, SSH_AUTH_SUCCESS, ssh_connect, SSH_ERROR, ssh_get_error_code, SSH_KEY_FREE, SSH_OK, SSH_OPTIONS_PUBLICKEY_ACCEPTED_TYPES, ssh_options_set, SSH_OPTIONS_USER, ssh_pki_import_privkey_file, SSH_REQUEST_DENIED, ssh_userauth_list, ssh_userauth_none, ssh_userauth_publickey, TORTURE_SSH_USER_ALICE.
Referenced by torture_run_tests.
static void torture_auth_pubkey_types_nonblocking(void **state)
References assert_ssh_return_code, rc, s, ssh_socket_struct::session, session, SSH_AUTH_AGAIN, SSH_AUTH_DENIED, SSH_AUTH_METHOD_PUBLICKEY, SSH_AUTH_SUCCESS, ssh_connect, SSH_ERROR, ssh_get_error_code, SSH_OPTIONS_PUBLICKEY_ACCEPTED_TYPES, ssh_options_set, SSH_OPTIONS_USER, SSH_REQUEST_DENIED, ssh_set_blocking, ssh_userauth_list, ssh_userauth_none, ssh_userauth_publickey_auto, TORTURE_SSH_USER_ALICE.
Referenced by torture_run_tests.
static void torture_auth_pubkey_types_ecdsa_nonblocking(void **state)
References assert_ssh_return_code, rc, s, ssh_socket_struct::session, session, SSH_AUTH_AGAIN, SSH_AUTH_DENIED, SSH_AUTH_METHOD_PUBLICKEY, SSH_AUTH_SUCCESS, ssh_connect, SSH_ERROR, ssh_get_error_code, SSH_OPTIONS_PUBLICKEY_ACCEPTED_TYPES, ssh_options_set, SSH_OPTIONS_USER, SSH_REQUEST_DENIED, ssh_set_blocking, ssh_userauth_list, ssh_userauth_none, ssh_userauth_publickey_auto, TORTURE_SSH_USER_ALICE.
Referenced by torture_run_tests.
static void torture_auth_pubkey_types_ed25519_nonblocking(void **state)
References assert_ssh_return_code, privkey, rc, s, ssh_socket_struct::session, session, SSH_AUTH_AGAIN, SSH_AUTH_DENIED, SSH_AUTH_METHOD_PUBLICKEY, SSH_AUTH_SUCCESS, ssh_connect, SSH_ERROR, ssh_get_error_code, SSH_OK, SSH_OPTIONS_PUBLICKEY_ACCEPTED_TYPES, ssh_options_set, SSH_OPTIONS_USER, ssh_pki_import_privkey_file, SSH_REQUEST_DENIED, ssh_set_blocking, ssh_userauth_list, ssh_userauth_none, ssh_userauth_publickey, TORTURE_SSH_USER_ALICE.
Referenced by torture_run_tests.
int torture_run_tests(void)
References agent_cert_setup, agent_setup, agent_teardown, pubkey_setup, rc, session_setup, session_teardown, ssh_finalize, ssh_init, sshd_setup, sshd_teardown, torture_auth_agent, torture_auth_agent_cert, torture_auth_agent_cert_nonblocking, torture_auth_agent_nonblocking, torture_auth_autopubkey, torture_auth_autopubkey_nonblocking, torture_auth_cert, torture_auth_kbdint, torture_auth_kbdint_nonblocking, torture_auth_none, torture_auth_none_nonblocking, torture_auth_password, torture_auth_password_nonblocking, torture_auth_pubkey_types, torture_auth_pubkey_types_ecdsa, torture_auth_pubkey_types_ecdsa_nonblocking, torture_auth_pubkey_types_ed25519, torture_auth_pubkey_types_ed25519_nonblocking, torture_auth_pubkey_types_nonblocking, torture_filter_tests.