torture_rand.c
LIBSSH_STATIC
NUM_LOOPS
NUM_THREADS
static int setup(void **state)
References rc, ssh_init, SSH_OK, ssh_threads_get_pthread, ssh_threads_set_callbacks.
Referenced by torture_run_tests.
static int teardown(void **state)
References ssh_finalize.
Referenced by torture_run_tests.
static void* torture_rand_thread(void *threadid)
References buffer, NUM_LOOPS, ssh_get_random.
Referenced by torture_rand_threading.
static void torture_rand_threading(void **state)
References NUM_THREADS, torture_rand_thread.
Referenced by torture_run_tests.
int torture_run_tests(void)
References rc, setup, teardown, torture_filter_tests, torture_rand_threading.