torture_pki_ed25519.c
LIBSSH_STATIC
LIBSSH_ED25519_TESTKEY
LIBSSH_ED25519_TESTKEY_PASSPHRASE
const char template[][]
const unsigned char HASH[][]
Referenced by torture_pki_ed25519_cert_verify, torture_pki_ed25519_generate_key, torture_pki_ed25519_sign, torture_pki_ed25519_sign_openssh_privkey_passphrase, torture_pki_ed25519_verify, torture_pki_ed25519_verify_bad.
const uint8_t ref_signature[ED25519_SIG_LEN][ED25519_SIG_LEN]
Referenced by torture_pki_ed25519_sign, torture_pki_ed25519_sign_openssh_privkey_passphrase, torture_pki_ed25519_verify, torture_pki_ed25519_verify_bad.
static int setup_ed25519_key(void **state)
References pki_st::cwd, LIBSSH_ED25519_TESTKEY, LIBSSH_ED25519_TESTKEY_PASSPHRASE, rc, SSH_KEYTYPE_ED25519, SSH_KEYTYPE_ED25519_CERT01, pki_st::temp_dir, torture_change_dir, torture_get_current_working_dir, torture_get_openssh_testkey, torture_get_testkey_pub, torture_make_temp_dir, torture_write_file.
Referenced by torture_run_tests.
static int teardown(void **state)
References pki_st::cwd, rc, SAFE_FREE, pki_st::temp_dir, torture_change_dir, torture_rmdirs.
Referenced by torture_run_tests.
static void torture_pki_ed25519_import_pubkey_file(void **state)
References assert_return_code, LIBSSH_ED25519_TESTKEY, pubkey, rc, SSH_KEY_FREE, ssh_pki_import_pubkey_file.
Referenced by torture_run_tests.
static void torture_pki_ed25519_import_pubkey_from_openssh_privkey(void **state)
References assert_return_code, LIBSSH_ED25519_TESTKEY_PASSPHRASE, pubkey, rc, SSH_KEY_FREE, ssh_pki_import_pubkey_file.
Referenced by torture_run_tests.
static void torture_pki_ed25519_import_privkey_base64(void **state)
References key, LIBSSH_ED25519_TESTKEY, rc, SSH_KEY_FREE, ssh_key_is_private, ssh_key_is_public, ssh_key_type, SSH_KEYTYPE_ED25519, ssh_pki_import_privkey_base64, torture_get_testkey_passphrase, torture_pki_read_file.
Referenced by torture_run_tests.
static void torture_pki_ed25519_import_privkey_base64_comment(void **state)
References key, LIBSSH_ED25519_TESTKEY, rc, SSH_KEY_FREE, ssh_key_is_private, ssh_key_is_public, ssh_key_type, SSH_KEYTYPE_ED25519, ssh_pki_import_privkey_base64, torture_get_testkey_passphrase, torture_pki_read_file.
Referenced by torture_run_tests.
static void torture_pki_ed25519_import_privkey_base64_whitespace(void **state)
References key, LIBSSH_ED25519_TESTKEY, rc, SSH_KEY_FREE, ssh_key_is_private, ssh_key_is_public, ssh_key_type, SSH_KEYTYPE_ED25519, ssh_pki_import_privkey_base64, torture_get_testkey_passphrase, torture_pki_read_file.
Referenced by torture_run_tests.
static void torture_pki_ed25519_import_export_privkey_base64(void **state)
References assert_return_code, key, rc, SSH_KEY_FREE, ssh_key_is_private, ssh_key_type, SSH_KEYTYPE_ED25519, ssh_pki_export_privkey_base64, ssh_pki_import_privkey_base64, SSH_STRING_FREE_CHAR, torture_get_openssh_testkey, torture_get_testkey_passphrase.
Referenced by torture_run_tests.
static void torture_pki_ed25519_publickey_from_privatekey(void **state)
References key, pubkey, rc, SSH_KEY_FREE, ssh_key_is_private, SSH_KEYTYPE_ED25519, SSH_OK, ssh_pki_export_privkey_to_pubkey, ssh_pki_import_privkey_base64, torture_get_openssh_testkey.
Referenced by torture_run_tests.
static void torture_pki_ed25519_import_cert_file(void **state)
References LIBSSH_ED25519_TESTKEY, rc, SSH_KEY_FREE, ssh_key_is_public, ssh_key_type, SSH_KEYTYPE_ED25519_CERT01, ssh_pki_import_cert_file.
Referenced by torture_run_tests.
static void torture_pki_ed25519_publickey_base64(void **state)
References key, rc, SSH_KEY_FREE, ssh_key_type_from_name, SSH_KEYTYPE_ED25519, ssh_pki_export_pubkey_base64, ssh_pki_import_pubkey_base64, torture_get_testkey_pub.
Referenced by torture_run_tests.
static void torture_pki_ed25519_generate_pubkey_from_privkey(void **state)
References LIBSSH_ED25519_TESTKEY, privkey, pubkey, rc, SSH_KEY_FREE, SSH_KEYTYPE_ED25519, SSH_OK, ssh_pki_export_privkey_to_pubkey, ssh_pki_export_pubkey_file, ssh_pki_import_privkey_file, torture_get_testkey_pub, torture_pubkey_len, torture_read_one_line.
Referenced by torture_run_tests.
static void torture_pki_ed25519_generate_key(void **state)
References ssh_signature_struct::ed25519_sig, endif, HASH, key, pki_do_sign, pubkey, ssh_signature_struct::raw_sig, rc, session, SSH_DIGEST_AUTO, SSH_ERROR, ssh_free, SSH_KEY_FREE, ssh_key_type, ssh_key_type_to_char, SSH_KEYTYPE_ED25519, SSH_KEYTYPE_UNKNOWN, ssh_new, SSH_OK, ssh_pki_export_privkey_to_pubkey, ssh_pki_generate, ssh_pki_signature_verify, ssh_signature_free, ssh_string_data.
Referenced by torture_run_tests.
static void torture_pki_ed25519_cert_verify(void **state)
References HASH, LIBSSH_ED25519_TESTKEY, pki_do_sign, privkey, rc, session, SSH_DIGEST_AUTO, ssh_free, SSH_KEY_FREE, ssh_new, SSH_OK, ssh_pki_import_cert_file, ssh_pki_import_privkey_file, ssh_pki_signature_verify, ssh_signature_free.
Referenced by torture_run_tests.
static void torture_pki_ed25519_write_privkey(void **state)
References LIBSSH_ED25519_TESTKEY, LIBSSH_ED25519_TESTKEY_PASSPHRASE, privkey, rc, SSH_ERROR, ssh_key_cmp, SSH_KEY_CMP_PRIVATE, SSH_KEY_FREE, ssh_pki_export_privkey_file, ssh_pki_import_privkey_file, torture_get_testkey_passphrase.
Referenced by torture_run_tests.
static void torture_pki_ed25519_sign(void **state)
References HASH, pki_do_sign, pki_signature_to_blob, privkey, rc, ref_signature, SSH_DIGEST_AUTO, SSH_KEY_FREE, SSH_KEYTYPE_ED25519, SSH_OK, ssh_pki_import_privkey_base64, ssh_signature_free, ssh_string_data, SSH_STRING_FREE, ssh_string_len, torture_get_openssh_testkey.
Referenced by torture_run_tests.
static void torture_pki_ed25519_sign_openssh_privkey_passphrase(void **state)
References HASH, pki_do_sign, pki_signature_to_blob, privkey, rc, ref_signature, SSH_DIGEST_AUTO, SSH_KEY_FREE, SSH_KEYTYPE_ED25519, SSH_OK, ssh_pki_import_privkey_base64, ssh_signature_free, ssh_string_data, SSH_STRING_FREE, ssh_string_len, torture_get_openssh_testkey, torture_get_testkey_passphrase.
Referenced by torture_run_tests.
static void torture_pki_ed25519_verify(void **state)
References ssh_signature_struct::ed25519_sig, ED25519_SIG_LEN, endif, HASH, pki_signature_from_blob, pubkey, ssh_signature_struct::raw_sig, rc, ref_signature, session, SSH_DIGEST_AUTO, SSH_ERROR, ssh_free, SSH_KEY_FREE, SSH_KEYTYPE_ED25519, ssh_new, SSH_OK, ssh_pki_import_pubkey_base64, ssh_pki_signature_verify, ssh_signature_free, ssh_string_data, ssh_string_fill, SSH_STRING_FREE, ssh_string_new, torture_get_testkey_pub.
Referenced by torture_run_tests.
static void torture_pki_ed25519_verify_bad(void **state)
References ED25519_SIG_LEN, HASH, pki_signature_from_blob, pubkey, rc, ref_signature, session, SSH_DIGEST_AUTO, SSH_ERROR, ssh_free, SSH_KEY_FREE, SSH_KEYTYPE_ED25519, ssh_new, SSH_OK, ssh_pki_import_pubkey_base64, ssh_pki_signature_verify, ssh_signature_free, ssh_string_data, ssh_string_fill, SSH_STRING_FREE, ssh_string_new, torture_get_testkey_pub.
Referenced by torture_run_tests.
static void torture_pki_ed25519_import_privkey_base64_passphrase(void **state)
References key, rc, SSH_KEY_FREE, ssh_key_is_private, SSH_KEYTYPE_ED25519, ssh_pki_import_privkey_base64, torture_get_openssh_testkey, torture_get_testkey_passphrase.
Referenced by torture_run_tests.
static void torture_pki_ed25519_privkey_dup(void **state)
References key, rc, ssh_key_dup, SSH_KEY_FREE, ssh_key_is_private, SSH_KEYTYPE_ED25519, ssh_pki_import_privkey_base64, torture_get_openssh_testkey, torture_get_testkey_passphrase.
Referenced by torture_run_tests.
static void torture_pki_ed25519_pubkey_dup(void **state)
References pubkey, rc, SAFE_FREE, ssh_key_dup, SSH_KEY_FREE, ssh_key_is_public, SSH_KEYTYPE_ED25519, ssh_pki_import_pubkey_base64, torture_get_testkey_pub.
Referenced by torture_run_tests.
int torture_run_tests(void)
References rc, setup_ed25519_key, ssh_finalize, ssh_init, teardown, torture_filter_tests, torture_pki_ed25519_cert_verify, torture_pki_ed25519_generate_key, torture_pki_ed25519_generate_pubkey_from_privkey, torture_pki_ed25519_import_cert_file, torture_pki_ed25519_import_export_privkey_base64, torture_pki_ed25519_import_privkey_base64, torture_pki_ed25519_import_privkey_base64_comment, torture_pki_ed25519_import_privkey_base64_passphrase, torture_pki_ed25519_import_privkey_base64_whitespace, torture_pki_ed25519_import_pubkey_file, torture_pki_ed25519_import_pubkey_from_openssh_privkey, torture_pki_ed25519_privkey_dup, torture_pki_ed25519_pubkey_dup, torture_pki_ed25519_publickey_base64, torture_pki_ed25519_publickey_from_privatekey, torture_pki_ed25519_sign, torture_pki_ed25519_sign_openssh_privkey_passphrase, torture_pki_ed25519_verify, torture_pki_ed25519_verify_bad, torture_pki_ed25519_write_privkey.