torture_algorithms.c
LIBSSH_STATIC
static int sshd_setup(void **state)
References torture_setup_sshd_server.
Referenced by torture_run_tests.
static int sshd_teardown(void **state)
References torture_teardown_sshd_server.
Referenced by torture_run_tests.
static int session_setup(void **state)
References assert_return_code, rc, s, ssh_socket_struct::session, ssh_new, SSH_OPTIONS_HOST, SSH_OPTIONS_LOG_VERBOSITY, SSH_OPTIONS_PROCESS_CONFIG, ssh_options_set, torture_libssh_verbosity, TORTURE_SSH_SERVER, verbosity.
Referenced by torture_run_tests.
static int session_teardown(void **state)
References s, ssh_socket_struct::session, ssh_disconnect, ssh_free.
Referenced by torture_run_tests.
static void test_algorithm(ssh_session session, const char *kex, const char *cipher, const char *hmac)
References assert_ssh_return_code, rc, session, ssh_connect, ssh_disconnect, ssh_get_error_code, ssh_handle_packets, SSH_OK, SSH_OPTIONS_CIPHERS_C_S, SSH_OPTIONS_CIPHERS_S_C, SSH_OPTIONS_HMAC_C_S, SSH_OPTIONS_HMAC_S_C, SSH_OPTIONS_KEY_EXCHANGE, ssh_options_set, SSH_REQUEST_DENIED, ssh_send_ignore, ssh_userauth_none.
Referenced by torture_algorithms_3des_cbc_hmac_sha1, torture_algorithms_3des_cbc_hmac_sha1_etm, torture_algorithms_3des_cbc_hmac_sha2_256, torture_algorithms_3des_cbc_hmac_sha2_256_etm, torture_algorithms_3des_cbc_hmac_sha2_512, torture_algorithms_3des_cbc_hmac_sha2_512_etm, torture_algorithms_aes128_cbc_hmac_sha1, torture_algorithms_aes128_cbc_hmac_sha1_etm, torture_algorithms_aes128_cbc_hmac_sha2_256, torture_algorithms_aes128_cbc_hmac_sha2_256_etm, torture_algorithms_aes128_cbc_hmac_sha2_512, torture_algorithms_aes128_cbc_hmac_sha2_512_etm, torture_algorithms_aes128_ctr_hmac_sha1, torture_algorithms_aes128_ctr_hmac_sha1_etm, torture_algorithms_aes128_ctr_hmac_sha2_256, torture_algorithms_aes128_ctr_hmac_sha2_256_etm, torture_algorithms_aes128_ctr_hmac_sha2_512, torture_algorithms_aes128_ctr_hmac_sha2_512_etm, torture_algorithms_aes128_gcm, torture_algorithms_aes192_cbc_hmac_sha1, torture_algorithms_aes192_cbc_hmac_sha1_etm, torture_algorithms_aes192_cbc_hmac_sha2_256, torture_algorithms_aes192_cbc_hmac_sha2_256_etm, torture_algorithms_aes192_cbc_hmac_sha2_512, torture_algorithms_aes192_cbc_hmac_sha2_512_etm, torture_algorithms_aes192_ctr_hmac_sha1, torture_algorithms_aes192_ctr_hmac_sha1_etm, torture_algorithms_aes192_ctr_hmac_sha2_256, torture_algorithms_aes192_ctr_hmac_sha2_256_etm, torture_algorithms_aes192_ctr_hmac_sha2_512, torture_algorithms_aes192_ctr_hmac_sha2_512_etm, torture_algorithms_aes256_cbc_hmac_sha1, torture_algorithms_aes256_cbc_hmac_sha1_etm, torture_algorithms_aes256_cbc_hmac_sha2_256, torture_algorithms_aes256_cbc_hmac_sha2_256_etm, torture_algorithms_aes256_cbc_hmac_sha2_512, torture_algorithms_aes256_cbc_hmac_sha2_512_etm, torture_algorithms_aes256_ctr_hmac_sha1, torture_algorithms_aes256_ctr_hmac_sha1_etm, torture_algorithms_aes256_ctr_hmac_sha2_256, torture_algorithms_aes256_ctr_hmac_sha2_256_etm, torture_algorithms_aes256_ctr_hmac_sha2_512, torture_algorithms_aes256_ctr_hmac_sha2_512_etm, torture_algorithms_aes256_gcm, torture_algorithms_dh_group1, torture_algorithms_dh_group14, torture_algorithms_dh_group16, torture_algorithms_dh_group18.
static void torture_algorithms_aes128_cbc_hmac_sha1(void **state)
References s, ssh_socket_struct::session, test_algorithm.
Referenced by torture_run_tests.
static void torture_algorithms_aes128_cbc_hmac_sha2_256(void **state)
References s, ssh_socket_struct::session, test_algorithm.
Referenced by torture_run_tests.
static void torture_algorithms_aes128_cbc_hmac_sha2_512(void **state)
References s, ssh_socket_struct::session, test_algorithm.
Referenced by torture_run_tests.
static void torture_algorithms_aes128_cbc_hmac_sha1_etm(void **state)
References s, ssh_socket_struct::session, test_algorithm.
Referenced by torture_run_tests.
static void torture_algorithms_aes128_cbc_hmac_sha2_256_etm(void **state)
References s, ssh_socket_struct::session, test_algorithm.
Referenced by torture_run_tests.
static void torture_algorithms_aes128_cbc_hmac_sha2_512_etm(void **state)
References s, ssh_socket_struct::session, test_algorithm.
Referenced by torture_run_tests.
static void torture_algorithms_aes192_cbc_hmac_sha1(void **state)
References s, ssh_socket_struct::session, test_algorithm.
Referenced by torture_run_tests.
static void torture_algorithms_aes192_cbc_hmac_sha2_256(void **state)
References s, ssh_socket_struct::session, test_algorithm.
Referenced by torture_run_tests.
static void torture_algorithms_aes192_cbc_hmac_sha2_512(void **state)
References s, ssh_socket_struct::session, test_algorithm.
Referenced by torture_run_tests.
static void torture_algorithms_aes192_cbc_hmac_sha1_etm(void **state)
References s, ssh_socket_struct::session, test_algorithm.
Referenced by torture_run_tests.
static void torture_algorithms_aes192_cbc_hmac_sha2_256_etm(void **state)
References s, ssh_socket_struct::session, test_algorithm.
Referenced by torture_run_tests.
static void torture_algorithms_aes192_cbc_hmac_sha2_512_etm(void **state)
References s, ssh_socket_struct::session, test_algorithm.
Referenced by torture_run_tests.
static void torture_algorithms_aes256_cbc_hmac_sha1(void **state)
References s, ssh_socket_struct::session, test_algorithm.
Referenced by torture_run_tests.
static void torture_algorithms_aes256_cbc_hmac_sha2_256(void **state)
References s, ssh_socket_struct::session, test_algorithm.
Referenced by torture_run_tests.
static void torture_algorithms_aes256_cbc_hmac_sha2_512(void **state)
References s, ssh_socket_struct::session, test_algorithm.
Referenced by torture_run_tests.
static void torture_algorithms_aes256_cbc_hmac_sha1_etm(void **state)
References s, ssh_socket_struct::session, test_algorithm.
Referenced by torture_run_tests.
static void torture_algorithms_aes256_cbc_hmac_sha2_256_etm(void **state)
References s, ssh_socket_struct::session, test_algorithm.
Referenced by torture_run_tests.
static void torture_algorithms_aes256_cbc_hmac_sha2_512_etm(void **state)
References s, ssh_socket_struct::session, test_algorithm.
Referenced by torture_run_tests.
static void torture_algorithms_aes128_ctr_hmac_sha1(void **state)
References s, ssh_socket_struct::session, test_algorithm.
Referenced by torture_run_tests.
static void torture_algorithms_aes128_ctr_hmac_sha2_256(void **state)
References s, ssh_socket_struct::session, test_algorithm.
Referenced by torture_run_tests.
static void torture_algorithms_aes128_ctr_hmac_sha2_512(void **state)
References s, ssh_socket_struct::session, test_algorithm.
Referenced by torture_run_tests.
static void torture_algorithms_aes128_ctr_hmac_sha1_etm(void **state)
References s, ssh_socket_struct::session, test_algorithm.
Referenced by torture_run_tests.
static void torture_algorithms_aes128_ctr_hmac_sha2_256_etm(void **state)
References s, ssh_socket_struct::session, test_algorithm.
Referenced by torture_run_tests.
static void torture_algorithms_aes128_ctr_hmac_sha2_512_etm(void **state)
References s, ssh_socket_struct::session, test_algorithm.
Referenced by torture_run_tests.
static void torture_algorithms_aes192_ctr_hmac_sha1(void **state)
References s, ssh_socket_struct::session, test_algorithm.
Referenced by torture_run_tests.
static void torture_algorithms_aes192_ctr_hmac_sha2_256(void **state)
References s, ssh_socket_struct::session, test_algorithm.
Referenced by torture_run_tests.
static void torture_algorithms_aes192_ctr_hmac_sha2_512(void **state)
References s, ssh_socket_struct::session, test_algorithm.
Referenced by torture_run_tests.
static void torture_algorithms_aes192_ctr_hmac_sha1_etm(void **state)
References s, ssh_socket_struct::session, test_algorithm.
Referenced by torture_run_tests.
static void torture_algorithms_aes192_ctr_hmac_sha2_256_etm(void **state)
References s, ssh_socket_struct::session, test_algorithm.
Referenced by torture_run_tests.
static void torture_algorithms_aes192_ctr_hmac_sha2_512_etm(void **state)
References s, ssh_socket_struct::session, test_algorithm.
Referenced by torture_run_tests.
static void torture_algorithms_aes256_ctr_hmac_sha1(void **state)
References s, ssh_socket_struct::session, test_algorithm.
Referenced by torture_run_tests.
static void torture_algorithms_aes256_ctr_hmac_sha2_256(void **state)
References s, ssh_socket_struct::session, test_algorithm.
Referenced by torture_run_tests.
static void torture_algorithms_aes256_ctr_hmac_sha2_512(void **state)
References s, ssh_socket_struct::session, test_algorithm.
Referenced by torture_run_tests.
static void torture_algorithms_aes256_ctr_hmac_sha1_etm(void **state)
References s, ssh_socket_struct::session, test_algorithm.
Referenced by torture_run_tests.
static void torture_algorithms_aes256_ctr_hmac_sha2_256_etm(void **state)
References s, ssh_socket_struct::session, test_algorithm.
Referenced by torture_run_tests.
static void torture_algorithms_aes256_ctr_hmac_sha2_512_etm(void **state)
References s, ssh_socket_struct::session, test_algorithm.
Referenced by torture_run_tests.
static void torture_algorithms_aes128_gcm(void **state)
References s, ssh_socket_struct::session, test_algorithm.
Referenced by torture_run_tests.
static void torture_algorithms_aes256_gcm(void **state)
References s, ssh_socket_struct::session, test_algorithm.
Referenced by torture_run_tests.
static void torture_algorithms_3des_cbc_hmac_sha1(void **state)
References s, ssh_socket_struct::session, test_algorithm.
Referenced by torture_run_tests.
static void torture_algorithms_3des_cbc_hmac_sha2_256(void **state)
References s, ssh_socket_struct::session, test_algorithm.
Referenced by torture_run_tests.
static void torture_algorithms_3des_cbc_hmac_sha2_512(void **state)
References s, ssh_socket_struct::session, test_algorithm.
Referenced by torture_run_tests.
static void torture_algorithms_3des_cbc_hmac_sha1_etm(void **state)
References s, ssh_socket_struct::session, test_algorithm.
Referenced by torture_run_tests.
static void torture_algorithms_3des_cbc_hmac_sha2_256_etm(void **state)
References s, ssh_socket_struct::session, test_algorithm.
Referenced by torture_run_tests.
static void torture_algorithms_3des_cbc_hmac_sha2_512_etm(void **state)
References s, ssh_socket_struct::session, test_algorithm.
Referenced by torture_run_tests.
static void torture_algorithms_zlib(void **state)
References rc, s, ssh_socket_struct::session, session, ssh_connect, ssh_disconnect, SSH_ERROR, ssh_get_error_code, ssh_get_openssh_version, SSH_OK, SSH_OPTIONS_COMPRESSION_C_S, SSH_OPTIONS_COMPRESSION_S_C, ssh_options_set, SSH_REQUEST_DENIED, ssh_userauth_none.
Referenced by torture_run_tests.
static void torture_algorithms_zlib_openssh(void **state)
References rc, s, ssh_socket_struct::session, session, ssh_connect, ssh_disconnect, SSH_ERROR, ssh_get_error_code, ssh_get_openssh_version, SSH_OK, SSH_OPTIONS_COMPRESSION_C_S, SSH_OPTIONS_COMPRESSION_S_C, ssh_options_set, SSH_REQUEST_DENIED, ssh_userauth_none.
Referenced by torture_run_tests.
static void torture_algorithms_dh_group1(void **state)
References s, ssh_socket_struct::session, test_algorithm.
Referenced by torture_run_tests.
static void torture_algorithms_dh_group14(void **state)
References s, ssh_socket_struct::session, test_algorithm.
Referenced by torture_run_tests.
static void torture_algorithms_dh_group16(void **state)
References s, ssh_socket_struct::session, test_algorithm.
Referenced by torture_run_tests.
static void torture_algorithms_dh_group18(void **state)
References s, ssh_socket_struct::session, test_algorithm.
Referenced by torture_run_tests.
int torture_run_tests(void)
References rc, session_setup, session_teardown, ssh_finalize, ssh_init, sshd_setup, sshd_teardown, torture_algorithms_3des_cbc_hmac_sha1, torture_algorithms_3des_cbc_hmac_sha1_etm, torture_algorithms_3des_cbc_hmac_sha2_256, torture_algorithms_3des_cbc_hmac_sha2_256_etm, torture_algorithms_3des_cbc_hmac_sha2_512, torture_algorithms_3des_cbc_hmac_sha2_512_etm, torture_algorithms_aes128_cbc_hmac_sha1, torture_algorithms_aes128_cbc_hmac_sha1_etm, torture_algorithms_aes128_cbc_hmac_sha2_256, torture_algorithms_aes128_cbc_hmac_sha2_256_etm, torture_algorithms_aes128_cbc_hmac_sha2_512, torture_algorithms_aes128_cbc_hmac_sha2_512_etm, torture_algorithms_aes128_ctr_hmac_sha1, torture_algorithms_aes128_ctr_hmac_sha1_etm, torture_algorithms_aes128_ctr_hmac_sha2_256, torture_algorithms_aes128_ctr_hmac_sha2_256_etm, torture_algorithms_aes128_ctr_hmac_sha2_512, torture_algorithms_aes128_ctr_hmac_sha2_512_etm, torture_algorithms_aes128_gcm, torture_algorithms_aes192_cbc_hmac_sha1, torture_algorithms_aes192_cbc_hmac_sha1_etm, torture_algorithms_aes192_cbc_hmac_sha2_256, torture_algorithms_aes192_cbc_hmac_sha2_256_etm, torture_algorithms_aes192_cbc_hmac_sha2_512, torture_algorithms_aes192_cbc_hmac_sha2_512_etm, torture_algorithms_aes192_ctr_hmac_sha1, torture_algorithms_aes192_ctr_hmac_sha1_etm, torture_algorithms_aes192_ctr_hmac_sha2_256, torture_algorithms_aes192_ctr_hmac_sha2_256_etm, torture_algorithms_aes192_ctr_hmac_sha2_512, torture_algorithms_aes192_ctr_hmac_sha2_512_etm, torture_algorithms_aes256_cbc_hmac_sha1, torture_algorithms_aes256_cbc_hmac_sha1_etm, torture_algorithms_aes256_cbc_hmac_sha2_256, torture_algorithms_aes256_cbc_hmac_sha2_256_etm, torture_algorithms_aes256_cbc_hmac_sha2_512, torture_algorithms_aes256_cbc_hmac_sha2_512_etm, torture_algorithms_aes256_ctr_hmac_sha1, torture_algorithms_aes256_ctr_hmac_sha1_etm, torture_algorithms_aes256_ctr_hmac_sha2_256, torture_algorithms_aes256_ctr_hmac_sha2_256_etm, torture_algorithms_aes256_ctr_hmac_sha2_512, torture_algorithms_aes256_ctr_hmac_sha2_512_etm, torture_algorithms_aes256_gcm, torture_algorithms_dh_group1, torture_algorithms_dh_group14, torture_algorithms_dh_group16, torture_algorithms_dh_group18, torture_algorithms_zlib, torture_algorithms_zlib_openssh, torture_filter_tests.
Referenced by main.