torture_tokens.c
LIBSSH_STATIC
static void torture_find_matching(UNUSED_PARAM(void **state))
References SAFE_FREE, ssh_find_matching.
Referenced by torture_run_tests.
static void torture_find_all_matching(UNUSED_PARAM(void **state))
References SAFE_FREE, ssh_find_all_matching.
Referenced by torture_run_tests.
static void tokenize_compare_expected(const char *chain, const char **expected, size_t num_expected)
References ssh_tokenize, ssh_tokens_free, ssh_tokens_st::tokens.
Referenced by torture_tokens_sanity.
static void torture_tokens_sanity(UNUSED_PARAM(void **state))
References tokenize_compare_expected.
Referenced by torture_run_tests.
static void torture_remove_duplicate(UNUSED_PARAM(void **state))
References SAFE_FREE, ssh_remove_duplicates.
Referenced by torture_run_tests.
static void torture_append_without_duplicate(UNUSED_PARAM(void **state))
References SAFE_FREE, ssh_append_without_duplicates.
Referenced by torture_run_tests.
int torture_run_tests(void)
References rc, ssh_finalize, ssh_init, torture_append_without_duplicate, torture_filter_tests, torture_find_all_matching, torture_find_matching, torture_remove_duplicate, torture_tokens_sanity.