torture_pki.c
char* torture_pki_read_file(const char *filename)
References key, rc.
Referenced by thread_pki_rsa_import_privkey_base64, torture_pki_ecdsa_import_privkey_base64, torture_pki_ecdsa_import_privkey_base64_comment, torture_pki_ecdsa_import_privkey_base64_whitespace, torture_pki_ecdsa_publickey_base64, torture_pki_ecdsa_publickey_from_privatekey, torture_pki_ed25519_import_privkey_base64, torture_pki_ed25519_import_privkey_base64_comment, torture_pki_ed25519_import_privkey_base64_whitespace, torture_pki_rsa_import_privkey_base64, torture_pki_rsa_import_privkey_base64_comment, torture_pki_rsa_import_privkey_base64_whitespace.
int torture_read_one_line(const char *filename, char *buffer, size_t len)
References buffer.
Referenced by torture_pki_dsa_generate_pubkey_from_privkey, torture_pki_ecdsa_generate_pubkey_from_privkey, torture_pki_ecdsa_publickey_from_privatekey_uri, torture_pki_ed25519_generate_pubkey_from_privkey, torture_pki_rsa_generate_pubkey_from_privkey.
size_t torture_pubkey_len(const char *pubkey)
References pubkey.
Referenced by torture_pki_dsa_generate_pubkey_from_privkey, torture_pki_ecdsa_generate_pubkey_from_privkey, torture_pki_ed25519_generate_pubkey_from_privkey, torture_pki_rsa_generate_pubkey_from_privkey.