torture_packet.c
LIBSSH_STATIC
uint8_t test_data[][]
Referenced by torture_packet.
uint8_t key[][]
Referenced by torture_packet.
uint8_t iv[][]
Referenced by chacha_ivsetup, ssh_blf_cbc_decrypt, ssh_blf_cbc_encrypt, thread_crypto_aes256_cbc, torture_crypto_aes256_cbc, torture_packet.
uint8_t mac[][]
Referenced by chacha20_poly1305_aead_decrypt, match_hashed_host, ssh_packet_hmac_verify, ssh_packet_socket_callback, torture_packet.
static uint8_t* copy_data(uint8_t *data, size_t len)
Referenced by torture_packet.
static SSH_PACKET_CALLBACK(copy_packet_data)
References session, ssh_buffer_get_data, ssh_buffer_get_len, user.
static void torture_packet(const char *cipher, const char *mac_type, const char *comp_type, size_t payload_len)
References buffer, callbacks, cb, copy_data, crypt_set_algorithms_client, crypto_new, ssh_session_struct::current_crypto, ssh_crypto_struct::decryptIV, ssh_crypto_struct::decryptkey, ssh_crypto_struct::decryptMAC, ssh_crypto_struct::encryptIV, ssh_crypto_struct::encryptkey, ssh_crypto_struct::encryptMAC, explicit_bzero, ssh_socket_struct::fd, ssh_crypto_struct::in_cipher, iv, ssh_crypto_struct::kex_methods, key, mac, ssh_session_struct::next_crypto, ssh_session_struct::out_buffer, ssh_crypto_struct::out_cipher, rc, session, ssh_cipher_struct::set_decrypt_key, ssh_cipher_struct::set_encrypt_key, ssh_session_struct::socket, ssh_buffer_add_data, SSH_COMP_C_S, SSH_COMP_S_C, SSH_CRYPT_C_S, SSH_CRYPT_S_C, SSH_DIRECTION_BOTH, SSH_ERROR, ssh_free, SSH_HOSTKEYS, SSH_INVALID_SOCKET, SSH_KEX, SSH_LANG_C_S, SSH_LANG_S_C, SSH_MAC_C_S, SSH_MAC_S_C, ssh_new, SSH_OK, SSH_OPTIONS_LOG_VERBOSITY, ssh_options_set, ssh_packet_send, ssh_packet_set_callbacks, ssh_packet_socket_callback, test_data, torture_libssh_verbosity, ssh_crypto_struct::used, verbosity, ssh_socket_struct::write_wontblock.
Referenced by torture_packet_3des_cbc, torture_packet_3des_cbc_etm, torture_packet_aes128_cbc, torture_packet_aes128_cbc_etm, torture_packet_aes128_ctr, torture_packet_aes128_ctr_etm, torture_packet_aes128_gcm, torture_packet_aes192_cbc, torture_packet_aes192_cbc_etm, torture_packet_aes192_ctr, torture_packet_aes192_ctr_etm, torture_packet_aes256_cbc, torture_packet_aes256_cbc_etm, torture_packet_aes256_ctr, torture_packet_aes256_ctr_etm, torture_packet_aes256_gcm, torture_packet_chacha20, torture_packet_compress_zlib, torture_packet_compress_zlib_openssh.
static void torture_packet_aes128_ctr_etm(UNUSED_PARAM(void **state))
References torture_packet.
Referenced by torture_run_tests.
static void torture_packet_aes192_ctr_etm(UNUSED_PARAM(void **state))
References torture_packet.
Referenced by torture_run_tests.
static void torture_packet_aes256_ctr_etm(UNUSED_PARAM(void **state))
References torture_packet.
Referenced by torture_run_tests.
static void torture_packet_aes128_ctr(void **state)
References torture_packet.
Referenced by torture_run_tests.
static void torture_packet_aes192_ctr(void **state)
References torture_packet.
Referenced by torture_run_tests.
static void torture_packet_aes256_ctr(void **state)
References torture_packet.
Referenced by torture_run_tests.
static void torture_packet_aes128_cbc(void **state)
References torture_packet.
Referenced by torture_run_tests.
static void torture_packet_aes192_cbc(void **state)
References torture_packet.
Referenced by torture_run_tests.
static void torture_packet_aes256_cbc(void **state)
References torture_packet.
Referenced by torture_run_tests.
static void torture_packet_aes128_cbc_etm(UNUSED_PARAM(void **state))
References torture_packet.
Referenced by torture_run_tests.
static void torture_packet_aes192_cbc_etm(UNUSED_PARAM(void **state))
References torture_packet.
Referenced by torture_run_tests.
static void torture_packet_aes256_cbc_etm(UNUSED_PARAM(void **state))
References torture_packet.
Referenced by torture_run_tests.
static void torture_packet_3des_cbc(void **state)
References torture_packet.
Referenced by torture_run_tests.
static void torture_packet_3des_cbc_etm(UNUSED_PARAM(void **state))
References torture_packet.
Referenced by torture_run_tests.
static void torture_packet_chacha20(void **state)
References torture_packet.
Referenced by torture_run_tests.
static void torture_packet_aes128_gcm(void **state)
References torture_packet.
Referenced by torture_run_tests.
static void torture_packet_aes256_gcm(void **state)
References torture_packet.
Referenced by torture_run_tests.
static void torture_packet_compress_zlib(void **state)
References torture_packet.
Referenced by torture_run_tests.
static void torture_packet_compress_zlib_openssh(void **state)
References torture_packet.
Referenced by torture_run_tests.
int torture_run_tests(void)
References rc, ssh_finalize, ssh_init, torture_filter_tests, torture_packet_3des_cbc, torture_packet_3des_cbc_etm, torture_packet_aes128_cbc, torture_packet_aes128_cbc_etm, torture_packet_aes128_ctr, torture_packet_aes128_ctr_etm, torture_packet_aes128_gcm, torture_packet_aes192_cbc, torture_packet_aes192_cbc_etm, torture_packet_aes192_ctr, torture_packet_aes192_ctr_etm, torture_packet_aes256_cbc, torture_packet_aes256_cbc_etm, torture_packet_aes256_ctr, torture_packet_aes256_ctr_etm, torture_packet_aes256_gcm, torture_packet_chacha20, torture_packet_compress_zlib, torture_packet_compress_zlib_openssh.