torture_knownhosts_parsing.c
LIBSSH_STATIC
LOCALHOST_RSA_LINE
LOCALHOST_ECDSA_SHA1_NISTP256_LINE
LOCALHOST_DEFAULT_ED25519
LOCALHOST_PORT_ED25519
LOCALHOST_PATTERN_ED25519
LOCALHOST_HASHED_ED25519
LOCALHOST_PORT_WILDCARD
LOCALHOST_STANDARD_PORT
TMP_FILE_NAME
const char template[][]
static int setup_knownhosts_file(void **state)
References LOCALHOST_PATTERN_ED25519, LOCALHOST_RSA_LINE, rc, TMP_FILE_NAME, torture_create_temp_file.
Referenced by torture_run_tests.
static int setup_knownhosts_file_duplicate(void **state)
References LOCALHOST_PATTERN_ED25519, LOCALHOST_RSA_LINE, rc, TMP_FILE_NAME, torture_create_temp_file.
Referenced by torture_run_tests.
static int teardown_knownhosts_file(void **state)
References SAFE_FREE.
Referenced by torture_run_tests.
static void torture_knownhosts_parse_line_rsa(void **state)
References ssh_knownhosts_entry::comment, ssh_knownhosts_entry::hostname, LOCALHOST_RSA_LINE, ssh_knownhosts_entry::publickey, rc, ssh_key_type, SSH_KEYTYPE_RSA, ssh_known_hosts_parse_line, SSH_KNOWNHOSTS_ENTRY_FREE, SSH_OK, ssh_knownhosts_entry::unparsed.
Referenced by torture_run_tests.
static void torture_knownhosts_parse_line_ecdsa(void **state)
References ssh_knownhosts_entry::hostname, LOCALHOST_ECDSA_SHA1_NISTP256_LINE, ssh_knownhosts_entry::publickey, rc, ssh_key_type, SSH_KEYTYPE_ECDSA_P256, ssh_known_hosts_parse_line, SSH_KNOWNHOSTS_ENTRY_FREE, SSH_OK, ssh_knownhosts_entry::unparsed.
Referenced by torture_run_tests.
static void torture_knownhosts_parse_line_default_ed25519(void **state)
References ssh_knownhosts_entry::hostname, LOCALHOST_DEFAULT_ED25519, ssh_knownhosts_entry::publickey, rc, ssh_key_type, SSH_KEYTYPE_ED25519, ssh_known_hosts_parse_line, SSH_KNOWNHOSTS_ENTRY_FREE, SSH_OK, ssh_knownhosts_entry::unparsed.
Referenced by torture_run_tests.
static void torture_knownhosts_parse_line_port_ed25519(void **state)
References ssh_knownhosts_entry::hostname, LOCALHOST_PORT_ED25519, ssh_knownhosts_entry::publickey, rc, ssh_key_type, SSH_KEYTYPE_ED25519, ssh_known_hosts_parse_line, SSH_KNOWNHOSTS_ENTRY_FREE, SSH_OK, ssh_knownhosts_entry::unparsed.
Referenced by torture_run_tests.
static void torture_knownhosts_parse_line_port_wildcard(void **state)
References ssh_knownhosts_entry::hostname, LOCALHOST_PORT_WILDCARD, ssh_knownhosts_entry::publickey, rc, ssh_key_type, SSH_KEYTYPE_ED25519, ssh_known_hosts_parse_line, SSH_KNOWNHOSTS_ENTRY_FREE, SSH_OK, ssh_knownhosts_entry::unparsed.
Referenced by torture_run_tests.
static void torture_knownhosts_parse_line_standard_port(void **state)
References ssh_knownhosts_entry::hostname, LOCALHOST_STANDARD_PORT, ssh_knownhosts_entry::publickey, rc, ssh_key_type, SSH_KEYTYPE_ED25519, ssh_known_hosts_parse_line, SSH_KNOWNHOSTS_ENTRY_FREE, SSH_OK, ssh_knownhosts_entry::unparsed.
Referenced by torture_run_tests.
static void torture_knownhosts_parse_line_pattern_ed25519(void **state)
References ssh_knownhosts_entry::hostname, LOCALHOST_PATTERN_ED25519, ssh_knownhosts_entry::publickey, rc, ssh_key_type, SSH_KEYTYPE_ED25519, ssh_known_hosts_parse_line, SSH_KNOWNHOSTS_ENTRY_FREE, SSH_OK, ssh_knownhosts_entry::unparsed.
Referenced by torture_run_tests.
static void torture_knownhosts_parse_line_hashed_ed25519(void **state)
References ssh_knownhosts_entry::hostname, LOCALHOST_HASHED_ED25519, ssh_knownhosts_entry::publickey, rc, ssh_key_type, SSH_KEYTYPE_ED25519, ssh_known_hosts_parse_line, SSH_KNOWNHOSTS_ENTRY_FREE, SSH_OK, ssh_knownhosts_entry::unparsed.
Referenced by torture_run_tests.
static void torture_knownhosts_read_file(void **state)
References ssh_knownhosts_entry::hostname, ssh_iterator::next, ssh_knownhosts_entry::publickey, rc, ssh_iterator_value, ssh_key_type, SSH_KEYTYPE_ED25519, SSH_KEYTYPE_RSA, ssh_known_hosts_read_entries, SSH_KNOWNHOSTS_ENTRY_FREE, ssh_list_free, ssh_list_get_iterator, SSH_OK.
Referenced by torture_run_tests.
static void torture_knownhosts_get_algorithms_names(void **state)
References SAFE_FREE, session, ssh_free, ssh_known_hosts_get_algorithms_names, ssh_new, SSH_OPTIONS_HOST, SSH_OPTIONS_KNOWNHOSTS, SSH_OPTIONS_PROCESS_CONFIG, ssh_options_set.
Referenced by torture_run_tests.
static void torture_knownhosts_algorithms_wanted(void **state)
References session, ssh_client_select_hostkeys, ssh_free, ssh_new, SSH_OPTIONS_HOST, SSH_OPTIONS_HOSTKEYS, SSH_OPTIONS_KNOWNHOSTS, SSH_OPTIONS_LOG_VERBOSITY, SSH_OPTIONS_PROCESS_CONFIG, ssh_options_set.
Referenced by torture_run_tests.
static void torture_knownhosts_algorithms_negative(UNUSED_PARAM(void **state))
References LOCALHOST_DEFAULT_ED25519, rc, SAFE_FREE, session, ssh_client_select_hostkeys, ssh_free, ssh_new, SSH_OPTIONS_HOST, SSH_OPTIONS_HOSTKEYS, SSH_OPTIONS_KNOWNHOSTS, SSH_OPTIONS_LOG_VERBOSITY, SSH_OPTIONS_PROCESS_CONFIG, ssh_options_set, torture_change_dir, torture_get_current_working_dir, torture_make_temp_dir, torture_rmdirs, torture_write_file.
Referenced by torture_run_tests.
static void torture_knownhosts_host_exists(void **state)
References session, ssh_free, SSH_KNOWN_HOSTS_OK, SSH_KNOWN_HOSTS_UNKNOWN, ssh_new, SSH_OPTIONS_GLOBAL_KNOWNHOSTS, SSH_OPTIONS_HOST, SSH_OPTIONS_KNOWNHOSTS, ssh_options_set, ssh_session_has_known_hosts_entry.
Referenced by torture_run_tests.
static void torture_knownhosts_host_exists_global(void **state)
References session, ssh_free, SSH_KNOWN_HOSTS_OK, SSH_KNOWN_HOSTS_UNKNOWN, ssh_new, SSH_OPTIONS_GLOBAL_KNOWNHOSTS, SSH_OPTIONS_HOST, SSH_OPTIONS_KNOWNHOSTS, ssh_options_set, ssh_session_has_known_hosts_entry.
Referenced by torture_run_tests.
static void torture_knownhosts_algorithms(void **state)
References session, ssh_client_select_hostkeys, ssh_free, ssh_new, SSH_OPTIONS_GLOBAL_KNOWNHOSTS, SSH_OPTIONS_HOST, SSH_OPTIONS_KNOWNHOSTS, SSH_OPTIONS_PROCESS_CONFIG, ssh_options_set.
Referenced by torture_run_tests.
static void torture_knownhosts_algorithms_global(void **state)
References session, ssh_client_select_hostkeys, ssh_free, ssh_new, SSH_OPTIONS_GLOBAL_KNOWNHOSTS, SSH_OPTIONS_HOST, SSH_OPTIONS_KNOWNHOSTS, SSH_OPTIONS_PROCESS_CONFIG, ssh_options_set.
Referenced by torture_run_tests.
int torture_run_tests(void)
References rc, setup_knownhosts_file, setup_knownhosts_file_duplicate, ssh_finalize, ssh_init, teardown_knownhosts_file, torture_filter_tests, torture_knownhosts_algorithms, torture_knownhosts_algorithms_global, torture_knownhosts_algorithms_negative, torture_knownhosts_algorithms_wanted, torture_knownhosts_get_algorithms_names, torture_knownhosts_host_exists, torture_knownhosts_host_exists_global, torture_knownhosts_parse_line_default_ed25519, torture_knownhosts_parse_line_ecdsa, torture_knownhosts_parse_line_hashed_ed25519, torture_knownhosts_parse_line_pattern_ed25519, torture_knownhosts_parse_line_port_ed25519, torture_knownhosts_parse_line_port_wildcard, torture_knownhosts_parse_line_rsa, torture_knownhosts_parse_line_standard_port, torture_knownhosts_read_file.