torture_threads_init.c
LIBSSH_STATIC
NUM_THREADS
static int run_on_threads(void *(*func)(void *))
References NUM_THREADS, rc.
Referenced by torture_ssh_init.
static void* thread_ssh_init(UNUSED_PARAM(void *threadid))
References rc, ssh_finalize, ssh_init, SSH_OK.
Referenced by torture_ssh_init.
static void torture_ssh_init(UNUSED_PARAM(void **state))
References rc, run_on_threads, thread_ssh_init.
Referenced by torture_run_tests.
int torture_run_tests(void)
References rc, ssh_finalize, ssh_init, torture_filter_tests, torture_ssh_init.