torture_list.c
LIBSSH_STATIC
static void torture_ssh_list_new(void **state)
References ssh_list::end, ssh_list::root, ssh_list_count, ssh_list_free, ssh_list_new.
Referenced by torture_run_tests.
static void torture_ssh_list_append(void **state)
References ssh_iterator::data, ssh_list::end, ssh_iterator::next, rc, ssh_list::root, ssh_list_append, ssh_list_count, ssh_list_free, ssh_list_new.
Referenced by torture_run_tests.
static void torture_ssh_list_prepend(void **state)
References ssh_iterator::data, ssh_list::end, ssh_iterator::next, rc, ssh_list::root, ssh_list_append, ssh_list_count, ssh_list_free, ssh_list_new, ssh_list_prepend.
Referenced by torture_run_tests.
int torture_run_tests(void)
References rc, ssh_finalize, ssh_init, torture_filter_tests, torture_ssh_list_append, torture_ssh_list_new, torture_ssh_list_prepend.