torture_proxycommand.c
LIBSSH_STATIC
static int sshd_setup(void **state)
References torture_setup_sshd_server.
Referenced by torture_run_tests.
static int sshd_teardown(void **state)
References torture_teardown_sshd_server.
Referenced by torture_run_tests.
static int session_setup(void **state)
References assert_return_code, rc, s, ssh_socket_struct::session, ssh_new, SSH_OPTIONS_HOST, SSH_OPTIONS_LOG_VERBOSITY, ssh_options_set, SSH_OPTIONS_USER, torture_libssh_verbosity, TORTURE_SSH_SERVER, TORTURE_SSH_USER_ALICE, verbosity.
Referenced by torture_run_tests.
static int session_teardown(void **state)
References s, ssh_socket_struct::session, ssh_disconnect, ssh_free.
Referenced by torture_run_tests.
static void torture_options_set_proxycommand(void **state)
Referenced by torture_run_tests.
static void torture_options_set_proxycommand_notexist(void **state)
References assert_ssh_return_code, assert_ssh_return_code_equal, rc, s, ssh_socket_struct::session, session, ssh_connect, SSH_ERROR, SSH_OPTIONS_PROXYCOMMAND, ssh_options_set.
Referenced by torture_run_tests.
static void torture_options_set_proxycommand_ssh(void **state)
References assert_ssh_return_code, rc, s, ssh_socket_struct::session, session, ssh_connect, ssh_get_fd, SSH_INVALID_SOCKET, SSH_OPTIONS_PROXYCOMMAND, ssh_options_set, torture_server_address.
Referenced by torture_run_tests.
static void torture_options_set_proxycommand_ssh_stderr(void **state)
References assert_ssh_return_code, rc, s, ssh_socket_struct::session, session, ssh_connect, ssh_get_fd, SSH_INVALID_SOCKET, SSH_OPTIONS_PROXYCOMMAND, ssh_options_set, torture_server_address.
Referenced by torture_run_tests.
int torture_run_tests(void)
References rc, session_setup, session_teardown, ssh_finalize, ssh_init, sshd_setup, sshd_teardown, torture_filter_tests, torture_options_set_proxycommand, torture_options_set_proxycommand_notexist, torture_options_set_proxycommand_ssh, torture_options_set_proxycommand_ssh_stderr.