torture_client_config.c
LIBSSH_STATIC
LIBSSH_SSH_CONFIG
TORTURE_CONFIG_USER
CIPHERS
CIPHERS2
static int sshd_setup(void **state)
References torture_setup_sshd_server.
Referenced by torture_run_tests.
static int sshd_teardown(void **state)
References torture_teardown_sshd_server.
Referenced by torture_run_tests.
static int setup_config_files(void **state)
References assert_return_code, CIPHERS, CIPHERS2, LIBSSH_SSH_CONFIG, rc, s, ssh_socket_struct::session, ssh_new, SSH_OPTIONS_HOST, SSH_OPTIONS_LOG_VERBOSITY, ssh_options_set, ssh_path_expand_tilde, TORTURE_CONFIG_USER, torture_libssh_verbosity, TORTURE_SSH_SERVER, torture_write_file, verbosity.
Referenced by torture_run_tests.
static int teardown(void **state)
References LIBSSH_SSH_CONFIG, s, SAFE_FREE, ssh_socket_struct::session, ssh_disconnect, ssh_free, ssh_path_expand_tilde.
Referenced by pkd_run_tests, torture_run_tests.
static void torture_client_config_system(void **state)
References assert_ssh_return_code, CIPHERS, ssh_session_struct::opts, s, SAFE_FREE, ssh_socket_struct::session, SSH_CRYPT_C_S, SSH_CRYPT_S_C, ssh_keep_fips_algos, ssh_options_parse_config, TORTURE_CONFIG_USER, ssh_session_struct::username, ssh_session_struct::wanted_methods.
Referenced by torture_run_tests.
static void torture_client_config_emulate(void **state)
References assert_ssh_return_code, CIPHERS, LIBSSH_SSH_CONFIG, ssh_session_struct::opts, s, SAFE_FREE, ssh_socket_struct::session, SSH_CRYPT_C_S, SSH_CRYPT_S_C, ssh_keep_fips_algos, ssh_options_parse_config, ssh_path_expand_tilde, TORTURE_CONFIG_USER, ssh_session_struct::username, ssh_session_struct::wanted_methods.
Referenced by torture_run_tests.
static void torture_client_config_autoparse(void **state)
References assert_ssh_return_code, ssh_session_struct::opts, s, ssh_socket_struct::session, ssh_connect, TORTURE_CONFIG_USER, ssh_session_struct::username.
Referenced by torture_run_tests.
static void torture_client_config_suppress(void **state)
References assert_ssh_return_code, ssh_session_struct::opts, s, ssh_socket_struct::session, ssh_connect, SSH_OPTIONS_PROCESS_CONFIG, ssh_options_set, ssh_session_struct::username.
Referenced by torture_run_tests.
int torture_run_tests(void)
References rc, setup_config_files, ssh_finalize, ssh_init, sshd_setup, sshd_teardown, teardown, torture_client_config_autoparse, torture_client_config_emulate, torture_client_config_suppress, torture_client_config_system, torture_filter_tests.