torture_threads_buffer.c
LIBSSH_STATIC
DEBUG_BUFFER
NUM_THREADS
BUFFER_LIMIT
NUM_TESTS
static int run_on_threads(void *(*func)(void *))
References NUM_THREADS, rc.
Referenced by torture_buffer_pack_badformat, torture_buffer_prepend, torture_growing_buffer, torture_growing_buffer_shifting, torture_ssh_buffer_add_format, torture_ssh_buffer_get_format, torture_ssh_buffer_get_format_error, torture_ssh_buffer_get_ssh_string.
static void* thread_growing_buffer(void *threadid)
References buffer, BUFFER_LIMIT, ssh_buffer_add_data, SSH_BUFFER_FREE, ssh_buffer_get_len, ssh_buffer_new, ssh_buffer_set_secure.
Referenced by torture_growing_buffer, torture_mixed.
static void torture_growing_buffer(void **state)
References rc, run_on_threads, thread_growing_buffer.
Referenced by torture_run_tests.
static void* thread_growing_buffer_shifting(void *threadid)
References buffer, BUFFER_LIMIT, ssh_buffer_add_data, SSH_BUFFER_FREE, ssh_buffer_get_len, ssh_buffer_get_u8, ssh_buffer_new, ssh_buffer_set_secure.
Referenced by torture_growing_buffer_shifting, torture_mixed.
static void torture_growing_buffer_shifting(void **state)
References rc, run_on_threads, thread_growing_buffer_shifting.
Referenced by torture_run_tests.
static void* thread_buffer_prepend(void *threadid)
References buffer, ssh_buffer_add_data, SSH_BUFFER_FREE, ssh_buffer_get, ssh_buffer_get_len, ssh_buffer_get_u32, ssh_buffer_new, ssh_buffer_prepend_data, ssh_buffer_set_secure.
Referenced by torture_buffer_prepend, torture_mixed.
static void torture_buffer_prepend(void **state)
References rc, run_on_threads, thread_buffer_prepend.
Referenced by torture_run_tests.
static void* thread_ssh_buffer_get_ssh_string(void *threadid)
References ARRAY_SIZE, buffer, k, rc, ssh_buffer_add_data, ssh_buffer_add_u32, SSH_BUFFER_FREE, ssh_buffer_get_ssh_string, ssh_buffer_new, SSH_STRING_FREE.
Referenced by torture_mixed, torture_ssh_buffer_get_ssh_string.
static void torture_ssh_buffer_get_ssh_string(void **state)
References rc, run_on_threads, thread_ssh_buffer_get_ssh_string.
Referenced by torture_run_tests.
static void* thread_ssh_buffer_add_format(void *threadid)
References buffer, rc, s, SSH_BUFFER_FREE, ssh_buffer_get, ssh_buffer_get_len, ssh_buffer_new, ssh_buffer_pack, ssh_buffer_set_secure, SSH_OK, SSH_STRING_FREE, ssh_string_from_char.
Referenced by torture_mixed, torture_ssh_buffer_add_format.
static void torture_ssh_buffer_add_format(void **state)
References rc, run_on_threads, thread_ssh_buffer_add_format.
Referenced by torture_run_tests.
static void* thread_ssh_buffer_get_format(void *threadid)
References buffer, rc, s, SAFE_FREE, ssh_buffer_add_data, SSH_BUFFER_FREE, ssh_buffer_get_len, ssh_buffer_new, ssh_buffer_set_secure, ssh_buffer_unpack, SSH_OK, ssh_string_data, ssh_string_len.
Referenced by torture_mixed, torture_ssh_buffer_get_format.
static void torture_ssh_buffer_get_format(void **state)
References rc, run_on_threads, thread_ssh_buffer_get_format.
Referenced by torture_run_tests.
static void* thread_ssh_buffer_get_format_error(void *threadid)
References buffer, rc, s, ssh_buffer_add_data, SSH_BUFFER_FREE, ssh_buffer_new, ssh_buffer_set_secure, ssh_buffer_unpack, SSH_ERROR, SSH_OK.
Referenced by torture_mixed, torture_ssh_buffer_get_format_error.
static void torture_ssh_buffer_get_format_error(void **state)
References rc, run_on_threads, thread_ssh_buffer_get_format_error.
Referenced by torture_run_tests.
static void* thread_buffer_pack_badformat(void *threadid)
References buffer, rc, SSH_BUFFER_FREE, ssh_buffer_new, ssh_buffer_pack, ssh_buffer_reinit, ssh_buffer_set_secure, ssh_buffer_unpack, SSH_ERROR, SSH_OK.
Referenced by torture_buffer_pack_badformat, torture_mixed.
static void torture_buffer_pack_badformat(void **state)
References rc, run_on_threads, thread_buffer_pack_badformat.
Referenced by torture_run_tests.
static void torture_mixed(void **state)
References NUM_TESTS, NUM_THREADS, rc, thread_buffer_pack_badformat, thread_buffer_prepend, thread_growing_buffer, thread_growing_buffer_shifting, thread_ssh_buffer_add_format, thread_ssh_buffer_get_format, thread_ssh_buffer_get_format_error, thread_ssh_buffer_get_ssh_string.
Referenced by torture_run_tests.
int torture_run_tests(void)
References rc, ssh_finalize, ssh_init, torture_buffer_pack_badformat, torture_buffer_prepend, torture_filter_tests, torture_growing_buffer, torture_growing_buffer_shifting, torture_mixed, torture_ssh_buffer_add_format, torture_ssh_buffer_get_format, torture_ssh_buffer_get_format_error, torture_ssh_buffer_get_ssh_string.