torture_buffer.c
LIBSSH_STATIC
DEBUG_BUFFER
LIMIT
static int setup(void **state)
References buffer, ssh_buffer_new, ssh_buffer_set_secure.
Referenced by torture_run_tests.
static int teardown(void **state)
References SSH_BUFFER_FREE.
Referenced by torture_run_tests.
static void torture_growing_buffer(void **state)
References buffer, LIMIT, ssh_buffer_add_data, ssh_buffer_get_len.
Referenced by torture_run_tests.
static void torture_growing_buffer_shifting(void **state)
References buffer, LIMIT, ssh_buffer_add_data, ssh_buffer_get_len, ssh_buffer_get_u8.
Referenced by torture_run_tests.
static void torture_buffer_prepend(void **state)
References buffer, ssh_buffer_add_data, ssh_buffer_get, ssh_buffer_get_len, ssh_buffer_get_u32, ssh_buffer_prepend_data.
Referenced by torture_run_tests.
static void torture_ssh_buffer_get_ssh_string(void **state)
References buffer, k, rc, ssh_buffer_add_data, ssh_buffer_add_u32, SSH_BUFFER_FREE, ssh_buffer_get_ssh_string, ssh_buffer_new, SSH_STRING_FREE.
Referenced by torture_run_tests.
static void torture_ssh_buffer_add_format(void **state)
References buffer, rc, s, ssh_buffer_get, ssh_buffer_get_len, ssh_buffer_pack, SSH_OK, SSH_STRING_FREE, ssh_string_from_char.
Referenced by torture_run_tests.
static void torture_ssh_buffer_get_format(void **state)
References buffer, rc, s, SAFE_FREE, ssh_buffer_add_data, ssh_buffer_get_len, ssh_buffer_unpack, SSH_OK, ssh_string_data, ssh_string_len.
Referenced by torture_run_tests.
static void torture_ssh_buffer_get_format_error(void **state)
References buffer, rc, s, ssh_buffer_add_data, ssh_buffer_unpack, SSH_ERROR, SSH_OK.
Referenced by torture_run_tests.
static void torture_buffer_pack_badformat(void **state)
References buffer, rc, ssh_buffer_pack, ssh_buffer_reinit, ssh_buffer_unpack, SSH_ERROR, SSH_OK.
Referenced by torture_run_tests.
int torture_run_tests(void)
References rc, setup, ssh_finalize, ssh_init, teardown, torture_buffer_pack_badformat, torture_buffer_prepend, torture_filter_tests, torture_growing_buffer, torture_growing_buffer_shifting, torture_ssh_buffer_add_format, torture_ssh_buffer_get_format, torture_ssh_buffer_get_format_error, torture_ssh_buffer_get_ssh_string.