torture_threads_pki_rsa.c
LIBSSH_STATIC
LIBSSH_RSA_TESTKEY
LIBSSH_RSA_TESTKEY_PASSPHRASE
NUM_THREADS
NUM_TESTS
const char template[][]
const unsigned char RSA_HASH[][]
Referenced by thread_pki_rsa_generate_key.
static int run_on_threads(void *(*func)(void *))
References NUM_THREADS, rc.
Referenced by torture_pki_rsa_copy_cert_to_privkey, torture_pki_rsa_duplicate_key, torture_pki_rsa_generate_key, torture_pki_rsa_import_cert_file, torture_pki_rsa_import_privkey_base64, torture_pki_rsa_import_privkey_base64_NULL_key, torture_pki_rsa_import_privkey_base64_NULL_str, torture_pki_rsa_import_privkey_base64_passphrase, torture_pki_rsa_import_pubkey_file, torture_pki_rsa_publickey_base64, torture_pki_rsa_publickey_from_privatekey.
static int setup_rsa_key(void **state)
References pki_st::cwd, LIBSSH_RSA_TESTKEY, LIBSSH_RSA_TESTKEY_PASSPHRASE, rc, SSH_KEYTYPE_RSA, SSH_KEYTYPE_RSA_CERT01, pki_st::temp_dir, torture_change_dir, torture_get_current_working_dir, torture_get_testkey, torture_get_testkey_pub, torture_make_temp_dir, torture_write_file.
Referenced by torture_run_tests.
static int teardown(void **state)
References pki_st::cwd, rc, SAFE_FREE, pki_st::temp_dir, torture_change_dir, torture_rmdirs.
Referenced by torture_run_tests.
static int disable_secmem(void **state)
Referenced by torture_run_tests.
static int enable_secmem(void **state)
Referenced by torture_run_tests.
static void* thread_pki_rsa_import_pubkey_file(void *threadid)
References assert_return_code, LIBSSH_RSA_TESTKEY, pubkey, rc, SSH_KEY_FREE, ssh_pki_import_pubkey_file.
Referenced by torture_mixed, torture_pki_rsa_import_pubkey_file.
static void torture_pki_rsa_import_pubkey_file(void **state)
References rc, run_on_threads, thread_pki_rsa_import_pubkey_file.
Referenced by torture_run_tests.
static void* thread_pki_rsa_import_privkey_base64_NULL_key(void *threadid)
References rc, SSH_KEYTYPE_RSA, ssh_pki_import_privkey_base64, torture_get_testkey, torture_get_testkey_passphrase.
Referenced by torture_mixed, torture_pki_rsa_import_privkey_base64_NULL_key.
static void torture_pki_rsa_import_privkey_base64_NULL_key(void **state)
References rc, run_on_threads, thread_pki_rsa_import_privkey_base64_NULL_key.
Referenced by torture_run_tests.
static void* thread_pki_rsa_import_privkey_base64_NULL_str(void *threadid)
References key, rc, SSH_KEY_FREE, ssh_pki_import_privkey_base64, torture_get_testkey_passphrase.
Referenced by torture_mixed, torture_pki_rsa_import_privkey_base64_NULL_str.
static void torture_pki_rsa_import_privkey_base64_NULL_str(void **state)
References rc, run_on_threads, thread_pki_rsa_import_privkey_base64_NULL_str.
Referenced by torture_run_tests.
static void* thread_pki_rsa_import_privkey_base64(void *threadid)
References key, LIBSSH_RSA_TESTKEY, rc, SSH_KEY_FREE, ssh_key_is_private, ssh_key_is_public, ssh_key_type, SSH_KEYTYPE_RSA, ssh_pki_import_privkey_base64, torture_get_testkey_passphrase, torture_pki_read_file.
Referenced by torture_mixed, torture_pki_rsa_import_privkey_base64.
static void torture_pki_rsa_import_privkey_base64(void **state)
References rc, run_on_threads, thread_pki_rsa_import_privkey_base64.
Referenced by torture_run_tests.
static void* thread_pki_rsa_publickey_from_privatekey(void *threadid)
References key, pubkey, rc, SSH_KEY_FREE, ssh_key_is_private, SSH_KEYTYPE_RSA, SSH_OK, ssh_pki_export_privkey_to_pubkey, ssh_pki_import_privkey_base64, torture_get_testkey.
Referenced by torture_mixed, torture_pki_rsa_publickey_from_privatekey.
static void torture_pki_rsa_publickey_from_privatekey(void **state)
References rc, run_on_threads, thread_pki_rsa_publickey_from_privatekey.
Referenced by torture_run_tests.
static void* thread_pki_rsa_copy_cert_to_privkey(void *threadid)
References LIBSSH_RSA_TESTKEY, privkey, pubkey, rc, SSH_ERROR, SSH_KEY_FREE, SSH_KEYTYPE_RSA, SSH_OK, ssh_pki_copy_cert_to_privkey, ssh_pki_import_cert_file, ssh_pki_import_privkey_base64, ssh_pki_import_pubkey_file, torture_get_testkey, torture_get_testkey_passphrase.
Referenced by torture_mixed, torture_pki_rsa_copy_cert_to_privkey.
static void torture_pki_rsa_copy_cert_to_privkey(void **state)
References rc, run_on_threads, thread_pki_rsa_copy_cert_to_privkey.
Referenced by torture_run_tests.
static void* thread_pki_rsa_import_cert_file(void *threadid)
References LIBSSH_RSA_TESTKEY, rc, SSH_KEY_FREE, ssh_key_is_public, ssh_key_type, SSH_KEYTYPE_RSA_CERT01, ssh_pki_import_cert_file.
Referenced by torture_mixed, torture_pki_rsa_import_cert_file.
static void torture_pki_rsa_import_cert_file(void **state)
References rc, run_on_threads, thread_pki_rsa_import_cert_file.
Referenced by torture_run_tests.
static void* thread_pki_rsa_publickey_base64(void *threadid)
References key, rc, SSH_KEY_FREE, ssh_key_type_from_name, SSH_KEYTYPE_RSA, ssh_pki_export_pubkey_base64, ssh_pki_import_pubkey_base64, torture_get_testkey_pub.
Referenced by torture_mixed, torture_pki_rsa_publickey_base64.
static void torture_pki_rsa_publickey_base64(void **state)
References rc, run_on_threads, thread_pki_rsa_publickey_base64.
Referenced by torture_run_tests.
static void* thread_pki_rsa_duplicate_key(void *threadid)
References LIBSSH_RSA_TESTKEY, privkey, pubkey, rc, ssh_key_cmp, SSH_KEY_CMP_PRIVATE, ssh_key_dup, SSH_KEY_FREE, SSH_OK, ssh_pki_export_privkey_to_pubkey, ssh_pki_export_pubkey_base64, ssh_pki_import_privkey_file, ssh_pki_import_pubkey_file, SSH_STRING_FREE_CHAR.
Referenced by torture_mixed, torture_pki_rsa_duplicate_key.
static void torture_pki_rsa_duplicate_key(void **state)
References rc, run_on_threads, thread_pki_rsa_duplicate_key.
Referenced by torture_run_tests.
static void* thread_pki_rsa_generate_key(void *threadid)
References assert_ssh_return_code, key, pki_do_sign, pubkey, rc, RSA_HASH, session, SSH_DIGEST_SHA256, ssh_free, SSH_KEY_FREE, SSH_KEYTYPE_RSA, ssh_new, SSH_OK, ssh_pki_export_privkey_to_pubkey, ssh_pki_generate, ssh_pki_signature_verify, ssh_signature_free.
Referenced by torture_mixed, torture_pki_rsa_generate_key.
static void torture_pki_rsa_generate_key(void **state)
References rc, run_on_threads, thread_pki_rsa_generate_key.
Referenced by torture_run_tests.
static void* thread_pki_rsa_import_privkey_base64_passphrase(void *threadid)
References assert_return_code, key, rc, SSH_KEY_FREE, ssh_key_is_private, SSH_KEYTYPE_RSA, ssh_pki_import_privkey_base64, torture_get_testkey, torture_get_testkey_passphrase.
Referenced by torture_mixed, torture_pki_rsa_import_privkey_base64_passphrase.
static void torture_pki_rsa_import_privkey_base64_passphrase(void **state)
References rc, run_on_threads, thread_pki_rsa_import_privkey_base64_passphrase.
Referenced by torture_run_tests.
static void torture_mixed(void **state)
References NUM_TESTS, NUM_THREADS, rc, thread_pki_rsa_copy_cert_to_privkey, thread_pki_rsa_duplicate_key, thread_pki_rsa_generate_key, thread_pki_rsa_import_cert_file, thread_pki_rsa_import_privkey_base64, thread_pki_rsa_import_privkey_base64_NULL_key, thread_pki_rsa_import_privkey_base64_NULL_str, thread_pki_rsa_import_privkey_base64_passphrase, thread_pki_rsa_import_pubkey_file, thread_pki_rsa_publickey_base64, thread_pki_rsa_publickey_from_privatekey.
Referenced by torture_run_tests.
int torture_run_tests(void)
References disable_secmem, enable_secmem, rc, setup_rsa_key, ssh_finalize, ssh_init, teardown, torture_filter_tests, torture_mixed, torture_pki_rsa_copy_cert_to_privkey, torture_pki_rsa_duplicate_key, torture_pki_rsa_generate_key, torture_pki_rsa_import_cert_file, torture_pki_rsa_import_privkey_base64, torture_pki_rsa_import_privkey_base64_NULL_key, torture_pki_rsa_import_privkey_base64_NULL_str, torture_pki_rsa_import_privkey_base64_passphrase, torture_pki_rsa_import_pubkey_file, torture_pki_rsa_publickey_base64, torture_pki_rsa_publickey_from_privatekey.