torture.h
_GNU_SOURCE
assert_return_code
TORTURE_SSH_SERVER
TORTURE_SSH_USER_BOB
TORTURE_SSH_USER_BOB_PASSWORD
TORTURE_SSH_USER_ALICE
TORTURE_SSH_USER_CHARLIE
ZERO_STRUCT
torture_filter_tests
void torture_cmdline_parse(int argc, char **argv, struct argument_s *arguments)
References argp.
Referenced by main.
int torture_rmdirs(const char *path)
References SAFE_FREE.
Referenced by session_teardown, sshbind_teardown, sshd_teardown, teardown, teardown_cert_dir, teardown_directory_structure, teardown_temp_dir, torture_knownhosts_algorithms_negative, torture_knownhosts_new_file, torture_ssh_dir_writeable, torture_ssh_mkdirs, torture_teardown_socket_dir.
int torture_isdir(const char *path)
Referenced by torture_sftp_mkdir.
int torture_terminate_process(const char *pidfile)
References rc, torture_read_pidfile.
Referenced by agent_teardown, stop_server, torture_teardown_sshd_server.
int torture_libssh_verbosity(void)
References verbosity.
Referenced by session_setup, setup, setup_config_files, setup_default_server, setup_kbdint_server, setup_server_state, torture_packet, torture_pki_verify_mismatch.
ssh_session torture_ssh_session(struct torture_state *s, const char *host, const unsigned int *port, const char *user, const char *password)
References _torture_auth_kbdint, host, port, rc, s, session, SSH_AUTH_ERROR, SSH_AUTH_METHOD_INTERACTIVE, SSH_AUTH_METHOD_PASSWORD, SSH_AUTH_SUCCESS, ssh_connect, ssh_disconnect, SSH_ERROR, ssh_free, ssh_is_connected, ssh_new, SSH_OPTIONS_HOST, SSH_OPTIONS_LOG_VERBOSITY, SSH_OPTIONS_PORT, SSH_OPTIONS_PROCESS_CONFIG, ssh_options_set, SSH_OPTIONS_USER, ssh_set_pcap_file, ssh_userauth_list, ssh_userauth_none, ssh_userauth_password, ssh_userauth_publickey_auto, user, verbosity.
Referenced by client_thread, session_setup.
ssh_bind torture_ssh_bind(const char *addr, const unsigned int port, enum ssh_keytypes_e key_type, const char *private_key_file)
Referenced by test_ssh_channel_request_x11.
struct torture_sftp* torture_sftp_session(ssh_session session)
Referenced by session_setup.
void torture_sftp_close(struct torture_sftp *t)
Referenced by session_teardown.
void torture_write_file(const char *filename, const char *data)
References rc.
Referenced by setup, setup_both_keys_passphrase, setup_config_files, setup_default_server, setup_dsa_key, setup_ecdsa_key, setup_ed25519_key, setup_files, setup_kbdint_server, setup_openssh_dsa_key, setup_openssh_ecdsa_key, setup_openssh_rsa_key, setup_rsa_key, setup_tokens, setup_tokens_ecdsa, start_server, torture_config_match, torture_config_proxyjump, torture_knownhosts_algorithms_negative, torture_pki_verify_mismatch, torture_setup_create_sshd_config, try_config_content.
void _torture_filter_tests(struct CMUnitTest *tests, size_t ntests)
const char* torture_server_address(int domain)
References TORTURE_SSHD_SRV_IPV4, TORTURE_SSHD_SRV_IPV6.
Referenced by torture_options_set_proxycommand_ssh, torture_options_set_proxycommand_ssh_stderr.
int torture_server_port(void)
References port, TORTURE_SSHD_SRV_PORT.
void torture_setup_socket_dir(void **state)
References rc, s, SSH_OK, ssh_pcap_file_new, ssh_pcap_file_open, torture_make_temp_dir, TORTURE_PCAP_FILE, TORTURE_SOCKET_DIR, TORTURE_SSHD_CONFIG, TORTURE_SSHD_PIDFILE.
Referenced by setup_default_server, setup_files, setup_kbdint_server, torture_setup_sshd_server.
void torture_setup_sshd_server(void **state, bool pam)
References assert_return_code, rc, s, torture_setup_create_sshd_config, torture_setup_socket_dir, torture_wait_for_daemon.
Referenced by sshd_group_setup, sshd_setup.
void torture_setup_tokens(const char *temp_dir, const char *filename, const char object_name[])
References assert_return_code, rc.
Referenced by setup_tokens, setup_tokens_ecdsa.
void torture_teardown_socket_dir(void **state)
References rc, s, ssh_pcap_file_free, torture_rmdirs.
Referenced by teardown_files, torture_teardown_sshd_server.
void torture_teardown_sshd_server(void **state)
References rc, s, torture_teardown_socket_dir, torture_terminate_process.
Referenced by sshd_group_teardown, sshd_teardown, teardown_default_server, teardown_kbdint_server.
int torture_update_sshd_config(void **state, const char *config)
References rc, s, SAFE_FREE, SSH_OK, torture_reload_sshd_server, torture_setup_create_sshd_config.
Referenced by torture_rekey_server_send.
void torture_reset_config(ssh_session session)
References ssh_session_struct::options_seen, ssh_session_struct::opts, session.
Referenced by torture_config_auth_methods, torture_config_match, torture_config_proxyjump, torture_config_rekey, torture_options_config_host, torture_options_config_match, torture_options_config_match_multi.
int torture_run_tests(void)
References agent_cert_setup, agent_setup, agent_teardown, disable_secmem, enable_secmem, pubkey_setup, rc, session, session_setup, session_teardown, setup, setup_both_keys, setup_both_keys_passphrase, setup_cert_dir, setup_config_files, setup_default_server, setup_directory_structure, setup_dsa_key, setup_ecdsa_key_256, setup_ecdsa_key_384, setup_ecdsa_key_521, setup_ed25519_key, setup_files, setup_kbdint_server, setup_knownhosts_file, setup_knownhosts_file_duplicate, setup_openssh_dsa_key, setup_openssh_ecdsa_key_256, setup_openssh_ecdsa_key_384, setup_openssh_ecdsa_key_521, setup_openssh_rsa_key, setup_rsa_key, setup_temp_dir, ssh_finalize, ssh_init, SSH_LOG_FUNCTIONS, ssh_new, SSH_OPTIONS_LOG_VERBOSITY, ssh_options_set, sshbind_setup, sshbind_teardown, sshd_group_setup, sshd_group_teardown, sshd_setup, sshd_teardown, teardown, teardown_cert_dir, teardown_default_server, teardown_directory_structure, teardown_files, teardown_kbdint_server, teardown_knownhosts_file, teardown_temp_dir, test_ssh_channel_request_x11, torture_algorithms_3des_cbc_hmac_sha1, torture_algorithms_3des_cbc_hmac_sha1_etm, torture_algorithms_3des_cbc_hmac_sha2_256, torture_algorithms_3des_cbc_hmac_sha2_256_etm, torture_algorithms_3des_cbc_hmac_sha2_512, torture_algorithms_3des_cbc_hmac_sha2_512_etm, torture_algorithms_aes128_cbc_hmac_sha1, torture_algorithms_aes128_cbc_hmac_sha1_etm, torture_algorithms_aes128_cbc_hmac_sha2_256, torture_algorithms_aes128_cbc_hmac_sha2_256_etm, torture_algorithms_aes128_cbc_hmac_sha2_512, torture_algorithms_aes128_cbc_hmac_sha2_512_etm, torture_algorithms_aes128_ctr_hmac_sha1, torture_algorithms_aes128_ctr_hmac_sha1_etm, torture_algorithms_aes128_ctr_hmac_sha2_256, torture_algorithms_aes128_ctr_hmac_sha2_256_etm, torture_algorithms_aes128_ctr_hmac_sha2_512, torture_algorithms_aes128_ctr_hmac_sha2_512_etm, torture_algorithms_aes128_gcm, torture_algorithms_aes192_cbc_hmac_sha1, torture_algorithms_aes192_cbc_hmac_sha1_etm, torture_algorithms_aes192_cbc_hmac_sha2_256, torture_algorithms_aes192_cbc_hmac_sha2_256_etm, torture_algorithms_aes192_cbc_hmac_sha2_512, torture_algorithms_aes192_cbc_hmac_sha2_512_etm, torture_algorithms_aes192_ctr_hmac_sha1, torture_algorithms_aes192_ctr_hmac_sha1_etm, torture_algorithms_aes192_ctr_hmac_sha2_256, torture_algorithms_aes192_ctr_hmac_sha2_256_etm, torture_algorithms_aes192_ctr_hmac_sha2_512, torture_algorithms_aes192_ctr_hmac_sha2_512_etm, torture_algorithms_aes256_cbc_hmac_sha1, torture_algorithms_aes256_cbc_hmac_sha1_etm, torture_algorithms_aes256_cbc_hmac_sha2_256, torture_algorithms_aes256_cbc_hmac_sha2_256_etm, torture_algorithms_aes256_cbc_hmac_sha2_512, torture_algorithms_aes256_cbc_hmac_sha2_512_etm, torture_algorithms_aes256_ctr_hmac_sha1, torture_algorithms_aes256_ctr_hmac_sha1_etm, torture_algorithms_aes256_ctr_hmac_sha2_256, torture_algorithms_aes256_ctr_hmac_sha2_256_etm, torture_algorithms_aes256_ctr_hmac_sha2_512, torture_algorithms_aes256_ctr_hmac_sha2_512_etm, torture_algorithms_aes256_gcm, torture_algorithms_dh_group1, torture_algorithms_dh_group14, torture_algorithms_dh_group16, torture_algorithms_dh_group18, torture_algorithms_zlib, torture_algorithms_zlib_openssh, torture_append_without_duplicate, torture_auth_agent, torture_auth_agent_cert, torture_auth_agent_cert_nonblocking, torture_auth_agent_nonblocking, torture_auth_autopubkey, torture_auth_autopubkey_ecdsa_key_256, torture_auth_autopubkey_ecdsa_key_384, torture_auth_autopubkey_ecdsa_key_521, torture_auth_autopubkey_nonblocking, torture_auth_autopubkey_rsa, torture_auth_cert, torture_auth_kbdint, torture_auth_kbdint_nonblocking, torture_auth_none, torture_auth_none_nonblocking, torture_auth_password, torture_auth_password_nonblocking, torture_auth_pubkey_types, torture_auth_pubkey_types_ecdsa, torture_auth_pubkey_types_ecdsa_nonblocking, torture_auth_pubkey_types_ed25519, torture_auth_pubkey_types_ed25519_nonblocking, torture_auth_pubkey_types_nonblocking, torture_back_and_forth, torture_basename, torture_bind_config_ciphers, torture_bind_config_corner_cases, torture_bind_config_full, torture_bind_config_hostkey, torture_bind_config_hostkey_algorithms, torture_bind_config_hostkey_separately, torture_bind_config_hostkey_twice_rec, torture_bind_config_include, torture_bind_config_include_recursive, torture_bind_config_kexalgorithms, torture_bind_config_listen_address, torture_bind_config_loglevel, torture_bind_config_macs, torture_bind_config_match_all, torture_bind_config_match_corner_cases, torture_bind_config_match_invalid, torture_bind_config_match_not_allowed, torture_bind_config_match_twice, torture_bind_config_match_unsupported, torture_bind_config_port, torture_bind_config_pubkey_accepted, torture_buffer_pack_badformat, torture_buffer_prepend, torture_callbacks_execute_list, torture_callbacks_exists, torture_callbacks_iterate, torture_callbacks_size, torture_channel_read_error, torture_channel_select, torture_client_config_autoparse, torture_client_config_emulate, torture_client_config_suppress, torture_client_config_system, torture_config_auth_methods, torture_config_double_ports, torture_config_from_file, torture_config_glob, torture_config_match, torture_config_match_pattern, torture_config_new, torture_config_parser_get_cmd, torture_config_parser_get_token, torture_config_proxyjump, torture_config_pubkeyacceptedkeytypes, torture_config_rekey, torture_config_unknown, torture_connect_double, torture_connect_failure, torture_connect_nonblocking, torture_connect_socket, torture_create_temp_dir, torture_crypto_aes256_cbc, torture_crypto_chacha20poly1305, torture_crypto_chacha20poly1305_bad_data, torture_crypto_chacha20poly1305_bad_packet_length, torture_crypto_chacha20poly1305_bad_tag, torture_dhgroup_better_size, torture_dirname, torture_ecdsa_sign_verify_uri_256, torture_ecdsa_sign_verify_uri_384, torture_ecdsa_sign_verify_uri_521, torture_filter_tests, torture_find_all_matching, torture_find_matching, torture_get_user_home_dir, torture_growing_buffer, torture_growing_buffer_shifting, torture_hostkey_ed25519, torture_hostkey_rsa, torture_hostkey_rsa_sha256, torture_hostkey_rsa_sha512, torture_knownhosts_algorithms, torture_knownhosts_algorithms_global, torture_knownhosts_algorithms_negative, torture_knownhosts_algorithms_wanted, torture_knownhosts_conflict, torture_knownhosts_duplicate, torture_knownhosts_export, torture_knownhosts_fail, torture_knownhosts_get_algorithms_names, torture_knownhosts_host_exists, torture_knownhosts_host_exists_global, torture_knownhosts_new_file, torture_knownhosts_no_hostkeychecking, torture_knownhosts_other, torture_knownhosts_other_auto, torture_knownhosts_parse_line_default_ed25519, torture_knownhosts_parse_line_ecdsa, torture_knownhosts_parse_line_hashed_ed25519, torture_knownhosts_parse_line_pattern_ed25519, torture_knownhosts_parse_line_port_ed25519, torture_knownhosts_parse_line_port_wildcard, torture_knownhosts_parse_line_rsa, torture_knownhosts_parse_line_standard_port, torture_knownhosts_port, torture_knownhosts_precheck, torture_knownhosts_read_file, torture_knownhosts_standard_port, torture_knownhosts_unknown, torture_knownhosts_wildcard, torture_knownhosts_write_and_verify, torture_log_callback, torture_md5_hash, torture_mixed, torture_ntohll, torture_options_config_host, torture_options_config_match, torture_options_config_match_multi, torture_options_copy, torture_options_get_global_knownhosts, torture_options_get_host, torture_options_get_identity, torture_options_get_knownhosts, torture_options_get_port, torture_options_get_user, torture_options_proxycommand, torture_options_set_ciphers, torture_options_set_fd, torture_options_set_global_knownhosts, torture_options_set_host, torture_options_set_hostkey, torture_options_set_identity, torture_options_set_key_exchange, torture_options_set_knownhosts, torture_options_set_macs, torture_options_set_port, torture_options_set_proxycommand, torture_options_set_proxycommand_notexist, torture_options_set_proxycommand_ssh, torture_options_set_proxycommand_ssh_stderr, torture_options_set_pubkey_accepted_types, torture_options_set_user, torture_packet_3des_cbc, torture_packet_3des_cbc_etm, torture_packet_aes128_cbc, torture_packet_aes128_cbc_etm, torture_packet_aes128_ctr, torture_packet_aes128_ctr_etm, torture_packet_aes128_gcm, torture_packet_aes192_cbc, torture_packet_aes192_cbc_etm, torture_packet_aes192_ctr, torture_packet_aes192_ctr_etm, torture_packet_aes256_cbc, torture_packet_aes256_cbc_etm, torture_packet_aes256_ctr, torture_packet_aes256_ctr_etm, torture_packet_aes256_gcm, torture_packet_chacha20, torture_packet_compress_zlib, torture_packet_compress_zlib_openssh, torture_packet_filter_check_auth_success, torture_packet_filter_check_channel_open, torture_packet_filter_check_msg_ext_info, torture_packet_filter_check_unfiltered, torture_path_expand_escape, torture_path_expand_known_hosts, torture_path_expand_percent, torture_path_expand_tilde_unix, torture_pki_dsa_cert_verify, torture_pki_dsa_duplicate_key, torture_pki_dsa_generate_key, torture_pki_dsa_generate_pubkey_from_privkey, torture_pki_dsa_import_cert_file, torture_pki_dsa_import_openssh_privkey_base64_passphrase, torture_pki_dsa_import_privkey_base64, torture_pki_dsa_import_privkey_base64_comment, torture_pki_dsa_import_privkey_base64_passphrase, torture_pki_dsa_import_privkey_base64_whitespace, torture_pki_dsa_import_pubkey_file, torture_pki_dsa_import_pubkey_from_openssh_privkey, torture_pki_dsa_publickey_base64, torture_pki_dsa_publickey_from_privatekey, torture_pki_dsa_skip, torture_pki_ecdsa_cert_verify, torture_pki_ecdsa_duplicate_key, torture_pki_ecdsa_duplicate_key_uri_256, torture_pki_ecdsa_duplicate_key_uri_384, torture_pki_ecdsa_duplicate_key_uri_521, torture_pki_ecdsa_duplicate_then_demote, torture_pki_ecdsa_duplicate_then_demote_uri_256, torture_pki_ecdsa_duplicate_then_demote_uri_384, torture_pki_ecdsa_duplicate_then_demote_uri_521, torture_pki_ecdsa_generate_pubkey_from_privkey, torture_pki_ecdsa_import_cert_file, torture_pki_ecdsa_import_privkey_base64, torture_pki_ecdsa_import_privkey_base64_comment, torture_pki_ecdsa_import_privkey_base64_whitespace, torture_pki_ecdsa_import_pubkey_file, torture_pki_ecdsa_import_pubkey_from_openssh_privkey, torture_pki_ecdsa_import_pubkey_uri_256, torture_pki_ecdsa_import_pubkey_uri_384, torture_pki_ecdsa_import_pubkey_uri_521, torture_pki_ecdsa_import_pubkey_uri_invalid_configurations, torture_pki_ecdsa_name256, torture_pki_ecdsa_name384, torture_pki_ecdsa_name521, torture_pki_ecdsa_publickey_base64, torture_pki_ecdsa_publickey_from_privatekey, torture_pki_ecdsa_publickey_from_privatekey_uri_256, torture_pki_ecdsa_publickey_from_privatekey_uri_384, torture_pki_ecdsa_publickey_from_privatekey_uri_521, torture_pki_ed25519_cert_verify, torture_pki_ed25519_generate_key, torture_pki_ed25519_generate_pubkey_from_privkey, torture_pki_ed25519_import_cert_file, torture_pki_ed25519_import_export_privkey_base64, torture_pki_ed25519_import_privkey_base64, torture_pki_ed25519_import_privkey_base64_comment, torture_pki_ed25519_import_privkey_base64_passphrase, torture_pki_ed25519_import_privkey_base64_whitespace, torture_pki_ed25519_import_pubkey_file, torture_pki_ed25519_import_pubkey_from_openssh_privkey, torture_pki_ed25519_privkey_dup, torture_pki_ed25519_pubkey_dup, torture_pki_ed25519_publickey_base64, torture_pki_ed25519_publickey_from_privatekey, torture_pki_ed25519_sign, torture_pki_ed25519_sign_openssh_privkey_passphrase, torture_pki_ed25519_verify, torture_pki_ed25519_verify_bad, torture_pki_ed25519_write_privkey, torture_pki_fail_sign_with_incompatible_hash, torture_pki_generate_key_ecdsa, torture_pki_keytype, torture_pki_rsa_copy_cert_to_privkey, torture_pki_rsa_duplicate_key, torture_pki_rsa_generate_key, torture_pki_rsa_generate_pubkey_from_privkey, torture_pki_rsa_import_cert_file, torture_pki_rsa_import_openssh_privkey_base64_passphrase, torture_pki_rsa_import_privkey_base64, torture_pki_rsa_import_privkey_base64_comment, torture_pki_rsa_import_privkey_base64_NULL_key, torture_pki_rsa_import_privkey_base64_NULL_str, torture_pki_rsa_import_privkey_base64_passphrase, torture_pki_rsa_import_privkey_base64_whitespace, torture_pki_rsa_import_privkey_uri, torture_pki_rsa_import_pubkey_file, torture_pki_rsa_import_pubkey_from_openssh_privkey, torture_pki_rsa_import_pubkey_uri, torture_pki_rsa_publickey_base64, torture_pki_rsa_publickey_from_privatekey, torture_pki_rsa_publickey_from_privatekey_uri, torture_pki_rsa_sha2, torture_pki_rsa_uri_invalid_configurations, torture_pki_sign_data_dsa, torture_pki_sign_data_ecdsa, torture_pki_sign_data_rsa, torture_pki_sign_verify_uri, torture_pki_signature, torture_pki_verify_mismatch, torture_privatekey_from_file, torture_privatekey_from_file_passphrase, torture_pubkey_from_file, torture_pubkey_generate_from_privkey, torture_pull_be_u16, torture_pull_be_u32, torture_pull_be_u8, torture_pull_le_u16, torture_pull_le_u32, torture_pull_le_u8, torture_push_be_u16, torture_push_be_u32, torture_push_be_u64, torture_push_be_u8, torture_push_le_u16, torture_push_le_u32, torture_push_le_u64, torture_push_le_u8, torture_rand_threading, torture_rekey_default, torture_rekey_send, torture_rekey_server_send, torture_rekey_time, torture_remove_duplicate, torture_request_env, torture_retrieve_dhgroup_file, torture_scp_download, torture_scp_download_recursive, torture_scp_upload, torture_scp_upload_newline, torture_scp_upload_recursive, torture_server_auth_kbdint, torture_server_auth_none, torture_server_auth_password, torture_server_auth_pubkey, torture_server_config_ciphers, torture_server_config_hostkey, torture_server_config_hostkey_algorithms, torture_server_config_kex, torture_server_config_macs, torture_server_config_unknown, torture_server_hostkey_mismatch, torture_server_unknown_global_request, torture_session_keys, torture_sftp_benchmark_write_read, torture_sftp_canonicalize_path, torture_sftp_ext_new, torture_sftp_fsync, torture_sftp_mkdir, torture_sftp_read_blocking, torture_sha1_hash, torture_sha256_fingerprint, torture_sha256_hash, torture_ssh_analyze_banner, torture_ssh_buffer_add_format, torture_ssh_buffer_get_format, torture_ssh_buffer_get_format_error, torture_ssh_buffer_get_ssh_string, torture_ssh_dir_writeable, torture_ssh_forward, torture_ssh_init, torture_ssh_init_after_finalize, torture_ssh_is_ipaddr, torture_ssh_list_append, torture_ssh_list_new, torture_ssh_list_prepend, torture_ssh_mkdirs, torture_ssh_newline_vis, torture_ssh_quote_file_name, torture_ssh_strreplace, torture_temp_file, torture_timeout_elapsed, torture_timeout_update, torture_tokens_sanity, torture_unknown_request, verbosity.
Referenced by main.
char* torture_make_temp_dir(const char *template)
References SAFE_FREE.
Referenced by session_setup, setup, setup_cert_dir, setup_config_files, setup_directory_structure, setup_dsa_key, setup_ecdsa_key, setup_ed25519_key, setup_openssh_dsa_key, setup_openssh_ecdsa_key, setup_openssh_rsa_key, setup_rsa_key, setup_session, setup_temp_dir, torture_knownhosts_algorithms_negative, torture_knownhosts_new_file, torture_setup_socket_dir, torture_ssh_dir_writeable, torture_ssh_mkdirs.
char* torture_create_temp_file(const char *template)
References SAFE_FREE.
Referenced by setup, setup_knownhosts_file, setup_knownhosts_file_duplicate, torture_knownhosts_conflict, torture_knownhosts_duplicate, torture_knownhosts_fail, torture_knownhosts_no_hostkeychecking, torture_knownhosts_other, torture_knownhosts_other_auto, torture_knownhosts_port, torture_knownhosts_precheck, torture_knownhosts_standard_port, torture_knownhosts_unknown, torture_knownhosts_wildcard.
char* torture_get_current_working_dir(void)
References SAFE_FREE.
Referenced by session_setup, setup_cert_dir, setup_config_files, setup_directory_structure, setup_dsa_key, setup_ecdsa_key, setup_ed25519_key, setup_openssh_dsa_key, setup_openssh_ecdsa_key, setup_openssh_rsa_key, setup_rsa_key, setup_session, setup_temp_dir, torture_back_and_forth, torture_knownhosts_algorithms_negative, torture_ssh_mkdirs.
int torture_change_dir(char *path)
References rc.
Referenced by session_teardown, setup_cert_dir, setup_config_files, setup_directory_structure, setup_dsa_key, setup_ecdsa_key, setup_ed25519_key, setup_openssh_dsa_key, setup_openssh_ecdsa_key, setup_openssh_rsa_key, setup_rsa_key, setup_session, sshbind_teardown, sshd_teardown, teardown, teardown_cert_dir, teardown_directory_structure, teardown_temp_dir, torture_back_and_forth, torture_knownhosts_algorithms_negative, torture_ssh_mkdirs.