torture_pki_ecdsa.c
LIBSSH_STATIC
LIBSSH_ECDSA_TESTKEY
LIBSSH_ECDSA_TESTKEY_PASSPHRASE
const char template[][]
const unsigned char INPUT[][]
Referenced by torture_pki_ecdsa_cert_verify, torture_pki_fail_sign_with_incompatible_hash, torture_pki_generate_key_ecdsa, torture_pki_sign_data_ecdsa.
static int setup_ecdsa_key(void **state, int ecdsa_bits)
References pki_st::cwd, LIBSSH_ECDSA_TESTKEY, LIBSSH_ECDSA_TESTKEY_PASSPHRASE, rc, SSH_KEYTYPE_ECDSA_P256, SSH_KEYTYPE_ECDSA_P384, SSH_KEYTYPE_ECDSA_P521, pki_st::temp_dir, torture_change_dir, torture_get_current_working_dir, torture_get_testkey, torture_get_testkey_pub, torture_make_temp_dir, torture_write_file, pki_st::type.
Referenced by setup_ecdsa_key_256, setup_ecdsa_key_384, setup_ecdsa_key_521.
static int setup_openssh_ecdsa_key(void **state, int ecdsa_bits)
References pki_st::cwd, LIBSSH_ECDSA_TESTKEY, LIBSSH_ECDSA_TESTKEY_PASSPHRASE, rc, SSH_KEYTYPE_ECDSA_P256, SSH_KEYTYPE_ECDSA_P384, SSH_KEYTYPE_ECDSA_P521, pki_st::temp_dir, torture_change_dir, torture_get_current_working_dir, torture_get_openssh_testkey, torture_get_testkey_pub, torture_make_temp_dir, torture_write_file, pki_st::type.
Referenced by setup_openssh_ecdsa_key_256, setup_openssh_ecdsa_key_384, setup_openssh_ecdsa_key_521.
static int setup_ecdsa_key_521(void **state)
References setup_ecdsa_key.
Referenced by torture_run_tests.
static int setup_ecdsa_key_384(void **state)
References setup_ecdsa_key.
Referenced by torture_run_tests.
static int setup_ecdsa_key_256(void **state)
References setup_ecdsa_key.
Referenced by torture_run_tests.
static int setup_openssh_ecdsa_key_521(void **state)
References setup_openssh_ecdsa_key.
Referenced by torture_run_tests.
static int setup_openssh_ecdsa_key_384(void **state)
References setup_openssh_ecdsa_key.
Referenced by torture_run_tests.
static int setup_openssh_ecdsa_key_256(void **state)
References setup_openssh_ecdsa_key.
Referenced by torture_run_tests.
static int teardown(void **state)
References pki_st::cwd, rc, SAFE_FREE, pki_st::temp_dir, torture_change_dir, torture_rmdirs.
Referenced by torture_run_tests.
static void torture_pki_ecdsa_import_pubkey_file(void **state)
References assert_return_code, LIBSSH_ECDSA_TESTKEY, pubkey, rc, SSH_KEY_FREE, ssh_pki_import_pubkey_file.
Referenced by torture_run_tests.
static void torture_pki_ecdsa_import_pubkey_from_openssh_privkey(void **state)
References assert_return_code, LIBSSH_ECDSA_TESTKEY_PASSPHRASE, pubkey, rc, SSH_KEY_FREE, ssh_pki_import_pubkey_file.
Referenced by torture_run_tests.
static void torture_pki_ecdsa_import_privkey_base64(void **state)
References key, LIBSSH_ECDSA_TESTKEY, rc, SSH_KEY_FREE, ssh_key_is_private, ssh_pki_import_privkey_base64, torture_get_testkey_passphrase, torture_pki_read_file.
Referenced by torture_run_tests.
static void torture_pki_ecdsa_import_privkey_base64_comment(void **state)
References key, LIBSSH_ECDSA_TESTKEY, rc, SSH_KEY_FREE, ssh_key_is_private, ssh_pki_import_privkey_base64, torture_get_testkey_passphrase, torture_pki_read_file.
Referenced by torture_run_tests.
static void torture_pki_ecdsa_import_privkey_base64_whitespace(void **state)
References key, LIBSSH_ECDSA_TESTKEY, rc, SSH_KEY_FREE, ssh_key_is_private, ssh_pki_import_privkey_base64, torture_get_testkey_passphrase, torture_pki_read_file.
Referenced by torture_run_tests.
static void torture_pki_ecdsa_publickey_from_privatekey(void **state)
References key, LIBSSH_ECDSA_TESTKEY, pubkey, rc, SSH_KEY_FREE, SSH_OK, ssh_pki_export_privkey_to_pubkey, ssh_pki_import_privkey_base64, torture_pki_read_file.
Referenced by torture_run_tests.
static void torture_pki_ecdsa_import_cert_file(void **state)
References LIBSSH_ECDSA_TESTKEY, rc, SSH_KEY_FREE, ssh_key_is_public, ssh_key_type, ssh_pki_import_cert_file, pki_st::type.
Referenced by torture_run_tests.
static void torture_pki_ecdsa_publickey_base64(void **state)
References key, LIBSSH_ECDSA_TESTKEY, rc, SSH_KEY_FREE, ssh_key_type_from_name, ssh_pki_export_pubkey_base64, ssh_pki_import_pubkey_base64, torture_pki_read_file, pki_st::type.
Referenced by torture_run_tests.
static void torture_pki_ecdsa_generate_pubkey_from_privkey(void **state)
References LIBSSH_ECDSA_TESTKEY, privkey, pubkey, rc, SSH_KEY_FREE, SSH_OK, ssh_pki_export_privkey_to_pubkey, ssh_pki_export_pubkey_file, ssh_pki_import_privkey_file, torture_pubkey_len, torture_read_one_line.
Referenced by torture_run_tests.
static void torture_pki_ecdsa_duplicate_key(void **state)
References LIBSSH_ECDSA_TESTKEY, privkey, pubkey, rc, ssh_key_cmp, SSH_KEY_CMP_PRIVATE, SSH_KEY_CMP_PUBLIC, ssh_key_dup, SSH_KEY_FREE, SSH_OK, ssh_pki_export_privkey_to_pubkey, ssh_pki_export_pubkey_base64, ssh_pki_import_privkey_file, ssh_pki_import_pubkey_file, SSH_STRING_FREE_CHAR.
Referenced by torture_run_tests.
static void torture_pki_ecdsa_duplicate_then_demote(void **state)
References ssh_key_struct::ecdsa_nid, LIBSSH_ECDSA_TESTKEY, privkey, pubkey, rc, ssh_key_dup, SSH_KEY_FREE, ssh_pki_export_privkey_to_pubkey, ssh_pki_import_privkey_file.
Referenced by torture_run_tests.
static void torture_pki_generate_key_ecdsa(void **state)
References INPUT, key, pki_do_sign, pubkey, rc, session, SSH_DIGEST_SHA256, SSH_DIGEST_SHA384, SSH_DIGEST_SHA512, ssh_free, SSH_KEY_FREE, ssh_key_type, ssh_key_type_to_char, SSH_KEYTYPE_ECDSA, SSH_KEYTYPE_ECDSA_P256, SSH_KEYTYPE_ECDSA_P384, SSH_KEYTYPE_ECDSA_P521, SSH_KEYTYPE_UNKNOWN, ssh_new, SSH_OK, ssh_pki_export_privkey_to_pubkey, ssh_pki_generate, ssh_pki_key_ecdsa_name, ssh_pki_signature_verify, ssh_signature_free.
Referenced by torture_run_tests.
static void torture_pki_ecdsa_cert_verify(void **state)
References INPUT, LIBSSH_ECDSA_TESTKEY, pki_do_sign, privkey, rc, session, ssh_free, SSH_KEY_FREE, ssh_key_type_to_hash, ssh_new, SSH_OK, ssh_pki_import_cert_file, ssh_pki_import_privkey_file, ssh_pki_signature_verify, ssh_signature_free.
Referenced by torture_run_tests.
static int test_sign_verify_data(ssh_key key, enum ssh_digest_e hash_type, const unsigned char *input, size_t input_len)
References key, pki_sign_data, pki_verify_data_signature, pubkey, rc, SSH_KEY_FREE, SSH_OK, ssh_pki_export_privkey_to_pubkey, ssh_signature_free.
Referenced by torture_pki_sign_data_ecdsa.
static void torture_pki_sign_data_ecdsa(void **state)
References INPUT, key, rc, SSH_DIGEST_SHA256, SSH_KEY_FREE, SSH_KEYTYPE_ECDSA, SSH_OK, ssh_pki_generate, test_sign_verify_data.
Referenced by torture_run_tests.
static void torture_pki_fail_sign_with_incompatible_hash(void **state)
References ssh_signature_struct::hash_type, INPUT, key, pki_sign_data, pki_verify_data_signature, pubkey, rc, SSH_DIGEST_AUTO, SSH_DIGEST_SHA1, SSH_DIGEST_SHA256, SSH_DIGEST_SHA384, SSH_DIGEST_SHA512, SSH_KEY_FREE, SSH_KEYTYPE_ECDSA_P256, SSH_OK, ssh_pki_export_privkey_to_pubkey, ssh_pki_generate, ssh_signature_free.
Referenced by torture_run_tests.
static void torture_pki_ecdsa_name(void **state, const char *expected_name)
References key, LIBSSH_ECDSA_TESTKEY, rc, SSH_KEY_FREE, ssh_pki_import_privkey_file, ssh_pki_key_ecdsa_name.
Referenced by torture_pki_ecdsa_name256, torture_pki_ecdsa_name384, torture_pki_ecdsa_name521.
static void torture_pki_ecdsa_name256(void **state)
References torture_pki_ecdsa_name.
Referenced by torture_run_tests.
static void torture_pki_ecdsa_name384(void **state)
References torture_pki_ecdsa_name.
Referenced by torture_run_tests.
static void torture_pki_ecdsa_name521(void **state)
References torture_pki_ecdsa_name.
Referenced by torture_run_tests.
int torture_run_tests(void)
References rc, setup_ecdsa_key_256, setup_ecdsa_key_384, setup_ecdsa_key_521, setup_openssh_ecdsa_key_256, setup_openssh_ecdsa_key_384, setup_openssh_ecdsa_key_521, ssh_finalize, ssh_init, teardown, torture_filter_tests, torture_pki_ecdsa_cert_verify, torture_pki_ecdsa_duplicate_key, torture_pki_ecdsa_duplicate_then_demote, torture_pki_ecdsa_generate_pubkey_from_privkey, torture_pki_ecdsa_import_cert_file, torture_pki_ecdsa_import_privkey_base64, torture_pki_ecdsa_import_privkey_base64_comment, torture_pki_ecdsa_import_privkey_base64_whitespace, torture_pki_ecdsa_import_pubkey_file, torture_pki_ecdsa_import_pubkey_from_openssh_privkey, torture_pki_ecdsa_name256, torture_pki_ecdsa_name384, torture_pki_ecdsa_name521, torture_pki_ecdsa_publickey_base64, torture_pki_ecdsa_publickey_from_privatekey, torture_pki_fail_sign_with_incompatible_hash, torture_pki_generate_key_ecdsa, torture_pki_sign_data_ecdsa.