torture_temp_file.c
LIBSSH_STATIC
const char template[][]
static int setup(void **state)
References torture_create_temp_file.
Referenced by torture_run_tests.
static int teardown(void **state)
References rc, SAFE_FREE.
Referenced by torture_run_tests.
static void torture_temp_file(void **state)
Referenced by torture_run_tests.
int torture_run_tests(void)
References rc, setup, teardown, torture_filter_tests, torture_temp_file.