torture_sftp_benchmark.c
LIBSSH_STATIC
MAX_XFER_BUF_SIZE
static int sshd_setup(void **state)
References torture_setup_sshd_server.
Referenced by torture_run_tests.
static int sshd_teardown(void **state)
References torture_teardown_sshd_server.
Referenced by torture_run_tests.
static int session_setup(void **state)
References assert_return_code, rc, s, ssh_socket_struct::session, torture_sftp_session, TORTURE_SSH_SERVER, torture_ssh_session, TORTURE_SSH_USER_ALICE.
Referenced by torture_run_tests.
static int session_teardown(void **state)
References s, ssh_socket_struct::session, ssh_disconnect, ssh_free, torture_rmdirs, torture_sftp_close.
Referenced by torture_run_tests.
static void torture_sftp_benchmark_write_read(void **state)
References assert_ssh_return_code, MAX_XFER_BUF_SIZE, rc, s, ssh_socket_struct::session, session, torture_sftp::sftp, sftp_close, sftp_open, sftp_read, sftp_write, torture_sftp::testdir.
Referenced by torture_run_tests.
int torture_run_tests(void)
References rc, session_setup, session_teardown, ssh_finalize, ssh_init, sshd_setup, sshd_teardown, torture_filter_tests, torture_sftp_benchmark_write_read.