torture_bind_config.c
LIBSSH_STATIC
LOGLEVEL
LOGLEVEL2
LOGLEVEL3
LOGLEVEL4
LISTEN_ADDRESS
LISTEN_ADDRESS2
KEXALGORITHMS
KEXALGORITHMS2
CIPHERS
CIPHERS2
HOSTKEYALGORITHMS
HOSTKEYALGORITHMS_UNKNOWN
HOSTKEYALGORITHMS2
PUBKEYACCEPTEDTYPES
PUBKEYACCEPTEDTYPES_UNKNOWN
PUBKEYACCEPTEDTYPES2
MACS
MACS2
LIBSSH_RSA_TESTKEY
LIBSSH_ED25519_TESTKEY
LIBSSH_TEST_BIND_CONFIG_LISTENADDRESS
LIBSSH_TEST_BIND_CONFIG_LISTENADDRESS2
LIBSSH_TEST_BIND_CONFIG_LISTENADDRESS_TWICE
LIBSSH_TEST_BIND_CONFIG_LISTENADDRESS_TWICE_REC
LIBSSH_TEST_BIND_CONFIG_PORT
LIBSSH_TEST_BIND_CONFIG_PORT2
LIBSSH_TEST_BIND_CONFIG_PORT_TWICE
LIBSSH_TEST_BIND_CONFIG_PORT_TWICE_REC
LIBSSH_TEST_BIND_CONFIG_HOSTKEY
LIBSSH_TEST_BIND_CONFIG_HOSTKEY2
LIBSSH_TEST_BIND_CONFIG_HOSTKEY_TWICE
LIBSSH_TEST_BIND_CONFIG_HOSTKEY_TWICE_REC
LIBSSH_TEST_BIND_CONFIG_LOGLEVEL
LIBSSH_TEST_BIND_CONFIG_LOGLEVEL2
LIBSSH_TEST_BIND_CONFIG_LOGLEVEL_TWICE
LIBSSH_TEST_BIND_CONFIG_LOGLEVEL_TWICE_REC
LIBSSH_TEST_BIND_CONFIG_CIPHERS
LIBSSH_TEST_BIND_CONFIG_CIPHERS2
LIBSSH_TEST_BIND_CONFIG_CIPHERS_TWICE
LIBSSH_TEST_BIND_CONFIG_CIPHERS_TWICE_REC
LIBSSH_TEST_BIND_CONFIG_MACS
LIBSSH_TEST_BIND_CONFIG_MACS2
LIBSSH_TEST_BIND_CONFIG_MACS_TWICE
LIBSSH_TEST_BIND_CONFIG_MACS_TWICE_REC
LIBSSH_TEST_BIND_CONFIG_KEXALGORITHMS
LIBSSH_TEST_BIND_CONFIG_KEXALGORITHMS2
LIBSSH_TEST_BIND_CONFIG_KEXALGORITHMS_TWICE
LIBSSH_TEST_BIND_CONFIG_KEXALGORITHMS_TWICE_REC
LIBSSH_TEST_BIND_CONFIG_FULL
LIBSSH_TEST_BIND_CONFIG_INCLUDE
LIBSSH_TEST_BIND_CONFIG_INCLUDE_RECURSIVE
LIBSSH_TEST_BIND_CONFIG_CORNER_CASES
LIBSSH_TEST_BIND_CONFIG_MATCH_ALL
LIBSSH_TEST_BIND_CONFIG_MATCH_TWICE
LIBSSH_TEST_BIND_CONFIG_MATCH_UNSUPPORTED
LIBSSH_TEST_BIND_CONFIG_MATCH_NOT_ALLOWED
LIBSSH_TEST_BIND_CONFIG_MATCH_CORNER_CASES
LIBSSH_TEST_BIND_CONFIG_MATCH_INVALID
LIBSSH_TEST_BIND_CONFIG_MATCH_INVALID2
LIBSSH_TEST_BIND_CONFIG_PUBKEY_ACCEPTED
LIBSSH_TEST_BIND_CONFIG_PUBKEY_ACCEPTED2
LIBSSH_TEST_BIND_CONFIG_PUBKEY_ACCEPTED_TWICE
LIBSSH_TEST_BIND_CONFIG_PUBKEY_ACCEPTED_TWICE_REC
LIBSSH_TEST_BIND_CONFIG_PUBKEY_ACCEPTED_UNKNOWN
LIBSSH_TEST_BIND_CONFIG_HOSTKEY_ALGORITHMS
LIBSSH_TEST_BIND_CONFIG_HOSTKEY_ALGORITHMS2
LIBSSH_TEST_BIND_CONFIG_HOSTKEY_ALGORITHMS_TWICE
LIBSSH_TEST_BIND_CONFIG_HOSTKEY_ALGORITHMS_TWICE_REC
LIBSSH_TEST_BIND_CONFIG_HOSTKEY_ALGORITHMS_UNKNOWN
LIBSSH_THREAD int ssh_log_level
const char template[][]
static int setup_config_files(void **state)
References CIPHERS, CIPHERS2, bind_st::cwd, HOSTKEYALGORITHMS, HOSTKEYALGORITHMS2, HOSTKEYALGORITHMS_UNKNOWN, KEXALGORITHMS, KEXALGORITHMS2, LIBSSH_DSA_TESTKEY, LIBSSH_ECDSA_521_TESTKEY, LIBSSH_ED25519_TESTKEY, LIBSSH_RSA_TESTKEY, LIBSSH_TEST_BIND_CONFIG_CIPHERS, LIBSSH_TEST_BIND_CONFIG_CIPHERS2, LIBSSH_TEST_BIND_CONFIG_CIPHERS_TWICE, LIBSSH_TEST_BIND_CONFIG_CIPHERS_TWICE_REC, LIBSSH_TEST_BIND_CONFIG_CORNER_CASES, LIBSSH_TEST_BIND_CONFIG_FULL, LIBSSH_TEST_BIND_CONFIG_HOSTKEY, LIBSSH_TEST_BIND_CONFIG_HOSTKEY2, LIBSSH_TEST_BIND_CONFIG_HOSTKEY_ALGORITHMS, LIBSSH_TEST_BIND_CONFIG_HOSTKEY_ALGORITHMS2, LIBSSH_TEST_BIND_CONFIG_HOSTKEY_ALGORITHMS_TWICE, LIBSSH_TEST_BIND_CONFIG_HOSTKEY_ALGORITHMS_TWICE_REC, LIBSSH_TEST_BIND_CONFIG_HOSTKEY_ALGORITHMS_UNKNOWN, LIBSSH_TEST_BIND_CONFIG_HOSTKEY_TWICE, LIBSSH_TEST_BIND_CONFIG_HOSTKEY_TWICE_REC, LIBSSH_TEST_BIND_CONFIG_INCLUDE, LIBSSH_TEST_BIND_CONFIG_INCLUDE_RECURSIVE, LIBSSH_TEST_BIND_CONFIG_KEXALGORITHMS, LIBSSH_TEST_BIND_CONFIG_KEXALGORITHMS2, LIBSSH_TEST_BIND_CONFIG_KEXALGORITHMS_TWICE, LIBSSH_TEST_BIND_CONFIG_KEXALGORITHMS_TWICE_REC, LIBSSH_TEST_BIND_CONFIG_LISTENADDRESS, LIBSSH_TEST_BIND_CONFIG_LISTENADDRESS2, LIBSSH_TEST_BIND_CONFIG_LISTENADDRESS_TWICE, LIBSSH_TEST_BIND_CONFIG_LISTENADDRESS_TWICE_REC, LIBSSH_TEST_BIND_CONFIG_LOGLEVEL, LIBSSH_TEST_BIND_CONFIG_LOGLEVEL2, LIBSSH_TEST_BIND_CONFIG_LOGLEVEL_TWICE, LIBSSH_TEST_BIND_CONFIG_LOGLEVEL_TWICE_REC, LIBSSH_TEST_BIND_CONFIG_MACS, LIBSSH_TEST_BIND_CONFIG_MACS2, LIBSSH_TEST_BIND_CONFIG_MACS_TWICE, LIBSSH_TEST_BIND_CONFIG_MACS_TWICE_REC, LIBSSH_TEST_BIND_CONFIG_MATCH_ALL, LIBSSH_TEST_BIND_CONFIG_MATCH_CORNER_CASES, LIBSSH_TEST_BIND_CONFIG_MATCH_INVALID, LIBSSH_TEST_BIND_CONFIG_MATCH_INVALID2, LIBSSH_TEST_BIND_CONFIG_MATCH_NOT_ALLOWED, LIBSSH_TEST_BIND_CONFIG_MATCH_TWICE, LIBSSH_TEST_BIND_CONFIG_MATCH_UNSUPPORTED, LIBSSH_TEST_BIND_CONFIG_PORT, LIBSSH_TEST_BIND_CONFIG_PORT2, LIBSSH_TEST_BIND_CONFIG_PORT_TWICE, LIBSSH_TEST_BIND_CONFIG_PORT_TWICE_REC, LIBSSH_TEST_BIND_CONFIG_PUBKEY_ACCEPTED, LIBSSH_TEST_BIND_CONFIG_PUBKEY_ACCEPTED2, LIBSSH_TEST_BIND_CONFIG_PUBKEY_ACCEPTED_TWICE, LIBSSH_TEST_BIND_CONFIG_PUBKEY_ACCEPTED_TWICE_REC, LIBSSH_TEST_BIND_CONFIG_PUBKEY_ACCEPTED_UNKNOWN, LISTEN_ADDRESS, LISTEN_ADDRESS2, LOGLEVEL, LOGLEVEL2, LOGLEVEL3, LOGLEVEL4, MACS, MACS2, PUBKEYACCEPTEDTYPES, PUBKEYACCEPTEDTYPES2, PUBKEYACCEPTEDTYPES_UNKNOWN, rc, SSH_KEYTYPE_DSS, SSH_KEYTYPE_ECDSA_P521, SSH_KEYTYPE_ED25519, SSH_KEYTYPE_RSA, bind_st::temp_dir, torture_change_dir, torture_get_current_working_dir, torture_get_openssh_testkey, torture_make_temp_dir, torture_write_file.
Referenced by sshbind_setup.
static int sshbind_setup(void **state)
References bind_st::bind, rc, setup_config_files, ssh_bind_new.
Referenced by torture_run_tests.
static int sshbind_teardown(void **state)
References bind_st::bind, bind_st::cwd, rc, SAFE_FREE, ssh_bind_free, bind_st::temp_dir, torture_change_dir, torture_rmdirs.
Referenced by torture_run_tests.
static void torture_bind_config_listen_address(void **state)
References bind_st::bind, ssh_bind_struct::bindaddr, LIBSSH_TEST_BIND_CONFIG_LISTENADDRESS, LIBSSH_TEST_BIND_CONFIG_LISTENADDRESS2, LIBSSH_TEST_BIND_CONFIG_LISTENADDRESS_TWICE, LIBSSH_TEST_BIND_CONFIG_LISTENADDRESS_TWICE_REC, LISTEN_ADDRESS, LISTEN_ADDRESS2, rc, ssh_bind_config_parse_file.
Referenced by torture_run_tests.
static void torture_bind_config_port(void **state)
References bind_st::bind, ssh_bind_struct::bindport, LIBSSH_TEST_BIND_CONFIG_PORT, LIBSSH_TEST_BIND_CONFIG_PORT2, LIBSSH_TEST_BIND_CONFIG_PORT_TWICE, LIBSSH_TEST_BIND_CONFIG_PORT_TWICE_REC, rc, ssh_bind_config_parse_file.
Referenced by torture_run_tests.
static void torture_bind_config_hostkey(void **state)
References bind_st::bind, ssh_bind_struct::ecdsakey, LIBSSH_ECDSA_521_TESTKEY, LIBSSH_RSA_TESTKEY, LIBSSH_TEST_BIND_CONFIG_HOSTKEY, LIBSSH_TEST_BIND_CONFIG_HOSTKEY_TWICE, rc, ssh_bind_struct::rsakey, ssh_bind_config_parse_file.
Referenced by torture_run_tests.
static void torture_bind_config_hostkey_twice_rec(void **state)
References bind_st::bind, ssh_bind_struct::ecdsakey, LIBSSH_ECDSA_521_TESTKEY, LIBSSH_RSA_TESTKEY, LIBSSH_TEST_BIND_CONFIG_HOSTKEY_TWICE_REC, rc, ssh_bind_struct::rsakey, ssh_bind_config_parse_file.
Referenced by torture_run_tests.
static void torture_bind_config_hostkey_separately(void **state)
References bind_st::bind, ssh_bind_struct::ecdsakey, LIBSSH_ECDSA_521_TESTKEY, LIBSSH_RSA_TESTKEY, LIBSSH_TEST_BIND_CONFIG_HOSTKEY, LIBSSH_TEST_BIND_CONFIG_HOSTKEY2, rc, ssh_bind_struct::rsakey, ssh_bind_config_parse_file.
Referenced by torture_run_tests.
static void torture_bind_config_loglevel(void **state)
References bind_st::bind, LIBSSH_TEST_BIND_CONFIG_LOGLEVEL, LIBSSH_TEST_BIND_CONFIG_LOGLEVEL2, LIBSSH_TEST_BIND_CONFIG_LOGLEVEL_TWICE, LIBSSH_TEST_BIND_CONFIG_LOGLEVEL_TWICE_REC, rc, ssh_bind_config_parse_file, ssh_get_log_level, SSH_OK, ssh_set_log_level.
Referenced by torture_run_tests.
static void torture_bind_config_ciphers(void **state)
References bind_st::bind, CIPHERS, CIPHERS2, LIBSSH_TEST_BIND_CONFIG_CIPHERS, LIBSSH_TEST_BIND_CONFIG_CIPHERS2, LIBSSH_TEST_BIND_CONFIG_CIPHERS_TWICE, LIBSSH_TEST_BIND_CONFIG_CIPHERS_TWICE_REC, rc, SAFE_FREE, ssh_bind_config_parse_file, SSH_CRYPT_C_S, SSH_CRYPT_S_C, ssh_keep_fips_algos, ssh_bind_struct::wanted_methods.
Referenced by torture_run_tests.
static void torture_bind_config_macs(void **state)
References bind_st::bind, LIBSSH_TEST_BIND_CONFIG_MACS, LIBSSH_TEST_BIND_CONFIG_MACS2, LIBSSH_TEST_BIND_CONFIG_MACS_TWICE, LIBSSH_TEST_BIND_CONFIG_MACS_TWICE_REC, MACS, MACS2, rc, ssh_bind_config_parse_file, SSH_MAC_C_S, SSH_MAC_S_C, ssh_bind_struct::wanted_methods.
Referenced by torture_run_tests.
static void torture_bind_config_kexalgorithms(void **state)
References bind_st::bind, KEXALGORITHMS, KEXALGORITHMS2, LIBSSH_TEST_BIND_CONFIG_KEXALGORITHMS, LIBSSH_TEST_BIND_CONFIG_KEXALGORITHMS2, LIBSSH_TEST_BIND_CONFIG_KEXALGORITHMS_TWICE, LIBSSH_TEST_BIND_CONFIG_KEXALGORITHMS_TWICE_REC, rc, SAFE_FREE, ssh_bind_config_parse_file, ssh_keep_fips_algos, SSH_KEX, ssh_bind_struct::wanted_methods.
Referenced by torture_run_tests.
static void torture_bind_config_pubkey_accepted(void **state)
References bind_st::bind, LIBSSH_TEST_BIND_CONFIG_PUBKEY_ACCEPTED, LIBSSH_TEST_BIND_CONFIG_PUBKEY_ACCEPTED2, LIBSSH_TEST_BIND_CONFIG_PUBKEY_ACCEPTED_TWICE, LIBSSH_TEST_BIND_CONFIG_PUBKEY_ACCEPTED_TWICE_REC, LIBSSH_TEST_BIND_CONFIG_PUBKEY_ACCEPTED_UNKNOWN, ssh_bind_struct::pubkey_accepted_key_types, PUBKEYACCEPTEDTYPES, PUBKEYACCEPTEDTYPES2, rc, SAFE_FREE, ssh_bind_config_parse_file, SSH_HOSTKEYS, ssh_keep_fips_algos.
Referenced by torture_run_tests.
static void torture_bind_config_hostkey_algorithms(void **state)
References bind_st::bind, HOSTKEYALGORITHMS, HOSTKEYALGORITHMS2, LIBSSH_TEST_BIND_CONFIG_HOSTKEY_ALGORITHMS, LIBSSH_TEST_BIND_CONFIG_HOSTKEY_ALGORITHMS2, LIBSSH_TEST_BIND_CONFIG_HOSTKEY_ALGORITHMS_TWICE, LIBSSH_TEST_BIND_CONFIG_HOSTKEY_ALGORITHMS_TWICE_REC, LIBSSH_TEST_BIND_CONFIG_HOSTKEY_ALGORITHMS_UNKNOWN, rc, SAFE_FREE, ssh_bind_config_parse_file, SSH_HOSTKEYS, ssh_keep_fips_algos, ssh_bind_struct::wanted_methods.
Referenced by torture_run_tests.
static int assert_full_bind_config(void **state)
References bind_st::bind, ssh_bind_struct::bindaddr, ssh_bind_struct::bindport, CIPHERS, ssh_bind_struct::ecdsakey, KEXALGORITHMS, LIBSSH_ECDSA_521_TESTKEY, LISTEN_ADDRESS, MACS, SAFE_FREE, SSH_CRYPT_C_S, SSH_CRYPT_S_C, ssh_get_log_level, ssh_keep_fips_algos, SSH_KEX, SSH_MAC_C_S, SSH_MAC_S_C, ssh_bind_struct::wanted_methods.
Referenced by torture_bind_config_full, torture_bind_config_include, torture_bind_config_include_recursive, torture_bind_config_match_not_allowed, torture_bind_config_match_unsupported.
static void torture_bind_config_full(void **state)
References assert_full_bind_config, bind_st::bind, LIBSSH_TEST_BIND_CONFIG_FULL, rc, ssh_bind_config_parse_file, ssh_get_log_level, SSH_OK, ssh_set_log_level.
Referenced by torture_run_tests.
static void torture_bind_config_include(void **state)
References assert_full_bind_config, bind_st::bind, LIBSSH_TEST_BIND_CONFIG_INCLUDE, rc, ssh_bind_config_parse_file, ssh_get_log_level, SSH_OK, ssh_set_log_level.
Referenced by torture_run_tests.
static void torture_bind_config_include_recursive(void **state)
References assert_full_bind_config, bind_st::bind, LIBSSH_TEST_BIND_CONFIG_INCLUDE_RECURSIVE, rc, ssh_bind_config_parse_file, ssh_get_log_level, SSH_OK, ssh_set_log_level.
Referenced by torture_run_tests.
static void torture_bind_config_corner_cases(void **state)
Verify the configuration parser does not choke on unknown or unsupported configuration options.
References bind_st::bind, CIPHERS2, LIBSSH_TEST_BIND_CONFIG_CORNER_CASES, rc, ssh_bind_config_parse_file, SSH_CRYPT_C_S, SSH_CRYPT_S_C, ssh_bind_struct::wanted_methods.
Referenced by torture_run_tests.
static void torture_bind_config_match_all(void **state)
References bind_st::bind, LIBSSH_TEST_BIND_CONFIG_MATCH_ALL, rc, ssh_bind_config_parse_file, ssh_get_log_level, SSH_OK, ssh_set_log_level.
Referenced by torture_run_tests.
static void torture_bind_config_match_twice(void **state)
References bind_st::bind, LIBSSH_TEST_BIND_CONFIG_MATCH_TWICE, rc, ssh_bind_config_parse_file, ssh_get_log_level, SSH_OK, ssh_set_log_level.
Referenced by torture_run_tests.
static void torture_bind_config_match_unsupported(void **state)
References assert_full_bind_config, bind_st::bind, LIBSSH_TEST_BIND_CONFIG_MATCH_UNSUPPORTED, rc, ssh_bind_config_parse_file, ssh_get_log_level, SSH_OK, ssh_set_log_level.
Referenced by torture_run_tests.
static void torture_bind_config_match_not_allowed(void **state)
References assert_full_bind_config, bind_st::bind, LIBSSH_TEST_BIND_CONFIG_MATCH_NOT_ALLOWED, rc, ssh_bind_config_parse_file, ssh_get_log_level, SSH_OK, ssh_set_log_level.
Referenced by torture_run_tests.
static void torture_bind_config_match_corner_cases(void **state)
References bind_st::bind, LIBSSH_TEST_BIND_CONFIG_MATCH_CORNER_CASES, rc, ssh_bind_config_parse_file, ssh_get_log_level, SSH_OK, ssh_set_log_level.
Referenced by torture_run_tests.
static void torture_bind_config_match_invalid(void **state)
References bind_st::bind, LIBSSH_TEST_BIND_CONFIG_MATCH_INVALID, LIBSSH_TEST_BIND_CONFIG_MATCH_INVALID2, rc, ssh_bind_config_parse_file, ssh_get_log_level, SSH_OK, ssh_set_log_level.
Referenced by torture_run_tests.
int torture_run_tests(void)
References rc, ssh_finalize, ssh_init, sshbind_setup, sshbind_teardown, torture_bind_config_ciphers, torture_bind_config_corner_cases, torture_bind_config_full, torture_bind_config_hostkey, torture_bind_config_hostkey_algorithms, torture_bind_config_hostkey_separately, torture_bind_config_hostkey_twice_rec, torture_bind_config_include, torture_bind_config_include_recursive, torture_bind_config_kexalgorithms, torture_bind_config_listen_address, torture_bind_config_loglevel, torture_bind_config_macs, torture_bind_config_match_all, torture_bind_config_match_corner_cases, torture_bind_config_match_invalid, torture_bind_config_match_not_allowed, torture_bind_config_match_twice, torture_bind_config_match_unsupported, torture_bind_config_port, torture_bind_config_pubkey_accepted, torture_filter_tests.