torture_pki.c
LIBSSH_STATIC
const unsigned char INPUT[][]
Referenced by torture_pki_verify_mismatch.
const char template[][]
struct key_attrs key_attrs_list[][5][][5]
Referenced by torture_pki_verify_mismatch.
static int setup_cert_dir(void **state)
References pki_st::cwd, rc, pki_st::temp_dir, torture_change_dir, torture_get_current_working_dir, torture_make_temp_dir.
Referenced by torture_run_tests.
static int teardown_cert_dir(void **state)
References pki_st::cwd, rc, SAFE_FREE, pki_st::temp_dir, torture_change_dir, torture_rmdirs.
Referenced by torture_run_tests.
static void torture_pki_keytype(void **state)
References ssh_key_type, ssh_key_type_from_name, ssh_key_type_to_char, SSH_KEYTYPE_UNKNOWN.
Referenced by torture_run_tests.
static void torture_pki_signature(void **state)
Referenced by torture_run_tests.
static void torture_pki_verify_mismatch(void **state)
References key_attrs::expect_success, INPUT, is_cert_type, key, key_attrs_list, pki_do_sign, pki_signature_from_blob, pki_signature_to_blob, pubkey, rc, session, key_attrs::sig_type_c, key_attrs::sign, key_attrs::size_arg, SSH_DIGEST_AUTO, SSH_DIGEST_SHA1, SSH_DIGEST_SHA512, ssh_free, SSH_KEY_FREE, ssh_key_type_plain, SSH_KEYTYPE_DSS, SSH_KEYTYPE_ED25519, SSH_KEYTYPE_ED25519_CERT01, SSH_LOG, SSH_LOG_TRACE, ssh_new, SSH_OK, SSH_OPTIONS_LOG_VERBOSITY, ssh_options_set, ssh_pki_export_privkey_to_pubkey, ssh_pki_generate, ssh_pki_import_cert_file, ssh_pki_signature_verify, ssh_signature_free, ssh_string_free, torture_get_testkey_pub, torture_libssh_verbosity, torture_write_file, ssh_signature_struct::type, ssh_signature_struct::type_c, key_attrs::type_c, verbosity, key_attrs::verify.
Referenced by torture_run_tests.
int torture_run_tests(void)
References rc, setup_cert_dir, ssh_finalize, ssh_init, teardown_cert_dir, torture_filter_tests, torture_pki_keytype, torture_pki_signature, torture_pki_verify_mismatch.