winlocks.c
struct ssh_threads_callbacks_struct ssh_threads_winlock
Referenced by ssh_threads_get_default, ssh_threads_get_winlock.
static int ssh_winlock_mutex_init(void **priv)
static int ssh_winlock_mutex_destroy(void **lock)
static int ssh_winlock_mutex_lock(void **lock)
static int ssh_winlock_mutex_unlock(void **lock)
static unsigned long ssh_winlock_thread_id(void)
void ssh_mutex_lock(SSH_MUTEX *mutex)
References rc.
Referenced by _ssh_finalize, libssh_constructor.
void ssh_mutex_unlock(SSH_MUTEX *mutex)
Referenced by _ssh_finalize, libssh_constructor.
struct ssh_threads_callbacks_struct* ssh_threads_get_winlock(void)
References ssh_threads_winlock.
struct ssh_threads_callbacks_struct* ssh_threads_get_default(void)
Returns a pointer to the appropriate callbacks structure for the environment, to be used with ssh_threads_set_callbacks.
A pointer to a ssh_threads_callbacks_struct to be used with ssh_threads_set_callbacks. ssh_threads_set_callbacks
References ssh_threads_noop, ssh_threads_winlock.
Referenced by ssh_threads_init.