wrapper.h
ssh_kdf_digest
ssh_hmac_e
ssh_des_e
ssh_crypto_direction_e
typedef struct ssh_mac_ctx_struct* ssh_mac_ctx
MD5CTX md5_init(void)
Referenced by ssh_get_pubkey_hash, ssh_get_publickey_hash.
void md5_update(MD5CTX c, const void *data, unsigned long len)
Referenced by ssh_get_pubkey_hash, ssh_get_publickey_hash.
void md5_final(unsigned char *md, MD5CTX c)
Referenced by ssh_get_pubkey_hash, ssh_get_publickey_hash.
SHACTX sha1_init(void)
Referenced by ssh_get_publickey_hash, ssh_mac_ctx_init.
void sha1_update(SHACTX c, const void *data, unsigned long len)
Referenced by ssh_get_publickey_hash, ssh_mac_update.
void sha1_final(unsigned char *md, SHACTX c)
Referenced by ssh_get_publickey_hash, ssh_mac_final.
void sha1(const unsigned char *digest, int len, unsigned char *hash)
Referenced by ssh_make_sessionid, torture_sha1_hash.
SHA256CTX sha256_init(void)
Referenced by ssh_get_publickey_hash, ssh_mac_ctx_init, ssh_pki_signature_verify.
void sha256_update(SHA256CTX c, const void *data, unsigned long len)
Referenced by ssh_get_publickey_hash, ssh_mac_update, ssh_pki_signature_verify.
void sha256_final(unsigned char *md, SHA256CTX c)
Referenced by ssh_get_publickey_hash, ssh_mac_final, ssh_pki_signature_verify.
void sha256(const unsigned char *digest, int len, unsigned char *hash)
Referenced by ssh_make_sessionid, torture_sha256_fingerprint, torture_sha256_hash.
SHA384CTX sha384_init(void)
Referenced by ssh_mac_ctx_init.
void sha384_update(SHA384CTX c, const void *data, unsigned long len)
Referenced by ssh_mac_update.
void sha384_final(unsigned char *md, SHA384CTX c)
Referenced by ssh_mac_final.
void sha384(const unsigned char *digest, int len, unsigned char *hash)
Referenced by ssh_make_sessionid.
SHA512CTX sha512_init(void)
Referenced by bcrypt_pbkdf, crypto_sign_ed25519, crypto_sign_ed25519_keypair, get_hram, ssh_mac_ctx_init.
void sha512_update(SHA512CTX c, const void *data, unsigned long len)
Referenced by bcrypt_pbkdf, crypto_sign_ed25519, crypto_sign_ed25519_keypair, get_hram, ssh_mac_update.
void sha512_final(unsigned char *md, SHA512CTX c)
Referenced by bcrypt_pbkdf, crypto_sign_ed25519, crypto_sign_ed25519_keypair, get_hram, ssh_mac_final.
void sha512(const unsigned char *digest, int len, unsigned char *hash)
Referenced by ssh_make_sessionid.
void evp(int nid, unsigned char *digest, int len, unsigned char *hash, unsigned int *hlen)
EVPCTX evp_init(int nid)
void evp_update(EVPCTX ctx, const void *data, unsigned long len)
void evp_final(EVPCTX ctx, unsigned char *md, unsigned int *mdlen)
HMACCTX hmac_init(const void *key, int len, enum ssh_hmac_e type)
Referenced by hash_hostname, match_hashed_host, ssh_packet_encrypt, ssh_packet_hmac_verify.
void hmac_update(HMACCTX c, const void *data, unsigned long len)
Referenced by hash_hostname, match_hashed_host, ssh_packet_encrypt, ssh_packet_hmac_verify.
void hmac_final(HMACCTX ctx, unsigned char *hashmacbuf, unsigned int *len)
Referenced by hash_hostname, match_hashed_host, ssh_packet_encrypt, ssh_packet_hmac_verify.
size_t hmac_digest_len(enum ssh_hmac_e type)
References AES_GCM_TAGLEN, MD5_DIGEST_LEN, POLY1305_TAGLEN, SSH_HMAC_AEAD_GCM, SSH_HMAC_AEAD_POLY1305, SSH_HMAC_MD5, SSH_HMAC_SHA1, SSH_HMAC_SHA256, SSH_HMAC_SHA512.
Referenced by packet_send2, ssh_generate_session_keys, ssh_packet_encrypt, ssh_packet_hmac_verify, ssh_packet_socket_callback.
int ssh_kdf(struct ssh_crypto_struct *crypto, unsigned char *key, size_t key_len, int key_type, unsigned char *output, size_t requested_len)
Referenced by ssh_generate_session_keys.
int crypt_set_algorithms_client(ssh_session session)
References crypt_set_algorithms2, session.
Referenced by ssh_packet_set_newkeys, torture_packet.
int crypt_set_algorithms_server(ssh_session session)
Referenced by ssh_server_connection_callback.
struct ssh_crypto_struct* crypto_new(void)
References ZERO_STRUCTP.
Referenced by ssh_disconnect, ssh_new, ssh_packet_set_newkeys, torture_packet.
void crypto_free(struct ssh_crypto_struct *crypto)
References cipher_free, ssh_crypto_struct::client_kex, ssh_crypto_struct::compress_in_ctx, ssh_crypto_struct::compress_out_ctx, ssh_crypto_struct::decryptIV, ssh_crypto_struct::decryptkey, ssh_crypto_struct::decryptMAC, ssh_crypto_struct::digest_len, ssh_crypto_struct::encryptIV, ssh_crypto_struct::encryptkey, ssh_crypto_struct::encryptMAC, explicit_bzero, ssh_crypto_struct::in_cipher, ssh_crypto_struct::kex_methods, ssh_cipher_struct::keysize, ssh_kex_struct::methods, ssh_crypto_struct::out_cipher, SAFE_FREE, ssh_crypto_struct::secret_hash, ssh_crypto_struct::server_kex, ssh_crypto_struct::server_pubkey, ssh_crypto_struct::session_id, ssh_crypto_struct::shared_secret, ssh_dh_cleanup, SSH_KEX_METHODS, ssh_key_free.
Referenced by ssh_disconnect, ssh_free, ssh_packet_set_newkeys.
void ssh_reseed(void)
Referenced by ssh_bind_accept_fd.
int ssh_crypto_init(void)
Referenced by libssh_constructor.
void ssh_crypto_finalize(void)
Referenced by _ssh_finalize.
void ssh_cipher_clear(struct ssh_cipher_struct *cipher)
References ssh_cipher_struct::cleanup, ssh_cipher_struct::keylen, SAFE_FREE.
Referenced by cipher_free, pki_private_key_decrypt, pki_private_key_encrypt, thread_crypto_aes256_cbc, torture_crypto_aes256_cbc, torture_crypto_chacha20poly1305, torture_crypto_chacha20poly1305_bad_data, torture_crypto_chacha20poly1305_bad_packet_length, torture_crypto_chacha20poly1305_bad_tag.
struct ssh_hmac_struct* ssh_get_hmactab(void)
References ssh_hmac_tab.
Referenced by crypt_set_algorithms2, ssh_hmac_type_to_string.
struct ssh_cipher_struct* ssh_get_ciphertab(void)
Referenced by cipher_new, crypt_set_algorithms2, get_cipher, pki_private_key_decrypt, pki_private_key_encrypt.
const char* ssh_hmac_type_to_string(enum ssh_hmac_e hmac_type, bool etm)
References ssh_hmac_struct::etm, ssh_hmac_struct::hmac_type, name, ssh_hmac_struct::name, ssh_get_hmactab.
Referenced by ssh_get_hmac_in, ssh_get_hmac_out.