wrapper.c
struct ssh_hmac_struct ssh_hmac_tab[][]
Referenced by ssh_get_hmactab.
struct ssh_hmac_struct* ssh_get_hmactab(void)
References ssh_hmac_tab.
Referenced by crypt_set_algorithms2, ssh_hmac_type_to_string.
size_t hmac_digest_len(enum ssh_hmac_e type)
References AES_GCM_TAGLEN, MD5_DIGEST_LEN, POLY1305_TAGLEN, SSH_HMAC_AEAD_GCM, SSH_HMAC_AEAD_POLY1305, SSH_HMAC_MD5, SSH_HMAC_SHA1, SSH_HMAC_SHA256, SSH_HMAC_SHA512.
Referenced by packet_send2, ssh_generate_session_keys, ssh_packet_encrypt, ssh_packet_hmac_verify, ssh_packet_socket_callback.
const char* ssh_hmac_type_to_string(enum ssh_hmac_e hmac_type, bool etm)
References ssh_hmac_struct::etm, ssh_hmac_struct::hmac_type, name, ssh_hmac_struct::name, ssh_get_hmactab.
Referenced by ssh_get_hmac_in, ssh_get_hmac_out.
static struct ssh_cipher_struct* cipher_new(int offset)
References ssh_get_ciphertab.
Referenced by crypt_set_algorithms2.
void ssh_cipher_clear(struct ssh_cipher_struct *cipher)
References ssh_cipher_struct::cleanup, ssh_cipher_struct::keylen, SAFE_FREE.
Referenced by cipher_free, pki_private_key_decrypt, pki_private_key_encrypt, thread_crypto_aes256_cbc, torture_crypto_aes256_cbc, torture_crypto_chacha20poly1305, torture_crypto_chacha20poly1305_bad_data, torture_crypto_chacha20poly1305_bad_packet_length, torture_crypto_chacha20poly1305_bad_tag.
static void cipher_free(struct ssh_cipher_struct *cipher)
References SAFE_FREE, ssh_cipher_clear.
Referenced by crypto_free.
struct ssh_crypto_struct* crypto_new(void)
References ZERO_STRUCTP.
Referenced by ssh_disconnect, ssh_new, ssh_packet_set_newkeys, torture_packet.
void crypto_free(struct ssh_crypto_struct *crypto)
References cipher_free, ssh_crypto_struct::client_kex, ssh_crypto_struct::compress_in_ctx, ssh_crypto_struct::compress_out_ctx, ssh_crypto_struct::decryptIV, ssh_crypto_struct::decryptkey, ssh_crypto_struct::decryptMAC, ssh_crypto_struct::digest_len, ssh_crypto_struct::encryptIV, ssh_crypto_struct::encryptkey, ssh_crypto_struct::encryptMAC, explicit_bzero, ssh_crypto_struct::in_cipher, ssh_crypto_struct::kex_methods, ssh_cipher_struct::keysize, ssh_kex_struct::methods, ssh_crypto_struct::out_cipher, SAFE_FREE, ssh_crypto_struct::secret_hash, ssh_crypto_struct::server_kex, ssh_crypto_struct::server_pubkey, ssh_crypto_struct::session_id, ssh_crypto_struct::shared_secret, ssh_dh_cleanup, SSH_KEX_METHODS, ssh_key_free.
Referenced by ssh_disconnect, ssh_free, ssh_packet_set_newkeys.
static int crypt_set_algorithms2(ssh_session session)
References ssh_cipher_struct::aead_encrypt, cipher_new, ssh_cipher_struct::ciphertype, ssh_crypto_struct::delayed_compress_in, ssh_crypto_struct::delayed_compress_out, ssh_crypto_struct::do_compress_in, ssh_crypto_struct::do_compress_out, ssh_hmac_struct::etm, ssh_hmac_struct::hmac_type, ssh_crypto_struct::in_cipher, ssh_crypto_struct::in_hmac_etm, ssh_crypto_struct::kex_methods, name, ssh_cipher_struct::name, ssh_hmac_struct::name, ssh_session_struct::next_crypto, ssh_crypto_struct::out_cipher, ssh_crypto_struct::out_hmac, ssh_crypto_struct::out_hmac_etm, session, SSH_AEAD_CHACHA20_POLY1305, SSH_COMP_C_S, SSH_COMP_S_C, SSH_CRYPT_C_S, SSH_CRYPT_S_C, SSH_ERROR, SSH_FATAL, ssh_get_ciphertab, ssh_get_hmactab, SSH_LOG, SSH_LOG_PACKET, SSH_MAC_C_S, SSH_MAC_S_C, SSH_OK, ssh_set_error, ssh_set_error_oom.
Referenced by crypt_set_algorithms_client.
int crypt_set_algorithms_client(ssh_session session)
References crypt_set_algorithms2, session.
Referenced by ssh_packet_set_newkeys, torture_packet.