bcrypt_pbkdf.c
SHA512_DIGEST_LENGTH
BCRYPT_BLOCKS
BCRYPT_HASHSIZE
static void bcrypt_hash(uint8_t *sha2pass, uint8_t *sha2salt, uint8_t *out)
References BCRYPT_BLOCKS, BCRYPT_HASHSIZE, Blowfish_expand0state, Blowfish_expandstate, Blowfish_initstate, Blowfish_stream2word, explicit_bzero, SHA512_DIGEST_LENGTH, ssh_blf_enc, ZERO_STRUCT.
Referenced by bcrypt_pbkdf.
int bcrypt_pbkdf(const char *pass, size_t passlen, const uint8_t *salt, size_t saltlen, uint8_t *key, size_t keylen, unsigned int rounds)
References bcrypt_hash, BCRYPT_HASHSIZE, ctx, explicit_bzero, key, MIN, SHA512_DIGEST_LENGTH, sha512_final, sha512_init, sha512_update.
Referenced by pki_private_key_decrypt, pki_private_key_encrypt.