bench_raw.c
PYTHON_PATH
const char python_eater[][]
Referenced by get_python_eater.
const char python_giver[][]
Referenced by get_python_giver.
static char* get_python_eater(unsigned long bytes)
References python_eater.
Referenced by benchmarks_raw_up.
static int upload_script(ssh_session session, const char *path, const char *script)
References error, session, ssh_channel_close, ssh_channel_free, ssh_channel_new, ssh_channel_open_session, ssh_channel_request_exec, ssh_channel_send_eof, ssh_channel_write, SSH_ERROR, ssh_get_error.
Referenced by benchmarks_raw_down, benchmarks_raw_up.
int benchmarks_raw_up(ssh_session session, struct argument_s *args, float *bps)
References buffer, argument_s::chunksize, argument_s::datasize, elapsed_time, error, get_python_eater, PYTHON_PATH, session, ssh_channel_close, ssh_channel_free, ssh_channel_new, ssh_channel_open_session, ssh_channel_read, ssh_channel_request_exec, ssh_channel_write, SSH_ERROR, ssh_get_error, timestamp_init, upload_script, argument_s::verbose.
static char* get_python_giver(unsigned long bytes)
References python_giver.
Referenced by benchmarks_raw_down.
int benchmarks_raw_down(ssh_session session, struct argument_s *args, float *bps)
References buffer, argument_s::chunksize, argument_s::datasize, elapsed_time, error, get_python_giver, PYTHON_PATH, session, ssh_channel_close, ssh_channel_free, ssh_channel_new, ssh_channel_open_session, ssh_channel_read, ssh_channel_request_exec, ssh_channel_write, SSH_ERROR, ssh_get_error, timestamp_init, upload_script, argument_s::verbose.