benchmarks.h
MAX_HOSTS_CONNECT
libssh_benchmarks
typedef int(* bench_fct) (ssh_session session, struct argument_s *args, float *bps))(ssh_session session, struct argument_s *args, float *bps)
char* buffer
Referenced by _ssh_buffer_pack, _ssh_buffer_unpack, _ssh_log, auth_kbdint, authenticate_console, authenticate_kbdint, base64_to_bin, batch_shell, benchmarks_async_sftp_down, benchmarks_raw_down, benchmarks_raw_up, benchmarks_scp_down, benchmarks_scp_up, benchmarks_sync_sftp_down, benchmarks_sync_sftp_up, buffer_free, buffer_get, buffer_get_len, buffer_shift, callback_receive_banner, channel_read_buffer, channel_request, create_files, do_connect, fetch_files, ssh::Session::log, main, match_hashed_host, pki_dsa_signature_to_blob, pki_ed25519_public_key_to_blob, pki_ed25519_sign, pki_ed25519_verify, pki_import_cert_buffer, pki_import_privkey_buffer, pki_import_pubkey_buffer, pki_openssh_export_privkey_blob, pki_private_key_decrypt, pki_publickey_to_blob, realloc_buffer, select_loop, setup, ssh_buffer_add_buffer, ssh_buffer_add_data, ssh_buffer_add_ssh_string, ssh_buffer_add_u16, ssh_buffer_add_u32, ssh_buffer_add_u64, ssh_buffer_add_u8, ssh_buffer_allocate, ssh_buffer_allocate_size, ssh_buffer_free, ssh_buffer_get, ssh_buffer_get_data, ssh_buffer_get_len, ssh_buffer_get_ssh_string, ssh_buffer_get_u32, ssh_buffer_get_u64, ssh_buffer_get_u8, ssh_buffer_pack_allocate_va, ssh_buffer_pack_va, ssh_buffer_pass_bytes, ssh_buffer_pass_bytes_end, ssh_buffer_prepend_data, ssh_buffer_reinit, ssh_buffer_set_secure, ssh_buffer_unpack_va, ssh_buffer_validate_length, ssh_channel_cancel_forward, ssh_channel_change_pty_size, ssh_channel_listen_forward, ssh_channel_request_env, ssh_channel_request_exec, ssh_channel_request_pty_size, ssh_channel_request_send_break, ssh_channel_request_send_signal, ssh_channel_request_subsystem, ssh_channel_request_x11, ssh_connector_channel_write_wontblock_cb, ssh_connector_fd_in_cb, ssh_connector_fd_out_cb, ssh_connector_fd_read, ssh_connector_fd_write, ssh_dir_writeable, ssh_dump_knownhost, ssh_get_knownhost_line, ssh_global_request, ssh_legacy_log_callback, ssh_log, ssh_log_common, ssh_log_function, ssh_log_hexdump, ssh_log_stderr, ssh_pki_import_pubkey_base64, ssh_pki_import_pubkey_blob, ssh_pki_openssh_import, ssh_pki_openssh_privkey_export, ssh_publickey_to_file, ssh_scp_accept_request, ssh_scp_close, ssh_scp_deny_request, ssh_scp_leave_directory, ssh_scp_pull_request, ssh_scp_push_directory, ssh_scp_push_file64, ssh_scp_read, ssh_scp_read_string, ssh_scp_string_mode, ssh_scp_write, ssh_send_banner, ssh_socket_pollcallback, ssh_socket_unbuffered_read, ssh_socket_unbuffered_write, ssh_socket_write, ssh_write_knownhost, test_mock_ssh_logging_callback, thread_buffer_pack_badformat, thread_buffer_prepend, thread_growing_buffer, thread_growing_buffer_shifting, thread_ssh_buffer_add_format, thread_ssh_buffer_get_format, thread_ssh_buffer_get_format_error, thread_ssh_buffer_get_ssh_string, torture_buffer_pack_badformat, torture_buffer_prepend, torture_growing_buffer, torture_growing_buffer_shifting, torture_knownhosts_port, torture_log_callback, torture_packet, torture_rand_thread, torture_read_one_line, torture_request_env, torture_ssh_buffer_add_format, torture_ssh_buffer_get_format, torture_ssh_buffer_get_format_error, torture_ssh_buffer_get_ssh_string, torture_ssh_dir_writeable, torture_ssh_mkdirs, torture_ssh_newline_vis, torture_ssh_quote_file_name.
int benchmarks_ping_latency(const char *host, float *average)
References host, PING_PROGRAM.
Referenced by do_benchmarks.
int benchmarks_ssh_latency(ssh_session session, float *average)
References elapsed_time, error, session, ssh_channel_close, ssh_channel_free, ssh_channel_new, ssh_channel_open_session, ssh_channel_request_env, SSH_ERROR, SSH_FATAL, ssh_get_error, ssh_get_error_code, timestamp_init.
Referenced by do_benchmarks.
void timestamp_init(struct timestamp_struct *ts)
References timestamp_struct::timestamp.
Referenced by benchmarks_async_sftp_down, benchmarks_raw_down, benchmarks_raw_up, benchmarks_scp_down, benchmarks_scp_up, benchmarks_ssh_latency, benchmarks_sync_sftp_down, benchmarks_sync_sftp_up.
float elapsed_time(struct timestamp_struct *ts)
References timestamp_struct::timestamp.
Referenced by benchmarks_async_sftp_down, benchmarks_raw_down, benchmarks_raw_up, benchmarks_scp_down, benchmarks_scp_up, benchmarks_ssh_latency, benchmarks_sync_sftp_down, benchmarks_sync_sftp_up.
int benchmarks_raw_up(ssh_session session, struct argument_s *args, float *bps)
References buffer, argument_s::chunksize, argument_s::datasize, elapsed_time, error, get_python_eater, PYTHON_PATH, session, ssh_channel_close, ssh_channel_free, ssh_channel_new, ssh_channel_open_session, ssh_channel_read, ssh_channel_request_exec, ssh_channel_write, SSH_ERROR, ssh_get_error, timestamp_init, upload_script, argument_s::verbose.
int benchmarks_raw_down(ssh_session session, struct argument_s *args, float *bps)
References buffer, argument_s::chunksize, argument_s::datasize, elapsed_time, error, get_python_giver, PYTHON_PATH, session, ssh_channel_close, ssh_channel_free, ssh_channel_new, ssh_channel_open_session, ssh_channel_read, ssh_channel_request_exec, ssh_channel_write, SSH_ERROR, ssh_get_error, timestamp_init, upload_script, argument_s::verbose.
int benchmarks_scp_up(ssh_session session, struct argument_s *args, float *bps)
References buffer, argument_s::chunksize, argument_s::datasize, elapsed_time, error, SCPDIR, SCPFILE, session, SSH_ERROR, ssh_get_error, SSH_OK, ssh_scp_close, ssh_scp_free, ssh_scp_init, ssh_scp_new, ssh_scp_push_file, SSH_SCP_WRITE, ssh_scp_write, timestamp_init, argument_s::verbose.
int benchmarks_scp_down(ssh_session session, struct argument_s *args, float *bps)
References buffer, argument_s::chunksize, argument_s::datasize, elapsed_time, error, SCPDIR, SCPFILE, session, SSH_ERROR, ssh_get_error, ssh_scp_accept_request, ssh_scp_close, ssh_scp_free, ssh_scp_init, ssh_scp_new, ssh_scp_pull_request, SSH_SCP_READ, ssh_scp_read, ssh_scp_request_get_size, SSH_SCP_REQUEST_NEWFILE, timestamp_init, argument_s::verbose.
int benchmarks_sync_sftp_up(ssh_session session, struct argument_s *args, float *bps)
References buffer, argument_s::chunksize, argument_s::datasize, elapsed_time, error, session, sftp_close, sftp_free, sftp_init, sftp_new, sftp_open, sftp_write, SFTPDIR, SFTPFILE, SSH_ERROR, ssh_get_error, timestamp_init, argument_s::verbose.
int benchmarks_sync_sftp_down(ssh_session session, struct argument_s *args, float *bps)
References buffer, argument_s::chunksize, argument_s::datasize, elapsed_time, error, session, sftp_close, sftp_free, sftp_init, sftp_new, sftp_open, sftp_read, SFTPDIR, SFTPFILE, SSH_ERROR, ssh_get_error, timestamp_init, argument_s::verbose.
int benchmarks_async_sftp_down(ssh_session session, struct argument_s *args, float *bps)
References buffer, argument_s::chunksize, argument_s::concurrent_requests, argument_s::datasize, elapsed_time, error, session, sftp_async_read, sftp_async_read_begin, sftp_close, sftp_free, sftp_init, sftp_new, sftp_open, SFTPDIR, SFTPFILE, SSH_ERROR, ssh_get_error, timestamp_init, argument_s::verbose.