bignum.h
bignum ssh_make_string_bn(ssh_string string)
References ssh_string_struct::data, SSH_LOG, SSH_LOG_TRACE, ssh_string_len.
Referenced by pki_privkey_build_dss, pki_privkey_build_rsa, pki_pubkey_build_dss, pki_pubkey_build_rsa, pki_signature_from_dsa_blob, pki_signature_from_ecdsa_blob, ssh_buffer_unpack_va, torture_session_keys.
ssh_string ssh_make_bignum_string(bignum num)
References bits, ssh_string_struct::data, SSH_LOG, SSH_LOG_TRACE, ssh_string_new.
Referenced by pki_dsa_signature_to_blob, pki_ecdsa_signature_to_blob, pki_publickey_to_blob, ssh_buffer_pack_va, ssh_generate_session_keys.
void ssh_print_bignum(const char *which, const_bignum num)
References name, SAFE_FREE.
Referenced by ssh_dh_debug_crypto.