bind_config.h
ssh_bind_config_opcode_e
int ssh_bind_config_parse_file(ssh_bind sshbind, const char *filename)
References BIND_CFG_MAX, MAX_LINE_SIZE, PARSING, ssh_bind_config_parse_line, SSH_LOG, SSH_LOG_PACKET.
Referenced by torture_bind_config_ciphers, torture_bind_config_corner_cases, torture_bind_config_full, torture_bind_config_hostkey, torture_bind_config_hostkey_algorithms, torture_bind_config_hostkey_separately, torture_bind_config_hostkey_twice_rec, torture_bind_config_include, torture_bind_config_include_recursive, torture_bind_config_kexalgorithms, torture_bind_config_listen_address, torture_bind_config_loglevel, torture_bind_config_macs, torture_bind_config_match_all, torture_bind_config_match_corner_cases, torture_bind_config_match_invalid, torture_bind_config_match_not_allowed, torture_bind_config_match_twice, torture_bind_config_match_unsupported, torture_bind_config_port, torture_bind_config_pubkey_accepted.