buffer.c
BUFFER_SIZE_MAX
buffer_verify
struct ssh_buffer_struct* ssh_buffer_new(void)
Create a new SSH buffer.
A newly initialized SSH buffer, NULL on error.
References buffer_verify, rc, SAFE_FREE, ssh_buffer_allocate_size.
Referenced by base64_to_bin, buffer_new, channel_default_bufferize, gzip_compress, gzip_decompress, main, pki_ecdsa_signature_to_blob, pki_import_cert_buffer, pki_private_key_decrypt, pki_publickey_to_blob, pki_signature_from_ecdsa_blob, setup, sftp_get_client_message, sftp_reply_attr, sftp_reply_data, sftp_reply_handle, sftp_reply_name, sftp_reply_names, sftp_reply_names_add, sftp_reply_status, ssh_agent_get_ident_count, ssh_agent_sign_data, ssh_channel_cancel_forward, ssh_channel_change_pty_size, ssh_channel_listen_forward, ssh_channel_new, ssh_channel_open_forward, ssh_channel_open_forward_unix, ssh_channel_request_env, ssh_channel_request_exec, ssh_channel_request_pty_size, ssh_channel_request_send_break, ssh_channel_request_send_signal, ssh_channel_request_subsystem, ssh_channel_request_x11, ssh_gssapi_build_mic, ssh_hashbufin_add_cookie, ssh_hashbufout_add_cookie, ssh_make_sessionid, ssh_new, ssh_packet_send, ssh_packet_socket_callback, ssh_pki_copy_cert_to_privkey, ssh_pki_do_sign, ssh_pki_do_sign_agent, ssh_pki_export_signature_blob, ssh_pki_import_pubkey_blob, ssh_pki_import_signature_blob, ssh_pki_openssh_import, ssh_pki_openssh_privkey_export, ssh_pki_signature_verify, ssh_socket_new, thread_buffer_pack_badformat, thread_buffer_prepend, thread_growing_buffer, thread_growing_buffer_shifting, thread_ssh_buffer_add_format, thread_ssh_buffer_get_format, thread_ssh_buffer_get_format_error, thread_ssh_buffer_get_ssh_string, torture_ssh_buffer_get_ssh_string.
void ssh_buffer_free(struct ssh_buffer_struct *buffer)
Deallocate a SSH buffer.
buffer The buffer to free.
References buffer, buffer_verify, explicit_bzero, SAFE_FREE.
void ssh_buffer_set_secure(ssh_buffer buffer)
Sets the buffer as secure.
A secure buffer will never leave cleartext data in the heap after being reallocated or freed. buffer buffer to set secure.
References buffer.
Referenced by base64_to_bin, setup, ssh_pki_do_sign, ssh_pki_openssh_import, ssh_userauth_password, thread_buffer_pack_badformat, thread_buffer_prepend, thread_growing_buffer, thread_growing_buffer_shifting, thread_ssh_buffer_add_format, thread_ssh_buffer_get_format, thread_ssh_buffer_get_format_error.
static int realloc_buffer(struct ssh_buffer_struct *buffer, size_t needed)
References buffer, BUFFER_SIZE_MAX, buffer_verify, explicit_bzero, SAFE_FREE.
Referenced by ssh_buffer_add_data, ssh_buffer_allocate, ssh_buffer_allocate_size, ssh_buffer_prepend_data, ssh_buffer_reinit.
static void buffer_shift(ssh_buffer buffer)
References buffer, buffer_verify, explicit_bzero.
Referenced by ssh_buffer_add_data, ssh_buffer_allocate, ssh_buffer_allocate_size.
int ssh_buffer_reinit(struct ssh_buffer_struct *buffer)
Reinitialize a SSH buffer.
In case the buffer has exceeded 64K in size, the buffer will be reallocated to 64K. buffer The buffer to reinitialize. 0 on success, < 0 on error.
References buffer, buffer_verify, explicit_bzero, rc, realloc_buffer.
int ssh_buffer_add_data(struct ssh_buffer_struct *buffer, const void *data, uint32_t len)
Add data at the tail of a buffer.
buffer The buffer to add the data. data A pointer to the data to add. len The length of the data to add. 0 on success, < 0 on error.
References buffer, buffer_shift, buffer_verify, ssh_buffer_struct::data, realloc_buffer.
Referenced by ssh_buffer_add_buffer, ssh_buffer_add_ssh_string, ssh_buffer_add_u16, ssh_buffer_add_u32, ssh_buffer_add_u64, ssh_buffer_add_u8, ssh_buffer_pack_va.
int ssh_buffer_allocate_size(struct ssh_buffer_struct *buffer, uint32_t len)
Ensure the buffer has at least a certain preallocated size.
buffer The buffer to enlarge. len The length to ensure as allocated. 0 on success, < 0 on error.
References buffer, buffer_shift, buffer_verify, realloc_buffer.
Referenced by ssh_agent_sign_data, ssh_buffer_new, ssh_buffer_pack_allocate_va, ssh_hashbufin_add_cookie, ssh_hashbufout_add_cookie.
void* ssh_buffer_allocate(struct ssh_buffer_struct *buffer, uint32_t len)
References buffer, buffer_shift, buffer_verify, realloc_buffer.
Referenced by ssh_packet_socket_callback.
int ssh_buffer_add_ssh_string(struct ssh_buffer_struct *buffer, struct ssh_string_struct *string)
References buffer, ssh_buffer_add_data, ssh_string_len.
Referenced by ssh_buffer_pack_va.
int ssh_buffer_add_u32(struct ssh_buffer_struct *buffer, uint32_t data)
References buffer, ssh_buffer_struct::data, rc, ssh_buffer_add_data.
Referenced by ssh_buffer_pack_va.
int ssh_buffer_add_u16(struct ssh_buffer_struct *buffer, uint16_t data)
References buffer, ssh_buffer_struct::data, rc, ssh_buffer_add_data.
Referenced by ssh_buffer_pack_va.
int ssh_buffer_add_u64(struct ssh_buffer_struct *buffer, uint64_t data)
References buffer, ssh_buffer_struct::data, rc, ssh_buffer_add_data.
Referenced by ssh_buffer_pack_va.
int ssh_buffer_add_u8(struct ssh_buffer_struct *buffer, uint8_t data)
References buffer, ssh_buffer_struct::data, rc, ssh_buffer_add_data.
Referenced by ssh_buffer_pack_va.
int ssh_buffer_prepend_data(struct ssh_buffer_struct *buffer, const void *data, uint32_t len)
References buffer, buffer_verify, ssh_buffer_struct::data, ssh_buffer_struct::pos, realloc_buffer.
int ssh_buffer_add_buffer(struct ssh_buffer_struct *buffer, struct ssh_buffer_struct *source)
References buffer, rc, ssh_buffer_add_data, ssh_buffer_get, ssh_buffer_get_len.
void* ssh_buffer_get(struct ssh_buffer_struct *buffer)
Get a pointer to the head of a buffer at the current position.
buffer The buffer to get the head pointer. A pointer to the data from current position. ssh_buffer_get_len()
References buffer.
Referenced by ssh_buffer_add_buffer.
uint32_t ssh_buffer_get_len(struct ssh_buffer_struct *buffer)
Get the length of the buffer from the current position.
buffer The buffer to get the length from. The length of the buffer. ssh_buffer_get()
References buffer, buffer_verify.
Referenced by ssh_buffer_add_buffer, ssh_buffer_unpack_va.
uint32_t ssh_buffer_pass_bytes(struct ssh_buffer_struct *buffer, uint32_t len)
References buffer, buffer_verify, ssh_buffer_struct::pos.
uint32_t ssh_buffer_pass_bytes_end(struct ssh_buffer_struct *buffer, uint32_t len)
References buffer, buffer_verify.
uint32_t ssh_buffer_get_data(struct ssh_buffer_struct *buffer, void *data, uint32_t len)
Get the remaining data out of the buffer and adjust the read pointer.
buffer The buffer to read. data The data buffer where to store the data. len The length to read from the buffer. 0 if there is not enough data in buffer, len otherwise.
References buffer, ssh_buffer_struct::data, rc, ssh_buffer_validate_length, SSH_OK.
Referenced by ssh_buffer_get_ssh_string, ssh_buffer_get_u32, ssh_buffer_get_u64, ssh_buffer_get_u8, ssh_buffer_unpack_va.
int ssh_buffer_get_u8(struct ssh_buffer_struct *buffer, uint8_t *data)
References buffer, ssh_buffer_struct::data, ssh_buffer_get_data.
Referenced by ssh_buffer_unpack_va.
int ssh_buffer_get_u32(struct ssh_buffer_struct *buffer, uint32_t *data)
References buffer, ssh_buffer_struct::data, ssh_buffer_get_data.
Referenced by ssh_buffer_get_ssh_string, ssh_buffer_unpack_va.
int ssh_buffer_get_u64(struct ssh_buffer_struct *buffer, uint64_t *data)
References buffer, ssh_buffer_struct::data, ssh_buffer_get_data.
Referenced by ssh_buffer_unpack_va.
int ssh_buffer_validate_length(struct ssh_buffer_struct *buffer, size_t len)
Valdiates that the given length can be obtained from the buffer.
buffer The buffer to read from. len The length to be checked. SSH_OK if the length is valid, SSH_ERROR otherwise.
References buffer, ssh_buffer_struct::pos, SSH_ERROR, SSH_OK.
Referenced by ssh_buffer_get_data, ssh_buffer_get_ssh_string, ssh_buffer_unpack_va.
struct ssh_string_struct* ssh_buffer_get_ssh_string(struct ssh_buffer_struct *buffer)
References buffer, rc, SAFE_FREE, ssh_buffer_get_data, ssh_buffer_get_u32, ssh_buffer_validate_length, SSH_OK, ssh_string_data, ssh_string_new.
Referenced by ssh_buffer_unpack_va.
static int ssh_buffer_pack_allocate_va(struct ssh_buffer_struct *buffer, const char *format, size_t argc, va_list ap)
Pre-calculate the size we need for packing the buffer.
This makes sure that enough memory is allocated for packing the buffer and we only have to do one memory allocation. buffer The buffer to allocate format A format string of arguments. argc The number of arguments. ap The va_list of arguments. SSH_OK on success, SSH_ERROR on error.
References buffer, rc, ssh_buffer_allocate_size, SSH_BUFFER_PACK_END, SSH_ERROR, SSH_LOG, SSH_LOG_WARN, SSH_OK, ssh_string_len.
Referenced by _ssh_buffer_pack.
int ssh_buffer_pack_va(struct ssh_buffer_struct *buffer, const char *format, size_t argc, va_list ap)
References buffer, ssh_string_struct::data, htonll, rc, SAFE_FREE, ssh_buffer_add_data, ssh_buffer_add_ssh_string, ssh_buffer_add_u16, ssh_buffer_add_u32, ssh_buffer_add_u64, ssh_buffer_add_u8, SSH_BUFFER_PACK_END, SSH_ERROR, SSH_LOG, SSH_LOG_WARN, ssh_make_bignum_string, SSH_OK.
Referenced by _ssh_buffer_pack.
int _ssh_buffer_pack(struct ssh_buffer_struct *buffer, const char *format, size_t argc,...)
References buffer, rc, ssh_buffer_pack_allocate_va, ssh_buffer_pack_va, SSH_ERROR, SSH_OK.
int ssh_buffer_unpack_va(struct ssh_buffer_struct *buffer, const char *format, size_t argc, va_list ap)
References buffer, explicit_bzero, ntohll, rc, SAFE_FREE, ssh_buffer_get_data, ssh_buffer_get_len, ssh_buffer_get_ssh_string, ssh_buffer_get_u32, ssh_buffer_get_u64, ssh_buffer_get_u8, SSH_BUFFER_PACK_END, ssh_buffer_validate_length, SSH_ERROR, SSH_LOG, SSH_LOG_WARN, ssh_make_string_bn, SSH_OK, ssh_string_burn, SSH_STRING_FREE.
Referenced by _ssh_buffer_unpack.
int _ssh_buffer_unpack(struct ssh_buffer_struct *buffer, const char *format, size_t argc,...)
References buffer, rc, ssh_buffer_unpack_va.