callbacks.h
typedef int(* ssh_thread_callback) (void **lock))(void **lock)
@group libssh_threads
typedef unsigned long(* ssh_thread_id_callback) (void))(void)
LIBSSH_API int ssh_threads_set_callbacks(struct ssh_threads_callbacks_struct *cb)
Set the thread callbacks structure.
This is necessary if your program is using libssh in a multithreaded fashion. This function must be called first, outside of any threading context (in your main() function for instance), before you call ssh_init(). cb A pointer to a ssh_threads_callbacks_struct structure, which contains the different callbacks to be set. Always returns SSH_OK. ssh_threads_callbacks_struct SSH_THREADS_PTHREAD Buglibgcrypt 1.6 and bigger backend does not support custom callback. Using anything else than pthreads here will fail.
References cb, crypto_thread_finalize, crypto_thread_init, rc, user_callbacks.
Referenced by pkd_init_libssh, setup.
LIBSSH_API struct ssh_threads_callbacks_struct* ssh_threads_get_default(void)
Returns a pointer to the appropriate callbacks structure for the environment, to be used with ssh_threads_set_callbacks.
A pointer to a ssh_threads_callbacks_struct to be used with ssh_threads_set_callbacks. ssh_threads_set_callbacks
References ssh_threads_noop.
Referenced by ssh_threads_init.
LIBSSH_API struct ssh_threads_callbacks_struct* ssh_threads_get_pthread(void)
Returns a pointer on the pthread threads callbacks, to be used with ssh_threads_set_callbacks.
ssh_threads_set_callbacks
References ssh_threads_pthread.
Referenced by pkd_init_libssh, setup.
LIBSSH_API struct ssh_threads_callbacks_struct* ssh_threads_get_noop(void)
Get the noop threads callbacks structure.
This can be used with ssh_threads_set_callbacks. These callbacks do nothing and are being used by default. Always returns a valid pointer to the noop callbacks structure. ssh_threads_set_callbacks
References ssh_threads_noop.
LIBSSH_API int ssh_set_log_callback(ssh_logging_callback cb)
Set the logging callback function.
cb The callback to set. 0 on success, < 0 on errror.
References cb, SSH_ERROR, ssh_log_cb, SSH_OK.
Referenced by ssh_set_callbacks, torture_log_callback.
LIBSSH_API ssh_logging_callback ssh_get_log_callback(void)
Get the pointer to the logging callback function.
The pointer the the callback or NULL if none set.
References ssh_log_cb.
Referenced by ssh_log_function, ssh_set_callbacks.
SSH_SOCKET_FLOW_WRITEWILLBLOCK
SSH_SOCKET_FLOW_WRITEWONTBLOCK
SSH_SOCKET_EXCEPTION_EOF
SSH_SOCKET_EXCEPTION_ERROR
SSH_SOCKET_CONNECTED_OK
SSH_SOCKET_CONNECTED_ERROR
SSH_SOCKET_CONNECTED_TIMEOUT
ssh_callbacks_init
Initializes an ssh_callbacks_struct A call to this macro is mandatory when you have set a new ssh_callback_struct structure. Its goal is to maintain the binary compatibility with future versions of libssh as the structure evolves with time.
ssh_callbacks_exists
ssh_callbacks_execute_list
ssh_callbacks_iterate
ssh_callbacks_iterate_exec
ssh_callbacks_iterate_end
SSH_PACKET_USED
return values for a ssh_packet_callback Packet was used and should not be parsed by another callback
SSH_PACKET_NOT_USED
Packet was not used and should be passed to any other callback available
SSH_PACKET_CALLBACK
This macro declares a packet callback handler.
SSH_PACKET_CALLBACK(mycallback){ ... }
typedef void(* ssh_callback_int) (int code, void *user))(int code, void *user)
typedef int(* ssh_callback_data) (const void *data, size_t len, void *user))(const void *data, size_t len, void *user)
typedef void(* ssh_callback_int_int) (int code, int errno_code, void *user))(int code, int errno_code, void *user)
typedef int(* ssh_message_callback) (ssh_session, ssh_message message, void *user))(ssh_session, ssh_message message, void *user)
typedef int(* ssh_channel_callback_int) (ssh_channel channel, int code, void *user))(ssh_channel channel, int code, void *user)
typedef int(* ssh_channel_callback_data) (ssh_channel channel, int code, void *data, size_t len, void *user))(ssh_channel channel, int code, void *data, size_t len, void *user)
typedef void(* ssh_log_callback) (ssh_session session, int priority, const char *message, void *userdata))(ssh_session session, int priority, const char *message, void *userdata)
SSH log callback. All logging messages will go through this callback.
session Current session handler priority Priority of the log, the smaller being the more important message the actual message userdata Userdata to be passed to the callback function.
typedef void(* ssh_logging_callback) (int priority, const char *function, const char *buffer, void *userdata))(int priority, const char *function, const char *buffer, void *userdata)
SSH log callback.
All logging messages will go through this callback. priority Priority of the log, the smaller being the more important. function The function name calling the the logging fucntions. message The actual message userdata Userdata to be passed to the callback function.
typedef void(* ssh_status_callback) (ssh_session session, float status, void *userdata))(ssh_session session, float status, void *userdata)
SSH Connection status callback.
session Current session handler status Percentage of connection status, going from 0.0 to 1.0 once connection is done. userdata Userdata to be passed to the callback function.
typedef void(* ssh_global_request_callback) (ssh_session session, ssh_message message, void *userdata))(ssh_session session, ssh_message message, void *userdata)
SSH global request callback. All global request will go through this callback.
session Current session handler message the actual message userdata Userdata to be passed to the callback function.
typedef ssh_channel(* ssh_channel_open_request_x11_callback) (ssh_session session, const char *originator_address, int originator_port, void *userdata))(ssh_session session, const char *originator_address, int originator_port, void *userdata)
Handles an SSH new channel open X11 request. This happens when the server sends back an X11 connection attempt. This is a client-side API.
session current session handler userdata Userdata to be passed to the callback function. a valid ssh_channel handle if the request is to be allowed NULL if the request should not be allowed The channel pointer returned by this callback must be closed by the application.
typedef ssh_channel(* ssh_channel_open_request_auth_agent_callback) (ssh_session session, void *userdata))(ssh_session session, void *userdata)
Handles an SSH new channel open "auth-agent" request. This happens when the server sends back an "auth-agent" connection attempt. This is a client-side API.
session current session handler userdata Userdata to be passed to the callback function. a valid ssh_channel handle if the request is to be allowed NULL if the request should not be allowed The channel pointer returned by this callback must be closed by the application.
typedef struct ssh_callbacks_struct* ssh_callbacks
typedef int(* ssh_auth_password_callback) (ssh_session session, const char *user, const char *password, void *userdata))(ssh_session session, const char *user, const char *password, void *userdata)
SSH authentication callback.
These are callbacks used specifically in SSH servers. session Current session handler user User that wants to authenticate password Password used for authentication userdata Userdata to be passed to the callback function. SSH_AUTH_SUCCESS Authentication is accepted. SSH_AUTH_PARTIAL Partial authentication, more authentication means are needed. SSH_AUTH_DENIED Authentication failed.
typedef int(* ssh_auth_none_callback) (ssh_session session, const char *user, void *userdata))(ssh_session session, const char *user, void *userdata)
SSH authentication callback. Tries to authenticates user with the "none" method which is anonymous or passwordless.
session Current session handler user User that wants to authenticate userdata Userdata to be passed to the callback function. SSH_AUTH_SUCCESS Authentication is accepted. SSH_AUTH_PARTIAL Partial authentication, more authentication means are needed. SSH_AUTH_DENIED Authentication failed.
typedef int(* ssh_auth_gssapi_mic_callback) (ssh_session session, const char *user, const char *principal, void *userdata))(ssh_session session, const char *user, const char *principal, void *userdata)
SSH authentication callback. Tries to authenticates user with the "gssapi-with-mic" method.
session Current session handler user Username of the user (can be spoofed) principal Authenticated principal of the user, including realm. userdata Userdata to be passed to the callback function. SSH_AUTH_SUCCESS Authentication is accepted. SSH_AUTH_PARTIAL Partial authentication, more authentication means are needed. SSH_AUTH_DENIED Authentication failed. Implementations should verify that parameter user matches in some way the principal. user and principal can be different. Only the latter is guaranteed to be safe.
typedef int(* ssh_auth_pubkey_callback) (ssh_session session, const char *user, struct ssh_key_struct *pubkey, char signature_state, void *userdata))(ssh_session session, const char *user, struct ssh_key_struct *pubkey, char signature_state, void *userdata)
SSH authentication callback.
session Current session handler user User that wants to authenticate pubkey public key used for authentication signature_state SSH_PUBLICKEY_STATE_NONE if the key is not signed (simple public key probe), SSH_PUBLICKEY_STATE_VALID if the signature is valid. Others values should be replied with a SSH_AUTH_DENIED. userdata Userdata to be passed to the callback function. SSH_AUTH_SUCCESS Authentication is accepted. SSH_AUTH_PARTIAL Partial authentication, more authentication means are needed. SSH_AUTH_DENIED Authentication failed.
typedef int(* ssh_service_request_callback) (ssh_session session, const char *service, void *userdata))(ssh_session session, const char *service, void *userdata)
Handles an SSH service request.
session current session handler service name of the service (e.g. "ssh-userauth") requested userdata Userdata to be passed to the callback function. 0 if the request is to be allowed -1 if the request should not be allowed
typedef ssh_channel(* ssh_channel_open_request_session_callback) (ssh_session session, void *userdata))(ssh_session session, void *userdata)
Handles an SSH new channel open session request.
session current session handler userdata Userdata to be passed to the callback function. a valid ssh_channel handle if the request is to be allowed NULL if the request should not be allowed The channel pointer returned by this callback must be closed by the application.
typedef ssh_string(* ssh_gssapi_select_oid_callback) (ssh_session session, const char *user, int n_oid, ssh_string *oids, void *userdata))(ssh_session session, const char *user, int n_oid, ssh_string *oids, void *userdata)
typedef int(* ssh_gssapi_accept_sec_ctx_callback) (ssh_session session, ssh_string input_token, ssh_string *output_token, void *userdata))(ssh_session session, ssh_string input_token, ssh_string *output_token, void *userdata)
typedef int(* ssh_gssapi_verify_mic_callback) (ssh_session session, ssh_string mic, void *mic_buffer, size_t mic_buffer_size, void *userdata))(ssh_session session, ssh_string mic, void *mic_buffer, size_t mic_buffer_size, void *userdata)
typedef struct ssh_server_callbacks_struct* ssh_server_callbacks
typedef struct ssh_socket_callbacks_struct* ssh_socket_callbacks
typedef int(* ssh_packet_callback) (ssh_session session, uint8_t type, ssh_buffer packet, void *user))(ssh_session session, uint8_t type, ssh_buffer packet, void *user)
Prototype for a packet callback, to be called when a new packet arrives.
session The current session of the packet type packet type (see ssh2.h) packet buffer containing the packet, excluding size, type and padding fields user user argument to the callback and are called each time a packet shows up SSH_PACKET_USED Packet was parsed and used SSH_PACKET_NOT_USED Packet was not used or understood, processing must continue
typedef struct ssh_packet_callbacks_struct* ssh_packet_callbacks
typedef int(* ssh_channel_data_callback) (ssh_session session, ssh_channel channel, void *data, uint32_t len, int is_stderr, void *userdata))(ssh_session session, ssh_channel channel, void *data, uint32_t len, int is_stderr, void *userdata)
SSH channel data callback. Called when data is available on a channel.
session Current session handler channel the actual channel data the data that has been read on the channel len the length of the data is_stderr is 0 for stdout or 1 for stderr userdata Userdata to be passed to the callback function. number of bytes processed by the callee. The remaining bytes will be sent in the next callback message, when more data is available.
typedef void(* ssh_channel_eof_callback) (ssh_session session, ssh_channel channel, void *userdata))(ssh_session session, ssh_channel channel, void *userdata)
SSH channel eof callback. Called when a channel receives EOF.
session Current session handler channel the actual channel userdata Userdata to be passed to the callback function.
typedef void(* ssh_channel_close_callback) (ssh_session session, ssh_channel channel, void *userdata))(ssh_session session, ssh_channel channel, void *userdata)
SSH channel close callback. Called when a channel is closed by remote peer.
session Current session handler channel the actual channel userdata Userdata to be passed to the callback function.
typedef void(* ssh_channel_signal_callback) (ssh_session session, ssh_channel channel, const char *signal, void *userdata))(ssh_session session, ssh_channel channel, const char *signal, void *userdata)
SSH channel signal callback. Called when a channel has received a signal.
session Current session handler channel the actual channel signal the signal name (without the SIG prefix) userdata Userdata to be passed to the callback function.
typedef void(* ssh_channel_exit_status_callback) (ssh_session session, ssh_channel channel, int exit_status, void *userdata))(ssh_session session, ssh_channel channel, int exit_status, void *userdata)
SSH channel exit status callback. Called when a channel has received an exit status.
session Current session handler channel the actual channel userdata Userdata to be passed to the callback function.
typedef void(* ssh_channel_exit_signal_callback) (ssh_session session, ssh_channel channel, const char *signal, int core, const char *errmsg, const char *lang, void *userdata))(ssh_session session, ssh_channel channel, const char *signal, int core, const char *errmsg, const char *lang, void *userdata)
SSH channel exit signal callback. Called when a channel has received an exit signal.
session Current session handler channel the actual channel signal the signal name (without the SIG prefix) core a boolean telling wether a core has been dumped or not errmsg the description of the exception lang the language of the description (format: RFC 3066) userdata Userdata to be passed to the callback function.
typedef int(* ssh_channel_pty_request_callback) (ssh_session session, ssh_channel channel, const char *term, int width, int height, int pxwidth, int pwheight, void *userdata))(ssh_session session, ssh_channel channel, const char *term, int width, int height, int pxwidth, int pwheight, void *userdata)
SSH channel PTY request from a client.
channel the channel term The type of terminal emulation width width of the terminal, in characters height height of the terminal, in characters pxwidth width of the terminal, in pixels pxheight height of the terminal, in pixels userdata Userdata to be passed to the callback function. 0 if the pty request is accepted -1 if the request is denied
typedef int(* ssh_channel_shell_request_callback) (ssh_session session, ssh_channel channel, void *userdata))(ssh_session session, ssh_channel channel, void *userdata)
SSH channel Shell request from a client.
channel the channel userdata Userdata to be passed to the callback function. 0 if the shell request is accepted 1 if the request is denied
typedef void(* ssh_channel_auth_agent_req_callback) (ssh_session session, ssh_channel channel, void *userdata))(ssh_session session, ssh_channel channel, void *userdata)
SSH auth-agent-request from the client. This request is sent by a client when agent forwarding is available. Server is free to ignore this callback, no answer is expected.
channel the channel userdata Userdata to be passed to the callback function.
typedef void(* ssh_channel_x11_req_callback) (ssh_session session, ssh_channel channel, int single_connection, const char *auth_protocol, const char *auth_cookie, uint32_t screen_number, void *userdata))(ssh_session session, ssh_channel channel, int single_connection, const char *auth_protocol, const char *auth_cookie, uint32_t screen_number, void *userdata)
SSH X11 request from the client. This request is sent by a client when X11 forwarding is requested(and available). Server is free to ignore this callback, no answer is expected.
channel the channel userdata Userdata to be passed to the callback function.
typedef int(* ssh_channel_pty_window_change_callback) (ssh_session session, ssh_channel channel, int width, int height, int pxwidth, int pwheight, void *userdata))(ssh_session session, ssh_channel channel, int width, int height, int pxwidth, int pwheight, void *userdata)
SSH channel PTY windows change (terminal size) from a client.
channel the channel width width of the terminal, in characters height height of the terminal, in characters pxwidth width of the terminal, in pixels pxheight height of the terminal, in pixels userdata Userdata to be passed to the callback function. 0 if the pty request is accepted -1 if the request is denied
typedef int(* ssh_channel_exec_request_callback) (ssh_session session, ssh_channel channel, const char *command, void *userdata))(ssh_session session, ssh_channel channel, const char *command, void *userdata)
SSH channel Exec request from a client.
channel the channel command the shell command to be executed userdata Userdata to be passed to the callback function. 0 if the exec request is accepted 1 if the request is denied
typedef int(* ssh_channel_env_request_callback) (ssh_session session, ssh_channel channel, const char *env_name, const char *env_value, void *userdata))(ssh_session session, ssh_channel channel, const char *env_name, const char *env_value, void *userdata)
SSH channel environment request from a client.
channel the channel env_name name of the environment value to be set env_value value of the environment value to be set userdata Userdata to be passed to the callback function. 0 if the env request is accepted 1 if the request is denied some environment variables can be dangerous if changed (e.g. LD_PRELOAD) and should not be fulfilled.
typedef int(* ssh_channel_subsystem_request_callback) (ssh_session session, ssh_channel channel, const char *subsystem, void *userdata))(ssh_session session, ssh_channel channel, const char *subsystem, void *userdata)
SSH channel subsystem request from a client.
channel the channel subsystem the subsystem required userdata Userdata to be passed to the callback function. 0 if the subsystem request is accepted 1 if the request is denied
typedef int(* ssh_channel_write_wontblock_callback) (ssh_session session, ssh_channel channel, size_t bytes, void *userdata))(ssh_session session, ssh_channel channel, size_t bytes, void *userdata)
SSH channel write will not block (flow control).
channel the channel bytes size of the remote window in bytes. Writing as much data will not block. userdata Userdata to be passed to the callback function. 0 default return value (other return codes may be added in future).
typedef struct ssh_channel_callbacks_struct* ssh_channel_callbacks
LIBSSH_API int ssh_set_server_callbacks(ssh_session session, ssh_server_callbacks cb)
Set the session server callback functions.
This functions sets the callback structure to use your own callback functions for user authentication, new channels and requests. Note, that the structure is not copied to the session structure so it needs to be valid for the whole session lifetime. structssh_server_callbacks_structcb={ .userdata=data, .auth_password_function=my_auth_function }; ssh_callbacks_init(&cb); ssh_set_server_callbacks(session,&cb); session The session to set the callback structure. cb The callback structure itself. SSH_OK on success, SSH_ERROR on error.
References cb, is_callback_valid, ssh_session_struct::server_callbacks, session, SSH_ERROR, SSH_FATAL, ssh_set_error.
Referenced by default_handle_session_cb, handle_kbdint_session_cb, handle_session, main, pkd_exec_hello, test_ssh_channel_request_x11.
LIBSSH_API int ssh_set_callbacks(ssh_session session, ssh_callbacks cb)
Set the session callback functions.
This functions sets the callback structure to use your own callback functions for auth, logging and status. Note, that the callback structure is not copied into the session so it needs to be valid for the whole session lifetime. structssh_callbacks_structcb={ .userdata=data, .auth_function=my_auth_function }; ssh_callbacks_init(&cb); ssh_set_callbacks(session,&cb); session The session to set the callback structure. cb The callback structure itself. SSH_OK on success, SSH_ERROR on error.
References ssh_common_struct::callbacks, cb, ssh_session_struct::common, is_callback_valid, ssh_callbacks_struct::log_function, session, SSH_ERROR, SSH_FATAL, ssh_get_log_callback, ssh_legacy_log_callback, ssh_set_error, ssh_set_log_callback, ssh_set_log_userdata.
Referenced by LLVMFuzzerTestOneInput, main.
LIBSSH_API int ssh_set_channel_callbacks(ssh_channel channel, ssh_channel_callbacks cb)
Set the channel callback functions.
This functions sets the callback structure to use your own callback functions for channel data and exceptions. Note, that the structure is not copied to the channel structure so it needs to be valid as for the whole life of the channel or until it is removed with ssh_remove_channel_callbacks(). structssh_channel_callbacks_structcb={ .userdata=data, .channel_data_function=my_channel_data_function }; ssh_callbacks_init(&cb); ssh_set_channel_callbacks(channel,&cb); channel The channel to set the callback structure. cb The callback structure itself. SSH_OK on success, SSH_ERROR on error. this function will not replace existing callbacks but set the new one atop of them.
References cb, ssh_add_set_channel_callbacks.
Referenced by channel_open, default_handle_session_cb, handle_kbdint_session_cb, handle_session, message_callback, new_session_channel, pkd_channel_openreq_cb.
LIBSSH_API int ssh_add_channel_callbacks(ssh_channel channel, ssh_channel_callbacks cb)
Add channel callback functions.
This function will add channel callback functions to the channel callback list. Callbacks missing from a callback structure will be probed in the next on the list. channel The channel to set the callback structure. cb The callback structure itself. SSH_OK on success, SSH_ERROR on error. ssh_set_channel_callbacks
References cb, ssh_add_set_channel_callbacks.
Referenced by ssh_connector_set_in_channel, ssh_connector_set_out_channel.
LIBSSH_API int ssh_remove_channel_callbacks(ssh_channel channel, ssh_channel_callbacks cb)
Remove a channel callback.
The channel has been added with ssh_add_channel_callbacks or ssh_set_channel_callbacks in this case. channel The channel to remove the callback structure from. cb The callback structure to remove SSH_OK on success, SSH_ERROR on error.
References ssh_channel_struct::callbacks, cb, SSH_ERROR, ssh_list_find, ssh_list_remove, SSH_OK.
Referenced by do_cleanup, ssh_connector_free.