chacha.c
U8C
U32C
U8V
U32V
ROTL32
U8TO32_LITTLE
U32TO8_LITTLE
ROTATE
XOR
PLUS
PLUSONE
QUARTERROUND
typedef struct chacha_ctx chacha_ctx
const char sigma[16][16]
Referenced by chacha_keysetup.
const char tau[16][16]
Referenced by chacha_keysetup.
void chacha_keysetup(chacha_ctx *x, const uint8_t *k, uint32_t kbits)
References chacha_ctx::input, k, sigma, tau, U8TO32_LITTLE.
Referenced by chacha20_set_encrypt_key.
void chacha_ivsetup(chacha_ctx *x, const uint8_t *iv, const uint8_t *counter)
References chacha_ctx::input, iv, U8TO32_LITTLE.
Referenced by chacha20_poly1305_aead_decrypt, chacha20_poly1305_aead_decrypt_length, chacha20_poly1305_aead_encrypt.
void chacha_encrypt_bytes(chacha_ctx *x, const uint8_t *m, uint8_t *c, uint32_t bytes)
References chacha_ctx::input, m, PLUS, PLUSONE, QUARTERROUND, U32TO8_LITTLE, U8TO32_LITTLE, XOR.
Referenced by chacha20_poly1305_aead_decrypt, chacha20_poly1305_aead_decrypt_length, chacha20_poly1305_aead_encrypt.