ssh::Channel
friend class Session
Session* ssh::Channel::session
Referenced by Channel, getCSession, getSession.
ssh_channel ssh::Channel::channel
Referenced by acceptX11, changePtySize, Channel, close, getCChannel, getExitStatus, isClosed, isEof, isOpen, openForward, openSession, poll, read, readNonblocking, requestEnv, requestExec, requestPty, requestSendSignal, requestShell, requestSubsystem, requestX11, sendEof, write, ~Channel.
ssh::Channel::Channel(Session &ssh_session)
References channel, session, ssh_channel_new.
Referenced by acceptX11.
ssh::Channel::~Channel()
References channel, ssh_channel_free.
Channel* ssh::Channel::acceptX11(int timeout_ms)
accept an incoming X11 connection
timeout_ms timeout for waiting, in ms new Channel pointer on the X11 connection NULL in case of error you have to delete this pointer after use ssh_channel_accept_x11 Channel::requestX11
References Channel, channel, getCSession, getSession, ssh_channel_accept_x11, ssh_throw_null.
void_throwable ssh::Channel::changePtySize(int cols, int rows)
change the size of a pseudoterminal
cols number of columns rows number of rows SshException on error ssh_channel_change_pty_size
References channel, return_throwable, ssh_channel_change_pty_size, ssh_throw.
void_throwable ssh::Channel::close()
closes a channel
SshException on error ssh_channel_close
References channel, return_throwable, ssh_channel_close, ssh_throw.
int ssh::Channel::getExitStatus()
References channel, ssh_channel_get_exit_status.
Session& ssh::Channel::getSession()
References session.
Referenced by acceptX11.
bool ssh::Channel::isClosed()
returns true if channel is in closed state
ssh_channel_is_closed
References channel, ssh_channel_is_closed.
bool ssh::Channel::isEof()
returns true if channel is in EOF state
ssh_channel_is_eof
References channel, ssh_channel_is_eof.
bool ssh::Channel::isOpen()
returns true if channel is in open state
ssh_channel_is_open
References channel, ssh_channel_is_open.
int ssh::Channel::openForward(const char *remotehost, int remoteport, const char *sourcehost=NULL, int localport=0)
References channel, ssh_channel_open_forward, ssh_throw.
void_throwable ssh::Channel::openSession()
References channel, return_throwable, ssh_channel_open_session, ssh_throw.
int ssh::Channel::poll(bool is_stderr=false)
References channel, ssh_channel_poll, ssh_throw.
int ssh::Channel::read(void *dest, size_t count)
References channel, ssh_channel_read_timeout, ssh_throw.
int ssh::Channel::read(void *dest, size_t count, int timeout)
References channel, ssh_channel_read_timeout, ssh_throw.
int ssh::Channel::read(void *dest, size_t count, bool is_stderr=false, int timeout=-1)
References channel, ssh_channel_read_timeout, ssh_throw.
int ssh::Channel::readNonblocking(void *dest, size_t count, bool is_stderr=false)
References channel, ssh_channel_read_nonblocking, ssh_throw.
void_throwable ssh::Channel::requestEnv(const char *name, const char *value)
References channel, name, return_throwable, ssh_channel_request_env, ssh_throw.
void_throwable ssh::Channel::requestExec(const char *cmd)
References channel, return_throwable, ssh_channel_request_exec, ssh_throw.
void_throwable ssh::Channel::requestPty(const char *term=NULL, int cols=0, int rows=0)
References channel, return_throwable, ssh_channel_request_pty, ssh_channel_request_pty_size, ssh_throw.
void_throwable ssh::Channel::requestShell()
References channel, return_throwable, ssh_channel_request_shell, ssh_throw.
void_throwable ssh::Channel::requestSendSignal(const char *signum)
References channel, return_throwable, ssh_channel_request_send_signal, ssh_throw.
void_throwable ssh::Channel::requestSubsystem(const char *subsystem)
References channel, return_throwable, ssh_channel_request_subsystem, ssh_throw.
int ssh::Channel::requestX11(bool single_connection, const char *protocol, const char *cookie, int screen_number)
References channel, ssh_channel_request_x11, ssh_throw.
void_throwable ssh::Channel::sendEof()
References channel, return_throwable, ssh_channel_send_eof, ssh_throw.
int ssh::Channel::write(const void *data, size_t len, bool is_stderr=false)
Writes on a channel.
data data to write. len number of bytes to write. is_stderr write should be done on the stderr channel (server only) number of bytes written SshException in case of error channel_write channel_write_stderr
References channel, ssh_channel_write, ssh_channel_write_stderr, ssh_throw.
ssh_session ssh::Channel::getCSession()
References ssh::Session::getCSession, session.
Referenced by acceptX11.
ssh_channel ssh::Channel::getCChannel()
References channel.
ssh::Channel::Channel(Session &ssh_session, ssh_channel c_channel)
ssh::Channel::Channel(const Channel &)
Channel& ssh::Channel::operator=(const Channel &)