config_parser.h
char* ssh_config_get_cmd(char **str)
Referenced by ssh_config_parse_line, torture_config_parser_get_cmd.
char* ssh_config_get_token(char **str)
Referenced by ssh_bind_config_parse_line, ssh_config_get_long, ssh_config_get_str_tok, ssh_config_parse_line, torture_config_parser_get_token.
long ssh_config_get_long(char **str, long notfound)
References ssh_config_get_token.
Referenced by ssh_config_parse_line.
const char* ssh_config_get_str_tok(char **str, const char *def)
References ssh_config_get_token.
Referenced by ssh_bind_config_parse_line, ssh_config_get_yesno, ssh_config_parse_line.
int ssh_config_get_yesno(char **str, int notfound)
References ssh_config_get_str_tok.
Referenced by ssh_config_parse_line.
int ssh_config_parse_uri(const char *tok, char **username, char **hostname, char **port)
References error, port, SAFE_FREE, SSH_ERROR, SSH_LOG, SSH_LOG_WARN, SSH_OK, strndup, username.
Referenced by ssh_config_parse_proxy_jump.