connect.c
static int ssh_connect_socket_close(socket_t s)
References s.
Referenced by ssh_connect_host_nonblocking.
static int getai(const char *host, int port, struct addrinfo **ai)
References host, port, ssh_is_ipaddr, SSH_LOG, SSH_LOG_PACKET, ZERO_STRUCT.
Referenced by ssh_connect_host_nonblocking.
static int set_tcp_nodelay(socket_t socket)
Referenced by ssh_connect_host_nonblocking.
socket_t ssh_connect_host_nonblocking(ssh_session session, const char *host, const char *bind_addr, int port)
References getai, host, ssh_session_struct::nodelay, ssh_session_struct::opts, port, rc, s, session, set_tcp_nodelay, ssh_connect_socket_close, SSH_FATAL, SSH_LOG, SSH_LOG_PACKET, ssh_set_error, ssh_socket_set_nonblocking.
Referenced by ssh_socket_connect.
static int ssh_select_cb(socket_t fd, int revents, void *userdata)
References POLLIN, set.
Referenced by ssh_select.
int ssh_select(ssh_channel *channels, ssh_channel *outchannels, socket_t maxfd, fd_set *readfds, struct timeval *timeout)
A wrapper for the select syscall.
This functions acts more or less like the select(2) syscall. There is no support for writing or exceptions. channels Arrays of channels pointers terminated by a NULL. It is never rewritten. outchannels Arrays of same size that "channels", there is no need to initialize it. maxfd Maximum +1 file descriptor from readfds. readfds A fd_set of file descriptors to be select'ed for reading. timeout The timeout in milliseconds. SSH_OK on success, SSH_ERROR on error, SSH_EINTR if it was interrupted. In that case, just restart it. libssh is not reentrant here. That means that if a signal is caught during the processing of this function, you cannot call libssh functions on sessions that are busy with ssh_select(). select(2)
References POLLIN, rc, session, ssh_channel_poll, SSH_ERROR, ssh_event_add_fd, ssh_event_add_session, ssh_event_dopoll, ssh_event_free, ssh_event_new, ssh_event_remove_fd, SSH_OK, ssh_select_cb, ssh_timeout_elapsed, ssh_timeout_update, ssh_timestamp_init, ZERO_STRUCT.
Referenced by select_loop, torture_channel_select.