curve25519_ref.c
const unsigned char base[32][32]
Referenced by crypto_scalarmult_base.
const unsigned int minusp[32][32]
Referenced by freeze.
int crypto_scalarmult_base(unsigned char *q, const unsigned char *n)
References base, crypto_scalarmult.
static void add(unsigned int out[32], const unsigned int a[32], const unsigned int b[32])
References generate.a.
Referenced by freeze, mainloop.
static void sub(unsigned int out[32], const unsigned int a[32], const unsigned int b[32])
References generate.a.
Referenced by mainloop, match_pattern_list.
static void squeeze(unsigned int a[32])
References generate.a.
Referenced by mult, square.
static void freeze(unsigned int a[32])
References generate.a, add, minusp, negative.
Referenced by crypto_scalarmult.
static void mult(unsigned int out[32], const unsigned int a[32], const unsigned int b[32])
References generate.a, squeeze.
Referenced by crypto_scalarmult, mainloop, recip.
static void mult121665(unsigned int out[32], const unsigned int a[32])
References generate.a.
Referenced by mainloop.
static void square(unsigned int out[32], const unsigned int a[32])
References generate.a, squeeze.
Referenced by mainloop, recip.
static void c_select(unsigned int p[64], unsigned int q[64], const unsigned int r[64], const unsigned int s[64], unsigned int b)
References s.
Referenced by mainloop.
static void mainloop(unsigned int work[64], const unsigned char e[32])
References add, c_select, mult, mult121665, s, square, sub.
Referenced by crypto_scalarmult.
static void recip(unsigned int out[32], const unsigned int z[32])
References mult, square.
Referenced by crypto_scalarmult.
int crypto_scalarmult(unsigned char *q, const unsigned char *n, const unsigned char *p)
References freeze, mainloop, mult, recip.
Referenced by crypto_scalarmult_base.