default_cb.c
int auth_pubkey_cb(UNUSED_PARAM(ssh_session session), const char *user, UNUSED_PARAM(struct ssh_key_struct *pubkey), char signature_state, void *userdata)
References session_data_st::auth_attempts, session_data_st::authenticated, SSH_AUTH_DENIED, SSH_AUTH_SUCCESS, SSH_PUBLICKEY_STATE_NONE, SSH_PUBLICKEY_STATE_VALID, user.
Referenced by get_default_server_cb.
int auth_password_cb(UNUSED_PARAM(ssh_session session), const char *user, const char *password, void *userdata)
References session_data_st::auth_attempts, session_data_st::authenticated, session_data_st::password, SSH_AUTH_DENIED, SSH_AUTH_SUCCESS, user, session_data_st::username.
Referenced by get_default_server_cb.
int channel_data_cb(UNUSED_PARAM(ssh_session session), UNUSED_PARAM(ssh_channel channel), void *data, uint32_t len, UNUSED_PARAM(int is_stderr), void *userdata)
References channel_data_st::child_stdin, channel_data_st::pid, rc, SSH_ERROR, SSH_OK.
Referenced by get_default_channel_cb.
void channel_eof_cb(UNUSED_PARAM(ssh_session session), UNUSED_PARAM(ssh_channel channel), void *userdata)
void channel_close_cb(UNUSED_PARAM(ssh_session session), UNUSED_PARAM(ssh_channel channel), void *userdata)
void channel_signal_cb(UNUSED_PARAM(ssh_session session), UNUSED_PARAM(ssh_channel channel), UNUSED_PARAM(const char *signal), void *userdata)
void channel_exit_status_cb(UNUSED_PARAM(ssh_session session), UNUSED_PARAM(ssh_channel channel), UNUSED_PARAM(int exit_status), void *userdata)
void channel_exit_signal_cb(UNUSED_PARAM(ssh_session session), UNUSED_PARAM(ssh_channel channel), UNUSED_PARAM(const char *signal), UNUSED_PARAM(int core), UNUSED_PARAM(const char *errmsg), UNUSED_PARAM(const char *lang), void *userdata)
int channel_pty_request_cb(UNUSED_PARAM(ssh_session session), UNUSED_PARAM(ssh_channel channel), UNUSED_PARAM(const char *term), int cols, int rows, int py, int px, void *userdata)
References channel_data_st::pty_master, channel_data_st::pty_slave, rc, SSH_ERROR, SSH_OK, channel_data_st::winsize.
Referenced by get_default_channel_cb.
int channel_pty_resize_cb(ssh_session session, ssh_channel channel, int cols, int rows, int py, int px, void *userdata)
References channel_data_st::pty_master, rc, session, SSH_ERROR, channel_data_st::winsize.
Referenced by get_default_channel_cb.
void channel_auth_agent_req_callback(UNUSED_PARAM(ssh_session session), UNUSED_PARAM(ssh_channel channel), UNUSED_PARAM(void *userdata))
void channel_x11_req_callback(UNUSED_PARAM(ssh_session session), UNUSED_PARAM(ssh_channel channel), UNUSED_PARAM(int single_connection), UNUSED_PARAM(const char *auth_protocol), UNUSED_PARAM(const char *auth_cookie), UNUSED_PARAM(uint32_t screen_number), UNUSED_PARAM(void *userdata))
static int exec_pty(const char *mode, const char *command, struct channel_data_st *cdata)
References channel_data_st::child_stdin, channel_data_st::child_stdout, channel_data_st::pid, channel_data_st::pty_master, channel_data_st::pty_slave, rc, SSH_ERROR, SSH_OK.
Referenced by channel_exec_request_cb, channel_shell_request_cb.
static int exec_nopty(const char *command, struct channel_data_st *cdata)
References channel_data_st::child_stderr, channel_data_st::child_stdin, channel_data_st::child_stdout, channel_data_st::pid, SSH_ERROR, SSH_OK.
Referenced by channel_exec_request_cb.
int channel_shell_request_cb(UNUSED_PARAM(ssh_session session), UNUSED_PARAM(ssh_channel channel), void *userdata)
References exec_pty, channel_data_st::pid, channel_data_st::pty_master, channel_data_st::pty_slave, rc, SSH_ERROR, SSH_OK.
Referenced by get_default_channel_cb.
int channel_exec_request_cb(UNUSED_PARAM(ssh_session session), UNUSED_PARAM(ssh_channel channel), const char *command, void *userdata)
References exec_nopty, exec_pty, channel_data_st::pid, channel_data_st::pty_master, channel_data_st::pty_slave, rc, SSH_ERROR.
Referenced by channel_subsystem_request_cb, get_default_channel_cb.
int channel_env_request_cb(UNUSED_PARAM(ssh_session session), UNUSED_PARAM(ssh_channel channel), UNUSED_PARAM(const char *env_name), UNUSED_PARAM(const char *env_value), void *userdata)
References rc, SSH_ERROR, SSH_OK.
Referenced by get_default_channel_cb.
int channel_subsystem_request_cb(ssh_session session, ssh_channel channel, const char *subsystem, void *userdata)
References channel_exec_request_cb, rc, session, SFTP_SERVER_PATH, SSH_ERROR.
Referenced by get_default_channel_cb.
int channel_write_wontblock_cb(UNUSED_PARAM(ssh_session session), UNUSED_PARAM(ssh_channel channel), UNUSED_PARAM(size_t bytes), UNUSED_PARAM(void *userdata))
ssh_channel channel_new_session_cb(ssh_session session, void *userdata)
References chan, session_data_st::channel, session, ssh_channel_new, ssh_get_error.
Referenced by get_default_server_cb.
static int process_stdout(socket_t fd, int revents, void *userdata)
References BUF_SIZE, session_data_st::channel, POLLIN, ssh_channel_write.
Referenced by default_handle_session_cb.
static int process_stderr(socket_t fd, int revents, void *userdata)
References BUF_SIZE, session_data_st::channel, POLLIN, ssh_channel_write_stderr.
Referenced by default_handle_session_cb.
struct ssh_server_callbacks_struct* get_default_server_cb(void)
References auth_password_cb, auth_pubkey_cb, cb, channel_new_session_cb.
Referenced by default_handle_session_cb, handle_kbdint_session_cb.
struct ssh_channel_callbacks_struct* get_default_channel_cb(void)
References cb, channel_data_cb, channel_env_request_cb, channel_exec_request_cb, channel_pty_request_cb, channel_pty_resize_cb, channel_shell_request_cb, channel_subsystem_request_cb.
Referenced by default_handle_session_cb, handle_kbdint_session_cb.
void default_handle_session_cb(ssh_event event, ssh_session session, struct server_state_st *state)
References session_data_st::auth_attempts, server_state_st::auth_methods, session_data_st::authenticated, session_data_st::channel, channel_cb, server_state_st::channel_cb, channel_data_st::child_stderr, channel_data_st::child_stdin, channel_data_st::child_stdout, cleanup_pcap, channel_data_st::event, server_state_st::expected_password, server_state_st::expected_username, get_default_channel_cb, get_default_server_cb, server_state_st::max_tries, session_data_st::password, server_state_st::pcap_file, channel_data_st::pid, POLLIN, process_stderr, process_stdout, channel_data_st::pty_master, rc, server_state_st::server_cb, channel_data_st::server_state, session_data_st::server_state, session, SESSION_END, set_pcap, SSH_AUTH_METHOD_PASSWORD, SSH_AUTH_METHOD_PUBLICKEY, ssh_callbacks_init, ssh_channel_close, ssh_channel_is_open, ssh_channel_request_send_exit_status, ssh_channel_send_eof, SSH_ERROR, ssh_event_add_fd, ssh_event_add_session, ssh_event_dopoll, ssh_event_remove_fd, ssh_get_error, ssh_get_status, ssh_handle_key_exchange, SSH_OK, ssh_set_auth_methods, ssh_set_channel_callbacks, ssh_set_server_callbacks, SSHD_DEFAULT_PASSWORD, SSHD_DEFAULT_USER, ssh_server_callbacks_struct::userdata, ssh_channel_callbacks_struct::userdata, session_data_st::username.
Referenced by setup_default_server, setup_server_state.