dh_crypto.c
bignum ssh_dh_generator
Referenced by ssh_dh_init_common.
bignum ssh_dh_group1
Referenced by ssh_dh_init_common.
bignum ssh_dh_group14
Referenced by ssh_dh_init_common.
bignum ssh_dh_group16
Referenced by ssh_dh_init_common.
bignum ssh_dh_group18
Referenced by ssh_dh_init_common.
void ssh_dh_debug_crypto(struct ssh_crypto_struct *c)
int ssh_dh_keypair_get_keys(struct dh_ctx *ctx, int peer, const_bignum *priv, const_bignum *pub)
Referenced by ssh_dh_compute_shared_secret, ssh_dh_debug_crypto.
int ssh_dh_keypair_set_keys(struct dh_ctx *ctx, int peer, const bignum priv, const bignum pub)
int ssh_dh_get_parameters(struct dh_ctx *ctx, const_bignum *modulus, const_bignum *generator)
int ssh_dh_set_parameters(struct dh_ctx *ctx, const bignum modulus, const bignum generator)
Referenced by ssh_dh_init_common.
int ssh_dh_init_common(struct ssh_crypto_struct *crypto)
void ssh_dh_cleanup(struct ssh_crypto_struct *crypto)
Referenced by ssh_dh_init_common.
int ssh_dh_keypair_gen_keys(struct dh_ctx *dh_ctx, int peer)
int ssh_dh_compute_shared_secret(struct dh_ctx *dh_ctx, int local, int remote, bignum *dest)