dh_key.c
DH_SECURITY_BITS
bignum ssh_dh_generator
Referenced by ssh_dh_finalize, ssh_dh_free_generator, ssh_dh_init, ssh_dh_init_common, ssh_dh_is_known_group.
bignum ssh_dh_group1
Referenced by ssh_dh_finalize, ssh_dh_free_modulus, ssh_dh_init, ssh_dh_init_common.
bignum ssh_dh_group14
Referenced by ssh_dh_finalize, ssh_dh_free_modulus, ssh_dh_init, ssh_dh_init_common, ssh_dh_is_known_group.
bignum ssh_dh_group16
Referenced by ssh_dh_finalize, ssh_dh_free_modulus, ssh_dh_init, ssh_dh_init_common, ssh_dh_is_known_group.
bignum ssh_dh_group18
Referenced by ssh_dh_finalize, ssh_dh_free_modulus, ssh_dh_init, ssh_dh_init_common, ssh_dh_is_known_group.
void ssh_dh_debug_crypto(struct ssh_crypto_struct *c)
References ssh_crypto_struct::client_kex, ssh_kex_struct::cookie, DH_CLIENT_KEYPAIR, ssh_crypto_struct::dh_ctx, DH_SERVER_KEYPAIR, dh_ctx::generator, dh_ctx::modulus, ssh_crypto_struct::server_kex, ssh_crypto_struct::shared_secret, ssh_dh_keypair_get_keys, ssh_log_hexdump, ssh_print_bignum.
Referenced by SSH_PACKET_CALLBACK.
static void ssh_dh_free_modulus(struct dh_ctx *ctx)
References ctx, ssh_dh_group1, ssh_dh_group14, ssh_dh_group16, ssh_dh_group18.
Referenced by ssh_dh_cleanup, ssh_dh_set_parameters.
static void ssh_dh_free_generator(struct dh_ctx *ctx)
References ctx, ssh_dh_generator.
Referenced by ssh_dh_cleanup, ssh_dh_set_parameters.
static void ssh_dh_free_dh_keypair(struct dh_keypair *keypair)
References dh_keypair::priv_key, dh_keypair::pub_key.
Referenced by ssh_dh_cleanup, ssh_dh_init_dh_keypair, ssh_dh_set_parameters.
static int ssh_dh_init_dh_keypair(struct dh_keypair *keypair)
References dh_keypair::priv_key, dh_keypair::pub_key, rc, ssh_dh_free_dh_keypair, SSH_ERROR, SSH_OK.
Referenced by ssh_dh_set_parameters.
int ssh_dh_keypair_get_keys(struct dh_ctx *ctx, int peer, const_bignum *priv, const_bignum *pub)
References ctx, DH_CLIENT_KEYPAIR, DH_get0_key, DH_SERVER_KEYPAIR, SSH_ERROR, SSH_OK.
Referenced by ssh_client_dh_init, ssh_dh_debug_crypto, ssh_make_sessionid, SSH_PACKET_CALLBACK.
int ssh_dh_keypair_set_keys(struct dh_ctx *ctx, int peer, bignum priv, bignum pub)
References ctx, DH_CLIENT_KEYPAIR, DH_SERVER_KEYPAIR, DH_set0_key, SSH_ERROR, SSH_OK.
Referenced by SSH_PACKET_CALLBACK.
int ssh_dh_get_parameters(struct dh_ctx *ctx, const_bignum *modulus, const_bignum *generator)
References ctx, DH_get0_pqg, SSH_ERROR, SSH_OK.
Referenced by ssh_make_sessionid.
int ssh_dh_set_parameters(struct dh_ctx *ctx, bignum modulus, bignum generator)
References ctx, DH_CLIENT_KEYPAIR, DH_SERVER_KEYPAIR, DH_set0_pqg, rc, ssh_dh_free_dh_keypair, ssh_dh_free_generator, ssh_dh_free_modulus, ssh_dh_init_dh_keypair, SSH_ERROR, SSH_OK.
Referenced by ssh_dh_init_common, SSH_PACKET_CALLBACK.
int ssh_dh_init_common(struct ssh_crypto_struct *crypto)
References ctx, ssh_crypto_struct::dh_ctx, ssh_crypto_struct::kex_type, rc, ssh_dh_cleanup, ssh_dh_generator, ssh_dh_group1, ssh_dh_group14, ssh_dh_group16, ssh_dh_group18, ssh_dh_set_parameters, SSH_ERROR, SSH_KEX_DH_GROUP14_SHA1, SSH_KEX_DH_GROUP16_SHA512, SSH_KEX_DH_GROUP18_SHA512, SSH_KEX_DH_GROUP1_SHA1, SSH_OK.
Referenced by ssh_client_dh_init, ssh_client_dhgex_init.
void ssh_dh_cleanup(struct ssh_crypto_struct *crypto)
References ctx, DH_CLIENT_KEYPAIR, ssh_crypto_struct::dh_ctx, DH_SERVER_KEYPAIR, dh_ctx::keypair, ssh_dh_free_dh_keypair, ssh_dh_free_generator, ssh_dh_free_modulus.
Referenced by crypto_free, ssh_client_dh_init, ssh_client_dhgex_init, ssh_dh_init_common, SSH_PACKET_CALLBACK.
int ssh_dh_keypair_gen_keys(struct dh_ctx *dh_ctx, int peer)
References bits, ctx, DH_SECURITY_BITS, error, dh_ctx::generator, dh_ctx::keypair, MIN, dh_ctx::modulus, rc, SSH_ERROR, SSH_OK.
Referenced by ssh_client_dh_init, SSH_PACKET_CALLBACK.
int ssh_dh_compute_shared_secret(struct dh_ctx *dh_ctx, int local, int remote, bignum *dest)
References ctx, dh_ctx::keypair, dh_ctx::modulus, rc, ssh_dh_keypair_get_keys, SSH_ERROR, SSH_OK.
Referenced by SSH_PACKET_CALLBACK.