ed25519.h
ED25519_PK_LEN
ED25519_SK_LEN
ED25519_SIG_LEN
typedef uint8_t ed25519_pubkey[ED25519_PK_LEN][ED25519_PK_LEN]
typedef uint8_t ed25519_privkey[ED25519_SK_LEN][ED25519_SK_LEN]
typedef uint8_t ed25519_signature[ED25519_SIG_LEN][ED25519_SIG_LEN]
int crypto_sign_ed25519_keypair(ed25519_pubkey pk, ed25519_privkey sk)
Referenced by pki_key_generate_ed25519.
int crypto_sign_ed25519(unsigned char *sm, uint64_t *smlen, const unsigned char *m, uint64_t mlen, const ed25519_privkey sk)
Referenced by pki_ed25519_sign.
int crypto_sign_ed25519_open(unsigned char *m, uint64_t *mlen, const unsigned char *sm, uint64_t smlen, const ed25519_pubkey pk)
Referenced by pki_ed25519_verify.