examples_common.h
ZERO_STRUCT
Zero a structure
int authenticate_console(ssh_session session)
References auth_keyfile, authenticate_kbdint, buffer, error, rc, session, SSH_AUTH_ERROR, SSH_AUTH_METHOD_GSSAPI_MIC, SSH_AUTH_METHOD_INTERACTIVE, SSH_AUTH_METHOD_PASSWORD, SSH_AUTH_METHOD_PUBLICKEY, SSH_AUTH_SUCCESS, ssh_get_issue_banner, ssh_getpass, SSH_STRING_FREE_CHAR, ssh_userauth_gssapi, ssh_userauth_list, ssh_userauth_none, ssh_userauth_password, ssh_userauth_publickey_auto.
Referenced by client, connect_ssh.
int authenticate_kbdint(ssh_session session, const char *password)
References buffer, echo, instruction, name, session, SSH_AUTH_ERROR, SSH_AUTH_INFO, ssh_getpass, ssh_userauth_kbdint, ssh_userauth_kbdint_getinstruction, ssh_userauth_kbdint_getname, ssh_userauth_kbdint_getnprompts, ssh_userauth_kbdint_getprompt, ssh_userauth_kbdint_setanswer.
Referenced by authenticate_console.
int verify_knownhost(ssh_session session)
References FALL_THROUGH, rc, session, ssh_clean_pubkey_hash, ssh_get_error, ssh_get_publickey_hash, ssh_get_server_publickey, ssh_key_free, SSH_KNOWN_HOSTS_CHANGED, SSH_KNOWN_HOSTS_ERROR, SSH_KNOWN_HOSTS_NOT_FOUND, SSH_KNOWN_HOSTS_OK, SSH_KNOWN_HOSTS_OTHER, SSH_OK, ssh_print_hash, SSH_PUBLICKEY_HASH_SHA256, SSH_SERVER_NOT_KNOWN, ssh_session_is_known_server, ssh_session_update_known_hosts.
Referenced by client, connect_ssh.
ssh_session connect_ssh(const char *hostname, const char *user, int verbosity)
References authenticate_console, host, session, SSH_AUTH_DENIED, SSH_AUTH_SUCCESS, ssh_connect, ssh_disconnect, ssh_free, ssh_get_error, ssh_new, SSH_OPTIONS_HOST, SSH_OPTIONS_LOG_VERBOSITY, ssh_options_set, SSH_OPTIONS_USER, user, verbosity, verify_knownhost.
Referenced by main.