getpass.c
static int ssh_gets(const char *prompt, char *buf, size_t len, int verify)
References explicit_bzero, SAFE_FREE.
Referenced by ssh_getpass.
int ssh_getpass(const char *prompt, char *buf, size_t len, int echo, int verify)
Get a password from the console.
You should make sure that the buffer is an empty string! You can also use this function to ask for a username. Then you can fill the buffer with the username and it is shows to the users. If the users just presses enter the buffer will be untouched. charusername[128]; snprintf(username,sizeof(username),"john"); ssh_getpass("Username:",username,sizeof(username),1,0); The prompt will look like this: Username: [john] If you press enter then john is used as the username, or you can type it in to change it. prompt The prompt to show to ask for the password. buf The buffer the password should be stored. It NEEDS to be empty or filled out. len The length of the buffer. echo Should we echo what you type. verify Should we ask for the password twice. 0 on success, -1 on error.
References echo, explicit_bzero, ssh_gets, ZERO_STRUCT.
Referenced by auth_callback, authenticate_console, authenticate_kbdint.