gssapi.c
ssh_gssapi_state_e
static int ssh_gssapi_init(ssh_session session)
References ssh_gssapi_struct::client_creds, ssh_gssapi_struct::ctx, ssh_session_struct::gssapi, ssh_gssapi_struct::server_creds, session, SSH_ERROR, SSH_GSSAPI_STATE_NONE, SSH_OK, ssh_set_error_oom, ssh_gssapi_struct::state, ZERO_STRUCTP.
Referenced by ssh_gssapi_auth_mic, ssh_gssapi_set_creds.
static void ssh_gssapi_free(ssh_session session)
References ssh_gssapi_struct::client, ssh_gssapi_struct::client_deleg_creds, ssh_gssapi_struct::creds, ssh_session_struct::gssapi, ssh_gssapi_struct::mech, SAFE_FREE, ssh_gssapi_struct::server_creds, session, ssh_gssapi_struct::user.
Referenced by SSH_PACKET_CALLBACK.
SSH_PACKET_CALLBACK(ssh_packet_userauth_gssapi_token)
References ssh_session_struct::server, session, user.
static void ssh_gssapi_log_error(int verb, const char *msg, int maj_stat, int min_stat)
References SSH_LOG.
Referenced by ssh_gssapi_auth_mic, ssh_gssapi_send_mic, SSH_PACKET_CALLBACK.
static ssh_buffer ssh_gssapi_build_mic(ssh_session session)
References ssh_crypto_struct::digest_len, ssh_session_struct::gssapi, rc, session, ssh_crypto_struct::session_id, SSH2_MSG_USERAUTH_REQUEST, SSH_BUFFER_FREE, ssh_buffer_new, ssh_buffer_pack, SSH_DIRECTION_BOTH, SSH_OK, ssh_packet_get_current_crypto, ssh_set_error_oom, ssh_gssapi_struct::user.
Referenced by ssh_gssapi_send_mic.
void ssh_gssapi_set_creds(ssh_session session, const ssh_gssapi_creds creds)
Set the forwadable ticket to be given to the server for authentication. Unlike ssh_gssapi_get_creds() this is called on the client side of an ssh connection.
creds gssapi credentials handle.
References ssh_gssapi_struct::client, ssh_gssapi_struct::client_deleg_creds, ssh_session_struct::gssapi, session, ssh_gssapi_init.
Referenced by main.
static int ssh_gssapi_send_auth_mic(ssh_session session, ssh_string *oid_set, int n_oid)
References ssh_session_struct::auth, ssh_session_struct::opts, ssh_session_struct::out_buffer, rc, session, SSH2_MSG_USERAUTH_REQUEST, SSH_AUTH_STATE_GSSAPI_REQUEST_SENT, ssh_buffer_add_ssh_string, ssh_buffer_pack, ssh_buffer_reinit, SSH_ERROR, SSH_OK, ssh_packet_send, ssh_set_error_oom, ssh_session_struct::state, ssh_session_struct::username.
Referenced by ssh_gssapi_auth_mic.
static int ssh_gssapi_match(ssh_session session, gss_OID_set *valid_oids)
returns the OIDs of the mechs that have usable credentials
References ssh_gssapi_struct::client, ssh_gssapi_struct::client_deleg_creds, ssh_gssapi_struct::creds, ssh_session_struct::gss_client_identity, ssh_session_struct::gssapi, ssh_session_struct::opts, SAFE_FREE, session, SSH_ERROR, ssh_get_hexa, SSH_LOG, SSH_LOG_DEBUG, SSH_OK.
Referenced by ssh_gssapi_auth_mic.
int ssh_gssapi_auth_mic(ssh_session session)
launches a gssapi-with-mic auth request
SSH_AUTH_ERROR: A serious error happened SSH_AUTH_DENIED: Authentication failed : use another method SSH_AUTH_AGAIN: In nonblocking mode, you've got to call this again later.
References ssh_gssapi_struct::client, ssh_session_struct::gss_server_identity, ssh_session_struct::gssapi, ssh_session_struct::host, ssh_session_struct::opts, rc, ssh_gssapi_struct::server_name, session, SSH_AUTH_AGAIN, SSH_AUTH_DENIED, SSH_AUTH_ERROR, SSH_ERROR, ssh_gssapi_init, ssh_gssapi_log_error, ssh_gssapi_match, ssh_gssapi_send_auth_mic, SSH_LOG, SSH_LOG_PROTOCOL, SSH_LOG_WARNING, SSH_OID_TAG, ssh_set_error_oom, SSH_STRING_FREE, ssh_string_new, ssh_gssapi_struct::user, ssh_session_struct::username.
static gss_OID ssh_gssapi_oid_from_string(ssh_string oid_s)
References SAFE_FREE, SSH_OID_TAG, ssh_string_data, ssh_string_len.
Referenced by SSH_PACKET_CALLBACK.
SSH_PACKET_CALLBACK(ssh_packet_userauth_gssapi_response)
References ssh_session_struct::auth, ssh_gssapi_struct::client, ssh_gssapi_struct::creds, ssh_gssapi_struct::ctx, error, ssh_gssapi_struct::flags, ssh_session_struct::gss_delegate_creds, ssh_session_struct::gssapi, ssh_gssapi_struct::oid, ssh_session_struct::opts, ssh_session_struct::out_buffer, SAFE_FREE, ssh_gssapi_struct::server_name, session, SSH2_MSG_USERAUTH_GSSAPI_TOKEN, SSH_AUTH_STATE_ERROR, SSH_AUTH_STATE_GSSAPI_REQUEST_SENT, SSH_AUTH_STATE_GSSAPI_TOKEN, ssh_buffer_get_ssh_string, ssh_buffer_pack, SSH_FATAL, ssh_get_hexa, ssh_gssapi_free, ssh_gssapi_log_error, ssh_gssapi_oid_from_string, SSH_LOG, SSH_LOG_PACKET, SSH_LOG_WARNING, ssh_packet_send, SSH_PACKET_USED, ssh_set_error, SSH_STRING_FREE, ssh_session_struct::state, user.
static int ssh_gssapi_send_mic(ssh_session session)
References ssh_gssapi_struct::ctx, ssh_session_struct::gssapi, ssh_session_struct::out_buffer, rc, session, SSH2_MSG_USERAUTH_GSSAPI_MIC, SSH_BUFFER_FREE, ssh_buffer_get, ssh_buffer_get_len, ssh_buffer_pack, SSH_ERROR, ssh_gssapi_build_mic, ssh_gssapi_log_error, SSH_LOG, SSH_LOG_PACKET, SSH_LOG_PROTOCOL, SSH_OK, ssh_packet_send, ssh_set_error_oom.
SSH_PACKET_CALLBACK(ssh_packet_userauth_gssapi_token_client)