kex.h
SSH_KEX_METHODS
SSH_PACKET_CALLBACK(ssh_packet_kexinit)
References ssh_crypto_struct::client_kex, cmp_first_kex_algo, ssh_kex_struct::cookie, ssh_session_struct::dh_handshake_state, DH_STATE_INIT, error, ssh_session_struct::extensions, ssh_session_struct::first_kex_follows_guess_wrong, ssh_session_struct::in_hashbuf, KEX_EXTENSION_CLIENT, ssh_kex_struct::methods, ssh_session_struct::next_crypto, ssh_session_struct::opts, rc, SAFE_FREE, ssh_session_struct::server, ssh_crypto_struct::server_kex, session, ssh_session_struct::session_state, ssh_buffer_add_ssh_string, ssh_buffer_add_u32, ssh_buffer_add_u8, ssh_buffer_get_data, ssh_buffer_get_ssh_string, ssh_buffer_get_u8, ssh_session_struct::ssh_connection_callback, SSH_ERROR, SSH_EXT_NEGOTIATION, SSH_EXT_SIG_RSA_SHA256, SSH_EXT_SIG_RSA_SHA512, SSH_FATAL, ssh_find_matching, ssh_hashbufin_add_cookie, SSH_HOSTKEYS, SSH_KEX, SSH_KEX_METHODS, SSH_LOG, SSH_LOG_DEBUG, SSH_LOG_INFO, ssh_match_group, SSH_PACKET_USED, SSH_SESSION_STATE_AUTHENTICATED, SSH_SESSION_STATE_ERROR, SSH_SESSION_STATE_INITIAL_KEX, SSH_SESSION_STATE_KEXINIT_RECEIVED, ssh_set_error, ssh_set_error_oom, SSH_STRING_FREE, ssh_string_to_char, user, ssh_session_struct::wanted_methods.
int ssh_send_kex(ssh_session session, int server_kex)
References ssh_crypto_struct::client_kex, ssh_kex_struct::cookie, error, ssh_kex_struct::methods, ssh_session_struct::next_crypto, ssh_session_struct::out_buffer, ssh_session_struct::out_hashbuf, rc, ssh_crypto_struct::server_kex, session, SSH2_MSG_KEXINIT, ssh_buffer_add_ssh_string, ssh_buffer_pack, ssh_buffer_reinit, SSH_ERROR, ssh_hashbufout_add_cookie, SSH_KEX_METHODS, ssh_list_kex, SSH_LOG, SSH_LOG_PACKET, SSH_OK, ssh_packet_send, SSH_STRING_FREE, ssh_string_from_char.
Referenced by ssh_client_connection_callback, ssh_send_rekex, ssh_server_connection_callback.
void ssh_list_kex(struct ssh_kex_struct *kex)
References ssh_kex_struct::cookie, ssh_kex_struct::methods, ssh_kex_descriptions, SSH_KEX_METHODS, SSH_LOG, SSH_LOG_FUNCTIONS, ssh_log_hexdump.
Referenced by ssh_client_connection_callback, ssh_send_kex, ssh_server_connection_callback.
int ssh_set_client_kex(ssh_session session)
sets the key exchange parameters to be sent to the server, in function of the options and available methods.
References client, ssh_crypto_struct::client_kex, default_methods, fips_methods, ssh_session_struct::flags, KEX_EXTENSION_CLIENT, ssh_session_struct::next_crypto, ssh_session_struct::opts, session, ssh_client_select_hostkeys, SSH_ERROR, SSH_FATAL, ssh_get_random, SSH_HOSTKEYS, SSH_KEX, SSH_KEX_METHODS, SSH_OK, SSH_SESSION_FLAG_AUTHENTICATED, ssh_set_error, ssh_set_error_oom, ssh_session_struct::wanted_methods.
Referenced by ssh_client_connection_callback, ssh_send_rekex.
int ssh_kex_select_methods(ssh_session session)
Select the different methods on basis of client's and server's kex messages, and watches out if a match is possible.
References client, ssh_crypto_struct::client_kex, KEX_EXTENSION_CLIENT, ssh_crypto_struct::kex_methods, ssh_crypto_struct::kex_type, ssh_kex_struct::methods, ssh_session_struct::next_crypto, ssh_crypto_struct::server_kex, session, SSH_COMP_C_S, SSH_COMP_S_C, SSH_CRYPT_C_S, SSH_CRYPT_S_C, SSH_ERROR, SSH_FATAL, ssh_find_matching, SSH_HOSTKEYS, SSH_KEX, SSH_KEX_CURVE25519_SHA256, SSH_KEX_CURVE25519_SHA256_LIBSSH_ORG, ssh_kex_descriptions, SSH_KEX_DH_GROUP14_SHA1, SSH_KEX_DH_GROUP16_SHA512, SSH_KEX_DH_GROUP18_SHA512, SSH_KEX_DH_GROUP1_SHA1, SSH_KEX_ECDH_SHA2_NISTP256, SSH_KEX_ECDH_SHA2_NISTP384, SSH_KEX_ECDH_SHA2_NISTP521, SSH_KEX_METHODS, SSH_LANG_C_S, SSH_LANG_S_C, SSH_LOG, SSH_LOG_INFO, SSH_MAC_C_S, SSH_MAC_S_C, SSH_OK, ssh_set_error.
Referenced by ssh_client_connection_callback, ssh_server_connection_callback.
int ssh_verify_existing_algo(enum ssh_kex_types_e algo, const char *name)
char* ssh_keep_known_algos(enum ssh_kex_types_e algo, const char *list)
References ssh_find_all_matching, SSH_LANG_S_C, supported_methods.
Referenced by ssh_options_set, ssh_options_set_algo.
char* ssh_keep_fips_algos(enum ssh_kex_types_e algo, const char *list)
References fips_methods, ssh_find_all_matching, SSH_LANG_S_C.
Referenced by assert_full_bind_config, ssh_client_select_hostkeys, ssh_options_set, ssh_options_set_algo, torture_bind_config_ciphers, torture_bind_config_hostkey_algorithms, torture_bind_config_kexalgorithms, torture_bind_config_pubkey_accepted, torture_client_config_emulate, torture_client_config_system, torture_config_from_file, torture_config_pubkeyacceptedkeytypes.
char** ssh_space_tokenize(const char *chain)
int ssh_get_kex1(ssh_session session)
char* ssh_find_matching(const char *in_d, const char *what_d)
References ssh_tokenize, ssh_tokens_free, ssh_tokens_st::tokens.
Referenced by ssh_kex_select_methods, SSH_PACKET_CALLBACK, torture_find_matching.
const char* ssh_kex_get_supported_method(uint32_t algo)
References SSH_KEX_METHODS, supported_methods.
Referenced by pkd_exec_hello.
const char* ssh_kex_get_default_methods(uint32_t algo)
References default_methods, SSH_KEX_METHODS.
Referenced by pkd_exec_hello, server_set_kex, ssh_client_select_hostkeys, ssh_key_algorithm_allowed, ssh_server_send_extensions, torture_server_config_ciphers, torture_server_config_hostkey_algorithms, torture_server_config_kex, torture_server_config_macs.
const char* ssh_kex_get_fips_methods(uint32_t algo)
References fips_methods, SSH_KEX_METHODS.
Referenced by server_set_kex, ssh_client_select_hostkeys, ssh_key_algorithm_allowed, ssh_server_send_extensions, torture_server_config_ciphers, torture_server_config_hostkey_algorithms, torture_server_config_kex, torture_server_config_macs.
const char* ssh_kex_get_description(uint32_t algo)
References ssh_kex_descriptions, SSH_KEX_METHODS.
Referenced by ssh_options_set_algo.
char* ssh_client_select_hostkeys(ssh_session session)
References HOSTKEYS, ssh_session_struct::opts, SAFE_FREE, session, ssh_append_without_duplicates, ssh_find_all_matching, SSH_HOSTKEYS, ssh_keep_fips_algos, ssh_kex_get_default_methods, ssh_kex_get_fips_methods, ssh_known_hosts_get_algorithms_names, SSH_LOG, SSH_LOG_DEBUG, SSH_LOG_WARNING, ssh_set_error_oom, ssh_session_struct::wanted_methods.
Referenced by ssh_set_client_kex, torture_knownhosts_algorithms, torture_knownhosts_algorithms_global, torture_knownhosts_algorithms_negative, torture_knownhosts_algorithms_wanted.
int ssh_send_rekex(ssh_session session)
References ssh_session_struct::client, ssh_session_struct::current_crypto, ssh_session_struct::dh_handshake_state, DH_STATE_FINISHED, DH_STATE_INIT, DH_STATE_INIT_SENT, rc, ssh_session_struct::server, server_set_kex, session, SSH_ERROR, SSH_LOG, SSH_LOG_PACKET, SSH_OK, ssh_send_kex, ssh_set_client_kex.
Referenced by ssh_packet_send, ssh_packet_socket_callback.
int server_set_kex(ssh_session session)
References ssh_kex_struct::cookie, ssh_session_struct::dsa_key, ssh_session_struct::ecdsa_key, ssh_session_struct::ed25519_key, ssh_kex_struct::methods, ssh_session_struct::next_crypto, ssh_session_struct::opts, rc, ssh_session_struct::rsa_key, SAFE_FREE, ssh_crypto_struct::server_kex, session, ssh_session_struct::srv, SSH_FATAL, ssh_find_all_matching, ssh_get_random, SSH_HOSTKEYS, ssh_kex_get_default_methods, ssh_kex_get_fips_methods, SSH_KEX_METHODS, ssh_key_type, ssh_key_type_to_char, ssh_options_set_algo, ssh_set_error, ssh_key_struct::type_c, ssh_session_struct::wanted_methods, ZERO_STRUCTP.
Referenced by ssh_handle_key_exchange, ssh_send_rekex, ssh_server_connection_callback, ssh_server_init_kex.
int ssh_make_sessionid(ssh_session session)
References ssh_session_struct::client, ssh_session_struct::clientbanner, CURVE25519_PUBKEY_SIZE, DH_CLIENT_KEYPAIR, ssh_crypto_struct::dh_ctx, DH_SERVER_KEYPAIR, ssh_crypto_struct::digest_len, ssh_crypto_struct::digest_type, error, ssh_session_struct::in_hashbuf, ssh_crypto_struct::kex_type, ssh_session_struct::next_crypto, ssh_session_struct::out_hashbuf, rc, ssh_crypto_struct::secret_hash, ssh_session_struct::serverbanner, session, ssh_crypto_struct::session_id, sha1, sha256, sha384, sha512, SHA512_DIGEST_LENGTH, ssh_crypto_struct::shared_secret, ssh_buffer_add_u32, ssh_buffer_add_u8, SSH_BUFFER_FREE, ssh_buffer_get, ssh_buffer_get_len, ssh_buffer_new, ssh_buffer_pack, ssh_dh_get_next_server_publickey_blob, ssh_dh_get_parameters, ssh_dh_keypair_get_keys, SSH_ERROR, SSH_KDF_SHA1, SSH_KDF_SHA256, SSH_KDF_SHA384, SSH_KDF_SHA512, SSH_KEX_CURVE25519_SHA256, SSH_KEX_CURVE25519_SHA256_LIBSSH_ORG, SSH_KEX_DH_GROUP14_SHA1, SSH_KEX_DH_GROUP16_SHA512, SSH_KEX_DH_GROUP18_SHA512, SSH_KEX_DH_GROUP1_SHA1, SSH_KEX_ECDH_SHA2_NISTP256, SSH_KEX_ECDH_SHA2_NISTP384, SSH_KEX_ECDH_SHA2_NISTP521, SSH_LOG, ssh_log_hexdump, SSH_LOG_WARNING, SSH_OK, ssh_set_error_oom, SSH_STRING_FREE.
Referenced by ssh_packet_set_newkeys.
int ssh_hashbufin_add_cookie(ssh_session session, unsigned char *cookie)
References ssh_kex_struct::cookie, ssh_session_struct::in_hashbuf, rc, session, ssh_buffer_add_data, ssh_buffer_add_u8, ssh_buffer_allocate_size, ssh_buffer_new, ssh_buffer_reinit.
Referenced by SSH_PACKET_CALLBACK.
int ssh_hashbufout_add_cookie(ssh_session session)
References ssh_crypto_struct::client_kex, ssh_kex_struct::cookie, ssh_session_struct::next_crypto, ssh_session_struct::out_hashbuf, rc, ssh_session_struct::server, ssh_crypto_struct::server_kex, session, ssh_buffer_add_data, ssh_buffer_add_u8, ssh_buffer_allocate_size, ssh_buffer_new, ssh_buffer_reinit.
Referenced by ssh_send_kex.
int ssh_generate_session_keys(ssh_session session)
References ssh_session_struct::client, ssh_crypto_struct::decryptIV, ssh_crypto_struct::decryptkey, ssh_crypto_struct::decryptMAC, ssh_crypto_struct::digest_len, ssh_crypto_struct::encryptIV, ssh_crypto_struct::encryptkey, ssh_crypto_struct::encryptMAC, error, hmac_digest_len, ssh_crypto_struct::in_cipher, key, ssh_cipher_struct::keysize, ssh_session_struct::next_crypto, ssh_crypto_struct::out_cipher, ssh_crypto_struct::out_hmac, rc, session, ssh_crypto_struct::shared_secret, ssh_kdf, ssh_log_hexdump, ssh_make_bignum_string, ssh_set_error_oom, ssh_string_burn, SSH_STRING_FREE, ssh_string_len.
Referenced by ssh_packet_set_newkeys, torture_session_keys.