legacy.h
typedef struct ssh_private_key_struct* ssh_private_key
typedef struct ssh_public_key_struct* ssh_public_key
LIBSSH_API int ssh_auth_list(ssh_session session)
functions in that file are wrappers to the newly named functions. All of them are depreciated, but these wrapper will avoid breaking backward compatibility
References session, ssh_userauth_list.
LIBSSH_API int ssh_userauth_offer_pubkey(ssh_session session, const char *username, int type, ssh_string publickey)
References key, rc, session, SSH_AUTH_ERROR, SSH_FATAL, ssh_key_free, ssh_pki_import_pubkey_blob, ssh_set_error, ssh_userauth_try_publickey, username.
LIBSSH_API int ssh_userauth_pubkey(ssh_session session, const char *username, ssh_string publickey, ssh_private_key privatekey)
References key, rc, session, SSH_AUTH_ERROR, SSH_KEY_FLAG_PRIVATE, SSH_KEY_FLAG_PUBLIC, ssh_key_free, ssh_key_new, ssh_key_type_to_char, ssh_userauth_publickey, ssh_private_key_struct::type, username.
Referenced by ssh_userauth_privatekey_file.
LIBSSH_API int ssh_userauth_agent_pubkey(ssh_session session, const char *username, ssh_public_key publickey)
References key, rc, session, SSH_AUTH_ERROR, SSH_KEY_FLAG_PUBLIC, ssh_key_free, ssh_key_new, ssh_key_type_to_char, ssh_userauth_agent_publickey, ssh_public_key_struct::type, username.
LIBSSH_API int ssh_userauth_autopubkey(ssh_session session, const char *passphrase)
References session, ssh_userauth_publickey_auto.
Referenced by authenticate, connect_host.
LIBSSH_API int ssh_userauth_privatekey_file(ssh_session session, const char *username, const char *filename, const char *passphrase)
References error, privatekey_free, privatekey_from_file, privkey, pubkey, publickey_from_file, rc, SAFE_FREE, session, SSH_AUTH_ERROR, SSH_LOG, SSH_LOG_RARE, ssh_set_error_oom, ssh_string_free, ssh_userauth_pubkey, username.
SSH_DEPRECATED LIBSSH_API void buffer_free(ssh_buffer buffer)
References buffer, ssh_buffer_free.
SSH_DEPRECATED LIBSSH_API void* buffer_get(ssh_buffer buffer)
References buffer, ssh_buffer_get.
SSH_DEPRECATED LIBSSH_API uint32_t buffer_get_len(ssh_buffer buffer)
References buffer, ssh_buffer_get_len.
SSH_DEPRECATED LIBSSH_API ssh_buffer buffer_new(void)
References ssh_buffer_new.
SSH_DEPRECATED LIBSSH_API ssh_channel channel_accept_x11(ssh_channel channel, int timeout_ms)
References ssh_channel_accept_x11.
SSH_DEPRECATED LIBSSH_API int channel_change_pty_size(ssh_channel channel, int cols, int rows)
References ssh_channel_change_pty_size.
SSH_DEPRECATED LIBSSH_API ssh_channel channel_forward_accept(ssh_session session, int timeout_ms)
References session, ssh_channel_accept_forward.
SSH_DEPRECATED LIBSSH_API int channel_close(ssh_channel channel)
References ssh_channel_close.
SSH_DEPRECATED LIBSSH_API int channel_forward_cancel(ssh_session session, const char *address, int port)
References port, session, ssh_channel_cancel_forward.
SSH_DEPRECATED LIBSSH_API int channel_forward_listen(ssh_session session, const char *address, int port, int *bound_port)
References port, session, ssh_channel_listen_forward.
SSH_DEPRECATED LIBSSH_API void channel_free(ssh_channel channel)
References ssh_channel_free.
SSH_DEPRECATED LIBSSH_API int channel_get_exit_status(ssh_channel channel)
References ssh_channel_get_exit_status.
SSH_DEPRECATED LIBSSH_API ssh_session channel_get_session(ssh_channel channel)
References ssh_channel_get_session.
SSH_DEPRECATED LIBSSH_API int channel_is_closed(ssh_channel channel)
References ssh_channel_is_closed.
SSH_DEPRECATED LIBSSH_API int channel_is_eof(ssh_channel channel)
References ssh_channel_is_eof.
SSH_DEPRECATED LIBSSH_API int channel_is_open(ssh_channel channel)
References ssh_channel_is_open.
SSH_DEPRECATED LIBSSH_API ssh_channel channel_new(ssh_session session)
References session, ssh_channel_new.
SSH_DEPRECATED LIBSSH_API int channel_open_forward(ssh_channel channel, const char *remotehost, int remoteport, const char *sourcehost, int localport)
References ssh_channel_open_forward.
SSH_DEPRECATED LIBSSH_API int channel_open_session(ssh_channel channel)
References ssh_channel_open_session.
SSH_DEPRECATED LIBSSH_API int channel_poll(ssh_channel channel, int is_stderr)
References ssh_channel_poll.
SSH_DEPRECATED LIBSSH_API int channel_read(ssh_channel channel, void *dest, uint32_t count, int is_stderr)
References ssh_channel_read.
SSH_DEPRECATED LIBSSH_API int channel_read_buffer(ssh_channel channel, ssh_buffer buffer, uint32_t count, int is_stderr)
Read data from a channel into a buffer.
channel The channel to read from. buffer The buffer which will get the data. count The count of bytes to be read. If it is bigger than 0, the exact size will be read, else (bytes=0) it will return once anything is available. is_stderr A boolean value to mark reading from the stderr stream. The number of bytes read, 0 on end of file or SSH_ERROR on error. DeprecatedPlease use ssh_channel_read instead This function doesn't work in nonblocking/timeout mode ssh_channel_read
References buffer, ssh_channel_struct::session, session, ssh_buffer_add_data, ssh_buffer_reinit, ssh_channel_is_eof, ssh_channel_poll, ssh_channel_read, SSH_ERROR, ssh_handle_packets, ssh_set_error_invalid, ssh_set_error_oom, SSH_TIMEOUT_INFINITE.
SSH_DEPRECATED LIBSSH_API int channel_read_nonblocking(ssh_channel channel, void *dest, uint32_t count, int is_stderr)
References ssh_channel_read_nonblocking.
SSH_DEPRECATED LIBSSH_API int channel_request_env(ssh_channel channel, const char *name, const char *value)
References name, ssh_channel_request_env.
SSH_DEPRECATED LIBSSH_API int channel_request_exec(ssh_channel channel, const char *cmd)
References ssh_channel_request_exec.
SSH_DEPRECATED LIBSSH_API int channel_request_pty(ssh_channel channel)
References ssh_channel_request_pty.
SSH_DEPRECATED LIBSSH_API int channel_request_pty_size(ssh_channel channel, const char *term, int cols, int rows)
References ssh_channel_request_pty_size.
SSH_DEPRECATED LIBSSH_API int channel_request_shell(ssh_channel channel)
References ssh_channel_request_shell.
SSH_DEPRECATED LIBSSH_API int channel_request_send_signal(ssh_channel channel, const char *signum)
References ssh_channel_request_send_signal.
SSH_DEPRECATED LIBSSH_API int channel_request_sftp(ssh_channel channel)
References ssh_channel_request_sftp.
SSH_DEPRECATED LIBSSH_API int channel_request_subsystem(ssh_channel channel, const char *subsystem)
References ssh_channel_request_subsystem.
SSH_DEPRECATED LIBSSH_API int channel_request_x11(ssh_channel channel, int single_connection, const char *protocol, const char *cookie, int screen_number)
References ssh_channel_request_x11.
SSH_DEPRECATED LIBSSH_API int channel_send_eof(ssh_channel channel)
References ssh_channel_send_eof.
SSH_DEPRECATED LIBSSH_API int channel_select(ssh_channel *readchans, ssh_channel *writechans, ssh_channel *exceptchans, struct timeval *timeout)
References ssh_channel_select.
SSH_DEPRECATED LIBSSH_API void channel_set_blocking(ssh_channel channel, int blocking)
References ssh_channel_set_blocking.
SSH_DEPRECATED LIBSSH_API int channel_write(ssh_channel channel, const void *data, uint32_t len)
References ssh_channel_write.
LIBSSH_API void privatekey_free(ssh_private_key prv)
References SAFE_FREE.
Referenced by ssh_userauth_privatekey_file, torture_privatekey_from_file, torture_privatekey_from_file_passphrase, torture_pubkey_generate_from_privkey.
LIBSSH_API ssh_private_key privatekey_from_file(ssh_session session, const char *filename, int type, const char *passphrase)
References ssh_callbacks_struct::auth_function, ssh_common_struct::callbacks, ssh_session_struct::common, key, privkey, rc, session, SSH_ERROR, ssh_key_free, ssh_pki_import_privkey_file, ssh_public_key_struct::type, ssh_callbacks_struct::userdata.
Referenced by ssh_userauth_privatekey_file, torture_privatekey_from_file, torture_privatekey_from_file_passphrase, torture_pubkey_generate_from_privkey.
LIBSSH_API void publickey_free(ssh_public_key key)
References key, SAFE_FREE, SSH_KEYTYPE_DSS, SSH_KEYTYPE_RSA.
Referenced by torture_pubkey_generate_from_privkey.
LIBSSH_API int ssh_publickey_to_file(ssh_session session, const char *file, ssh_string pubkey, int type)
References bin_to_base64, buffer, host, pubkey, rc, SAFE_FREE, session, SSH_ERROR, SSH_FATAL, ssh_get_local_username, SSH_LOG, SSH_LOG_PACKET, SSH_LOG_RARE, SSH_OK, SSH_REQUEST_DENIED, ssh_set_error, ssh_string_data, ssh_string_len, ssh_type_to_char, ssh_public_key_struct::type, user.
Referenced by torture_pubkey_generate_from_privkey.
LIBSSH_API ssh_string publickey_from_file(ssh_session session, const char *filename, int *type)
References key, rc, session, ssh_key_free, ssh_pki_export_pubkey_blob, ssh_pki_import_pubkey_file, ssh_public_key_struct::type.
Referenced by ssh_try_publickey_from_file, ssh_userauth_privatekey_file.
LIBSSH_API ssh_public_key publickey_from_privatekey(ssh_private_key prv)
References privkey, pubkey, rc, SSH_KEY_FLAG_PRIVATE, SSH_KEY_FLAG_PUBLIC, ssh_key_free, ssh_key_new, ssh_key_type_to_char, ssh_pki_convert_key_to_publickey, ssh_pki_export_privkey_to_pubkey, ssh_private_key_struct::type.
Referenced by torture_pubkey_generate_from_privkey.
LIBSSH_API ssh_string publickey_to_string(ssh_public_key key)
References key, pubkey, rc, ssh_key_free, ssh_key_new, ssh_pki_export_pubkey_blob.
Referenced by torture_pubkey_generate_from_privkey.
LIBSSH_API int ssh_try_publickey_from_file(ssh_session session, const char *keyfile, ssh_string *publickey, int *type)
References ssh_session_struct::opts, publickey_from_file, SAFE_FREE, session, ssh_file_readaccess_ok, ssh_get_error, SSH_LOG, SSH_LOG_PACKET, ssh_options_apply, ssh_session_struct::sshdir, ssh_public_key_struct::type.
Referenced by torture_pubkey_from_file, torture_pubkey_generate_from_privkey.
LIBSSH_API enum ssh_keytypes_e ssh_privatekey_type(ssh_private_key privatekey)
LIBSSH_API ssh_string ssh_get_pubkey(ssh_session session)
References ssh_session_struct::current_crypto, rc, ssh_crypto_struct::server_pubkey, session, ssh_dh_get_current_server_publickey_blob.
LIBSSH_API ssh_message ssh_message_retrieve(ssh_session session, uint32_t packettype)
LIBSSH_API ssh_public_key ssh_message_auth_publickey(ssh_message msg)
References ssh_message_struct::auth_request, ssh_auth_request::pubkey, ssh_pki_convert_key_to_publickey.
SSH_DEPRECATED LIBSSH_API void string_burn(ssh_string str)
References ssh_string_burn.
SSH_DEPRECATED LIBSSH_API ssh_string string_copy(ssh_string str)
References ssh_string_copy.
SSH_DEPRECATED LIBSSH_API void* string_data(ssh_string str)
References ssh_string_data.
SSH_DEPRECATED LIBSSH_API int string_fill(ssh_string str, const void *data, size_t len)
References ssh_string_fill.
SSH_DEPRECATED LIBSSH_API void string_free(ssh_string str)
References ssh_string_free.
SSH_DEPRECATED LIBSSH_API ssh_string string_from_char(const char *what)
References ssh_string_from_char.
SSH_DEPRECATED LIBSSH_API size_t string_len(ssh_string str)
References ssh_string_len.
SSH_DEPRECATED LIBSSH_API ssh_string string_new(size_t size)
References ssh_string_new.
SSH_DEPRECATED LIBSSH_API char* string_to_char(ssh_string str)
References ssh_string_to_char.