legacy.c
int ssh_auth_list(ssh_session session)
functions in that file are wrappers to the newly named functions. All of them are depreciated, but these wrapper will avoid breaking backward compatibility
References session, ssh_userauth_list.
int ssh_userauth_offer_pubkey(ssh_session session, const char *username, int type, ssh_string publickey)
References key, rc, session, SSH_AUTH_ERROR, SSH_FATAL, ssh_key_free, ssh_pki_import_pubkey_blob, ssh_set_error, ssh_userauth_try_publickey, username.
int ssh_userauth_pubkey(ssh_session session, const char *username, ssh_string publickey, ssh_private_key privatekey)
References key, rc, session, SSH_AUTH_ERROR, SSH_KEY_FLAG_PRIVATE, SSH_KEY_FLAG_PUBLIC, ssh_key_free, ssh_key_new, ssh_key_type_to_char, ssh_userauth_publickey, ssh_private_key_struct::type, username.
Referenced by ssh_userauth_privatekey_file.
int ssh_userauth_autopubkey(ssh_session session, const char *passphrase)
References session, ssh_userauth_publickey_auto.
Referenced by authenticate, connect_host.
int ssh_userauth_privatekey_file(ssh_session session, const char *username, const char *filename, const char *passphrase)
References error, privatekey_free, privatekey_from_file, privkey, pubkey, publickey_from_file, rc, SAFE_FREE, session, SSH_AUTH_ERROR, SSH_LOG, SSH_LOG_RARE, ssh_set_error_oom, ssh_string_free, ssh_userauth_pubkey, username.
void buffer_free(ssh_buffer buffer)
References buffer, ssh_buffer_free.
void* buffer_get(ssh_buffer buffer)
References buffer, ssh_buffer_get.
uint32_t buffer_get_len(ssh_buffer buffer)
References buffer, ssh_buffer_get_len.
ssh_buffer buffer_new(void)
References ssh_buffer_new.
ssh_channel channel_accept_x11(ssh_channel channel, int timeout_ms)
References ssh_channel_accept_x11.
int channel_change_pty_size(ssh_channel channel, int cols, int rows)
References ssh_channel_change_pty_size.
ssh_channel channel_forward_accept(ssh_session session, int timeout_ms)
References session, ssh_channel_accept_forward.
int channel_close(ssh_channel channel)
References ssh_channel_close.
int channel_forward_cancel(ssh_session session, const char *address, int port)
References port, session, ssh_channel_cancel_forward.
int channel_forward_listen(ssh_session session, const char *address, int port, int *bound_port)
References port, session, ssh_channel_listen_forward.
void channel_free(ssh_channel channel)
References ssh_channel_free.
int channel_get_exit_status(ssh_channel channel)
References ssh_channel_get_exit_status.
ssh_session channel_get_session(ssh_channel channel)
References ssh_channel_get_session.
int channel_is_closed(ssh_channel channel)
References ssh_channel_is_closed.
int channel_is_eof(ssh_channel channel)
References ssh_channel_is_eof.
int channel_is_open(ssh_channel channel)
References ssh_channel_is_open.
ssh_channel channel_new(ssh_session session)
References session, ssh_channel_new.
int channel_open_forward(ssh_channel channel, const char *remotehost, int remoteport, const char *sourcehost, int localport)
References ssh_channel_open_forward.
int channel_open_session(ssh_channel channel)
References ssh_channel_open_session.
int channel_poll(ssh_channel channel, int is_stderr)
References ssh_channel_poll.
int channel_read(ssh_channel channel, void *dest, uint32_t count, int is_stderr)
References ssh_channel_read.
int channel_read_nonblocking(ssh_channel channel, void *dest, uint32_t count, int is_stderr)
References ssh_channel_read_nonblocking.
int channel_request_env(ssh_channel channel, const char *name, const char *value)
References name, ssh_channel_request_env.
int channel_request_exec(ssh_channel channel, const char *cmd)
References ssh_channel_request_exec.
int channel_request_pty(ssh_channel channel)
References ssh_channel_request_pty.
int channel_request_pty_size(ssh_channel channel, const char *term, int cols, int rows)
References ssh_channel_request_pty_size.
int channel_request_shell(ssh_channel channel)
References ssh_channel_request_shell.
int channel_request_send_signal(ssh_channel channel, const char *signum)
References ssh_channel_request_send_signal.
int channel_request_sftp(ssh_channel channel)
References ssh_channel_request_sftp.
int channel_request_subsystem(ssh_channel channel, const char *subsystem)
References ssh_channel_request_subsystem.
int channel_request_x11(ssh_channel channel, int single_connection, const char *protocol, const char *cookie, int screen_number)
References ssh_channel_request_x11.
int channel_send_eof(ssh_channel channel)
References ssh_channel_send_eof.
int channel_select(ssh_channel *readchans, ssh_channel *writechans, ssh_channel *exceptchans, struct timeval *timeout)
References ssh_channel_select.
void channel_set_blocking(ssh_channel channel, int blocking)
References ssh_channel_set_blocking.
int channel_write(ssh_channel channel, const void *data, uint32_t len)
References ssh_channel_write.
void string_burn(ssh_string str)
References ssh_string_burn.
ssh_string string_copy(ssh_string str)
References ssh_string_copy.
void* string_data(ssh_string str)
References ssh_string_data.
int string_fill(ssh_string str, const void *data, size_t len)
References ssh_string_fill.
void string_free(ssh_string str)
References ssh_string_free.
ssh_string string_from_char(const char *what)
References ssh_string_from_char.
size_t string_len(ssh_string str)
References ssh_string_len.
ssh_string string_new(size_t size)
References ssh_string_new.
char* string_to_char(ssh_string str)
References ssh_string_to_char.
void publickey_free(ssh_public_key key)
References key, SAFE_FREE, SSH_KEYTYPE_DSS, SSH_KEYTYPE_RSA.
Referenced by torture_pubkey_generate_from_privkey.
ssh_public_key publickey_from_privatekey(ssh_private_key prv)
References privkey, pubkey, rc, SSH_KEY_FLAG_PRIVATE, SSH_KEY_FLAG_PUBLIC, ssh_key_free, ssh_key_new, ssh_key_type_to_char, ssh_pki_convert_key_to_publickey, ssh_pki_export_privkey_to_pubkey, ssh_private_key_struct::type.
Referenced by torture_pubkey_generate_from_privkey.
ssh_private_key privatekey_from_file(ssh_session session, const char *filename, int type, const char *passphrase)
References ssh_callbacks_struct::auth_function, ssh_common_struct::callbacks, ssh_session_struct::common, key, privkey, rc, session, SSH_ERROR, ssh_key_free, ssh_pki_import_privkey_file, ssh_public_key_struct::type, ssh_callbacks_struct::userdata.
Referenced by ssh_userauth_privatekey_file, torture_privatekey_from_file, torture_privatekey_from_file_passphrase, torture_pubkey_generate_from_privkey.
enum ssh_keytypes_e ssh_privatekey_type(ssh_private_key privatekey)
void privatekey_free(ssh_private_key prv)
References SAFE_FREE.
Referenced by ssh_userauth_privatekey_file, torture_privatekey_from_file, torture_privatekey_from_file_passphrase, torture_pubkey_generate_from_privkey.
ssh_string publickey_from_file(ssh_session session, const char *filename, int *type)
References key, rc, session, ssh_key_free, ssh_pki_export_pubkey_blob, ssh_pki_import_pubkey_file, ssh_public_key_struct::type.
Referenced by ssh_try_publickey_from_file, ssh_userauth_privatekey_file.
const char* ssh_type_to_char(int type)
References ssh_key_type_to_char, ssh_public_key_struct::type.
Referenced by ssh_publickey_to_file.
int ssh_type_from_name(const char *name)
References name, ssh_key_type_from_name.
ssh_public_key publickey_from_string(ssh_session session, ssh_string pubkey_s)
References key, pubkey, rc, session, ssh_key_free, ssh_pki_import_pubkey_blob.
ssh_string publickey_to_string(ssh_public_key pubkey)
References key, pubkey, rc, ssh_key_free, ssh_key_new, ssh_pki_export_pubkey_blob.
Referenced by torture_pubkey_generate_from_privkey.
int ssh_publickey_to_file(ssh_session session, const char *file, ssh_string pubkey, int type)
References bin_to_base64, buffer, host, pubkey, rc, SAFE_FREE, session, SSH_ERROR, SSH_FATAL, ssh_get_local_username, SSH_LOG, SSH_LOG_PACKET, SSH_LOG_RARE, SSH_OK, SSH_REQUEST_DENIED, ssh_set_error, ssh_string_data, ssh_string_len, ssh_type_to_char, ssh_public_key_struct::type, user.
Referenced by torture_pubkey_generate_from_privkey.
int ssh_try_publickey_from_file(ssh_session session, const char *keyfile, ssh_string *publickey, int *type)
References ssh_session_struct::opts, publickey_from_file, SAFE_FREE, session, ssh_file_readaccess_ok, ssh_get_error, SSH_LOG, SSH_LOG_PACKET, ssh_options_apply, ssh_session_struct::sshdir, ssh_public_key_struct::type.
Referenced by torture_pubkey_from_file, torture_pubkey_generate_from_privkey.
ssh_string ssh_get_pubkey(ssh_session session)
References ssh_session_struct::current_crypto, rc, ssh_crypto_struct::server_pubkey, session, ssh_dh_get_current_server_publickey_blob.