libssh.h
SSH_LOG_NONE
No logging at all
SSH_LOG_WARN
Show only warnings
SSH_LOG_INFO
Get some information what's going on
SSH_LOG_DEBUG
Get detailed debuging information
SSH_LOG_TRACE
Get trace output, packet information, ...
LIBSSH_API
SSH_STRINGIFY
SSH_TOSTRING
SSH_VERSION_INT
SSH_VERSION_DOT
SSH_VERSION
LIBSSH_VERSION_MAJOR
LIBSSH_VERSION_MINOR
LIBSSH_VERSION_MICRO
LIBSSH_VERSION_INT
LIBSSH_VERSION
PRINTF_ATTRIBUTE
SSH_DEPRECATED
SSH_INVALID_SOCKET
SSH_CRYPT
SSH_MAC
SSH_COMP
SSH_LANG
SSH_AUTH_METHOD_UNKNOWN
SSH_AUTH_METHOD_NONE
SSH_AUTH_METHOD_PASSWORD
SSH_AUTH_METHOD_PUBLICKEY
SSH_AUTH_METHOD_HOSTBASED
SSH_AUTH_METHOD_INTERACTIVE
SSH_AUTH_METHOD_GSSAPI_MIC
SSH_CLOSED
Socket is closed
SSH_READ_PENDING
Reading to socket won't block
SSH_CLOSED_ERROR
Session was closed due to an error
SSH_WRITE_PENDING
Output buffer not empty
MD5_DIGEST_LEN
SSH_ADDRSTRLEN
SSH_OK
SSH_ERROR
SSH_AGAIN
SSH_EOF
SSH_LOG_RARE
SSH_KNOWNHOSTS_ENTRY_FREE
SSH_MESSAGE_FREE
SSH_KEY_FREE
SSH_STRING_FREE
SSH_STRING_FREE_CHAR
SSH_BUFFER_FREE
ssh_kex_types_e
ssh_auth_e
ssh_requests_e
ssh_channel_type_e
ssh_channel_requests_e
ssh_global_requests_e
ssh_publickey_state_e
ssh_server_known_e
ssh_known_hosts_e
There had been an error checking the host.
ssh_error_types_e
ssh_keytypes_e
ssh_keycmp_e
@1
No logging at all
ssh_options_e
@2
Code is going to write/create remote files
ssh_scp_request_types
A new directory is going to be pulled
ssh_connector_flags_e
Only the standard stream of the channel
ssh_publickey_hash_type
typedef struct ssh_counter_struct* ssh_counter
typedef struct ssh_agent_struct* ssh_agent
typedef struct ssh_buffer_struct* ssh_buffer
typedef struct ssh_channel_struct* ssh_channel
typedef struct ssh_message_struct* ssh_message
typedef struct ssh_pcap_file_struct* ssh_pcap_file
typedef struct ssh_key_struct* ssh_key
typedef struct ssh_scp_struct* ssh_scp
typedef struct ssh_session_struct* ssh_session
typedef struct ssh_string_struct* ssh_string
typedef struct ssh_event_struct* ssh_event
typedef struct ssh_connector_struct* ssh_connector
typedef void* ssh_gssapi_creds
typedef int socket_t
typedef int(* ssh_auth_callback) (const char *prompt, char *buf, size_t len, int echo, int verify, void *userdata))(const char *prompt, char *buf, size_t len, int echo, int verify, void *userdata)
SSH authentication callback.
prompt Prompt to be displayed. buf Buffer to save the password. You should null-terminate it. len Length of the buffer. echo Enable or disable the echo of what you type. verify Should the password be verified? userdata Userdata to be passed to the callback function. Useful for GUI applications. 0 on success, < 0 on error.
typedef int(* ssh_event_callback) (socket_t fd, int revents, void *userdata))(socket_t fd, int revents, void *userdata)
LIBSSH_API int ssh_blocking_flush(ssh_session session, int timeout)
Blocking flush of the outgoing buffer.
session The SSH session timeout Set an upper limit on the time for which this function will block, in milliseconds. Specifying -1 means an infinite timeout. This parameter is passed to the poll() function. SSH_OK on success, SSH_AGAIN if timeout occurred, SSH_ERROR otherwise.
References rc, session, SSH_AGAIN, SSH_ERROR, ssh_flush_termination, ssh_handle_packets_termination.
Referenced by ssh_channel_flush.
LIBSSH_API ssh_channel ssh_channel_accept_x11(ssh_channel channel, int timeout_ms)
Accept an X11 forwarding channel.
channel An x11-enabled session channel. timeout_ms Timeout in milliseconds. A newly created channel, or NULL if no X11 request from the server.
References ssh_channel_struct::session, ssh_channel_accept, SSH_CHANNEL_X11.
Referenced by ssh::Channel::acceptX11, channel_accept_x11.
LIBSSH_API int ssh_channel_change_pty_size(ssh_channel channel, int cols, int rows)
Change the size of the terminal associated to a channel.
channel The channel to change the size. cols The new number of columns. rows The new number of rows. SSH_OK on success, SSH_ERROR if an error occurred. Do not call it from a signal handler if you are not sure any other libssh function using the same channel/session is running at same time (not 100% threadsafe).
References buffer, channel_request, error, rc, ssh_channel_struct::session, session, SSH_BUFFER_FREE, ssh_buffer_new, ssh_buffer_pack, SSH_ERROR, SSH_OK, ssh_set_error_oom.
Referenced by ssh::Channel::changePtySize, channel_change_pty_size, sizechanged.
LIBSSH_API int ssh_channel_close(ssh_channel channel)
Close a channel.
This sends an end of file and then closes the channel. You won't be able to recover any data the server was going to send or was in buffers. channel The channel to close. SSH_OK on success, SSH_ERROR if an error occurred. ssh_channel_free() ssh_channel_is_eof()
References error, ssh_channel_struct::flags, ssh_channel_struct::local_channel, ssh_session_struct::out_buffer, rc, ssh_channel_struct::remote_channel, ssh_channel_struct::session, session, SSH2_MSG_CHANNEL_CLOSE, ssh_buffer_pack, ssh_buffer_reinit, SSH_CHANNEL_FLAG_CLOSED_LOCAL, ssh_channel_flush, ssh_channel_send_eof, SSH_CHANNEL_STATE_CLOSED, SSH_ERROR, SSH_LOG, SSH_LOG_PACKET, SSH_OK, ssh_packet_send, ssh_set_error_oom, ssh_channel_struct::state.
Referenced by benchmarks_raw_down, benchmarks_raw_up, benchmarks_ssh_latency, channel_close, ssh::Channel::close, create_files, default_handle_session_cb, do_cleanup, do_connect, handle_kbdint_session_cb, handle_session, main, my_fd_data_function, pkd_exec_hello, ssh_channel_free, ssh_scp_close, torture_request_env, torture_server_unknown_global_request, torture_ssh_forward, torture_unknown_request, upload_script.
LIBSSH_API void ssh_channel_free(ssh_channel channel)
Close and free a channel.
channel The channel to free. Any data unread on this channel will be lost.
References ssh_session_struct::alive, ssh_channel_struct::flags, ssh_channel_struct::session, session, ssh_channel_close, ssh_channel_do_free, SSH_CHANNEL_FLAG_CLOSED_LOCAL, SSH_CHANNEL_FLAG_CLOSED_REMOTE, SSH_CHANNEL_FLAG_FREED_LOCAL, SSH_CHANNEL_FLAG_NOT_BOUND, SSH_CHANNEL_STATE_CLOSED, SSH_CHANNEL_STATE_OPEN, ssh_channel_struct::state.
Referenced by batch_shell, benchmarks_raw_down, benchmarks_raw_up, benchmarks_ssh_latency, channel_free, create_files, do_cleanup, do_connect, LLVMFuzzerTestOneInput, main, pkd_channel_openreq_cb, pkd_exec_hello, select_loop, shell, ssh_message_channel_request_open_reply_accept, ssh_scp_close, ssh_scp_free, torture_channel_read_error, upload_script, ssh::Channel::~Channel.
LIBSSH_API int ssh_channel_get_exit_status(ssh_channel channel)
Get the exit status of the channel (error code from the executed instruction).
channel The channel to get the status from. The exit status, -1 if no exit status has been returned (yet), or SSH_ERROR on error. This function may block until a timeout (or never) if the other side is not willing to close the channel. If you're looking for an async handling of this register a callback for the exit status. ssh_channel_exit_status_callback
References ssh_channel_read_termination_struct::channel, ssh_channel_struct::exit_status, rc, ssh_channel_struct::session, ssh_session_struct::session_state, ssh_channel_exit_status_termination, SSH_ERROR, ssh_handle_packets_termination, SSH_SESSION_STATE_ERROR, SSH_TIMEOUT_DEFAULT.
Referenced by channel_get_exit_status, do_connect, ssh::Channel::getExitStatus.
LIBSSH_API ssh_session ssh_channel_get_session(ssh_channel channel)
Recover the session in which belongs a channel.
channel The channel to recover the session from. The session pointer.
References ssh_channel_read_termination_struct::channel, ssh_channel_struct::session.
Referenced by channel_get_session, my_fd_data_function, ssh_connector_remove_event, ssh_connector_set_event.
LIBSSH_API int ssh_channel_is_closed(ssh_channel channel)
Check if the channel is closed or not.
channel The channel to check. 0 if channel is opened, nonzero otherwise. ssh_channel_is_open()
References ssh_session_struct::alive, ssh_channel_struct::session, SSH_CHANNEL_STATE_OPEN, SSH_ERROR, ssh_channel_struct::state.
Referenced by channel_is_closed, channel_protocol_select, do_cleanup, ssh::Channel::isClosed, my_fd_data_function, select_loop.
LIBSSH_API int ssh_channel_is_eof(ssh_channel channel)
Check if remote has sent an EOF.
channel The channel to check. 0 if there is no EOF, nonzero otherwise.
References ssh_channel_struct::remote_eof, ssh_buffer_get_len, SSH_ERROR, ssh_channel_struct::stderr_buffer, ssh_channel_struct::stdout_buffer.
Referenced by channel_is_eof, channel_read_buffer, create_files, ssh::Channel::isEof, ssh_connector_channel_write_wontblock_cb, ssh_connector_fd_out_cb, ssh_scp_close, ssh_scp_pull_request.
LIBSSH_API int ssh_channel_is_open(ssh_channel channel)
Check if the channel is open or not.
channel The channel to check. 0 if channel is closed, nonzero otherwise. ssh_channel_is_closed()
References ssh_session_struct::alive, ssh_channel_struct::session, SSH_CHANNEL_STATE_OPEN, ssh_channel_struct::state.
Referenced by channel_is_open, channel_protocol_select, default_handle_session_cb, handle_kbdint_session_cb, handle_session, ssh::Channel::isOpen, my_fd_data_function, select_loop.
LIBSSH_API ssh_channel ssh_channel_new(ssh_session session)
Allocate a new channel.
session The ssh session to use. A pointer to a newly allocated channel, NULL on error.
References ssh_session_struct::channels, ssh_channel_struct::exit_status, ssh_channel_struct::flags, ssh_session_struct::flags, ssh_channel_struct::request_state, SAFE_FREE, ssh_channel_struct::session, session, SSH_BUFFER_FREE, ssh_buffer_new, SSH_CHANNEL_FLAG_NOT_BOUND, SSH_CHANNEL_REQ_STATE_NONE, SSH_CHANNEL_STATE_NOT_OPEN, ssh_list_new, ssh_list_prepend, SSH_SESSION_FLAG_AUTHENTICATED, ssh_set_error_oom, ssh_channel_struct::state, ssh_channel_struct::stderr_buffer, ssh_channel_struct::stdout_buffer.
Referenced by batch_shell, benchmarks_raw_down, benchmarks_raw_up, benchmarks_ssh_latency, ssh::Channel::Channel, channel_new, channel_new_session_cb, channel_open, client_thread, create_files, do_connect, forwarding, LLVMFuzzerTestOneInput, main, new_session_channel, pkd_channel_openreq_cb, shell, ssh_message_channel_request_open_reply_accept, ssh_scp_init, torture_channel_read_error, torture_request_env, torture_server_unknown_global_request, torture_unknown_request, upload_script.
LIBSSH_API int ssh_channel_open_auth_agent(ssh_channel channel)
Open an agent authentication forwarding channel. This type of channel can be opened by a server towards a client in order to provide SSH-Agent services to the server-side process. This channel can only be opened if the client claimed support by sending a channel request beforehand.
channel An allocated channel. SSH_OK on success, SSH_ERROR if an error occurred, SSH_AGAIN if in nonblocking mode and call has to be done again. ssh_channel_open_forward()
References CHANNEL_INITIAL_WINDOW, CHANNEL_MAX_PACKET, channel_open, SSH_ERROR.
LIBSSH_API int ssh_channel_open_forward(ssh_channel channel, const char *remotehost, int remoteport, const char *sourcehost, int localport)
Open a TCP/IP forwarding channel.
channel An allocated channel. remotehost The remote host to connected (host name or IP). remoteport The remote port. sourcehost The numeric IP address of the machine from where the connection request originates. This is mostly for logging purposes. localport The port on the host from where the connection originated. This is mostly for logging purposes. SSH_OK on success, SSH_ERROR if an error occurred, SSH_AGAIN if in nonblocking mode and call has to be done again. This function does not bind the local port and does not automatically forward the content of a socket to the channel. You still have to use channel_read and channel_write for this.
References CHANNEL_INITIAL_WINDOW, CHANNEL_MAX_PACKET, channel_open, error, rc, ssh_channel_struct::session, session, SSH_BUFFER_FREE, ssh_buffer_new, ssh_buffer_pack, SSH_ERROR, SSH_OK, ssh_set_error_invalid, ssh_set_error_oom, SSH_STRING_FREE.
Referenced by channel_open_forward, do_connect, forwarding, ssh::Channel::openForward.
LIBSSH_API int ssh_channel_open_forward_unix(ssh_channel channel, const char *remotepath, const char *sourcehost, int localport)
Open a TCP/IP - UNIX domain socket forwarding channel.
channel An allocated channel. remotepath The UNIX socket path on the remote machine sourcehost The numeric IP address of the machine from where the connection request originates. This is mostly for logging purposes. localport The port on the host from where the connection originated. This is mostly for logging purposes. SSH_OK on success, SSH_ERROR if an error occurred, SSH_AGAIN if in nonblocking mode and call has to be done again. This function does not bind the local port and does not automatically forward the content of a socket to the channel. You still have to use channel_read and channel_write for this. Requires support of OpenSSH for UNIX domain socket forwarding.
References CHANNEL_INITIAL_WINDOW, CHANNEL_MAX_PACKET, channel_open, error, rc, ssh_channel_struct::session, session, SSH_BUFFER_FREE, ssh_buffer_new, ssh_buffer_pack, SSH_ERROR, ssh_get_openssh_version, SSH_OK, SSH_REQUEST_DENIED, ssh_set_error, ssh_set_error_invalid, ssh_set_error_oom, SSH_STRING_FREE.
LIBSSH_API int ssh_channel_open_session(ssh_channel channel)
Open a session channel (suited for a shell, not TCP forwarding).
channel An allocated channel. SSH_OK on success, SSH_ERROR if an error occurred, SSH_AGAIN if in nonblocking mode and call has to be done again. ssh_channel_open_forward() ssh_channel_request_env() ssh_channel_request_shell() ssh_channel_request_exec()
References CHANNEL_INITIAL_WINDOW, CHANNEL_MAX_PACKET, channel_open, SSH_ERROR.
Referenced by batch_shell, benchmarks_raw_down, benchmarks_raw_up, benchmarks_ssh_latency, channel_open_session, client_thread, create_files, do_connect, LLVMFuzzerTestOneInput, main, ssh::Channel::openSession, shell, ssh_scp_init, torture_channel_read_error, torture_request_env, torture_server_unknown_global_request, torture_unknown_request, upload_script.
LIBSSH_API int ssh_channel_open_x11(ssh_channel channel, const char *orig_addr, int orig_port)
LIBSSH_API int ssh_channel_poll(ssh_channel channel, int is_stderr)
Polls a channel for data to read.
channel The channel to poll. is_stderr A boolean to select the stderr stream. The number of bytes available for reading, 0 if nothing is available or SSH_ERROR on error. When the channel is in EOF state, the function returns SSH_EOF. ssh_channel_is_eof()
References ssh_channel_read_termination_struct::channel, ssh_channel_struct::remote_eof, ssh_channel_struct::session, ssh_session_struct::session_state, ssh_buffer_get_len, SSH_EOF, SSH_ERROR, ssh_handle_packets, SSH_SESSION_STATE_ERROR, SSH_TIMEOUT_NONBLOCKING, ssh_channel_struct::stderr_buffer, ssh_channel_struct::stdout_buffer.
Referenced by channel_poll, channel_read_buffer, do_connect, ssh::Channel::poll, select_loop, ssh_channel_read_nonblocking, ssh_scp_write, ssh_select.
LIBSSH_API int ssh_channel_poll_timeout(ssh_channel channel, int timeout, int is_stderr)
Polls a channel for data to read, waiting for a certain timeout.
channel The channel to poll. timeout Set an upper limit on the time for which this function will block, in milliseconds. Specifying a negative value means an infinite timeout. This parameter is passed to the poll() function. is_stderr A boolean to select the stderr stream. The number of bytes available for reading, 0 if nothing is available (timeout elapsed), SSH_EOF on end of file, SSH_ERROR on error. When the channel is in EOF state, the function returns SSH_EOF. ssh_channel_is_eof()
References ssh_channel_read_termination_struct::channel, ctx, rc, ssh_channel_struct::remote_eof, ssh_channel_struct::session, session, ssh_session_struct::session_state, ssh_buffer_get_len, ssh_channel_read_termination, SSH_EOF, SSH_ERROR, ssh_handle_packets_termination, SSH_SESSION_STATE_ERROR, ssh_channel_struct::stderr_buffer, ssh_channel_struct::stdout_buffer.
Referenced by ssh_connector_set_event.
LIBSSH_API int ssh_channel_read(ssh_channel channel, void *dest, uint32_t count, int is_stderr)
Reads data from a channel.
channel The channel to read from. dest The destination buffer which will get the data. count The count of bytes to be read. is_stderr A boolean value to mark reading from the stderr flow. The number of bytes read, 0 on end of file or SSH_ERROR on error. In nonblocking mode it Can return 0 if no data is available or SSH_AGAIN. This function may return less than count bytes of data, and won't block until count bytes have been read. The read function using a buffer has been renamed to channel_read_buffer().
References ssh_channel_read_termination_struct::channel, ssh_channel_read_termination_struct::count, ssh_channel_read_timeout, SSH_TIMEOUT_DEFAULT.
Referenced by atomicio, benchmarks_raw_down, benchmarks_raw_up, channel_read, channel_read_buffer, create_files, do_connect, main, select_loop, ssh_channel_read_nonblocking, ssh_scp_close, ssh_scp_read, ssh_scp_read_string, ssh_scp_response, torture_channel_read_error, torture_request_env.
LIBSSH_API int ssh_channel_read_timeout(ssh_channel channel, void *dest, uint32_t count, int is_stderr, int timeout_ms)
Reads data from a channel.
channel The channel to read from. dest The destination buffer which will get the data. count The count of bytes to be read. is_stderr A boolean value to mark reading from the stderr flow. timeout_ms A timeout in milliseconds. A value of -1 means infinite timeout. The number of bytes read, 0 on end of file or SSH_ERROR on error. In nonblocking mode it Can return 0 if no data is available or SSH_AGAIN. This function may return less than count bytes of data, and won't block until count bytes have been read. The read function using a buffer has been renamed to channel_read_buffer().
References ssh_channel_read_termination_struct::channel, ssh_channel_read_termination_struct::count, ssh_channel_struct::counter, ctx, grow_window, ssh_counter_struct::in_bytes, ssh_channel_struct::local_window, rc, ssh_channel_struct::remote_eof, ssh_channel_struct::session, session, ssh_session_struct::session_state, ssh_buffer_get, ssh_buffer_get_len, ssh_buffer_pass_bytes, ssh_channel_read_termination, SSH_CHANNEL_STATE_CLOSED, SSH_ERROR, SSH_FATAL, ssh_handle_packets_termination, SSH_LOG, SSH_LOG_PACKET, SSH_SESSION_STATE_ERROR, ssh_set_error, ssh_set_error_invalid, SSH_TIMEOUT_DEFAULT, SSH_TIMEOUT_INFINITE, ssh_channel_struct::state, ssh_channel_struct::stderr_buffer, ssh_channel_struct::stdout_buffer, WINDOWLIMIT.
Referenced by ssh::Channel::read, ssh_channel_read.
LIBSSH_API int ssh_channel_read_nonblocking(ssh_channel channel, void *dest, uint32_t count, int is_stderr)
Do a nonblocking read on the channel.
A nonblocking read on the specified channel. it will return <= count bytes of data read atomically. channel The channel to read from. dest A pointer to a destination buffer. count The count of bytes of data to be read. is_stderr A boolean to select the stderr stream. The number of bytes read, 0 if nothing is available or SSH_ERROR on error. Don't forget to check for EOF as it would return 0 here. ssh_channel_is_eof()
References ssh_channel_read_termination_struct::channel, ssh_channel_read_termination_struct::count, rc, ssh_channel_struct::session, session, ssh_session_struct::session_state, ssh_channel_poll, ssh_channel_read, SSH_ERROR, ssh_is_blocking, SSH_SESSION_STATE_ERROR, ssh_set_blocking, ssh_set_error_invalid.
Referenced by channel_read_nonblocking, do_connect, ssh::Channel::readNonblocking, ssh_connector_channel_write_wontblock_cb, ssh_connector_fd_out_cb.
LIBSSH_API int ssh_channel_request_env(ssh_channel channel, const char *name, const char *value)
Set environment variables.
channel The channel to set the environment variables. name The name of the variable. value The value to set. SSH_OK on success, SSH_ERROR if an error occurred, SSH_AGAIN if in nonblocking mode and call has to be done again. Some environment variables may be refused by security reasons.
References buffer, channel_request, error, name, rc, ssh_channel_struct::request_state, ssh_channel_struct::session, SSH_BUFFER_FREE, ssh_buffer_new, ssh_buffer_pack, SSH_CHANNEL_REQ_STATE_NONE, SSH_ERROR, SSH_OK, ssh_set_error_invalid, ssh_set_error_oom.
Referenced by benchmarks_ssh_latency, channel_request_env, ssh::Channel::requestEnv, torture_request_env.
LIBSSH_API int ssh_channel_request_exec(ssh_channel channel, const char *cmd)
Run a shell command without an interactive shell.
This is similar to 'sh -c command'. channel The channel to execute the command. cmd The command to execute (e.g. "ls ~/ -al | grep -i reports"). SSH_OK on success, SSH_ERROR if an error occurred, SSH_AGAIN if in nonblocking mode and call has to be done again. Example: rc=ssh_channel_request_exec(channel,"psaux"); if(rc>0){ return-1; } while((rc=ssh_channel_read(channel,buffer,sizeof(buffer),0))>0){ if(fwrite(buffer,1,rc,stdout)!=(unsignedint)rc){ return-1; } } ssh_channel_request_shell()
References buffer, channel_request, error, rc, ssh_channel_struct::request_state, ssh_channel_struct::session, SSH_BUFFER_FREE, ssh_buffer_new, ssh_buffer_pack, SSH_CHANNEL_REQ_STATE_NONE, SSH_ERROR, SSH_OK, ssh_set_error_invalid, ssh_set_error_oom.
Referenced by batch_shell, benchmarks_raw_down, benchmarks_raw_up, channel_request_exec, create_files, do_connect, LLVMFuzzerTestOneInput, main, ssh::Channel::requestExec, ssh_scp_init, torture_channel_read_error, torture_request_env, upload_script.
LIBSSH_API int ssh_channel_request_pty(ssh_channel channel)
Request a PTY.
channel The channel to send the request. SSH_OK on success, SSH_ERROR if an error occurred, SSH_AGAIN if in nonblocking mode and call has to be done again. ssh_channel_request_pty_size()
References ssh_channel_request_pty_size.
Referenced by channel_request_pty, ssh::Channel::requestPty, shell.
LIBSSH_API int ssh_channel_request_pty_size(ssh_channel channel, const char *term, int cols, int rows)
Request a pty with a specific type and size.
channel The channel to sent the request. terminal The terminal type ("vt100, xterm,..."). col The number of columns. row The number of rows. SSH_OK on success, SSH_ERROR if an error occurred, SSH_AGAIN if in nonblocking mode and call has to be done again.
References buffer, channel_request, error, rc, ssh_channel_struct::request_state, ssh_channel_struct::session, session, SSH_BUFFER_FREE, ssh_buffer_new, ssh_buffer_pack, SSH_CHANNEL_REQ_STATE_NONE, SSH_ERROR, SSH_OK, ssh_set_error_invalid, ssh_set_error_oom, terminal.
Referenced by channel_request_pty_size, ssh::Channel::requestPty, ssh_channel_request_pty.
LIBSSH_API int ssh_channel_request_shell(ssh_channel channel)
Request a shell.
channel The channel to send the request. SSH_OK on success, SSH_ERROR if an error occurred, SSH_AGAIN if in nonblocking mode and call has to be done again.
References channel_request, SSH_ERROR.
Referenced by channel_request_shell, ssh::Channel::requestShell, shell.
LIBSSH_API int ssh_channel_request_send_signal(ssh_channel channel, const char *signum)
Send a signal to remote process (as described in RFC 4254, section 6.9).
Sends a signal 'sig' to the remote process. Note, that remote system may not support signals concept. In such a case this request will be silently ignored. Only SSH-v2 is supported (I'm not sure about SSH-v1). OpenSSH doesn't support signals yet, see: https://bugzilla.mindrot.org/show_bug.cgi?id=1424 channel The channel to send signal. sig The signal to send (without SIG prefix) SIGABRT -> ABRT SIGALRM -> ALRM SIGFPE -> FPE SIGHUP -> HUP SIGILL -> ILL SIGINT -> INT SIGKILL -> KILL SIGPIPE -> PIPE SIGQUIT -> QUIT SIGSEGV -> SEGV SIGTERM -> TERM SIGUSR1 -> USR1 SIGUSR2 -> USR2 SSH_OK on success, SSH_ERROR if an error occurred (including attempts to send signal via SSH-v1 session).
References buffer, channel_request, error, rc, ssh_channel_struct::session, SSH_BUFFER_FREE, ssh_buffer_new, ssh_buffer_pack, SSH_ERROR, SSH_OK, ssh_set_error_invalid, ssh_set_error_oom.
Referenced by channel_request_send_signal, ssh::Channel::requestSendSignal.
LIBSSH_API int ssh_channel_request_send_break(ssh_channel channel, uint32_t length)
Send a break signal to the server (as described in RFC 4335).
Sends a break signal to the remote process. Note, that remote system may not support breaks. In such a case this request will be silently ignored. Only SSH-v2 is supported. channel The channel to send the break to. length The break-length in milliseconds to send. SSH_OK on success, SSH_ERROR if an error occurred (including attempts to send signal via SSH-v1 session).
References buffer, channel_request, error, rc, ssh_channel_struct::session, SSH_BUFFER_FREE, ssh_buffer_new, ssh_buffer_pack, SSH_ERROR, SSH_OK, ssh_set_error_oom.
LIBSSH_API int ssh_channel_request_sftp(ssh_channel channel)
Request sftp subsystem on the channel.
channel The channel to request the sftp subsystem. SSH_OK on success, SSH_ERROR if an error occurred, SSH_AGAIN if in nonblocking mode and call has to be done again. You should use sftp_new() which does this for you.
References ssh_channel_request_subsystem, SSH_ERROR.
Referenced by channel_request_sftp.
LIBSSH_API int ssh_channel_request_subsystem(ssh_channel channel, const char *subsystem)
Request a subsystem (for example "sftp").
channel The channel to send the request. subsys The subsystem to request (for example "sftp"). SSH_OK on success, SSH_ERROR if an error occurred, SSH_AGAIN if in nonblocking mode and call has to be done again. You normally don't have to call it for sftp, see sftp_new().
References buffer, channel_request, error, rc, ssh_channel_struct::request_state, ssh_channel_struct::session, SSH_BUFFER_FREE, ssh_buffer_new, ssh_buffer_pack, SSH_CHANNEL_REQ_STATE_NONE, SSH_ERROR, SSH_OK, ssh_set_error_invalid, ssh_set_error_oom.
Referenced by channel_request_subsystem, ssh::Channel::requestSubsystem, ssh_channel_request_sftp.
LIBSSH_API int ssh_channel_request_x11(ssh_channel channel, int single_connection, const char *protocol, const char *cookie, int screen_number)
Sends the "x11-req" channel request over an existing session channel.
This will enable redirecting the display of the remote X11 applications to local X server over an secure tunnel. channel An existing session channel where the remote X11 applications are going to be executed. single_connection A boolean to mark only one X11 app will be redirected. protocol A x11 authentication protocol. Pass NULL to use the default value MIT-MAGIC-COOKIE-1. cookie A x11 authentication cookie. Pass NULL to generate a random cookie. screen_number The screen number. SSH_OK on success, SSH_ERROR if an error occurred, SSH_AGAIN if in nonblocking mode and call has to be done again.
References buffer, channel_request, error, generate_cookie, rc, ssh_channel_struct::request_state, SAFE_FREE, ssh_channel_struct::session, SSH_BUFFER_FREE, ssh_buffer_new, ssh_buffer_pack, SSH_CHANNEL_REQ_STATE_NONE, SSH_ERROR, SSH_OK, ssh_set_error_oom.
Referenced by channel_request_x11, client_thread, ssh::Channel::requestX11.
LIBSSH_API int ssh_channel_request_auth_agent(ssh_channel channel)
Send an "auth-agent-req" channel request over an existing session channel.
This client-side request will enable forwarding the agent over an secure tunnel. When the server is ready to open one authentication agent channel, an ssh_channel_open_request_auth_agent_callback event will be generated. channel The channel to send signal. SSH_OK on success, SSH_ERROR if an error occurred
References channel_request, SSH_ERROR.
LIBSSH_API int ssh_channel_send_eof(ssh_channel channel)
Send an end of file on the channel.
This doesn't close the channel. You may still read from it but not write. channel The channel to send the eof to. SSH_OK on success, SSH_ERROR if an error occurred. Example: rc=ssh_channel_send_eof(channel); if(rc==SSH_ERROR){ return-1; } while(!ssh_channel_is_eof(channel)){ rc=ssh_channel_read(channel,buf,sizeof(buf),0); if(rc==SSH_ERROR){ return-1; } } ssh_channel_close(channel); ssh_channel_close() ssh_channel_free() ssh_channel_is_eof()
References error, ssh_channel_struct::local_channel, ssh_channel_struct::local_eof, ssh_session_struct::out_buffer, rc, ssh_channel_struct::remote_channel, ssh_channel_struct::session, session, SSH2_MSG_CHANNEL_EOF, ssh_buffer_pack, ssh_buffer_reinit, ssh_channel_flush, SSH_ERROR, SSH_LOG, SSH_LOG_PACKET, SSH_OK, ssh_packet_send, ssh_set_error_oom.
Referenced by channel_send_eof, default_handle_session_cb, do_connect, handle_kbdint_session_cb, handle_session, main, my_fd_data_function, pkd_exec_hello, select_loop, ssh::Channel::sendEof, ssh_channel_close, ssh_connector_channel_write_wontblock_cb, ssh_connector_fd_in_cb, ssh_scp_close, torture_ssh_forward, upload_script.
LIBSSH_API int ssh_channel_select(ssh_channel *readchans, ssh_channel *writechans, ssh_channel *exceptchans, struct timeval *timeout)
Act like the standard select(2) on channels.
The list of pointers are then actualized and will only contain pointers to channels that are respectively readable, writable or have an exception to trap. readchans A NULL pointer or an array of channel pointers, terminated by a NULL. writechans A NULL pointer or an array of channel pointers, terminated by a NULL. exceptchans A NULL pointer or an array of channel pointers, terminated by a NULL. timeout Timeout as defined by select(2). SSH_OK on a successful operation, SSH_EINTR if the select(2) syscall was interrupted, then relaunch the function, or SSH_ERROR on error.
References channel_protocol_select, count_ptrs, rc, SAFE_FREE, session, SSH_ERROR, ssh_event_add_session, ssh_event_dopoll, ssh_event_free, ssh_event_new, SSH_OK, ssh_poll_get_default_ctx, ssh_timeout_elapsed, SSH_TIMEOUT_INFINITE, ssh_timeout_update, ssh_timestamp_init.
Referenced by channel_select.
LIBSSH_API void ssh_channel_set_blocking(ssh_channel channel, int blocking)
Put the channel into blocking or nonblocking mode.
channel The channel to use. blocking A boolean for blocking or nonblocking. A side-effect of this is to put the whole session in non-blocking mode. ssh_set_blocking()
References ssh_channel_struct::session, ssh_set_blocking.
Referenced by channel_set_blocking.
LIBSSH_API void ssh_channel_set_counter(ssh_channel channel, ssh_counter counter)
Set the channel data counter.
structssh_counter_structcounter={ .in_bytes=0, .out_bytes=0, .in_packets=0, .out_packets=0 }; ssh_channel_set_counter(channel,&counter); channel The SSH channel. counter Counter for bytes handled by the channel.
References ssh_channel_struct::counter.
LIBSSH_API int ssh_channel_write(ssh_channel channel, const void *data, uint32_t len)
Blocking write on a channel.
channel The channel to write to. data A pointer to the data to write. len The length of the buffer to write to. The number of bytes written, SSH_ERROR on error. ssh_channel_read()
References channel_write_common, ssh_iterator::data.
Referenced by atomicio, benchmarks_raw_down, benchmarks_raw_up, channel_write, do_connect, main, my_fd_data_function, pkd_exec_hello, process_stdout, select_loop, ssh_connector_channel_data_cb, ssh_connector_channel_write_wontblock_cb, ssh_connector_fd_in_cb, ssh_scp_accept_request, ssh_scp_deny_request, ssh_scp_init, ssh_scp_leave_directory, ssh_scp_pull_request, ssh_scp_push_directory, ssh_scp_push_file64, ssh_scp_read, ssh_scp_write, upload_script, ssh::Channel::write.
LIBSSH_API int ssh_channel_write_stderr(ssh_channel channel, const void *data, uint32_t len)
Blocking write on a channel stderr.
channel The channel to write to. data A pointer to the data to write. len The length of the buffer to write to. The number of bytes written, SSH_ERROR on error. ssh_channel_read()
References channel_write_common.
Referenced by process_stderr, ssh_connector_channel_data_cb, ssh_connector_fd_in_cb, ssh::Channel::write.
LIBSSH_API uint32_t ssh_channel_window_size(ssh_channel channel)
Get the remote window size.
This is the maximum amounts of bytes the remote side expects us to send before growing the window again. channel The channel to query. The remote window size A nonzero return value does not guarantee the socket is ready to send that much data. Buffering may happen in the local SSH packet buffer, so beware of really big window sizes. A zero return value means ssh_channel_write (default settings) will block until the window grows back.
References ssh_channel_struct::remote_window.
Referenced by ssh_connector_channel_data_cb, ssh_connector_fd_in_cb, ssh_connector_set_event.
LIBSSH_API char* ssh_basename(const char *path)
basename - parse filename component.
basename breaks a null-terminated pathname string into a filename component. ssh_basename() returns the component following the final '/'. Trailing '/' characters are not counted as part of the pathname. path The path to parse. The filename of path or NULL if we can't allocate memory. If path is a the string "/", basename returns the string "/". If path is NULL or an empty string, "." is returned.
References s.
Referenced by session_setup, ssh_scp_push_directory, ssh_scp_push_file64, torture_basename.
LIBSSH_API void ssh_clean_pubkey_hash(unsigned char **hash)
Deallocate the hash obtained by ssh_get_pubkey_hash.
This is required under Microsoft platform as this library might use a different C library than your software, hence a different heap. hash The buffer to deallocate. ssh_get_pubkey_hash()
References SAFE_FREE.
Referenced by verify_knownhost.
LIBSSH_API int ssh_connect(ssh_session session)
Connect to the ssh server.
session The ssh session to connect. SSH_OK on success, SSH_ERROR on error. SSH_AGAIN, if the session is in nonblocking mode, and call must be done again. ssh_new() ssh_disconnect()
References ssh_session_struct::alive, ssh_session_struct::bindaddr, callback_receive_banner, ssh_session_struct::client, ssh_session_struct::config_processed, ssh_socket_callbacks_struct::connected, ssh_socket_callbacks_struct::data, ssh_socket_callbacks_struct::exception, ssh_session_struct::fd, ssh_session_struct::host, ssh_session_struct::opts, ssh_session_struct::pending_call_state, ssh_session_struct::port, ssh_session_struct::ProxyCommand, session, ssh_session_struct::session_state, set_status, ssh_session_struct::socket, socket_callback_connected, ssh_session_struct::socket_callbacks, SSH_AGAIN, ssh_client_connection_callback, ssh_connect_termination, ssh_session_struct::ssh_connection_callback, ssh_copyright, SSH_ERROR, SSH_FATAL, ssh_handle_packets_termination, SSH_INVALID_SOCKET, ssh_is_blocking, SSH_LOG, SSH_LOG_PACKET, SSH_LOG_PROTOCOL, SSH_OK, ssh_options_apply, ssh_options_parse_config, SSH_PENDING_CALL_CONNECT, SSH_PENDING_CALL_NONE, SSH_SESSION_STATE_CONNECTING, SSH_SESSION_STATE_DISCONNECTED, SSH_SESSION_STATE_ERROR, SSH_SESSION_STATE_SOCKET_CONNECTED, ssh_set_error, ssh_socket_connect, ssh_socket_connect_proxycommand, ssh_socket_exception_callback, ssh_socket_set_callbacks, ssh_socket_set_fd, ssh_threads_get_type, SSH_TIMEOUT_NONBLOCKING, ssh_session_struct::timeout, ssh_session_struct::timeout_usec, ssh_socket_callbacks_struct::userdata.
Referenced by authenticate, client, ssh::Session::connect, connect_host, connect_ssh, do_connect, LLVMFuzzerTestOneInput, main, ssh_client, test_algorithm, torture_algorithms_zlib, torture_algorithms_zlib_openssh, torture_auth_agent, torture_auth_agent_nonblocking, torture_auth_autopubkey, torture_auth_autopubkey_nonblocking, torture_auth_cert, torture_auth_kbdint, torture_auth_kbdint_nonblocking, torture_auth_none, torture_auth_none_nonblocking, torture_auth_password, torture_auth_password_nonblocking, torture_auth_pubkey_types, torture_auth_pubkey_types_ecdsa, torture_auth_pubkey_types_ecdsa_nonblocking, torture_auth_pubkey_types_ed25519, torture_auth_pubkey_types_ed25519_nonblocking, torture_auth_pubkey_types_nonblocking, torture_client_config_autoparse, torture_client_config_suppress, torture_connect_double, torture_connect_nonblocking, torture_connect_socket, torture_hostkey_ed25519, torture_hostkey_rsa, torture_hostkey_rsa_sha256, torture_hostkey_rsa_sha512, torture_knownhosts_conflict, torture_knownhosts_export, torture_knownhosts_fail, torture_knownhosts_new_file, torture_knownhosts_no_hostkeychecking, torture_knownhosts_other, torture_knownhosts_other_auto, torture_knownhosts_port, torture_knownhosts_standard_port, torture_knownhosts_unknown, torture_knownhosts_wildcard, torture_knownhosts_write_and_verify, torture_options_set_proxycommand_notexist, torture_options_set_proxycommand_ssh, torture_options_set_proxycommand_ssh_stderr, torture_rekey_default, torture_rekey_send, torture_rekey_server_send, torture_rekey_time, torture_server_auth_kbdint, torture_server_auth_none, torture_server_auth_password, torture_server_auth_pubkey, torture_server_hostkey_mismatch, torture_server_unknown_global_request, torture_ssh_session, try_config_content.
LIBSSH_API ssh_connector ssh_connector_new(ssh_session session)
References ssh_channel_callbacks_struct::channel_data_function, ssh_channel_callbacks_struct::channel_write_wontblock_function, ssh_connector_struct::fd_is_socket, ssh_connector_struct::in_channel_cb, ssh_connector_struct::in_fd, ssh_connector_struct::out_channel_cb, ssh_connector_struct::out_fd, ssh_connector_struct::session, session, ssh_callbacks_init, ssh_connector_channel_data_cb, ssh_connector_channel_write_wontblock_cb, SSH_INVALID_SOCKET, ssh_set_error_oom, ssh_channel_callbacks_struct::userdata.
Referenced by select_loop.
LIBSSH_API void ssh_connector_free(ssh_connector connector)
References ssh_connector_struct::event, ssh_connector_struct::in_channel, ssh_connector_struct::in_channel_cb, ssh_connector_struct::in_poll, ssh_connector_struct::out_channel, ssh_connector_struct::out_channel_cb, ssh_connector_struct::out_poll, ssh_connector_remove_event, ssh_poll_free, ssh_remove_channel_callbacks.
Referenced by select_loop.
LIBSSH_API int ssh_connector_set_in_channel(ssh_connector connector, ssh_channel channel, enum ssh_connector_flags_e flags)
References ssh_connector_struct::in_channel, ssh_connector_struct::in_channel_cb, ssh_connector_struct::in_fd, ssh_connector_struct::in_flags, ssh_add_channel_callbacks, SSH_CONNECTOR_STDERR, SSH_CONNECTOR_STDOUT, SSH_INVALID_SOCKET.
Referenced by select_loop.
LIBSSH_API int ssh_connector_set_out_channel(ssh_connector connector, ssh_channel channel, enum ssh_connector_flags_e flags)
References ssh_connector_struct::in_flags, ssh_connector_struct::out_channel, ssh_connector_struct::out_channel_cb, ssh_connector_struct::out_fd, ssh_connector_struct::out_flags, ssh_add_channel_callbacks, SSH_CONNECTOR_STDERR, SSH_CONNECTOR_STDOUT, SSH_INVALID_SOCKET.
Referenced by select_loop.
LIBSSH_API void ssh_connector_set_in_fd(ssh_connector connector, socket_t fd)
References ssh_connector_struct::fd_is_socket, ssh_connector_struct::in_channel, ssh_connector_struct::in_fd, ssh_connector_fd_is_socket.
Referenced by select_loop.
LIBSSH_API void ssh_connector_set_out_fd(ssh_connector connector, socket_t fd)
References ssh_connector_struct::fd_is_socket, ssh_connector_struct::out_channel, ssh_connector_struct::out_fd, ssh_connector_fd_is_socket.
Referenced by select_loop.
LIBSSH_API const char* ssh_copyright(void)
References LIBSSH_VERSION, SSH_STRINGIFY.
Referenced by ssh_connect.
LIBSSH_API void ssh_disconnect(ssh_session session)
Disconnect from a session (client or server). The session can then be reused to open a new session.
session The SSH session to use.
References ssh_session_struct::alive, ssh_session_struct::auth, ssh_session_struct::channels, ssh_session_struct::clientbanner, crypto_free, crypto_new, ssh_session_struct::current_crypto, error, ssh_session_struct::fd, ssh_session_struct::in_buffer, ssh_session_struct::in_hashbuf, ssh_session_struct::next_crypto, ssh_session_struct::opts, ssh_session_struct::out_buffer, ssh_session_struct::out_hashbuf, ssh_session_struct::packet_callbacks, rc, ssh_session_struct::recv_seq, SAFE_FREE, ssh_session_struct::send_seq, ssh_session_struct::serverbanner, session, ssh_session_struct::session_state, ssh_session_struct::socket, SSH2_DISCONNECT_BY_APPLICATION, SSH2_MSG_DISCONNECT, ssh_buffer_pack, ssh_buffer_reinit, ssh_channel_do_free, SSH_INVALID_SOCKET, ssh_iterator_value, ssh_list_free, ssh_list_get_iterator, ssh_list_pop_head, ssh_list_remove, ssh_message_free, ssh_session_struct::ssh_message_list, SSH_OK, ssh_packet_send, SSH_SESSION_STATE_DISCONNECTED, ssh_set_error_oom, ssh_socket_close, ssh_socket_is_open, ssh_socket_reset, ssh_session_struct::supported_methods.
Referenced by auth_password, connect_host, connect_ssh, ssh::Session::disconnect, docycle, LLVMFuzzerTestOneInput, main, pkd_exec_hello, run_server, session_teardown, ssh_silent_disconnect, teardown, test_algorithm, torture_algorithms_zlib, torture_algorithms_zlib_openssh, torture_connect_double, torture_connect_failure, torture_hostkey_ed25519, torture_hostkey_rsa, torture_hostkey_rsa_sha256, torture_hostkey_rsa_sha512, torture_knownhosts_conflict, torture_knownhosts_other_auto, torture_knownhosts_port, torture_knownhosts_unknown, torture_rekey_default, torture_rekey_send, torture_rekey_server_send, torture_rekey_time, torture_ssh_session.
LIBSSH_API char* ssh_dirname(const char *path)
Parse directory component.
dirname breaks a null-terminated pathname string into a directory component. In the usual case, ssh_dirname() returns the string up to, but not including, the final '/'. Trailing '/' characters are not counted as part of the pathname. The caller must free the memory. path The path to parse. The dirname of path or NULL if we can't allocate memory. If path does not contain a slash, c_dirname() returns the string ".". If path is the string "/", it returns the string "/". If path is NULL or an empty string, "." is returned.
Referenced by ssh_known_hosts_check_server_key, ssh_mkdirs, ssh_write_knownhost, torture_dirname.
LIBSSH_API int ssh_finalize(void)
Finalize and cleanup all libssh and cryptographic data structures.
Since version 0.8.0, it is not necessary to call this function, since it is automatically called when the library is unloaded. If ssh_init() is called explicitly, then ssh_finalize() must be called explicitly. When called, decrements the counter _ssh_initialized. If the counter reaches zero, then the libssh and cryptographic data structures are cleaned up. 0 on succes, -1 if an error occured. 0 otherwise
References _ssh_finalize.
Referenced by connect_host, LLVMFuzzerTestOneInput, main, teardown, thread_ssh_init, torture_run_tests, torture_ssh_init, torture_ssh_init_after_finalize.
LIBSSH_API ssh_channel ssh_channel_accept_forward(ssh_session session, int timeout_ms, int *destination_port)
Accept an incoming TCP/IP forwarding channel and get information about incomming connection.
session The ssh session to use. timeout_ms A timeout in milliseconds. destination_port A pointer to destination port or NULL. Newly created channel, or NULL if no incoming channel request from the server
References session, ssh_channel_accept, SSH_CHANNEL_FORWARDED_TCPIP.
Referenced by ssh::Session::acceptForward, channel_forward_accept, torture_ssh_forward.
LIBSSH_API int ssh_channel_cancel_forward(ssh_session session, const char *address, int port)
Sends the "cancel-tcpip-forward" global request to ask the server to cancel the tcpip-forward request.
session The ssh session to send the request. address The bound address on the server. port The bound port on the server. SSH_OK on success, SSH_ERROR if an error occurred, SSH_AGAIN if in nonblocking mode and call has to be done again.
References buffer, error, ssh_session_struct::global_req_state, port, rc, session, SSH_BUFFER_FREE, ssh_buffer_new, ssh_buffer_pack, SSH_CHANNEL_REQ_STATE_NONE, SSH_ERROR, ssh_global_request, SSH_OK, ssh_set_error_oom.
Referenced by ssh::Session::cancelForward, channel_forward_cancel, ssh_forward_cancel.
LIBSSH_API int ssh_channel_listen_forward(ssh_session session, const char *address, int port, int *bound_port)
Sends the "tcpip-forward" global request to ask the server to begin listening for inbound connections.
session The ssh session to send the request. address The address to bind to on the server. Pass NULL to bind to all available addresses on all protocol families supported by the server. port The port to bind to on the server. Pass 0 to ask the server to allocate the next available unprivileged port number bound_port The pointer to get actual bound port. Pass NULL to ignore. SSH_OK on success, SSH_ERROR if an error occurred, SSH_AGAIN if in nonblocking mode and call has to be done again.
References buffer, error, ssh_session_struct::global_req_state, ssh_session_struct::in_buffer, port, rc, session, SSH_BUFFER_FREE, ssh_buffer_new, ssh_buffer_pack, ssh_buffer_unpack, SSH_CHANNEL_REQ_STATE_NONE, SSH_ERROR, ssh_global_request, SSH_OK, ssh_set_error_oom.
Referenced by channel_forward_listen, ssh::Session::listenForward, ssh_forward_listen, torture_ssh_forward.
LIBSSH_API void ssh_free(ssh_session session)
Deallocate a SSH session handle.
session The SSH session to free. ssh_disconnect() ssh_new()
References ssh_session_struct::agent, ssh_session_struct::agent_state, ssh_session_struct::auth, ssh_session_struct::auto_state, ssh_session_struct::banner, ssh_session_struct::bindaddr, ssh_session_struct::channels, ssh_session_struct::clientbanner, crypto_free, ssh_session_struct::current_crypto, ssh_session_struct::custombanner, ssh_session_struct::default_poll_ctx, ssh_session_struct::dsa_key, ssh_session_struct::ecdsa_key, ssh_session_struct::ed25519_key, explicit_bzero, ssh_session_struct::global_knownhosts, ssh_session_struct::gss_client_identity, ssh_session_struct::gss_server_identity, ssh_session_struct::host, ssh_session_struct::identity, ssh_session_struct::in_buffer, ssh_session_struct::in_hashbuf, ssh_session_struct::kbdint, ssh_session_struct::knownhosts, ssh_session_struct::next_crypto, ssh_session_struct::opts, ssh_session_struct::out_buffer, ssh_session_struct::out_hashbuf, ssh_session_struct::out_queue, ssh_session_struct::packet_callbacks, ssh_session_struct::ProxyCommand, ssh_session_struct::pubkey_accepted_types, ssh_session_struct::rsa_key, SAFE_FREE, ssh_session_struct::serverbanner, session, ssh_session_struct::socket, ssh_session_struct::srv, ssh_agent_free, ssh_agent_state_free, SSH_BUFFER_FREE, ssh_channel_do_free, ssh_iterator_value, ssh_kbdint_free, SSH_KEX_METHODS, ssh_key_free, ssh_list_free, ssh_list_get_iterator, ssh_list_pop_head, ssh_list_remove, ssh_message_free, ssh_session_struct::ssh_message_list, ssh_poll_ctx_free, ssh_socket_free, ssh_session_struct::sshdir, ssh_session_struct::username, ssh_session_struct::wanted_methods.
Referenced by check_message_in_all_states, client_thread, connect_host, connect_ssh, LLVMFuzzerTestOneInput, main, pkd_exec_hello, run_server, session_teardown, setup_both_keys, ssh_new, ssh_options_copy, teardown, test_ssh_channel_request_x11, thread_pki_rsa_generate_key, torture_knownhosts_algorithms, torture_knownhosts_algorithms_global, torture_knownhosts_algorithms_negative, torture_knownhosts_algorithms_wanted, torture_knownhosts_conflict, torture_knownhosts_get_algorithms_names, torture_knownhosts_host_exists, torture_knownhosts_host_exists_global, torture_knownhosts_other_auto, torture_knownhosts_port, torture_knownhosts_unknown, torture_options_copy, torture_packet, torture_packet_filter_check_unfiltered, torture_pki_dsa_cert_verify, torture_pki_dsa_generate_key, torture_pki_ecdsa_cert_verify, torture_pki_ed25519_cert_verify, torture_pki_ed25519_generate_key, torture_pki_ed25519_verify, torture_pki_ed25519_verify_bad, torture_pki_generate_key_ecdsa, torture_pki_rsa_generate_key, torture_pki_rsa_sha2, torture_pki_sign_verify_uri, torture_pki_verify_mismatch, torture_ssh_analyze_banner, torture_ssh_session, ssh::Session::~Session.
LIBSSH_API const char* ssh_get_disconnect_message(ssh_session session)
Get the disconnect message from the server.
session The ssh session to use. The message sent by the server along with the disconnect, or NULL in which case the reason of the disconnect may be found with ssh_get_error. ssh_get_error()
References ssh_session_struct::discon_msg, session, ssh_session_struct::session_state, SSH_FATAL, SSH_REQUEST_DENIED, SSH_SESSION_STATE_DISCONNECTED, ssh_set_error.
Referenced by ssh::Session::getDisconnectMessage.
LIBSSH_API const char* ssh_get_error(void *error)
Retrieve the error text message from the last error.
error An ssh_session or ssh_bind. A static string describing the error.
References error, error_struct::error_buffer.
Referenced by _assert_ssh_return_code, _assert_ssh_return_code_equal, _assert_ssh_return_code_not_equal, authenticate, batch_shell, benchmarks_async_sftp_down, benchmarks_raw_down, benchmarks_raw_up, benchmarks_scp_down, benchmarks_scp_up, benchmarks_ssh_latency, benchmarks_sync_sftp_down, benchmarks_sync_sftp_up, channel_new_session_cb, client, connect_host, connect_ssh, create_files, default_handle_session_cb, do_connect, error, fetch_files, forwarding, ssh::Session::getError, handle_kbdint_session_cb, handle_session, main, pkd_channel_openreq_cb, pkd_exec_hello, run_server, select_loop, set_opts, sftp_test, shell, ssh_client, SSH_PACKET_CALLBACK, ssh_packet_process, ssh_server, ssh_try_publickey_from_file, ssh::SshException::SshException, torture_sftp_mkdir, upload_script, verify_knownhost.
LIBSSH_API int ssh_get_error_code(void *error)
Retrieve the error code from the last error.
error An ssh_session or ssh_bind. SSH_NO_ERROR No error occurred SSH_REQUEST_DENIED The last request was denied but situation is recoverable SSH_FATAL A fatal error occurred. This could be an unexpected disconnection Other error codes are internal but can be considered same than SSH_FATAL.
References error, error_struct::error_code.
Referenced by benchmarks_ssh_latency, ssh::Session::getErrorCode, ssh::SshException::SshException, test_algorithm, torture_algorithms_zlib, torture_algorithms_zlib_openssh, torture_auth_agent, torture_auth_agent_nonblocking, torture_auth_autopubkey, torture_auth_autopubkey_nonblocking, torture_auth_kbdint, torture_auth_kbdint_nonblocking, torture_auth_none, torture_auth_none_nonblocking, torture_auth_password, torture_auth_password_nonblocking, torture_auth_pubkey_types, torture_auth_pubkey_types_ecdsa, torture_auth_pubkey_types_ecdsa_nonblocking, torture_auth_pubkey_types_ed25519, torture_auth_pubkey_types_ed25519_nonblocking, torture_auth_pubkey_types_nonblocking, torture_rekey_send, torture_rekey_server_send, torture_rekey_time, torture_server_auth_kbdint, torture_server_auth_none, torture_server_auth_password, torture_server_auth_pubkey, try_config_content.
LIBSSH_API socket_t ssh_get_fd(ssh_session session)
Get the fd of a connection.
In case you'd need the file descriptor of the connection to the server/client. session The ssh session to use. The file descriptor of the connection, or -1 if it is not connected
References session, ssh_session_struct::socket, ssh_socket_get_fd.
Referenced by ssh::Session::getSocket, select_loop, torture_channel_read_error, torture_options_set_proxycommand_ssh, torture_options_set_proxycommand_ssh_stderr.
LIBSSH_API char* ssh_get_hexa(const unsigned char *what, size_t len)
Convert a buffer into a colon separated hex string. The caller has to free the memory.
what What should be converted to a hex string. len Length of the buffer to convert. The hex string or NULL on error. ssh_string_free_char()
Referenced by ssh_get_fingerprint_hash, ssh_gssapi_match, SSH_PACKET_CALLBACK, ssh_print_hexa, torture_md5_hash.
LIBSSH_API char* ssh_get_issue_banner(ssh_session session)
Get the issue banner from the server.
This is the banner showing a disclaimer to users who log in, typically their right or the fact that they will be monitored. session The SSH session to use. A newly allocated string with the banner, NULL on error.
References ssh_session_struct::banner, session, ssh_string_to_char.
Referenced by authenticate_console, client, ssh::Session::getIssueBanner.
LIBSSH_API int ssh_get_openssh_version(ssh_session session)
Get the version of the OpenSSH server, if it is not an OpenSSH server then 0 will be returned.
You can use the SSH_VERSION_INT macro to compare version numbers. session The SSH session to use. The version number if available, 0 otherwise. intopenssh=ssh_get_openssh_version(); if(openssh==SSH_INT_VERSION(6,1,0)){ printf("Versionmatch!\m"); }
References ssh_session_struct::openssh, session.
Referenced by ssh::Session::getOpensshVersion, ssh_channel_open_forward_unix, torture_algorithms_zlib, torture_algorithms_zlib_openssh.
LIBSSH_API int ssh_get_server_publickey(ssh_session session, ssh_key *key)
Get the server public key from a session.
session The session to get the key from. key A pointer to store the allocated key. You need to free the key. SSH_OK on success, SSH_ERROR on errror. ssh_key_free()
References ssh_session_struct::current_crypto, key, pubkey, ssh_crypto_struct::server_pubkey, session, SSH_ERROR, ssh_key_dup, SSH_OK.
Referenced by ssh_get_pubkey_hash, ssh_get_publickey, verify_knownhost.
LIBSSH_API int ssh_get_publickey_hash(const ssh_key key, enum ssh_publickey_hash_type type, unsigned char **hash, size_t *hlen)
Allocates a buffer with the hash of the public key.
This function allows you to get a hash of the public key. You can then print this hash in a human-readable form to the user so that he is able to verify it. Use ssh_get_hexa() or ssh_print_hash() to display it. key The public key to create the hash for. type The type of the hash you want. hash A pointer to store the allocated buffer. It can be freed using ssh_clean_pubkey_hash(). hlen The length of the hash. 0 on success, -1 if an error occured. It is very important that you verify at some moment that the hash matches a known server. If you don't do it, cryptography wont help you at making things secure. OpenSSH uses SHA256 to print public key digests. ssh_session_update_known_hosts() ssh_get_hexa() ssh_print_hash() ssh_clean_pubkey_hash()
References ctx, key, MD5_DIGEST_LEN, md5_final, md5_init, md5_update, rc, sha1_final, sha1_init, sha1_update, sha256_final, sha256_init, sha256_update, SSH_ERROR, SSH_LOG, SSH_LOG_WARN, ssh_pki_export_pubkey_blob, SSH_PUBLICKEY_HASH_MD5, SSH_PUBLICKEY_HASH_SHA1, SSH_PUBLICKEY_HASH_SHA256, ssh_string_data, SSH_STRING_FREE, ssh_string_len.
Referenced by torture_md5_hash, torture_sha1_hash, torture_sha256_fingerprint, torture_sha256_hash, verify_knownhost.
SSH_DEPRECATED LIBSSH_API int ssh_get_pubkey_hash(ssh_session session, unsigned char **hash)
DeprecatedUse ssh_get_publickey_hash()
References ctx, ssh_session_struct::current_crypto, MD5_DIGEST_LEN, md5_final, md5_init, md5_update, pubkey, rc, SAFE_FREE, ssh_crypto_struct::server_pubkey, session, SSH_ERROR, SSH_FATAL, ssh_get_server_publickey, ssh_key_free, SSH_OK, ssh_pki_export_pubkey_blob, ssh_set_error, ssh_string_data, SSH_STRING_FREE, ssh_string_len.
SSH_DEPRECATED LIBSSH_API ssh_channel ssh_forward_accept(ssh_session session, int timeout_ms)
References session, ssh_channel_accept, SSH_CHANNEL_FORWARDED_TCPIP.
SSH_DEPRECATED LIBSSH_API int ssh_forward_cancel(ssh_session session, const char *address, int port)
References port, session, ssh_channel_cancel_forward.
SSH_DEPRECATED LIBSSH_API int ssh_forward_listen(ssh_session session, const char *address, int port, int *bound_port)
References port, session, ssh_channel_listen_forward.
SSH_DEPRECATED LIBSSH_API int ssh_get_publickey(ssh_session session, ssh_key *key)
DeprecatedUse ssh_get_server_publickey()
References key, session, ssh_get_server_publickey.
SSH_DEPRECATED LIBSSH_API int ssh_write_knownhost(ssh_session session)
This function is deprecated.
DeprecatedPlease use ssh_session_update_known_hosts()
References buffer, ssh_session_struct::knownhosts, ssh_session_struct::opts, rc, SAFE_FREE, session, ssh_dirname, SSH_ERROR, SSH_FATAL, ssh_mkdirs, SSH_OK, ssh_options_apply, ssh_session_export_known_hosts_entry, ssh_set_error.
Referenced by torture_knownhosts_conflict, torture_knownhosts_other_auto, torture_knownhosts_port.
SSH_DEPRECATED LIBSSH_API char* ssh_dump_knownhost(ssh_session session)
This function is deprecated.
DeprecatedPlease use ssh_session_export_known_hosts_entry()
References buffer, ssh_session_struct::current_crypto, host, ssh_session_struct::host, ssh_session_struct::opts, ssh_session_struct::port, rc, SAFE_FREE, session, ssh_dh_get_current_server_publickey, SSH_FATAL, ssh_hostport, ssh_lowercase, ssh_pki_export_pubkey_base64, ssh_set_error, ssh_key_struct::type_c.
SSH_DEPRECATED LIBSSH_API int ssh_is_server_known(ssh_session session)
This function is deprecated.
DeprecatedPlease use ssh_session_is_known_server() ssh_session_is_known_server()
References check_public_key, ssh_session_struct::current_crypto, ssh_session_struct::global_knownhosts, host, ssh_session_struct::host, ssh_session_struct::knownhosts, match_hashed_host, match_hostname, ssh_session_struct::opts, ssh_session_struct::port, pubkey, SAFE_FREE, session, ssh_dh_get_current_server_publickey, SSH_FATAL, ssh_get_knownhost_line, ssh_hostport, ssh_key_type, ssh_key_type_to_char, SSH_LOG, SSH_LOG_PACKET, ssh_lowercase, SSH_OK, ssh_options_apply, SSH_REQUEST_DENIED, SSH_SERVER_ERROR, SSH_SERVER_FILE_NOT_FOUND, SSH_SERVER_FOUND_OTHER, SSH_SERVER_KNOWN_CHANGED, SSH_SERVER_KNOWN_OK, SSH_SERVER_NOT_KNOWN, ssh_session_update_known_hosts, ssh_set_error, ssh_set_error_oom, ssh_tokens_free, ssh_session_struct::StrictHostKeyChecking, ssh_tokens_st::tokens.
Referenced by torture_knownhosts_conflict, torture_knownhosts_fail, torture_knownhosts_other, torture_knownhosts_other_auto, torture_knownhosts_port, torture_knownhosts_standard_port, torture_knownhosts_wildcard.
SSH_DEPRECATED LIBSSH_API void ssh_print_hexa(const char *descr, const unsigned char *what, size_t len)
DeprecatedPlease use ssh_print_hash() instead
References ssh_get_hexa.
LIBSSH_API int ssh_get_random(void *where, int len, int strong)
Referenced by crypto_sign_ed25519_keypair, generate_cookie, packet_send2, server_set_kex, ssh_pki_openssh_privkey_export, ssh_set_client_kex, torture_rand_thread.
LIBSSH_API int ssh_get_version(ssh_session session)
Get the protocol version of the session.
session The ssh session to use. The SSH version as integer, < 0 on error.
References session.
Referenced by ssh::Session::getVersion.
LIBSSH_API int ssh_get_status(ssh_session session)
Get session status.
session The ssh session to use. A bitmask including SSH_CLOSED, SSH_READ_PENDING, SSH_WRITE_PENDING or SSH_CLOSED_ERROR which respectively means the session is closed, has data to read on the connection socket and session was closed due to an error.
References session, ssh_session_struct::session_state, ssh_session_struct::socket, SSH_CLOSED, SSH_CLOSED_ERROR, SSH_READ_PENDING, SSH_SESSION_STATE_DISCONNECTED, SSH_SESSION_STATE_ERROR, ssh_socket_get_status, SSH_WRITE_PENDING.
Referenced by default_handle_session_cb, handle_kbdint_session_cb, handle_session.
LIBSSH_API int ssh_get_poll_flags(ssh_session session)
Get poll flags for an external mainloop.
session The ssh session to use. A bitmask including SSH_READ_PENDING or SSH_WRITE_PENDING. For SSH_READ_PENDING, your invocation of poll() should include POLLIN. For SSH_WRITE_PENDING, your invocation of poll() should include POLLOUT.
References session, ssh_session_struct::socket, ssh_socket_get_poll_flags.
LIBSSH_API int ssh_init(void)
Initialize global cryptographic data structures.
Since version 0.8.0, it is not necessary to call this function on systems which are fully supported with regards to threading (that is, system with pthreads available). If the library is already initialized, increments the _ssh_initialized counter and return the error code cached in _ssh_init_ret. SSH_OK on success, SSH_ERROR if an error occurred.
Referenced by LLVMFuzzerTestOneInput, main, setup, thread_ssh_init, torture_run_tests, torture_ssh_init, torture_ssh_init_after_finalize.
LIBSSH_API int ssh_is_blocking(ssh_session session)
Return the blocking mode of libssh.
session The SSH session 0 if the session is nonblocking, 1 if the functions may block.
References ssh_session_struct::flags, session, SSH_SESSION_FLAG_BLOCKING.
Referenced by my_fd_data_function, ssh_channel_read_nonblocking, ssh_connect, ssh_handle_packets, ssh_handle_packets_termination.
LIBSSH_API int ssh_is_connected(ssh_session session)
Check if we are connected.
session The session to check if it is connected. 1 if we are connected, 0 if not.
References ssh_session_struct::alive, session.
Referenced by pkd_exec_hello, torture_ssh_session.
LIBSSH_API void ssh_knownhosts_entry_free(struct ssh_knownhosts_entry *entry)
Free an allocated ssh_knownhosts_entry.
Use SSH_KNOWNHOSTS_ENTRY_FREE() to set the pointer to NULL. entry The entry to free.
References ssh_knownhosts_entry::comment, ssh_knownhosts_entry::hostname, ssh_knownhosts_entry::publickey, SAFE_FREE, ssh_key_free, ssh_knownhosts_entry::unparsed.
Referenced by ssh_known_hosts_get_algorithms, ssh_known_hosts_get_algorithms_names, ssh_known_hosts_parse_line, ssh_known_hosts_read_entries.
LIBSSH_API int ssh_known_hosts_parse_line(const char *host, const char *line, struct ssh_knownhosts_entry **entry)
Parse a line from a known_hosts entry into a structure.
This parses an known_hosts entry into a structure with the key in a libssh consumeable form. You can use the PKI key function to further work with it. hostname The hostname to match the line to line The line to compare and parse if we have a hostname match. entry A pointer to store the the allocated known_hosts entry structure. The user needs to free the memory using SSH_KNOWNHOSTS_ENTRY_FREE(). SSH_OK on success, SSH_ERROR otherwise.
References ssh_knownhosts_entry::comment, ssh_knownhosts_entry::hostname, match_hashed_hostname, match_hostname, ssh_knownhosts_entry::publickey, rc, SAFE_FREE, SSH_AGAIN, SSH_ERROR, ssh_hostport, ssh_key_type_from_name, ssh_key_type_to_char, SSH_KEYTYPE_UNKNOWN, ssh_knownhosts_entry_free, SSH_LOG, SSH_LOG_WARN, SSH_OK, ssh_pki_import_pubkey_base64, ssh_knownhosts_entry::unparsed.
Referenced by ssh_known_hosts_read_entries, torture_knownhosts_parse_line_default_ed25519, torture_knownhosts_parse_line_ecdsa, torture_knownhosts_parse_line_hashed_ed25519, torture_knownhosts_parse_line_pattern_ed25519, torture_knownhosts_parse_line_port_ed25519, torture_knownhosts_parse_line_port_wildcard, torture_knownhosts_parse_line_rsa, torture_knownhosts_parse_line_standard_port.
LIBSSH_API enum ssh_known_hosts_e ssh_session_has_known_hosts_entry(ssh_session session)
Check if the set hostname and port matches an entry in known_hosts.
This check if the set hostname and port has an entry in the known_hosts file. You need to set at least the hostname using ssh_options_set(). session The session with with the values set to check. A ssh_known_hosts_e return value.
Referenced by torture_knownhosts_host_exists, torture_knownhosts_host_exists_global.
LIBSSH_API int ssh_session_export_known_hosts_entry(ssh_session session, char **pentry_string)
Export the current session information to a known_hosts string.
This exports the current information of a session which is connected so a ssh server into an entry line which can be added to a known_hosts file. session The session with information to export. pentry_string A pointer to a string to store the alloocated line of the entry. The user must free it using ssh_string_free_char(). SSH_OK on succcess, SSH_ERROR otherwise.
References ssh_session_struct::current_crypto, host, ssh_session_struct::host, ssh_session_struct::opts, rc, SAFE_FREE, session, ssh_dh_get_current_server_publickey, SSH_ERROR, SSH_FATAL, SSH_OK, ssh_pki_export_pubkey_base64, ssh_session_get_host_port, ssh_set_error, ssh_set_error_invalid, ssh_key_struct::type_c.
Referenced by ssh_known_hosts_check_server_key, ssh_write_knownhost, torture_knownhosts_export.
LIBSSH_API int ssh_session_update_known_hosts(ssh_session session)
Add the current connected server to the user known_hosts file.
This adds the currently connected server to the known_hosts file by appending a new line at the end. The global known_hosts file is considered read-only so it is not touched by this function. session The session to use to write the entry. SSH_OK on success, SSH_ERROR otherwise.
Referenced by ssh_is_server_known, torture_knownhosts_conflict, torture_knownhosts_new_file, torture_knownhosts_unknown, torture_knownhosts_write_and_verify, verify_knownhost, ssh::Session::writeKnownhost.
LIBSSH_API enum ssh_known_hosts_e ssh_session_get_known_hosts_entry(ssh_session session, struct ssh_knownhosts_entry **pentry)
Get the known_hosts entry for the current connected session.
session The session to validate. pentry A pointer to store the allocated known hosts entry. SSH_KNOWN_HOSTS_OK: The server is known and has not changed. SSH_KNOWN_HOSTS_CHANGED: The server key has changed. Either you are under attack or the administrator changed the key. You HAVE to warn the user about a possible attack. SSH_KNOWN_HOSTS_OTHER: The server gave use a key of a type while we had an other type recorded. It is a possible attack. SSH_KNOWN_HOSTS_UNKNOWN: The server is unknown. User should confirm the public key hash is correct. SSH_KNOWN_HOSTS_NOT_FOUND: The known host file does not exist. The host is thus unknown. File will be created if host key is accepted. SSH_KNOWN_HOSTS_ERROR: There had been an eror checking the host. ssh_knownhosts_entry_free()
LIBSSH_API enum ssh_known_hosts_e ssh_session_is_known_server(ssh_session session)
Check if the servers public key for the connected session is known.
This checks if we already know the public key of the server we want to connect to. This allows to detect if there is a MITM attach going on of if there have been changes on the server we don't know about. session The SSH to validate. SSH_KNOWN_HOSTS_OK: The server is known and has not changed. SSH_KNOWN_HOSTS_CHANGED: The server key has changed. Either you are under attack or the administrator changed the key. You HAVE to warn the user about a possible attack. SSH_KNOWN_HOSTS_OTHER: The server gave use a key of a type while we had an other type recorded. It is a possible attack. SSH_KNOWN_HOSTS_UNKNOWN: The server is unknown. User should confirm the public key hash is correct. SSH_KNOWN_HOSTS_NOT_FOUND: The known host file does not exist. The host is thus unknown. File will be created if host key is accepted. SSH_KNOWN_HOSTS_ERROR: There had been an error checking the host.
Referenced by connect_host, do_connect, ssh::Session::isServerKnown, torture_knownhosts_conflict, torture_knownhosts_new_file, torture_knownhosts_no_hostkeychecking, torture_knownhosts_other, torture_knownhosts_unknown, torture_knownhosts_write_and_verify, torture_server_hostkey_mismatch, verify_knownhost.
LIBSSH_API int ssh_set_log_level(int level)
Set the log level of the library.
level The level to set. SSH_OK on success, SSH_ERROR on error.
References SSH_ERROR, ssh_log_level, SSH_OK.
Referenced by ssh_options_getopt, ssh_options_set, torture_bind_config_full, torture_bind_config_include, torture_bind_config_include_recursive, torture_bind_config_loglevel, torture_bind_config_match_all, torture_bind_config_match_corner_cases, torture_bind_config_match_invalid, torture_bind_config_match_not_allowed, torture_bind_config_match_twice, torture_bind_config_match_unsupported, torture_log_callback.
LIBSSH_API int ssh_get_log_level(void)
Get the log level of the library.
The value of the log level.
References ssh_log_level.
Referenced by _ssh_log, _ssh_set_error, assert_full_bind_config, torture_bind_config_full, torture_bind_config_include, torture_bind_config_include_recursive, torture_bind_config_loglevel, torture_bind_config_match_all, torture_bind_config_match_corner_cases, torture_bind_config_match_invalid, torture_bind_config_match_not_allowed, torture_bind_config_match_twice, torture_bind_config_match_unsupported, torture_config_new.
LIBSSH_API void* ssh_get_log_userdata(void)
Get the userdata of the logging function.
The userdata if set or NULL.
References ssh_log_userdata.
Referenced by ssh_log_function.
LIBSSH_API int ssh_set_log_userdata(void *data)
Set the userdata for the logging function.
data The userdata to set. SSH_OK on success.
References ssh_log_userdata.
Referenced by ssh_set_callbacks, torture_log_callback.
LIBSSH_API void _ssh_log(int verbosity, const char *function, const char *format,...) PRINTF_ATTRIBUTE(3
Referenced by _close_socket, auth_password, do_cleanup, global_request, ssh::Session::log, message_callback, my_channel_close_function, my_channel_data_function, my_channel_eof_function, my_channel_exit_status_function, my_fd_data_function, new_session_channel, open_tcp_socket, service_request, stack_socket_close.
LIBSSH_API void SSH_DEPRECATED LIBSSH_API void ssh_log(ssh_session session, int prioriry, const char *format,...) PRINTF_ATTRIBUTE(3
Referenced by connect_host.
LIBSSH_API void SSH_DEPRECATED LIBSSH_API void LIBSSH_API ssh_channel ssh_message_channel_request_open_reply_accept(ssh_message msg)
References chan, rc, ssh_message_struct::session, ssh_channel_free, ssh_channel_new, ssh_message_channel_request_open_reply_accept_channel.
Referenced by main, message_callback, ssh_channel_accept.
LIBSSH_API int ssh_message_channel_request_open_reply_accept_channel(ssh_message msg, ssh_channel chan)
References chan, ssh_message_struct::channel_request_open, ssh_channel_struct::flags, ssh_channel_struct::local_channel, ssh_channel_struct::local_maxpacket, ssh_channel_struct::local_window, ssh_session_struct::out_buffer, ssh_channel_request_open::packet_size, rc, ssh_channel_struct::remote_channel, ssh_channel_struct::remote_maxpacket, ssh_channel_struct::remote_window, ssh_channel_request_open::sender, ssh_message_struct::session, session, SSH2_MSG_CHANNEL_OPEN_CONFIRMATION, ssh_buffer_pack, SSH_CHANNEL_FLAG_NOT_BOUND, ssh_channel_new_id, SSH_CHANNEL_STATE_OPEN, SSH_ERROR, SSH_LOG, SSH_LOG_PACKET, SSH_OK, ssh_packet_send, ssh_set_error_oom, ssh_channel_struct::state, ssh_channel_request_open::window.
Referenced by ssh_message_channel_request_open_reply_accept.
LIBSSH_API int ssh_message_channel_request_reply_success(ssh_message msg)
References ssh_channel_request::channel, ssh_message_struct::channel_request, ssh_session_struct::out_buffer, rc, ssh_channel_struct::remote_channel, ssh_message_struct::session, SSH2_MSG_CHANNEL_SUCCESS, ssh_buffer_pack, SSH_ERROR, SSH_LOG, SSH_LOG_PACKET, SSH_OK, ssh_packet_send, ssh_set_error_oom, ssh_channel_request::want_reply.
Referenced by main.
LIBSSH_API void ssh_message_free(ssh_message msg)
Free a SSH message.
msg The message to release the memory.
References ssh_message_struct::auth_request, ssh_global_request::bind_address, ssh_message_struct::channel_request, ssh_message_struct::channel_request_open, ssh_channel_request::command, ssh_channel_request_open::destination, explicit_bzero, ssh_message_struct::global_request, ssh_channel_request::modes, ssh_channel_request_open::originator, ssh_auth_request::password, ssh_auth_request::pubkey, SAFE_FREE, ssh_service_request::service, ssh_message_struct::service_request, SSH_CHANNEL_REQUEST_ENV, SSH_CHANNEL_REQUEST_EXEC, SSH_CHANNEL_REQUEST_PTY, SSH_CHANNEL_REQUEST_SUBSYSTEM, SSH_CHANNEL_REQUEST_X11, ssh_key_free, SSH_REQUEST_AUTH, SSH_REQUEST_CHANNEL, SSH_REQUEST_CHANNEL_OPEN, SSH_REQUEST_GLOBAL, SSH_REQUEST_SERVICE, ssh_channel_request::subsystem, ssh_channel_request::TERM, ssh_channel_request::type, ssh_message_struct::type, ssh_auth_request::username, ssh_channel_request::var_name, ssh_channel_request::var_value, ssh_channel_request::x11_auth_cookie, ssh_channel_request::x11_auth_protocol, ZERO_STRUCTP.
Referenced by authenticate, authenticate_callback, main, ssh_channel_accept, ssh_disconnect, ssh_execute_message_callbacks, ssh_free.
LIBSSH_API ssh_message ssh_message_get(ssh_session session)
Retrieve a SSH message from a SSH session.
session The SSH session to get the message. The SSH message received, NULL in case of error, or timeout elapsed. This function blocks until a message has been received. Betterset up a callback if this behavior is unwanted.
References rc, session, ssh_session_struct::session_state, ssh_handle_packets_termination, ssh_list_new, ssh_list_pop_head, ssh_session_struct::ssh_message_list, ssh_message_pop_head, ssh_message_termination, SSH_SESSION_STATE_ERROR, SSH_TIMEOUT_USER.
Referenced by authenticate, main.
LIBSSH_API int ssh_message_subtype(ssh_message msg)
Get the subtype of the message.
msg The message to get the subtype from. The message type or -1 on error.
References ssh_message_struct::auth_request, ssh_message_struct::channel_request, ssh_message_struct::channel_request_open, ssh_message_struct::global_request, ssh_auth_request::method, SSH_REQUEST_AUTH, SSH_REQUEST_CHANNEL, SSH_REQUEST_CHANNEL_OPEN, SSH_REQUEST_GLOBAL, ssh_channel_request_open::type, ssh_global_request::type, ssh_channel_request::type, ssh_message_struct::type.
Referenced by authenticate, authenticate_callback, main, message_callback, ssh_channel_accept.
LIBSSH_API int ssh_message_type(ssh_message msg)
Get the type of the message.
msg The message to get the type from. The message type or -1 on error.
References ssh_message_struct::type.
Referenced by authenticate, authenticate_callback, global_request, main, message_callback, ssh_channel_accept.
LIBSSH_API int ssh_mkdir(const char *pathname, mode_t mode)
Attempts to create a directory with the given pathname.
This is the portable version of mkdir, mode is ignored on Windows systems. pathname The path name to create the directory. mode The permissions to use. 0 on success, < 0 on error with errno set.
Referenced by torture_ssh_dir_writeable.
LIBSSH_API ssh_session ssh_new(void)
Create a new ssh session.
A new ssh_session pointer, NULL on error.
References ssh_session_struct::agent, ssh_session_struct::alive, ssh_session_struct::auth, ssh_session_struct::compressionlevel, crypto_new, ssh_session_struct::dh_handshake_state, DH_STATE_INIT, ssh_session_struct::fd, FIRST_CHANNEL, ssh_session_struct::flags, ssh_session_struct::global_req_state, ssh_session_struct::identity, ssh_session_struct::in_buffer, ssh_session_struct::maxchannel, ssh_session_struct::next_crypto, ssh_session_struct::nodelay, ssh_session_struct::opts, ssh_session_struct::out_buffer, ssh_session_struct::out_queue, ssh_session_struct::packet_state, PACKET_STATE_INIT, ssh_session_struct::pending_call_state, ssh_session_struct::port, rc, ssh_session_struct::service_state, session, ssh_session_struct::session_state, ssh_session_struct::socket, ssh_agent_new, SSH_AUTH_SERVICE_NONE, SSH_AUTH_STATE_NONE, ssh_buffer_new, SSH_CHANNEL_REQ_STATE_NONE, SSH_ERROR, ssh_free, ssh_list_append, ssh_list_new, SSH_OPT_FLAG_GSSAPI_AUTH, SSH_OPT_FLAG_KBDINT_AUTH, SSH_OPT_FLAG_PASSWORD_AUTH, SSH_OPT_FLAG_PUBKEY_AUTH, SSH_PENDING_CALL_NONE, SSH_SESSION_STATE_NONE, ssh_set_blocking, ssh_socket_new, ssh_session_struct::state, ssh_session_struct::StrictHostKeyChecking, ssh_session_struct::supported_methods.
Referenced by check_message_in_all_states, connect_host, connect_ssh, LLVMFuzzerTestOneInput, main, pkd_exec_hello, run_server, ssh::Session::Session, session_setup, setup, setup_both_keys_passphrase, setup_config_files, setup_rsa_key, ssh_client, ssh_options_copy, ssh_server, test_ssh_channel_request_x11, thread_pki_rsa_generate_key, torture_ecdsa_sign_verify_uri, torture_knownhosts_algorithms, torture_knownhosts_algorithms_global, torture_knownhosts_algorithms_negative, torture_knownhosts_algorithms_wanted, torture_knownhosts_conflict, torture_knownhosts_get_algorithms_names, torture_knownhosts_host_exists, torture_knownhosts_host_exists_global, torture_knownhosts_other_auto, torture_knownhosts_port, torture_knownhosts_unknown, torture_packet, torture_packet_filter_check_unfiltered, torture_pki_dsa_cert_verify, torture_pki_dsa_generate_key, torture_pki_ecdsa_cert_verify, torture_pki_ed25519_cert_verify, torture_pki_ed25519_generate_key, torture_pki_ed25519_verify, torture_pki_ed25519_verify_bad, torture_pki_generate_key_ecdsa, torture_pki_rsa_generate_key, torture_pki_rsa_sha2, torture_pki_sign_verify_uri, torture_pki_verify_mismatch, torture_run_tests, torture_ssh_session.
LIBSSH_API int ssh_options_copy(ssh_session src, ssh_session *dest)
Duplicate the options of a session structure.
If you make several sessions with the same options this is useful. You cannot use twice the same option structure in ssh_session_connect. src The session to use to copy the options. dest A pointer to store the allocated session with duplicated options. You have to free the memory. 0 on sucess, -1 on error with errno set. ssh_session_connect()
References ssh_session_struct::bindaddr, ssh_common_struct::callbacks, ssh_session_struct::common, ssh_session_struct::compressionlevel, ssh_session_struct::config_processed, ssh_iterator::data, ssh_session_struct::fd, ssh_session_struct::flags, ssh_session_struct::global_knownhosts, ssh_session_struct::gss_client_identity, ssh_session_struct::gss_delegate_creds, ssh_session_struct::gss_server_identity, ssh_session_struct::host, ssh_session_struct::identity, ssh_session_struct::knownhosts, ssh_common_struct::log_verbosity, ssh_iterator::next, ssh_session_struct::nodelay, ssh_session_struct::options_seen, ssh_session_struct::opts, ssh_session_struct::port, ssh_session_struct::ProxyCommand, ssh_session_struct::pubkey_accepted_types, rc, SAFE_FREE, ssh_free, SSH_KEX_METHODS, ssh_list_append, ssh_list_get_iterator, ssh_list_pop_head, ssh_new, ssh_session_struct::sshdir, ssh_session_struct::StrictHostKeyChecking, ssh_session_struct::timeout, ssh_session_struct::timeout_usec, ssh_session_struct::username, ssh_session_struct::wanted_methods.
Referenced by ssh::Session::optionsCopy, torture_options_copy.
LIBSSH_API int ssh_options_getopt(ssh_session session, int *argcptr, char **argv)
Parse command line arguments.
This is a helper for your application to generate the appropriate options from the command line arguments. The argv array and argc value are changed so that the parsed arguments wont appear anymore in them. The single arguments (without switches) are not parsed. thus, myssh -l user localhost The command wont set the hostname value of options to localhost. session The session to configure. argcptr The pointer to the argument count. argv The arguments list pointer. 0 on success, < 0 on error. ssh_session_new()
References port, SAFE_FREE, session, SSH_ERROR, SSH_FATAL, SSH_OK, SSH_OPTIONS_CIPHERS_C_S, SSH_OPTIONS_CIPHERS_S_C, SSH_OPTIONS_COMPRESSION, SSH_OPTIONS_IDENTITY, SSH_OPTIONS_PORT_STR, ssh_options_set, SSH_OPTIONS_USER, ssh_set_error, ssh_set_error_oom, ssh_set_log_level, user.
Referenced by main, set_opts.
LIBSSH_API int ssh_options_parse_config(ssh_session session, const char *filename)
Parse the ssh config file.
This should be the last call of all options, it may overwrite options which are already set. It requires that the host name is already set with ssh_options_set_host(). session SSH session handle filename The options file to use, if NULL the default ~/.ssh/config will be used. 0 on success, < 0 on error. ssh_options_set_host()
References ssh_session_struct::config_processed, ssh_session_struct::host, ssh_session_struct::opts, session, ssh_config_parse_file, ssh_options_set, SSH_OPTIONS_SSH_DIR, ssh_path_expand_escape, ssh_set_error_invalid, ssh_set_error_oom, ssh_session_struct::sshdir.
Referenced by client, connect_host, ssh::Session::optionsParseConfig, ssh_connect, torture_client_config_emulate, torture_client_config_system, torture_options_config_host, torture_options_config_match, torture_options_config_match_multi, torture_options_copy.
LIBSSH_API int ssh_options_set(ssh_session session, enum ssh_options_e type, const void *value)
This function can set all possible ssh options.
session An allocated SSH session structure. type The option type to set. This could be one of the following: SSH_OPTIONS_HOST: The hostname or ip address to connect to (const char *). SSH_OPTIONS_PORT: The port to connect to (unsigned int *). SSH_OPTIONS_PORT_STR: The port to connect to (const char *). SSH_OPTIONS_FD: The file descriptor to use (socket_t). If you wish to open the socket yourself for a reason or another, set the file descriptor. Don't forget to set the hostname as the hostname is used as a key in the known_host mechanism. SSH_OPTIONS_BINDADDR: The address to bind the client to (const char *). SSH_OPTIONS_USER: The username for authentication (const char *). If the value is NULL, the username is set to the default username. SSH_OPTIONS_SSH_DIR: Set the ssh directory (const char *,format string). If the value is NULL, the directory is set to the default ssh directory. The ssh directory is used for files like known_hosts and identity (private and public key). It may include "%s" which will be replaced by the user home directory. SSH_OPTIONS_KNOWNHOSTS: Set the known hosts file name (const char *,format string). If the value is NULL, the directory is set to the default known hosts file, normally ~/.ssh/known_hosts. The known hosts file is used to certify remote hosts are genuine. It may include "%d" which will be replaced by the user home directory. SSH_OPTIONS_GLOBAL_KNOWNHOSTS: Set the global known hosts file name (const char *,format string). If the value is NULL, the directory is set to the default global known hosts file, normally /etc/ssh/ssh_known_hosts. The known hosts file is used to certify remote hosts are genuine. SSH_OPTIONS_ADD_IDENTITY (or SSH_OPTIONS_IDENTITY): Add a new identity file (const char *, format string) to the identity list. By default identity, id_dsa and id_rsa are checked. The identity used to authenticate with public key will be prepended to the list. It may include "%s" which will be replaced by the user home directory. SSH_OPTIONS_TIMEOUT: Set a timeout for the connection in seconds (long). SSH_OPTIONS_TIMEOUT_USEC: Set a timeout for the connection in micro seconds (long). SSH_OPTIONS_SSH1: Deprecated SSH_OPTIONS_SSH2: Unused SSH_OPTIONS_LOG_VERBOSITY: Set the session logging verbosity (int). The verbosity of the messages. Every log smaller or equal to verbosity will be shown. SSH_LOG_NOLOG: No logging SSH_LOG_WARNING: Only warnings SSH_LOG_PROTOCOL: High level protocol information SSH_LOG_PACKET: Lower level protocol infomations, packet level SSH_LOG_FUNCTIONS: Every function path SSH_OPTIONS_LOG_VERBOSITY_STR: Set the session logging verbosity via a string that will be converted to a numerical value (e.g. "3") and interpreted according to the values of SSH_OPTIONS_LOG_VERBOSITY above (const char *). SSH_OPTIONS_CIPHERS_C_S: Set the symmetric cipher client to server (const char *, comma-separated list). SSH_OPTIONS_CIPHERS_S_C: Set the symmetric cipher server to client (const char *, comma-separated list). SSH_OPTIONS_KEY_EXCHANGE: Set the key exchange method to be used (const char *, comma-separated list). ex: "ecdh-sha2-nistp256,diffie-hellman-group14-sha1,diffie-hellman-group1-sha1" SSH_OPTIONS_HMAC_C_S: Set the Message Authentication Code algorithm client to server (const char *, comma-separated list). SSH_OPTIONS_HMAC_S_C: Set the Message Authentication Code algorithm server to client (const char *, comma-separated list). SSH_OPTIONS_HOSTKEYS: Set the preferred server host key types (const char *, comma-separated list). ex: "ssh-rsa,ssh-dss,ecdh-sha2-nistp256" SSH_OPTIONS_PUBLICKEY_ACCEPTED_TYPES: Set the preferred public key algorithms to be used for authentication (const char *, comma-separated list). ex: "ssh-rsa,rsa-sha2-256,ssh-dss,ecdh-sha2-nistp256" SSH_OPTIONS_COMPRESSION_C_S: Set the compression to use for client to server communication (const char *, "yes", "no" or a specific algorithm name if needed ("zlib","zlib@openssh.com","none"). SSH_OPTIONS_COMPRESSION_S_C: Set the compression to use for server to client communication (const char *, "yes", "no" or a specific algorithm name if needed ("zlib","zlib@openssh.com","none"). SSH_OPTIONS_COMPRESSION: Set the compression to use for both directions communication (const char *, "yes", "no" or a specific algorithm name if needed ("zlib","zlib@openssh.com","none"). SSH_OPTIONS_COMPRESSION_LEVEL: Set the compression level to use for zlib functions. (int, value from 1 to 9, 9 being the most efficient but slower). SSH_OPTIONS_STRICTHOSTKEYCHECK: Set the parameter StrictHostKeyChecking to avoid asking about a fingerprint (int, 0 = false). SSH_OPTIONS_PROXYCOMMAND: Set the command to be executed in order to connect to server (const char *). SSH_OPTIONS_GSSAPI_SERVER_IDENTITY Set it to specify the GSSAPI server identity that libssh should expect when connecting to the server (const char *). SSH_OPTIONS_GSSAPI_CLIENT_IDENTITY Set it to specify the GSSAPI client identity that libssh should expect when connecting to the server (const char *). SSH_OPTIONS_GSSAPI_DELEGATE_CREDENTIALS Set it to specify that GSSAPI should delegate credentials to the server (int, 0 = false). SSH_OPTIONS_PASSWORD_AUTH Set it if password authentication should be used in ssh_userauth_auto_pubkey(). (int, 0=false). Currently without effect (ssh_userauth_auto_pubkey doesn't use password authentication). SSH_OPTIONS_PUBKEY_AUTH Set it if pubkey authentication should be used in ssh_userauth_auto_pubkey(). (int, 0=false). SSH_OPTIONS_KBDINT_AUTH Set it if keyboard-interactive authentication should be used in ssh_userauth_auto_pubkey(). (int, 0=false). Currently without effect (ssh_userauth_auto_pubkey doesn't use keyboard-interactive authentication). SSH_OPTIONS_GSSAPI_AUTH Set it if gssapi authentication should be used in ssh_userauth_auto_pubkey(). (int, 0=false). Currently without effect (ssh_userauth_auto_pubkey doesn't use gssapi authentication). SSH_OPTIONS_NODELAY Set it to disable Nagle's Algorithm (TCP_NODELAY) on the session socket. (int, 0=false) SSH_OPTIONS_PROCESS_CONFIG Set it to false to disable automatic processing of per-user and system-wide OpenSSH configuration files. LibSSH automatically uses these configuration files unless you provide it with this option or with different file (bool). SSH_OPTIONS_REKEY_DATA Set the data limit that can be transferred with a single key in bytes. RFC 4253 Section 9 recommends 1GB of data, while RFC 4344 provides more specific restrictions, that are applied automatically. When specified, the lower value will be used. (uint64_t, 0=default) SSH_OPTIONS_REKEY_TIME Set the time limit for a session before intializing a rekey in seconds. RFC 4253 Section 9 recommends one hour. (uint32_t, 0=off) value The value to set. This is a generic pointer and the datatype which is used should be set according to the type set. 0 on success, < 0 on error.
References ssh_session_struct::bindaddr, ssh_session_struct::common, ssh_session_struct::compressionlevel, ssh_session_struct::config_processed, ssh_session_struct::fd, ssh_session_struct::flags, ssh_session_struct::global_knownhosts, ssh_session_struct::gss_client_identity, ssh_session_struct::gss_delegate_creds, ssh_session_struct::gss_server_identity, ssh_session_struct::host, ssh_session_struct::identity, ssh_session_struct::knownhosts, ssh_common_struct::log_verbosity, ssh_session_struct::nodelay, ssh_session_struct::opts, ssh_session_struct::port, ssh_session_struct::ProxyCommand, ssh_session_struct::pubkey_accepted_types, rc, ssh_session_struct::rekey_data, ssh_session_struct::rekey_time, SAFE_FREE, session, SSH_COMP_C_S, SSH_COMP_S_C, SSH_CRYPT_C_S, SSH_CRYPT_S_C, ssh_get_local_username, SSH_HOSTKEYS, SSH_INVALID_SOCKET, ssh_keep_fips_algos, ssh_keep_known_algos, SSH_KEX, ssh_list_prepend, SSH_MAC_C_S, SSH_MAC_S_C, SSH_OPT_FLAG_GSSAPI_AUTH, SSH_OPT_FLAG_KBDINT_AUTH, SSH_OPT_FLAG_PASSWORD_AUTH, SSH_OPT_FLAG_PUBKEY_AUTH, SSH_OPTIONS_ADD_IDENTITY, SSH_OPTIONS_BINDADDR, SSH_OPTIONS_CIPHERS_C_S, SSH_OPTIONS_CIPHERS_S_C, SSH_OPTIONS_COMPRESSION, SSH_OPTIONS_COMPRESSION_C_S, SSH_OPTIONS_COMPRESSION_LEVEL, SSH_OPTIONS_COMPRESSION_S_C, SSH_OPTIONS_FD, SSH_OPTIONS_GLOBAL_KNOWNHOSTS, SSH_OPTIONS_GSSAPI_AUTH, SSH_OPTIONS_GSSAPI_CLIENT_IDENTITY, SSH_OPTIONS_GSSAPI_DELEGATE_CREDENTIALS, SSH_OPTIONS_GSSAPI_SERVER_IDENTITY, SSH_OPTIONS_HMAC_C_S, SSH_OPTIONS_HMAC_S_C, SSH_OPTIONS_HOST, SSH_OPTIONS_HOSTKEYS, SSH_OPTIONS_IDENTITY, SSH_OPTIONS_KBDINT_AUTH, SSH_OPTIONS_KEY_EXCHANGE, SSH_OPTIONS_KNOWNHOSTS, SSH_OPTIONS_LOG_VERBOSITY, SSH_OPTIONS_LOG_VERBOSITY_STR, SSH_OPTIONS_NODELAY, SSH_OPTIONS_PASSWORD_AUTH, SSH_OPTIONS_PORT, SSH_OPTIONS_PORT_STR, SSH_OPTIONS_PROCESS_CONFIG, SSH_OPTIONS_PROXYCOMMAND, SSH_OPTIONS_PUBKEY_AUTH, SSH_OPTIONS_PUBLICKEY_ACCEPTED_TYPES, SSH_OPTIONS_REKEY_DATA, SSH_OPTIONS_REKEY_TIME, ssh_options_set, ssh_options_set_algo, SSH_OPTIONS_SSH1, SSH_OPTIONS_SSH2, SSH_OPTIONS_SSH_DIR, SSH_OPTIONS_STRICTHOSTKEYCHECK, SSH_OPTIONS_TIMEOUT, SSH_OPTIONS_TIMEOUT_USEC, SSH_OPTIONS_USER, ssh_path_expand_tilde, SSH_REQUEST_DENIED, ssh_set_error, ssh_set_error_invalid, ssh_set_error_oom, ssh_set_log_level, ssh_session_struct::sshdir, ssh_session_struct::StrictHostKeyChecking, ssh_session_struct::timeout, ssh_session_struct::timeout_usec, ssh_session_struct::username.
Referenced by authenticate, client, connect_host, connect_ssh, LLVMFuzzerTestOneInput, main, pkd_exec_hello, session_setup, ssh::Session::setOption, setup, setup_config_files, ssh_client, ssh_config_parse_line, ssh_config_parse_proxy_jump, ssh_options_apply, ssh_options_getopt, ssh_options_parse_config, ssh_options_set, test_algorithm, torture_algorithms_zlib, torture_algorithms_zlib_openssh, torture_auth_agent, torture_auth_agent_cert, torture_auth_agent_cert_nonblocking, torture_auth_agent_nonblocking, torture_auth_autopubkey, torture_auth_autopubkey_nonblocking, torture_auth_cert, torture_auth_kbdint, torture_auth_kbdint_nonblocking, torture_auth_none, torture_auth_none_nonblocking, torture_auth_password, torture_auth_password_nonblocking, torture_auth_pubkey_types, torture_auth_pubkey_types_ecdsa, torture_auth_pubkey_types_ecdsa_nonblocking, torture_auth_pubkey_types_ed25519, torture_auth_pubkey_types_ed25519_nonblocking, torture_auth_pubkey_types_nonblocking, torture_client_config_suppress, torture_config_auth_methods, torture_config_match, torture_config_proxyjump, torture_config_rekey, torture_connect_double, torture_connect_nonblocking, torture_connect_socket, torture_hostkey_ed25519, torture_hostkey_rsa, torture_hostkey_rsa_sha256, torture_hostkey_rsa_sha512, torture_knownhosts_algorithms, torture_knownhosts_algorithms_global, torture_knownhosts_algorithms_negative, torture_knownhosts_algorithms_wanted, torture_knownhosts_conflict, torture_knownhosts_duplicate, torture_knownhosts_fail, torture_knownhosts_get_algorithms_names, torture_knownhosts_host_exists, torture_knownhosts_host_exists_global, torture_knownhosts_new_file, torture_knownhosts_no_hostkeychecking, torture_knownhosts_other, torture_knownhosts_other_auto, torture_knownhosts_port, torture_knownhosts_precheck, torture_knownhosts_standard_port, torture_knownhosts_unknown, torture_knownhosts_wildcard, torture_options_config_host, torture_options_config_match, torture_options_config_match_multi, torture_options_copy, torture_options_get_global_knownhosts, torture_options_get_host, torture_options_get_identity, torture_options_get_knownhosts, torture_options_get_port, torture_options_get_user, torture_options_proxycommand, torture_options_set_ciphers, torture_options_set_fd, torture_options_set_global_knownhosts, torture_options_set_host, torture_options_set_hostkey, torture_options_set_identity, torture_options_set_key_exchange, torture_options_set_knownhosts, torture_options_set_macs, torture_options_set_port, torture_options_set_proxycommand_notexist, torture_options_set_proxycommand_ssh, torture_options_set_proxycommand_ssh_stderr, torture_options_set_pubkey_accepted_types, torture_options_set_user, torture_packet, torture_pki_verify_mismatch, torture_rekey_default, torture_rekey_send, torture_rekey_time, torture_run_tests, torture_server_auth_kbdint, torture_server_auth_none, torture_server_auth_password, torture_server_auth_pubkey, torture_server_hostkey_mismatch, torture_server_unknown_global_request, torture_ssh_forward, torture_ssh_session, try_config_content.
LIBSSH_API int ssh_options_get(ssh_session session, enum ssh_options_e type, char **value)
This function can get ssh options, it does not support all options provided for ssh options set, but mostly those which a user-space program may care about having trusted the ssh driver to infer these values from underlaying configuration files. It operates only on those SSH_OPTIONS_* which return char*. If you wish to receive the port then please use ssh_options_get_port() which returns an unsigned int.
session An allocated SSH session structure. type The option type to get. This could be one of the following: SSH_OPTIONS_HOST: The hostname or ip address to connect to (const char *). SSH_OPTIONS_USER: The username for authentication (const char *). when not explicitly set this will be inferred from the ~/.ssh/config file. SSH_OPTIONS_IDENTITY: Get the first identity file name (const char *). By default identity, id_dsa and id_rsa are checked. SSH_OPTIONS_PROXYCOMMAND: Get the proxycommand necessary to log into the remote host. When not explicitly set, it will be read from the ~/.ssh/config file. SSH_OPTIONS_GLOBAL_KNOWNHOSTS: Get the path to the global known_hosts file being used. SSH_OPTIONS_KNOWNHOSTS: Get the path to the known_hosts file being used. value The value to get into. As a char**, space will be allocated by the function for the value, it is your responsibility to free the memory using ssh_string_free_char(). SSH_OK on success, SSH_ERROR on error.
References ssh_session_struct::global_knownhosts, ssh_session_struct::host, ssh_session_struct::identity, ssh_session_struct::knownhosts, ssh_session_struct::opts, ssh_session_struct::ProxyCommand, session, SSH_ERROR, ssh_iterator_value, ssh_list_get_iterator, SSH_OK, SSH_OPTIONS_GLOBAL_KNOWNHOSTS, SSH_OPTIONS_HOST, SSH_OPTIONS_IDENTITY, SSH_OPTIONS_KNOWNHOSTS, SSH_OPTIONS_PROXYCOMMAND, SSH_OPTIONS_USER, SSH_REQUEST_DENIED, ssh_set_error, ssh_set_error_invalid, ssh_set_error_oom, ssh_session_struct::username.
Referenced by torture_config_from_file, torture_config_glob, torture_options_get_global_knownhosts, torture_options_get_host, torture_options_get_identity, torture_options_get_knownhosts, torture_options_get_user.
LIBSSH_API int ssh_options_get_port(ssh_session session, unsigned int *port_target)
This function can get ssh the ssh port. It must only be used on a valid ssh session. This function is useful when the session options have been automatically inferred from the environment or configuration files and one.
session An allocated SSH session structure. port_target An unsigned integer into which the port will be set from the ssh session. 0 on success, < 0 on error.
References ssh_session_struct::opts, ssh_session_struct::port, session.
Referenced by torture_options_get_port.
LIBSSH_API int ssh_pcap_file_close(ssh_pcap_file pcap)
References pcap, SSH_ERROR.
LIBSSH_API void ssh_pcap_file_free(ssh_pcap_file pcap)
References pcap.
Referenced by cleanup_pcap, set_pcap, torture_teardown_socket_dir.
LIBSSH_API ssh_pcap_file ssh_pcap_file_new(void)
Referenced by main, set_pcap, torture_setup_socket_dir.
LIBSSH_API int ssh_pcap_file_open(ssh_pcap_file pcap, const char *filename)
References pcap, SSH_ERROR.
Referenced by main, set_pcap, torture_setup_socket_dir.
LIBSSH_API ssh_key ssh_key_new(void)
creates a new empty SSH key
an empty ssh_key handle, or NULL on error.
References ZERO_STRUCTP.
Referenced by pki_import_cert_buffer, pki_import_privkey_buffer, pki_import_pubkey_buffer, pki_key_dup, pki_private_key_from_base64, pki_uri_import, publickey_from_privatekey, publickey_to_string, ssh_pki_generate, ssh_userauth_agent_pubkey, ssh_userauth_pubkey.
LIBSSH_API void ssh_key_free(ssh_key key)
deallocate a SSH key
key ssh_key handle to free
References key, SAFE_FREE, ssh_key_clean.
Referenced by auth_keyfile, auth_publickey, crypto_free, pki_import_cert_buffer, pki_import_privkey_buffer, pki_import_pubkey_buffer, pki_key_dup, pki_openssh_import_privkey_blob, pki_private_key_from_base64, pki_uri_import, privatekey_from_file, publickey_from_file, publickey_from_privatekey, publickey_from_string, publickey_to_string, ssh_agent_state_free, ssh_bind_free, ssh_bind_import_keys, ssh_bind_listen, ssh_free, ssh_get_key_params, ssh_get_pubkey_hash, ssh_knownhosts_entry_free, ssh_message_free, ssh_pki_convert_key_to_privatekey, ssh_pki_convert_key_to_publickey, ssh_pki_generate, ssh_pki_openssh_import, ssh_userauth_agent, ssh_userauth_agent_pubkey, ssh_userauth_offer_pubkey, ssh_userauth_pubkey, ssh_userauth_publickey_auto, verify_knownhost.
LIBSSH_API enum ssh_keytypes_e ssh_key_type(const ssh_key key)
returns the type of a ssh key
key the ssh_key handle one of SSH_KEYTYPE_RSA, SSH_KEYTYPE_DSS, SSH_KEYTYPE_ECDSA_P256, SSH_KEYTYPE_ECDSA_P384, SSH_KEYTYPE_ECDSA_P521, SSH_KEYTYPE_ED25519, SSH_KEYTYPE_DSS_CERT01, SSH_KEYTYPE_RSA_CERT01, SSH_KEYTYPE_ECDSA_P256_CERT01, SSH_KEYTYPE_ECDSA_P384_CERT01, SSH_KEYTYPE_ECDSA_P521_CERT01, or SSH_KEYTYPE_ED25519_CERT01. SSH_KEYTYPE_UNKNOWN if the type is unknown
Referenced by pkd_auth_pubkey_cb, server_set_kex, ssh_bind_import_keys, ssh_is_server_known, thread_pki_rsa_import_cert_file, thread_pki_rsa_import_privkey_base64, torture_ecdsa_sign_verify_uri, torture_knownhosts_parse_line_default_ed25519, torture_knownhosts_parse_line_ecdsa, torture_knownhosts_parse_line_hashed_ed25519, torture_knownhosts_parse_line_pattern_ed25519, torture_knownhosts_parse_line_port_ed25519, torture_knownhosts_parse_line_port_wildcard, torture_knownhosts_parse_line_rsa, torture_knownhosts_parse_line_standard_port, torture_knownhosts_read_file, torture_pki_dsa_import_cert_file, torture_pki_ecdsa_import_cert_file, torture_pki_ed25519_generate_key, torture_pki_ed25519_import_cert_file, torture_pki_ed25519_import_export_privkey_base64, torture_pki_ed25519_import_privkey_base64, torture_pki_ed25519_import_privkey_base64_comment, torture_pki_ed25519_import_privkey_base64_whitespace, torture_pki_generate_key_ecdsa, torture_pki_keytype, torture_pki_rsa_import_cert_file, torture_pki_rsa_import_privkey_base64, torture_pki_rsa_import_privkey_base64_comment, torture_pki_rsa_import_privkey_base64_whitespace.
LIBSSH_API const char* ssh_key_type_to_char(enum ssh_keytypes_e type)
Convert a key type to a string.
type The type to convert. A string for the keytype or NULL if unknown.
Referenced by pkd_auth_pubkey_cb, pki_import_cert_buffer, pki_import_privkey_buffer, pki_import_pubkey_buffer, pki_private_key_from_base64, pki_uri_import, publickey_from_privatekey, server_set_kex, ssh_is_server_known, ssh_key_signature_to_char, ssh_known_hosts_parse_line, ssh_pki_generate, ssh_type_to_char, ssh_userauth_agent_pubkey, ssh_userauth_pubkey, torture_ecdsa_sign_verify_uri, torture_pki_ed25519_generate_key, torture_pki_generate_key_ecdsa, torture_pki_keytype.
LIBSSH_API enum ssh_keytypes_e ssh_key_type_from_name(const char *name)
Convert a ssh key name to a ssh key type.
name The name to convert. The enum ssh key type.
Referenced by pki_openssh_import_privkey_blob, setup_rsa_key, ssh_known_hosts_parse_line, ssh_pki_import_pubkey_blob, ssh_pki_import_pubkey_file, ssh_type_from_name, thread_pki_rsa_publickey_base64, torture_pki_dsa_publickey_base64, torture_pki_ecdsa_publickey_base64, torture_pki_ed25519_publickey_base64, torture_pki_keytype, torture_pki_rsa_publickey_base64.
LIBSSH_API int ssh_key_is_public(const ssh_key k)
Check if the key has/is a public key.
k The key to check. 1 if it is a public key, 0 if not.
References k, SSH_KEY_FLAG_PUBLIC.
Referenced by ssh_userauth_try_publickey, thread_pki_rsa_import_cert_file, thread_pki_rsa_import_privkey_base64, torture_pki_dsa_import_cert_file, torture_pki_ecdsa_import_cert_file, torture_pki_ecdsa_import_pubkey_uri, torture_pki_ed25519_import_cert_file, torture_pki_ed25519_import_privkey_base64, torture_pki_ed25519_import_privkey_base64_comment, torture_pki_ed25519_import_privkey_base64_whitespace, torture_pki_ed25519_pubkey_dup, torture_pki_rsa_import_cert_file, torture_pki_rsa_import_privkey_base64, torture_pki_rsa_import_privkey_base64_comment, torture_pki_rsa_import_privkey_base64_whitespace, torture_pki_rsa_import_pubkey_uri.
LIBSSH_API int ssh_key_is_private(const ssh_key k)
Check if the key is a private key.
k The key to check. 1 if it is a private key, 0 if not.
References k, SSH_KEY_FLAG_PRIVATE.
Referenced by pki_key_dup, pki_key_to_pkey, pki_sign_data, pki_verify_data_signature, ssh_key_cmp, ssh_pki_do_sign, ssh_pki_export_privkey_base64, ssh_pki_export_privkey_file, ssh_pki_export_privkey_to_pubkey, ssh_userauth_publickey, thread_pki_rsa_import_privkey_base64, thread_pki_rsa_import_privkey_base64_passphrase, thread_pki_rsa_publickey_from_privatekey, torture_pki_dsa_import_openssh_privkey_base64_passphrase, torture_pki_dsa_import_privkey_base64_passphrase, torture_pki_dsa_publickey_from_privatekey, torture_pki_ecdsa_import_privkey_base64, torture_pki_ecdsa_import_privkey_base64_comment, torture_pki_ecdsa_import_privkey_base64_whitespace, torture_pki_ed25519_import_export_privkey_base64, torture_pki_ed25519_import_privkey_base64, torture_pki_ed25519_import_privkey_base64_comment, torture_pki_ed25519_import_privkey_base64_passphrase, torture_pki_ed25519_import_privkey_base64_whitespace, torture_pki_ed25519_privkey_dup, torture_pki_ed25519_publickey_from_privatekey, torture_pki_rsa_import_openssh_privkey_base64_passphrase, torture_pki_rsa_import_privkey_base64, torture_pki_rsa_import_privkey_base64_comment, torture_pki_rsa_import_privkey_base64_passphrase, torture_pki_rsa_import_privkey_base64_whitespace, torture_pki_rsa_import_privkey_uri, torture_pki_rsa_publickey_from_privatekey, torture_pki_rsa_publickey_from_privatekey_uri.
LIBSSH_API int ssh_key_cmp(const ssh_key k1, const ssh_key k2, enum ssh_keycmp_e what)
Compare keys if they are equal.
k1 The first key to compare. k2 The second key to compare. what What part or type of the key do you want to compare. 0 if equal, 1 if not.
References pki_ed25519_key_cmp, pki_key_compare, ssh_key_struct::sk_application, SSH_KEY_CMP_PRIVATE, ssh_key_is_private, SSH_KEYTYPE_ED25519, SSH_KEYTYPE_SK_ECDSA, SSH_KEYTYPE_SK_ED25519, SSH_LOG, SSH_LOG_WARN, ssh_string_get_char, ssh_string_len, ssh_key_struct::type.
Referenced by auth_publickey, ssh_known_hosts_entries_compare, thread_pki_rsa_duplicate_key, torture_pki_dsa_duplicate_key, torture_pki_ecdsa_duplicate_key, torture_pki_ecdsa_duplicate_key_uri, torture_pki_ed25519_write_privkey, torture_pki_rsa_duplicate_key.
LIBSSH_API int ssh_pki_generate(enum ssh_keytypes_e type, int parameter, ssh_key *pkey)
Generates a keypair.
type Type of key to create parameter Parameter to the creation of key: rsa : length of the key in bits (e.g. 1024, 2048, 4096) dsa : length of the key in bits (e.g. 1024, 2048, 3072) pkey A pointer to store the allocated private key. You need to free the memory. SSH_OK on success, SSH_ERROR on error. Generating a key pair may take some time.
References error, key, pki_key_generate_dss, pki_key_generate_ecdsa, pki_key_generate_ed25519, pki_key_generate_rsa, rc, SSH_ERROR, SSH_KEY_FLAG_PRIVATE, SSH_KEY_FLAG_PUBLIC, ssh_key_free, ssh_key_new, ssh_key_type_to_char, SSH_KEYTYPE_DSS, SSH_KEYTYPE_DSS_CERT01, SSH_KEYTYPE_ECDSA, SSH_KEYTYPE_ECDSA_P256, SSH_KEYTYPE_ECDSA_P256_CERT01, SSH_KEYTYPE_ECDSA_P384, SSH_KEYTYPE_ECDSA_P384_CERT01, SSH_KEYTYPE_ECDSA_P521, SSH_KEYTYPE_ECDSA_P521_CERT01, SSH_KEYTYPE_ED25519, SSH_KEYTYPE_ED25519_CERT01, SSH_KEYTYPE_RSA, SSH_KEYTYPE_RSA1, SSH_KEYTYPE_RSA_CERT01, SSH_KEYTYPE_SK_ECDSA, SSH_KEYTYPE_SK_ECDSA_CERT01, SSH_KEYTYPE_SK_ED25519, SSH_KEYTYPE_SK_ED25519_CERT01, SSH_KEYTYPE_UNKNOWN, SSH_OK, ssh_pki_key_ecdsa_name.
Referenced by main, thread_pki_rsa_generate_key, torture_pki_dsa_generate_key, torture_pki_ed25519_generate_key, torture_pki_fail_sign_with_incompatible_hash, torture_pki_generate_key_ecdsa, torture_pki_rsa_generate_key, torture_pki_sign_data_dsa, torture_pki_sign_data_ecdsa, torture_pki_sign_data_rsa, torture_pki_verify_mismatch.
LIBSSH_API int ssh_pki_import_privkey_base64(const char *b64_key, const char *passphrase, ssh_auth_callback auth_fn, void *auth_data, ssh_key *pkey)
import a base64 formated key from a memory c-string
b64_key The c-string holding the base64 encoded key passphrase The passphrase to decrypt the key, or NULL auth_fn An auth function you may want to use or NULL. auth_data Private data passed to the auth function. pkey A pointer where the allocated key can be stored. You need to free the memory. SSH_ERROR in case of error, SSH_OK otherwise. ssh_key_free()
References key, OPENSSH_HEADER_BEGIN, pki_private_key_from_base64, SSH_ERROR, SSH_LOG, SSH_LOG_INFO, SSH_OK, ssh_pki_openssh_privkey_import.
Referenced by ssh_pki_import_privkey_file, thread_pki_rsa_copy_cert_to_privkey, thread_pki_rsa_import_privkey_base64, thread_pki_rsa_import_privkey_base64_NULL_key, thread_pki_rsa_import_privkey_base64_NULL_str, thread_pki_rsa_import_privkey_base64_passphrase, thread_pki_rsa_publickey_from_privatekey, torture_pki_dsa_import_openssh_privkey_base64_passphrase, torture_pki_dsa_import_privkey_base64, torture_pki_dsa_import_privkey_base64_comment, torture_pki_dsa_import_privkey_base64_passphrase, torture_pki_dsa_import_privkey_base64_whitespace, torture_pki_dsa_publickey_from_privatekey, torture_pki_ecdsa_import_privkey_base64, torture_pki_ecdsa_import_privkey_base64_comment, torture_pki_ecdsa_import_privkey_base64_whitespace, torture_pki_ecdsa_publickey_from_privatekey, torture_pki_ed25519_import_export_privkey_base64, torture_pki_ed25519_import_privkey_base64, torture_pki_ed25519_import_privkey_base64_comment, torture_pki_ed25519_import_privkey_base64_passphrase, torture_pki_ed25519_import_privkey_base64_whitespace, torture_pki_ed25519_privkey_dup, torture_pki_ed25519_publickey_from_privatekey, torture_pki_ed25519_sign, torture_pki_ed25519_sign_openssh_privkey_passphrase, torture_pki_rsa_copy_cert_to_privkey, torture_pki_rsa_import_openssh_privkey_base64_passphrase, torture_pki_rsa_import_privkey_base64, torture_pki_rsa_import_privkey_base64_comment, torture_pki_rsa_import_privkey_base64_NULL_key, torture_pki_rsa_import_privkey_base64_NULL_str, torture_pki_rsa_import_privkey_base64_passphrase, torture_pki_rsa_import_privkey_base64_whitespace, torture_pki_rsa_publickey_from_privatekey.
LIBSSH_API int ssh_pki_export_privkey_base64(const ssh_key privkey, const char *passphrase, ssh_auth_callback auth_fn, void *auth_data, char **b64_key)
Convert a private key to a pem base64 encoded key, or OpenSSH format for keytype ssh-ed25519.
privkey The private key to export. passphrase The passphrase to use to encrypt the key with or NULL. An empty string means no passphrase. auth_fn An auth function you may want to use or NULL. auth_data Private data passed to the auth function. b64_key A pointer to store the allocated base64 encoded key. You need to free the buffer. SSH_OK on success, SSH_ERROR on error.
References pki_private_key_to_pem, privkey, SSH_ERROR, ssh_key_is_private, SSH_KEYTYPE_ED25519, SSH_OK, ssh_pki_openssh_privkey_export, ssh_string_data, SSH_STRING_FREE, ssh_string_len, strndup.
Referenced by torture_pki_ed25519_import_export_privkey_base64.
LIBSSH_API int ssh_pki_import_privkey_file(const char *filename, const char *passphrase, ssh_auth_callback auth_fn, void *auth_data, ssh_key *pkey)
Import a key from a file.
filename The filename of the the private key. passphrase The passphrase to decrypt the private key. Set to NULL if none is needed or it is unknown. auth_fn An auth function you may want to use or NULL. auth_data Private data passed to the auth function. pkey A pointer to store the allocated ssh_key. You need to free the key. SSH_OK on success, SSH_EOF if the file doesn't exist or permission denied, SSH_ERROR otherwise. ssh_key_free()
References MAX_PRIVKEY_SIZE, pki_uri_import, rc, SAFE_FREE, SSH_EOF, SSH_ERROR, SSH_KEY_PRIVATE, SSH_LOG, SSH_LOG_WARN, ssh_pki_import_privkey_base64, ssh_pki_is_uri.
Referenced by auth_keyfile, privatekey_from_file, ssh_bind_import_keys, ssh_userauth_publickey_auto, thread_pki_rsa_duplicate_key, torture_auth_cert, torture_auth_pubkey_types_ed25519, torture_auth_pubkey_types_ed25519_nonblocking, torture_ecdsa_sign_verify_uri, torture_pki_dsa_cert_verify, torture_pki_dsa_duplicate_key, torture_pki_dsa_generate_pubkey_from_privkey, torture_pki_ecdsa_cert_verify, torture_pki_ecdsa_duplicate_key, torture_pki_ecdsa_duplicate_key_uri, torture_pki_ecdsa_duplicate_then_demote, torture_pki_ecdsa_duplicate_then_demote_uri, torture_pki_ecdsa_generate_pubkey_from_privkey, torture_pki_ecdsa_import_pubkey_uri_invalid_configurations, torture_pki_ecdsa_name, torture_pki_ecdsa_publickey_from_privatekey_uri, torture_pki_ed25519_cert_verify, torture_pki_ed25519_generate_pubkey_from_privkey, torture_pki_ed25519_write_privkey, torture_pki_rsa_duplicate_key, torture_pki_rsa_generate_pubkey_from_privkey, torture_pki_rsa_import_privkey_uri, torture_pki_rsa_publickey_from_privatekey_uri, torture_pki_rsa_sha2, torture_pki_rsa_uri_invalid_configurations, torture_pki_sign_verify_uri.
LIBSSH_API int ssh_pki_export_privkey_file(const ssh_key privkey, const char *passphrase, ssh_auth_callback auth_fn, void *auth_data, const char *filename)
Export a private key to a pem file on disk, or OpenSSH format for keytype ssh-ed25519.
privkey The private key to export. passphrase The passphrase to use to encrypt the key with or NULL. An empty string means no passphrase. auth_fn An auth function you may want to use or NULL. auth_data Private data passed to the auth function. filename The path where to store the pem file. SSH_OK on success, SSH_ERROR on error.
References pki_private_key_to_pem, privkey, rc, SSH_EOF, SSH_ERROR, ssh_key_is_private, SSH_KEYTYPE_ED25519, SSH_LOG, SSH_LOG_FUNCTIONS, SSH_OK, ssh_pki_openssh_privkey_export, ssh_string_data, SSH_STRING_FREE, ssh_string_len.
Referenced by main, torture_pki_ed25519_write_privkey.
LIBSSH_API int ssh_pki_copy_cert_to_privkey(const ssh_key cert_key, ssh_key privkey)
Copy the certificate part of a public key into a private key.
certkey The certificate key. privkey The target private key to copy the certificate to. SSH_OK on success, SSH_ERROR otherwise.
References ssh_key_struct::cert, privkey, rc, ssh_buffer_add_buffer, SSH_BUFFER_FREE, ssh_buffer_new, SSH_ERROR, SSH_OK, ssh_key_struct::type.
Referenced by thread_pki_rsa_copy_cert_to_privkey, torture_auth_cert, torture_pki_rsa_copy_cert_to_privkey.
LIBSSH_API int ssh_pki_import_pubkey_base64(const char *b64_key, enum ssh_keytypes_e type, ssh_key *pkey)
Import a base64 formated public key from a memory c-string.
b64_key The base64 key to format. type The type of the key to format. pkey A pointer where the allocated key can be stored. You need to free the memory. SSH_OK on success, SSH_ERROR on error. ssh_key_free()
References base64_to_bin, buffer, is_cert_type, pki_import_cert_buffer, pki_import_pubkey_buffer, rc, SSH_BUFFER_FREE, ssh_buffer_get_ssh_string, SSH_ERROR, SSH_STRING_FREE.
Referenced by setup_rsa_key, ssh_known_hosts_parse_line, ssh_pki_import_cert_base64, ssh_pki_import_pubkey_file, thread_pki_rsa_publickey_base64, torture_pki_dsa_publickey_base64, torture_pki_ecdsa_publickey_base64, torture_pki_ed25519_pubkey_dup, torture_pki_ed25519_publickey_base64, torture_pki_ed25519_verify, torture_pki_ed25519_verify_bad, torture_pki_rsa_publickey_base64.
LIBSSH_API int ssh_pki_import_pubkey_file(const char *filename, ssh_key *pkey)
Import a public key from the given filename.
filename The path to the public key. pkey A pointer to store the allocated public key. You need to free the memory. SSH_OK on success, SSH_EOF if the file doesn't exist or permission denied, SSH_ERROR otherwise. ssh_key_free()
References MAX_PUBKEY_SIZE, OPENSSH_HEADER_BEGIN, pki_uri_import, rc, SAFE_FREE, SSH_EOF, SSH_ERROR, SSH_KEY_PUBLIC, ssh_key_type_from_name, SSH_KEYTYPE_UNKNOWN, SSH_LOG, SSH_LOG_WARN, SSH_OK, ssh_pki_import_pubkey_base64, ssh_pki_is_uri, ssh_pki_openssh_pubkey_import.
Referenced by auth_keyfile, auth_publickey, publickey_from_file, ssh_pki_import_cert_file, ssh_userauth_publickey_auto, thread_pki_rsa_copy_cert_to_privkey, thread_pki_rsa_duplicate_key, thread_pki_rsa_import_pubkey_file, torture_pki_dsa_duplicate_key, torture_pki_dsa_import_pubkey_file, torture_pki_dsa_import_pubkey_from_openssh_privkey, torture_pki_ecdsa_duplicate_key, torture_pki_ecdsa_duplicate_key_uri, torture_pki_ecdsa_import_pubkey_file, torture_pki_ecdsa_import_pubkey_from_openssh_privkey, torture_pki_ecdsa_import_pubkey_uri, torture_pki_ecdsa_import_pubkey_uri_invalid_configurations, torture_pki_ed25519_import_pubkey_file, torture_pki_ed25519_import_pubkey_from_openssh_privkey, torture_pki_rsa_copy_cert_to_privkey, torture_pki_rsa_duplicate_key, torture_pki_rsa_import_pubkey_file, torture_pki_rsa_import_pubkey_from_openssh_privkey, torture_pki_rsa_import_pubkey_uri, torture_pki_rsa_uri_invalid_configurations, torture_pki_sign_verify_uri.
LIBSSH_API int ssh_pki_import_cert_base64(const char *b64_cert, enum ssh_keytypes_e type, ssh_key *pkey)
Import a base64 formated certificate from a memory c-string.
b64_cert The base64 cert to format. type The type of the cert to format. pkey A pointer where the allocated key can be stored. You need to free the memory. SSH_OK on success, SSH_ERROR on error. ssh_key_free()
References ssh_pki_import_pubkey_base64.
LIBSSH_API int ssh_pki_import_cert_file(const char *filename, ssh_key *pkey)
Import a certificate from the given filename.
filename The path to the certificate. pkey A pointer to store the allocated certificate. You need to free the memory. SSH_OK on success, SSH_EOF if the file doesn't exist or permission denied, SSH_ERROR otherwise. ssh_key_free()
References ssh_pki_import_pubkey_file.
Referenced by thread_pki_rsa_copy_cert_to_privkey, thread_pki_rsa_import_cert_file, torture_auth_cert, torture_pki_dsa_cert_verify, torture_pki_dsa_import_cert_file, torture_pki_ecdsa_cert_verify, torture_pki_ecdsa_import_cert_file, torture_pki_ed25519_cert_verify, torture_pki_ed25519_import_cert_file, torture_pki_rsa_copy_cert_to_privkey, torture_pki_rsa_import_cert_file, torture_pki_rsa_sha2, torture_pki_verify_mismatch.
LIBSSH_API int ssh_pki_export_privkey_to_pubkey(const ssh_key privkey, ssh_key *pkey)
Create a public key from a private key.
privkey The private key to get the public key from. pkey A pointer to store the newly allocated public key. You NEED to free the key. SSH_OK on success, SSH_ERROR on error. ssh_key_free()
References pki_key_dup, privkey, pubkey, SSH_ERROR, ssh_key_is_private, SSH_OK.
Referenced by publickey_from_privatekey, ssh_get_key_params, ssh_userauth_publickey_auto, test_sign_verify_data, thread_pki_rsa_duplicate_key, thread_pki_rsa_generate_key, thread_pki_rsa_publickey_from_privatekey, torture_ecdsa_sign_verify_uri, torture_pki_dsa_duplicate_key, torture_pki_dsa_generate_key, torture_pki_dsa_generate_pubkey_from_privkey, torture_pki_dsa_publickey_from_privatekey, torture_pki_ecdsa_duplicate_key, torture_pki_ecdsa_duplicate_key_uri, torture_pki_ecdsa_duplicate_then_demote, torture_pki_ecdsa_duplicate_then_demote_uri, torture_pki_ecdsa_generate_pubkey_from_privkey, torture_pki_ecdsa_publickey_from_privatekey, torture_pki_ecdsa_publickey_from_privatekey_uri, torture_pki_ed25519_generate_key, torture_pki_ed25519_generate_pubkey_from_privkey, torture_pki_ed25519_publickey_from_privatekey, torture_pki_fail_sign_with_incompatible_hash, torture_pki_generate_key_ecdsa, torture_pki_rsa_duplicate_key, torture_pki_rsa_generate_key, torture_pki_rsa_generate_pubkey_from_privkey, torture_pki_rsa_publickey_from_privatekey, torture_pki_rsa_publickey_from_privatekey_uri, torture_pki_rsa_sha2, torture_pki_verify_mismatch.
LIBSSH_API int ssh_pki_export_pubkey_base64(const ssh_key key, char **b64_key)
Convert a public key to a base64 encoded key.
key The key to hash b64_key A pointer to store the allocated base64 encoded key. You need to free the buffer. SSH_OK on success, SSH_ERROR on error. SSH_STRING_FREE_CHAR()
References bin_to_base64, key, pki_publickey_to_blob, SSH_ERROR, SSH_OK, ssh_string_data, SSH_STRING_FREE, ssh_string_len.
Referenced by ssh_dump_knownhost, ssh_pki_export_pubkey_file, ssh_session_export_known_hosts_entry, thread_pki_rsa_duplicate_key, thread_pki_rsa_publickey_base64, torture_pki_dsa_duplicate_key, torture_pki_dsa_publickey_base64, torture_pki_ecdsa_duplicate_key, torture_pki_ecdsa_duplicate_key_uri, torture_pki_ecdsa_publickey_base64, torture_pki_ed25519_publickey_base64, torture_pki_rsa_duplicate_key, torture_pki_rsa_publickey_base64.
LIBSSH_API int ssh_pki_export_pubkey_file(const ssh_key key, const char *filename)
References host, key, rc, SSH_ERROR, ssh_get_local_username, SSH_OK, ssh_pki_export_pubkey_base64, user.
Referenced by ssh_userauth_publickey_auto, torture_pki_dsa_generate_pubkey_from_privkey, torture_pki_ecdsa_generate_pubkey_from_privkey, torture_pki_ecdsa_publickey_from_privatekey_uri, torture_pki_ed25519_generate_pubkey_from_privkey, torture_pki_rsa_generate_pubkey_from_privkey.
LIBSSH_API const char* ssh_pki_key_ecdsa_name(const ssh_key key)
returns the ECDSA key name ("ecdsa-sha2-nistp256" for example)
key the ssh_key whose ECDSA name to get the ECDSA key name ("ecdsa-sha2-nistp256" for example) "unknown" if the ECDSA key name is not known
References key, pki_key_ecdsa_nid_to_name.
Referenced by pki_import_pubkey_buffer, ssh_pki_generate, torture_ecdsa_sign_verify_uri, torture_pki_ecdsa_name, torture_pki_generate_key_ecdsa.
LIBSSH_API char* ssh_get_fingerprint_hash(enum ssh_publickey_hash_type type, unsigned char *hash, size_t len)
Get a hash as a human-readable hex- or base64-string.
This gets an allocated fingerprint hash. If it is a SHA sum, it will return an unpadded base64 strings. If it is a MD5 sum, it will return hex string. Either way, the output is prepended by the hash-type. Do NOT use MD5 or SHA1! Those hash functions are being deprecated. type Which sort of hash is given, use SSH_PUBLICKEY_HASH_SHA256 or better. hash The hash to be converted to fingerprint. len Length of the buffer to convert. Returns the allocated fingerprint hash or NULL on error. ssh_string_free_char()
References rc, SAFE_FREE, ssh_get_b64_unpadded, ssh_get_hexa, SSH_PUBLICKEY_HASH_MD5, SSH_PUBLICKEY_HASH_SHA1, SSH_PUBLICKEY_HASH_SHA256.
Referenced by ssh_print_hash, torture_sha256_fingerprint.
LIBSSH_API void ssh_print_hash(enum ssh_publickey_hash_type type, unsigned char *hash, size_t len)
Print a hash as a human-readable hex- or base64-string.
This prints an unpadded base64 strings for SHA sums and hex strings for MD5 sum. Either way, the output is prepended by the hash-type. type Which sort of hash is given. Use SSH_PUBLICKEY_HASH_SHA256 or better. hash The hash to be converted to fingerprint. len Length of the buffer to convert. ssh_get_publickey_hash() ssh_get_fingerprint_hash()
References SAFE_FREE, ssh_get_fingerprint_hash.
Referenced by verify_knownhost.
LIBSSH_API int ssh_send_ignore(ssh_session session, const char *data)
Send a message that should be ignored.
session The SSH session data Data to be sent SSH_OK on success, SSH_ERROR otherwise.
References error, ssh_session_struct::out_buffer, rc, session, ssh_session_struct::socket, SSH2_MSG_IGNORE, ssh_buffer_pack, ssh_buffer_reinit, SSH_ERROR, ssh_handle_packets, SSH_OK, ssh_packet_send, ssh_set_error_oom, ssh_socket_is_open.
Referenced by test_algorithm, torture_rekey_send, torture_rekey_server_send, torture_rekey_time.
LIBSSH_API int ssh_send_debug(ssh_session session, const char *message, int always_display)
Send a debug message.
session The SSH session message Data to be sent always_display Message SHOULD be displayed by the server. It SHOULD NOT be displayed unless debugging information has been explicitly requested. SSH_OK on success, SSH_ERROR otherwise.
References error, ssh_session_struct::out_buffer, rc, session, ssh_session_struct::socket, SSH2_MSG_DEBUG, ssh_buffer_pack, ssh_buffer_reinit, SSH_ERROR, ssh_handle_packets, SSH_OK, ssh_packet_send, ssh_set_error_oom, ssh_socket_is_open.
LIBSSH_API void ssh_gssapi_set_creds(ssh_session session, const ssh_gssapi_creds creds)
Set the forwadable ticket to be given to the server for authentication. Unlike ssh_gssapi_get_creds() this is called on the client side of an ssh connection.
creds gssapi credentials handle.
References ssh_gssapi_struct::client, ssh_gssapi_struct::client_deleg_creds, ssh_session_struct::gssapi, session, ssh_gssapi_init.
Referenced by main.
LIBSSH_API int ssh_scp_accept_request(ssh_scp scp)
Accepts transfer of a file or creation of a directory coming from the remote party.
scp The scp handle. SSH_OK if the message was sent, SSH_ERROR if sending the message failed, or sending it in a bad state.
References buffer, ssh_scp_struct::channel, rc, ssh_scp_struct::request_type, ssh_scp_struct::session, ssh_channel_write, SSH_ERROR, SSH_FATAL, SSH_OK, SSH_SCP_READ_INITED, SSH_SCP_READ_READING, SSH_SCP_READ_REQUESTED, SSH_SCP_REQUEST_NEWFILE, ssh_set_error, ssh_scp_struct::state.
Referenced by benchmarks_scp_down, fetch_files, ssh_scp_read, torture_scp_download, torture_scp_download_recursive.
LIBSSH_API int ssh_scp_close(ssh_scp scp)
Close the scp channel.
scp The scp context to close. SSH_OK on success or an SSH error code. ssh_scp_init()
References buffer, ssh_scp_struct::channel, rc, ssh_channel_close, ssh_channel_free, ssh_channel_is_eof, ssh_channel_read, ssh_channel_send_eof, SSH_ERROR, SSH_OK, SSH_SCP_ERROR, SSH_SCP_NEW, ssh_scp_struct::state.
Referenced by benchmarks_scp_down, benchmarks_scp_up, fetch_files, ssh_scp_free, torture_scp_download, torture_scp_download_recursive, torture_scp_upload, torture_scp_upload_newline, torture_scp_upload_recursive.
LIBSSH_API int ssh_scp_deny_request(ssh_scp scp, const char *reason)
Deny the transfer of a file or creation of a directory coming from the remote party.
scp The scp handle. reason A nul-terminated string with a human-readable explanation of the deny. SSH_OK if the message was sent, SSH_ERROR if the sending the message failed, or sending it in a bad state.
References buffer, ssh_scp_struct::channel, MAX_BUF_SIZE, rc, ssh_scp_struct::session, ssh_channel_write, SSH_ERROR, SSH_FATAL, SSH_OK, SSH_SCP_READ_INITED, SSH_SCP_READ_REQUESTED, ssh_set_error, ssh_scp_struct::state.
LIBSSH_API void ssh_scp_free(ssh_scp scp)
Free a scp context.
scp The context to free. ssh_scp_new()
References ssh_scp_struct::channel, ssh_scp_struct::location, ssh_scp_struct::request_name, SAFE_FREE, ssh_channel_free, ssh_scp_close, SSH_SCP_NEW, ssh_scp_struct::state, ssh_scp_struct::warning.
Referenced by benchmarks_scp_down, benchmarks_scp_up, fetch_files, ssh_scp_new, torture_scp_download, torture_scp_download_recursive, torture_scp_upload, torture_scp_upload_newline, torture_scp_upload_recursive.
LIBSSH_API int ssh_scp_init(ssh_scp scp)
Initialize the scp channel.
scp The scp context to initialize. SSH_OK on success or an SSH error code. ssh_scp_new()
References ssh_scp_struct::channel, ssh_scp_struct::location, ssh_scp_struct::mode, rc, ssh_scp_struct::recursive, SAFE_FREE, ssh_scp_struct::session, ssh_channel_new, ssh_channel_open_session, ssh_channel_request_exec, ssh_channel_write, SSH_ERROR, SSH_FATAL, SSH_LOG, SSH_LOG_DEBUG, SSH_LOG_PROTOCOL, SSH_OK, ssh_quote_file_name, SSH_SCP_ERROR, SSH_SCP_NEW, SSH_SCP_READ_INITED, ssh_scp_response, SSH_SCP_WRITE, SSH_SCP_WRITE_INITED, ssh_set_error, ssh_scp_struct::state.
Referenced by benchmarks_scp_down, benchmarks_scp_up, fetch_files, torture_scp_download, torture_scp_download_recursive, torture_scp_upload, torture_scp_upload_newline, torture_scp_upload_recursive.
LIBSSH_API int ssh_scp_leave_directory(ssh_scp scp)
Leave a directory.
SSH_OK if the directory has been left, SSH_ERROR if an error occured. ssh_scp_push_directory()
References buffer, ssh_scp_struct::channel, rc, ssh_scp_struct::session, ssh_channel_write, SSH_ERROR, SSH_FATAL, SSH_OK, SSH_SCP_ERROR, ssh_scp_response, SSH_SCP_WRITE_INITED, ssh_set_error, ssh_scp_struct::state.
Referenced by torture_scp_upload_newline, torture_scp_upload_recursive.
LIBSSH_API ssh_scp ssh_scp_new(ssh_session session, int mode, const char *location)
Create a new scp session.
session The SSH session to use. mode One of SSH_SCP_WRITE or SSH_SCP_READ, depending if you need to drop files remotely or read them. It is not possible to combine read and write. SSH_SCP_RECURSIVE Flag can be or'ed to this to indicate that you're going to use recursion. Browsing through directories is not possible without this. location The directory in which write or read will be done. Any push or pull will be relative to this place. This can also be a pattern of files to download (read). A ssh_scp handle, NULL if the creation was impossible.
References ssh_scp_struct::channel, error, ssh_scp_struct::location, ssh_scp_struct::mode, ssh_scp_struct::recursive, ssh_scp_struct::session, session, SSH_FATAL, ssh_scp_free, SSH_SCP_NEW, SSH_SCP_READ, SSH_SCP_RECURSIVE, SSH_SCP_WRITE, ssh_set_error, ssh_scp_struct::state.
Referenced by benchmarks_scp_down, benchmarks_scp_up, fetch_files, torture_scp_download, torture_scp_download_recursive, torture_scp_upload, torture_scp_upload_newline, torture_scp_upload_recursive.
LIBSSH_API int ssh_scp_pull_request(ssh_scp scp)
Wait for a scp request (file, directory).
SSH_SCP_REQUEST_NEWFILE: The other side is sending a file SSH_SCP_REQUEST_NEWDIR: The other side is sending a directory SSH_SCP_REQUEST_ENDDIR: The other side has finished with the current directory SSH_SCP_REQUEST_WARNING: The other side sent us a warning SSH_SCP_REQUEST_EOF: The other side finished sending us files and data. SSH_ERROR: Some error happened ssh_scp_read() ssh_scp_deny_request() ssh_scp_accept_request() ssh_scp_request_get_warning()
References buffer, ssh_scp_struct::channel, error, ssh_scp_struct::filelen, MAX_BUF_SIZE, name, ssh_scp_struct::processed, rc, ssh_scp_struct::request_mode, ssh_scp_struct::request_name, ssh_scp_struct::request_type, SAFE_FREE, ssh_scp_struct::session, ssh_channel_is_eof, ssh_channel_write, SSH_ERROR, SSH_FATAL, SSH_LOG, SSH_LOG_PROTOCOL, SSH_REQUEST_DENIED, ssh_scp_integer_mode, SSH_SCP_READ_INITED, SSH_SCP_READ_REQUESTED, ssh_scp_read_string, SSH_SCP_REQUEST_ENDDIR, SSH_SCP_REQUEST_EOF, SSH_SCP_REQUEST_NEWDIR, SSH_SCP_REQUEST_NEWFILE, SSH_SCP_REQUEST_WARNING, SSH_SCP_TERMINATED, ssh_set_error, ssh_scp_struct::state, ssh_scp_struct::warning.
Referenced by benchmarks_scp_down, fetch_files, torture_scp_download, torture_scp_download_recursive.
LIBSSH_API int ssh_scp_push_directory(ssh_scp scp, const char *dirname, int mode)
Create a directory in a scp in sink mode.
scp The scp handle. dirname The name of the directory being created. mode The UNIX permissions for the new directory, e.g. 0755. SSH_OK if the directory has been created, SSH_ERROR if an error occured. ssh_scp_leave_directory()
References buffer, ssh_scp_struct::channel, error, rc, SAFE_FREE, ssh_scp_struct::session, ssh_basename, ssh_channel_write, SSH_ERROR, SSH_FATAL, SSH_LOG, SSH_LOG_PROTOCOL, ssh_newline_vis, SSH_OK, SSH_SCP_ERROR, ssh_scp_response, ssh_scp_string_mode, SSH_SCP_WRITE_INITED, ssh_set_error, ssh_set_error_oom, ssh_scp_struct::state.
Referenced by torture_scp_upload_newline, torture_scp_upload_recursive.
LIBSSH_API int ssh_scp_push_file(ssh_scp scp, const char *filename, size_t size, int perms)
Initialize the sending of a file to a scp in sink mode.
scp The scp handle. filename The name of the file being sent. It should not contain any path indicator size Exact size in bytes of the file being sent. mode The UNIX permissions for the new file, e.g. 0644. SSH_OK if the file is ready to be sent, SSH_ERROR if an error occured.
References ssh_scp_push_file64.
Referenced by benchmarks_scp_up, torture_scp_upload, torture_scp_upload_newline, torture_scp_upload_recursive.
LIBSSH_API int ssh_scp_push_file64(ssh_scp scp, const char *filename, uint64_t size, int perms)
Initialize the sending of a file to a scp in sink mode, using a 64-bit size.
scp The scp handle. filename The name of the file being sent. It should not contain any path indicator size Exact size in bytes of the file being sent. mode The UNIX permissions for the new file, e.g. 0644. SSH_OK if the file is ready to be sent, SSH_ERROR if an error occured. ssh_scp_push_file()
References buffer, ssh_scp_struct::channel, error, ssh_scp_struct::filelen, ssh_scp_struct::processed, rc, SAFE_FREE, ssh_scp_struct::session, ssh_basename, ssh_channel_write, SSH_ERROR, SSH_FATAL, SSH_LOG, SSH_LOG_PROTOCOL, ssh_newline_vis, SSH_OK, SSH_SCP_ERROR, ssh_scp_response, ssh_scp_string_mode, SSH_SCP_WRITE_INITED, SSH_SCP_WRITE_WRITING, ssh_set_error, ssh_set_error_oom, ssh_scp_struct::state.
Referenced by ssh_scp_push_file.
LIBSSH_API int ssh_scp_read(ssh_scp scp, void *buffer, size_t size)
Read from a remote scp file.
scp The scp handle. buffer The destination buffer. size The size of the buffer. The nNumber of bytes read, SSH_ERROR if an error occured while reading.
References buffer, ssh_scp_struct::channel, ssh_scp_struct::filelen, ssh_scp_struct::processed, rc, ssh_scp_struct::request_type, ssh_scp_struct::session, ssh_channel_read, ssh_channel_write, SSH_ERROR, SSH_FATAL, ssh_scp_accept_request, SSH_SCP_ERROR, SSH_SCP_READ_INITED, SSH_SCP_READ_READING, SSH_SCP_READ_REQUESTED, SSH_SCP_REQUEST_NEWFILE, ssh_scp_response, ssh_set_error, ssh_scp_struct::state.
Referenced by benchmarks_scp_down, fetch_files, torture_scp_download, torture_scp_download_recursive.
LIBSSH_API const char* ssh_scp_request_get_filename(ssh_scp scp)
Get the name of the directory or file being pushed from the other party.
The file name, NULL on error. The string should not be freed.
References ssh_scp_struct::request_name.
Referenced by fetch_files, torture_scp_download, torture_scp_download_recursive.
LIBSSH_API int ssh_scp_request_get_permissions(ssh_scp scp)
Get the permissions of the directory or file being pushed from the other party.
The UNIX permission, e.g 0644, -1 on error.
References ssh_scp_struct::request_mode.
Referenced by fetch_files, torture_scp_download, torture_scp_download_recursive.
LIBSSH_API size_t ssh_scp_request_get_size(ssh_scp scp)
Get the size of the file being pushed from the other party.
The numeric size of the file being read. The real size may not fit in a 32 bits field and may be truncated. ssh_scp_request_get_size64()
References ssh_scp_struct::filelen.
Referenced by benchmarks_scp_down, fetch_files, torture_scp_download, torture_scp_download_recursive.
LIBSSH_API uint64_t ssh_scp_request_get_size64(ssh_scp scp)
Get the size of the file being pushed from the other party.
The numeric size of the file being read.
References ssh_scp_struct::filelen.
LIBSSH_API const char* ssh_scp_request_get_warning(ssh_scp scp)
Get the warning string from a scp handle.
scp The scp handle. A warning string, or NULL on error. The string should not be freed.
References ssh_scp_struct::warning.
Referenced by fetch_files.
LIBSSH_API int ssh_scp_write(ssh_scp scp, const void *buffer, size_t len)
Write into a remote scp file.
scp The scp handle. buffer The buffer to write. len The number of bytes to write. SSH_OK if the write was successful, SSH_ERROR an error occured while writing.
References buffer, ssh_scp_struct::channel, ssh_scp_struct::filelen, ssh_scp_struct::processed, rc, ssh_scp_struct::session, ssh_channel_poll, ssh_channel_write, SSH_ERROR, SSH_FATAL, SSH_OK, SSH_SCP_ERROR, ssh_scp_response, SSH_SCP_WRITE_INITED, SSH_SCP_WRITE_WRITING, ssh_set_error, ssh_scp_struct::state.
Referenced by benchmarks_scp_up, torture_scp_upload, torture_scp_upload_newline, torture_scp_upload_recursive.
LIBSSH_API int ssh_select(ssh_channel *channels, ssh_channel *outchannels, socket_t maxfd, fd_set *readfds, struct timeval *timeout)
A wrapper for the select syscall.
This functions acts more or less like the select(2) syscall. There is no support for writing or exceptions. channels Arrays of channels pointers terminated by a NULL. It is never rewritten. outchannels Arrays of same size that "channels", there is no need to initialize it. maxfd Maximum +1 file descriptor from readfds. readfds A fd_set of file descriptors to be select'ed for reading. timeout The timeout in milliseconds. SSH_OK on success, SSH_ERROR on error, SSH_EINTR if it was interrupted. In that case, just restart it. libssh is not reentrant here. That means that if a signal is caught during the processing of this function, you cannot call libssh functions on sessions that are busy with ssh_select(). select(2)
References POLLIN, rc, session, ssh_channel_poll, SSH_ERROR, ssh_event_add_fd, ssh_event_add_session, ssh_event_dopoll, ssh_event_free, ssh_event_new, ssh_event_remove_fd, SSH_OK, ssh_select_cb, ssh_timeout_elapsed, ssh_timeout_update, ssh_timestamp_init, ZERO_STRUCT.
Referenced by select_loop, torture_channel_select.
LIBSSH_API int ssh_service_request(ssh_session session, const char *service)
References ssh_session_struct::auth, ssh_session_struct::out_buffer, rc, ssh_session_struct::service_state, session, SSH2_MSG_SERVICE_REQUEST, SSH_AGAIN, SSH_AUTH_SERVICE_ACCEPTED, SSH_AUTH_SERVICE_DENIED, SSH_AUTH_SERVICE_NONE, SSH_AUTH_SERVICE_SENT, ssh_buffer_pack, SSH_ERROR, SSH_FATAL, ssh_handle_packets_termination, SSH_LOG, SSH_LOG_PACKET, SSH_OK, ssh_packet_send, ssh_service_request_termination, ssh_set_error, ssh_set_error_oom, SSH_TIMEOUT_USER.
Referenced by ssh_userauth_request_service.
LIBSSH_API int ssh_set_agent_channel(ssh_session session, ssh_channel channel)
sets the SSH agent channel. The SSH agent channel will be used to authenticate this client using an agent through a channel, from another session. The most likely use is to implement SSH Agent forwarding into a SSH proxy.
channel a SSH channel from another session. SSH_OK in case of success SSH_ERROR in case of an error
References ssh_session_struct::agent, agent_set_channel, session, SSH_ERROR, SSH_OK, SSH_REQUEST_DENIED, ssh_set_error.
LIBSSH_API int ssh_set_agent_socket(ssh_session session, socket_t fd)
sets the SSH agent socket. The SSH agent will be used to authenticate this client using the given socket to communicate with the ssh-agent. The caller is responsible for connecting to the socket prior to calling this function.
SSH_OK in case of success SSH_ERROR in case of an error
References ssh_session_struct::agent, session, ssh_agent_struct::sock, SSH_ERROR, SSH_OK, SSH_REQUEST_DENIED, ssh_set_error, ssh_socket_set_fd.
LIBSSH_API void ssh_set_blocking(ssh_session session, int blocking)
Set the session in blocking/nonblocking mode.
session The ssh session to change. blocking Zero for nonblocking mode.
References ssh_session_struct::flags, session, SSH_SESSION_FLAG_BLOCKING.
Referenced by my_fd_data_function, ssh_channel_read_nonblocking, ssh_channel_set_blocking, ssh_new, torture_auth_agent_nonblocking, torture_auth_autopubkey_nonblocking, torture_auth_kbdint_nonblocking, torture_auth_none_nonblocking, torture_auth_password_nonblocking, torture_auth_pubkey_types_ecdsa_nonblocking, torture_auth_pubkey_types_ed25519_nonblocking, torture_auth_pubkey_types_nonblocking, torture_connect_nonblocking.
LIBSSH_API void ssh_set_counters(ssh_session session, ssh_counter scounter, ssh_counter rcounter)
Set the session data counters.
This functions sets the counter structures to be used to calculate data which comes in and goes out through the session at different levels. structssh_counter_structscounter={ .in_bytes=0, .out_bytes=0, .in_packets=0, .out_packets=0 }; structssh_counter_structrcounter={ .in_bytes=0, .out_bytes=0, .in_packets=0, .out_packets=0 }; ssh_set_counters(session,&scounter,&rcounter); session The SSH session. scounter Counter for byte data handled by the session sockets. rcounter Counter for byte and packet data handled by the session, prior compression and SSH overhead.
References ssh_session_struct::raw_counter, session, ssh_session_struct::socket_counter.
LIBSSH_API void ssh_set_fd_except(ssh_session session)
Tell the session it has an exception to catch on the file descriptor.
session The ssh session to use.
References session, ssh_session_struct::socket, ssh_socket_set_except.
LIBSSH_API void ssh_set_fd_toread(ssh_session session)
Tell the session it has data to read on the file descriptor without blocking.
session The ssh session to use.
References session, ssh_session_struct::socket, ssh_socket_set_read_wontblock.
LIBSSH_API void ssh_set_fd_towrite(ssh_session session)
Tell the session it may write to the file descriptor without blocking.
session The ssh session to use.
References session, ssh_session_struct::socket, ssh_socket_set_write_wontblock.
Referenced by ssh_client_connection_callback.
LIBSSH_API void ssh_silent_disconnect(ssh_session session)
Disconnect impolitely from a remote host by closing the socket.
Suitable if you forked and want to destroy this session. session The SSH session to disconnect.
References ssh_session_struct::alive, session, ssh_session_struct::socket, ssh_disconnect, ssh_socket_close.
Referenced by ssh::Session::silentDisconnect.
LIBSSH_API int ssh_set_pcap_file(ssh_session session, ssh_pcap_file pcapfile)
References session, SSH_ERROR, SSH_REQUEST_DENIED, ssh_set_error.
Referenced by set_pcap, torture_ssh_session.
LIBSSH_API int ssh_userauth_none(ssh_session session, const char *username)
Try to authenticate through the "none" method.
session The ssh session to use. username The username, this SHOULD be NULL. SSH_AUTH_ERROR: A serious error happened. SSH_AUTH_DENIED: Authentication failed: use another method SSH_AUTH_PARTIAL: You've been partially authenticated, you still have to use another method SSH_AUTH_SUCCESS: Authentication success SSH_AUTH_AGAIN: In nonblocking mode, you've got to call this again later. Most server implementations do not permit changing the username during authentication. The username should only be set with ssh_options_set() only before you connect to the server.
References ssh_session_struct::auth, ssh_session_struct::current_method, ssh_session_struct::opts, ssh_session_struct::out_buffer, ssh_session_struct::pending_call_state, rc, session, SSH2_MSG_USERAUTH_REQUEST, SSH_AGAIN, SSH_AUTH_AGAIN, SSH_AUTH_ERROR, SSH_AUTH_METHOD_NONE, SSH_AUTH_STATE_AUTH_NONE_SENT, ssh_buffer_pack, ssh_buffer_reinit, SSH_ERROR, SSH_FATAL, ssh_packet_send, SSH_PENDING_CALL_AUTH_NONE, SSH_PENDING_CALL_NONE, ssh_set_error, ssh_set_error_oom, ssh_userauth_get_response, ssh_userauth_request_service, ssh_session_struct::state, username, ssh_session_struct::username.
Referenced by authenticate_console, client, connect_host, LLVMFuzzerTestOneInput, main, test_algorithm, torture_algorithms_zlib, torture_algorithms_zlib_openssh, torture_auth_agent, torture_auth_agent_nonblocking, torture_auth_autopubkey, torture_auth_autopubkey_nonblocking, torture_auth_kbdint, torture_auth_kbdint_nonblocking, torture_auth_none, torture_auth_none_nonblocking, torture_auth_password, torture_auth_password_nonblocking, torture_auth_pubkey_types, torture_auth_pubkey_types_ecdsa, torture_auth_pubkey_types_ecdsa_nonblocking, torture_auth_pubkey_types_ed25519, torture_auth_pubkey_types_ed25519_nonblocking, torture_auth_pubkey_types_nonblocking, torture_rekey_send, torture_rekey_server_send, torture_rekey_time, torture_server_auth_kbdint, torture_server_auth_none, torture_server_auth_password, torture_server_auth_pubkey, torture_ssh_session, try_config_content, ssh::Session::userauthNone.
LIBSSH_API int ssh_userauth_list(ssh_session session, const char *username)
Get available authentication methods from the server.
This requires the function ssh_userauth_none() to be called before the methods are available. The server MAY return a list of methods that may continue. session The SSH session. username Deprecated, set to NULL. A bitfield of the fllowing values: SSH_AUTH_METHOD_PASSWORD SSH_AUTH_METHOD_PUBLICKEY SSH_AUTH_METHOD_HOSTBASED SSH_AUTH_METHOD_INTERACTIVE Other reserved flags may appear in future versions. ssh_userauth_none()
References ssh_session_struct::auth, session, ssh_session_struct::supported_methods, username.
Referenced by authenticate_console, ssh::Session::getAuthList, ssh_auth_list, torture_auth_agent, torture_auth_agent_nonblocking, torture_auth_autopubkey, torture_auth_autopubkey_nonblocking, torture_auth_kbdint, torture_auth_kbdint_nonblocking, torture_auth_password, torture_auth_password_nonblocking, torture_auth_pubkey_types, torture_auth_pubkey_types_ecdsa, torture_auth_pubkey_types_ecdsa_nonblocking, torture_auth_pubkey_types_ed25519, torture_auth_pubkey_types_ed25519_nonblocking, torture_auth_pubkey_types_nonblocking, torture_rekey_send, torture_rekey_server_send, torture_rekey_time, torture_server_auth_kbdint, torture_server_auth_password, torture_server_auth_pubkey, torture_ssh_session, try_config_content.
LIBSSH_API int ssh_userauth_try_publickey(ssh_session session, const char *username, const ssh_key pubkey)
Try to authenticate with the given public key.
To avoid unnecessary processing and user interaction, the following method is provided for querying whether authentication using the 'pubkey' would be possible. session The SSH session. username The username, this SHOULD be NULL. pubkey The public key to try. SSH_AUTH_ERROR: A serious error happened. SSH_AUTH_DENIED: The server doesn't accept that public key as an authentication token. Try another key or another method. SSH_AUTH_PARTIAL: You've been partially authenticated, you still have to use another method. SSH_AUTH_SUCCESS: The public key is accepted, you want now to use ssh_userauth_publickey(). SSH_AUTH_AGAIN: In nonblocking mode, you've got to call this again later. Most server implementations do not permit changing the username during authentication. The username should only be set with ssh_options_set() only before you connect to the server.
References ssh_session_struct::auth, ssh_session_struct::current_method, ssh_session_struct::opts, ssh_session_struct::out_buffer, ssh_session_struct::pending_call_state, pubkey, rc, session, SSH2_MSG_USERAUTH_REQUEST, SSH_AGAIN, SSH_AUTH_AGAIN, SSH_AUTH_DENIED, SSH_AUTH_ERROR, SSH_AUTH_METHOD_PUBLICKEY, SSH_AUTH_STATE_PUBKEY_OFFER_SENT, ssh_buffer_pack, ssh_buffer_reinit, SSH_ERROR, SSH_FATAL, ssh_key_algorithm_allowed, ssh_key_get_signature_algorithm, ssh_key_is_public, ssh_packet_send, SSH_PENDING_CALL_AUTH_OFFER_PUBKEY, SSH_PENDING_CALL_NONE, ssh_pki_export_pubkey_blob, SSH_REQUEST_DENIED, ssh_set_error, ssh_set_error_oom, SSH_STRING_FREE, ssh_userauth_get_response, ssh_userauth_request_service, ssh_session_struct::state, username, ssh_session_struct::username.
Referenced by auth_keyfile, ssh_userauth_agent, ssh_userauth_offer_pubkey, ssh_userauth_publickey_auto, torture_auth_cert, ssh::Session::userauthTryPublickey.
LIBSSH_API int ssh_userauth_publickey(ssh_session session, const char *username, const ssh_key privkey)
Authenticate with public/private key or certificate.
session The SSH session. username The username, this SHOULD be NULL. privkey The private key for authentication. SSH_AUTH_ERROR: A serious error happened. SSH_AUTH_DENIED: The server doesn't accept that public key as an authentication token. Try another key or another method. SSH_AUTH_PARTIAL: You've been partially authenticated, you still have to use another method. SSH_AUTH_SUCCESS: The public key is accepted. SSH_AUTH_AGAIN: In nonblocking mode, you've got to call this again later. Most server implementations do not permit changing the username during authentication. The username should only be set with ssh_options_set() only before you connect to the server.
References ssh_session_struct::auth, ssh_session_struct::current_method, ssh_session_struct::opts, ssh_session_struct::out_buffer, ssh_session_struct::pending_call_state, privkey, rc, session, SSH2_MSG_USERAUTH_REQUEST, SSH_AGAIN, SSH_AUTH_AGAIN, SSH_AUTH_DENIED, SSH_AUTH_ERROR, SSH_AUTH_METHOD_PUBLICKEY, SSH_AUTH_STATE_PUBKEY_AUTH_SENT, ssh_buffer_add_ssh_string, ssh_buffer_pack, ssh_buffer_reinit, SSH_ERROR, SSH_FATAL, ssh_key_algorithm_allowed, ssh_key_get_signature_algorithm, ssh_key_is_private, ssh_key_type_to_hash, ssh_packet_send, SSH_PENDING_CALL_AUTH_PUBKEY, SSH_PENDING_CALL_NONE, ssh_pki_do_sign, ssh_pki_export_pubkey_blob, SSH_REQUEST_DENIED, ssh_set_error, ssh_set_error_oom, SSH_STRING_FREE, ssh_userauth_get_response, ssh_userauth_request_service, ssh_session_struct::state, username, ssh_session_struct::username.
Referenced by auth_keyfile, ssh_userauth_pubkey, ssh_userauth_publickey_auto, torture_auth_cert, torture_auth_pubkey_types_ed25519, torture_auth_pubkey_types_ed25519_nonblocking, ssh::Session::userauthPublickey.
LIBSSH_API int ssh_userauth_agent(ssh_session session, const char *username)
Try to do public key authentication with ssh agent.
session The ssh session to use. username The username, this SHOULD be NULL. SSH_AUTH_ERROR: A serious error happened. SSH_AUTH_DENIED: The server doesn't accept that public key as an authentication token. Try another key or another method. SSH_AUTH_PARTIAL: You've been partially authenticated, you still have to use another method. SSH_AUTH_SUCCESS: The public key is accepted, you want now to use ssh_userauth_publickey(). SSH_AUTH_AGAIN: In nonblocking mode, you've got to call this again later. Most server implementations do not permit changing the username during authentication. The username should only be set with ssh_options_set() only before you connect to the server.
References ssh_session_struct::agent_state, rc, session, ssh_agent_get_first_ident, ssh_agent_get_next_ident, ssh_agent_is_running, SSH_AGENT_STATE_AUTH, ssh_agent_state_free, SSH_AGENT_STATE_NONE, SSH_AGENT_STATE_PUBKEY, SSH_AUTH_AGAIN, SSH_AUTH_DENIED, SSH_AUTH_ERROR, SSH_AUTH_PARTIAL, SSH_AUTH_SUCCESS, ssh_key_free, SSH_LOG, SSH_LOG_DEBUG, SSH_LOG_INFO, ssh_set_error_oom, SSH_STRING_FREE_CHAR, ssh_userauth_agent_publickey, ssh_userauth_try_publickey, ssh_agent_state_struct::state, username, ZERO_STRUCTP.
Referenced by ssh_userauth_publickey_auto, torture_auth_agent, torture_auth_agent_nonblocking.
LIBSSH_API int ssh_userauth_publickey_auto(ssh_session session, const char *username, const char *passphrase)
Tries to automatically authenticate with public key and "none".
It may fail, for instance it doesn't ask for a password and uses a default asker for passphrases (in case the private key is encrypted). session The SSH session. username The username, this SHOULD be NULL. passphrase Use this passphrase to unlock the privatekey. Use NULL if you don't want to use a passphrase or the user should be asked. SSH_AUTH_ERROR: A serious error happened. SSH_AUTH_DENIED: The server doesn't accept that public key as an authentication token. Try another key or another method. SSH_AUTH_PARTIAL: You've been partially authenticated, you still have to use another method. SSH_AUTH_SUCCESS: The public key is accepted, you want now to use ssh_userauth_publickey(). SSH_AUTH_AGAIN: In nonblocking mode, you've got to call this again later. Most server implementations do not permit changing the username during authentication. The username should only be set with ssh_options_set() only before you connect to the server.
References ssh_session_struct::auth, ssh_callbacks_struct::auth_function, ssh_session_struct::auto_state, ssh_common_struct::callbacks, ssh_session_struct::common, ssh_session_struct::flags, ssh_session_struct::identity, ssh_session_struct::opts, rc, SAFE_FREE, session, SSH_AUTH_AGAIN, SSH_AUTH_AUTO_STATE_KEY_IMPORTED, SSH_AUTH_AUTO_STATE_NONE, SSH_AUTH_AUTO_STATE_PUBKEY, SSH_AUTH_AUTO_STATE_PUBKEY_ACCEPTED, SSH_AUTH_DENIED, SSH_AUTH_ERROR, SSH_AUTH_METHOD_PUBLICKEY, SSH_AUTH_PARTIAL, SSH_AUTH_SUCCESS, SSH_EOF, SSH_ERROR, SSH_FATAL, ssh_key_free, ssh_list_get_iterator, SSH_LOG, SSH_LOG_DEBUG, SSH_LOG_INFO, SSH_LOG_WARN, SSH_OPT_FLAG_PUBKEY_AUTH, ssh_pki_export_privkey_to_pubkey, ssh_pki_export_pub_uri_from_priv_uri, ssh_pki_export_pubkey_file, ssh_pki_import_privkey_file, ssh_pki_import_pubkey_file, ssh_pki_is_uri, ssh_set_error, ssh_set_error_oom, ssh_userauth_agent, ssh_userauth_publickey, ssh_userauth_try_publickey, ssh_auth_auto_state_struct::state, ssh_session_struct::supported_methods, ssh_callbacks_struct::userdata, username.
Referenced by authenticate_console, ssh_userauth_autopubkey, torture_auth_autopubkey, torture_auth_autopubkey_nonblocking, torture_auth_pubkey_types, torture_auth_pubkey_types_ecdsa, torture_auth_pubkey_types_ecdsa_nonblocking, torture_auth_pubkey_types_nonblocking, torture_rekey_send, torture_rekey_server_send, torture_rekey_time, torture_server_auth_pubkey, torture_ssh_session, try_config_content, ssh::Session::userauthPublickeyAuto.
LIBSSH_API int ssh_userauth_password(ssh_session session, const char *username, const char *password)
Try to authenticate by password.
This authentication method is normally disabled on SSHv2 server. You should use keyboard-interactive mode. The 'password' value MUST be encoded UTF-8. It is up to the server how to interpret the password and validate it against the password database. However, if you read the password in some other encoding, you MUST convert the password to UTF-8. session The ssh session to use. username The username, this SHOULD be NULL. password The password to authenticate in UTF-8. SSH_AUTH_ERROR: A serious error happened. SSH_AUTH_DENIED: Authentication failed: use another method SSH_AUTH_PARTIAL: You've been partially authenticated, you still have to use another method SSH_AUTH_SUCCESS: Authentication success SSH_AUTH_AGAIN: In nonblocking mode, you've got to call this again later. Most server implementations do not permit changing the username during authentication. The username should only be set with ssh_options_set() only before you connect to the server. ssh_userauth_none() ssh_userauth_kbdint()
References ssh_session_struct::auth, ssh_session_struct::current_method, ssh_session_struct::opts, ssh_session_struct::out_buffer, ssh_session_struct::pending_call_state, rc, session, SSH2_MSG_USERAUTH_REQUEST, SSH_AGAIN, SSH_AUTH_AGAIN, SSH_AUTH_ERROR, SSH_AUTH_METHOD_PASSWORD, SSH_AUTH_STATE_PASSWORD_AUTH_SENT, ssh_buffer_pack, ssh_buffer_reinit, ssh_buffer_set_secure, SSH_ERROR, SSH_FATAL, ssh_packet_send, SSH_PENDING_CALL_AUTH_PASSWORD, SSH_PENDING_CALL_NONE, ssh_set_error, ssh_set_error_oom, ssh_userauth_get_response, ssh_userauth_request_service, ssh_session_struct::state, username, ssh_session_struct::username.
Referenced by authenticate, authenticate_console, torture_auth_password, torture_auth_password_nonblocking, torture_server_auth_password, torture_server_unknown_global_request, torture_ssh_session, ssh::Session::userauthPassword.
LIBSSH_API int ssh_userauth_kbdint(ssh_session session, const char *user, const char *submethods)
Try to authenticate through the "keyboard-interactive" method.
session The ssh session to use. user The username to authenticate. You can specify NULL if ssh_option_set_username() has been used. You cannot try two different logins in a row. submethods Undocumented. Set it to NULL. SSH_AUTH_ERROR: A serious error happened SSH_AUTH_DENIED: Authentication failed : use another method SSH_AUTH_PARTIAL: You've been partially authenticated, you still have to use another method SSH_AUTH_SUCCESS: Authentication success SSH_AUTH_INFO: The server asked some questions. Use ssh_userauth_kbdint_getnprompts() and such. SSH_AUTH_AGAIN: In nonblocking mode, you've got to call this again later. ssh_userauth_kbdint_getnprompts() ssh_userauth_kbdint_getname() ssh_userauth_kbdint_getinstruction() ssh_userauth_kbdint_getprompt() ssh_userauth_kbdint_setanswer()
References ssh_session_struct::kbdint, ssh_session_struct::pending_call_state, rc, session, SSH_AUTH_ERROR, SSH_FATAL, SSH_PENDING_CALL_AUTH_KBDINT_INIT, SSH_PENDING_CALL_AUTH_KBDINT_SEND, SSH_PENDING_CALL_NONE, ssh_set_error, ssh_userauth_kbdint_init, ssh_userauth_kbdint_send, user.
Referenced by _torture_auth_kbdint, auth_kbdint, authenticate_kbdint, torture_auth_kbdint, torture_auth_kbdint_nonblocking, torture_server_auth_kbdint, ssh::Session::userauthKbdint.
LIBSSH_API const char* ssh_userauth_kbdint_getinstruction(ssh_session session)
Get the "instruction" of the message block.
Once you have called ssh_userauth_kbdint() and received SSH_AUTH_INFO return code, this function can be used to retrieve information about the keyboard interactive authentication questions sent by the remote host. session The ssh session to use. The instruction of the message block.
References ssh_kbdint_struct::instruction, ssh_session_struct::kbdint, session, ssh_set_error_invalid.
Referenced by auth_kbdint, authenticate_kbdint.
LIBSSH_API const char* ssh_userauth_kbdint_getname(ssh_session session)
Get the "name" of the message block.
Once you have called ssh_userauth_kbdint() and received SSH_AUTH_INFO return code, this function can be used to retrieve information about the keyboard interactive authentication questions sent by the remote host. session The ssh session to use. The name of the message block. Do not free it.
References ssh_session_struct::kbdint, ssh_kbdint_struct::name, session, ssh_set_error_invalid.
Referenced by auth_kbdint, authenticate_kbdint.
LIBSSH_API int ssh_userauth_kbdint_getnprompts(ssh_session session)
Get the number of prompts (questions) the server has given.
Once you have called ssh_userauth_kbdint() and received SSH_AUTH_INFO return code, this function can be used to retrieve information about the keyboard interactive authentication questions sent by the remote host. session The ssh session to use. The number of prompts.
References ssh_session_struct::kbdint, ssh_kbdint_struct::nprompts, session, SSH_ERROR, ssh_set_error_invalid.
Referenced by _torture_auth_kbdint, auth_kbdint, authenticate_kbdint, torture_auth_kbdint, torture_auth_kbdint_nonblocking, torture_server_auth_kbdint, ssh::Session::userauthKbdintGetNPrompts.
LIBSSH_API const char* ssh_userauth_kbdint_getprompt(ssh_session session, unsigned int i, char *echo)
Get a prompt from a message block.
Once you have called ssh_userauth_kbdint() and received SSH_AUTH_INFO return code, this function can be used to retrieve information about the keyboard interactive authentication questions sent by the remote host. session The ssh session to use. i The index number of the i'th prompt. echo This is an optional variable. You can obtain a boolean if the user input should be echoed or hidden. For passwords it is usually hidden. A pointer to the prompt. Do not free it. constcharprompt; charecho; prompt=ssh_userauth_kbdint_getprompt(session,0,&echo); if(echo)...
References echo, ssh_kbdint_struct::echo, ssh_session_struct::kbdint, ssh_kbdint_struct::nprompts, ssh_kbdint_struct::prompts, session, ssh_set_error_invalid.
Referenced by _torture_auth_kbdint, auth_kbdint, authenticate_kbdint.
LIBSSH_API int ssh_userauth_kbdint_getnanswers(ssh_session session)
Referenced by authenticate_kbdint, kbdint_check_response.
LIBSSH_API const char* ssh_userauth_kbdint_getanswer(ssh_session session, unsigned int i)
Referenced by authenticate_kbdint, kbdint_check_response.
LIBSSH_API int ssh_userauth_kbdint_setanswer(ssh_session session, unsigned int i, const char *answer)
Set the answer for a question from a message block.
If you have called ssh_userauth_kbdint() and got SSH_AUTH_INFO, this function returns the questions from the server. session The ssh session to use. i index The number of the ith prompt. answer The answer to give to the server. The answer MUST be encoded UTF-8. It is up to the server how to interpret the value and validate it. However, if you read the answer in some other encoding, you MUST convert it to UTF-8. 0 on success, < 0 on error.
References ssh_kbdint_struct::answers, explicit_bzero, ssh_session_struct::kbdint, ssh_kbdint_struct::nprompts, SAFE_FREE, session, ssh_set_error_invalid, ssh_set_error_oom.
Referenced by _torture_auth_kbdint, auth_kbdint, authenticate_kbdint, torture_auth_kbdint, torture_auth_kbdint_nonblocking, torture_server_auth_kbdint, ssh::Session::userauthKbdintSetAnswer.
LIBSSH_API int ssh_userauth_gssapi(ssh_session session)
Try to authenticate through the "gssapi-with-mic" method.
session The ssh session to use. SSH_AUTH_ERROR: A serious error happened SSH_AUTH_DENIED: Authentication failed : use another method SSH_AUTH_PARTIAL: You've been partially authenticated, you still have to use another method SSH_AUTH_SUCCESS: Authentication success SSH_AUTH_AGAIN: In nonblocking mode, you've got to call this again later.
Referenced by authenticate_console, main.
LIBSSH_API const char* ssh_version(int req_version)
Check if libssh is the required version or get the version string.
req_version The version required. If the version of libssh is newer than the version required it will return a version string. NULL if the version is older. Example: if(ssh_version(SSH_VERSION_INT(0,2,1))==NULL){ fprintf(stderr,"libsshversionistooold!\n"); exit(1); } if(debug){ printf("libssh%s\n",ssh_version(0)); }
References CRYPTO_STRING, GCRYPT_STRING, LIBSSH_VERSION, LIBSSH_VERSION_INT, MBED_STRING, SSH_STRINGIFY, ZLIB_STRING.
Referenced by usage.
LIBSSH_API void ssh_string_burn(ssh_string str)
Referenced by pki_import_privkey_buffer, pki_import_pubkey_buffer, pki_publickey_to_blob, pki_signature_from_dsa_blob, pki_signature_from_ecdsa_blob, ssh_buffer_unpack_va, ssh_generate_session_keys, ssh_key_clean, SSH_PACKET_CALLBACK, ssh_signature_free, string_burn.
LIBSSH_API ssh_string ssh_string_copy(ssh_string str)
Referenced by pki_signature_from_ed25519_blob, pki_signature_from_rsa_blob, pki_signature_to_blob, string_copy.
LIBSSH_API void* ssh_string_data(ssh_string str)
Referenced by check_public_key, pki_dsa_signature_to_blob, pki_ecdsa_signature_to_blob, pki_ed25519_signature_to_blob, pki_import_privkey_buffer, pki_import_pubkey_buffer, pki_private_key_decrypt, pki_private_key_encrypt, pki_privkey_build_ed25519, pki_signature_from_dsa_blob, pki_signature_from_ecdsa_blob, pki_signature_from_ed25519_blob, pki_signature_from_rsa_blob, pki_verify_data_signature, sftp_handle, sftp_handle_alloc, ssh_buffer_get_ssh_string, ssh_get_pubkey_hash, ssh_get_publickey_hash, ssh_gssapi_oid_from_string, SSH_PACKET_CALLBACK, ssh_pki_export_privkey_base64, ssh_pki_export_privkey_file, ssh_pki_export_pubkey_base64, ssh_pki_import_pubkey_blob, ssh_pki_import_signature_blob, ssh_pki_openssh_import, ssh_pki_openssh_privkey_export, ssh_pki_signature_verify, ssh_publickey_to_file, string_data, thread_ssh_buffer_get_format, torture_pki_ed25519_generate_key, torture_pki_ed25519_sign, torture_pki_ed25519_sign_openssh_privkey_passphrase, torture_pki_ed25519_verify, torture_pki_ed25519_verify_bad, torture_pubkey_generate_from_privkey, torture_ssh_buffer_get_format.
LIBSSH_API int ssh_string_fill(ssh_string str, const void *data, size_t len)
Referenced by pki_dsa_signature_to_blob, pki_ecdsa_signature_to_blob, pki_ed25519_signature_to_blob, pki_private_key_to_pem, pki_publickey_to_blob, pki_sign_data, pki_signature_from_dsa_blob, pki_signature_from_ecdsa_blob, ssh_pki_do_sign, ssh_pki_do_sign_agent, ssh_pki_export_signature_blob, string_fill, torture_pki_ed25519_verify, torture_pki_ed25519_verify_bad, torture_session_keys.
LIBSSH_API void ssh_string_free(ssh_string str)
Referenced by check_public_key, ssh_key_clean, ssh_userauth_privatekey_file, string_free, torture_pki_verify_mismatch.
LIBSSH_API ssh_string ssh_string_from_char(const char *what)
Create a ssh string using a C string.
what The source 0-terminated C string. The newly allocated string, NULL on error with errno set. The nul byte is not copied nor counted in the ouput string.
References ssh_string_struct::data, ssh_string_new.
Referenced by pki_import_cert_buffer, pki_publickey_to_blob, sftp_reply_name, sftp_reply_names_add, sftp_reply_status, ssh_message_auth_reply_pk_ok_simple, ssh_pki_export_signature_blob, ssh_send_kex, string_from_char, thread_ssh_buffer_add_format, torture_ssh_buffer_add_format.
LIBSSH_API size_t ssh_string_len(ssh_string str)
Referenced by check_public_key, pki_dsa_signature_to_blob, pki_ecdsa_signature_to_blob, pki_ed25519_signature_to_blob, pki_import_privkey_buffer, pki_import_pubkey_buffer, pki_private_key_decrypt, pki_private_key_encrypt, pki_privkey_build_ed25519, pki_signature_from_dsa_blob, pki_signature_from_ecdsa_blob, pki_signature_from_ed25519_blob, pki_signature_from_rsa_blob, pki_verify_data_signature, sftp_handle, ssh_agent_sign_data, ssh_buffer_add_ssh_string, ssh_buffer_pack_allocate_va, ssh_generate_session_keys, ssh_get_pubkey_hash, ssh_get_publickey_hash, ssh_gssapi_oid_from_string, ssh_key_cmp, ssh_make_string_bn, SSH_PACKET_CALLBACK, ssh_pki_export_privkey_base64, ssh_pki_export_privkey_file, ssh_pki_export_pubkey_base64, ssh_pki_import_pubkey_blob, ssh_pki_import_signature_blob, ssh_pki_openssh_import, ssh_pki_signature_verify, ssh_publickey_to_file, string_len, thread_ssh_buffer_get_format, torture_pki_ed25519_sign, torture_pki_ed25519_sign_openssh_privkey_passphrase, torture_pubkey_generate_from_privkey, torture_ssh_buffer_get_format.
LIBSSH_API ssh_string ssh_string_new(size_t size)
Create a new SSH String object.
size The size of the string. The newly allocated string, NULL on error.
References ssh_string_struct::data, ssh_string_struct::size, STRING_SIZE_MAX.
Referenced by pki_dsa_signature_to_blob, pki_ecdsa_signature_to_blob, pki_ed25519_signature_to_blob, pki_private_key_to_pem, pki_publickey_to_blob, pki_sign_data, pki_signature_from_dsa_blob, pki_signature_from_ecdsa_blob, pki_signature_from_rsa_blob, sftp_handle_alloc, ssh_buffer_get_ssh_string, ssh_gssapi_auth_mic, ssh_make_bignum_string, ssh_pki_do_sign, ssh_pki_do_sign_agent, ssh_pki_export_signature_blob, ssh_pki_openssh_privkey_export, ssh_string_copy, ssh_string_from_char, string_new, torture_pki_ed25519_verify, torture_pki_ed25519_verify_bad, torture_session_keys.
LIBSSH_API const char* ssh_string_get_char(ssh_string str)
Referenced by pki_import_privkey_buffer, pki_import_pubkey_buffer, ssh_key_cmp, ssh_pki_import_pubkey_blob, ssh_pki_import_signature_blob.
LIBSSH_API char* ssh_string_to_char(ssh_string str)
Referenced by sftp_client_message_get_data, ssh_agent_get_next_ident, ssh_get_issue_banner, SSH_PACKET_CALLBACK, string_to_char.
LIBSSH_API void ssh_string_free_char(char *s)
Deallocate a char string object.
s The string to delete.
References s, SAFE_FREE.
LIBSSH_API int ssh_getpass(const char *prompt, char *buf, size_t len, int echo, int verify)
Get a password from the console.
You should make sure that the buffer is an empty string! You can also use this function to ask for a username. Then you can fill the buffer with the username and it is shows to the users. If the users just presses enter the buffer will be untouched. charusername[128]; snprintf(username,sizeof(username),"john"); ssh_getpass("Username:",username,sizeof(username),1,0); The prompt will look like this: Username: [john] If you press enter then john is used as the username, or you can type it in to change it. prompt The prompt to show to ask for the password. buf The buffer the password should be stored. It NEEDS to be empty or filled out. len The length of the buffer. echo Should we echo what you type. verify Should we ask for the password twice. 0 on success, -1 on error.
References echo, explicit_bzero, ssh_gets, ZERO_STRUCT.
Referenced by auth_callback, authenticate_console, authenticate_kbdint.
LIBSSH_API ssh_event ssh_event_new(void)
Create a new event context. It could be associated with many ssh_session objects and socket fd which are going to be polled at the same time as the event context. You would need a single event context per thread.
The ssh_event object on success, NULL on failure.
References ssh_event_struct::ctx, ssh_list_new, ssh_poll_ctx_free, ssh_poll_ctx_new, ZERO_STRUCTP.
Referenced by LLVMFuzzerTestOneInput, main, pkd_exec_hello, run_server, select_loop, ssh_channel_select, ssh_select, test_ssh_channel_request_x11.
LIBSSH_API int ssh_event_add_fd(ssh_event event, socket_t fd, short events, ssh_event_callback cb, void *userdata)
Add a fd to the event and assign it a callback, when used in blocking mode.
event The ssh_event fd Socket that will be polled. events Poll events that will be monitored for the socket. i.e. POLLIN, POLLPRI, POLLOUT cb Function to be called if any of the events are set. The prototype of cb is: int (*ssh_event_callback)(socket_t fd, int revents, void *userdata); userdata Userdata to be passed to the callback function. NULL if not needed. SSH_OK on success SSH_ERROR on failure
References cb, ssh_event_fd_wrapper::cb, ssh_event_struct::ctx, SSH_ERROR, ssh_event_fd_wrapper_callback, SSH_INVALID_SOCKET, SSH_OK, ssh_poll_ctx_add, ssh_poll_free, ssh_poll_new, ssh_event_fd_wrapper::userdata.
Referenced by default_handle_session_cb, handle_kbdint_session_cb, handle_session, message_callback, ssh_select.
LIBSSH_API int ssh_event_add_session(ssh_event event, ssh_session session)
remove the poll handle from session and assign them to a event, when used in blocking mode.
event The ssh_event object session The session to add to the event. SSH_OK on success SSH_ERROR on failure
References ssh_event_struct::ctx, ssh_iterator::data, ssh_session_struct::default_poll_ctx, ssh_iterator::next, ssh_poll_ctx_struct::pollptrs, ssh_poll_ctx_struct::polls_used, ssh_poll_handle_struct::session, session, SSH_ERROR, ssh_list_append, ssh_list_get_iterator, SSH_OK, ssh_poll_ctx_add, ssh_poll_ctx_remove.
Referenced by default_handle_session_cb, handle_kbdint_session_cb, handle_session, LLVMFuzzerTestOneInput, main, pkd_exec_hello, ssh_channel_select, ssh_connector_set_event, ssh_select, test_ssh_channel_request_x11.
LIBSSH_API int ssh_event_add_connector(ssh_event event, ssh_connector connector)
Add a connector to the SSH event loop.
event The SSH event loop connector The connector object SSH_OK SSH_ERROR in case of error
References ssh_connector_set_event.
Referenced by select_loop.
LIBSSH_API int ssh_event_dopoll(ssh_event event, int timeout)
Poll all the sockets and sessions associated through an event object.i.
If any of the events are set after the poll, the call back functions of the sessions or sockets will be called. This function should be called once within the programs main loop. event The ssh_event object to poll. timeout An upper limit on the time for which the poll will block, in milliseconds. Specifying a negative value means an infinite timeout. This parameter is passed to the poll() function. SSH_OK on success. SSH_ERROR Error happened during the poll. SSH_AGAIN Timeout occured
References ssh_event_struct::ctx, rc, SSH_ERROR, ssh_poll_ctx_dopoll.
Referenced by default_handle_session_cb, handle_kbdint_session_cb, handle_session, LLVMFuzzerTestOneInput, main, pkd_exec_hello, select_loop, ssh_channel_select, ssh_select, test_ssh_channel_request_x11.
LIBSSH_API int ssh_event_remove_fd(ssh_event event, socket_t fd)
Remove a socket fd from an event context.
event The ssh_event object. fd The fd to remove. SSH_OK on success SSH_ERROR on failure
References ssh_poll_handle_struct::cb, ssh_poll_handle_struct::cb_data, ssh_poll_handle_struct::ctx, ssh_event_struct::ctx, ssh_pollfd_struct::fd, ssh_poll_ctx_struct::pollfds, ssh_poll_ctx_struct::pollptrs, rc, SAFE_FREE, ssh_poll_handle_struct::session, SSH_ERROR, ssh_event_fd_wrapper_callback, SSH_OK, ssh_poll_free.
Referenced by _close_socket, default_handle_session_cb, handle_kbdint_session_cb, handle_session, ssh_select.
LIBSSH_API int ssh_event_remove_session(ssh_event event, ssh_session session)
Remove a session object from an event context.
event The ssh_event object. session The session to remove. SSH_OK on success SSH_ERROR on failure
References ssh_poll_handle_struct::ctx, ssh_event_struct::ctx, ssh_iterator::data, ssh_session_struct::default_poll_ctx, ssh_iterator::next, ssh_poll_ctx_struct::pollptrs, rc, ssh_poll_handle_struct::session, session, SSH_ERROR, ssh_list_get_iterator, ssh_list_remove, SSH_OK, ssh_poll_ctx_add, ssh_poll_ctx_remove.
Referenced by pkd_exec_hello, ssh_connector_remove_event.
LIBSSH_API int ssh_event_remove_connector(ssh_event event, ssh_connector connector)
Remove a connector from an event context.
event The ssh_event object. connector connector object to remove SSH_OK on success SSH_ERROR on failure
References ssh_connector_remove_event.
Referenced by select_loop.
LIBSSH_API void ssh_event_free(ssh_event event)
Free an event context.
event The ssh_event object to free. Note: you have to manually remove sessions and socket fds before freeing the event object.
References ssh_poll_handle_struct::ctx, ssh_event_struct::ctx, ssh_session_struct::default_poll_ctx, ssh_poll_ctx_struct::pollptrs, ssh_poll_ctx_struct::polls_used, ssh_poll_handle_struct::session, ssh_list_free, ssh_poll_ctx_add, ssh_poll_ctx_free, ssh_poll_ctx_remove.
Referenced by LLVMFuzzerTestOneInput, main, pkd_exec_hello, run_server, select_loop, ssh_channel_select, ssh_select, test_ssh_channel_request_x11.
LIBSSH_API const char* ssh_get_clientbanner(ssh_session session)
get the client banner
session The SSH session Returns the client banner string or NULL.
References ssh_session_struct::clientbanner, session.
LIBSSH_API const char* ssh_get_serverbanner(ssh_session session)
get the server banner
session The SSH session Returns the server banner string or NULL.
References ssh_session_struct::serverbanner, session.
Referenced by main.
LIBSSH_API const char* ssh_get_kex_algo(ssh_session session)
get the name of the current key exchange algorithm.
session The SSH session Returns the key exchange algorithm string or NULL.
References ssh_session_struct::current_crypto, ssh_crypto_struct::kex_type, session, SSH_KEX_CURVE25519_SHA256, SSH_KEX_CURVE25519_SHA256_LIBSSH_ORG, SSH_KEX_DH_GROUP14_SHA1, SSH_KEX_DH_GROUP16_SHA512, SSH_KEX_DH_GROUP18_SHA512, SSH_KEX_DH_GROUP1_SHA1, SSH_KEX_ECDH_SHA2_NISTP256, SSH_KEX_ECDH_SHA2_NISTP384, SSH_KEX_ECDH_SHA2_NISTP521.
LIBSSH_API const char* ssh_get_cipher_in(ssh_session session)
get the name of the input cipher for the given session.
session The SSH session. Returns cipher name or NULL.
References ssh_session_struct::current_crypto, ssh_crypto_struct::in_cipher, ssh_cipher_struct::name, session.
LIBSSH_API const char* ssh_get_cipher_out(ssh_session session)
get the name of the output cipher for the given session.
session The SSH session. Returns cipher name or NULL.
References ssh_session_struct::current_crypto, ssh_cipher_struct::name, ssh_crypto_struct::out_cipher, session.
LIBSSH_API const char* ssh_get_hmac_in(ssh_session session)
get the name of the input HMAC algorithm for the given session.
session The SSH session. Returns HMAC algorithm name or NULL if unknown.
References ssh_session_struct::current_crypto, ssh_crypto_struct::in_hmac_etm, session, ssh_hmac_type_to_string.
LIBSSH_API const char* ssh_get_hmac_out(ssh_session session)
get the name of the output HMAC algorithm for the given session.
session The SSH session. Returns HMAC algorithm name or NULL if unknown.
References ssh_session_struct::current_crypto, ssh_crypto_struct::out_hmac, ssh_crypto_struct::out_hmac_etm, session, ssh_hmac_type_to_string.
LIBSSH_API ssh_buffer ssh_buffer_new(void)
Create a new SSH buffer.
A newly initialized SSH buffer, NULL on error.
References buffer_verify, rc, SAFE_FREE, ssh_buffer_allocate_size.
Referenced by base64_to_bin, buffer_new, channel_default_bufferize, gzip_compress, gzip_decompress, main, pki_ecdsa_signature_to_blob, pki_import_cert_buffer, pki_private_key_decrypt, pki_publickey_to_blob, pki_signature_from_ecdsa_blob, setup, sftp_get_client_message, sftp_reply_attr, sftp_reply_data, sftp_reply_handle, sftp_reply_name, sftp_reply_names, sftp_reply_names_add, sftp_reply_status, ssh_agent_get_ident_count, ssh_agent_sign_data, ssh_channel_cancel_forward, ssh_channel_change_pty_size, ssh_channel_listen_forward, ssh_channel_new, ssh_channel_open_forward, ssh_channel_open_forward_unix, ssh_channel_request_env, ssh_channel_request_exec, ssh_channel_request_pty_size, ssh_channel_request_send_break, ssh_channel_request_send_signal, ssh_channel_request_subsystem, ssh_channel_request_x11, ssh_gssapi_build_mic, ssh_hashbufin_add_cookie, ssh_hashbufout_add_cookie, ssh_make_sessionid, ssh_new, ssh_packet_send, ssh_packet_socket_callback, ssh_pki_copy_cert_to_privkey, ssh_pki_do_sign, ssh_pki_do_sign_agent, ssh_pki_export_signature_blob, ssh_pki_import_pubkey_blob, ssh_pki_import_signature_blob, ssh_pki_openssh_import, ssh_pki_openssh_privkey_export, ssh_pki_signature_verify, ssh_socket_new, thread_buffer_pack_badformat, thread_buffer_prepend, thread_growing_buffer, thread_growing_buffer_shifting, thread_ssh_buffer_add_format, thread_ssh_buffer_get_format, thread_ssh_buffer_get_format_error, thread_ssh_buffer_get_ssh_string, torture_ssh_buffer_get_ssh_string.
LIBSSH_API void ssh_buffer_free(ssh_buffer buffer)
Referenced by buffer_free, check_public_key, match_hashed_host, ssh_pki_signature_verify.
LIBSSH_API int ssh_buffer_reinit(ssh_buffer buffer)
Referenced by channel_read_buffer, channel_request, channel_write_common, compress_buffer, decompress_buffer, grow_window, packet_send2, ssh_agent_get_ident_count, ssh_channel_close, ssh_channel_send_eof, ssh_disconnect, ssh_global_request, ssh_gssapi_send_auth_mic, ssh_hashbufin_add_cookie, ssh_hashbufout_add_cookie, ssh_packet_socket_callback, ssh_pki_openssh_privkey_export, ssh_send_debug, ssh_send_ignore, ssh_send_kex, ssh_server_send_extensions, ssh_socket_reset, ssh_userauth_agent_publickey, ssh_userauth_kbdint_init, ssh_userauth_kbdint_send, ssh_userauth_none, ssh_userauth_password, ssh_userauth_publickey, ssh_userauth_try_publickey, thread_buffer_pack_badformat, torture_buffer_pack_badformat.
LIBSSH_API int ssh_buffer_add_data(ssh_buffer buffer, const void *data, uint32_t len)
Referenced by agent_talk, base64_to_bin, channel_default_bufferize, channel_read_buffer, channel_request, compress_buffer, decompress_buffer, gzip_compress, gzip_decompress, packet_send2, pki_private_key_decrypt, pki_signature_from_ecdsa_blob, sftp_get_client_message, sftp_reply_data, sftp_reply_names, ssh_agent_sign_data, ssh_global_request, ssh_hashbufin_add_cookie, ssh_hashbufout_add_cookie, ssh_pki_import_pubkey_blob, ssh_pki_import_signature_blob, ssh_pki_openssh_import, ssh_socket_pollcallback, ssh_socket_write, thread_buffer_prepend, thread_growing_buffer, thread_growing_buffer_shifting, thread_ssh_buffer_get_format, thread_ssh_buffer_get_format_error, thread_ssh_buffer_get_ssh_string, torture_buffer_prepend, torture_growing_buffer, torture_growing_buffer_shifting, torture_packet, torture_ssh_buffer_get_format, torture_ssh_buffer_get_format_error, torture_ssh_buffer_get_ssh_string.
LIBSSH_API uint32_t ssh_buffer_get_data(ssh_buffer buffer, void *data, uint32_t requestedlen)
Referenced by SSH_PACKET_CALLBACK, ssh_pki_openssh_privkey_export.
LIBSSH_API void* ssh_buffer_get(ssh_buffer buffer)
Referenced by agent_talk, buffer_get, channel_request, check_public_key, compress_buffer, decompress_buffer, gzip_compress, gzip_decompress, match_hashed_host, match_hashed_hostname, packet_send2, pki_ecdsa_signature_to_blob, pki_private_key_encrypt, pki_publickey_to_blob, sftp_get_client_message, sftp_reply_names, ssh_agent_sign_data, ssh_channel_read_timeout, ssh_global_request, ssh_gssapi_send_mic, ssh_make_sessionid, SSH_PACKET_CALLBACK, ssh_packet_send, ssh_packet_socket_callback, ssh_packet_write, ssh_pki_do_sign, ssh_pki_export_signature_blob, ssh_pki_openssh_privkey_export, ssh_pki_signature_verify, ssh_socket_nonblocking_flush, ssh_socket_pollcallback, thread_buffer_prepend, thread_ssh_buffer_add_format, torture_buffer_prepend, torture_ssh_buffer_add_format.
LIBSSH_API uint32_t ssh_buffer_get_len(ssh_buffer buffer)
Referenced by agent_talk, buffer_get_len, channel_protocol_select, channel_request, check_public_key, compress_buffer, decompress_buffer, gzip_compress, gzip_decompress, match_hashed_host, match_hashed_hostname, packet_send2, pki_ecdsa_signature_to_blob, pki_private_key_encrypt, pki_publickey_to_blob, pki_signature_from_ecdsa_blob, sftp_get_client_message, sftp_reply_names, ssh_agent_sign_data, ssh_channel_is_eof, ssh_channel_poll, ssh_channel_poll_timeout, ssh_channel_read_termination, ssh_channel_read_timeout, ssh_global_request, ssh_gssapi_send_mic, ssh_make_sessionid, SSH_PACKET_CALLBACK, ssh_packet_send, ssh_packet_socket_callback, ssh_packet_write, ssh_pki_do_sign, ssh_pki_export_signature_blob, ssh_pki_openssh_import, ssh_pki_openssh_privkey_export, ssh_pki_signature_verify, ssh_socket_buffered_write_bytes, ssh_socket_get_status, ssh_socket_nonblocking_flush, ssh_socket_pollcallback, thread_buffer_prepend, thread_growing_buffer, thread_growing_buffer_shifting, thread_ssh_buffer_add_format, thread_ssh_buffer_get_format, torture_buffer_prepend, torture_growing_buffer, torture_growing_buffer_shifting, torture_ssh_buffer_add_format, torture_ssh_buffer_get_format.