log.c
LIBSSH_THREAD int ssh_log_level
Referenced by ssh_get_log_level, ssh_set_log_level.
LIBSSH_THREAD ssh_logging_callback ssh_log_cb
Referenced by ssh_get_log_callback, ssh_set_log_callback.
LIBSSH_THREAD void* ssh_log_userdata
Referenced by ssh_get_log_userdata, ssh_set_log_userdata.
static int current_timestring(int hires, char *buf, size_t len)
Referenced by ssh_log_stderr.
static void ssh_log_stderr(int verbosity, const char *function, const char *buffer)
References buffer, current_timestring, rc, verbosity.
Referenced by ssh_log_function.
void ssh_log_function(int verbosity, const char *function, const char *buffer)
References buffer, ssh_get_log_callback, ssh_get_log_userdata, ssh_log_stderr, verbosity.
Referenced by _ssh_log, _ssh_set_error, ssh_log, ssh_log_common.
void _ssh_log(int verbosity, const char *function, const char *format,...)
References buffer, ssh_get_log_level, ssh_log_function, verbosity.
void ssh_log(ssh_session session, int verbosity, const char *format,...)
References buffer, ssh_log_function, verbosity.
void ssh_log_common(struct ssh_common_struct *common, int verbosity, const char *function, const char *format,...)
References buffer, ssh_log_function, verbosity.
int ssh_set_log_level(int level)
Set the log level of the library.
level The level to set. SSH_OK on success, SSH_ERROR on error.
References SSH_ERROR, ssh_log_level, SSH_OK.
Referenced by ssh_options_getopt, ssh_options_set, torture_bind_config_full, torture_bind_config_include, torture_bind_config_include_recursive, torture_bind_config_loglevel, torture_bind_config_match_all, torture_bind_config_match_corner_cases, torture_bind_config_match_invalid, torture_bind_config_match_not_allowed, torture_bind_config_match_twice, torture_bind_config_match_unsupported, torture_log_callback.
int ssh_get_log_level(void)
Get the log level of the library.
The value of the log level.
References ssh_log_level.
Referenced by _ssh_log, _ssh_set_error, assert_full_bind_config, torture_bind_config_full, torture_bind_config_include, torture_bind_config_include_recursive, torture_bind_config_loglevel, torture_bind_config_match_all, torture_bind_config_match_corner_cases, torture_bind_config_match_invalid, torture_bind_config_match_not_allowed, torture_bind_config_match_twice, torture_bind_config_match_unsupported, torture_config_new.
int ssh_set_log_callback(ssh_logging_callback cb)
Set the logging callback function.
cb The callback to set. 0 on success, < 0 on errror.
References cb, SSH_ERROR, ssh_log_cb, SSH_OK.
Referenced by ssh_set_callbacks, torture_log_callback.
ssh_logging_callback ssh_get_log_callback(void)
Get the pointer to the logging callback function.
The pointer the the callback or NULL if none set.
References ssh_log_cb.
Referenced by ssh_log_function, ssh_set_callbacks.
void* ssh_get_log_userdata(void)
Get the userdata of the logging function.
The userdata if set or NULL.
References ssh_log_userdata.
Referenced by ssh_log_function.
int ssh_set_log_userdata(void *data)
Set the userdata for the logging function.
data The userdata to set. SSH_OK on success.
References ssh_log_userdata.
Referenced by ssh_set_callbacks, torture_log_callback.