mbedtls.c
int crypto_thread_init(struct ssh_threads_callbacks_struct *user_callbacks)
References cb, crypto_thread_finalize, libcrypto_lock_callback, libcrypto_mutexes, ssh_threads_callbacks_struct::mutex_destroy, ssh_threads_callbacks_struct::mutex_init, ssh_threads_callbacks_struct::mutex_lock, ssh_threads_callbacks_struct::mutex_unlock, SSH_ERROR, SSH_OK, ssh_threads_callbacks_struct::thread_id, ssh_threads_callbacks_struct::type, user_callbacks.
Referenced by ssh_threads_init, ssh_threads_set_callbacks.
void crypto_thread_finalize(void)
References libcrypto_mutexes, ssh_threads_callbacks_struct::mutex_destroy, SAFE_FREE, user_callbacks.
Referenced by crypto_thread_init, ssh_threads_finalize, ssh_threads_set_callbacks.