messages.h
SSH_PACKET_CALLBACK(ssh_packet_channel_open)
References ssh_message_struct::channel_request_open, ssh_channel_request_open::destination, ssh_channel_request_open::destination_port, error, ssh_channel_request_open::originator, ssh_channel_request_open::originator_port, ssh_channel_request_open::packet_size, rc, SAFE_FREE, ssh_channel_request_open::sender, session, ssh_session_struct::session_state, ssh_buffer_unpack, SSH_CHANNEL_AUTH_AGENT, SSH_CHANNEL_DIRECT_TCPIP, SSH_CHANNEL_FORWARDED_TCPIP, SSH_CHANNEL_SESSION, SSH_CHANNEL_UNKNOWN, SSH_CHANNEL_X11, SSH_FATAL, SSH_LOG, SSH_LOG_PACKET, SSH_MESSAGE_FREE, ssh_message_new, ssh_message_queue, SSH_OK, SSH_PACKET_USED, SSH_REQUEST_CHANNEL_OPEN, SSH_SESSION_STATE_AUTHENTICATED, ssh_set_error, ssh_set_error_oom, ssh_channel_request_open::type, ssh_message_struct::type, user, ssh_channel_request_open::window.
SSH_PACKET_CALLBACK(ssh_packet_global_request)
int ssh_message_handle_channel_request(ssh_session session, ssh_channel channel, ssh_buffer packet, const char *request, uint8_t want_reply)
References ssh_channel_request::channel, ssh_message_struct::channel_request, ssh_channel_request::command, error, ssh_channel_request::height, ssh_channel_struct::local_channel, ssh_channel_request::modes, ssh_channel_request::pxheight, ssh_channel_request::pxwidth, rc, ssh_channel_struct::remote_channel, session, ssh_buffer_unpack, SSH_CHANNEL_REQUEST_ENV, SSH_CHANNEL_REQUEST_EXEC, SSH_CHANNEL_REQUEST_PTY, SSH_CHANNEL_REQUEST_SHELL, SSH_CHANNEL_REQUEST_SUBSYSTEM, SSH_CHANNEL_REQUEST_UNKNOWN, SSH_CHANNEL_REQUEST_WINDOW_CHANGE, SSH_CHANNEL_REQUEST_X11, SSH_ERROR, SSH_LOG, SSH_LOG_PACKET, SSH_MESSAGE_FREE, ssh_message_new, ssh_message_queue, SSH_OK, SSH_REQUEST_CHANNEL, ssh_set_error_oom, ssh_channel_request::subsystem, ssh_channel_request::TERM, ssh_channel_request::type, ssh_message_struct::type, ssh_channel_request::var_name, ssh_channel_request::var_value, ssh_channel_request::want_reply, ssh_channel_request::width, ssh_channel_request::x11_auth_cookie, ssh_channel_request::x11_auth_protocol, ssh_channel_request::x11_screen_number, ssh_channel_request::x11_single_connection.
Referenced by SSH_PACKET_CALLBACK.
ssh_message ssh_message_pop_head(ssh_session session)
References session, ssh_iterator_value, ssh_list_get_iterator, ssh_list_remove, ssh_session_struct::ssh_message_list.
Referenced by ssh_execute_message_callbacks, ssh_message_get.