options.c
int ssh_options_copy(ssh_session src, ssh_session *dest)
Duplicate the options of a session structure.
If you make several sessions with the same options this is useful. You cannot use twice the same option structure in ssh_session_connect. src The session to use to copy the options. dest A pointer to store the allocated session with duplicated options. You have to free the memory. 0 on sucess, -1 on error with errno set. ssh_session_connect()
References ssh_session_struct::bindaddr, ssh_common_struct::callbacks, ssh_session_struct::common, ssh_session_struct::compressionlevel, ssh_session_struct::config_processed, ssh_iterator::data, ssh_session_struct::fd, ssh_session_struct::flags, ssh_session_struct::global_knownhosts, ssh_session_struct::gss_client_identity, ssh_session_struct::gss_delegate_creds, ssh_session_struct::gss_server_identity, ssh_session_struct::host, ssh_session_struct::identity, ssh_session_struct::knownhosts, ssh_common_struct::log_verbosity, ssh_iterator::next, ssh_session_struct::nodelay, ssh_session_struct::options_seen, ssh_session_struct::opts, ssh_session_struct::port, ssh_session_struct::ProxyCommand, ssh_session_struct::pubkey_accepted_types, rc, SAFE_FREE, ssh_free, SSH_KEX_METHODS, ssh_list_append, ssh_list_get_iterator, ssh_list_pop_head, ssh_new, ssh_session_struct::sshdir, ssh_session_struct::StrictHostKeyChecking, ssh_session_struct::timeout, ssh_session_struct::timeout_usec, ssh_session_struct::username, ssh_session_struct::wanted_methods.
Referenced by ssh::Session::optionsCopy, torture_options_copy.
int ssh_options_set_algo(ssh_session session, enum ssh_kex_types_e algo, const char *list)
References ssh_session_struct::opts, SAFE_FREE, session, ssh_keep_fips_algos, ssh_keep_known_algos, ssh_kex_get_description, SSH_REQUEST_DENIED, ssh_set_error, ssh_session_struct::wanted_methods.
Referenced by server_set_kex, ssh_options_set.
int ssh_options_set(ssh_session session, enum ssh_options_e type, const void *value)
This function can set all possible ssh options.
session An allocated SSH session structure. type The option type to set. This could be one of the following: SSH_OPTIONS_HOST: The hostname or ip address to connect to (const char *). SSH_OPTIONS_PORT: The port to connect to (unsigned int *). SSH_OPTIONS_PORT_STR: The port to connect to (const char *). SSH_OPTIONS_FD: The file descriptor to use (socket_t). If you wish to open the socket yourself for a reason or another, set the file descriptor. Don't forget to set the hostname as the hostname is used as a key in the known_host mechanism. SSH_OPTIONS_BINDADDR: The address to bind the client to (const char *). SSH_OPTIONS_USER: The username for authentication (const char *). If the value is NULL, the username is set to the default username. SSH_OPTIONS_SSH_DIR: Set the ssh directory (const char *,format string). If the value is NULL, the directory is set to the default ssh directory. The ssh directory is used for files like known_hosts and identity (private and public key). It may include "%s" which will be replaced by the user home directory. SSH_OPTIONS_KNOWNHOSTS: Set the known hosts file name (const char *,format string). If the value is NULL, the directory is set to the default known hosts file, normally ~/.ssh/known_hosts. The known hosts file is used to certify remote hosts are genuine. It may include "%d" which will be replaced by the user home directory. SSH_OPTIONS_GLOBAL_KNOWNHOSTS: Set the global known hosts file name (const char *,format string). If the value is NULL, the directory is set to the default global known hosts file, normally /etc/ssh/ssh_known_hosts. The known hosts file is used to certify remote hosts are genuine. SSH_OPTIONS_ADD_IDENTITY (or SSH_OPTIONS_IDENTITY): Add a new identity file (const char *, format string) to the identity list. By default identity, id_dsa and id_rsa are checked. The identity used to authenticate with public key will be prepended to the list. It may include "%s" which will be replaced by the user home directory. SSH_OPTIONS_TIMEOUT: Set a timeout for the connection in seconds (long). SSH_OPTIONS_TIMEOUT_USEC: Set a timeout for the connection in micro seconds (long). SSH_OPTIONS_SSH1: Deprecated SSH_OPTIONS_SSH2: Unused SSH_OPTIONS_LOG_VERBOSITY: Set the session logging verbosity (int). The verbosity of the messages. Every log smaller or equal to verbosity will be shown. SSH_LOG_NOLOG: No logging SSH_LOG_WARNING: Only warnings SSH_LOG_PROTOCOL: High level protocol information SSH_LOG_PACKET: Lower level protocol infomations, packet level SSH_LOG_FUNCTIONS: Every function path SSH_OPTIONS_LOG_VERBOSITY_STR: Set the session logging verbosity via a string that will be converted to a numerical value (e.g. "3") and interpreted according to the values of SSH_OPTIONS_LOG_VERBOSITY above (const char *). SSH_OPTIONS_CIPHERS_C_S: Set the symmetric cipher client to server (const char *, comma-separated list). SSH_OPTIONS_CIPHERS_S_C: Set the symmetric cipher server to client (const char *, comma-separated list). SSH_OPTIONS_KEY_EXCHANGE: Set the key exchange method to be used (const char *, comma-separated list). ex: "ecdh-sha2-nistp256,diffie-hellman-group14-sha1,diffie-hellman-group1-sha1" SSH_OPTIONS_HMAC_C_S: Set the Message Authentication Code algorithm client to server (const char *, comma-separated list). SSH_OPTIONS_HMAC_S_C: Set the Message Authentication Code algorithm server to client (const char *, comma-separated list). SSH_OPTIONS_HOSTKEYS: Set the preferred server host key types (const char *, comma-separated list). ex: "ssh-rsa,ssh-dss,ecdh-sha2-nistp256" SSH_OPTIONS_PUBLICKEY_ACCEPTED_TYPES: Set the preferred public key algorithms to be used for authentication (const char *, comma-separated list). ex: "ssh-rsa,rsa-sha2-256,ssh-dss,ecdh-sha2-nistp256" SSH_OPTIONS_COMPRESSION_C_S: Set the compression to use for client to server communication (const char *, "yes", "no" or a specific algorithm name if needed ("zlib","zlib@openssh.com","none"). SSH_OPTIONS_COMPRESSION_S_C: Set the compression to use for server to client communication (const char *, "yes", "no" or a specific algorithm name if needed ("zlib","zlib@openssh.com","none"). SSH_OPTIONS_COMPRESSION: Set the compression to use for both directions communication (const char *, "yes", "no" or a specific algorithm name if needed ("zlib","zlib@openssh.com","none"). SSH_OPTIONS_COMPRESSION_LEVEL: Set the compression level to use for zlib functions. (int, value from 1 to 9, 9 being the most efficient but slower). SSH_OPTIONS_STRICTHOSTKEYCHECK: Set the parameter StrictHostKeyChecking to avoid asking about a fingerprint (int, 0 = false). SSH_OPTIONS_PROXYCOMMAND: Set the command to be executed in order to connect to server (const char *). SSH_OPTIONS_GSSAPI_SERVER_IDENTITY Set it to specify the GSSAPI server identity that libssh should expect when connecting to the server (const char *). SSH_OPTIONS_GSSAPI_CLIENT_IDENTITY Set it to specify the GSSAPI client identity that libssh should expect when connecting to the server (const char *). SSH_OPTIONS_GSSAPI_DELEGATE_CREDENTIALS Set it to specify that GSSAPI should delegate credentials to the server (int, 0 = false). SSH_OPTIONS_PASSWORD_AUTH Set it if password authentication should be used in ssh_userauth_auto_pubkey(). (int, 0=false). Currently without effect (ssh_userauth_auto_pubkey doesn't use password authentication). SSH_OPTIONS_PUBKEY_AUTH Set it if pubkey authentication should be used in ssh_userauth_auto_pubkey(). (int, 0=false). SSH_OPTIONS_KBDINT_AUTH Set it if keyboard-interactive authentication should be used in ssh_userauth_auto_pubkey(). (int, 0=false). Currently without effect (ssh_userauth_auto_pubkey doesn't use keyboard-interactive authentication). SSH_OPTIONS_GSSAPI_AUTH Set it if gssapi authentication should be used in ssh_userauth_auto_pubkey(). (int, 0=false). Currently without effect (ssh_userauth_auto_pubkey doesn't use gssapi authentication). SSH_OPTIONS_NODELAY Set it to disable Nagle's Algorithm (TCP_NODELAY) on the session socket. (int, 0=false) SSH_OPTIONS_PROCESS_CONFIG Set it to false to disable automatic processing of per-user and system-wide OpenSSH configuration files. LibSSH automatically uses these configuration files unless you provide it with this option or with different file (bool). SSH_OPTIONS_REKEY_DATA Set the data limit that can be transferred with a single key in bytes. RFC 4253 Section 9 recommends 1GB of data, while RFC 4344 provides more specific restrictions, that are applied automatically. When specified, the lower value will be used. (uint64_t, 0=default) SSH_OPTIONS_REKEY_TIME Set the time limit for a session before intializing a rekey in seconds. RFC 4253 Section 9 recommends one hour. (uint32_t, 0=off) value The value to set. This is a generic pointer and the datatype which is used should be set according to the type set. 0 on success, < 0 on error.
References ssh_session_struct::bindaddr, ssh_session_struct::common, ssh_session_struct::compressionlevel, ssh_session_struct::config_processed, ssh_session_struct::fd, ssh_session_struct::flags, ssh_session_struct::global_knownhosts, ssh_session_struct::gss_client_identity, ssh_session_struct::gss_delegate_creds, ssh_session_struct::gss_server_identity, ssh_session_struct::host, ssh_session_struct::identity, ssh_session_struct::knownhosts, ssh_common_struct::log_verbosity, ssh_session_struct::nodelay, ssh_session_struct::opts, ssh_session_struct::port, ssh_session_struct::ProxyCommand, ssh_session_struct::pubkey_accepted_types, rc, ssh_session_struct::rekey_data, ssh_session_struct::rekey_time, SAFE_FREE, session, SSH_COMP_C_S, SSH_COMP_S_C, SSH_CRYPT_C_S, SSH_CRYPT_S_C, ssh_get_local_username, SSH_HOSTKEYS, SSH_INVALID_SOCKET, ssh_keep_fips_algos, ssh_keep_known_algos, SSH_KEX, ssh_list_prepend, SSH_MAC_C_S, SSH_MAC_S_C, SSH_OPT_FLAG_GSSAPI_AUTH, SSH_OPT_FLAG_KBDINT_AUTH, SSH_OPT_FLAG_PASSWORD_AUTH, SSH_OPT_FLAG_PUBKEY_AUTH, SSH_OPTIONS_ADD_IDENTITY, SSH_OPTIONS_BINDADDR, SSH_OPTIONS_CIPHERS_C_S, SSH_OPTIONS_CIPHERS_S_C, SSH_OPTIONS_COMPRESSION, SSH_OPTIONS_COMPRESSION_C_S, SSH_OPTIONS_COMPRESSION_LEVEL, SSH_OPTIONS_COMPRESSION_S_C, SSH_OPTIONS_FD, SSH_OPTIONS_GLOBAL_KNOWNHOSTS, SSH_OPTIONS_GSSAPI_AUTH, SSH_OPTIONS_GSSAPI_CLIENT_IDENTITY, SSH_OPTIONS_GSSAPI_DELEGATE_CREDENTIALS, SSH_OPTIONS_GSSAPI_SERVER_IDENTITY, SSH_OPTIONS_HMAC_C_S, SSH_OPTIONS_HMAC_S_C, SSH_OPTIONS_HOST, SSH_OPTIONS_HOSTKEYS, SSH_OPTIONS_IDENTITY, SSH_OPTIONS_KBDINT_AUTH, SSH_OPTIONS_KEY_EXCHANGE, SSH_OPTIONS_KNOWNHOSTS, SSH_OPTIONS_LOG_VERBOSITY, SSH_OPTIONS_LOG_VERBOSITY_STR, SSH_OPTIONS_NODELAY, SSH_OPTIONS_PASSWORD_AUTH, SSH_OPTIONS_PORT, SSH_OPTIONS_PORT_STR, SSH_OPTIONS_PROCESS_CONFIG, SSH_OPTIONS_PROXYCOMMAND, SSH_OPTIONS_PUBKEY_AUTH, SSH_OPTIONS_PUBLICKEY_ACCEPTED_TYPES, SSH_OPTIONS_REKEY_DATA, SSH_OPTIONS_REKEY_TIME, ssh_options_set, ssh_options_set_algo, SSH_OPTIONS_SSH1, SSH_OPTIONS_SSH2, SSH_OPTIONS_SSH_DIR, SSH_OPTIONS_STRICTHOSTKEYCHECK, SSH_OPTIONS_TIMEOUT, SSH_OPTIONS_TIMEOUT_USEC, SSH_OPTIONS_USER, ssh_path_expand_tilde, SSH_REQUEST_DENIED, ssh_set_error, ssh_set_error_invalid, ssh_set_error_oom, ssh_set_log_level, ssh_session_struct::sshdir, ssh_session_struct::StrictHostKeyChecking, ssh_session_struct::timeout, ssh_session_struct::timeout_usec, ssh_session_struct::username.
Referenced by authenticate, client, connect_host, connect_ssh, LLVMFuzzerTestOneInput, main, pkd_exec_hello, session_setup, ssh::Session::setOption, setup, setup_config_files, ssh_client, ssh_config_parse_line, ssh_config_parse_proxy_jump, ssh_options_apply, ssh_options_getopt, ssh_options_parse_config, ssh_options_set, test_algorithm, torture_algorithms_zlib, torture_algorithms_zlib_openssh, torture_auth_agent, torture_auth_agent_cert, torture_auth_agent_cert_nonblocking, torture_auth_agent_nonblocking, torture_auth_autopubkey, torture_auth_autopubkey_nonblocking, torture_auth_cert, torture_auth_kbdint, torture_auth_kbdint_nonblocking, torture_auth_none, torture_auth_none_nonblocking, torture_auth_password, torture_auth_password_nonblocking, torture_auth_pubkey_types, torture_auth_pubkey_types_ecdsa, torture_auth_pubkey_types_ecdsa_nonblocking, torture_auth_pubkey_types_ed25519, torture_auth_pubkey_types_ed25519_nonblocking, torture_auth_pubkey_types_nonblocking, torture_client_config_suppress, torture_config_auth_methods, torture_config_match, torture_config_proxyjump, torture_config_rekey, torture_connect_double, torture_connect_nonblocking, torture_connect_socket, torture_hostkey_ed25519, torture_hostkey_rsa, torture_hostkey_rsa_sha256, torture_hostkey_rsa_sha512, torture_knownhosts_algorithms, torture_knownhosts_algorithms_global, torture_knownhosts_algorithms_negative, torture_knownhosts_algorithms_wanted, torture_knownhosts_conflict, torture_knownhosts_duplicate, torture_knownhosts_fail, torture_knownhosts_get_algorithms_names, torture_knownhosts_host_exists, torture_knownhosts_host_exists_global, torture_knownhosts_new_file, torture_knownhosts_no_hostkeychecking, torture_knownhosts_other, torture_knownhosts_other_auto, torture_knownhosts_port, torture_knownhosts_precheck, torture_knownhosts_standard_port, torture_knownhosts_unknown, torture_knownhosts_wildcard, torture_options_config_host, torture_options_config_match, torture_options_config_match_multi, torture_options_copy, torture_options_get_global_knownhosts, torture_options_get_host, torture_options_get_identity, torture_options_get_knownhosts, torture_options_get_port, torture_options_get_user, torture_options_proxycommand, torture_options_set_ciphers, torture_options_set_fd, torture_options_set_global_knownhosts, torture_options_set_host, torture_options_set_hostkey, torture_options_set_identity, torture_options_set_key_exchange, torture_options_set_knownhosts, torture_options_set_macs, torture_options_set_port, torture_options_set_proxycommand_notexist, torture_options_set_proxycommand_ssh, torture_options_set_proxycommand_ssh_stderr, torture_options_set_pubkey_accepted_types, torture_options_set_user, torture_packet, torture_pki_verify_mismatch, torture_rekey_default, torture_rekey_send, torture_rekey_time, torture_run_tests, torture_server_auth_kbdint, torture_server_auth_none, torture_server_auth_password, torture_server_auth_pubkey, torture_server_hostkey_mismatch, torture_server_unknown_global_request, torture_ssh_forward, torture_ssh_session, try_config_content.
int ssh_options_get_port(ssh_session session, unsigned int *port_target)
This function can get ssh the ssh port. It must only be used on a valid ssh session. This function is useful when the session options have been automatically inferred from the environment or configuration files and one.
session An allocated SSH session structure. port_target An unsigned integer into which the port will be set from the ssh session. 0 on success, < 0 on error.
References ssh_session_struct::opts, ssh_session_struct::port, session.
Referenced by torture_options_get_port.
int ssh_options_get(ssh_session session, enum ssh_options_e type, char **value)
This function can get ssh options, it does not support all options provided for ssh options set, but mostly those which a user-space program may care about having trusted the ssh driver to infer these values from underlaying configuration files. It operates only on those SSH_OPTIONS_* which return char*. If you wish to receive the port then please use ssh_options_get_port() which returns an unsigned int.
session An allocated SSH session structure. type The option type to get. This could be one of the following: SSH_OPTIONS_HOST: The hostname or ip address to connect to (const char *). SSH_OPTIONS_USER: The username for authentication (const char *). when not explicitly set this will be inferred from the ~/.ssh/config file. SSH_OPTIONS_IDENTITY: Get the first identity file name (const char *). By default identity, id_dsa and id_rsa are checked. SSH_OPTIONS_PROXYCOMMAND: Get the proxycommand necessary to log into the remote host. When not explicitly set, it will be read from the ~/.ssh/config file. SSH_OPTIONS_GLOBAL_KNOWNHOSTS: Get the path to the global known_hosts file being used. SSH_OPTIONS_KNOWNHOSTS: Get the path to the known_hosts file being used. value The value to get into. As a char**, space will be allocated by the function for the value, it is your responsibility to free the memory using ssh_string_free_char(). SSH_OK on success, SSH_ERROR on error.
References ssh_session_struct::global_knownhosts, ssh_session_struct::host, ssh_session_struct::identity, ssh_session_struct::knownhosts, ssh_session_struct::opts, ssh_session_struct::ProxyCommand, session, SSH_ERROR, ssh_iterator_value, ssh_list_get_iterator, SSH_OK, SSH_OPTIONS_GLOBAL_KNOWNHOSTS, SSH_OPTIONS_HOST, SSH_OPTIONS_IDENTITY, SSH_OPTIONS_KNOWNHOSTS, SSH_OPTIONS_PROXYCOMMAND, SSH_OPTIONS_USER, SSH_REQUEST_DENIED, ssh_set_error, ssh_set_error_invalid, ssh_set_error_oom, ssh_session_struct::username.
Referenced by torture_config_from_file, torture_config_glob, torture_options_get_global_knownhosts, torture_options_get_host, torture_options_get_identity, torture_options_get_knownhosts, torture_options_get_user.
int ssh_options_getopt(ssh_session session, int *argcptr, char **argv)
Parse command line arguments.
This is a helper for your application to generate the appropriate options from the command line arguments. The argv array and argc value are changed so that the parsed arguments wont appear anymore in them. The single arguments (without switches) are not parsed. thus, myssh -l user localhost The command wont set the hostname value of options to localhost. session The session to configure. argcptr The pointer to the argument count. argv The arguments list pointer. 0 on success, < 0 on error. ssh_session_new()
References port, SAFE_FREE, session, SSH_ERROR, SSH_FATAL, SSH_OK, SSH_OPTIONS_CIPHERS_C_S, SSH_OPTIONS_CIPHERS_S_C, SSH_OPTIONS_COMPRESSION, SSH_OPTIONS_IDENTITY, SSH_OPTIONS_PORT_STR, ssh_options_set, SSH_OPTIONS_USER, ssh_set_error, ssh_set_error_oom, ssh_set_log_level, user.
Referenced by main, set_opts.
int ssh_options_parse_config(ssh_session session, const char *filename)
Parse the ssh config file.
This should be the last call of all options, it may overwrite options which are already set. It requires that the host name is already set with ssh_options_set_host(). session SSH session handle filename The options file to use, if NULL the default ~/.ssh/config will be used. 0 on success, < 0 on error. ssh_options_set_host()
References ssh_session_struct::config_processed, ssh_session_struct::host, ssh_session_struct::opts, session, ssh_config_parse_file, ssh_options_set, SSH_OPTIONS_SSH_DIR, ssh_path_expand_escape, ssh_set_error_invalid, ssh_set_error_oom, ssh_session_struct::sshdir.
Referenced by client, connect_host, ssh::Session::optionsParseConfig, ssh_connect, torture_client_config_emulate, torture_client_config_system, torture_options_config_host, torture_options_config_match, torture_options_config_match_multi, torture_options_copy.
int ssh_options_apply(ssh_session session)
References ssh_iterator::data, ssh_session_struct::global_knownhosts, ssh_session_struct::identity, if, ssh_session_struct::knownhosts, ssh_iterator::next, ssh_session_struct::opts, ssh_session_struct::ProxyCommand, rc, session, ssh_list_get_iterator, ssh_options_set, SSH_OPTIONS_SSH_DIR, SSH_OPTIONS_USER, ssh_path_expand_escape, ssh_session_struct::sshdir, ssh_session_struct::username.
Referenced by ssh_connect, ssh_is_server_known, ssh_known_hosts_check_server_key, ssh_known_hosts_get_algorithms, ssh_known_hosts_get_algorithms_names, ssh_try_publickey_from_file, ssh_write_knownhost, torture_options_set_knownhosts.