packet.c
MAX_PACKETS
ssh_packet_callback default_packet_handlers[][]
Referenced by ssh_packet_set_default_callbacks.
static enum ssh_packet_filter_result_e ssh_packet_incoming_filter(ssh_session session)
Referenced by check_message_in_all_states, ssh_packet_socket_callback, torture_packet_filter_check_unfiltered.
struct ssh_crypto_struct* ssh_packet_get_current_crypto(ssh_session session, enum ssh_crypto_direction_e direction)
References ssh_session_struct::current_crypto, ssh_crypto_struct::in_cipher, ssh_session_struct::next_crypto, ssh_crypto_struct::out_cipher, session, SSH_DIRECTION_BOTH, SSH_DIRECTION_IN, SSH_DIRECTION_OUT, ssh_crypto_struct::used.
Referenced by gzip_compress, gzip_decompress, packet_send2, ssh_auth_reply_success, ssh_gssapi_build_mic, SSH_PACKET_CALLBACK, ssh_packet_decrypt, ssh_packet_decrypt_len, ssh_packet_encrypt, ssh_packet_hmac_verify, ssh_packet_need_rekey, ssh_packet_socket_callback, ssh_pki_do_sign, ssh_pki_do_sign_agent.
static bool ssh_packet_need_rekey(ssh_session session, const uint32_t payloadsize)
References ssh_cipher_struct::blocks, ssh_cipher_struct::blocksize, ssh_session_struct::dh_handshake_state, DH_STATE_FINISHED, ssh_session_struct::flags, ssh_crypto_struct::in_cipher, ssh_session_struct::last_rekey_time, ssh_cipher_struct::max_blocks, MAX_PACKETS, ssh_session_struct::opts, ssh_crypto_struct::out_cipher, ssh_cipher_struct::packets, ssh_session_struct::rekey_time, session, SSH_DIRECTION_BOTH, SSH_LOG, SSH_LOG_PACKET, ssh_packet_get_current_crypto, SSH_SESSION_FLAG_AUTHENTICATED, ssh_timeout_elapsed.
Referenced by ssh_packet_send, ssh_packet_socket_callback.
int ssh_packet_socket_callback(const void *data, size_t receivedlen, void *user)
References ssh_cipher_struct::blocks, ssh_cipher_struct::blocksize, decompress_buffer, ssh_crypto_struct::do_compress_in, error, FALL_THROUGH, hmac_digest_len, ssh_session_struct::in_buffer, ssh_counter_struct::in_bytes, ssh_crypto_struct::in_cipher, ssh_crypto_struct::in_hmac_etm, ssh_session_struct::in_packet, ssh_counter_struct::in_packets, packet_struct::len, ssh_cipher_struct::lenfield_blocksize, mac, MAX_PACKET_LEN, ssh_session_struct::packet_state, PACKET_STATE_INIT, PACKET_STATE_PROCESSING, PACKET_STATE_SIZEREAD, ssh_cipher_struct::packets, PRIdS, PULL_BE_U32, ssh_session_struct::raw_counter, rc, ssh_session_struct::recv_seq, session, ssh_session_struct::session_state, ssh_buffer_allocate, ssh_buffer_get, ssh_buffer_get_len, ssh_buffer_get_u8, ssh_buffer_new, ssh_buffer_pass_bytes, ssh_buffer_pass_bytes_end, ssh_buffer_reinit, SSH_DIRECTION_IN, SSH_FATAL, SSH_LOG, SSH_LOG_PACKET, SSH_OK, SSH_PACKET_ALLOWED, ssh_packet_decrypt, ssh_packet_decrypt_len, SSH_PACKET_DENIED, ssh_packet_get_current_crypto, ssh_packet_hmac_verify, ssh_packet_incoming_filter, ssh_packet_need_rekey, ssh_packet_parse_type, ssh_packet_process, ssh_packet_send_unimplemented, ssh_packet_socket_callback, SSH_PACKET_UNKNOWN, ssh_send_rekex, SSH_SESSION_STATE_ERROR, ssh_set_error, packet_struct::type, user.
Referenced by ssh_packet_register_socket_callback, ssh_packet_socket_callback, ssh_server_connection_callback, torture_packet.
static void ssh_packet_socket_controlflow_callback(int code, void *userdata)
References ssh_channel_struct::callbacks, ssh_session_struct::channels, ssh_iterator::next, ssh_channel_struct::remote_window, session, ssh_callbacks_execute_list, ssh_iterator_value, ssh_list_get_iterator, SSH_LOG, SSH_LOG_TRACE, SSH_SOCKET_FLOW_WRITEWONTBLOCK.
Referenced by ssh_packet_register_socket_callback.
void ssh_packet_register_socket_callback(ssh_session session, ssh_socket s)
References ssh_socket_callbacks_struct::connected, ssh_socket_callbacks_struct::controlflow, ssh_socket_callbacks_struct::data, s, session, ssh_session_struct::socket_callbacks, ssh_packet_socket_callback, ssh_packet_socket_controlflow_callback, ssh_socket_set_callbacks, ssh_socket_callbacks_struct::userdata.
void ssh_packet_set_callbacks(ssh_session session, ssh_packet_callbacks callbacks)
References callbacks, ssh_session_struct::packet_callbacks, session, ssh_list_append, ssh_list_new.
Referenced by ssh_client_dh_init, ssh_client_dhgex_init, ssh_packet_set_default_callbacks, torture_packet.
void ssh_packet_remove_callbacks(ssh_session session, ssh_packet_callbacks callbacks)
References callbacks, ssh_session_struct::packet_callbacks, session, ssh_list_find, ssh_list_remove.
Referenced by SSH_PACKET_CALLBACK.
void ssh_packet_set_default_callbacks(ssh_session session)
References ssh_packet_callbacks_struct::callbacks, ssh_session_struct::default_packet_callbacks, default_packet_handlers, ssh_packet_callbacks_struct::n_callbacks, session, ssh_packet_set_callbacks, ssh_packet_callbacks_struct::start, ssh_packet_callbacks_struct::user.
Referenced by ssh_client_connection_callback, ssh_server_connection_callback.
void ssh_packet_process(ssh_session session, uint8_t type)
References cb, ssh_session_struct::in_buffer, ssh_iterator::next, ssh_session_struct::packet_callbacks, rc, ssh_session_struct::recv_seq, session, ssh_get_error, ssh_iterator_value, ssh_list_get_iterator, SSH_LOG, SSH_LOG_PACKET, SSH_LOG_RARE, SSH_OK, SSH_PACKET_NOT_USED, ssh_packet_send_unimplemented, SSH_PACKET_USED.
Referenced by ssh_packet_socket_callback.
int ssh_packet_send_unimplemented(ssh_session session, uint32_t seqnum)
References ssh_session_struct::out_buffer, rc, session, SSH2_MSG_UNIMPLEMENTED, ssh_buffer_pack, SSH_ERROR, SSH_OK, ssh_packet_send, ssh_set_error_oom.
Referenced by ssh_packet_process, ssh_packet_socket_callback.
SSH_PACKET_CALLBACK(ssh_packet_unimplemented)
References rc, session, ssh_buffer_unpack, SSH_LOG, SSH_LOG_RARE, SSH_LOG_WARNING, SSH_OK, SSH_PACKET_USED, user.
int ssh_packet_parse_type(struct ssh_session_struct *session)
References ssh_session_struct::in_buffer, ssh_session_struct::in_packet, session, ssh_buffer_get_u8, SSH_ERROR, SSH_FATAL, SSH_OK, ssh_set_error, packet_struct::type, packet_struct::valid.
Referenced by ssh_packet_socket_callback.
static int ssh_packet_write(ssh_session session)
References ssh_session_struct::out_buffer, rc, session, ssh_session_struct::socket, ssh_buffer_get, ssh_buffer_get_len, SSH_ERROR, ssh_socket_write.
Referenced by packet_send2.
static int packet_send2(ssh_session session)
References ssh_cipher_struct::blocks, ssh_cipher_struct::blocksize, compress_buffer, ssh_crypto_struct::do_compress_out, error, hmac_digest_len, ssh_cipher_struct::lenfield_blocksize, ssh_session_struct::next_crypto, ssh_session_struct::out_buffer, ssh_counter_struct::out_bytes, ssh_crypto_struct::out_cipher, ssh_crypto_struct::out_hmac, ssh_crypto_struct::out_hmac_etm, ssh_counter_struct::out_packets, ssh_cipher_struct::packets, PUSH_BE_U32, PUSH_BE_U8, ssh_session_struct::raw_counter, rc, ssh_session_struct::send_seq, session, SSH2_MSG_NEWKEYS, ssh_buffer_add_data, ssh_buffer_get, ssh_buffer_get_len, ssh_buffer_prepend_data, ssh_buffer_reinit, SSH_DIRECTION_OUT, SSH_ERROR, SSH_FATAL, ssh_get_random, SSH_LOG, SSH_LOG_PACKET, ssh_packet_encrypt, ssh_packet_get_current_crypto, ssh_packet_set_newkeys, ssh_packet_write, ssh_set_error.
Referenced by ssh_packet_send.
static bool ssh_packet_is_kex(unsigned char type)
References SSH2_MSG_DISCONNECT, SSH2_MSG_EXT_INFO, SSH2_MSG_IGNORE, SSH2_MSG_KEX_DH_GEX_REQUEST, SSH2_MSG_SERVICE_ACCEPT, SSH2_MSG_SERVICE_REQUEST.
Referenced by ssh_packet_send.
static bool ssh_packet_in_rekey(ssh_session session)
References ssh_session_struct::dh_handshake_state, DH_STATE_FINISHED, ssh_session_struct::flags, session, SSH_SESSION_FLAG_AUTHENTICATED.
Referenced by ssh_packet_send.
int ssh_packet_send(ssh_session session)
References ssh_iterator::data, ssh_session_struct::out_buffer, ssh_session_struct::out_queue, packet_send2, rc, session, SSH2_MSG_NEWKEYS, SSH_BUFFER_FREE, ssh_buffer_get, ssh_buffer_get_len, ssh_buffer_new, SSH_ERROR, ssh_list_append, ssh_list_get_iterator, ssh_list_pop_head, SSH_LOG, SSH_LOG_PACKET, SSH_OK, ssh_packet_in_rekey, ssh_packet_is_kex, ssh_packet_need_rekey, ssh_send_rekex, ssh_set_error_oom.
Referenced by channel_open, channel_request, channel_write_common, grow_window, ssh_auth_reply_default, ssh_auth_reply_success, ssh_channel_close, ssh_channel_send_eof, ssh_client_dh_init, ssh_client_dhgex_init, ssh_disconnect, ssh_global_request, ssh_gssapi_send_auth_mic, ssh_gssapi_send_mic, ssh_message_auth_interactive_request, ssh_message_auth_reply_pk_ok, ssh_message_channel_request_open_reply_accept_channel, ssh_message_channel_request_open_reply_default, ssh_message_channel_request_reply_default, ssh_message_channel_request_reply_success, ssh_message_global_request_reply_default, ssh_message_global_request_reply_success, ssh_message_reply_default, ssh_message_service_reply_success, SSH_PACKET_CALLBACK, ssh_packet_send_unimplemented, ssh_send_debug, ssh_send_ignore, ssh_send_kex, ssh_server_send_extensions, ssh_service_request, ssh_userauth_agent_publickey, ssh_userauth_kbdint_init, ssh_userauth_kbdint_send, ssh_userauth_none, ssh_userauth_password, ssh_userauth_publickey, ssh_userauth_try_publickey, torture_packet.
static void ssh_init_rekey_state(struct ssh_session_struct *session, struct ssh_cipher_struct *cipher)
References ssh_cipher_struct::blocks, ssh_cipher_struct::blocksize, ssh_cipher_struct::max_blocks, MIN, ssh_session_struct::opts, ssh_cipher_struct::packets, ssh_session_struct::rekey_data, session, SSH_LOG, SSH_LOG_PROTOCOL.
Referenced by ssh_packet_set_newkeys.
int ssh_packet_set_newkeys(ssh_session session, enum ssh_crypto_direction_e direction)
References ssh_session_struct::client, crypt_set_algorithms_client, crypto_free, crypto_new, ssh_session_struct::current_crypto, ssh_crypto_struct::decryptIV, ssh_crypto_struct::decryptkey, ssh_crypto_struct::digest_len, ssh_crypto_struct::encryptIV, ssh_crypto_struct::encryptkey, ssh_crypto_struct::in_cipher, ssh_session_struct::last_rekey_time, ssh_session_struct::next_crypto, ssh_session_struct::opts, ssh_crypto_struct::out_cipher, rc, ssh_session_struct::rekey_time, session, ssh_crypto_struct::session_id, ssh_cipher_struct::set_decrypt_key, ssh_cipher_struct::set_encrypt_key, SSH_DIRECTION_BOTH, SSH_DIRECTION_IN, SSH_DIRECTION_OUT, SSH_ERROR, ssh_generate_session_keys, ssh_init_rekey_state, SSH_LOG, SSH_LOG_PROTOCOL, SSH_LOG_TRACE, SSH_LOG_WARNING, ssh_make_sessionid, SSH_OK, ssh_set_error_oom, ssh_timestamp_init, ssh_crypto_struct::used.
Referenced by packet_send2, SSH_PACKET_CALLBACK, ssh_server_connection_callback.