packet.h
ssh_packet_state_e
Packet not initialized, must read the size of packet
ssh_packet_filter_result_e
typedef struct packet_struct PACKET
int ssh_packet_send(ssh_session session)
References ssh_iterator::data, ssh_session_struct::out_buffer, ssh_session_struct::out_queue, packet_send2, rc, session, SSH2_MSG_NEWKEYS, SSH_BUFFER_FREE, ssh_buffer_get, ssh_buffer_get_len, ssh_buffer_new, SSH_ERROR, ssh_list_append, ssh_list_get_iterator, ssh_list_pop_head, SSH_LOG, SSH_LOG_PACKET, SSH_OK, ssh_packet_in_rekey, ssh_packet_is_kex, ssh_packet_need_rekey, ssh_send_rekex, ssh_set_error_oom.
Referenced by channel_open, channel_request, channel_write_common, grow_window, ssh_auth_reply_default, ssh_auth_reply_success, ssh_channel_close, ssh_channel_send_eof, ssh_client_dh_init, ssh_client_dhgex_init, ssh_disconnect, ssh_global_request, ssh_gssapi_send_auth_mic, ssh_gssapi_send_mic, ssh_message_auth_interactive_request, ssh_message_auth_reply_pk_ok, ssh_message_channel_request_open_reply_accept_channel, ssh_message_channel_request_open_reply_default, ssh_message_channel_request_reply_default, ssh_message_channel_request_reply_success, ssh_message_global_request_reply_default, ssh_message_global_request_reply_success, ssh_message_reply_default, ssh_message_service_reply_success, SSH_PACKET_CALLBACK, ssh_packet_send_unimplemented, ssh_send_debug, ssh_send_ignore, ssh_send_kex, ssh_server_send_extensions, ssh_service_request, ssh_userauth_agent_publickey, ssh_userauth_kbdint_init, ssh_userauth_kbdint_send, ssh_userauth_none, ssh_userauth_password, ssh_userauth_publickey, ssh_userauth_try_publickey, torture_packet.
SSH_PACKET_CALLBACK(ssh_packet_unimplemented)
References rc, session, ssh_buffer_unpack, SSH_LOG, SSH_LOG_RARE, SSH_LOG_WARNING, SSH_OK, SSH_PACKET_USED, user.
SSH_PACKET_CALLBACK(ssh_packet_disconnect_callback)
References ssh_session_struct::alive, error, rc, SAFE_FREE, session, ssh_session_struct::session_state, ssh_session_struct::socket, ssh_buffer_get_ssh_string, ssh_buffer_get_u32, SSH_FATAL, SSH_LOG, SSH_LOG_PACKET, SSH_PACKET_USED, SSH_SESSION_STATE_ERROR, ssh_set_error, ssh_socket_close, SSH_STRING_FREE, ssh_string_to_char, user.
SSH_PACKET_CALLBACK(ssh_packet_ignore_callback)
References session, SSH2_MSG_IGNORE, SSH_LOG, SSH_LOG_PROTOCOL, SSH_PACKET_USED, user.
SSH_PACKET_CALLBACK(ssh_packet_dh_reply)
SSH_PACKET_CALLBACK(ssh_packet_newkeys)
References ssh_session_struct::dh_handshake_state, ssh_crypto_struct::dh_server_signature, DH_STATE_FINISHED, DH_STATE_NEWKEYS_SENT, ssh_crypto_struct::digest_len, error, ssh_session_struct::next_crypto, ssh_session_struct::opts, rc, ssh_crypto_struct::secret_hash, ssh_session_struct::server, session, ssh_session_struct::session_state, ssh_session_struct::ssh_connection_callback, ssh_dh_get_next_server_publickey, SSH_DIRECTION_IN, SSH_ERROR, SSH_FATAL, SSH_HOSTKEYS, SSH_LOG, SSH_LOG_PROTOCOL, ssh_match_group, SSH_OK, ssh_packet_set_newkeys, SSH_PACKET_USED, ssh_pki_import_signature_blob, ssh_pki_signature_verify, SSH_SESSION_STATE_DH, SSH_SESSION_STATE_ERROR, ssh_set_error, ssh_signature_free, ssh_string_burn, SSH_STRING_FREE, ssh_signature_struct::type_c, user, ssh_session_struct::wanted_methods.
SSH_PACKET_CALLBACK(ssh_packet_service_accept)
References ssh_session_struct::auth, ssh_session_struct::service_state, session, SSH_AUTH_SERVICE_ACCEPTED, SSH_LOG, SSH_LOG_PACKET, SSH_PACKET_USED, user.
SSH_PACKET_CALLBACK(ssh_packet_ext_info)
References ssh_session_struct::extensions, name, rc, session, ssh_buffer_get_u32, ssh_buffer_unpack, SSH_EXT_SIG_RSA_SHA256, SSH_EXT_SIG_RSA_SHA512, SSH_LOG, SSH_LOG_PACKET, ssh_match_group, SSH_OK, SSH_PACKET_USED, user.
int ssh_packet_send_unimplemented(ssh_session session, uint32_t seqnum)
References ssh_session_struct::out_buffer, rc, session, SSH2_MSG_UNIMPLEMENTED, ssh_buffer_pack, SSH_ERROR, SSH_OK, ssh_packet_send, ssh_set_error_oom.
Referenced by ssh_packet_process, ssh_packet_socket_callback.
int ssh_packet_parse_type(ssh_session session)
int ssh_packet_socket_callback(const void *data, size_t len, void *user)
References ssh_cipher_struct::blocks, ssh_cipher_struct::blocksize, decompress_buffer, ssh_crypto_struct::do_compress_in, error, FALL_THROUGH, hmac_digest_len, ssh_session_struct::in_buffer, ssh_counter_struct::in_bytes, ssh_crypto_struct::in_cipher, ssh_crypto_struct::in_hmac_etm, ssh_session_struct::in_packet, ssh_counter_struct::in_packets, packet_struct::len, ssh_cipher_struct::lenfield_blocksize, mac, MAX_PACKET_LEN, ssh_session_struct::packet_state, PACKET_STATE_INIT, PACKET_STATE_PROCESSING, PACKET_STATE_SIZEREAD, ssh_cipher_struct::packets, PRIdS, PULL_BE_U32, ssh_session_struct::raw_counter, rc, ssh_session_struct::recv_seq, session, ssh_session_struct::session_state, ssh_buffer_allocate, ssh_buffer_get, ssh_buffer_get_len, ssh_buffer_get_u8, ssh_buffer_new, ssh_buffer_pass_bytes, ssh_buffer_pass_bytes_end, ssh_buffer_reinit, SSH_DIRECTION_IN, SSH_FATAL, SSH_LOG, SSH_LOG_PACKET, SSH_OK, SSH_PACKET_ALLOWED, ssh_packet_decrypt, ssh_packet_decrypt_len, SSH_PACKET_DENIED, ssh_packet_get_current_crypto, ssh_packet_hmac_verify, ssh_packet_incoming_filter, ssh_packet_need_rekey, ssh_packet_parse_type, ssh_packet_process, ssh_packet_send_unimplemented, ssh_packet_socket_callback, SSH_PACKET_UNKNOWN, ssh_send_rekex, SSH_SESSION_STATE_ERROR, ssh_set_error, packet_struct::type, user.
Referenced by ssh_packet_register_socket_callback, ssh_packet_socket_callback, ssh_server_connection_callback, torture_packet.
void ssh_packet_register_socket_callback(ssh_session session, struct ssh_socket_struct *s)
Referenced by ssh_client_connection_callback, ssh_server_connection_callback.
void ssh_packet_set_callbacks(ssh_session session, ssh_packet_callbacks callbacks)
References callbacks, ssh_session_struct::packet_callbacks, session, ssh_list_append, ssh_list_new.
Referenced by ssh_client_dh_init, ssh_client_dhgex_init, ssh_packet_set_default_callbacks, torture_packet.
void ssh_packet_remove_callbacks(ssh_session session, ssh_packet_callbacks callbacks)
References callbacks, ssh_session_struct::packet_callbacks, session, ssh_list_find, ssh_list_remove.
Referenced by SSH_PACKET_CALLBACK.
void ssh_packet_set_default_callbacks(ssh_session session)
References ssh_packet_callbacks_struct::callbacks, ssh_session_struct::default_packet_callbacks, default_packet_handlers, ssh_packet_callbacks_struct::n_callbacks, session, ssh_packet_set_callbacks, ssh_packet_callbacks_struct::start, ssh_packet_callbacks_struct::user.
Referenced by ssh_client_connection_callback, ssh_server_connection_callback.
void ssh_packet_process(ssh_session session, uint8_t type)
References cb, ssh_session_struct::in_buffer, ssh_iterator::next, ssh_session_struct::packet_callbacks, rc, ssh_session_struct::recv_seq, session, ssh_get_error, ssh_iterator_value, ssh_list_get_iterator, SSH_LOG, SSH_LOG_PACKET, SSH_LOG_RARE, SSH_OK, SSH_PACKET_NOT_USED, ssh_packet_send_unimplemented, SSH_PACKET_USED.
Referenced by ssh_packet_socket_callback.
uint32_t ssh_packet_decrypt_len(ssh_session session, uint8_t *destination, uint8_t *source)
References ssh_cipher_struct::aead_decrypt_length, ssh_cipher_struct::blocksize, destination, ssh_crypto_struct::in_cipher, ssh_cipher_struct::lenfield_blocksize, rc, ssh_session_struct::recv_seq, session, SSH_DIRECTION_IN, ssh_packet_decrypt, ssh_packet_get_current_crypto.
Referenced by ssh_packet_socket_callback.
int ssh_packet_decrypt(ssh_session session, uint8_t *destination, uint8_t *source, size_t start, size_t encrypted_size)
References ssh_cipher_struct::aead_decrypt, ssh_cipher_struct::blocksize, ssh_cipher_struct::decrypt, destination, ssh_crypto_struct::in_cipher, PRIdS, ssh_session_struct::recv_seq, session, SSH_DIRECTION_IN, SSH_ERROR, SSH_FATAL, ssh_packet_get_current_crypto, ssh_set_error.
Referenced by ssh_packet_decrypt_len, ssh_packet_socket_callback.
unsigned char* ssh_packet_encrypt(ssh_session session, void *packet, unsigned int len)
Referenced by packet_send2.
int ssh_packet_hmac_verify(ssh_session session, const void *data, size_t len, unsigned char *mac, enum ssh_hmac_e type)
Referenced by ssh_packet_socket_callback.
int ssh_packet_set_newkeys(ssh_session session, enum ssh_crypto_direction_e direction)
References ssh_session_struct::client, crypt_set_algorithms_client, crypto_free, crypto_new, ssh_session_struct::current_crypto, ssh_crypto_struct::decryptIV, ssh_crypto_struct::decryptkey, ssh_crypto_struct::digest_len, ssh_crypto_struct::encryptIV, ssh_crypto_struct::encryptkey, ssh_crypto_struct::in_cipher, ssh_session_struct::last_rekey_time, ssh_session_struct::next_crypto, ssh_session_struct::opts, ssh_crypto_struct::out_cipher, rc, ssh_session_struct::rekey_time, session, ssh_crypto_struct::session_id, ssh_cipher_struct::set_decrypt_key, ssh_cipher_struct::set_encrypt_key, SSH_DIRECTION_BOTH, SSH_DIRECTION_IN, SSH_DIRECTION_OUT, SSH_ERROR, ssh_generate_session_keys, ssh_init_rekey_state, SSH_LOG, SSH_LOG_PROTOCOL, SSH_LOG_TRACE, SSH_LOG_WARNING, ssh_make_sessionid, SSH_OK, ssh_set_error_oom, ssh_timestamp_init, ssh_crypto_struct::used.
Referenced by packet_send2, SSH_PACKET_CALLBACK, ssh_server_connection_callback.
struct ssh_crypto_struct* ssh_packet_get_current_crypto(ssh_session session, enum ssh_crypto_direction_e direction)
References ssh_session_struct::current_crypto, ssh_crypto_struct::in_cipher, ssh_session_struct::next_crypto, ssh_crypto_struct::out_cipher, session, SSH_DIRECTION_BOTH, SSH_DIRECTION_IN, SSH_DIRECTION_OUT, ssh_crypto_struct::used.
Referenced by gzip_compress, gzip_decompress, packet_send2, ssh_auth_reply_success, ssh_gssapi_build_mic, SSH_PACKET_CALLBACK, ssh_packet_decrypt, ssh_packet_decrypt_len, ssh_packet_encrypt, ssh_packet_hmac_verify, ssh_packet_need_rekey, ssh_packet_socket_callback, ssh_pki_do_sign, ssh_pki_do_sign_agent.