packet_crypt.c
uint32_t ssh_packet_decrypt_len(ssh_session session, uint8_t *destination, uint8_t *source)
References ssh_cipher_struct::aead_decrypt_length, ssh_cipher_struct::blocksize, destination, ssh_crypto_struct::in_cipher, ssh_cipher_struct::lenfield_blocksize, rc, ssh_session_struct::recv_seq, session, SSH_DIRECTION_IN, ssh_packet_decrypt, ssh_packet_get_current_crypto.
Referenced by ssh_packet_socket_callback.
int ssh_packet_decrypt(ssh_session session, uint8_t *destination, uint8_t *source, size_t start, size_t encrypted_size)
References ssh_cipher_struct::aead_decrypt, ssh_cipher_struct::blocksize, ssh_cipher_struct::decrypt, destination, ssh_crypto_struct::in_cipher, PRIdS, ssh_session_struct::recv_seq, session, SSH_DIRECTION_IN, SSH_ERROR, SSH_FATAL, ssh_packet_get_current_crypto, ssh_set_error.
Referenced by ssh_packet_decrypt_len, ssh_packet_socket_callback.
unsigned char* ssh_packet_encrypt(ssh_session session, void *data, uint32_t len)
References ssh_cipher_struct::aead_encrypt, ssh_cipher_struct::blocksize, ctx, ssh_cipher_struct::encrypt, ssh_crypto_struct::encryptMAC, explicit_bzero, hmac_digest_len, hmac_final, hmac_init, hmac_update, ssh_crypto_struct::hmacbuf, ssh_cipher_struct::lenfield_blocksize, ssh_crypto_struct::out_cipher, ssh_crypto_struct::out_hmac, ssh_crypto_struct::out_hmac_etm, PUSH_BE_U32, SAFE_FREE, ssh_session_struct::send_seq, session, SSH_DIRECTION_OUT, SSH_FATAL, ssh_log_hexdump, ssh_packet_get_current_crypto, ssh_set_error.
static int secure_memcmp(const void *s1, const void *s2, size_t n)
References rc.
Referenced by ssh_packet_hmac_verify.
int ssh_packet_hmac_verify(ssh_session session, const void *data, size_t len, uint8_t *mac, enum ssh_hmac_e type)
References ctx, ssh_crypto_struct::decryptMAC, DIGEST_MAX_LEN, hmac_digest_len, hmac_final, hmac_init, hmac_update, ssh_crypto_struct::hmacbuf, mac, ssh_session_struct::recv_seq, secure_memcmp, session, SSH_DIRECTION_IN, SSH_ERROR, SSH_HMAC_AEAD_GCM, SSH_HMAC_AEAD_POLY1305, ssh_log_hexdump, SSH_OK, ssh_packet_get_current_crypto.