pcap.c
int ssh_pcap_file_close(ssh_pcap_file pcap)
References pcap, SSH_ERROR.
void ssh_pcap_file_free(ssh_pcap_file pcap)
References pcap.
Referenced by cleanup_pcap, set_pcap, torture_teardown_socket_dir.
ssh_pcap_file ssh_pcap_file_new(void)
Referenced by main, set_pcap, torture_setup_socket_dir.
int ssh_pcap_file_open(ssh_pcap_file pcap, const char *filename)
References pcap, SSH_ERROR.
Referenced by main, set_pcap, torture_setup_socket_dir.
int ssh_set_pcap_file(ssh_session session, ssh_pcap_file pcapfile)
References session, SSH_ERROR, SSH_REQUEST_DENIED, ssh_set_error.
Referenced by set_pcap, torture_ssh_session.