pkd_hello.c
DEFAULT_ITERATIONS
PKDTESTS_DEFAULT_FIPS
PKDTESTS_DEFAULT
PKDTESTS_DEFAULT_OPENSSHONLY
GEX_SHA256
GEX_SHA1
PKDTESTS_KEX_FIPS
PKDTESTS_KEX_COMMON
PKDTESTS_KEX
PKDTESTS_KEX_OPENSSHONLY
PKDTESTS_CIPHER_FIPS
PKDTESTS_CIPHER
CHACHA20
AES128_GCM
AES256_GCM
PKDTESTS_CIPHER_OPENSSHONLY_FIPS
PKDTESTS_CIPHER_OPENSSHONLY
PKDTESTS_MAC_FIPS
PKDTESTS_MAC_OPENSSHONLY_FIPS
PKDTESTS_MAC
PKDTESTS_MAC_OPENSSHONLY
PKDTESTS_HOSTKEY_OPENSSHONLY_FIPS
PKDTESTS_HOSTKEY_OPENSSHONLY
emit_keytest
CLIENT_ID_FILE
CLIENT_ID_FILE
CLIENT_ID_FILE
CLIENT_ID_FILE
emit_testmap
emit_unit_test
emit_unit_test_comma
struct pkd_daemon_args pkd_dargs
Referenced by main, pkd_cleanup_socket_wrapper, pkd_init_socket_wrapper, pkd_run_tests, torture_pkd_runtest, torture_pkd_setup.
uint8_t default_payload_buf[][]
Referenced by main.
size_t default_payload_len
Referenced by main.
const char* testname
Referenced by main, pkd_run_tests, torture_pkd_runtest.
const struct CMUnitTest test
Referenced by docycle, pkd_run_tests, sftp_test.
struct @14 testmap[][]
Referenced by main, pkd_run_tests.
static struct pkd_state* torture_pkd_setup(enum pkd_hostkey_type_e type, const char *hostkeypath)
References pkd_daemon_args::hostkeypath, pkd_dargs, pkd_start, rc, pkd_daemon_args::type.
Referenced by torture_pkd_setup_ecdsa_256, torture_pkd_setup_ecdsa_384, torture_pkd_setup_ecdsa_521, torture_pkd_setup_ed25519, torture_pkd_setup_noop, torture_pkd_setup_rsa.
static int torture_pkd_teardown(void **state)
References pkd_result::ok, pkd_stop.
static int torture_pkd_setup_noop(void **state)
References PKD_RSA, torture_pkd_setup.
static int torture_pkd_setup_rsa(void **state)
References LIBSSH_RSA_TESTKEY, PKD_RSA, setup_rsa_key, torture_pkd_setup.
static int torture_pkd_setup_ed25519(void **state)
References LIBSSH_ED25519_TESTKEY, PKD_ED25519, setup_ed25519_key, torture_pkd_setup.
static int torture_pkd_setup_ecdsa_256(void **state)
References LIBSSH_ECDSA_256_TESTKEY, PKD_ECDSA, setup_ecdsa_keys, torture_pkd_setup.
static int torture_pkd_setup_ecdsa_384(void **state)
References LIBSSH_ECDSA_384_TESTKEY, PKD_ECDSA, setup_ecdsa_keys, torture_pkd_setup.
static int torture_pkd_setup_ecdsa_521(void **state)
References LIBSSH_ECDSA_521_TESTKEY, PKD_ECDSA, setup_ecdsa_keys, torture_pkd_setup.
static void torture_pkd_client_noop(void **state)
References pkd_state.
static void torture_pkd_runtest(const char *testname, const char *testcmd)
References DEFAULT_ITERATIONS, pkd_daemon_args::iterations, pkd_daemon_args::opts, pkd_dargs, rc, system_checked, testname.
static int pkd_run_tests(void)
References cleanup_dropbear_client_rsa_key, cleanup_ecdsa_keys, cleanup_ed25519_key, cleanup_openssh_client_keys, cleanup_rsa_key, client, DROPBEAR_CIPHER_CMD, DROPBEAR_CMD, DROPBEAR_MAC_CMD, emit_unit_test, emit_unit_test_comma, is_dropbear_client_enabled, is_openssh_client_enabled, OPENSSH_CERT_CMD, OPENSSH_CIPHER_CMD, OPENSSH_CMD, OPENSSH_KEX_CMD, OPENSSH_MAC_CMD, OPENSSH_SHA256_CERT_CMD, pkd_daemon_args::opts, pkd_dargs, PKDTESTS_CIPHER, PKDTESTS_CIPHER_FIPS, PKDTESTS_CIPHER_OPENSSHONLY, PKDTESTS_CIPHER_OPENSSHONLY_FIPS, PKDTESTS_DEFAULT, PKDTESTS_DEFAULT_FIPS, PKDTESTS_DEFAULT_OPENSSHONLY, PKDTESTS_KEX, PKDTESTS_KEX_FIPS, PKDTESTS_MAC, PKDTESTS_MAC_FIPS, PKDTESTS_MAC_OPENSSHONLY, PKDTESTS_MAC_OPENSSHONLY_FIPS, rc, setup_dropbear_client_rsa_key, setup_openssh_client_keys, teardown, test, testmap, pkd_daemon_args::testmatch, pkd_daemon_args::testname, testname.
Referenced by main.
static int pkd_init_socket_wrapper(void)
References pkd_daemon_args::opts, pkd_dargs, rc, pkd_daemon_args::socket_wrapper.
Referenced by main.
static int pkd_rmfiles(const char *path)
References system_checked.
Referenced by pkd_cleanup_socket_wrapper.
static int pkd_cleanup_socket_wrapper(void)
References pkd_daemon_args::opts, pkd_dargs, pkd_rmfiles, rc, pkd_daemon_args::socket_wrapper.
Referenced by main.
int main(int argc, char **argv)
References pkd_daemon_args::buf, default_payload_buf, default_payload_len, pkd_daemon_args::len, pkd_daemon_args::list, pkd_daemon_args::opts, pkd_daemon_args::payload, pkd_cleanup_socket_wrapper, pkd_dargs, pkd_init_socket_wrapper, pkd_run_tests, rc, ssh_finalize, ssh_init, testmap, testname.