pki.h
ED25519_KEY_LEN
MAX_PUBKEY_SIZE
MAX_PRIVKEY_SIZE
SSH_KEY_FLAG_EMPTY
SSH_KEY_FLAG_PUBLIC
SSH_KEY_FLAG_PRIVATE
SSH_KEY_FLAG_PKCS11_URI
is_ecdsa_key_type
is_cert_type
typedef struct ssh_signature_struct* ssh_signature
ssh_key ssh_key_dup(const ssh_key key)
References key, pki_key_dup.
Referenced by ssh_bind_accept_fd, ssh_get_server_publickey, ssh_pki_convert_key_to_publickey, thread_pki_rsa_duplicate_key, torture_pki_dsa_duplicate_key, torture_pki_ecdsa_duplicate_key, torture_pki_ecdsa_duplicate_key_uri, torture_pki_ecdsa_duplicate_then_demote, torture_pki_ecdsa_duplicate_then_demote_uri, torture_pki_ed25519_privkey_dup, torture_pki_ed25519_pubkey_dup, torture_pki_rsa_duplicate_key.
void ssh_key_clean(ssh_key key)
clean up the key and deallocate all existing keys
key ssh_key to clean
References ED25519_KEY_LEN, explicit_bzero, key, SAFE_FREE, SSH_BUFFER_FREE, SSH_KEY_FLAG_EMPTY, SSH_KEYTYPE_SK_ECDSA, SSH_KEYTYPE_SK_ECDSA_CERT01, SSH_KEYTYPE_SK_ED25519, SSH_KEYTYPE_SK_ED25519_CERT01, SSH_KEYTYPE_UNKNOWN, ssh_string_burn, ssh_string_free.
Referenced by ssh_key_free.
const char* ssh_key_get_signature_algorithm(ssh_session session, enum ssh_keytypes_e type)
Gets signature algorithm name to be used with the given key type.
session SSH session. type The algorithm type to convert. A string for the keytype or NULL if unknown.
References ssh_session_struct::openssh, session, ssh_key_signature_to_char, ssh_key_type_to_hash, SSH_KEYTYPE_RSA_CERT01, SSH_LOG, SSH_LOG_DEBUG, SSH_VERSION_INT.
Referenced by ssh_userauth_agent_publickey, ssh_userauth_publickey, ssh_userauth_try_publickey.
enum ssh_keytypes_e ssh_key_type_from_signature_name(const char *name)
Convert a ssh key algorithm name to a ssh key algorithm type.
name The name to convert. The enum ssh key algorithm type.
Referenced by ssh_pki_import_signature_blob.
enum ssh_keytypes_e ssh_key_type_plain(enum ssh_keytypes_e type)
Get the pubic key type corresponding to a certificate type.
type The certificate or public key type. The matching public key type.
Referenced by pki_signature_from_blob, ssh_agent_sign_data, ssh_pki_signature_verify, torture_pki_verify_mismatch.
enum ssh_digest_e ssh_key_type_to_hash(ssh_session session, enum ssh_keytypes_e type)
Convert a key type to a hash type. This is usually unambiguous for all the key types, unless the SHA2 extension (RFC 8332) is negotiated during key exchange.
session SSH Session. type The type to convert. A hash type to be used.
Referenced by ssh_userauth_publickey, torture_options_set_pubkey_accepted_types, torture_pki_ecdsa_cert_verify.
enum ssh_digest_e ssh_key_hash_from_name(const char *name)
References SSH_KEYTYPE_DSS, SSH_KEYTYPE_DSS_CERT01, SSH_KEYTYPE_ECDSA, SSH_KEYTYPE_ECDSA_P256, SSH_KEYTYPE_ECDSA_P256_CERT01, SSH_KEYTYPE_ECDSA_P384, SSH_KEYTYPE_ECDSA_P384_CERT01, SSH_KEYTYPE_ECDSA_P521, SSH_KEYTYPE_ECDSA_P521_CERT01, SSH_KEYTYPE_ED25519, SSH_KEYTYPE_ED25519_CERT01, SSH_KEYTYPE_RSA, SSH_KEYTYPE_RSA1, SSH_KEYTYPE_RSA_CERT01, SSH_KEYTYPE_SK_ECDSA, SSH_KEYTYPE_SK_ECDSA_CERT01, SSH_KEYTYPE_SK_ED25519, SSH_KEYTYPE_SK_ED25519_CERT01, SSH_KEYTYPE_UNKNOWN.
Referenced by ssh_pki_import_signature_blob.
ssh_signature ssh_signature_new(void)
References ZERO_STRUCTP.
Referenced by pki_do_sign_hash, pki_sign_data, pki_signature_from_blob.
void ssh_signature_free(ssh_signature sign)
References ssh_signature_struct::ed25519_sig, ssh_signature_struct::raw_sig, SAFE_FREE, SSH_KEYTYPE_DSS, SSH_KEYTYPE_DSS_CERT01, SSH_KEYTYPE_ECDSA, SSH_KEYTYPE_ECDSA_P256, SSH_KEYTYPE_ECDSA_P256_CERT01, SSH_KEYTYPE_ECDSA_P384, SSH_KEYTYPE_ECDSA_P384_CERT01, SSH_KEYTYPE_ECDSA_P521, SSH_KEYTYPE_ECDSA_P521_CERT01, SSH_KEYTYPE_ED25519, SSH_KEYTYPE_ED25519_CERT01, SSH_KEYTYPE_RSA, SSH_KEYTYPE_RSA1, SSH_KEYTYPE_RSA_CERT01, SSH_KEYTYPE_SK_ECDSA, SSH_KEYTYPE_SK_ECDSA_CERT01, SSH_KEYTYPE_SK_ED25519, SSH_KEYTYPE_SK_ED25519_CERT01, SSH_KEYTYPE_UNKNOWN, ssh_string_burn, SSH_STRING_FREE, ssh_signature_struct::type.
Referenced by pki_do_sign_hash, pki_sign_data, pki_signature_from_blob, SSH_PACKET_CALLBACK, ssh_pki_do_sign, test_sign_verify_data, thread_pki_rsa_generate_key, torture_ecdsa_sign_verify_uri, torture_pki_dsa_cert_verify, torture_pki_dsa_generate_key, torture_pki_ecdsa_cert_verify, torture_pki_ed25519_cert_verify, torture_pki_ed25519_generate_key, torture_pki_ed25519_sign, torture_pki_ed25519_sign_openssh_privkey_passphrase, torture_pki_ed25519_verify, torture_pki_ed25519_verify_bad, torture_pki_fail_sign_with_incompatible_hash, torture_pki_generate_key_ecdsa, torture_pki_rsa_generate_key, torture_pki_rsa_sha2, torture_pki_sign_verify_uri, torture_pki_verify_mismatch.
int ssh_pki_export_signature_blob(const ssh_signature sign, ssh_string *sign_blob)
References pki_signature_to_blob, rc, ssh_buffer_add_ssh_string, SSH_BUFFER_FREE, ssh_buffer_get, ssh_buffer_get_len, ssh_buffer_new, SSH_ERROR, SSH_OK, ssh_string_fill, SSH_STRING_FREE, ssh_string_from_char, ssh_string_new, ssh_signature_struct::type_c.
Referenced by ssh_pki_do_sign.
int ssh_pki_import_signature_blob(const ssh_string sig_blob, const ssh_key pubkey, ssh_signature *psig)
References pki_signature_from_blob, pubkey, rc, ssh_signature_struct::sk_counter, ssh_signature_struct::sk_flags, ssh_buffer_add_data, SSH_BUFFER_FREE, ssh_buffer_get_ssh_string, ssh_buffer_new, ssh_buffer_unpack, SSH_ERROR, ssh_key_hash_from_name, ssh_key_type_from_signature_name, SSH_KEYTYPE_SK_ECDSA, SSH_KEYTYPE_SK_ED25519, SSH_OK, ssh_string_data, SSH_STRING_FREE, ssh_string_get_char, ssh_string_len.
Referenced by SSH_PACKET_CALLBACK.
int ssh_pki_signature_verify(ssh_session session, ssh_signature sig, const ssh_key key, const unsigned char *digest, size_t dlen)
References ctx, explicit_bzero, ssh_signature_struct::hash_type, key, pki_key_check_hash_compatible, pki_verify_data_signature, rc, session, sha256_final, sha256_init, sha256_update, ssh_signature_struct::sk_counter, ssh_signature_struct::sk_flags, ssh_buffer_free, ssh_buffer_get, ssh_buffer_get_len, ssh_buffer_new, ssh_buffer_pack, SSH_ERROR, ssh_key_type_plain, SSH_KEYTYPE_SK_ECDSA, SSH_KEYTYPE_SK_ECDSA_CERT01, SSH_KEYTYPE_SK_ED25519, SSH_KEYTYPE_SK_ED25519_CERT01, SSH_LOG, SSH_LOG_FUNCTIONS, SSH_LOG_TRACE, SSH_LOG_WARN, SSH_OK, ssh_string_data, ssh_string_len, ssh_signature_struct::type, ssh_signature_struct::type_c.
Referenced by SSH_PACKET_CALLBACK, thread_pki_rsa_generate_key, torture_ecdsa_sign_verify_uri, torture_pki_dsa_cert_verify, torture_pki_dsa_generate_key, torture_pki_ecdsa_cert_verify, torture_pki_ed25519_cert_verify, torture_pki_ed25519_generate_key, torture_pki_ed25519_verify, torture_pki_ed25519_verify_bad, torture_pki_generate_key_ecdsa, torture_pki_rsa_generate_key, torture_pki_rsa_sha2, torture_pki_sign_verify_uri, torture_pki_verify_mismatch.
int ssh_pki_export_pubkey_blob(const ssh_key key, ssh_string *pblob)
References key, pki_publickey_to_blob, SSH_ERROR, SSH_OK.
Referenced by publickey_from_file, publickey_to_string, ssh_agent_sign_data, ssh_dh_get_current_server_publickey_blob, ssh_dh_get_next_server_publickey_blob, ssh_get_key_params, ssh_get_pubkey_hash, ssh_get_publickey_hash, ssh_message_auth_reply_pk_ok_simple, ssh_userauth_agent_publickey, ssh_userauth_publickey, ssh_userauth_try_publickey.
int ssh_pki_import_pubkey_blob(const ssh_string key_blob, ssh_key *pkey)
References buffer, is_cert_type, pki_import_cert_buffer, pki_import_pubkey_buffer, rc, ssh_buffer_add_data, SSH_BUFFER_FREE, ssh_buffer_get_ssh_string, ssh_buffer_new, SSH_ERROR, ssh_key_type_from_name, SSH_KEYTYPE_UNKNOWN, SSH_LOG, SSH_LOG_WARN, ssh_string_data, SSH_STRING_FREE, ssh_string_get_char, ssh_string_len.
Referenced by publickey_from_string, ssh_agent_get_next_ident, ssh_dh_import_next_pubkey_blob, ssh_pki_import_cert_blob, ssh_pki_openssh_import, ssh_userauth_offer_pubkey.
int ssh_pki_import_cert_blob(const ssh_string cert_blob, ssh_key *pkey)
References ssh_pki_import_pubkey_blob.
Referenced by ssh_agent_get_next_ident.
ssh_string ssh_pki_do_sign(ssh_session session, ssh_buffer sigbuf, const ssh_key privatekey, enum ssh_digest_e hash_type)
References ssh_crypto_struct::digest_len, pki_do_sign, privkey, rc, session, ssh_crypto_struct::session_id, SSH_BUFFER_FREE, ssh_buffer_get, ssh_buffer_get_len, ssh_buffer_new, ssh_buffer_pack, ssh_buffer_set_secure, SSH_DIRECTION_BOTH, ssh_key_is_private, SSH_LOG, SSH_LOG_TRACE, SSH_OK, ssh_packet_get_current_crypto, ssh_pki_export_signature_blob, ssh_signature_free, ssh_string_fill, SSH_STRING_FREE, ssh_string_new.
Referenced by ssh_userauth_publickey.
ssh_string ssh_pki_do_sign_agent(ssh_session session, struct ssh_buffer_struct *buf, const ssh_key pubkey)
References ssh_crypto_struct::digest_len, pubkey, rc, session, ssh_crypto_struct::session_id, ssh_agent_sign_data, ssh_buffer_add_buffer, ssh_buffer_add_ssh_string, SSH_BUFFER_FREE, ssh_buffer_new, SSH_DIRECTION_BOTH, ssh_packet_get_current_crypto, ssh_string_fill, SSH_STRING_FREE, ssh_string_new.
Referenced by ssh_userauth_agent_publickey.
ssh_string ssh_srv_pki_do_sign_sessionid(ssh_session session, const ssh_key privkey, const enum ssh_digest_e digest)
ssh_public_key ssh_pki_convert_key_to_publickey(const ssh_key key)
References key, ssh_key_dup, ssh_key_free, ssh_public_key_struct::type, ssh_key_struct::type, ssh_public_key_struct::type_c, ssh_key_struct::type_c, ZERO_STRUCTP.
Referenced by publickey_from_privatekey, ssh_message_auth_publickey.
ssh_private_key ssh_pki_convert_key_to_privatekey(const ssh_key key)
References key, privkey, ssh_key_free.
int ssh_key_algorithm_allowed(ssh_session session, const char *type)
Checks the given key against the configured allowed public key algorithm types.
session The SSH session type The key algorithm to check 1 if the key algorithm is allowed, 0 otherwise
References ssh_session_struct::client, ssh_session_struct::opts, ssh_session_struct::pubkey_accepted_types, ssh_session_struct::server, session, SSH_HOSTKEYS, ssh_kex_get_default_methods, ssh_kex_get_fips_methods, SSH_LOG, SSH_LOG_DEBUG, SSH_LOG_WARN, ssh_match_group, ssh_session_struct::wanted_methods.
Referenced by ssh_userauth_agent_publickey, ssh_userauth_publickey, ssh_userauth_try_publickey.
bool ssh_pki_is_uri(const char *filename)
Detect if the pathname in cmp is a PKCS #11 URI.
cmp The path to the public/private key or a private/public PKCS #11 URI. true if filename is a URI starting with "pkcs11:" false otherwise.
References PKCS11_URI, rc.
Referenced by ssh_pki_import_privkey_file, ssh_pki_import_pubkey_file, ssh_userauth_publickey_auto.
char* ssh_pki_export_pub_uri_from_priv_uri(const char *priv_uri)
export a Public PKCS #11 URI from a Private PKCS #11 URI by replacing "type=private" to "type=public". TODO: Improve the parser
priv_uri Private PKCS #11 URI. pointer to the public PKCS #11 URI
References ssh_strreplace.
Referenced by ssh_userauth_publickey_auto.