pki_priv.h
RSA_HEADER_BEGIN
RSA_HEADER_END
DSA_HEADER_BEGIN
DSA_HEADER_END
ECDSA_HEADER_BEGIN
ECDSA_HEADER_END
OPENSSH_HEADER_BEGIN
OPENSSH_HEADER_END
OPENSSH_AUTH_MAGIC
ssh_key_e
int bcrypt_pbkdf(const char *pass, size_t passlen, const uint8_t *salt, size_t saltlen, uint8_t *key, size_t keylen, unsigned int rounds)
References bcrypt_hash, BCRYPT_HASHSIZE, ctx, explicit_bzero, key, MIN, SHA512_DIGEST_LENGTH, sha512_final, sha512_init, sha512_update.
Referenced by pki_private_key_decrypt, pki_private_key_encrypt.
int pki_key_ecdsa_nid_from_name(const char *name)
Referenced by pki_import_privkey_buffer, pki_import_pubkey_buffer.
const char* pki_key_ecdsa_nid_to_name(int nid)
Referenced by ssh_pki_key_ecdsa_name.
const char* ssh_key_signature_to_char(enum ssh_keytypes_e type, enum ssh_digest_e hash_type)
Convert a signature type to a string.
type The algorithm type to convert. A string for the keytype or NULL if unknown.
References SSH_DIGEST_AUTO, SSH_DIGEST_SHA1, SSH_DIGEST_SHA256, SSH_DIGEST_SHA512, ssh_key_type_to_char, SSH_KEYTYPE_RSA, SSH_KEYTYPE_RSA_CERT01.
Referenced by pki_do_sign_hash, pki_sign_data, pki_signature_from_blob, ssh_key_get_signature_algorithm.
enum ssh_digest_e ssh_key_type_to_hash(ssh_session session, enum ssh_keytypes_e type)
Convert a key type to a hash type. This is usually unambiguous for all the key types, unless the SHA2 extension (RFC 8332) is negotiated during key exchange.
session SSH Session. type The type to convert. A hash type to be used.
Referenced by ssh_key_get_signature_algorithm.
ssh_key pki_key_dup(const ssh_key key, int demote)
References DSA_get0_key, DSA_get0_pqg, DSA_set0_key, DSA_set0_pqg, key, pki_ed25519_key_dup, rc, RSA_get0_crt_params, RSA_get0_factors, RSA_get0_key, RSA_set0_crt_params, RSA_set0_factors, RSA_set0_key, SSH_KEY_FLAG_PRIVATE, SSH_KEY_FLAG_PUBLIC, ssh_key_free, ssh_key_is_private, ssh_key_new, SSH_KEYTYPE_DSS, SSH_KEYTYPE_ECDSA_P256, SSH_KEYTYPE_ECDSA_P384, SSH_KEYTYPE_ECDSA_P521, SSH_KEYTYPE_ED25519, SSH_KEYTYPE_RSA, SSH_KEYTYPE_RSA1, SSH_KEYTYPE_UNKNOWN, SSH_OK.
Referenced by ssh_key_dup, ssh_pki_export_privkey_to_pubkey.
int pki_key_generate_rsa(ssh_key key, int parameter)
References key, rc, SSH_ERROR, SSH_OK.
Referenced by ssh_pki_generate.
int pki_key_generate_dss(ssh_key key, int parameter)
References key, rc, SSH_ERROR, SSH_OK.
Referenced by ssh_pki_generate.
int pki_key_generate_ecdsa(ssh_key key, int parameter)
Referenced by ssh_pki_generate.
int pki_key_generate_ed25519(ssh_key key)
References crypto_sign_ed25519_keypair, error, key, rc, SAFE_FREE, SSH_ERROR, SSH_OK.
Referenced by ssh_pki_generate.
int pki_key_compare(const ssh_key k1, const ssh_key k2, enum ssh_keycmp_e what)
References DSA_get0_key, DSA_get0_pqg, RSA_get0_factors, RSA_get0_key, SSH_KEY_CMP_PRIVATE, SSH_KEYTYPE_DSS, SSH_KEYTYPE_ECDSA_P256, SSH_KEYTYPE_ECDSA_P384, SSH_KEYTYPE_ECDSA_P521, SSH_KEYTYPE_ED25519, SSH_KEYTYPE_RSA, SSH_KEYTYPE_RSA1, SSH_KEYTYPE_SK_ECDSA, SSH_KEYTYPE_SK_ED25519, SSH_KEYTYPE_UNKNOWN, ssh_key_struct::type.
Referenced by ssh_key_cmp.
int pki_key_check_hash_compatible(ssh_key key, enum ssh_digest_e hash_type)
References key, SSH_DIGEST_AUTO, SSH_DIGEST_SHA1, SSH_DIGEST_SHA256, SSH_DIGEST_SHA384, SSH_DIGEST_SHA512, SSH_ERROR, SSH_KEYTYPE_DSS, SSH_KEYTYPE_DSS_CERT01, SSH_KEYTYPE_ECDSA, SSH_KEYTYPE_ECDSA_P256, SSH_KEYTYPE_ECDSA_P256_CERT01, SSH_KEYTYPE_ECDSA_P384, SSH_KEYTYPE_ECDSA_P384_CERT01, SSH_KEYTYPE_ECDSA_P521, SSH_KEYTYPE_ECDSA_P521_CERT01, SSH_KEYTYPE_ED25519, SSH_KEYTYPE_ED25519_CERT01, SSH_KEYTYPE_RSA, SSH_KEYTYPE_RSA1, SSH_KEYTYPE_RSA_CERT01, SSH_KEYTYPE_SK_ECDSA, SSH_KEYTYPE_SK_ECDSA_CERT01, SSH_KEYTYPE_SK_ED25519, SSH_KEYTYPE_SK_ED25519_CERT01, SSH_KEYTYPE_UNKNOWN, SSH_LOG, SSH_LOG_TRACE, SSH_LOG_WARN, SSH_OK.
Referenced by pki_do_sign, pki_sign_data, pki_verify_data_signature, ssh_pki_signature_verify.
enum ssh_keytypes_e pki_privatekey_type_from_string(const char *privkey)
ssh_key pki_private_key_from_base64(const char *b64_key, const char *passphrase, ssh_auth_callback auth_fn, void *auth_data)
References ED25519_KEY_LEN, is_ecdsa_key_type, key, pem_get_password, SAFE_FREE, SSH_KEY_FLAG_PRIVATE, SSH_KEY_FLAG_PUBLIC, ssh_key_free, ssh_key_new, ssh_key_type_to_char, SSH_KEYTYPE_DSS, SSH_KEYTYPE_ED25519, SSH_KEYTYPE_RSA, SSH_KEYTYPE_UNKNOWN, SSH_LOG, SSH_LOG_TRACE, SSH_LOG_WARN.
Referenced by ssh_pki_import_privkey_base64.
ssh_string pki_private_key_to_pem(const ssh_key key, const char *passphrase, ssh_auth_callback auth_fn, void *auth_data)
References ssh_string_struct::data, ED25519_KEY_LEN, key, pem_get_password, rc, SSH_KEYTYPE_DSS, SSH_KEYTYPE_DSS_CERT01, SSH_KEYTYPE_ECDSA_P256, SSH_KEYTYPE_ECDSA_P256_CERT01, SSH_KEYTYPE_ECDSA_P384, SSH_KEYTYPE_ECDSA_P384_CERT01, SSH_KEYTYPE_ECDSA_P521, SSH_KEYTYPE_ECDSA_P521_CERT01, SSH_KEYTYPE_ED25519, SSH_KEYTYPE_ED25519_CERT01, SSH_KEYTYPE_RSA, SSH_KEYTYPE_RSA1, SSH_KEYTYPE_RSA_CERT01, SSH_KEYTYPE_UNKNOWN, SSH_LOG, SSH_LOG_TRACE, SSH_LOG_WARN, ssh_string_fill, ssh_string_new.
Referenced by ssh_pki_export_privkey_base64, ssh_pki_export_privkey_file.
int pki_import_privkey_buffer(enum ssh_keytypes_e type, ssh_buffer buffer, ssh_key *pkey)
References buffer, key, pki_key_ecdsa_nid_from_name, pki_privkey_build_dss, pki_privkey_build_ecdsa, pki_privkey_build_ed25519, pki_privkey_build_rsa, privkey, pubkey, rc, ssh_buffer_unpack, SSH_ERROR, SSH_KEY_FLAG_PRIVATE, SSH_KEY_FLAG_PUBLIC, ssh_key_free, ssh_key_new, ssh_key_type_to_char, SSH_KEYTYPE_DSS, SSH_KEYTYPE_DSS_CERT01, SSH_KEYTYPE_ECDSA_P256, SSH_KEYTYPE_ECDSA_P256_CERT01, SSH_KEYTYPE_ECDSA_P384, SSH_KEYTYPE_ECDSA_P384_CERT01, SSH_KEYTYPE_ECDSA_P521, SSH_KEYTYPE_ECDSA_P521_CERT01, SSH_KEYTYPE_ED25519, SSH_KEYTYPE_ED25519_CERT01, SSH_KEYTYPE_RSA, SSH_KEYTYPE_RSA1, SSH_KEYTYPE_RSA_CERT01, SSH_KEYTYPE_SK_ECDSA, SSH_KEYTYPE_SK_ECDSA_CERT01, SSH_KEYTYPE_SK_ED25519, SSH_KEYTYPE_SK_ED25519_CERT01, SSH_KEYTYPE_UNKNOWN, SSH_LOG, ssh_log_hexdump, SSH_LOG_WARN, SSH_OK, ssh_string_burn, ssh_string_data, SSH_STRING_FREE, ssh_string_get_char, ssh_string_len.
Referenced by pki_openssh_import_privkey_blob.
int pki_pubkey_build_dss(ssh_key key, ssh_string p, ssh_string q, ssh_string g, ssh_string pubkey)
References DSA_set0_key, DSA_set0_pqg, key, pubkey, rc, SSH_ERROR, ssh_make_string_bn, SSH_OK.
Referenced by pki_import_pubkey_buffer.
int pki_pubkey_build_rsa(ssh_key key, ssh_string e, ssh_string n)
References key, rc, RSA_set0_key, SSH_ERROR, ssh_make_string_bn, SSH_OK.
Referenced by pki_import_pubkey_buffer.
int pki_pubkey_build_ecdsa(ssh_key key, int nid, ssh_string e)
Referenced by pki_import_pubkey_buffer.
ssh_string pki_publickey_to_blob(const ssh_key key)
References buffer, DSA_get0_key, DSA_get0_pqg, key, pki_ed25519_public_key_to_blob, rc, RSA_get0_key, ssh_buffer_add_buffer, ssh_buffer_add_ssh_string, SSH_BUFFER_FREE, ssh_buffer_get, ssh_buffer_get_len, ssh_buffer_new, SSH_ERROR, SSH_KEYTYPE_DSS, SSH_KEYTYPE_ECDSA_P256, SSH_KEYTYPE_ECDSA_P384, SSH_KEYTYPE_ECDSA_P521, SSH_KEYTYPE_ED25519, SSH_KEYTYPE_RSA, SSH_KEYTYPE_RSA1, SSH_KEYTYPE_SK_ECDSA, SSH_KEYTYPE_SK_ED25519, SSH_KEYTYPE_UNKNOWN, ssh_make_bignum_string, ssh_string_burn, ssh_string_fill, SSH_STRING_FREE, ssh_string_from_char, ssh_string_new.
Referenced by ssh_pki_export_pubkey_base64, ssh_pki_export_pubkey_blob, ssh_pki_openssh_privkey_export.
int pki_privkey_build_dss(ssh_key key, ssh_string p, ssh_string q, ssh_string g, ssh_string pubkey, ssh_string privkey)
References DSA_set0_key, DSA_set0_pqg, key, privkey, pubkey, rc, SSH_ERROR, ssh_make_string_bn, SSH_OK.
Referenced by pki_import_privkey_buffer.
int pki_privkey_build_rsa(ssh_key key, ssh_string n, ssh_string e, ssh_string d, ssh_string iqmp, ssh_string p, ssh_string q)
Referenced by pki_import_privkey_buffer.
int pki_privkey_build_ecdsa(ssh_key key, int nid, ssh_string e, ssh_string exp)
Referenced by pki_import_privkey_buffer.
ssh_signature pki_sign_data(const ssh_key privkey, enum ssh_digest_e hash_type, const unsigned char *input, size_t input_len)
References ctx, EVP_MD_CTX_free, explicit_bzero, ssh_signature_struct::hash_type, pki_digest_to_md, pki_do_sign_hash, pki_key_check_hash_compatible, pki_key_to_pkey, privkey, ssh_signature_struct::raw_sig, rc, SAFE_FREE, SSH_DIGEST_AUTO, ssh_key_is_private, ssh_key_signature_to_char, SSH_KEYTYPE_ED25519, SSH_KEYTYPE_ED25519_CERT01, SSH_LOG, ssh_log_hexdump, SSH_LOG_TRACE, SSH_OK, ssh_signature_free, ssh_signature_new, ssh_string_fill, ssh_string_new, ssh_signature_struct::type, ssh_signature_struct::type_c.
Referenced by pki_do_sign, test_sign_verify_data, torture_pki_fail_sign_with_incompatible_hash.
int pki_verify_data_signature(ssh_signature signature, const ssh_key pubkey, const unsigned char *input, size_t input_len)
References ctx, ssh_signature_struct::ed25519_sig, endif, EVP_MD_CTX_free, ssh_signature_struct::hash_type, pki_digest_to_md, pki_ed25519_verify, pki_key_check_hash_compatible, pki_key_to_pkey, pubkey, ssh_signature_struct::raw_sig, rc, SSH_DIGEST_AUTO, SSH_ERROR, ssh_key_is_private, SSH_KEYTYPE_ED25519, SSH_KEYTYPE_ED25519_CERT01, SSH_KEYTYPE_SK_ED25519, SSH_KEYTYPE_SK_ED25519_CERT01, SSH_LOG, SSH_LOG_TRACE, SSH_OK, ssh_string_data, ssh_string_len.
Referenced by ssh_pki_signature_verify, test_sign_verify_data, torture_pki_fail_sign_with_incompatible_hash.
ssh_string pki_signature_to_blob(const ssh_signature sign)
References pki_dsa_signature_to_blob, pki_ecdsa_signature_to_blob, pki_ed25519_signature_to_blob, ssh_signature_struct::raw_sig, SSH_KEYTYPE_DSS, SSH_KEYTYPE_ECDSA_P256, SSH_KEYTYPE_ECDSA_P384, SSH_KEYTYPE_ECDSA_P521, SSH_KEYTYPE_ED25519, SSH_KEYTYPE_RSA, SSH_KEYTYPE_RSA1, SSH_KEYTYPE_UNKNOWN, SSH_LOG, SSH_LOG_WARN, ssh_string_copy, ssh_signature_struct::type, ssh_signature_struct::type_c.
Referenced by ssh_pki_export_signature_blob, torture_pki_ed25519_sign, torture_pki_ed25519_sign_openssh_privkey_passphrase, torture_pki_verify_mismatch.
ssh_signature pki_signature_from_blob(const ssh_key pubkey, const ssh_string sig_blob, enum ssh_keytypes_e type, enum ssh_digest_e hash_type)
References error, ssh_signature_struct::hash_type, pki_signature_from_dsa_blob, pki_signature_from_ecdsa_blob, pki_signature_from_ed25519_blob, pki_signature_from_rsa_blob, pubkey, rc, ssh_key_signature_to_char, ssh_key_type_plain, SSH_KEYTYPE_DSS, SSH_KEYTYPE_ECDSA_P256, SSH_KEYTYPE_ECDSA_P256_CERT01, SSH_KEYTYPE_ECDSA_P384, SSH_KEYTYPE_ECDSA_P384_CERT01, SSH_KEYTYPE_ECDSA_P521, SSH_KEYTYPE_ECDSA_P521_CERT01, SSH_KEYTYPE_ED25519, SSH_KEYTYPE_RSA, SSH_KEYTYPE_RSA1, SSH_KEYTYPE_SK_ECDSA, SSH_KEYTYPE_SK_ECDSA_CERT01, SSH_KEYTYPE_SK_ED25519, SSH_KEYTYPE_UNKNOWN, SSH_LOG, SSH_LOG_WARN, SSH_OK, ssh_signature_free, ssh_signature_new, ssh_signature_struct::type, ssh_signature_struct::type_c.
Referenced by ssh_pki_import_signature_blob, torture_pki_ed25519_verify, torture_pki_ed25519_verify_bad, torture_pki_verify_mismatch.
ssh_signature pki_do_sign(const ssh_key privkey, const unsigned char *input, size_t input_len, enum ssh_digest_e hash_type)
References pki_key_check_hash_compatible, pki_sign_data, privkey, rc, SSH_LOG, SSH_LOG_TRACE, SSH_OK.
Referenced by ssh_pki_do_sign, thread_pki_rsa_generate_key, torture_ecdsa_sign_verify_uri, torture_pki_dsa_cert_verify, torture_pki_dsa_generate_key, torture_pki_ecdsa_cert_verify, torture_pki_ed25519_cert_verify, torture_pki_ed25519_generate_key, torture_pki_ed25519_sign, torture_pki_ed25519_sign_openssh_privkey_passphrase, torture_pki_generate_key_ecdsa, torture_pki_rsa_generate_key, torture_pki_rsa_sha2, torture_pki_sign_verify_uri, torture_pki_verify_mismatch.
ssh_signature pki_do_sign_hash(const ssh_key privkey, const unsigned char *hash, size_t hlen, enum ssh_digest_e hash_type)
References ssh_signature_struct::hash_type, pki_ed25519_sign, privkey, rc, ssh_key_signature_to_char, SSH_KEYTYPE_ED25519, SSH_OK, ssh_signature_free, ssh_signature_new, ssh_signature_struct::type, ssh_signature_struct::type_c.
Referenced by pki_sign_data.
int pki_ed25519_sign(const ssh_key privkey, ssh_signature sig, const unsigned char *hash, size_t hlen)
References buffer, crypto_sign_ed25519, ssh_signature_struct::ed25519_sig, ED25519_SIG_LEN, error, privkey, rc, SAFE_FREE, SSH_ERROR, SSH_OK.
Referenced by pki_do_sign_hash.
int pki_ed25519_verify(const ssh_key pubkey, ssh_signature sig, const unsigned char *hash, size_t hlen)
References buffer, crypto_sign_ed25519_open, ssh_signature_struct::ed25519_sig, ED25519_SIG_LEN, error, explicit_bzero, pubkey, rc, SAFE_FREE, SSH_ERROR, SSH_OK.
Referenced by pki_verify_data_signature.
int pki_ed25519_key_cmp(const ssh_key k1, const ssh_key k2, enum ssh_keycmp_e what)
References ED25519_KEY_LEN, ssh_key_struct::ed25519_privkey, ssh_key_struct::ed25519_pubkey, SSH_KEY_CMP_PRIVATE, SSH_KEY_CMP_PUBLIC.
Referenced by ssh_key_cmp.
int pki_ed25519_key_dup(ssh_key new, const ssh_key key)
References ED25519_KEY_LEN, key, SAFE_FREE, SSH_ERROR, SSH_OK.
Referenced by pki_key_dup.
int pki_ed25519_public_key_to_blob(ssh_buffer buffer, ssh_key key)
References buffer, ED25519_KEY_LEN, key, rc, ssh_buffer_pack, SSH_ERROR.
Referenced by pki_publickey_to_blob.
ssh_string pki_ed25519_signature_to_blob(ssh_signature sig)
References ssh_signature_struct::ed25519_sig, ED25519_SIG_LEN, ssh_signature_struct::raw_sig, ssh_string_data, ssh_string_fill, ssh_string_len, ssh_string_new.
Referenced by pki_signature_to_blob.
int pki_signature_from_ed25519_blob(ssh_signature sig, ssh_string sig_blob)
References ssh_signature_struct::ed25519_sig, ED25519_SIG_LEN, ssh_signature_struct::raw_sig, SSH_ERROR, SSH_LOG, SSH_LOG_WARN, SSH_OK, ssh_string_copy, ssh_string_data, ssh_string_len.
Referenced by pki_signature_from_blob.
int pki_privkey_build_ed25519(ssh_key key, ssh_string pubkey, ssh_string privkey)
References ED25519_KEY_LEN, error, key, privkey, pubkey, SAFE_FREE, SSH_ERROR, SSH_LOG, SSH_LOG_WARN, SSH_OK, ssh_string_data, ssh_string_len.
Referenced by pki_import_privkey_buffer.
ssh_key ssh_pki_openssh_pubkey_import(const char *text_key)
References ssh_pki_openssh_import.
Referenced by ssh_pki_import_pubkey_file.
ssh_key ssh_pki_openssh_privkey_import(const char *text_key, const char *passphrase, ssh_auth_callback auth_fn, void *auth_data)
References ssh_pki_openssh_import.
Referenced by ssh_pki_import_privkey_base64.
ssh_string ssh_pki_openssh_privkey_export(const ssh_key privkey, const char *passphrase, ssh_auth_callback auth_fn, void *auth_data)
References bin_to_base64, buffer, error, explicit_bzero, OPENSSH_AUTH_MAGIC, OPENSSH_HEADER_BEGIN, OPENSSH_HEADER_END, pki_openssh_export_privkey_blob, pki_private_key_encrypt, pki_publickey_to_blob, privkey, rc, SAFE_FREE, ssh_buffer_add_u8, SSH_BUFFER_FREE, ssh_buffer_get, ssh_buffer_get_data, ssh_buffer_get_len, ssh_buffer_new, ssh_buffer_pack, ssh_buffer_reinit, SSH_ERROR, ssh_get_random, SSH_KEYTYPE_ED25519, SSH_LOG, SSH_LOG_INFO, SSH_LOG_WARN, SSH_OK, ssh_string_data, SSH_STRING_FREE, ssh_string_new.
Referenced by ssh_pki_export_privkey_base64, ssh_pki_export_privkey_file.
int pki_uri_import(const char *uri_name, ssh_key *key, enum ssh_key_e key_type)
References is_ecdsa_key_type, key, SSH_ERROR, SSH_KEY_CMP_PRIVATE, SSH_KEY_CMP_PUBLIC, SSH_KEY_FLAG_PKCS11_URI, SSH_KEY_FLAG_PRIVATE, SSH_KEY_FLAG_PUBLIC, ssh_key_free, ssh_key_new, SSH_KEY_PRIVATE, ssh_key_type_to_char, SSH_KEYTYPE_RSA, SSH_KEYTYPE_UNKNOWN, SSH_LOG, SSH_LOG_INFO, SSH_LOG_WARN, SSH_OK.
Referenced by ssh_pki_import_privkey_file, ssh_pki_import_pubkey_file.