pki_ed25519.c
int pki_key_generate_ed25519(ssh_key key)
References crypto_sign_ed25519_keypair, error, key, rc, SAFE_FREE, SSH_ERROR, SSH_OK.
Referenced by ssh_pki_generate.
int pki_ed25519_sign(const ssh_key privkey, ssh_signature sig, const unsigned char *hash, size_t hlen)
References buffer, crypto_sign_ed25519, ssh_signature_struct::ed25519_sig, ED25519_SIG_LEN, error, privkey, rc, SAFE_FREE, SSH_ERROR, SSH_OK.
Referenced by pki_do_sign_hash.
int pki_ed25519_verify(const ssh_key pubkey, ssh_signature sig, const unsigned char *hash, size_t hlen)
References buffer, crypto_sign_ed25519_open, ssh_signature_struct::ed25519_sig, ED25519_SIG_LEN, error, explicit_bzero, pubkey, rc, SAFE_FREE, SSH_ERROR, SSH_OK.
Referenced by pki_verify_data_signature.