priv.h
bswap_32
PRIdS
_XCLOSESOCKET
MAX_PACKET_LEN
ERROR_BUFFERLEN
CLIENT_BANNER_SSH2
KBDINT_MAX_PROMPT
MAX_BUF_SIZE
LIBSSH_THREAD
LIBSSH_MEM_PROTECTION
SSH_LOG
ssh_set_error
ssh_set_error_oom
ssh_set_error_invalid
MIN
MAX
SAFE_FREE
Free memory space
ZERO_STRUCT
Zero a structure
ZERO_STRUCTP
Zero a structure given a pointer to the structure
ARRAY_SIZE
Get the size of an array
discard_const
This is a hack to fix warnings. The idea is to use this everywhere that we get the "discarding const" warning by the compiler. That doesn't actually fix the real issue, but marks the place and you can search the code for discard_const. Please use this macro only when there is no other way to fix the warning. We should use this function in only in a very few places. Also, please call this via the discard_const_p() macro interface, as that makes the return type safe.
discard_const_p
Type-safe version of discard_const
VA_APPLY_VARIADIC_MACRO
Get the argument cound of variadic arguments
__VA_NARG__
__VA_NARG_
__VA_ARG_N
__RSEQ_N
CLOSE_SOCKET
htonll
ntohll
FALL_THROUGH
__attr_unused__
UNUSED_PARAM
UNUSED_VAR
ssh_digest_e
char* strndup(const char *s, size_t n)
References s.
Referenced by ssh_config_parse_uri, ssh_get_b64_unpadded, ssh_pki_export_privkey_base64.
int ssh_get_key_params(ssh_session session, ssh_key *privkey, enum ssh_digest_e *digest)
References ssh_session_struct::dsa_key, ssh_session_struct::ecdsa_key, ssh_session_struct::ed25519_key, ssh_session_struct::hostkey, ssh_session_struct::hostkey_digest, privkey, pubkey, rc, ssh_session_struct::rsa_key, session, ssh_session_struct::srv, ssh_dh_import_next_pubkey_blob, SSH_FATAL, ssh_key_free, SSH_KEYTYPE_DSS, SSH_KEYTYPE_ECDSA_P256, SSH_KEYTYPE_ECDSA_P384, SSH_KEYTYPE_ECDSA_P521, SSH_KEYTYPE_ED25519, SSH_KEYTYPE_RSA, SSH_KEYTYPE_RSA1, SSH_KEYTYPE_UNKNOWN, SSH_OK, ssh_pki_export_privkey_to_pubkey, ssh_pki_export_pubkey_blob, ssh_set_error, ssh_set_error_oom, SSH_STRING_FREE.
void ssh_log_function(int verbosity, const char *function, const char *buffer)
References buffer, ssh_get_log_callback, ssh_get_log_userdata, ssh_log_stderr, verbosity.
Referenced by _ssh_log, _ssh_set_error, ssh_log, ssh_log_common.
void ssh_log_common(struct ssh_common_struct *common, int verbosity, const char *function, const char *format,...) PRINTF_ATTRIBUTE(4
void _ssh_set_error(void *error, int code, const char *function, const char *descr,...) PRINTF_ATTRIBUTE(4
void _ssh_set_error_oom(void *error, const char *function)
References error, error_struct::error_buffer, error_struct::error_code, SSH_FATAL.
void _ssh_set_error_invalid(void *error, const char *function)
References _ssh_set_error, error, SSH_FATAL.
void ssh_reset_error(void *error)
References error, ssh_common_struct::error, error_struct::error_buffer, error_struct::error_code, ZERO_STRUCT.
Referenced by SSH_PACKET_CALLBACK.
int ssh_send_banner(ssh_session session, int is_server)
References buffer, CLIENT_BANNER_SSH2, ssh_session_struct::clientbanner, ssh_session_struct::custombanner, ssh_session_struct::opts, rc, ssh_session_struct::serverbanner, session, ssh_session_struct::socket, SSH_ERROR, SSH_OK, ssh_socket_write.
Referenced by ssh_client_connection_callback, ssh_handle_key_exchange.
socket_t ssh_connect_host_nonblocking(ssh_session session, const char *host, const char *bind_addr, int port)
References getai, host, ssh_session_struct::nodelay, ssh_session_struct::opts, port, rc, s, session, set_tcp_nodelay, ssh_connect_socket_close, SSH_FATAL, SSH_LOG, SSH_LOG_PACKET, ssh_set_error, ssh_socket_set_nonblocking.
Referenced by ssh_socket_connect.
ssh_buffer base64_to_bin(const char *source)
References _base64_to_bin, buffer, error, get_equals, SAFE_FREE, ssh_buffer_add_data, SSH_BUFFER_FREE, ssh_buffer_new, ssh_buffer_set_secure.
Referenced by check_public_key, match_hashed_host, match_hashed_hostname, ssh_pki_import_pubkey_base64, ssh_pki_openssh_import.
uint8_t* bin_to_base64(const uint8_t *source, size_t len)
References _bin_to_base64.
Referenced by ssh_get_b64_unpadded, ssh_pki_export_pubkey_base64, ssh_pki_openssh_privkey_export, ssh_publickey_to_file.
int compress_buffer(ssh_session session, ssh_buffer buf)
References ssh_session_struct::compressionlevel, gzip_compress, ssh_session_struct::opts, session, ssh_buffer_add_data, SSH_BUFFER_FREE, ssh_buffer_get, ssh_buffer_get_len, ssh_buffer_reinit.
Referenced by packet_send2.
int decompress_buffer(ssh_session session, ssh_buffer buf, size_t maxlen)
References gzip_decompress, session, ssh_buffer_add_data, SSH_BUFFER_FREE, ssh_buffer_get, ssh_buffer_get_len, ssh_buffer_reinit.
Referenced by ssh_packet_socket_callback.
int match_pattern_list(const char *string, const char *pattern, unsigned int len, int dolower)
References match_pattern, MAX_MATCH_RECURSION, pattern, sub.
Referenced by match_hostname, ssh_config_match.
int match_hostname(const char *host, const char *pattern, unsigned int len)
References host, match_pattern_list, pattern.
Referenced by ssh_config_parse_line, ssh_is_server_known, ssh_known_hosts_parse_line.
int ssh_connector_set_event(ssh_connector connector, ssh_event event)
References error, ssh_connector_struct::event, ssh_connector_struct::in_available, ssh_connector_struct::in_channel, ssh_connector_struct::in_fd, ssh_connector_struct::in_poll, ssh_connector_struct::out_channel, ssh_connector_struct::out_fd, ssh_connector_struct::out_poll, ssh_connector_struct::out_wontblock, POLLERR, POLLIN, POLLOUT, rc, ssh_connector_struct::session, session, ssh_channel_get_session, ssh_channel_poll_timeout, ssh_channel_window_size, ssh_connector_fd_cb, SSH_ERROR, ssh_event_add_poll, ssh_event_add_session, SSH_FATAL, SSH_INVALID_SOCKET, SSH_OK, ssh_poll_new, ssh_set_error.
Referenced by ssh_event_add_connector.
int ssh_connector_remove_event(ssh_connector connector)
References ssh_connector_struct::event, ssh_connector_struct::in_channel, ssh_connector_struct::in_poll, ssh_connector_struct::out_channel, ssh_connector_struct::out_poll, session, ssh_channel_get_session, ssh_event_remove_poll, ssh_event_remove_session, SSH_OK, ssh_poll_free.
Referenced by ssh_connector_free, ssh_event_remove_connector.
void explicit_bzero(void *s, size_t n)
References s.
Referenced by bcrypt_hash, bcrypt_pbkdf, buffer_shift, crypto_free, pki_ed25519_verify, pki_private_key_decrypt, pki_private_key_encrypt, pki_sign_data, pki_signature_from_dsa_blob, pki_signature_from_ecdsa_blob, pki_signature_from_rsa_blob, realloc_buffer, ssh_buffer_free, ssh_buffer_reinit, ssh_buffer_unpack_va, ssh_free, ssh_getpass, ssh_gets, ssh_kbdint_clean, ssh_kbdint_free, ssh_key_clean, ssh_message_free, ssh_packet_encrypt, ssh_pki_openssh_privkey_export, ssh_pki_signature_verify, ssh_string_burn, ssh_tokens_free, ssh_userauth_kbdint_setanswer, torture_packet.
void ssh_agent_state_free(void *data)
References ssh_key_free, SSH_STRING_FREE_CHAR, ssh_agent_state_struct::state.
Referenced by ssh_free, ssh_userauth_agent.