proxy.c
USER
PASSWORD
int authenticated
Referenced by auth_gssapi_mic, auth_password, main.
int tries
Referenced by auth_password.
int error
Referenced by _ssh_set_error, _ssh_set_error_invalid, _ssh_set_error_oom, auth_password, base64_to_bin, benchmarks_async_sftp_down, benchmarks_raw_down, benchmarks_raw_up, benchmarks_scp_down, benchmarks_scp_up, benchmarks_ssh_latency, benchmarks_sync_sftp_down, benchmarks_sync_sftp_up, channel_request, channel_write_common, connect_host, do_connect, grow_window, main, match_hashed_hostname, packet_send2, pki_dsa_signature_to_blob, pki_ecdsa_signature_to_blob, pki_ed25519_sign, pki_ed25519_verify, pki_key_generate_ed25519, pki_key_to_pkey, pki_privkey_build_ed25519, pki_signature_from_blob, pki_signature_from_dsa_blob, pki_signature_from_ecdsa_blob, ssh_channel_cancel_forward, ssh_channel_change_pty_size, ssh_channel_close, ssh_channel_listen_forward, ssh_channel_open_forward, ssh_channel_open_forward_unix, ssh_channel_request_env, ssh_channel_request_exec, ssh_channel_request_pty_size, ssh_channel_request_send_break, ssh_channel_request_send_signal, ssh_channel_request_subsystem, ssh_channel_request_x11, ssh_channel_send_eof, ssh_client_connection_callback, ssh_client_dh_init, ssh_client_dhgex_init, ssh_config_parse_uri, ssh_connector_set_event, ssh_dh_init, ssh_dh_keypair_gen_keys, ssh_disconnect, ssh_generate_session_keys, ssh_get_error, ssh_get_error_code, ssh_global_request, ssh_known_hosts_get_algorithms, ssh_known_hosts_read_entries, ssh_log_hexdump, ssh_make_sessionid, ssh_message_global_request_reply_default, ssh_message_global_request_reply_success, ssh_message_handle_channel_request, ssh_message_reply_default, SSH_PACKET_CALLBACK, ssh_packet_socket_callback, ssh_pki_generate, ssh_pki_openssh_privkey_export, ssh_quote_file_name, ssh_reset_error, ssh_scp_new, ssh_scp_pull_request, ssh_scp_push_directory, ssh_scp_push_file64, ssh_send_debug, ssh_send_ignore, ssh_send_kex, ssh_server_connection_callback, ssh_server_send_extensions, ssh_tokenize, ssh_userauth_privatekey_file, upload_script.
ssh_channel chan
Referenced by channel_from_msg, channel_new_session_cb, channel_protocol_select, main, new_session_channel, ssh_message_channel_request_open_reply_accept, ssh_message_channel_request_open_reply_accept_channel.
char* username
Referenced by auth_gssapi_mic, main, ssh_config_parse_proxy_jump, ssh_config_parse_uri, ssh_userauth_agent, ssh_userauth_agent_pubkey, ssh_userauth_agent_publickey, ssh_userauth_kbdint_init, ssh_userauth_list, ssh_userauth_none, ssh_userauth_offer_pubkey, ssh_userauth_password, ssh_userauth_privatekey_file, ssh_userauth_pubkey, ssh_userauth_publickey, ssh_userauth_publickey_auto, ssh_userauth_try_publickey, ssh::Session::userauthKbdint.
ssh_gssapi_creds client_creds
Referenced by auth_gssapi_mic, main.
struct ssh_channel_callbacks_struct channel_cb
Referenced by channel_open, default_handle_session_cb, handle_kbdint_session_cb, handle_session, new_session_channel, test_ssh_channel_request_x11.
static int auth_password(ssh_session session, const char *user, const char *password, void *userdata)
References authenticated, error, PASSWORD, session, SSH_AUTH_DENIED, SSH_AUTH_SUCCESS, ssh_disconnect, tries, USER, user.
Referenced by main.
static int auth_gssapi_mic(ssh_session session, const char *user, const char *principal, void *userdata)
References authenticated, client_creds, session, SSH_AUTH_SUCCESS, ssh_gssapi_get_creds, user, username.
Referenced by main.
static int pty_request(ssh_session session, ssh_channel channel, const char *term, int x, int y, int px, int py, void *userdata)
References session.
static int shell_request(ssh_session session, ssh_channel channel, void *userdata)
static ssh_channel new_session_channel(ssh_session session, void *userdata)
References chan, channel_cb, session, ssh_callbacks_init, ssh_channel_new, ssh_set_channel_callbacks, ssh_channel_callbacks_struct::userdata.
Referenced by main.
int main(int argc, char **argv)
References argp, auth_gssapi_mic, auth_password, authenticated, cb, chan, client_creds, error, host, mainloop, new_session_channel, rc, session, SSH_AUTH_METHOD_GSSAPI_MIC, SSH_AUTH_METHOD_PASSWORD, SSH_AUTH_SUCCESS, ssh_bind_accept, ssh_bind_free, ssh_bind_listen, ssh_bind_new, SSH_BIND_OPTIONS_RSAKEY, ssh_bind_options_set, ssh_callbacks_init, ssh_channel_read, ssh_channel_write, ssh_connect, ssh_disconnect, SSH_ERROR, ssh_event_add_session, ssh_event_dopoll, ssh_event_new, ssh_finalize, ssh_get_error, ssh_gssapi_set_creds, ssh_handle_key_exchange, ssh_new, SSH_OK, SSH_OPTIONS_HOST, ssh_options_set, SSH_OPTIONS_USER, ssh_set_auth_methods, ssh_set_server_callbacks, ssh_userauth_gssapi, ssh_userauth_none, ssh_callbacks_struct::userdata, username.