samplesshd-kbdint.c
SSHD_USER
SSHD_PASSWORD
KEYS_FOLDER
int port
Referenced by main.
bool authenticated
Referenced by auth_password, kbdint_check_response, main.
const char* name
Referenced by auth_kbdint, authenticate, authenticate_kbdint, channel_request_env, crypt_set_algorithms2, get_cipher, hash_hostname, main, pki_private_key_decrypt, pki_private_key_encrypt, ssh::Channel::requestEnv, sftp_reply_name, sftp_reply_names_add, sftp_test, ssh_channel_request_env, ssh_get_local_username, ssh_hmac_type_to_string, ssh_message_auth_interactive_request, SSH_PACKET_CALLBACK, ssh_print_bignum, ssh_scp_pull_request, ssh_type_from_name.
const char* instruction
Referenced by auth_kbdint, authenticate, authenticate_kbdint, kbdint_check_response, ssh_message_auth_interactive_request.
const char* prompts[2][2]
Referenced by authenticate, kbdint_check_response, ssh_message_auth_interactive_request.
char echo[][]
Referenced by _torture_auth_kbdint, auth_callback, auth_kbdint, authenticate, authenticate_kbdint, myauthcallback, ssh_getpass, ssh_message_auth_interactive_request, ssh_userauth_kbdint_getprompt.
static int auth_password(const char *user, const char *password)
References authenticated, SSHD_PASSWORD, SSHD_USER, user.
Referenced by authenticate.
static int kbdint_check_response(ssh_session session)
References authenticated, instruction, prompts, session, ssh_userauth_kbdint_getanswer, ssh_userauth_kbdint_getnanswers.
Referenced by authenticate.
static int authenticate(ssh_session session)
References auth_password, echo, instruction, kbdint_check_response, name, prompts, session, SSH_AUTH_METHOD_INTERACTIVE, SSH_AUTH_METHOD_NONE, SSH_AUTH_METHOD_PASSWORD, ssh_message_auth_interactive_request, ssh_message_auth_kbdint_is_response, ssh_message_auth_password, ssh_message_auth_reply_success, ssh_message_auth_set_methods, ssh_message_auth_user, ssh_message_free, ssh_message_get, ssh_message_reply_default, ssh_message_subtype, ssh_message_type, SSH_REQUEST_AUTH.
Referenced by do_connect, main.
int main(int argc, char **argv)
References argp, authenticate, authenticated, chan, cleanup_pcap, KEYS_FOLDER, port, session, set_pcap, shell, ssh_bind_accept, ssh_bind_free, ssh_bind_listen, ssh_bind_new, SSH_BIND_OPTIONS_DSAKEY, SSH_BIND_OPTIONS_RSAKEY, ssh_bind_options_set, ssh_channel_close, ssh_channel_read, SSH_CHANNEL_REQUEST_SHELL, SSH_CHANNEL_SESSION, ssh_channel_write, ssh_disconnect, SSH_ERROR, ssh_finalize, ssh_get_error, ssh_handle_key_exchange, ssh_message_channel_request_open_reply_accept, ssh_message_channel_request_reply_success, ssh_message_free, ssh_message_get, ssh_message_reply_default, ssh_message_subtype, ssh_message_type, ssh_new, SSH_REQUEST_CHANNEL, SSH_REQUEST_CHANNEL_OPEN, SSHD_PASSWORD, SSHD_USER.