sc25519.c
const uint32_t m[32][32]
Referenced by barrett_reduce, chacha_encrypt_bytes, crypto_sign_ed25519, crypto_sign_ed25519_open, fe25519_freeze, poly1305_auth, reduce_add_sub, ssh_dh_is_known_group.
const uint32_t mu[33][33]
Referenced by barrett_reduce.
static uint32_t lt(uint32_t a, uint32_t b)
References generate.a.
Referenced by barrett_reduce, reduce_add_sub.
static void reduce_add_sub(sc25519 *r)
References lt, m, sc25519::v.
Referenced by barrett_reduce, sc25519_add.
static void barrett_reduce(sc25519 *r, const uint32_t x[64])
References lt, m, mu, reduce_add_sub, sc25519::v.
Referenced by sc25519_from32bytes, sc25519_from64bytes, sc25519_mul.
void sc25519_from32bytes(sc25519 *r, const unsigned char x[32])
References barrett_reduce.
void shortsc25519_from16bytes(shortsc25519 *r, const unsigned char x[16])
References shortsc25519::v.
void sc25519_from64bytes(sc25519 *r, const unsigned char x[64])
References barrett_reduce.
void sc25519_from_shortsc(sc25519 *r, const shortsc25519 *x)
References shortsc25519::v, sc25519::v.
Referenced by sc25519_mul_shortsc.
void sc25519_to32bytes(unsigned char r[32], const sc25519 *x)
References sc25519::v.
int sc25519_iszero_vartime(const sc25519 *x)
References sc25519::v.
int sc25519_isshort_vartime(const sc25519 *x)
References sc25519::v.
int sc25519_lt_vartime(const sc25519 *x, const sc25519 *y)
References sc25519::v.
void sc25519_add(sc25519 *r, const sc25519 *x, const sc25519 *y)
References reduce_add_sub, sc25519::v.
void sc25519_sub_nored(sc25519 *r, const sc25519 *x, const sc25519 *y)
References sc25519::v.
void sc25519_mul(sc25519 *r, const sc25519 *x, const sc25519 *y)
References barrett_reduce, sc25519::v.
Referenced by sc25519_mul_shortsc.
void sc25519_mul_shortsc(sc25519 *r, const sc25519 *x, const shortsc25519 *y)
References sc25519_from_shortsc, sc25519_mul.
void sc25519_window3(signed char r[85], const sc25519 *s)
References s.
void sc25519_window5(signed char r[51], const sc25519 *s)
References s.
void sc25519_2interleave2(unsigned char r[127], const sc25519 *s1, const sc25519 *s2)
References sc25519::v.