scp.h
ssh_scp_states
int ssh_scp_read_string(ssh_scp scp, char *buffer, size_t len)
Read a string on a channel, terminated by ' '.
scp The scp handle. buffer A pointer to a buffer to place the string. len The size of the buffer in bytes. If the string is bigger than len-1, only len-1 bytes are read and the string is null-terminated. SSH_OK if the string was read, SSH_ERROR if an error occured while reading.
References buffer, ssh_scp_struct::channel, ssh_scp_struct::session, ssh_channel_read, SSH_ERROR, SSH_FATAL, SSH_OK, ssh_set_error.
Referenced by ssh_scp_pull_request, ssh_scp_response.
int ssh_scp_integer_mode(const char *mode)
Convert a scp text mode to an integer.
mode The mode to convert, e.g. "0644". An integer value, e.g. 420 for "0644".
Referenced by ssh_scp_pull_request.
char* ssh_scp_string_mode(int mode)
Convert a unix mode into a scp string.
mode The mode to convert, e.g. 420 or 0644. A pointer to a malloc'ed string containing the scp mode, e.g. "0644".
References buffer.
Referenced by ssh_scp_push_directory, ssh_scp_push_file64.
int ssh_scp_response(ssh_scp scp, char **response)
References ssh_scp_struct::channel, rc, ssh_scp_struct::session, ssh_channel_read, SSH_ERROR, SSH_FATAL, SSH_LOG, SSH_LOG_RARE, SSH_REQUEST_DENIED, SSH_SCP_ERROR, ssh_scp_read_string, ssh_set_error, ssh_scp_struct::state.
Referenced by ssh_scp_init, ssh_scp_leave_directory, ssh_scp_push_directory, ssh_scp_push_file64, ssh_scp_read, ssh_scp_write.