scp_download.c
int verbosity
Referenced by main, opts.
const char* createcommand
Referenced by create_files.
char* host
Referenced by main, opts.
static void usage(const char *argv0)
References ssh_version.
Referenced by opts.
static int opts(int argc, char **argv)
References host, usage, verbosity.
Referenced by main, pkd_exec_hello.
static void create_files(ssh_session session)
References buffer, createcommand, rc, session, ssh_channel_close, ssh_channel_free, ssh_channel_is_eof, ssh_channel_new, ssh_channel_open_session, ssh_channel_read, ssh_channel_request_exec, ssh_get_error, SSH_OK.
Referenced by main.
static int fetch_files(ssh_session session)
References buffer, session, SSH_ERROR, ssh_get_error, SSH_OK, ssh_scp_accept_request, ssh_scp_close, ssh_scp_free, ssh_scp_init, ssh_scp_new, ssh_scp_pull_request, SSH_SCP_READ, ssh_scp_read, SSH_SCP_RECURSIVE, SSH_SCP_REQUEST_ENDDIR, SSH_SCP_REQUEST_EOF, ssh_scp_request_get_filename, ssh_scp_request_get_permissions, ssh_scp_request_get_size, ssh_scp_request_get_warning, SSH_SCP_REQUEST_NEWDIR, SSH_SCP_REQUEST_NEWFILE, SSH_SCP_REQUEST_WARNING.
Referenced by main.
int main(int argc, char **argv)
References connect_ssh, create_files, fetch_files, host, opts, session, ssh_disconnect, ssh_finalize, ssh_free, verbosity.