session.c
FIRST_CHANNEL
ssh_session ssh_new(void)
Create a new ssh session.
A new ssh_session pointer, NULL on error.
References ssh_session_struct::agent, ssh_session_struct::alive, ssh_session_struct::auth, ssh_session_struct::compressionlevel, crypto_new, ssh_session_struct::dh_handshake_state, DH_STATE_INIT, ssh_session_struct::fd, FIRST_CHANNEL, ssh_session_struct::flags, ssh_session_struct::global_req_state, ssh_session_struct::identity, ssh_session_struct::in_buffer, ssh_session_struct::maxchannel, ssh_session_struct::next_crypto, ssh_session_struct::nodelay, ssh_session_struct::opts, ssh_session_struct::out_buffer, ssh_session_struct::out_queue, ssh_session_struct::packet_state, PACKET_STATE_INIT, ssh_session_struct::pending_call_state, ssh_session_struct::port, rc, ssh_session_struct::service_state, session, ssh_session_struct::session_state, ssh_session_struct::socket, ssh_agent_new, SSH_AUTH_SERVICE_NONE, SSH_AUTH_STATE_NONE, ssh_buffer_new, SSH_CHANNEL_REQ_STATE_NONE, SSH_ERROR, ssh_free, ssh_list_append, ssh_list_new, SSH_OPT_FLAG_GSSAPI_AUTH, SSH_OPT_FLAG_KBDINT_AUTH, SSH_OPT_FLAG_PASSWORD_AUTH, SSH_OPT_FLAG_PUBKEY_AUTH, SSH_PENDING_CALL_NONE, SSH_SESSION_STATE_NONE, ssh_set_blocking, ssh_socket_new, ssh_session_struct::state, ssh_session_struct::StrictHostKeyChecking, ssh_session_struct::supported_methods.
Referenced by check_message_in_all_states, connect_host, connect_ssh, LLVMFuzzerTestOneInput, main, pkd_exec_hello, run_server, ssh::Session::Session, session_setup, setup, setup_both_keys_passphrase, setup_config_files, setup_rsa_key, ssh_client, ssh_options_copy, ssh_server, test_ssh_channel_request_x11, thread_pki_rsa_generate_key, torture_ecdsa_sign_verify_uri, torture_knownhosts_algorithms, torture_knownhosts_algorithms_global, torture_knownhosts_algorithms_negative, torture_knownhosts_algorithms_wanted, torture_knownhosts_conflict, torture_knownhosts_get_algorithms_names, torture_knownhosts_host_exists, torture_knownhosts_host_exists_global, torture_knownhosts_other_auto, torture_knownhosts_port, torture_knownhosts_unknown, torture_packet, torture_packet_filter_check_unfiltered, torture_pki_dsa_cert_verify, torture_pki_dsa_generate_key, torture_pki_ecdsa_cert_verify, torture_pki_ed25519_cert_verify, torture_pki_ed25519_generate_key, torture_pki_ed25519_verify, torture_pki_ed25519_verify_bad, torture_pki_generate_key_ecdsa, torture_pki_rsa_generate_key, torture_pki_rsa_sha2, torture_pki_sign_verify_uri, torture_pki_verify_mismatch, torture_run_tests, torture_ssh_session.
void ssh_free(ssh_session session)
Deallocate a SSH session handle.
session The SSH session to free. ssh_disconnect() ssh_new()
References ssh_session_struct::agent, ssh_session_struct::agent_state, ssh_session_struct::auth, ssh_session_struct::auto_state, ssh_session_struct::banner, ssh_session_struct::bindaddr, ssh_session_struct::channels, ssh_session_struct::clientbanner, crypto_free, ssh_session_struct::current_crypto, ssh_session_struct::custombanner, ssh_session_struct::default_poll_ctx, ssh_session_struct::dsa_key, ssh_session_struct::ecdsa_key, ssh_session_struct::ed25519_key, explicit_bzero, ssh_session_struct::global_knownhosts, ssh_session_struct::gss_client_identity, ssh_session_struct::gss_server_identity, ssh_session_struct::host, ssh_session_struct::identity, ssh_session_struct::in_buffer, ssh_session_struct::in_hashbuf, ssh_session_struct::kbdint, ssh_session_struct::knownhosts, ssh_session_struct::next_crypto, ssh_session_struct::opts, ssh_session_struct::out_buffer, ssh_session_struct::out_hashbuf, ssh_session_struct::out_queue, ssh_session_struct::packet_callbacks, ssh_session_struct::ProxyCommand, ssh_session_struct::pubkey_accepted_types, ssh_session_struct::rsa_key, SAFE_FREE, ssh_session_struct::serverbanner, session, ssh_session_struct::socket, ssh_session_struct::srv, ssh_agent_free, ssh_agent_state_free, SSH_BUFFER_FREE, ssh_channel_do_free, ssh_iterator_value, ssh_kbdint_free, SSH_KEX_METHODS, ssh_key_free, ssh_list_free, ssh_list_get_iterator, ssh_list_pop_head, ssh_list_remove, ssh_message_free, ssh_session_struct::ssh_message_list, ssh_poll_ctx_free, ssh_socket_free, ssh_session_struct::sshdir, ssh_session_struct::username, ssh_session_struct::wanted_methods.
Referenced by check_message_in_all_states, client_thread, connect_host, connect_ssh, LLVMFuzzerTestOneInput, main, pkd_exec_hello, run_server, session_teardown, setup_both_keys, ssh_new, ssh_options_copy, teardown, test_ssh_channel_request_x11, thread_pki_rsa_generate_key, torture_knownhosts_algorithms, torture_knownhosts_algorithms_global, torture_knownhosts_algorithms_negative, torture_knownhosts_algorithms_wanted, torture_knownhosts_conflict, torture_knownhosts_get_algorithms_names, torture_knownhosts_host_exists, torture_knownhosts_host_exists_global, torture_knownhosts_other_auto, torture_knownhosts_port, torture_knownhosts_unknown, torture_options_copy, torture_packet, torture_packet_filter_check_unfiltered, torture_pki_dsa_cert_verify, torture_pki_dsa_generate_key, torture_pki_ecdsa_cert_verify, torture_pki_ed25519_cert_verify, torture_pki_ed25519_generate_key, torture_pki_ed25519_verify, torture_pki_ed25519_verify_bad, torture_pki_generate_key_ecdsa, torture_pki_rsa_generate_key, torture_pki_rsa_sha2, torture_pki_sign_verify_uri, torture_pki_verify_mismatch, torture_ssh_analyze_banner, torture_ssh_session, ssh::Session::~Session.
const char* ssh_get_clientbanner(ssh_session session)
get the client banner
session The SSH session Returns the client banner string or NULL.
References ssh_session_struct::clientbanner, session.
const char* ssh_get_serverbanner(ssh_session session)
get the server banner
session The SSH session Returns the server banner string or NULL.
References ssh_session_struct::serverbanner, session.
Referenced by main.
const char* ssh_get_kex_algo(ssh_session session)
get the name of the current key exchange algorithm.
session The SSH session Returns the key exchange algorithm string or NULL.
References ssh_session_struct::current_crypto, ssh_crypto_struct::kex_type, session, SSH_KEX_CURVE25519_SHA256, SSH_KEX_CURVE25519_SHA256_LIBSSH_ORG, SSH_KEX_DH_GROUP14_SHA1, SSH_KEX_DH_GROUP16_SHA512, SSH_KEX_DH_GROUP18_SHA512, SSH_KEX_DH_GROUP1_SHA1, SSH_KEX_ECDH_SHA2_NISTP256, SSH_KEX_ECDH_SHA2_NISTP384, SSH_KEX_ECDH_SHA2_NISTP521.
const char* ssh_get_cipher_in(ssh_session session)
get the name of the input cipher for the given session.
session The SSH session. Returns cipher name or NULL.
References ssh_session_struct::current_crypto, ssh_crypto_struct::in_cipher, ssh_cipher_struct::name, session.
const char* ssh_get_cipher_out(ssh_session session)
get the name of the output cipher for the given session.
session The SSH session. Returns cipher name or NULL.
References ssh_session_struct::current_crypto, ssh_cipher_struct::name, ssh_crypto_struct::out_cipher, session.
const char* ssh_get_hmac_in(ssh_session session)
get the name of the input HMAC algorithm for the given session.
session The SSH session. Returns HMAC algorithm name or NULL if unknown.
References ssh_session_struct::current_crypto, ssh_crypto_struct::in_hmac_etm, session, ssh_hmac_type_to_string.
const char* ssh_get_hmac_out(ssh_session session)
get the name of the output HMAC algorithm for the given session.
session The SSH session. Returns HMAC algorithm name or NULL if unknown.
References ssh_session_struct::current_crypto, ssh_crypto_struct::out_hmac, ssh_crypto_struct::out_hmac_etm, session, ssh_hmac_type_to_string.
void ssh_silent_disconnect(ssh_session session)
Disconnect impolitely from a remote host by closing the socket.
Suitable if you forked and want to destroy this session. session The SSH session to disconnect.
References ssh_session_struct::alive, session, ssh_session_struct::socket, ssh_disconnect, ssh_socket_close.
Referenced by ssh::Session::silentDisconnect.
void ssh_set_blocking(ssh_session session, int blocking)
Set the session in blocking/nonblocking mode.
session The ssh session to change. blocking Zero for nonblocking mode.
References ssh_session_struct::flags, session, SSH_SESSION_FLAG_BLOCKING.
Referenced by my_fd_data_function, ssh_channel_read_nonblocking, ssh_channel_set_blocking, ssh_new, torture_auth_agent_nonblocking, torture_auth_autopubkey_nonblocking, torture_auth_kbdint_nonblocking, torture_auth_none_nonblocking, torture_auth_password_nonblocking, torture_auth_pubkey_types_ecdsa_nonblocking, torture_auth_pubkey_types_ed25519_nonblocking, torture_auth_pubkey_types_nonblocking, torture_connect_nonblocking.
int ssh_is_blocking(ssh_session session)
Return the blocking mode of libssh.
session The SSH session 0 if the session is nonblocking, 1 if the functions may block.
References ssh_session_struct::flags, session, SSH_SESSION_FLAG_BLOCKING.
Referenced by my_fd_data_function, ssh_channel_read_nonblocking, ssh_connect, ssh_handle_packets, ssh_handle_packets_termination.
static int ssh_flush_termination(void *c)
References session, ssh_session_struct::session_state, ssh_session_struct::socket, SSH_SESSION_STATE_ERROR, ssh_socket_buffered_write_bytes.
Referenced by ssh_blocking_flush.
int ssh_blocking_flush(ssh_session session, int timeout)
Blocking flush of the outgoing buffer.
session The SSH session timeout Set an upper limit on the time for which this function will block, in milliseconds. Specifying -1 means an infinite timeout. This parameter is passed to the poll() function. SSH_OK on success, SSH_AGAIN if timeout occurred, SSH_ERROR otherwise.
References rc, session, SSH_AGAIN, SSH_ERROR, ssh_flush_termination, ssh_handle_packets_termination.
Referenced by ssh_channel_flush.
int ssh_is_connected(ssh_session session)
Check if we are connected.
session The session to check if it is connected. 1 if we are connected, 0 if not.
References ssh_session_struct::alive, session.
Referenced by pkd_exec_hello, torture_ssh_session.
socket_t ssh_get_fd(ssh_session session)
Get the fd of a connection.
In case you'd need the file descriptor of the connection to the server/client. session The ssh session to use. The file descriptor of the connection, or -1 if it is not connected
References session, ssh_session_struct::socket, ssh_socket_get_fd.
Referenced by ssh::Session::getSocket, select_loop, torture_channel_read_error, torture_options_set_proxycommand_ssh, torture_options_set_proxycommand_ssh_stderr.
void ssh_set_fd_toread(ssh_session session)
Tell the session it has data to read on the file descriptor without blocking.
session The ssh session to use.
References session, ssh_session_struct::socket, ssh_socket_set_read_wontblock.
void ssh_set_fd_towrite(ssh_session session)
Tell the session it may write to the file descriptor without blocking.
session The ssh session to use.
References session, ssh_session_struct::socket, ssh_socket_set_write_wontblock.
Referenced by ssh_client_connection_callback.
void ssh_set_fd_except(ssh_session session)
Tell the session it has an exception to catch on the file descriptor.
session The ssh session to use.
References session, ssh_session_struct::socket, ssh_socket_set_except.
int ssh_handle_packets(ssh_session session, int timeout)
References ctx, ssh_session_struct::opts, POLLIN, rc, session, ssh_session_struct::session_state, ssh_session_struct::socket, SSH_ERROR, ssh_is_blocking, ssh_make_milliseconds, ssh_poll_add_events, ssh_poll_ctx_add, ssh_poll_ctx_dopoll, ssh_poll_get_ctx, ssh_poll_get_default_ctx, SSH_SESSION_STATE_ERROR, ssh_socket_get_poll_handle, SSH_TIMEOUT_USER, ssh_session_struct::timeout, ssh_session_struct::timeout_usec.
Referenced by channel_protocol_select, channel_read_buffer, ssh_channel_accept, ssh_channel_poll, ssh_execute_message_callbacks, ssh_handle_packets_termination, ssh_send_debug, ssh_send_ignore, test_algorithm, torture_rekey_send, torture_rekey_server_send, torture_rekey_time.
int ssh_handle_packets_termination(ssh_session session, long timeout, ssh_termination_function fct, void *user)
References ssh_session_struct::opts, session, SSH_AGAIN, SSH_ERROR, ssh_handle_packets, ssh_is_blocking, ssh_make_milliseconds, SSH_OK, SSH_TIMEOUT_DEFAULT, ssh_timeout_elapsed, SSH_TIMEOUT_INFINITE, SSH_TIMEOUT_NONBLOCKING, ssh_timeout_update, SSH_TIMEOUT_USER, ssh_timestamp_init, ssh_session_struct::timeout, ssh_session_struct::timeout_usec, user.
Referenced by channel_open, channel_request, channel_write_common, ssh_blocking_flush, ssh_channel_get_exit_status, ssh_channel_poll_timeout, ssh_channel_read_timeout, ssh_connect, ssh_global_request, ssh_handle_key_exchange, ssh_message_get, ssh_service_request, ssh_userauth_get_response.
int ssh_get_status(ssh_session session)
Get session status.
session The ssh session to use. A bitmask including SSH_CLOSED, SSH_READ_PENDING, SSH_WRITE_PENDING or SSH_CLOSED_ERROR which respectively means the session is closed, has data to read on the connection socket and session was closed due to an error.
References session, ssh_session_struct::session_state, ssh_session_struct::socket, SSH_CLOSED, SSH_CLOSED_ERROR, SSH_READ_PENDING, SSH_SESSION_STATE_DISCONNECTED, SSH_SESSION_STATE_ERROR, ssh_socket_get_status, SSH_WRITE_PENDING.
Referenced by default_handle_session_cb, handle_kbdint_session_cb, handle_session.
int ssh_get_poll_flags(ssh_session session)
Get poll flags for an external mainloop.
session The ssh session to use. A bitmask including SSH_READ_PENDING or SSH_WRITE_PENDING. For SSH_READ_PENDING, your invocation of poll() should include POLLIN. For SSH_WRITE_PENDING, your invocation of poll() should include POLLOUT.
References session, ssh_session_struct::socket, ssh_socket_get_poll_flags.
const char* ssh_get_disconnect_message(ssh_session session)
Get the disconnect message from the server.
session The ssh session to use. The message sent by the server along with the disconnect, or NULL in which case the reason of the disconnect may be found with ssh_get_error. ssh_get_error()
References ssh_session_struct::discon_msg, session, ssh_session_struct::session_state, SSH_FATAL, SSH_REQUEST_DENIED, SSH_SESSION_STATE_DISCONNECTED, ssh_set_error.
Referenced by ssh::Session::getDisconnectMessage.
int ssh_get_version(ssh_session session)
Get the protocol version of the session.
session The ssh session to use. The SSH version as integer, < 0 on error.
References session.
Referenced by ssh::Session::getVersion.
void ssh_socket_exception_callback(int code, int errno_code, void *user)
References session, ssh_session_struct::session_state, ssh_session_struct::ssh_connection_callback, SSH_FATAL, SSH_LOG, SSH_LOG_RARE, SSH_SESSION_STATE_ERROR, ssh_set_error, SSH_SOCKET_EXCEPTION_EOF, user.
Referenced by ssh_connect, ssh_handle_key_exchange.
int ssh_send_ignore(ssh_session session, const char *data)
Send a message that should be ignored.
session The SSH session data Data to be sent SSH_OK on success, SSH_ERROR otherwise.
References error, ssh_session_struct::out_buffer, rc, session, ssh_session_struct::socket, SSH2_MSG_IGNORE, ssh_buffer_pack, ssh_buffer_reinit, SSH_ERROR, ssh_handle_packets, SSH_OK, ssh_packet_send, ssh_set_error_oom, ssh_socket_is_open.
Referenced by test_algorithm, torture_rekey_send, torture_rekey_server_send, torture_rekey_time.
int ssh_send_debug(ssh_session session, const char *message, int always_display)
Send a debug message.
session The SSH session message Data to be sent always_display Message SHOULD be displayed by the server. It SHOULD NOT be displayed unless debugging information has been explicitly requested. SSH_OK on success, SSH_ERROR otherwise.
References error, ssh_session_struct::out_buffer, rc, session, ssh_session_struct::socket, SSH2_MSG_DEBUG, ssh_buffer_pack, ssh_buffer_reinit, SSH_ERROR, ssh_handle_packets, SSH_OK, ssh_packet_send, ssh_set_error_oom, ssh_socket_is_open.
void ssh_set_counters(ssh_session session, ssh_counter scounter, ssh_counter rcounter)
Set the session data counters.
This functions sets the counter structures to be used to calculate data which comes in and goes out through the session at different levels. structssh_counter_structscounter={ .in_bytes=0, .out_bytes=0, .in_packets=0, .out_packets=0 }; structssh_counter_structrcounter={ .in_bytes=0, .out_bytes=0, .in_packets=0, .out_packets=0 }; ssh_set_counters(session,&scounter,&rcounter); session The SSH session. scounter Counter for byte data handled by the session sockets. rcounter Counter for byte and packet data handled by the session, prior compression and SSH overhead.
References ssh_session_struct::raw_counter, session, ssh_session_struct::socket_counter.
int ssh_get_pubkey_hash(ssh_session session, unsigned char **hash)
DeprecatedUse ssh_get_publickey_hash()
References ctx, ssh_session_struct::current_crypto, MD5_DIGEST_LEN, md5_final, md5_init, md5_update, pubkey, rc, SAFE_FREE, ssh_crypto_struct::server_pubkey, session, SSH_ERROR, SSH_FATAL, ssh_get_server_publickey, ssh_key_free, SSH_OK, ssh_pki_export_pubkey_blob, ssh_set_error, ssh_string_data, SSH_STRING_FREE, ssh_string_len.
void ssh_clean_pubkey_hash(unsigned char **hash)
Deallocate the hash obtained by ssh_get_pubkey_hash.
This is required under Microsoft platform as this library might use a different C library than your software, hence a different heap. hash The buffer to deallocate. ssh_get_pubkey_hash()
References SAFE_FREE.
Referenced by verify_knownhost.
int ssh_get_server_publickey(ssh_session session, ssh_key *key)
Get the server public key from a session.
session The session to get the key from. key A pointer to store the allocated key. You need to free the key. SSH_OK on success, SSH_ERROR on errror. ssh_key_free()
References ssh_session_struct::current_crypto, key, pubkey, ssh_crypto_struct::server_pubkey, session, SSH_ERROR, ssh_key_dup, SSH_OK.
Referenced by ssh_get_pubkey_hash, ssh_get_publickey, verify_knownhost.
int ssh_get_publickey(ssh_session session, ssh_key *key)
DeprecatedUse ssh_get_server_publickey()
References key, session, ssh_get_server_publickey.
int ssh_get_publickey_hash(const ssh_key key, enum ssh_publickey_hash_type type, unsigned char **hash, size_t *hlen)
Allocates a buffer with the hash of the public key.
This function allows you to get a hash of the public key. You can then print this hash in a human-readable form to the user so that he is able to verify it. Use ssh_get_hexa() or ssh_print_hash() to display it. key The public key to create the hash for. type The type of the hash you want. hash A pointer to store the allocated buffer. It can be freed using ssh_clean_pubkey_hash(). hlen The length of the hash. 0 on success, -1 if an error occured. It is very important that you verify at some moment that the hash matches a known server. If you don't do it, cryptography wont help you at making things secure. OpenSSH uses SHA256 to print public key digests. ssh_session_update_known_hosts() ssh_get_hexa() ssh_print_hash() ssh_clean_pubkey_hash()
References ctx, key, MD5_DIGEST_LEN, md5_final, md5_init, md5_update, rc, sha1_final, sha1_init, sha1_update, sha256_final, sha256_init, sha256_update, SSH_ERROR, SSH_LOG, SSH_LOG_WARN, ssh_pki_export_pubkey_blob, SSH_PUBLICKEY_HASH_MD5, SSH_PUBLICKEY_HASH_SHA1, SSH_PUBLICKEY_HASH_SHA256, ssh_string_data, SSH_STRING_FREE, ssh_string_len.
Referenced by torture_md5_hash, torture_sha1_hash, torture_sha256_fingerprint, torture_sha256_hash, verify_knownhost.