session.h
SSH_SESSION_FLAG_BLOCKING
SSH_SESSION_FLAG_AUTHENTICATED
SSH_TIMEOUT_INFINITE
SSH_TIMEOUT_USER
SSH_TIMEOUT_DEFAULT
SSH_TIMEOUT_NONBLOCKING
SSH_OPT_FLAG_PASSWORD_AUTH
SSH_OPT_FLAG_PUBKEY_AUTH
SSH_OPT_FLAG_KBDINT_AUTH
SSH_OPT_FLAG_GSSAPI_AUTH
SSH_EXT_NEGOTIATION
SSH_EXT_SIG_RSA_SHA256
SSH_EXT_SIG_RSA_SHA512
ssh_session_state_e
ssh_dh_state_e
ssh_pending_call_e
typedef int(* ssh_termination_function) (void *user))(void *user)
int ssh_handle_packets(ssh_session session, int timeout)
References ctx, ssh_session_struct::opts, POLLIN, rc, session, ssh_session_struct::session_state, ssh_session_struct::socket, SSH_ERROR, ssh_is_blocking, ssh_make_milliseconds, ssh_poll_add_events, ssh_poll_ctx_add, ssh_poll_ctx_dopoll, ssh_poll_get_ctx, ssh_poll_get_default_ctx, SSH_SESSION_STATE_ERROR, ssh_socket_get_poll_handle, SSH_TIMEOUT_USER, ssh_session_struct::timeout, ssh_session_struct::timeout_usec.
Referenced by channel_protocol_select, channel_read_buffer, ssh_channel_accept, ssh_channel_poll, ssh_execute_message_callbacks, ssh_handle_packets_termination, ssh_send_debug, ssh_send_ignore, test_algorithm, torture_rekey_send, torture_rekey_server_send, torture_rekey_time.
int ssh_handle_packets_termination(ssh_session session, long timeout, ssh_termination_function fct, void *user)
References ssh_session_struct::opts, session, SSH_AGAIN, SSH_ERROR, ssh_handle_packets, ssh_is_blocking, ssh_make_milliseconds, SSH_OK, SSH_TIMEOUT_DEFAULT, ssh_timeout_elapsed, SSH_TIMEOUT_INFINITE, SSH_TIMEOUT_NONBLOCKING, ssh_timeout_update, SSH_TIMEOUT_USER, ssh_timestamp_init, ssh_session_struct::timeout, ssh_session_struct::timeout_usec, user.
Referenced by channel_open, channel_request, channel_write_common, ssh_blocking_flush, ssh_channel_get_exit_status, ssh_channel_poll_timeout, ssh_channel_read_timeout, ssh_connect, ssh_global_request, ssh_handle_key_exchange, ssh_message_get, ssh_service_request, ssh_userauth_get_response.
void ssh_socket_exception_callback(int code, int errno_code, void *user)
References session, ssh_session_struct::session_state, ssh_session_struct::ssh_connection_callback, SSH_FATAL, SSH_LOG, SSH_LOG_RARE, SSH_SESSION_STATE_ERROR, ssh_set_error, SSH_SOCKET_EXCEPTION_EOF, user.
Referenced by ssh_connect, ssh_handle_key_exchange.