sftp_priv.h
sftp_packet sftp_packet_read(sftp_session sftp)
Referenced by sftp_get_client_message.
ssize_t sftp_packet_write(sftp_session sftp, uint8_t type, ssh_buffer payload)
Referenced by sftp_reply_attr, sftp_reply_data, sftp_reply_handle, sftp_reply_name, sftp_reply_names, sftp_reply_status, sftp_send_client_message.
void sftp_packet_free(sftp_packet packet)
int buffer_add_attributes(ssh_buffer buffer, sftp_attributes attr)
Referenced by sftp_reply_attr, sftp_reply_name, sftp_reply_names_add.
sftp_attributes sftp_parse_attr(sftp_session session, ssh_buffer buf, int expectname)
Referenced by sftp_get_client_message.