knownhosts.c
static int hash_hostname(const char *name, unsigned char *salt, unsigned int salt_size, unsigned char **hash, unsigned int *hash_size)
References hmac_final, hmac_init, hmac_update, name, SSH_ERROR, SSH_HMAC_SHA1, SSH_OK.
Referenced by match_hashed_hostname.
static int match_hashed_hostname(const char *host, const char *hashed_host)
References base64_to_bin, error, hash_hostname, host, rc, SSH_BUFFER_FREE, ssh_buffer_get, ssh_buffer_get_len, SSH_OK.
Referenced by ssh_known_hosts_parse_line.
void ssh_knownhosts_entry_free(struct ssh_knownhosts_entry *entry)
Free an allocated ssh_knownhosts_entry.
Use SSH_KNOWNHOSTS_ENTRY_FREE() to set the pointer to NULL. entry The entry to free.
References ssh_knownhosts_entry::comment, ssh_knownhosts_entry::hostname, ssh_knownhosts_entry::publickey, SAFE_FREE, ssh_key_free, ssh_knownhosts_entry::unparsed.
Referenced by ssh_known_hosts_get_algorithms, ssh_known_hosts_get_algorithms_names, ssh_known_hosts_parse_line, ssh_known_hosts_read_entries.
static int known_hosts_read_line(FILE *fp, char *buf, size_t buf_size, size_t *buf_len, size_t *lineno)
Referenced by ssh_known_hosts_read_entries.
static int ssh_known_hosts_entries_compare(struct ssh_knownhosts_entry *k1, struct ssh_knownhosts_entry *k2)
References ssh_knownhosts_entry::hostname, ssh_knownhosts_entry::publickey, ssh_key_cmp, SSH_KEY_CMP_PUBLIC.
Referenced by ssh_known_hosts_read_entries.
static int ssh_known_hosts_read_entries(const char *match, const char *filename, struct ssh_list **entries)
References error, known_hosts_read_line, ssh_iterator::next, rc, SSH_AGAIN, SSH_ERROR, ssh_iterator_value, ssh_known_hosts_entries_compare, ssh_known_hosts_parse_line, ssh_knownhosts_entry_free, ssh_list_append, ssh_list_get_iterator, ssh_list_new, SSH_LOG, SSH_LOG_WARN, SSH_OK.
Referenced by ssh_known_hosts_get_algorithms, ssh_known_hosts_get_algorithms_names, torture_knownhosts_read_file.
static char* ssh_session_get_host_port(ssh_session session)
References host, ssh_session_struct::host, ssh_session_struct::opts, ssh_session_struct::port, SAFE_FREE, session, SSH_FATAL, ssh_hostport, ssh_lowercase, ssh_set_error, ssh_set_error_oom.
Referenced by ssh_known_hosts_get_algorithms, ssh_known_hosts_get_algorithms_names, ssh_session_export_known_hosts_entry.
struct ssh_list* ssh_known_hosts_get_algorithms(ssh_session session)
References error, ssh_session_struct::global_knownhosts, ssh_session_struct::knownhosts, ssh_iterator::next, ssh_session_struct::opts, ssh_knownhosts_entry::publickey, rc, SAFE_FREE, session, ssh_iterator_value, ssh_known_hosts_read_entries, ssh_knownhosts_entry_free, ssh_list_append, ssh_list_count, ssh_list_free, ssh_list_get_iterator, ssh_list_new, ssh_list_remove, SSH_OK, ssh_options_apply, SSH_REQUEST_DENIED, ssh_session_get_host_port, ssh_set_error, ssh_key_struct::type_c.
Referenced by torture_knownhosts_duplicate, torture_knownhosts_precheck.
static const char* ssh_known_host_sigs_from_hostkey_type(enum ssh_keytypes_e type)
References SSH_KEYTYPE_DSS, SSH_KEYTYPE_ECDSA_P256, SSH_KEYTYPE_ECDSA_P384, SSH_KEYTYPE_ECDSA_P521, SSH_KEYTYPE_ED25519, SSH_KEYTYPE_RSA, SSH_KEYTYPE_UNKNOWN, SSH_LOG, SSH_LOG_WARN.
Referenced by ssh_known_hosts_get_algorithms_names.
char* ssh_known_hosts_get_algorithms_names(ssh_session session)
References ssh_session_struct::global_knownhosts, ssh_session_struct::knownhosts, ssh_session_struct::opts, ssh_knownhosts_entry::publickey, rc, SAFE_FREE, session, ssh_iterator_value, ssh_known_host_sigs_from_hostkey_type, ssh_known_hosts_read_entries, ssh_knownhosts_entry_free, ssh_list_count, ssh_list_free, ssh_list_get_iterator, ssh_list_remove, ssh_options_apply, ssh_remove_duplicates, SSH_REQUEST_DENIED, ssh_session_get_host_port, ssh_set_error, ssh_key_struct::type.
Referenced by ssh_client_select_hostkeys, torture_knownhosts_get_algorithms_names.
int ssh_known_hosts_parse_line(const char *hostname, const char *line, struct ssh_knownhosts_entry **entry)
Parse a line from a known_hosts entry into a structure.
This parses an known_hosts entry into a structure with the key in a libssh consumeable form. You can use the PKI key function to further work with it. hostname The hostname to match the line to line The line to compare and parse if we have a hostname match. entry A pointer to store the the allocated known_hosts entry structure. The user needs to free the memory using SSH_KNOWNHOSTS_ENTRY_FREE(). SSH_OK on success, SSH_ERROR otherwise.
References ssh_knownhosts_entry::comment, ssh_knownhosts_entry::hostname, match_hashed_hostname, match_hostname, ssh_knownhosts_entry::publickey, rc, SAFE_FREE, SSH_AGAIN, SSH_ERROR, ssh_hostport, ssh_key_type_from_name, ssh_key_type_to_char, SSH_KEYTYPE_UNKNOWN, ssh_knownhosts_entry_free, SSH_LOG, SSH_LOG_WARN, SSH_OK, ssh_pki_import_pubkey_base64, ssh_knownhosts_entry::unparsed.
Referenced by ssh_known_hosts_read_entries, torture_knownhosts_parse_line_default_ed25519, torture_knownhosts_parse_line_ecdsa, torture_knownhosts_parse_line_hashed_ed25519, torture_knownhosts_parse_line_pattern_ed25519, torture_knownhosts_parse_line_port_ed25519, torture_knownhosts_parse_line_port_wildcard, torture_knownhosts_parse_line_rsa, torture_knownhosts_parse_line_standard_port.
enum ssh_known_hosts_e ssh_session_has_known_hosts_entry(ssh_session session)
Check if the set hostname and port matches an entry in known_hosts.
This check if the set hostname and port has an entry in the known_hosts file. You need to set at least the hostname using ssh_options_set(). session The session with with the values set to check. A ssh_known_hosts_e return value.
Referenced by torture_knownhosts_host_exists, torture_knownhosts_host_exists_global.
int ssh_session_export_known_hosts_entry(ssh_session session, char **pentry_string)
Export the current session information to a known_hosts string.
This exports the current information of a session which is connected so a ssh server into an entry line which can be added to a known_hosts file. session The session with information to export. pentry_string A pointer to a string to store the alloocated line of the entry. The user must free it using ssh_string_free_char(). SSH_OK on succcess, SSH_ERROR otherwise.
References ssh_session_struct::current_crypto, host, ssh_session_struct::host, ssh_session_struct::opts, rc, SAFE_FREE, session, ssh_dh_get_current_server_publickey, SSH_ERROR, SSH_FATAL, SSH_OK, ssh_pki_export_pubkey_base64, ssh_session_get_host_port, ssh_set_error, ssh_set_error_invalid, ssh_key_struct::type_c.
Referenced by ssh_known_hosts_check_server_key, ssh_write_knownhost, torture_knownhosts_export.
int ssh_session_update_known_hosts(ssh_session session)
Add the current connected server to the user known_hosts file.
This adds the currently connected server to the known_hosts file by appending a new line at the end. The global known_hosts file is considered read-only so it is not touched by this function. session The session to use to write the entry. SSH_OK on success, SSH_ERROR otherwise.
Referenced by ssh_is_server_known, torture_knownhosts_conflict, torture_knownhosts_new_file, torture_knownhosts_unknown, torture_knownhosts_write_and_verify, verify_knownhost, ssh::Session::writeKnownhost.
static enum ssh_known_hosts_e ssh_known_hosts_check_server_key(const char *hosts_entry, const char *filename, ssh_key server_key, struct ssh_knownhosts_entry **pentry)
References ssh_session_struct::knownhosts, ssh_session_struct::opts, rc, SAFE_FREE, session, ssh_dirname, SSH_ERROR, SSH_FATAL, ssh_mkdirs, SSH_OK, ssh_options_apply, ssh_session_export_known_hosts_entry, ssh_set_error.
enum ssh_known_hosts_e ssh_session_get_known_hosts_entry(ssh_session session, struct ssh_knownhosts_entry **pentry)
Get the known_hosts entry for the current connected session.
session The session to validate. pentry A pointer to store the allocated known hosts entry. SSH_KNOWN_HOSTS_OK: The server is known and has not changed. SSH_KNOWN_HOSTS_CHANGED: The server key has changed. Either you are under attack or the administrator changed the key. You HAVE to warn the user about a possible attack. SSH_KNOWN_HOSTS_OTHER: The server gave use a key of a type while we had an other type recorded. It is a possible attack. SSH_KNOWN_HOSTS_UNKNOWN: The server is unknown. User should confirm the public key hash is correct. SSH_KNOWN_HOSTS_NOT_FOUND: The known host file does not exist. The host is thus unknown. File will be created if host key is accepted. SSH_KNOWN_HOSTS_ERROR: There had been an eror checking the host. ssh_knownhosts_entry_free()
enum ssh_known_hosts_e ssh_session_get_known_hosts_entry_file(ssh_session session, const char *filename, struct ssh_knownhosts_entry **pentry)
Get the known_hosts entry for the current connected session from the given known_hosts file.
session The session to validate. filename The filename to parse. pentry A pointer to store the allocated known hosts entry. SSH_KNOWN_HOSTS_OK: The server is known and has not changed. SSH_KNOWN_HOSTS_CHANGED: The server key has changed. Either you are under attack or the administrator changed the key. You HAVE to warn the user about a possible attack. SSH_KNOWN_HOSTS_OTHER: The server gave use a key of a type while we had an other type recorded. It is a possible attack. SSH_KNOWN_HOSTS_UNKNOWN: The server is unknown. User should confirm the public key hash is correct. SSH_KNOWN_HOSTS_NOT_FOUND: The known host file does not exist. The host is thus unknown. File will be created if host key is accepted. SSH_KNOWN_HOSTS_ERROR: There had been an eror checking the host. ssh_knownhosts_entry_free()
enum ssh_known_hosts_e ssh_session_is_known_server(ssh_session session)
Check if the servers public key for the connected session is known.
This checks if we already know the public key of the server we want to connect to. This allows to detect if there is a MITM attach going on of if there have been changes on the server we don't know about. session The SSH to validate. SSH_KNOWN_HOSTS_OK: The server is known and has not changed. SSH_KNOWN_HOSTS_CHANGED: The server key has changed. Either you are under attack or the administrator changed the key. You HAVE to warn the user about a possible attack. SSH_KNOWN_HOSTS_OTHER: The server gave use a key of a type while we had an other type recorded. It is a possible attack. SSH_KNOWN_HOSTS_UNKNOWN: The server is unknown. User should confirm the public key hash is correct. SSH_KNOWN_HOSTS_NOT_FOUND: The known host file does not exist. The host is thus unknown. File will be created if host key is accepted. SSH_KNOWN_HOSTS_ERROR: There had been an error checking the host.
Referenced by connect_host, do_connect, ssh::Session::isServerKnown, torture_knownhosts_conflict, torture_knownhosts_new_file, torture_knownhosts_no_hostkeychecking, torture_knownhosts_other, torture_knownhosts_unknown, torture_knownhosts_write_and_verify, torture_server_hostkey_mismatch, verify_knownhost.