ssh_server_fuzzer.cpp
LIBSSH_STATIC
const char kRSAPrivateKeyPEM[][]
Referenced by write_rsa_hostkey.
static int auth_none(ssh_session session, const char *user, void *userdata)
References session_data_struct::auth_attempts, session_data_struct::authenticated, session, SSH_AUTH_PARTIAL, SSH_AUTH_SUCCESS.
Referenced by LLVMFuzzerTestOneInput.
static ssh_channel channel_open(ssh_session session, void *userdata)
References session_data_struct::channel, session, ssh_channel_new.
Referenced by LLVMFuzzerTestOneInput.
static int write_rsa_hostkey(const char *rsakey_path)
References kRSAPrivateKeyPEM.
Referenced by LLVMFuzzerTestOneInput.
int LLVMFuzzerTestOneInput(const uint8_t *data, size_t size)
References session_data_struct::auth_attempts, auth_none, session_data_struct::authenticated, session_data_struct::channel, channel_open, rc, session, ssh_server_callbacks_struct::size, SSH_AUTH_METHOD_NONE, ssh_bind_accept_fd, ssh_bind_free, ssh_bind_new, SSH_BIND_OPTIONS_RSAKEY, ssh_bind_options_set, ssh_callbacks_init, ssh_disconnect, SSH_ERROR, ssh_event_add_session, ssh_event_dopoll, ssh_event_free, ssh_event_new, ssh_free, ssh_handle_key_exchange, ssh_new, SSH_OK, ssh_set_auth_methods, ssh_server_callbacks_struct::userdata, write_rsa_hostkey.