ssh_client.c
MAXCMD
char* host
Referenced by client, opts.
char* user
Referenced by auth_gssapi_mic, auth_password, auth_password_accept, auth_password_cb, auth_pubkey_cb, auth_publickey, callback_receive_banner, client, connect_ssh, pkd_auth_pubkey_cb, socket_callback_connected, ssh_auth_response_termination, ssh_bind_poll_callback, ssh_connect_termination, ssh_handle_packets_termination, ssh_options_getopt, SSH_PACKET_CALLBACK, ssh_packet_socket_callback, ssh_pki_export_pubkey_file, ssh_publickey_to_file, ssh_socket_exception_callback, ssh_userauth_kbdint, torture_get_user_home_dir, torture_options_get_user, torture_path_expand_tilde_unix, torture_ssh_session.
char* cmds[MAXCMD][MAXCMD]
Referenced by add_cmd, batch_shell, client.
struct termios terminal
Referenced by do_cleanup, shell, ssh_channel_request_pty_size.
char* pcap_file
Referenced by opts, set_pcap.
char* proxycommand
Referenced by client, opts.
struct ssh_callbacks_struct cb
Referenced by crypto_thread_init, get_default_channel_cb, get_default_server_cb, main, setup, ssh_add_channel_callbacks, ssh_add_set_channel_callbacks, ssh_event_add_fd, ssh_packet_process, ssh_poll_new, ssh_poll_set_callback, ssh_remove_channel_callbacks, ssh_set_callbacks, ssh_set_channel_callbacks, ssh_set_log_callback, ssh_set_server_callbacks, ssh_threads_set_callbacks, torture_callbacks_exists, torture_callbacks_size, torture_packet.
ssh_channel chan
Referenced by shell, sizechanged.
int signal_delayed
Referenced by select_loop, setsignal, sigwindowchanged.
ssh_pcap_file pcap
Referenced by cleanup_pcap, main, set_pcap, ssh_pcap_file_close, ssh_pcap_file_free, ssh_pcap_file_open.
static int auth_callback(const char *prompt, char *buf, size_t len, int echo, int verify, void *userdata)
References echo, ssh_getpass.
static void add_cmd(char *cmd)
References cmds, MAXCMD.
Referenced by opts.
static void usage(void)
References endif, ssh_version.
Referenced by main, opts.
static int opts(int argc, char **argv)
References add_cmd, host, pcap_file, proxycommand, usage.
Referenced by main.
static void cfmakeraw(struct termios *termios_p)
Referenced by shell.
static void do_cleanup(int i)
References terminal.
Referenced by do_exit, shell.
static void do_exit(int i)
References do_cleanup.
Referenced by main.
static void sigwindowchanged(int i)
References signal_delayed.
Referenced by setsignal.
static void setsignal(void)
References signal_delayed, sigwindowchanged.
Referenced by shell, sizechanged.
static void sizechanged(void)
References chan, setsignal, ssh_channel_change_pty_size.
Referenced by select_loop, shell.
static void select_loop(ssh_session session, ssh_channel channel)
References rc, session, signal_delayed, sizechanged, ssh_channel_is_open, ssh_connector_free, ssh_connector_new, ssh_connector_set_in_channel, ssh_connector_set_in_fd, ssh_connector_set_out_channel, ssh_connector_set_out_fd, SSH_CONNECTOR_STDERR, SSH_CONNECTOR_STDINOUT, SSH_ERROR, ssh_event_add_connector, ssh_event_dopoll, ssh_event_free, ssh_event_new, ssh_event_remove_connector.
Referenced by batch_shell, shell.
static void shell(ssh_session session)
References cfmakeraw, chan, do_cleanup, select_loop, session, setsignal, sizechanged, ssh_channel_free, ssh_channel_new, ssh_channel_open_session, ssh_channel_request_pty, ssh_channel_request_shell, ssh_get_error, terminal.
Referenced by client, main, ssh_exec_shell, ssh_execute_command.
static void batch_shell(ssh_session session)
References buffer, cmds, MAXCMD, s, select_loop, session, ssh_channel_free, ssh_channel_new, ssh_channel_open_session, ssh_channel_request_exec, ssh_get_error.
Referenced by client.
static int client(ssh_session session)
References authenticate_console, batch_shell, cmds, host, proxycommand, session, shell, SSH_AUTH_SUCCESS, ssh_connect, ssh_get_error, ssh_get_issue_banner, SSH_OPTIONS_HOST, ssh_options_parse_config, SSH_OPTIONS_PROXYCOMMAND, ssh_options_set, SSH_OPTIONS_USER, ssh_userauth_none, user, verify_knownhost.
Referenced by main, pkd_run_tests, ssh_kex_select_methods, ssh_set_client_kex.
static void set_pcap(ssh_session session)
References pcap, pcap_file, session, SSH_ERROR, ssh_pcap_file_free, ssh_pcap_file_new, ssh_pcap_file_open, ssh_set_pcap_file.
Referenced by default_handle_session_cb, handle_kbdint_session_cb, main.
static void cleanup_pcap(void)
References pcap, ssh_pcap_file_free.
Referenced by default_handle_session_cb, handle_kbdint_session_cb, main.
int main(int argc, char **argv)
References cb, cleanup_pcap, client, do_exit, opts, session, set_pcap, ssh_callbacks_init, ssh_disconnect, ssh_finalize, ssh_free, ssh_get_error, ssh_new, ssh_options_getopt, ssh_set_callbacks, usage.