sshnetcat.c
char* host
Referenced by benchmarks_ping_latency, client, connect_host, connect_ssh, docycle, getai, main, match_hashed_host, match_hashed_hostname, match_hostname, open_tcp_socket, opts, set_opts, ssh_bind_listen, ssh_connect_host_nonblocking, ssh_dump_knownhost, ssh_hostport, ssh_is_server_known, ssh_path_expand_escape, ssh_pki_export_pubkey_file, ssh_publickey_to_file, ssh_session_export_known_hosts_entry, ssh_session_get_host_port, ssh_socket_connect, torture_options_get_host, torture_ssh_session.
const char* desthost
Referenced by forwarding, opts.
const char* port
Referenced by bind_socket, ssh::Session::cancelForward, channel_forward_cancel, channel_forward_listen, forwarding, getai, ssh::Session::listenForward, opts, pkd_init_server_fd, ssh_channel_cancel_forward, ssh_channel_listen_forward, ssh_config_parse_proxy_jump, ssh_config_parse_uri, ssh_connect_host_nonblocking, ssh_forward_cancel, ssh_forward_listen, ssh_hostport, ssh_options_getopt, ssh_socket_connect, torture_options_set_port, torture_server_port, torture_ssh_session.
static void usage(void)
Referenced by main, opts.
static int opts(int argc, char **argv)
References desthost, host, pcap_file, port, usage.
Referenced by main.
static void select_loop(ssh_session session, ssh_channel channel)
References buffer, session, ssh_channel_free, ssh_channel_is_closed, ssh_channel_is_open, ssh_channel_poll, ssh_channel_read, ssh_channel_send_eof, ssh_channel_write, SSH_EINTR, ssh_get_error, ssh_get_fd, ssh_select, ZERO_STRUCT.
Referenced by forwarding.
static void forwarding(ssh_session session)
References desthost, port, select_loop, session, ssh_channel_new, ssh_channel_open_forward, ssh_get_error.
Referenced by client.
static int client(ssh_session session)
References authenticate_console, forwarding, host, session, SSH_AUTH_SUCCESS, ssh_connect, ssh_get_error, ssh_get_issue_banner, SSH_OPTIONS_HOST, ssh_options_parse_config, ssh_options_set, ssh_userauth_none, verify_knownhost.
Referenced by main.
int main(int argc, char **argv)
References cleanup_pcap, client, opts, session, set_pcap, ssh_disconnect, ssh_finalize, ssh_free, ssh_get_error, ssh_new, ssh_options_getopt, usage.