string.c
STRING_SIZE_MAX
struct ssh_string_struct* ssh_string_new(size_t size)
Create a new SSH String object.
size The size of the string. The newly allocated string, NULL on error.
References ssh_string_struct::data, ssh_string_struct::size, STRING_SIZE_MAX.
Referenced by pki_dsa_signature_to_blob, pki_ecdsa_signature_to_blob, pki_ed25519_signature_to_blob, pki_private_key_to_pem, pki_publickey_to_blob, pki_sign_data, pki_signature_from_dsa_blob, pki_signature_from_ecdsa_blob, pki_signature_from_rsa_blob, sftp_handle_alloc, ssh_buffer_get_ssh_string, ssh_gssapi_auth_mic, ssh_make_bignum_string, ssh_pki_do_sign, ssh_pki_do_sign_agent, ssh_pki_export_signature_blob, ssh_pki_openssh_privkey_export, ssh_string_copy, ssh_string_from_char, string_new, torture_pki_ed25519_verify, torture_pki_ed25519_verify_bad, torture_session_keys.
int ssh_string_fill(struct ssh_string_struct *s, const void *data, size_t len)
Fill a string with given data. The string should be big enough.
s An allocated string to fill with data. data The data to fill the string with. len Size of data. 0 on success, < 0 on error.
References ssh_string_struct::data, s, ssh_string_len.
struct ssh_string_struct* ssh_string_from_char(const char *what)
Create a ssh string using a C string.
what The source 0-terminated C string. The newly allocated string, NULL on error with errno set. The nul byte is not copied nor counted in the ouput string.
References ssh_string_struct::data, ssh_string_new.
Referenced by pki_import_cert_buffer, pki_publickey_to_blob, sftp_reply_name, sftp_reply_names_add, sftp_reply_status, ssh_message_auth_reply_pk_ok_simple, ssh_pki_export_signature_blob, ssh_send_kex, string_from_char, thread_ssh_buffer_add_format, torture_ssh_buffer_add_format.
size_t ssh_string_len(struct ssh_string_struct *s)
Return the size of a SSH string.
s The the input SSH string. The size of the content of the string, 0 on error.
References s, ssh_string_struct::size, STRING_SIZE_MAX.
Referenced by ssh_string_burn, ssh_string_copy, ssh_string_fill, ssh_string_get_char, ssh_string_to_char.
const char* ssh_string_get_char(struct ssh_string_struct *s)
Get the the string as a C nul-terminated string.
This is only available as long as the SSH string exists. s The SSH string to get the C string from. The char pointer, NULL on error.
References s, ssh_string_len.
char* ssh_string_to_char(struct ssh_string_struct *s)
Convert a SSH string to a C nul-terminated string.
s The SSH input string. An allocated string pointer, NULL on error with errno set. If the input SSH string contains zeroes, some parts of the output string may not be readable with regular libc functions.
References s, ssh_string_len.
void ssh_string_free_char(char *s)
Deallocate a char string object.
s The string to delete.
References s, SAFE_FREE.
struct ssh_string_struct* ssh_string_copy(struct ssh_string_struct *s)
Copy a string, return a newly allocated string. The caller has to free the string.
s String to copy. Newly allocated copy of the string, NULL on error.
References s, ssh_string_len, ssh_string_new.
void ssh_string_burn(struct ssh_string_struct *s)
Destroy the data in a string so it couldn't appear in a core dump.
s The string to burn.
References explicit_bzero, s, ssh_string_len.
void* ssh_string_data(struct ssh_string_struct *s)
Get the payload of the string.
s The string to get the data from. Return the data of the string or NULL on error.
References s.
void ssh_string_free(struct ssh_string_struct *s)
Deallocate a SSH string object.
s The SSH string to delete.
References s, SAFE_FREE.