test_ssh_bind_accept_fd.c
struct options options
Referenced by connect_host, set_opts.
const char HOST[][]
Referenced by get_connection, ssh_client.
const int PORT
Referenced by get_connection, ssh_client.
int get_connection()
References HOST, PORT, rc.
Referenced by ssh_server.
void ssh_server()
References get_connection, options::server_keyfile, session, ssh_bind_accept_fd, ssh_bind_new, SSH_BIND_OPTIONS_DSAKEY, SSH_BIND_OPTIONS_RSAKEY, ssh_bind_options_set, ssh_get_error, ssh_handle_key_exchange, ssh_new, SSH_OK.
Referenced by main.
void ssh_client()
References HOST, PORT, session, ssh_connect, ssh_get_error, ssh_new, SSH_OK, SSH_OPTIONS_HOST, SSH_OPTIONS_PORT, ssh_options_set.
Referenced by main.
int main(int argc, const char *argv[])
References options::server_keyfile, ssh_client, ssh_server.