torture_connect.c
LIBSSH_STATIC
BLACKHOLE
static int sshd_setup(void **state)
References torture_setup_sshd_server.
Referenced by torture_run_tests.
static int sshd_teardown(void **state)
References torture_teardown_sshd_server.
Referenced by torture_run_tests.
static int session_setup(void **state)
References assert_return_code, BLACKHOLE, rc, s, ssh_socket_struct::session, ssh_new, SSH_OPTIONS_HOST, SSH_OPTIONS_LOG_VERBOSITY, ssh_options_set, torture_libssh_verbosity, verbosity.
Referenced by torture_run_tests.
static int session_teardown(void **state)
References s, ssh_socket_struct::session, ssh_disconnect, ssh_free.
Referenced by torture_run_tests.
static void torture_connect_nonblocking(void **state)
References assert_ssh_return_code, assert_ssh_return_code_not_equal, rc, s, ssh_socket_struct::session, session, SSH_AGAIN, ssh_connect, SSH_ERROR, SSH_OPTIONS_HOST, ssh_options_set, ssh_set_blocking, TORTURE_SSH_SERVER.
Referenced by torture_run_tests.
static void torture_connect_double(void **state)
References assert_ssh_return_code, rc, s, ssh_socket_struct::session, session, ssh_connect, ssh_disconnect, SSH_OPTIONS_HOST, ssh_options_set, TORTURE_SSH_SERVER.
Referenced by torture_run_tests.
static void torture_connect_failure(void **state)
References s, ssh_socket_struct::session, session, ssh_disconnect.
Referenced by torture_run_tests.
static void torture_connect_socket(void **state)
References assert_return_code, assert_ssh_return_code, rc, s, ssh_socket_struct::session, session, ssh_connect, SSH_OPTIONS_FD, ssh_options_set, TORTURE_SSH_SERVER.
Referenced by torture_run_tests.
int torture_run_tests(void)
References rc, session_setup, session_teardown, ssh_finalize, ssh_init, sshd_setup, sshd_teardown, torture_connect_double, torture_connect_failure, torture_connect_nonblocking, torture_connect_socket, torture_filter_tests.