torture_session.c
LIBSSH_STATIC
BUFLEN
char buffer[BUFLEN][BUFLEN]
Referenced by torture_channel_read_error.
static int sshd_setup(void **state)
References torture_setup_sshd_server.
Referenced by torture_run_tests.
static int sshd_teardown(void **state)
References torture_teardown_sshd_server.
Referenced by torture_run_tests.
static int session_setup(void **state)
References assert_return_code, rc, s, ssh_socket_struct::session, TORTURE_SSH_SERVER, torture_ssh_session, TORTURE_SSH_USER_ALICE.
Referenced by torture_run_tests.
static int session_teardown(void **state)
References s, ssh_socket_struct::session, ssh_disconnect, ssh_free.
Referenced by torture_run_tests.
static void torture_channel_read_error(void **state)
References assert_ssh_return_code, assert_ssh_return_code_equal, buffer, rc, s, ssh_socket_struct::session, session, ssh_channel_free, ssh_channel_new, ssh_channel_open_session, ssh_channel_read, ssh_channel_request_exec, SSH_ERROR, ssh_get_fd.
Referenced by torture_run_tests.
int torture_run_tests(void)
References rc, session_setup, session_teardown, ssh_finalize, ssh_init, sshd_setup, sshd_teardown, torture_channel_read_error, torture_filter_tests.