torture_server.c
LIBSSH_STATIC
TORTURE_KNOWN_HOSTS_FILE
const char template[][]
static int setup_default_server(void **state)
References server_state_st::address, ARRAY_SIZE, assert_return_code, server_state_st::auth_methods, default_handle_session_cb, server_state_st::dsa_key, server_state_st::ecdsa_key, server_state_st::ed25519_key, server_state_st::error, server_state_st::expected_password, server_state_st::expected_username, fork_run_server, server_state_st::handle_session, server_state_st::host_key, server_state_st::max_tries, server_state_st::parse_global_config, server_state_st::pcap_file, server_state_st::port, rc, server_state_st::rsa_key, s, test_server_st::ss, SSH_AUTH_METHOD_PASSWORD, SSH_AUTH_METHOD_PUBLICKEY, SSH_KEYTYPE_DSS, SSH_KEYTYPE_ECDSA_P521, SSH_KEYTYPE_ED25519, SSH_KEYTYPE_RSA, test_server_st::state, torture_get_openssh_testkey, torture_get_testkey, torture_libssh_verbosity, torture_setup_socket_dir, torture_write_file, server_state_st::verbosity, server_state_st::with_pcap.
Referenced by torture_run_tests.
static int teardown_default_server(void **state)
References free_server_state, s, SAFE_FREE, test_server_st::ss, test_server_st::state, torture_teardown_sshd_server.
Referenced by torture_run_tests.
static int session_setup(void **state)
References assert_return_code, assert_ssh_return_code, test_server_st::cwd, rc, s, ssh_socket_struct::session, ssh_new, SSH_OPTIONS_HOST, SSH_OPTIONS_LOG_VERBOSITY, SSH_OPTIONS_PROCESS_CONFIG, ssh_options_set, test_server_st::state, test_server_st::temp_dir, torture_get_current_working_dir, torture_libssh_verbosity, torture_make_temp_dir, TORTURE_SSH_SERVER, verbosity.
Referenced by torture_run_tests.
static int session_teardown(void **state)
References test_server_st::cwd, rc, s, SAFE_FREE, ssh_socket_struct::session, ssh_disconnect, ssh_free, test_server_st::state, test_server_st::temp_dir, torture_change_dir, torture_rmdirs.
Referenced by torture_run_tests.
static void torture_server_auth_none(void **state)
References rc, s, ssh_socket_struct::session, session, SSH_AUTH_DENIED, ssh_connect, SSH_ERROR, ssh_get_error_code, SSH_OK, ssh_options_set, SSH_OPTIONS_USER, SSH_REQUEST_DENIED, ssh_userauth_none, test_server_st::state, TORTURE_SSH_USER_BOB.
Referenced by torture_run_tests.
static void torture_server_auth_password(void **state)
References rc, s, ssh_socket_struct::session, session, SSH_AUTH_ERROR, SSH_AUTH_METHOD_PASSWORD, SSH_AUTH_SUCCESS, ssh_connect, ssh_get_error_code, SSH_OK, ssh_options_set, SSH_OPTIONS_USER, SSH_REQUEST_DENIED, ssh_userauth_list, ssh_userauth_none, ssh_userauth_password, SSHD_DEFAULT_PASSWORD, SSHD_DEFAULT_USER, test_server_st::state.
Referenced by torture_run_tests.
static void torture_server_auth_pubkey(void **state)
References rc, s, ssh_socket_struct::session, session, SSH_AUTH_METHOD_PUBLICKEY, SSH_AUTH_SUCCESS, ssh_connect, SSH_ERROR, ssh_get_error_code, SSH_OK, ssh_options_set, SSH_OPTIONS_USER, SSH_REQUEST_DENIED, ssh_userauth_list, ssh_userauth_none, ssh_userauth_publickey_auto, test_server_st::state, TORTURE_SSH_USER_ALICE.
Referenced by torture_run_tests.
static void torture_server_hostkey_mismatch(void **state)
References assert_ssh_return_code, rc, s, ssh_socket_struct::session, session, ssh_connect, SSH_KEYTYPE_RSA, SSH_KNOWN_HOSTS_OK, SSH_OPTIONS_HOSTKEYS, SSH_OPTIONS_KNOWNHOSTS, ssh_options_set, SSH_OPTIONS_USER, ssh_session_is_known_server, SSHD_DEFAULT_USER, test_server_st::state, torture_get_testkey_pub, TORTURE_KNOWN_HOSTS_FILE.
Referenced by torture_run_tests.
static void torture_server_unknown_global_request(void **state)
References assert_ssh_return_code, assert_ssh_return_code_equal, rc, s, ssh_socket_struct::session, session, SSH_AUTH_SUCCESS, ssh_channel_close, ssh_channel_new, ssh_channel_open_session, ssh_connect, SSH_ERROR, ssh_global_request, SSH_OK, ssh_options_set, SSH_OPTIONS_USER, ssh_userauth_password, SSHD_DEFAULT_PASSWORD, SSHD_DEFAULT_USER, test_server_st::state.
Referenced by torture_run_tests.
int torture_run_tests(void)
References rc, session_setup, session_teardown, setup_default_server, ssh_finalize, ssh_init, teardown_default_server, torture_filter_tests, torture_server_auth_none, torture_server_auth_password, torture_server_auth_pubkey, torture_server_hostkey_mismatch, torture_server_unknown_global_request.