torture_hostkey.c
LIBSSH_STATIC
static int sshd_setup(void **state)
References torture_setup_sshd_server.
Referenced by torture_run_tests.
static int sshd_teardown(void **state)
References torture_teardown_sshd_server.
Referenced by torture_run_tests.
static int session_setup(void **state)
References assert_return_code, assert_ssh_return_code, rc, s, ssh_socket_struct::session, ssh_new, SSH_OPTIONS_HOST, SSH_OPTIONS_LOG_VERBOSITY, ssh_options_set, torture_libssh_verbosity, TORTURE_SSH_SERVER, verbosity.
Referenced by torture_run_tests.
static int session_teardown(void **state)
References s, ssh_socket_struct::session, ssh_disconnect, ssh_free.
Referenced by torture_run_tests.
static void torture_hostkey_rsa(void **state)
References assert_ssh_return_code, rc, s, ssh_socket_struct::session, session, ssh_connect, ssh_disconnect, SSH_OPTIONS_HOSTKEYS, ssh_options_set.
Referenced by torture_run_tests.
static void torture_hostkey_ed25519(void **state)
References assert_ssh_return_code, rc, s, ssh_socket_struct::session, session, ssh_connect, ssh_disconnect, SSH_OPTIONS_HOSTKEYS, ssh_options_set.
Referenced by torture_run_tests.
static void torture_hostkey_rsa_sha256(void **state)
References assert_ssh_return_code, rc, s, ssh_socket_struct::session, session, ssh_connect, ssh_disconnect, SSH_OPTIONS_HOSTKEYS, ssh_options_set.
Referenced by torture_run_tests.
static void torture_hostkey_rsa_sha512(void **state)
References assert_ssh_return_code, rc, s, ssh_socket_struct::session, session, ssh_connect, ssh_disconnect, SSH_OPTIONS_HOSTKEYS, ssh_options_set.
Referenced by torture_run_tests.
int torture_run_tests(void)
References rc, session_setup, session_teardown, ssh_finalize, ssh_init, sshd_setup, sshd_teardown, torture_filter_tests, torture_hostkey_ed25519, torture_hostkey_rsa, torture_hostkey_rsa_sha256, torture_hostkey_rsa_sha512.