torture_forward.c
LIBSSH_STATIC
static int sshd_setup(void **state)
References torture_setup_sshd_server.
Referenced by torture_run_tests.
static int sshd_teardown(void **state)
References torture_teardown_sshd_server.
Referenced by torture_run_tests.
static int session_setup(void **state)
References assert_return_code, rc, s, ssh_socket_struct::session, TORTURE_SSH_SERVER, torture_ssh_session, TORTURE_SSH_USER_ALICE.
Referenced by torture_run_tests.
static int session_teardown(void **state)
References s, ssh_socket_struct::session, ssh_disconnect, ssh_free.
Referenced by torture_run_tests.
static void torture_ssh_forward(void **state)
References assert_ssh_return_code, rc, s, ssh_socket_struct::session, session, ssh_channel_accept_forward, ssh_channel_close, ssh_channel_listen_forward, ssh_channel_send_eof, SSH_LOG_TRACE, SSH_OPTIONS_LOG_VERBOSITY, ssh_options_set, verbosity.
Referenced by torture_run_tests.
int torture_run_tests(void)
References rc, session_setup, session_teardown, ssh_finalize, ssh_init, sshd_setup, sshd_teardown, torture_filter_tests, torture_ssh_forward.