torture_client_global_requests.c
LIBSSH_STATIC
static int sshd_setup(void **state)
References torture_setup_sshd_server.
Referenced by torture_run_tests.
static int sshd_teardown(void **state)
References torture_teardown_sshd_server.
Referenced by torture_run_tests.
static int session_setup(void **state)
References assert_return_code, assert_ssh_return_code, rc, s, ssh_socket_struct::session, ssh_new, SSH_OPTIONS_HOST, SSH_OPTIONS_LOG_VERBOSITY, SSH_OPTIONS_PROCESS_CONFIG, ssh_options_set, torture_libssh_verbosity, TORTURE_SSH_SERVER, verbosity.
Referenced by torture_run_tests.
static int session_teardown(void **state)
References s, ssh_socket_struct::session, ssh_disconnect, ssh_free.
Referenced by torture_run_tests.
static int authenticate(void **state)
References rc, s, ssh_socket_struct::session, session, SSH_AUTH_SUCCESS, ssh_connect, SSH_OK, ssh_options_set, SSH_OPTIONS_USER, ssh_userauth_password, TORTURE_SSH_USER_BOB, TORTURE_SSH_USER_BOB_PASSWORD.
Referenced by torture_unknown_request.
static void torture_unknown_request(void **state)
References assert_ssh_return_code, assert_ssh_return_code_equal, authenticate, rc, s, ssh_socket_struct::session, session, ssh_channel_close, ssh_channel_new, ssh_channel_open_session, SSH_ERROR, ssh_global_request.
Referenced by torture_run_tests.
int torture_run_tests(void)
References rc, session_setup, session_teardown, ssh_finalize, ssh_init, sshd_setup, sshd_teardown, torture_filter_tests, torture_unknown_request.