torture_knownhosts_verify.c
LIBSSH_STATIC
TMP_FILE_TEMPLATE
BAD_RSA
KNOWN_HOST_ENTRY_ECDSA
KNOWN_HOST_ENTRY_ED25519
const char template[][]
static int sshd_group_setup(void **state)
References torture_setup_sshd_server.
Referenced by torture_run_tests.
static int sshd_group_teardown(void **state)
References torture_teardown_sshd_server.
Referenced by torture_run_tests.
static int session_setup(void **state)
References assert_return_code, assert_ssh_return_code, rc, s, ssh_socket_struct::session, ssh_new, SSH_OPTIONS_HOST, SSH_OPTIONS_LOG_VERBOSITY, SSH_OPTIONS_PROCESS_CONFIG, ssh_options_set, SSH_OPTIONS_USER, torture_libssh_verbosity, TORTURE_SSH_SERVER, TORTURE_SSH_USER_ALICE, verbosity.
Referenced by torture_run_tests.
static int session_teardown(void **state)
References s, ssh_socket_struct::session, ssh_disconnect, ssh_free.
Referenced by torture_run_tests.
static void torture_knownhosts_export(void **state)
References assert_ssh_return_code, KNOWN_HOST_ENTRY_ECDSA, KNOWN_HOST_ENTRY_ED25519, rc, s, SAFE_FREE, ssh_socket_struct::session, session, ssh_connect, ssh_session_export_known_hosts_entry.
Referenced by torture_run_tests.
static void torture_knownhosts_write_and_verify(void **state)
References assert_ssh_return_code, rc, s, ssh_socket_struct::session, session, ssh_connect, SSH_KNOWN_HOSTS_OK, ssh_session_is_known_server, ssh_session_update_known_hosts.
Referenced by torture_run_tests.
static void torture_knownhosts_precheck(void **state)
References assert_ssh_return_code, rc, s, ssh_socket_struct::session, session, ssh_iterator_value, SSH_KEYTYPE_ECDSA_P521, SSH_KEYTYPE_ED25519, SSH_KEYTYPE_RSA, ssh_known_hosts_get_algorithms, ssh_list_count, ssh_list_free, ssh_list_get_iterator, ssh_list_remove, SSH_OPTIONS_KNOWNHOSTS, ssh_options_set, TMP_FILE_TEMPLATE, torture_create_temp_file, torture_get_testkey_pub.
Referenced by torture_run_tests.
static void torture_knownhosts_duplicate(void **state)
References assert_ssh_return_code, rc, s, ssh_socket_struct::session, session, ssh_iterator_value, SSH_KEYTYPE_RSA, ssh_known_hosts_get_algorithms, ssh_list_count, ssh_list_free, ssh_list_get_iterator, SSH_OPTIONS_KNOWNHOSTS, ssh_options_set, TMP_FILE_TEMPLATE, torture_create_temp_file, torture_get_testkey_pub.
Referenced by torture_run_tests.
static void torture_knownhosts_other(void **state)
References assert_ssh_return_code, rc, s, ssh_socket_struct::session, session, ssh_connect, SSH_KEYTYPE_RSA, SSH_KNOWN_HOSTS_OTHER, SSH_OPTIONS_HOSTKEYS, SSH_OPTIONS_KNOWNHOSTS, ssh_options_set, ssh_session_is_known_server, TMP_FILE_TEMPLATE, torture_create_temp_file, torture_get_testkey_pub.
Referenced by torture_run_tests.
static void torture_knownhosts_unknown(void **state)
References assert_ssh_return_code, rc, s, ssh_socket_struct::session, session, ssh_connect, ssh_disconnect, ssh_free, SSH_KNOWN_HOSTS_OK, SSH_KNOWN_HOSTS_UNKNOWN, ssh_new, SSH_OPTIONS_HOST, SSH_OPTIONS_HOSTKEYS, SSH_OPTIONS_KNOWNHOSTS, ssh_options_set, SSH_OPTIONS_USER, ssh_session_is_known_server, ssh_session_update_known_hosts, TMP_FILE_TEMPLATE, torture_create_temp_file, TORTURE_SSH_SERVER, TORTURE_SSH_USER_ALICE.
Referenced by torture_run_tests.
static void torture_knownhosts_conflict(void **state)
References assert_ssh_return_code, BAD_RSA, rc, s, ssh_socket_struct::session, session, ssh_connect, ssh_disconnect, ssh_free, SSH_KNOWN_HOSTS_CHANGED, SSH_KNOWN_HOSTS_OK, ssh_new, SSH_OPTIONS_HOST, SSH_OPTIONS_HOSTKEYS, SSH_OPTIONS_KNOWNHOSTS, ssh_options_set, ssh_session_is_known_server, ssh_session_update_known_hosts, TMP_FILE_TEMPLATE, torture_create_temp_file, TORTURE_SSH_SERVER.
Referenced by torture_run_tests.
static void torture_knownhosts_new_file(void **state)
References assert_return_code, assert_ssh_return_code, rc, s, SAFE_FREE, ssh_socket_struct::session, session, ssh_connect, SSH_KNOWN_HOSTS_OK, SSH_OPTIONS_KNOWNHOSTS, ssh_options_set, ssh_session_is_known_server, ssh_session_update_known_hosts, torture_make_temp_dir, torture_rmdirs.
Referenced by torture_run_tests.
int torture_run_tests(void)
References rc, session_setup, session_teardown, ssh_finalize, ssh_init, sshd_group_setup, sshd_group_teardown, torture_filter_tests, torture_knownhosts_conflict, torture_knownhosts_duplicate, torture_knownhosts_export, torture_knownhosts_new_file, torture_knownhosts_other, torture_knownhosts_precheck, torture_knownhosts_unknown, torture_knownhosts_write_and_verify.