torture_scp.c
LIBSSH_STATIC
BUF_SIZE
TEMPLATE
static int sshd_setup(void **state)
References scp_st::s, s, torture_setup_sshd_server.
Referenced by torture_run_tests.
static int sshd_teardown(void **state)
References scp_st::s, SAFE_FREE, torture_teardown_sshd_server.
Referenced by torture_run_tests.
static int session_setup(void **state)
References assert_return_code, rc, scp_st::s, s, ssh_socket_struct::session, ssh_basename, TEMPLATE, scp_st::tmp_dir, scp_st::tmp_dir_basename, torture_make_temp_dir, TORTURE_SSH_SERVER, torture_ssh_session, TORTURE_SSH_USER_ALICE.
Referenced by torture_run_tests.
static int session_teardown(void **state)
References scp_st::s, s, SAFE_FREE, ssh_socket_struct::session, ssh_disconnect, ssh_free, scp_st::tmp_dir, scp_st::tmp_dir_basename, torture_rmdirs.
Referenced by torture_run_tests.
static void torture_scp_upload(void **state)
References assert_ssh_return_code, BUF_SIZE, rc, scp_st::s, s, ssh_socket_struct::session, session, ssh_scp_close, ssh_scp_free, ssh_scp_init, ssh_scp_new, ssh_scp_push_file, SSH_SCP_WRITE, ssh_scp_write, scp_st::tmp_dir, scp_st::tmp_dir_basename.
Referenced by torture_run_tests.
static void torture_scp_upload_recursive(void **state)
References assert_ssh_return_code, BUF_SIZE, rc, scp_st::s, s, ssh_socket_struct::session, session, ssh_scp_close, ssh_scp_free, ssh_scp_init, ssh_scp_leave_directory, ssh_scp_new, ssh_scp_push_directory, ssh_scp_push_file, SSH_SCP_RECURSIVE, SSH_SCP_WRITE, ssh_scp_write, scp_st::tmp_dir, scp_st::tmp_dir_basename.
Referenced by torture_run_tests.
static void torture_scp_download(void **state)
References assert_ssh_return_code, BUF_SIZE, rc, scp_st::s, s, ssh_socket_struct::session, session, ssh_scp_accept_request, ssh_scp_close, ssh_scp_free, ssh_scp_init, ssh_scp_new, ssh_scp_pull_request, SSH_SCP_READ, ssh_scp_read, ssh_scp_request_get_filename, ssh_scp_request_get_permissions, ssh_scp_request_get_size, SSH_SCP_REQUEST_NEWFILE, scp_st::tmp_dir, scp_st::tmp_dir_basename.
Referenced by torture_run_tests.
static void torture_scp_download_recursive(void **state)
References assert_ssh_return_code, BUF_SIZE, rc, scp_st::s, s, ssh_socket_struct::session, session, ssh_scp_accept_request, ssh_scp_close, ssh_scp_free, ssh_scp_init, ssh_scp_new, ssh_scp_pull_request, SSH_SCP_READ, ssh_scp_read, SSH_SCP_RECURSIVE, SSH_SCP_REQUEST_ENDDIR, SSH_SCP_REQUEST_EOF, ssh_scp_request_get_filename, ssh_scp_request_get_permissions, ssh_scp_request_get_size, SSH_SCP_REQUEST_NEWDIR, SSH_SCP_REQUEST_NEWFILE, scp_st::tmp_dir, scp_st::tmp_dir_basename.
Referenced by torture_run_tests.
static void torture_scp_upload_newline(void **state)
References assert_ssh_return_code, BUF_SIZE, rc, scp_st::s, s, ssh_socket_struct::session, session, ssh_scp_close, ssh_scp_free, ssh_scp_init, ssh_scp_leave_directory, ssh_scp_new, ssh_scp_push_directory, ssh_scp_push_file, SSH_SCP_RECURSIVE, SSH_SCP_WRITE, ssh_scp_write, scp_st::tmp_dir, scp_st::tmp_dir_basename.
Referenced by torture_run_tests.
int torture_run_tests(void)
References rc, session_setup, session_teardown, ssh_finalize, ssh_init, sshd_setup, sshd_teardown, torture_filter_tests, torture_scp_download, torture_scp_download_recursive, torture_scp_upload, torture_scp_upload_newline, torture_scp_upload_recursive.