torture_rekey.c
LIBSSH_STATIC
static int sshd_setup(void **state)
References torture_setup_sshd_server.
Referenced by torture_run_tests.
static int sshd_teardown(void **state)
References torture_teardown_sshd_server.
Referenced by torture_run_tests.
static int session_setup(void **state)
References assert_return_code, assert_ssh_return_code, rc, s, ssh_socket_struct::session, ssh_new, SSH_OK, SSH_OPTIONS_HOST, SSH_OPTIONS_LOG_VERBOSITY, SSH_OPTIONS_PROCESS_CONFIG, ssh_options_set, SSH_OPTIONS_USER, torture_libssh_verbosity, TORTURE_SSH_SERVER, TORTURE_SSH_USER_ALICE, verbosity.
Referenced by torture_run_tests.
static int session_teardown(void **state)
References s, ssh_socket_struct::session, ssh_free.
Referenced by torture_run_tests.
static void torture_rekey_default(void **state)
References assert_ssh_return_code, ssh_cipher_struct::blocksize, ssh_session_struct::current_crypto, ssh_crypto_struct::in_cipher, ssh_cipher_struct::max_blocks, ssh_crypto_struct::out_cipher, rc, s, ssh_socket_struct::session, ssh_connect, ssh_disconnect, SSH_OPTIONS_CIPHERS_C_S, SSH_OPTIONS_CIPHERS_S_C, ssh_options_set.
Referenced by torture_run_tests.
static void torture_rekey_send(void **state)
References assert_ssh_return_code, ssh_cipher_struct::blocksize, ssh_session_struct::current_crypto, ssh_crypto_struct::digest_len, ssh_crypto_struct::in_cipher, ssh_cipher_struct::max_blocks, ssh_crypto_struct::out_cipher, ssh_cipher_struct::packets, rc, ssh_session_struct::recv_seq, s, ssh_crypto_struct::secret_hash, ssh_session_struct::send_seq, ssh_socket_struct::session, SSH_AUTH_METHOD_PUBLICKEY, SSH_AUTH_SUCCESS, ssh_connect, ssh_disconnect, SSH_ERROR, ssh_get_error_code, ssh_handle_packets, SSH_OPTIONS_REKEY_DATA, ssh_options_set, SSH_REQUEST_DENIED, ssh_send_ignore, ssh_userauth_list, ssh_userauth_none, ssh_userauth_publickey_auto.
Referenced by torture_run_tests.
static void torture_rekey_time(void **state)
References assert_ssh_return_code, ssh_session_struct::current_crypto, ssh_crypto_struct::digest_len, ssh_session_struct::opts, rc, ssh_session_struct::rekey_time, s, ssh_crypto_struct::secret_hash, ssh_socket_struct::session, SSH_AUTH_METHOD_PUBLICKEY, SSH_AUTH_SUCCESS, ssh_connect, ssh_disconnect, SSH_ERROR, ssh_get_error_code, ssh_handle_packets, SSH_OPTIONS_REKEY_TIME, ssh_options_set, SSH_REQUEST_DENIED, ssh_send_ignore, ssh_userauth_list, ssh_userauth_none, ssh_userauth_publickey_auto, time.
Referenced by torture_run_tests.
static void torture_rekey_server_send(void **state)
References assert_ssh_return_code, ssh_session_struct::current_crypto, ssh_crypto_struct::digest_len, rc, s, ssh_crypto_struct::secret_hash, ssh_socket_struct::session, SSH_AUTH_METHOD_PUBLICKEY, SSH_AUTH_SUCCESS, ssh_connect, ssh_disconnect, SSH_ERROR, ssh_get_error_code, ssh_handle_packets, SSH_REQUEST_DENIED, ssh_send_ignore, ssh_userauth_list, ssh_userauth_none, ssh_userauth_publickey_auto, torture_update_sshd_config.
Referenced by torture_run_tests.
int torture_run_tests(void)
References rc, session_setup, session_teardown, ssh_finalize, ssh_init, sshd_setup, sshd_teardown, torture_filter_tests, torture_rekey_default, torture_rekey_send, torture_rekey_server_send, torture_rekey_time.