torture_server_auth_kbdint.c
LIBSSH_STATIC
TORTURE_KNOWN_HOSTS_FILE
@15
static int process_stdout(socket_t fd, int revents, void *userdata)
References BUF_SIZE, POLLIN, ssh_channel_write.
Referenced by handle_kbdint_session_cb.
static int process_stderr(socket_t fd, int revents, void *userdata)
References BUF_SIZE, POLLIN, ssh_channel_write_stderr.
Referenced by handle_kbdint_session_cb.
static int authenticate_kbdint(ssh_session session, ssh_message message, void *userdata)
References session_data_st::extra_data, FAILED, instruction, MORE, name, session_data_st::password, rc, session, ssh_message_auth_interactive_request, ssh_userauth_kbdint_getanswer, ssh_userauth_kbdint_getnanswers, SUCCESS, session_data_st::username.
Referenced by authenticate_callback.
static int authenticate_callback(ssh_session session, ssh_message message, void *userdata)
References authenticate_kbdint, session_data_st::extra_data, MORE, rc, session, SSH_AUTH_METHOD_INTERACTIVE, ssh_message_auth_reply_success, ssh_message_auth_set_methods, ssh_message_free, ssh_message_subtype, ssh_message_type, SSH_REQUEST_AUTH, SUCCESS.
Referenced by handle_kbdint_session_cb.
static void handle_kbdint_session_cb(ssh_event event, ssh_session session, struct server_state_st *state)
References session_data_st::auth_attempts, authenticate_callback, session_data_st::authenticated, session_data_st::channel, channel_cb, channel_data_st::child_stderr, channel_data_st::child_stdin, channel_data_st::child_stdout, cleanup_pcap, channel_data_st::event, get_default_channel_cb, get_default_server_cb, server_state_st::max_tries, server_state_st::pcap_file, channel_data_st::pid, POLLIN, process_stderr, process_stdout, channel_data_st::pty_master, rc, session, SESSION_END, set_pcap, SSH_AUTH_METHOD_INTERACTIVE, ssh_callbacks_init, ssh_channel_close, ssh_channel_is_open, ssh_channel_request_send_exit_status, ssh_channel_send_eof, SSH_ERROR, ssh_event_add_fd, ssh_event_add_session, ssh_event_dopoll, ssh_event_remove_fd, ssh_get_error, ssh_get_status, ssh_handle_key_exchange, SSH_OK, ssh_set_auth_methods, ssh_set_channel_callbacks, ssh_set_message_callback, ssh_set_server_callbacks, TORTURE_SSH_USER_BOB, TORTURE_SSH_USER_BOB_PASSWORD, ssh_server_callbacks_struct::userdata, ssh_channel_callbacks_struct::userdata.
Referenced by setup_kbdint_server.
static int setup_kbdint_server(void **state)
References server_state_st::address, assert_return_code, server_state_st::error, fork_run_server, handle_kbdint_session_cb, server_state_st::handle_session, server_state_st::host_key, server_state_st::max_tries, server_state_st::pcap_file, server_state_st::port, rc, test_server_st::rsa_hostkey, s, test_server_st::ss, SSH_KEYTYPE_RSA, test_server_st::state, torture_get_openssh_testkey, torture_libssh_verbosity, torture_setup_socket_dir, torture_write_file, server_state_st::verbosity, server_state_st::with_pcap.
Referenced by torture_run_tests.
static int teardown_kbdint_server(void **state)
References free_server_state, s, SAFE_FREE, test_server_st::ss, test_server_st::state, torture_teardown_sshd_server.
Referenced by torture_run_tests.
static int session_setup(void **state)
References assert_return_code, assert_ssh_return_code, rc, s, ssh_socket_struct::session, ssh_new, SSH_OPTIONS_HOST, SSH_OPTIONS_LOG_VERBOSITY, SSH_OPTIONS_PROCESS_CONFIG, ssh_options_set, test_server_st::state, torture_libssh_verbosity, TORTURE_SSH_SERVER, verbosity.
Referenced by torture_run_tests.
static int session_teardown(void **state)
References s, ssh_socket_struct::session, ssh_disconnect, ssh_free, test_server_st::state.
Referenced by torture_run_tests.
static void torture_server_auth_kbdint(void **state)
References assert_ssh_return_code, rc, s, ssh_socket_struct::session, session, SSH_AUTH_INFO, SSH_AUTH_METHOD_INTERACTIVE, SSH_AUTH_SUCCESS, ssh_connect, SSH_ERROR, ssh_get_error_code, ssh_options_set, SSH_OPTIONS_USER, SSH_REQUEST_DENIED, ssh_userauth_kbdint, ssh_userauth_kbdint_getnprompts, ssh_userauth_kbdint_setanswer, ssh_userauth_list, ssh_userauth_none, test_server_st::state, TORTURE_SSH_USER_BOB, TORTURE_SSH_USER_BOB_PASSWORD.
Referenced by torture_run_tests.
int torture_run_tests(void)
References rc, session_setup, session_teardown, setup_kbdint_server, ssh_finalize, ssh_init, teardown_kbdint_server, torture_filter_tests, torture_server_auth_kbdint.